### ISSUE TITLE
enhancement: allow Java8 lambda steps to throw checked Exceptions

### ISSUE THREAD

**Issue by RichardBradley** [cucumber/cucumber-jvm#1001]
Any steps declared with the Java8 lambda syntax may not throw checked Exceptions:

```
    // Compile error: Unhandled exception: IOException
    Given("^I have a file with some text$", () -> {
        Files.write("my setup", new File("example.txt"), Charsets.UTF_8);
    });
```

It would be more convenient for developers if they were declared as "throws Exception"; the runtime machinery all copes with it fine, and it avoids lots of "`catch(e) { throw new RuntimeException(e) }`" noise.

This should be a simple change to the interface declarations in [`StepdefBody`](https://github.com/cucumber/cucumber-jvm/blob/0aecc4d3e4c15fc34b63f848043deba2c230e35f/java/src/main/java/cucumber/api/java8/StepdefBody.java#L5)

**Comment by leodutra** [comment]
Any temporary replacement for this? Any special RuntimeException to be thrown?

**Comment by RichardBradley** [comment]
There is an easy workaround for now: catch all your checked exceptions and rethrow as `RuntimeException`:

    Given("^I have a file with some text$", () -> {
        try {
            Files.write("my setup", new File("example.txt"), Charsets.UTF_8);
        } catch(e) { 
            throw new RuntimeException(e) 
        }
    });

**Comment by christianhujer** [comment]
I guess the solution is to add `throws Exception` to all `accept()` methods of the `A*` interfaces in `src/main/java/cucumber/api/java8/StepdefBody.java`. And I agree it would remove a hell lot of noise.

**Comment by renannprado** [comment]
any news on this?

**Comment by RichardBradley** [comment]
No-one has stepped up to implement it yet. I would hope that a well written PR fix would be accepted, but I can't speak for the project maintainers. I don't plan to implement it myself in the short / medium term.

**Comment by RichardBradley** [comment]
Thanks!
