### ISSUE TITLE
Tests fail to generate report, causing a wide failure

### ISSUE THREAD

**Issue by omerxx** [cucumber/cucumber-jvm#1006]
Hi,

We're running approx. 4000 tests every 1 hour, from time to time we get an exception probably based on the report builder jar not extracted correctly. (cucumber-html V.0.2.3)
This is the exception: `cucumber.runtime.CucumberException: Couldn't find /cucumber/formatter/formatter.js. Is cucumber-html on your classpath? Make sure you have the right version.`
This only happens occasionally which leads us to believe the problem is high load on the automation machine. (The path exists 100% in our classpath - this has been checked thoroughly over and over)

Would it be possible for you to add an option to let a test finish it's run even if the report cannot be built?

**Comment by anandxp** [comment]
@omerxx Hi Omer .. Any idea regarding this issue. I am also getting the same issue.

**Comment by omerxx** [comment]
@anandxp Not really. I've scaled the infra to 4 hubs each orchestrating tests to 15 nodes.
After a long debug my main conclusion is that this was a result of load the hub could not hold.
