### ISSUE TITLE
JUnit runner does not distinguish between pending and ignored via Assume

### ISSUE THREAD

**Issue by RichardBradley** [cucumber/cucumber-jvm#1007]
JUnit tests can be marked as "ignored" via the [Assume](http://junit.sourceforge.net/javadoc/org/junit/Assume.html) API. If an assumption fails, then JUnit will mark the test as "ignored". Tests in this state do not count as failures.

Cucumber tests can be in "pending" state if they have undefined steps. Tests in this state should count as a failure if "strict" is set.

The `cucumber.api.junit.Cucumber` JUnit test runner doies not distinguish between these two cases; both are either failures or not according to the "strict" setting.

I believe that the "strict setting should make "pending" tests a failure, but not make "ignored" tests a failure.

**Comment by RichardBradley** [comment]
See #359 -- I think it's wrong to treat "Assume" the same as "pending": the former means "ignore without failing" whereas the latter means "fail if strict or ignore if not strict".

**Comment by mpkorstanje** [comment]
This will be partially resolved in version 2.0.0 once #1142 merged.

This won't cause tests to be marked as `SKIPPED` in Cucumber. They'll be marked as `PENDING` but when non-strict is enabled but these count as skipped in JUnit terms.

> I think it's wrong to treat "Assume" the same as "pending": the former means "ignore without failing" whereas the latter means "fail if strict or ignore if not strict".

@brasmusson how do you feel about mapping `AssumptionViolatedException` to `SKIPPED`?
