### ISSUE TITLE
How to run JUnit-Selenium-Cucumber-Android-Appium tests in parallel ?

### ISSUE THREAD

**Issue by ajit-jadhav** [cucumber/cucumber-jvm#1008]
Please let me know How to run JUnit-Selenium-Cucumber-Android-Appium tests in parallel.
Thanks.

**Comment by brasmusson** [comment]
This is an issue tracker, please ask your question in a [support forum](https://cucumber.io/support)

**Comment by ajit-jadhav** [comment]
ok.
