### ISSUE TITLE
Tags missing from JUnit reporter and formatter

### ISSUE THREAD

**Issue by jakub-bochenski** [cucumber/cucumber-jvm#1012]
I can't seem to find the tags anywhere in the JUnit output -- regardless weather I run it with JUnit runner or use the plugin `junit:target/cucumber-junit.xml`

**Comment by brasmusson** [comment]
I don't think the JUnit output ever have been intended to include the whole feature file (the pretty and html formatter are much more feature file oriented), but rather the test cases executed and their result. There are certainly many things in the feature file missing in the JUnit output, descriptions, comment, and yes also tags. Why would we want to include tags in the JUnit output?

**Comment by jakub-bochenski** [comment]
JUnit XML is a format used much more widely than JUnit itself. It's kind of funny since the format itself is an Ant artifact and there isn't even any definite spec.

I think that giving the ability to add arbitrary content to the report via tags would be generally useful, given the amount of tools that consume the format. 

Comments also seem like a good addition, but for my  particular case I prefer tags. I need to feed a linked ticket id to a feature in order to pass the report to Zephyr.

**Comment by aslakhellesoy** [comment]
Please add an example of what you would like the generated XML to look like.

**Comment by aslakhellesoy** [comment]
Never mind my last comment - just spotted the PR
