### ISSUE TITLE
Android: Multiple Cucumber runners

### ISSUE THREAD

**Issue by kirillzh** [cucumber/cucumber-jvm#1017]
Is it possible to have multiple test runners with unique `CucumberOptions`?

For example I have two runners
`RegressionTestsRunner.java`:
```java
@RunWith(Cucumber.class)
@CucumberOptions(
        features = "features/regression",
        tags = "~@wip"
)
public class RegressionTestsRunner {
}
```
and `SmokeTestsRunner.java`
```java
@RunWith(Cucumber.class)
@CucumberOptions(
        features = "features/smoke",
        tags = "~@wip"
)
public class SmokeTestsRunner {
}
```

But in some reason Cucumber runs first runner it finds. If I run `SmokeTestsRunner`, `RegressionTestsRunner` will be ran:
```
Found CucumberOptions in class com.example.app.stepDefinitions.RegressionTestsRunner
```

**Note:** works in `java` project

**Comment by aslakhellesoy** [comment]
It's JUnit that runs the Runner class (which is a JUnit test), which in turn runs Cucumber. You have to tell JUnit what tests to run.

**Comment by kirillzh** [comment]
Thanks for replying, @aslakhellesoy.

Does Cucumber JVM has profiles like Ruby does (or something similar)?
I'm trying to make it easy to run set of tests (smoke, regression, maybe some feature, etc.) from IDE.

Thank you.

**Comment by smallstepstoday** [comment]
I agree with the OP on this issue: for Android there is the need to test portrait, landscape, free, paid, etc. Multiple configurations and multiple different options. Having a single TestCase that drives the whole of the Cucumber testing severely limits the usefulness of the framework in my opinion.

For Android, the following routine in [CucumberExecutor](https://github.com/cucumber/cucumber-jvm/blob/master/android/src/main/java/cucumber/runtime/android/CucumberExecutor.java) is responsible for retrieving the `@CucumberOptions` annotation:

```
    private RuntimeOptions createRuntimeOptions(final Context context) {
        for (final Class<?> clazz : classFinder.getDescendants(Object.class, context.getPackageName())) {
            if (clazz.isAnnotationPresent(CucumberOptions.class)) {
                Log.d(TAG, "Found CucumberOptions in class " + clazz.getName());
                final RuntimeOptionsFactory factory = new RuntimeOptionsFactory(clazz);
                return factory.create();
            }
        }

        throw new CucumberException("No CucumberOptions annotation");
    }
```
It is clear that it is not checking the arguments at all, making it impossible to "tell JUnit what tests to run." :) The routine is simply returning the first `TestCase` it finds in the appropriate package.

If cucumber-android respected the arguments passed in, one would be able to define multiple test cases, each with separate `@CucumberOptions` annotations. This would solve the issue, yes?
