### ISSUE TITLE
Call a step within a step definition

### ISSUE THREAD

**Issue by danyg** [cucumber/cucumber-jvm#1020]
Hi, I know this is a sensible topic in the community, I read you don't want to use gherkin language for programmatic proposes.

I'm asking something different here, Would something like this be possible?

```java
@Given("^A user in the profile section$")
public static void openProfile() {

	Cucumber.runStep("Given a user with [no important privileges] in the Web");
	Cucumber.runStep("And the user open the settings section");
	Cucumber.runStep("And the user open the profile section");

}
```

I know the recommendation here is to call the methods of those steps directly, but think about this, what happen if the day of tomorrow, I want to change that implementation (and in my current project we will) but we won't (of course) change the BDD, what then? should I refactor all the places that are calling the old methods?

In this way you can decouple the implementation from the wordings, and create macro steps clear enough, from all the points of view, to understand what the tests are doing.

What do you think guys?
Is it possible to do this with the current API in some how?

**Comment by kirillzh** [comment]
You can create instance of steps class and execute any steps like so:

```java
public class FooSteps {
  @Given("^Foo step$")
  public void fooStep() {
    System.out.println("This is a foo step");
  }
}
```

```java
public class BarSteps {
  @Given("^Bar step$")
  public void barStep() {
    new FooSteps().fooStep();
  }
}
```

**Comment by brasmusson** [comment]
No it is not possible to call steps from step definitions.

I close this issue since this is an issue tracker, please ask your question in a [support forum](https://cucumber.io/support).

**Comment by danyg** [comment]
@brasmusson this is a request, is a request a valid issue for you mate?

**Comment by brasmusson** [comment]
> What do you think guys?
> Is it possible to do this with the current API in some how?

@danyg I'am sorry. The wording made me interpret it as a question. You could have reopened the issue to correct me.
