### ISSUE TITLE
[REQUEST] Call a step within a step definition

### ISSUE THREAD

**Issue by danyg** [cucumber/cucumber-jvm#1022]
As expressed in #1020 

I would like to do this

@Given("^A user in the profile section$")
public static void openProfile() {

    Cucumber.runStep("Given a user with [no important privileges] in the Web");
    Cucumber.runStep("And the user open the settings section");
    Cucumber.runStep("And the user open the profile section");

}

It will help a lot to decouple wording from implementation, and let the Developer of a suite to reuse wording without needing of couple the implementations of macro steps to the previous ones.

**Comment by brasmusson** [comment]
Cucumber-Ruby has a method of calling steps from steps. However, practical experience have led people to realize that they are best avioded, see for instance https://groups.google.com/d/msg/cukes/9QXe_mZv6kU/mVA5WzgmCQAJ

**Comment by aslakhellesoy** [comment]
Sorry, we're not going to add this feature.
