### ISSUE TITLE
Spring issue when step definitions file is too deep in packages

### ISSUE THREAD

**Issue by a-yumashin** [cucumber/cucumber-jvm#1023]
**Cucumber-jvm version:** 1.2.4
**Modules listed in pom.xml (all v.1.2.4):** Cucumber-java, Cucumber-jvm, Cucumber-junit, Cucumber-spring, Cucumber-core.
**Java:** 1.7.0_80
**IDE:** IntelliJ IDEA 2016.1.2, CE
**Spring:** 3.2.8

**Maven project structure:**
```
MyAutotestsProject
    src
        main
            java
                com.bla.bla.autotests
                    (classes used from MyStepDefs)
                stepdefs
                    MyStepDefs.java
            resources
                features
                    my.feature
                Cucumber.xml
        test
            java
                com.CucumberOptions
                    RunCucumberTests.java
```
As recommended [here](http://stackoverflow.com/questions/10564240/spring-dependencies-not-injected-for-cucumber-runner), file `Cucumber.xml` contains element `<import resource="myBeans.xml"/>`, where file `myBeans.xml` contains all information needed to successfully autowire all beans involved in testing. For example, it contains element `<context:component-scan base-package="com.bla.bla">`.

Class `RunCucumberTests` looks like this:
```
@RunWith(Cucumber.class)
@CucumberOptions(features="classpath:features", glue="stepdefs")
public final class RunCucumberTests { }
```

_Run/Debug Configuration_ in IDEA is of the **JUnit** type and has the following properties defined:
```
Test kind: Class
Class: com.CucumberOptions.RunCucumberTests
```

**With the project structure given above, this Configuration runs fine.** However, if I move package `stepdefs` inside package `com.bla.bla.autotests` (where it should be located actually), and of course update options to `@CucumberOptions(features="classpath:features", glue="com/bla/bla/autotests/stepdefs")`, I get the following runtime error:

`org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [com.bla.bla.autotests.stepdefs.MyStepDefs] is defined: expected single matching bean but found 2: myStepDefs,com.bla.bla.autotests.stepdefs.MyStepDefs.`

**What is the reason of this strange behavior?** Why is Spring finding **two** beans now?!

It sounds like this: _"With Cucumber-jvm we cannot have our step definition file(s) to be located more than one package deep, even with the `glue` option being set correctly - because it results in Spring exception"_. But that's not a valid explanation, of course :) For the moment I left `stepdefs` package where it was, just to proceed with my project. However, it would be nice to understand the reason.

**Comment by brasmusson** [comment]
The `glue` parameter in `@CucumberOptions` take package name(s) (`glue="com.bla.bla.autotests.stepdefs"`), not paths. Using a deep package hierarchy for the step definitions works fine, see for instance https://github.com/cucumber/cucumber-jvm/blob/master/spring/src/test/java/cucumber/runtime/java/spring/contextconfig/RunCukesTest.java.

**Comment by a-yumashin** [comment]
Unfortunately, changing slashes to dots doesn't help - still getting the same exception.

**Comment by a-yumashin** [comment]
Please re-open.

**Comment by brasmusson** [comment]
> org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [com.bla.bla.autotests.stepdefs.MyStepDefs] is defined: expected single matching bean but found 2: myStepDefs,com.bla.bla.autotests.stepdefs.MyStepDefs.

@a-yumashin This error message say what the problem is. You have the same bean type defined twice on the classpath, you need to remove `myStepDefs` (defined in the directory `src/main/java/stepdefs`?), so that only `com.bla.bla.autotests.stepdefs.MyStepDefs` is single matching bean on the classpath.

**Comment by luisa123456** [comment]
Long path error is a very common problem in Windows users face. Try using Long Path Tool if your computer is giving errors like, “Path too long”, “Path too long – aborting (error code 80/1)”, 0x80010135 Path too long”, “Error cannot delete file: cannot read from source file or disk” or “File cannot be copied”. You can use Long Path Tool to resolve these problems. Get support of this product by subscribing it online.
