### ISSUE TITLE
scenario steps are written to log only after scenario has finished

### ISSUE THREAD

**Issue by lior-gershony** [cucumber/cucumber-jvm#1027]
I've just upgraded the cucumber-JVM from version 1.0.14  to version 1.2.4 and encountered the following issue:
i am running a Feature File with 3 scenarios - scenario A, scenario B, scenario C.
in the steps implementation class, I have a @Before and @After methods to print the scenario name, so that we can clearly see in the log file which data belongs to which scenario.
surprisingly, after the execution is done and I check the log file - Scenario's A steps (as they appear in the Feature File itself) are written under Scenario's B section in the log - Scenario's B steps are written under Scenario's C section etc ...

log file example:
starting scenario A ...
"some irrelevant data"
finished scenario A

starting scenario B ...
"[Scenarios A steps]"
finished scenario B

starting scenario C ...
"[Scenarios B steps]"
finished scenario C

my cucumberOptions is set with "pretty"
please note that in version 1.0.14 the issue is not recreating.

can you please advise what could be the reason for this?

**Comment by alayor** [comment]
Can you show an actual example of your logs?

**Comment by lunivore** [comment]
Hi @lior-gershony! If this is still important to you, please could you provide an example of your logs as requested? If we don't hear back from you we'll close this ticket in a week. Thanks!

**Comment by lior-gershony** [comment]
Hi,
thanks for addressing this issue and apologies for the late response.
it appears that we had a bug in our cucumber log parsing logic - you can close this ticket as a non-issue. 

sorry for troubling you.
