### ISSUE TITLE
Can I place cucumber.properties file in custom folder?

### ISSUE THREAD

**Issue by varunnvs92** [cucumber/cucumber-jvm#1031]
Hi,

As per these [docs](https://cucumber.github.io/api/cucumber/jvm/javadoc/cucumber/api/guice/package-summary.html),  cucumber.properties should be placed at root of the classpath. Is there any way that I can place the file at some folder like {custompath}/cucumber.properties and tell the tests to find the cucumber.properties file from {custompath}?

Thanks.

**Comment by aslakhellesoy** [comment]
I'm afraid you can't, no
