### ISSUE TITLE
Add support for Tag Expressions

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#1040]
## Summary

[Tag Expressions](http://docs.cucumber.io/tag-expressions/) is a more intuitive way to specify tags in tagged hooks and on the command line's `--tags` argument.
## Expected Behavior

Tagged Hooks should accept a single string:

``` Java
@Before("@foo and not @bar")
```

Likewise, the `--tags` command line argument should allow the same. (Specifying it more than once should cause an error)

```
--tags "@foo and not @bar"
```
## Context & Motivation

The current mechanism to specify `or` with comma and `and` with multiple `--tags` is incredibly awkward. Tag Expressions are intuitive!

**Comment by mattwynne** [comment]
Done 1af20c5e32efb82a8ea85ed40356b293b99d6eb3
