### ISSUE TITLE
Multiple report files is breaking with versions > 2.6.3

### ISSUE THREAD

**Issue by jsdevel** [cucumber/cucumber-jvm#1051]
I now see this on every build:

![error](https://cloud.githubusercontent.com/assets/2605980/18464044/52e452d6-7943-11e6-8a3d-44951ef29714.png)

Here's my config:

![config](https://cloud.githubusercontent.com/assets/2605980/18464058/65d50f66-7943-11e6-9758-165784850a4c.png)

Currently using 2.8.0.  If I downgrade to 2.6.3 it works.

**Comment by aslakhellesoy** [comment]
Wrong tracker. The masterthought report is not a Cucumber project

**Comment by jsdevel** [comment]
Ahh, so sorry.
