### ISSUE TITLE
Composite steps?

### ISSUE THREAD

**Issue by bsideup** [cucumber/cucumber-jvm#1052]
Hi!

We use CucumberJVM and it's awesome, but one thing we miss (especially, compared to JBehave) - composite steps ( https://github.com/cucumber/cucumber/wiki/Calling-Steps-from-Step-Definitions )

Yes, I do understand that this could be done by calling other stepdef functions. But, you will not see it in the report, and if some "substep" fails - you will not be able to figure out which one.

Are there any attempts to implement this feature? Or strong reasons not to?

Thanks!

**Comment by sebrose** [comment]
This feature was explicitly left out of Cucumber-JVM. We found that people that made use of this feature frequently ended up with messy automation code that was fragile and difficult to maintain.

**Comment by Curtis004** [comment]
Can you not just call the method from the step def file? I thought that was cucumber-jvms implementation of composite steps?

e.g. Inject the step def you want to call the step from and invoke the method you want directly?
