### ISSUE TITLE
Crash on android 6.0+ due to permission issue

### ISSUE THREAD

**Issue by LeoDZhao** [cucumber/cucumber-jvm#1065]
It failed to create directory. It should be caused by permission issue. On android 6.0+, user needs to request permissions at run time. Crash log:

09-29 09:05:39.933: E/AndroidRuntime(3039): cucumber.runtime.CucumberException: java.io.IOException: Failed to create directory /sdcard/cucumber-report
09-29 09:05:39.933: E/AndroidRuntime(3039):     at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:80)
09-29 09:05:39.933: E/AndroidRuntime(3039):     at cucumber.runtime.RuntimeOptions.getPlugins(RuntimeOptions.java:207)
09-29 09:05:39.933: E/AndroidRuntime(3039):     at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:241)
09-29 09:05:39.933: E/AndroidRuntime(3039):     at java.lang.reflect.Proxy.invoke(Proxy.java:813)
09-29 09:05:39.933: E/AndroidRuntime(3039):     at $Proxy15.stepDefinition(Unknown Source)
09-29 09:05:39.933: E/AndroidRuntime(3039):     at cucumber.runtime.RuntimeGlue.reportStepDefinitions(RuntimeGlue.java:91)
09-29 09:05:39.933: E/AndroidRuntime(3039):     at cucumber.runtime.android.CucumberExecutor.execute(CucumberExecutor.java:110)
09-29 09:05:39.933: E/AndroidRuntime(3039):     at cucumber.api.android.CucumberInstrumentationCore.start(CucumberInstrumentationCore.java:88)

**Comment by vivganes** [comment]
@LeoDZhao 
1. Does your application run cucumber tests on android devices?  
2. Is this log generated during application runtime or when you were testing it?  Was this in an emulator environment?  
3. Also, what permission set in Android does your application (the one running cucumber) have?

**Comment by LeoDZhao** [comment]
1. My app runs cucumber tests on android device.
2. Log is generated when I test it. It's emulator. But I believe it will crash on real device with 6.0+ too.
3. My application has permission WRITE_EXTERNAL_STORAGE.

As I said, it's caused by dynamic permission on 6.0+. Set permission in manifest does not work for 6.0+.  https://developer.android.com/training/permissions/requesting.html

**Comment by audkar** [comment]
I don't think that this is cucumber issue. 
There is some possible solutions:
- You can provide different output path for cucumber reports. e.g. you application dir. `/data/data/your.app.pkg`. In this case you must have root access on device to retrieve reports. (android emulators, genymotion emulator or rooted device)
- You implement grant on demand permissions solution in your tests yourself.
- Use already existing solutions like [Spoon](http://square.github.io/spoon/). Spoon has option `--grant-all` to approve all permissions .

**Comment by LeoDZhao** [comment]
I tried the 1 solution, save cucumber-report under /data/data/app.pkg. It works. Thanks.

**Comment by mpkorstanje** [comment]
I'm closing this issue as it does not appear to be a cucumber issue. 

Please feel free to reopen if this not the case.
