### ISSUE TITLE
Add support for Hk2 Dependency Injection framework

### ISSUE THREAD

**Issue by tayloryork** [cucumber/cucumber-jvm#1066]
Hk2 is a popular dependency injection framework used by the popular JAX-RS implementation Jersey.

An Hk2 Object Factory could be added to cucumber-jvm to allow Cucumber Glue code to be injected via Hk2's service locator.

**Comment by christianbellinaef** [comment]
Hi, any update on HK2 support? My team would really like to see this become a feature.

**Comment by mpkorstanje** [comment]
Not at the moment. We're currently working getting 2.0.0 done. 

For now I'd recommend that you create your own jar.

It may be a while before we get to this issue.

**Comment by mpkorstanje** [comment]
We currently have two different pull request for HK2 support. At a glance it looks like #1067 supports a only subset of the usecases of #1125 but I can't confirm this with certainty.

@tayloryork @christianbellinaef can you sort out which version should be merged?

And additionally to avoid problems like #724 could you add a `README.md` that minimally describes the possible configuration of the factory, the use of scopes if any and how it looks when used in a step definition.

**Comment by mpkorstanje** [comment]
Feel free to restart this issue.
