### ISSUE TITLE
cucumber.runtime.CucumberException: Don't know how to convert BigDecimal

### ISSUE THREAD

**Issue by jalona** [cucumber/cucumber-jvm#1068]
Hello
Error when passing double number 4071.35 to BigDecimal[ ]:
cucumber.runtime.CucumberException: Don't know how to convert "4071.35" into [Ljava.math.BigDecimal;.
Try writing your own converter:
@cucumber.deps.com.thoughtworks.xstream.annotations.XStreamConverter(BigDecimal[]Converter.class)
public class BigDecimal[] {}

```
@Когда("^Расчет с условиями (\\d+), ([\\d,.]+)$")
public void calculateCost(BigDecimal amount, BigDecimal[] pay) {
   ...
}
```

**Comment by vivganes** [comment]
@jalona  Can you please add a sample .feature file snippet?

**Comment by aslakhellesoy** [comment]
Ok. I think you can close issues you've created yourself, but I'm closing it anyway.
