### ISSUE TITLE
cucumber with junit and testng

### ISSUE THREAD

**Issue by hybaken** [cucumber/cucumber-jvm#1070]
Hello,

using cucumber and junit and testng will produce that result display, that no test has been run.
## Possible Solution

Using with just junit or just testng will solve, the problem.
However using both is not working.
## Steps to Reproduce (for bugs)
1. Include junit and testng to the same project. 
2. Run any cucumber test.
3. Check results. It should display number of tests, that have been run. It displays always 0.

**Comment by vivganes** [comment]
@hybaken Are you running the cucumber test using your IDE? Or do you use command line to run them? Or, do you perhaps use Maven for running tests?

Also, can you please give me the versions of junit, testng and cucumber that you are using?

**Comment by hybaken** [comment]
@vivganes 
I m using those versions:
cucumber 1.2.5
junit 4.12
testng 6.9.10

I am running it by using "mvn test" via terminal in IntelliJ.

**Comment by brasmusson** [comment]
When running Cucumber-JVM through a JUnit-runner class or a TestNG-runnner class, maven is using a JUnit runner module (like Maven-surefire) or a TestNG-runner module to run test classes as JUnit-test or TestNG-tests, which in turn (using the `@RunWith` annotation - for JUnit, or using TestNG annotations) execute Cucumber-JVM. Why do you say that the problem is in Cucumber-JVM and not in your maven configuration?

**Comment by hybaken** [comment]
@brasmusson 
Maybe I missed something. This seems simple for me.
When I remove jUnit dependency from maven, and keep just TestNG, its ok (correct results displays).
When I remove TestNG dependency from maven, and keep just jUnit, its ok too (correct results displays).

I keep maven surefire without touch.

Is there way to collect results from both jUnit and TestNG?

**Comment by brasmusson** [comment]
It is important to distinguish using JUnit and/or TestNG as assertion libraries together with Cucumber-JVM, and using JUnit and/or TestNG runners as execution entry. A runner class like
```
@RunWith(Cucumber.class)
@CucumberOptions(features = {...}, glue = {...})
public class RunCukesTest {}
```
can, with the proper definition of the `feature` and `glue` options, be used both to run features with step definitions using JUnit assertions and and feature with step definitions using TestNG assertions. From the perspective of Cucumber-JVM a exceptions thrown in a step definition defines a failed step regardless of whether it is a JUnit exception or a TestNG exception. The class above is to be executed by a JUnit runner and will use JUnit notifications to notify listeners about the run, but that is a different issue.

Running both:
```
class XTest {
  @org.junit.Test
  public void a_test() {
    ...
  }
}
```
and
```
class YTest {
  @org.testng.annotations.Test
  public void another_test() {
    ...
  }
}
```
in the same maven run, is purely a maven problem (I do not know if or how it is possible to do).

I do not see that it should not still be a maven problem, if those classes were change to trigger Cucumber-JVM to run feature files.

> Is there way to collect results from both jUnit and TestNG?

I have no idea. Cucumber-JVM collect results for all feature file during one execution. Executing all feature files in the same Cucumber-JVM execution is the easiest way to collect all results. Executing Cucumber-JVM (one time each) using two different JUnit runner classes (each using a `@RunWith` annotation), would enable the utility running those runner classes (maven surefire?) to collect results from both runs (listening to JUnit notification). I have no idea if there is a utility that can run both JUnit test classes and TestNG test classes and collect the results from them both. In any case I see that not as a Cucumber-JVM problem, but a problem for the utility that are to run both JUnit test classes and TestNG classes (regardless whether they are used to run JUnit/TestNG unit tests, or to run Cucumber-JVM.

**Comment by nsidhaye** [comment]
@hybaken : In JUnit 5 you can define / configure different test runner. You can configure TestNG as test runner in JUnit 5 initiative 

Unfortunately cucumber did not release JUnit 5 support. Ref: #1103 

Ref for JUnit 5: 
[Open Test Alliance Initiative](https://github.com/ota4j-team/opentest4j).
[Launch Open Test Alliance Initiative](https://github.com/junit-team/junit5/issues/12)
[JUnit 5 User Guide](http://junit.org/junit5/docs/current/user-guide/)

**Comment by hybaken** [comment]
Sorry for not responding.
I have choosed to use just jUnit in project wihtout TestNG.
It is not relevant for me anymore.

Anyway thanks for advice.
