### ISSUE TITLE
Test result reports are truncated in 1.2.5

### ISSUE THREAD

**Issue by ck7m** [cucumber/cucumber-jvm#1071]
## Summary

   New version (1.2.5) is not showing pretty/detailed test reports. Test results are shown properly in 1.2.4.
**command :** `mvn test`
## Expected Behavior

```
Scenario: I XXXXXXX                 # features/endToEnd.feature:21
    Given XXXXXXXX                                # feature.method(String,String)
    When XXXXXXXX                                # endToEnd.submit()
    Then The response code should be 200                          # endToEnd.checkResponseCode(int)
```
## Current Behavior

```
4 Scenarios (4 passed)
21 Steps (21 passed)
0m28.445s

Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 29.635 sec - in com.cucumber.runTest
```
## Your Environment
- Version used: 1.2.5
- Operating System and version: mac

**Comment by sebrose** [comment]
We haven't seen this behaviour elsewhere. Can you supply a complete, minimal example, please?

**Comment by lunivore** [comment]
Hi @ck7m, if this is still an issue for you please could you supply an example as requested, or let us know that you're working on it? Otherwise I'll close this in a week, since the codebase has moved on significantly.
