### ISSUE TITLE
Hosted documentation is outdated

### ISSUE THREAD

**Issue by jromero** [cucumber/cucumber-jvm#1074]
## Summary

HTML page linked from https://github.com/cucumber/cucumber-jvm/tree/master/guice is outdated. The properties filename should be `cucumber.properties` not `cucumber-guice.properties`

Looking at it further it seems like http://cucumber.github.io/api/cucumber/jvm/javadoc/ is version 1.2.2 while the current version is 1.2.5.
## Steps to Reproduce (for bugs)

1. Go to https://github.com/cucumber/cucumber-jvm/tree/master/guice
2. Click link "Read package documentation online at cukes.info"
3. Notice it states "cucumber-guice.properties" instead of "cucumber.properties"

**Comment by mlvandijk** [comment]
Note that "cucumber-guice.properties" was already updated to "cucumber.properties" (by #913).
However, https://github.com/cucumber/cucumber-jvm/tree/master/guice contains an invalid link, which I've removed in PR #1224
