### ISSUE TITLE
Numbers in DataTables must be formatted to avoid TableDiffException

### ISSUE THREAD

**Issue by phillipjohnson** [cucumber/cucumber-jvm#1083]
## Summary
It appears that numbers passed into `DataTable.diff()` will get formatted according to the default `Locale`, even if the numbers in the provided data table are not formatted.

## Expected Behavior
I expect that the data passed into `diff` should not undergo additional formatting.

## Current Behavior
Given a data table:

```cucumber
| MyName | MyNumber |
| Foo    | 10000    |
| Bar    | 20000    |
```

If we diff that table against data that contains the integers 10000 and 20000, we get the following exception:

```
cucumber.runtime.table.TableDiffException: Tables were not identical:
      | MyName | MyNumber |
    - | Foo    | 10000    |
    - | Bar    | 20000    |
    + | Foo    | 10,000   |
    + | Bar    | 20,000   |
```

## Steps to Reproduce (for bugs)
This test will reproduce the error:

```java
public void spike() {
    DataTable expected = DataTable.create(
            Arrays.asList(
                    Arrays.asList("MyName","MyNumber"),
                    Arrays.asList("Foo","10000"),
                    Arrays.asList("Bar","20000")
            )
    );

    List<Map<String, Object>> actual = new ArrayList<>();
    Map<String, Object> actual1 = new LinkedHashMap<>();
    actual1.put("MyName", "Foo");
    actual1.put("MyNumber", 10000);
    actual.add(actual1);

    Map<String, Object> actual2 = new LinkedHashMap<>();
    actual2.put("MyName", "Bar");
    actual2.put("MyNumber", 20000);
    actual.add(actual2);

    expected.diff(actual);
}
```
## Possible Solution
For number comparisons, just make sure that both the actual data and the expected data parse to the same number.

## Context & Motivation
My application saves data to a SQL database. I used `DataTable.diff()` to compare my expected data to the actual data returned from the database. The diff comparison failed on the "ID" column because the IDs were larger than 1000 and I did not include commas in my expected data.

## Your Environment
* Version used: 1.2.5
* Operating System and version: Windows 7

**Comment by cosmocracy** [comment]
+1 ...definitely an unexpected sharp edge in the toolset

**Comment by mpkorstanje** [comment]
Had a look at the code but this appears to be by design. The expectation is that when users write numbers in their gherkin, they use the appropriate locale like so:

```
| MyName | MyNumber |
| Foo    | 10,000    |
| Bar    | 20,000    |
```

Because a DataTable represents user input the cells can not reasonably be typed as anything but string - there is no obvious conversion that will work for every situation, especially not with when people add their own formatters.  Hence the chosen solution is to convert the actual data table to strings too using the appropriate locale.

It's a feature, not a bug. :)
