### ISSUE TITLE
Multi parameter lambdas with of the same type cause IndexOutOfBoundsException

### ISSUE THREAD

**Issue by bblonski** [cucumber/cucumber-jvm#1084]
## Summary

Defining a java8 lambda stepdef that takes multiple parameters will cause an IndexOutOfBoundsException if more than one parameter are of the same type.

## Expected Behavior

Expected behavior is for multi-parameter lambda to not cause an exception.

## Current Behavior

Trying to add a multi-parameter lambda with multiple parameters of the same type will cause an IndexOutOfBoundsException.

## Possible Solution

It looks like the number of arguments are being subtracted by the number of argument types on ConstantPoolTypeIntrospector:36.  This will result in indexes < 0 in any scenario where multiple arguments are the same type.  It looks like maybe it should be the other way around, with `typeParameterCount - argumentTypes.length` instead of `argumentTypes.length - typeParameterCount`.

## Steps to Reproduce (for bugs)

Simple to reproduce.
Create a Java8 StepDef class.  
Add the following snippet to the constructor
~~~
Given("^'(.+)' '(.+)'$", (x, y) -> {
   System.out.println(x + " " + y);
});
~~~
Create a feature Gherkin Scenario that calls `Given 'Hello' 'World'`

This will cause the StepDef class to fail to initialize with root cause

~~~
Caused by: java.lang.IndexOutOfBoundsException: fromIndex = -1
	at java.util.SubList.<init>(AbstractList.java:620)
	at java.util.RandomAccessSubList.<init>(AbstractList.java:775)
	at java.util.AbstractList.subList(AbstractList.java:484)
	at cucumber.runtime.java8.ConstantPoolTypeIntrospector.getGenericTypes(ConstantPoolTypeIntrospector.java:36)
	at cucumber.runtime.java.Java8StepDefinition.getParameterInfos(Java8StepDefinition.java:54)
	at cucumber.runtime.java.Java8StepDefinition.<init>(Java8StepDefinition.java:44)
	at cucumber.runtime.java.JavaBackend.addStepDefinition(JavaBackend.java:162)
~~~

## Context & Motivation

I can't define multi-parameter steps with lambdas.  Annotated methods work as expected.

## Your Environment

* Version used: 1.2.5
* Operating System and version: Linux Mint 18 x64.  Oracle java 1.8.0_111-b14

**Comment by mpkorstanje** [comment]
I seem to be unable to reproduce the issue. Can you confirm this is the correct reproducer?

https://github.com/mpkorstanje/multi-parameter-lambda

**Comment by bblonski** [comment]
Found the issue.  The problem was being caused by the JRebel plugin in my Intellij IDE.  My guess is JRebel is messing with some of the internal calls being used.  Running without JRebel works as expected.
