### ISSUE TITLE
Cucumber-JVM report test status says Failed even though all the test steps are pass.

### ISSUE THREAD

**Issue by vishwathma** [cucumber/cucumber-jvm#1085]
## Summary
Cucumber-JVM report status says Failed even though the test case has passed.

## Expected Behavior
The report should say PASS.
 
## Current Behavior
The report says status has Failed  even though the test case has passed.
This usually happens with only one random single test when the entire suite is Pass.

## Context & Motivation
Because of this issue, the build status goes red when it is actually green.

## Your Environment

* Version used: Latest
* Operating System and version: MAC OS 10.11.6

**Comment by aslakhellesoy** [comment]
Please provide some code to reproduce this

**Comment by lunivore** [comment]
Hi @vishwathma! If this is still important to you, please provide some code to reproduce the problem or let us know that you're working on that. If we don't hear back from you, we'll close this ticket in a week. Thanks!
