### ISSUE TITLE
JUnit RunListener.testStarted called after step glue code was executed.

### ISSUE THREAD

**Issue by TimJD82** [cucumber/cucumber-jvm#1090]
## Summary

When a RunListener is registered to JUnit's RunNotifier, the testStarted method of the RunListener class is invoked by cucumber after the step glue code has already completed. 

When logging from testStarted, testFinished and step glue code, output is as follows: 

[timestamp] [main] INFO  - [log from step definition glue code]
[timestamp] [main] INFO  - [log from RunListener.testStarted]
[timestamp] [main] INFO  - [log from RunListener.testFinished]

I would expect the log to be like:

[timestamp] [main] INFO  - [log from RunListener.testStarted]
[timestamp] [main] INFO  - [log from step definition glue code]
[timestamp] [main] INFO  - [log from RunListener.testFinished]

## Possible Solution

Location of fireTestStarted in junit/src/main/java/cucumber/runtime/junit/JUnitReporter.java should be analysed.

**Comment by brasmusson** [comment]
Use `--junit,--allow-started-ignored`/`@CucumberOptions(junit = { --allow-started-ignored })` to have `testStarted` to be called before the glue code is executed. See the section on  `--allow-started-ignored` in #1002 for the discussion on why the default behavior is what is is.

**Comment by TimJD82** [comment]
Thanks for the reply. I tried to use the --allow-started-ignored option, but that will unfortunately result in this issue: https://github.com/cucumber/cucumber-jvm/issues/1015.
