### ISSUE TITLE
cucumber.api.cli.Main cannot recognize step definition files

### ISSUE THREAD

**Issue by ari-fikri** [cucumber/cucumber-jvm#1092]
## Summary
Using Cucumber.api.cli.Main to test cucumber features in an android project, did not recognize step definition files. 

## Expected Behavior
- Running cucumber.api.cli.Main should run correctly given the --glue param is used, pointing to the correct Step Definition package, even the package is put in the AndroidTest or Test folder.

## Current Behavior
Using Cucumber.api.cli.Main to test cucumber features in an android project, did not recognize step definition files, and always end with Undefined steps **unless the stepDefinition package and file is put under the same package as the main app.**
Using **--glue=package_to_step_definition** to specified steps definition files, didn't work either if the steps defs are put under androidTest or test folder in the project structure.
Version used : 1.2.0
Also not working in Android Studio by creating Cucumber Java test scenario, unless steps defs are put in the same folder as the main app source code

~~~
~~~

## Steps to Reproduce (for bugs)

1. Create an android project using Android studio
2. Create feature file and step definition, in the androidTest folder
3. Run the cucumber.api.cli.Main to run the cucumber test file from terminal, or, 
4. Feature is recognized but Step Definitions is unrecognized so, the test failed with error "Undefined steps"
5. Move the Step Definition files into the main app folder, and run the test again
6. Now the test successful.

## Your Environment

* Android Studio version 2.2.2
* Cucumber.api.cli.Main version 1.2.0
* Operating System and version: Mac OS Sierra 10.12.1

gradle dependencies section:
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit-dep:4.8.1'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.2.1'
    compile 'com.android.support:cardview-v7:23.4.0'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'net.hockeyapp.android:HockeySDK:4.1.1'
    compile 'com.google.zxing:core:3.2.0'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.squareup.retrofit2:retrofit:2.0.0'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0'
    compile 'com.makeramen:roundedimageview:2.2.1'
    compile 'me.dm7.barcodescanner:zbar:1.8.4'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    compile 'com.j256.ormlite:ormlite-android:4.48'
    compile 'com.j256.ormlite:ormlite-core:4.48'
    compile 'eu.davidea:flexible-adapter:4.2.0'
    compile 'eu.davidea:flexible-adapter:5.0.0-b6'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.0'
    androidTestCompile 'com.android.support.test:testing-support-lib:0.1'
    androidTestCompile 'info.cukes:cucumber-android:1.2.0@jar'
    androidTestCompile 'info.cukes:cucumber-picocontainer:1.2.0'

    androidTestCompile('com.squareup.okhttp3:mockwebserver:3.5.0') {
        exclude group: 'junit'
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    testCompile 'info.cukes:cucumber-jvm:1.2.5'
    testCompile 'junit:junit:4.8.1'
    testCompile 'info.cukes:cucumber-junit:1.2.5'
}

```

**Comment by brasmusson** [comment]
Since you are using Android, should you not use [`cucumber.api.android.CucumberInstrumentation`](https://github.com/cucumber/cucumber-jvm/blob/master/android/src/main/java/cucumber/api/android/CucumberInstrumentation.java) as the entry, instead of `Cucumber.api.cli.Main`? Why else do you have declared `info.cukes:cucumber-android` as a dependency?

You are mixing versions of Cucumber-JVM jars (v1.2.0 and v1.2.5), that is not supported.

Are you sure that the step definitions are available on the classpath to the Cucumber-JVM runtime? `--glue` is only a runtime argument, if Android Studio have not put the step definition package on the classpath when running, the `--glue` option will have not effect.

Please file issues against the latest released version (v.1.2.5).

**Comment by ari-fikri** [comment]
I use Cucumber.api.cli.Main because when I create a scenario in Android Studio, this is the default option given to run the scenario.

I tried replacing everything that v.1.20 with 1.2.5, but still no luck.

I guess the step definitions just not recognized by cucumber-jvm, so I compiled the step definitions file, put the directory (where the generated *.classes exists) inside the -cp, but still git the message " steps is  undefined".

Please be gentle with me, all this time I developed android app only through Android Studio or Eclipse, so there might be wrong steps I did here and there, and commands and configuration that I do not aware of.

If I run the test using **gradlew connectedCheck**, all the tests will just run file, but I'd like to be able to run single scenarios, just like what Cucumber.api.cli.Main offered.

I tried running tests in this project using gradle connectedCheck and it ran fine:
**https://github.com/emmasuzuki/CucumberEspressoDemo**
It would be nice if I can run the project's tests scenario using Cucumber.api.cli.Main, will it be possible?

**Comment by willpowr** [comment]
Hi Ari. Did you ever get a fix for this? I'm having the same issue.

**Comment by toothpicks131** [comment]
Hi Ari, did you eventually have success running tests with the CLI runner, cucumber.api.cli.Main? I'm having the same problem where it cannot find the step definitions despite passing it the location of the files in the glue option...https://stackoverflow.com/questions/45022603/cli-runner-cucumber-api-cli-main-cannot-find-step-definitions?noredirect=1#comment77048804_45022603

**Comment by ZiqueYuutaka** [comment]
Hey @toothpicks131 and @willpowr.  I not sure if you figured it out yet but the solution is to use the package the step definitions are found in.
example: --glue your.step.package

**Comment by mpkorstanje** [comment]
> I use Cucumber.api.cli.Main because when I create a scenario in Android Studio, this is the default option given to run the scenario.

To the best of my knowledge it is not possible to use the cli runner in combination with Android. I suspect you are using the plugin provided by IntelliJ. You may have to file a ticket there.
