### ISSUE TITLE
Tag issues with "good first issue"

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#1093]
In order to attract newcomers to contribute, we should help them where to start.
Whenever you see a new issue, and you think it is a good fit for someone who isn't familiar with the codebase, tag it with "good first issue".

All newcomers friendly issues in the cucumber org can be listed [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Acucumber+no%3Aassignee+label%3A%22good+first+issue%22) - we'll link to that from our yet-to-be-written "How to contribute" page on our website.

This is an ongoing effort, but what you can do right now is to have a scan at existing issues, tag a few of them. Then close this issue.

**Comment by aslakhellesoy** [comment]
We should still do this and reconfigure stalebot to leave those open

**Comment by mlvandijk** [comment]
Atm issues are being marked if they're "good first issue" I think. 
Configurating Stalebot to ingnore "Good first issue" sounds like a great idea. This issue itself could be closed imho.

**Comment by aslakhellesoy** [comment]
Let's keep it open until stalebot has been reconfigured (needs to be done in all repos' `./github/stalebot.yml`)
