### ISSUE TITLE
Have a .feature file with 4 scenarios with multiple steps.I want a piece of code to execute just before & after each scenario

### ISSUE THREAD

**Issue by chaitraJagirdar** [cucumber/cucumber-jvm#1096]
Have a .feature file with 4 scenarios with multiple steps.I want a piece of code to execute just before & after each scenario.
Tried using @before/@after [junit] & @before/@after [cucumber.api.java.before ] in Stepdefinations.This did not work

## Summary

My code is as follows:
@Before public void before(Scenario scenario) {
	 this.scenario = scenario;
	 scenario.write("*****************************************************");
	 System.out.println("BEFOREEEEEEEEEEEEEEEEEEEE");
	 
	 }
	
	@After
	 public static void embedScreenshot(Scenario scenario) {
	 if (scenario.isFailed()) {
	 try {
	 byte[] screenshot = ((TakesScreenshot) selenium.w)
	 .getScreenshotAs(OutputType.BYTES);
	 scenario.embed(screenshot, "image_png");
	 System.out.println("-----------SCREENSHOT TAKEN---------------------");
	 } catch (Exception e) {
	 e.printStackTrace();
	 }
	 }
	 }

## Expected Behavior

Am expecting @before initiates scenario to current scenario.

@after takes screenshots after end of scenario, incase scenario failed.

## Current Behavior
@before function ,@after function never executes.

## Possible Solution
Could you please suggest.Am not sure of why this is the situation

## Your Environment

* Version used:copy pasting my pom.xml [Please find all related versions of dependencies]
* Operating System and version:win 7

==============================
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>x</groupId>
  <artifactId>y</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>y</name>
  <url>http://maven.apache.org</url>
  <properties>
        <cucumber-jvm.version>1.1.2</cucumber-jvm.version>
        <selenium.version>2.28.0</selenium.version>
        <junit.version>4.11</junit.version>
    </properties>

  
 

   <build>

   <testResources>
      <testResource>
        <directory>src/test/resources</directory>
        <includes>
          <include>log4j.properties</include>
        </includes>
      </testResource>
    </testResources>

<plugins>
   
      
    

   <plugin>
			 <groupId>org.codehaus.mojo</groupId>
			   <artifactId>exec-maven-plugin</artifactId>
					<version>1.2.1</version>
					 <executions>
					    <execution>
						  <phase>integration-phase</phase>

							<goals>
								<goal>java</goal>
							</goals>
				        </execution>
					 </executions>
		 <configuration>
			  <executableDependency>
					 <groupId>info.cukes</groupId>
					<artifactId>cucumber-core</artifactId>
			 </executableDependency>
       
				<mainClass>cucumber.api.cli.Main</mainClass>
				<arguments>
					<argument>--format</argument>
					<argument>junit:target/cucumber-junit-report/allcukes.xml</argument>
					<argument>--format</argument>
					<argument>pretty</argument>
					<argument>--format</argument>
					<argument>html:target/cucumber-html-report</argument>
					<argument>--tags</argument>
					<argument>@Bestallhamtning,@BestallPostbox</argument>
					<argument>--glue</argument>
					<argument>com/</argument>
					<argument>src/</argument>

				</arguments>
		</configuration>
		</plugin>
</plugins>

</build>		
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
   <dependency>
  <groupId>org.testng</groupId> 
  <artifactId>testng</artifactId> 
  <version>6.1.1</version> 
  </dependency>
  <dependency>
    <groupId>javax.mail</groupId>
    <artifactId>mail</artifactId>
    <version>1.4</version>
</dependency>
<dependency>
  <groupId>log4j</groupId> 
  <artifactId>log4j</artifactId> 
  <version>1.2.14</version> 
  </dependency>
<dependency>
  <groupId>commons-logging</groupId> 
  <artifactId>commons-logging</artifactId> 
  <version>1.1.1</version> 
  </dependency>
  <dependency>
    <groupId>com.vimalselvam</groupId>
    <artifactId>cucumber-extentsreport</artifactId>
    <version>1.1.1</version>
</dependency>
  <dependency>
    <groupId>info.cukes</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>1.2.2</version>
    <scope>test</scope>
</dependency>
<dependency>
  <groupId>info.cukes</groupId> 
  <artifactId>cucumber-core</artifactId> 
  <version>1.2.2</version> 
  </dependency>
 <dependency>
    <groupId>info.cukes</groupId>
    <artifactId>cucumber-picocontainer</artifactId>
    <version>1.2.2</version>
</dependency>
<dependency>
<groupId>info.cukes</groupId>
<artifactId>cucumber-junit</artifactId>
<version>1.2.2</version>
</dependency>
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>2.53.0</version>
</dependency>
<dependency>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>2.19.1</version>
  <type>maven-plugin</type>
</dependency>
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-support</artifactId>
    <version>2.53.0</version>
</dependency>
  </dependencies>
  
</project>

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
