### ISSUE TITLE
My pom.xml does not pickup the tests to run

### ISSUE THREAD

**Issue by chaitraJagirdar** [cucumber/cucumber-jvm#1097]
* Version used:pom attached
* Operating System and version:win 7
[POM.txt](https://github.com/cucumber/cucumber-jvm/files/730786/POM.txt)

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
