### ISSUE TITLE
JUnit plugin not generating output

### ISSUE THREAD

**Issue by sebrose** [cucumber/cucumber-jvm#1098]
## Summary

In a Cucumber JUnit runner (RunCukesTest) a client has implemented a @BeforeClass initialisation method in which we override a system property "javax.xml.parsers.DocumentBuilderFactory". This seems to stop any output being written to the specified output file.

## Expected Behavior

They expect output to be written to the specified output file as usual.

## Current Behavior

No output is written to the specified output file. The file is created, but is empty.

## Steps to Reproduce (for bugs)

Here's the runner:
~~~
@RunWith(Cucumber.class)
@CucumberOptions(snippets = SnippetType.CAMELCASE, strict = true, monochrome = true},
features = {CucumberRunnerUtil.CukeFormat.FEATURE_FILE_LOCATION},
plugin = {"pretty",
              "junit:target/cucumber-reports/integration/integration-test-reports.xml"})
public class RunIntegrationCukeTest {

       @BeforeClass
       public static void init() {
              System.setProperty("javax.xml.parsers.DocumentBuilderFactory",
                           "org.apache.xerces.jaxp.DocumentBuilderFactoryImpl");
       }
}
~~~

## Context & Motivation

The code that we're testing needs us to set this system property, but we also need to capture JUnit output from the test run.

## Your Environment

Windows, Jenkins

**Comment by anjalivaswani** [comment]
Hi is this issue resolved? Or any developments here ? 
Till December 2016, this was working fine, now i have just executed my old code and realized a blank xml is being generated.

**Comment by mpkorstanje** [comment]
No development but this smells like an implementation difference between `org.apache.xerces.jaxp.DocumentBuilderFactoryImpl` and the default returned by [DocumentBuilderFactory.newInstance()](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java#L91).

Running with `-Djaxp.debug=1` should give you some information to help you debug and solve the issue. It will be easier to do so if you copy the JunitFormatter into your cucumber project and place some breakpoints.

**Comment by anjalivaswani** [comment]
Ok thanks a lot ... let me find out the version of xerves im using ... Thanks a lot for pointing it out
