### ISSUE TITLE
Listener registered to RunNotifier executes testStarted() method after test

### ISSUE THREAD

**Issue by amartyushov** [cucumber/cucumber-jvm#1099]
## Summary

I extend cucumber.api.junit.Cucumber and override method cucumber.api.junit.Cucumber#run to provide my own implementation of org.junit.runner.notification.RunListener. 
In this case code from method _listener_.testStarted() is actually executed after test is executed right before code from _listener_.testFinished().
You can find my experimental code in repo [LINK](https://github.com/amartyushov/Testing-frameworks/tree/master/cucumber/cucumberJvmWithSpring)

**System.out from experiment:**
[STEP DEFINITION] I can read scenario name in Runtime 2. scenario2 ## implementation of step
9.0 ## implementation of step
Inserted for Android ## implementation of step
MY: test started 
MyListener.testStarted: method name Given first step 
MyListener.testStarted: display name Given first step(Scenario: 2. scenario2) 
MY: test finished 
MyListener.testFinished: method name Given first step 
MyListener.testFinished: display name Given first step(Scenario: 2. scenario2) 

## Expected Behavior

**I expect to see lines in such a direction**
MY: test started 
MyListener.testStarted: method name Given first step 
MyListener.testStarted: display name Given first step(Scenario: 2. scenario2) 
[STEP DEFINITION] I can read scenario name in Runtime 2. scenario2 ## implementation of step
9.0 ## implementation of step
Inserted for Android ## implementation of step
MY: test finished 
MyListener.testFinished: method name Given first step 
MyListener.testFinished: display name Given first step(Scenario: 2. scenario2) 

And actually I see such sequence of lines if I use pure JUnit. You can find proof in class io.mart.Evaluator#main from above mentioned repo.

## Current Behavior

Currently I see that code from method _listener_.testStarted() is actually executed after test is executed right before code from _listener_.testFinished(). 

## Possible Solution

Potentially I suspect the fact that System.out.println() uses buffer and it may be a cause. But honesty I don`t strongly believe in it.

## Steps to Reproduce (for bugs)

1. Use repo [LINK](https://github.com/amartyushov/Testing-frameworks/tree/master/cucumber/cucumberJvmWithSpring)
2. run 'mvn clean test'
3. Check console output

## Context & Motivation

I am solving logging problem. I want to see a Scenario names and step names among rest of log lines.

## Your Environment

* Version used: cucumber-java:1.2.4; cucumber-junit:1.2.4
* Operating System and version: MacBook 10.11.6
* Link to your project: [LINK](https://github.com/amartyushov/Testing-frameworks/tree/master/cucumber/cucumberJvmWithSpring)
* java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
* Apache Maven 3.3.9

**Comment by brasmusson** [comment]
The current behaviour is intentional, see #1002. You can change it using `--junit,--allow-started-ignored`, see #1002.
