### ISSUE TITLE
Get scenario steps names

### ISSUE THREAD

**Issue by ionutss** [cucumber/cucumber-jvm#1100]
## Summary

In the Step class we can access an object of type Scenario.
Using this object we can get the name of the scenario, the status, etc.

## Expected Behavior

It would be helpful if we can get through this object the name of the current execution step from the scenario.

## Current Behavior

Now there is a property in ScenarioImpl, called report. Through this object we can find the name of the scenario steps. The thing is, this property is declared private and it can't be accessible.

## Possible Solution
Changing the access modifier for report property in ScenarioImpl from private to public or creating a new public method which would return the desired step names.

## Context & Motivation

I want to generate custom reports(not the cucumber reports) and I need this data.

**Comment by sorin-costea** [comment]
I had a Cucumber with Selenium integration project and would have loved to save the error screenshots with the failing step name. But yes, that was private info :(
Is that thinkable before v2?

**Comment by swapnilpatne** [comment]
I am also in need of exactly the same. Saving error screenshots with the failing steps name. Is there a possibility of that being available soon?

**Comment by mpkorstanje** [comment]
Rather then using Hooks or trying to hack Cucumber I reckon the best avenue of approach would be to create your own formatter/reporter. These can be passed as a plugin through `@CucumberOptions`.

For a working example either look a the [HTMLFormatter](https://github.com/cucumber/cucumber-jvm/blob/v1.2.5/core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java) or the [ExtentCucumberFormatter](https://github.com/email2vimalraj/CucumberExtentReporter/blob/master/src/main/java/com/cucumber/listener/ExtentCucumberFormatter.java).

Beware that we're working on 2.0.0 right now. You may need to do a rewrite once that comes out to make use of the event based system.

**Comment by igalep** [comment]
Same Issue as here...
Trying to set a ScreenShot name as step name , but have no access to it.
I think that implementing a new reporter only for step name is a bit an overkill ...

No chance to switch the Step to public ?

**Comment by mpkorstanje** [comment]
Only if someone creates a pr with before/after step hooks. 

Getting it through the scenario as proposed would expose you to the implementation details of cucumber. These may and will change leaving you unable to upgrade easily.
