### ISSUE TITLE
Can't add multiple tags in cucumber. Not able to find any tests if I add more than one tag

### ISSUE THREAD

**Issue by Amisha95** [cucumber/cucumber-jvm#1102]
## Summary
I tried adding one tag in tags and it works fine. But if I try adding multiple tags, it's unable to find any tests on android studio. I'm writing my UI tests using expresso.

**Comment by tmullender** [comment]
There are lots of examples of Features/Scenarios with multiple tags that are working, could you attach a small sample feature file that is not working for you with details of the run configuration you are using (ie. Program arguments, VM options etc)

**Comment by brasmusson** [comment]
This seems to be a misunderstanding the "`--tags @foo --tags @bar`" means "scenarios with either `@foo` or `@bar`" when it actually means "scenarios with both `@foo` and `@bar`". To specify "scenarios with either `@foo` or `@bar`" in Cucumber-JVM v1.x.x use "`--tags @foo,@bar`" and in the coming Cucumber-JVM v2.0.0 (available as a [snapshot release](https://cucumber.io/docs/reference/jvm) - note the the groupId has changed to "io.cucumber") use "`--tags '@foo or @bar'`"
