### ISSUE TITLE
Plugin formatter having no arg and File arg constructor

### ISSUE THREAD

**Issue by email2vimalraj** [cucumber/cucumber-jvm#1104]
## Summary

If a plugin formatter contains a no-arg constructor and a constructor with one of the valid argument: Appendable, URI, URL or File, always the no-arg constructor is being triggered, even when the valid argument is passed.

## Expected Behavior

The no-arg constructor should be a least check where-in if any of the conditions of arg not met, it should fallback to trigger the no-arg constructor if defined.

## Current Behavior

Always the no-arg constructor is being triggered.

## Possible Solution

The `PluginFactory` should be updated to consider null as a least priority.

## Steps to Reproduce (for bugs)

My own formatter look like this:

```java
public class TestFormatter implements Formatter  {

    public TestListener() {
        System.err.println("Null constructor");
    }

    public TestListener(File file) {
        System.err.println("File Constructor");
    }
}
```

The runner look like as follows:

```java
@RunWith(Cucumber.class)
@CucumberOptions(
    features = {"src/test/resources/features/MyFeature.feature"},
    glue = {"com.cucumber.stepdefinitions"},
        plugin = {"com.cucumber.listener.TestListener:output/report.html"}
)
public class RunCukesTest {
}
```

## Context & Motivation

The expectation was that the constructor with `File` argument is called. But, the no-arg constructor is called. The motivation is to when the argument is given, report will be generated at the given location. If not, the no-arg constructor will generate the output at the default location defined by the framework.

## Your Environment

* Version used: 1.2.4
* Operating System and version: Mac OSx Maveriks
* Link to your project: https://github.com/email2vimalraj/CucumberExtentReporter

**Comment by mlvandijk** [comment]
@email2vimalraj Would you like to process the review comments? Otherwise I might give this issue a go...

**Comment by email2vimalraj** [comment]
Yes, I'll look into this over this weekend.

On 23-Aug-2017 12:15 AM, "Marit van Dijk" <notifications@github.com> wrote:

@email2vimalraj <https://github.com/email2vimalraj> Would you like to
process the review comments? Otherwise I might give this issue a go...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cucumber/cucumber-jvm/issues/1104#issuecomment-324116906>,
or mute the thread
