### ISSUE TITLE
Running cucumber scenarios using TestNG (Scenario level)

### ISSUE THREAD

**Issue by deepnirmal** [cucumber/cucumber-jvm#1113]
## Summary
When we run the  Cucumber-jvm using TestNG, by default it runs each and every feature file as a single Test case. What I want is basically it should give functionality to run each and every scenario with examples as single test case.

## Expected Behavior
I want to create screenshots of the test failure and I am currently using selenium with cucumber-testng. Selenium listener is used to capture the event and based on the event it captures the screenshots. But this happens only on a feature level, not at the scenario level. 
My expectation is I want each scenario to be passed in @Test such that if any scenarios fails. It should trigger the event for test fail such that my code would capture the event.

## Current Behavior
It takes all the scenarios as a single test case. So my code is generating the screenshots if any scenarios fails in the feature and a single snap is generated for a particular feature file.
It runs the scenarios one after the other and doesn't trigger any event for the failure.

~~~
~~~

## Possible Solution
By extending the feature of 		```testNGCucumberRunner.runCucumber(cucumberFeature.getCucumberFeature()); ```
such as 
```testNGCucumberRunner.runCucumberScenario(cucumberFeature.getFeatureScenario(scenarioname))```

## Steps to Reproduce (for bugs)

1. Functionality for getting all scenarios name and examples
2. Adding a method for running cucumber scenario by passing every scenario name
3. Throw exception if the scenario name is not present
4. Run every scenario as a @Test kind 

## Context & Motivation
This will help in achieving the scenario level runtime options for the QA for handling events such as creating screenshots or onSuccess things to be done.
Feature level Test helps in solving the issues on modular level. But Scenario level test will help in achieving the sub-functionalities and various other uses cases per module.

## Your Environment

* Operating System and version: Mac

**Comment by mpkorstanje** [comment]
Nothing to worry about. The current build is passing. 

A commit was pushed to the the PR to include attribution. This started a new build. Then the PR was merged and its branch deleted. All before travis could actually fetch the Branch.

**Comment by srilakshmi211** [comment]
Hello Team,

 I would like to know  if this was fixed -"Run each Scenario as a TestNG @Test".

In my automation framework I was using @BeforeTest and @AfterTest annotations but It executes before and after feature and not before and after each scenario.

Looking forward for your response.

Regards,
Sri

**Comment by mlvandijk** [comment]
@srilakshmi211 As you can see in the [CHANGELOG.md](https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md) #1174 was merged in v2.0.0

**Comment by srilakshmi211** [comment]
Hi Marit,

I am using the below gradle dependency:
    compile 'info.cukes:cucumber-java8:1.2.5'
    compile 'info.cukes:cucumber-testng:1.2.5'

v2.0.0 is not available.

Could you please suggest what should be done?

**Comment by mlvandijk** [comment]
@srilakshmi211 For v2.0.0 the group id is changed to io.cucumber.
Try replacing 'info.cukes' with 'io.cucumber'.

**Comment by mpkorstanje** [comment]
Please note the groupid has changed to io.cucumber

**Comment by srilakshmi211** [comment]
Awesome. Works like a charm now :) Thanks I somehow missed the documentation.
