### ISSUE TITLE
What's the solution for common steps definitions of all the project, like login and access to a specific space

### ISSUE THREAD

**Issue by fatenBAB** [cucumber/cucumber-jvm#1114]
In my project, there are some common steps, which is not professionnal to repeat them in each scenario, it will be nice to put them all in one class java and call them when needed,

BUT HOW TO DO THAT :(

**Comment by dkowis** [comment]
This isn't a support forum. It's only for bugs with the software.

Please use one of the other options listed here: https://cucumber.io/support
