### ISSUE TITLE
How can I write information to xml report

### ISSUE THREAD

**Issue by yJLiGit** [cucumber/cucumber-jvm#1119]
I use the plugin : junit: /report/testreport.xml to output test infomation to xml report.

I use "         scenario.write("message to testreport.xm"); ", but the message ""message to testreport.xm"" can not be written into the xml report.

May I know how to add custom information to cucumber  junit xml report?

Thank you.

**Comment by yJLiGit** [comment]
report issues

**Comment by mpkorstanje** [comment]
Please ensure that `/report/testreport.xml`  is a valid path in your OS and that your test execution has access to it. If you are using OSX or Unix try dropping the starting `/` from the path.

If this remains a persistent problem please create a new issue with enough sufficient information that allows us to reproduce the problem.
