### ISSUE TITLE
Cannot use Java method reference in lambda step definition (as stepdef body)

### ISSUE THREAD

**Issue by zyablic** [cucumber/cucumber-jvm#1126]
I'm using Java implementation of Cucumber-JVM. But I can't use method reference as step definition body as I get an exception: Caused by: cucumber.runtime.CucumberException: java.lang.IndexOutOfBoundsException: fromIndex = -1

**Expected Behavior**
I want to use step definition in the following way:
Given("I am on the page (.*)", Navigation::openPage);

But it only works as follows:
Given("I am on the page (.*)", (Navigation nav) -> nav.openPage());

**Context & Motivation**
cucumber-java8 encourages to use Java 8 syntax, but restricts method reference usage. It would be great to use method reference for more convenient programming.

**Environment**
* Version used: 1.2.5
* Build Tool: Maven 3.3.9
* JDK version: 1.8.0_121 (1.8.0_45, 1.8.0_51)
* Operating System and version: Windows 10

**Comment by mpkorstanje** [comment]
The current implementation of ConstantPoolTypeIntrospector doesn't understand typed instance method  references. It only looks at the argument types of the method, not the type it binds to.

However ConstantPoolTypeIntrospector does have all the information it needs to determine if the StepdefBody is a method reference or a lambda. Internally it uses `ConstantPool#getMemberRefInfoAt(int)` which a an array of the form `["ClassName", "methodName", "ArgumentTypes"]` which for a lambda looks like `["StepDefintionClass", "lambda$new", "ArgumentTypes"]`.

By return only the argument types for a lambda and returning the class name and argument types for everything else we can handle method references.

**Comment by mpkorstanje** [comment]
Found a better solution. References to an instance method of an arbitrary object of a particular type are always short exactly one argument.

Can you try building [support-java-8-method-references](https://github.com/cucumber/cucumber-jvm/tree/feature/support-java-8-method-references) locally and add a dependency to `io.cucumber:cucumber-java8:2.0.0-SNAPSHOT`? Note that the groupId has also changed.

This should solve the problem.

**Comment by mpkorstanje** [comment]
This fix will be available once 2.0.0 is done. Thanks for point it out!
