### ISSUE TITLE
Give Bjorn release karma

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-jvm#1132]
## Summary

In order to facilitate frequent releases, more people need to be able to do it. Currently only Aslak has release karma, and that means that when he's busy we can't do releases.

@aslakhellesoy can you make this happen as a priority, please? What are the steps?

**Comment by mpkorstanje** [comment]
@brasmusson I believe this has been resolved.

**Comment by brasmusson** [comment]
Yes, with the release of cucumber-jvm-deps v1.0.6 it is verified that I have everything needed to release maven project with the `io.cucumber` group id.
