### ISSUE TITLE
Is it possible to use regex with cucumber.options tags?

### ISSUE THREAD

**Issue by prasanta-biswas** [cucumber/cucumber-jvm#1141]
I want to run multiple cucumber feature tags. I don't want to mention all the tags in the command line because it can be tedious if there are lots of tags. Instead I want to provide a pattern of tags that will run all the tags which matches the pattern like -Dcucumber.options=" --tags @my-test*". This will run all the tags that matches @my-test pattern.

**Comment by mpkorstanje** [comment]
No. You can however use regular expressions in the `--name` argument to match scenario names.

**Comment by prasanta-biswas** [comment]
Don't you think it should be feature?

**Comment by mpkorstanje** [comment]
Not on its face no. To be able to make sensible use of a pattern your tags have a naming structure or convention that provides a meaning to it components. Your tags however should be the smallest components that have meaning.

So for example a tag like `@team-yellow-sprint-15-2017-jhon-doe-issue-1205` should be split up in `@team-yellow`, `@inception-sprint-15` `@inception-year-2017`, `@author-jhon-doe` and `@issue-1205`.

**Comment by mpkorstanje** [comment]
So the solution to your problem would be tag the scenarios or features you want to run with `@my-test`. It appears to be a unit of meaning and so it should be a tag.
