### ISSUE TITLE
Cucumber CLI runner stops abruptly without handling exceptions

### ISSUE THREAD

**Issue by mathan91** [cucumber/cucumber-jvm#1143]
I'm trying to find a way to Integrate JUNIT test methods with Cucumber to use in JMeter Load testing.

I'm clueless on why it's not executing the complete @Test method. Why it's stopping without any exceptions.

Below is the code,
````
@Test
public void runTest() throws Throwable {
    try {
        String[] getRequest = GetRequest.testValuesReturn();

**Main.main**(new String[]{"-g", "com.sanity.step.definition","-t", "@" +getRequest[1], "C:/Users/IBM_ADMIN/Documents/Automation/Performance Testing/PerformanceTesting/MyFeature.feature"});
        System.out.println("Print");
    } catch (Exception e) {
        e.printStackTrace();
    }
}  
```  `

The test runs until the last step defined in the feature file. Below is the feature file and last method.
`When Start the performance Test
When Open the Inventory Page
When Click on Seamless Switch`

And the last method,
`@When("^Click on Seamless Switch$")
public void Seamless_Switch() throws Throwable {    
    driver.baseDriver.findElement(By.id("seamlessSwitchButton")).click();
    log.info("Seamless switch is clicked");
    System.out.println("Click on Seamless Switch");
}`
It's printing until "Click on Seamless Switch". But the syso in @Test annotated method ("Print") is not printed in the console.

Why is it stopping without any exception? Because of this issue, in JMeter, I'm getting the following errors before even completion of the thread,
`2017/06/01 13:40:31 INFO  - jmeter.reporters.ResultCollector: Shutdown hook started 
 2017/06/01 13:40:31 INFO  - jmeter.reporters.ResultCollector: Shutdown hook ended  `

I'm not sure if there's an issue with CLI runner or Java libraries not able to handle it. 

I'm using Cucumber-Core 1.1.2 jar.

**Comment by mathan91** [comment]
I've just checked the code and it says there's a System.exit at the end. 
`public static void main(String[] argv) throws Throwable {
byte exitstatus = run(argv, Thread.currentThread().getContextClassLoader());
**System.exit(exitstatus);**
}` 

What if I need to execute some more lines of code after Main.main like the one I have mentioned above.

**Comment by mpkorstanje** [comment]
Try using [Main.run()](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/api/cli/Main.java#L30) instead. :)

**Comment by mpkorstanje** [comment]
Though you might want to use the [Cucumber JUnit runner](https://cucumber.io/docs/reference/jvm#junit-runner) instead of directly calling the CLI from a test. You can use [@CucumberOptions](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/api/CucumberOptions.java) to pass configuration.

**Comment by mathan91** [comment]
@mpkorstanje . Thanks for taking your time to comment. It still stops when I use `Main.run()` When I debug it, it goes to the main method still. Am I using a older Cucumber core version (1.1.2)? 
Also, it's not a void method, Do I need to change my code to expect a variable in return? 
`try {
String[] getRequest = GetRequest.testValuesReturn();
Main.run(new String[]{"-g", "com.sanity.step.definition","-t", "@New", "C:/Users/IBM_ADMIN/Documents/Automation/Performance Testing/PerformanceTesting/MyFeature.feature"}, ClassLoader.getSystemClassLoader());
System.out.println("Print");
} catch (Exception e) {
e.printStackTrace();
}` 
Thanks in advance!

**Comment by mpkorstanje** [comment]
1.1.2? Cucumbers are perishable you know. :D  I can't help you with a version that old really. Either upgrade or workout what run does and do that all in your unit test.

I'll close the issue because it doesn't appear to be a problem with the latest release.
