### ISSUE TITLE
Feature Request: Custom Reporting capabilities or Increment Scenario Object info in hooks

### ISSUE THREAD

**Issue by ppadialitrs** [cucumber/cucumber-jvm#1157]
## Summary
Hi all,

In order to integrate cucumber-jvm execution/reporting with third party services i found some limitations (maybe due my ignorance).
1. If i use an After hook, is a good solution since it is called after each scenario but i found that Scenario object doesn't contains information about the errors and the steps. (this is the option i have implemented but would be nice to also post a comment with the error details so devs can take a look easily).

Taking a look to the ScenarioImpl class it hass already a set of stepsResults property but is not exposed so i can't access to them. I can't expose them easily, but since this object is also being used in Before hook where there's no result yet im not sure if this is the best choice.

2. Another solution could be add a new capability to the TestNGCucumberRunner to specify some additional Reporters (it has a property `TestNgReporter reporter = new TestNgReporter(System.out);` but is not used in any place).

In any case, i will need to raise a PR, but i want to know which option you think is better, or if i'm missing something, please let me know.

Thanks a lot.

**Comment by mpkorstanje** [comment]
Rather then using Hooks or trying to hack Cucumber I reckon the best avenue of approach would be to create your own formatter/reporter. These can be passed as a plug through `@CucumberOptions`.

For a working example either look the [HTMLFormatter](https://github.com/cucumber/cucumber-jvm/blob/v1.2.5/core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java) or the [ExtentCucumberFormatter](https://github.com/email2vimalraj/CucumberExtentReporter/blob/master/src/main/java/com/cucumber/listener/ExtentCucumberFormatter.java).

Beware that we're working on 2.0.0 right now. You may need to do a rewrite.

**Comment by ppadialitrs** [comment]
i will take a look tomorrow, thank you very much

**Comment by ppadialitrs** [comment]
it worked as a charm, thank you very much!!!
