### ISSUE TITLE
cucumber-testng: tearDownClass() does not print run summary

### ISSUE THREAD

**Issue by lucianovdveekens** [cucumber/cucumber-jvm#1173]
## Summary

The `@AfterClass` step  AbstractTestNGCucumberTests#tearDownClass fails to print the cucumber run summary despite whether all tests are green or not. 

In AbstractTestNGCucumberTests there's the following failing snippet:
```java 
@AfterClass(alwaysRun = true)
public void tearDownClass() throws Exception {
    testNGCucumberRunner.finish();
}
```
and TestNGCucumberRunner#finish looks like this:

```java
public void finish() {
    runtime.getEventBus().send(new TestRunFinished(runtime.getEventBus().getTime()));
    runtime.printSummary();
}
```
Sending the `TestRunFinished` event to the event bus triggers `TestNGReporter`'s `runFinishHandler` to close the `System.out` print stream, which affects other event handlers and code still wanting to write to sysout, e.g. `runtime.printSummary()` in the method above but also actual TestNG listeners.

```java
private EventHandler<TestRunFinished> runFinishHandler = new EventHandler<TestRunFinished>() {
    @Override
    public void receive(TestRunFinished event) {
        out.close();
    }
};
```

## Possible Solution

Don't close the output stream in `runFinishHandler` or remove the whole handler because it does nothing else.

## Steps to Reproduce (for bugs)

Run a Cucumber TestNG test using the `cucumber-testng-2.0.0-SNAPSHOT.jar` library.

**Comment by brasmusson** [comment]
The `TestNGReporter` does not know (and should not know) if it is `System.out` it is printing to, so it should call `close()`. It is the `NiceAppendable` that should avoid to close `System.out`.
