### ISSUE TITLE
Scala reuses step defintions between scenarios and examples

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1176]
## Summary

Scala reuses step definitions between scenarios and examples. This is a bad practice as it can cause tests to interfere with each other.

## Expected Behavior

```feature
Feature: Steps are not reused between examples

  Scenario Outline: Steps are not reused between examples
    Given I have '<Initial Cukes>' cukes in the jar
    When I eat '<Eaten>' cukes
    Then There are '<Remaining>' cukes in the jar
    And I am <Fullness>

    Examples:
      | Initial Cukes | Eaten | Remaining | Fullness |
      | 6             | 2     | 4         | full     |
      | 4             | 1     | 3         | not full |
      | 6             | 2     | 4         | full     |
      | 4             | 1     | 3         | not full |
```

And implementing _I eat x cuckes_ as 

```scala
class StepsDefs extends ScalaDsl with EN  {

  private var amFull = false

  When("""^I eat '(\d+)' cukes$""") {
    cukesEaten: Int => {
      cukeCount -= cukesEaten
      if (cukesEaten >= 2) amFull = true
    }
  }
}
```
should pass.

## Current Behavior

Will result in a failing test as the `StepsDefs` is not recreated between test and so `amFull` is never cleared.

## Possible Solution

`ScalaBackend.loadGlue` both loads and instantiates classes and objects. The instantiation of classes should be moved into `ScalaBackend.buildWorld`

## Steps to Reproduce (for bugs)

Run: [cucumber-jvm/tree/reproducer-scala-reuses-step-definitions](https://github.com/cucumber/cucumber-jvm/tree/reproducer-scala-reuses-step-definitions)

**Comment by brasmusson** [comment]
This and #755 seems to be duplicates.

**Comment by mpkorstanje** [comment]
Indeed.
