### ISSUE TITLE
[Build] Trusty with oraclejdk7 is not supported

### ISSUE THREAD

**Issue by nicosmaris** [cucumber/cucumber-jvm#1185]
## Summary

After forking this repo and enabling my travis repo, the build for java 7 failed as travis does not support it since june 14.

https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879

## Expected Behavior

Without changes, the build at my repository should stop at 'mvn deploy' step, not earlier.

## Current Behavior

https://travis-ci.org/nicosmaris/cucumber-jvm/jobs/256635147

## Possible Solution

We can remove the following line and the next one to drop support for java 7.

https://github.com/nicosmaris/cucumber-jvm/blob/master/.travis.yml#L23

## Steps to Reproduce (for bugs)

Fork and build

## Context & Motivation

Fork and build before doing anything else

## Your Environment

https://travis-ci.org/nicosmaris/cucumber-jvm/jobs/256635147

**Comment by mpkorstanje** [comment]
Thanks for pointing this out! 

I have removed OracleJdk7 from the build.
