### ISSUE TITLE
[Junit] Scenario/Feature names may not be longer then 255 characters

### ISSUE THREAD

**Issue by nicosmaris** [cucumber/cucumber-jvm#1186]
## Summary

At 1.2.5 we need to write a scenario outline with examples whose rows are very long. For each row, a txt and an xml file is generated with TEST- prefix and if the row is longer than 255 characters we get a 'File name too long' exception due to the filename length restriction imposed by Linux.

## Expected Behavior

Examples should not be limited by their length.

## Current Behavior

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test (integration-test) on project cms-automation: Execution integration-test of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test failed: java.lang.RuntimeException: org.apache.maven.surefire.report.ReporterException: When writing report: target/failsafe-reports/TEST-| 1 | issue range | Code:issue range-1, bundle_code:bundle-1, Description:issue range-1, area:Staging, publication-title:All Categories, from-volume:1, from-issue:1, to-volume:2, to-issue:2, issue-type:all | uid:1a222e4d-b2f7-4844-b8ef-d94359e88d30 |.xml (File name too long)

## Possible Solution

The following commit at a branch from 1.2.5 (related to https://github.com/cucumber/cucumber-jvm/pull/1002) has a workaround and a test that passes.

commit:
https://github.com/nicosmaris/cucumber-jvm/commit/b486e0654f0048f839cc4f7efe05422541de9224

However, this workaround cannot be merged to master branch as the file is not there at all and the workaround takes action only if the examples has a uid anywhere like in hiptest.

## Steps to Reproduce (for bugs)

You can fork my repo for further discussion if necessary.

## Context & Motivation

We can discuss a fix in this repo or a change in our source code that uses this repo but we cannot change our scenario outline and examples section and we cannot use any snapshot like 2.0.0-SNAPSHOT.

In case this is a treated as a bug with priority, will it be at 1.2.6 or at 2.0.0?

## Your Environment

Ubuntu 16.04

**Comment by mpkorstanje** [comment]
There won't be a 1.2.6 to fix this. The next release will be 2.0.0.


I don't think your solution is the proper one. Rather then relying on some 'magic' values in the title the Junit Description should use 


https://github.com/cucumber/cucumber-jvm/blob/master/junit/src/main/java/cucumber/runtime/junit/PickleRunners.java#L150



It is

**Comment by mpkorstanje** [comment]
There won't be a 1.2.6 to fix this. The next release will be 2.0.0.

In 2.0.0 things have changed a bit. By default we'll no longer treat a scenario as a test suite and its steps as tests. Rather the feature is mapped to a suite and each scenario is a test. The old behavior can be enabled by passing the `junit="--step-notifications"` through `@CucumberOptions`.

As such we'll now have a problem with extremely long scenario and feature title. I think a proper solution would use the filename part of Scenario or Features uri.

You can find the file name functionality in the [PickleRunners](https://github.com/cucumber/cucumber-jvm/blob/master/junit/src/main/java/cucumber/runtime/junit/PickleRunners.java#L150).

**Comment by brasmusson** [comment]
> The old behavior can be enabled by passing the junit="--step-notifications" through @CucumberOptions.

Well, not quite, no names are ever created from the example row content (not even with `junit="--step-notifications"`). So in practice your problem will no occur in v2.0.0 (which was about the names constructed from the example row content as far as I could tell), even though there is no explicit limitation of the name constructed in the JUnit module. You should try the 2.0.0-SNAPSHOT, it is available through the Sonatype snapshot repository. Do note the changed groupId
```
<repository>
    <id>sonatype-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>

<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <scope>test</scope>
</dependency>
```

**Comment by nicosmaris** [comment]
Thanks. When do you expect to release 2.0.0?

**Comment by mlvandijk** [comment]
@nicosmaris The answers on Gitter and Slack respectively are "When we're done" and "really soon now". All the work is done (https://github.com/cucumber/cucumber-jvm/milestone/3) and a blog is being drafted to announce it (https://github.com/cucumber/website/pull/234).
In the mean time you can use the snapshot version, see here: https://cucumber.io/docs/reference/jvm#snapshot-releases

**Comment by nicosmaris** [comment]
Thanks for the links, I'll inform you by the end of this month.

**Comment by mlvandijk** [comment]
@nicosmaris Thanks!

**Comment by mlvandijk** [comment]
@nicosmaris Cucumber-jvm v 2.0.0 was just released: https://cucumber.io/blog/2017/08/29/announcing-cucumber-jvm-2-0-0

**Comment by mlvandijk** [comment]
@nicosmaris Any updates on this?

**Comment by nicosmaris** [comment]
At 1.2.5 the filename length is limited by the filesystem: https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations

We are importing in our classes several classes of 1.2.5 that are breaking on 2.0.0 and we don't plan to move to 2.x any time soon. If you don't plan to write a test about it, you can close this ticket.

**Comment by mlvandijk** [comment]
@nicosmaris Thanks or the update!
