### ISSUE TITLE
Json file required for cucumber report not generated.

### ISSUE THREAD

**Issue by uday1955** [cucumber/cucumber-jvm#1188]
I am running cucumber tests using gradle cucumber task without any execution issues. But i don't see the json file for test results. I looked at existing issues and have similar setup. Wondering if someone can assist me if I am missing any.

**My build.gradle setup**

testCompile 'info.cukes:cucumber-java:1.2.5'

/ setup the cucumber task
task cucumber() {
    dependsOn assemble, compileTestJava
    doLast {
        javaexec {
            main = "cucumber.api.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.acceptanceTest.runtimeClasspath + sourceSets.main.output + sourceSets.test.output
            args = ['--plugin', 'pretty', '--glue', 'com.company.project', 'src/acceptancetest/resources']

        }

    }
    test {
        reports {
            junitXml.enabled = false
            html.enabled = true
        }
    }
}

**Runner Setup:**
@RunWith(Cucumber.class)
@CucumberOptions(
format = {"html:target/TestResults/html/P2PMobileNumberValidation/cucumber-html-report","json:target/TestResults/json/P2PMobileNumberValidation-reports.json"},
features = {"src/acceptancetest/resources/com/company/project/features/P2PMobileNumberValidation.feature" },
tags = "@mobilenumber-validation-service-acceptance",
glue = {"com.company.project.steps"})

**Comment by brasmusson** [comment]
> I am running cucumber tests using gradle cucumber task

Your gradle cucumber task does not specify that a json file should be created, you have to add that to the args definition of the task, something like:
```
args = ['--plugin', 'pretty', '--plugin', 'json:path/file.json', '--glue', 'com.company.project', 'src/acceptancetest/resources']
```

> Runner Setup

In your gradle cucumber task you specify the use of the Cucumber command line runner (`cucumber.api.cli.Main`), then nothing in any runner class is used. A runner class can be used to the execution of cucumber features, but then you have to tell gradle to execute that class as a JUnit test class.

**Comment by uday1955** [comment]
Thanks for the quick response @brasmusson . Was able to fix with the change you suggested
