### ISSUE TITLE
Can't load applicationContext.xml in Cucumber Testing using Spring

### ISSUE THREAD

**Issue by ruchit31** [cucumber/cucumber-jvm#1191]
Failed to load application context for me. I am running tests using cucumber and I have defined features and steps file. I have ("Run.java" class) which has annotation @runwith(Cucumber.class) which is to be ran for cucumber test, but it says application context not found. I have include @contextconfiguration(locations = { "classpath:applicationContext.xml" }) in steps file. Can someone please look into this and provide me some help ? Thank you!

**Comment by mpkorstanje** [comment]
This could be anything. Most probably you haven't configured your class path properly or the application context isn't on the class path, but you haven't provided enough information for us to tell.
