### ISSUE TITLE
cucumber-guice 2.0.0-SNAPSHOT is not found

### ISSUE THREAD

**Issue by cdiminutto** [cucumber/cucumber-jvm#1193]
## Summary
When trying to update to the 2.0.0-SNAPSHOT the code is failing to find the one for cucumber-guice.
The rest of the io.cucumber dependencies are being correctly downloaded.
This is the dependencies I'm currently using:
`<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-jvm</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <type>pom</type>
</dependency>
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-junit</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <type>jar</type>
</dependency>
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <type>jar</type>
</dependency>
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-guice</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <type>jar</type>
</dependency>`

I was able to manually find the cucumber-guice 2.0.0-SNAPSHOT in oss.sonatype, but for some reason it's still failing to get it when doing a mvn clean -U install:
https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-guice/2.0.0-SNAPSHOT/

This is the console error:

> [projectRoot]>mvn clean -U install
[INFO] ------------------------------------------------------------------------
[INFO] Building qa-fw-core 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://internal-jenkins-build-server-1925901387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/org/seleniumhq/selenium/selenium-api/maven-metadata.xml
Downloaded: http://internal-jenkins-build-server-1925901387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/org/seleniumhq/selenium/selenium-api/maven-metadata.xml (3.0 kB at 1.5 kB/s)
Downloading: http://internal-jenkins-build-server-1925901387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/org/seleniumhq/selenium/selenium-support/maven-metadata.xml
Downloaded: http://internal-jenkins-build-server-1925901387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/org/seleniumhq/selenium/selenium-support/maven-metadata.xml (3.2 kB at 2.1 kB/s)
Downloading: http://internal-jenkins-build-server-1925901387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/io/cucumber/cucumber-jvm/2.0.0-SNAPSHOT/maven-metadata.xml
Downloading: http://internal-jenkins-build-server-1925901387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/io/cucumber/cucumber-junit/2.0.0-SNAPSHOT/maven-metadata.xml
Downloading: http://internal-jenkins-build-server-1925901387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/io/cucumber/cucumber-core/2.0.0-SNAPSHOT/maven-metadata.xml
Downloading: http://internal-jenkins-build-server-1925901387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/io/cucumber/cucumber-java/2.0.0-SNAPSHOT/maven-metadata.xml
Downloading: http://internal-jenkins-build-server-1925901387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/io/cucumber/cucumber-guice/2.0.0-SNAPSHOT/maven-metadata.xml
Downloading: http://internal-jenkins-build-server-1925901387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/io/cucumber/cucumber-guice/2.0.0-SNAPSHOT/cucumber-guice-2.0.0-SNAPSHOT.pom
[WARNING] The POM for io.cucumber:cucumber-guice:jar:2.0.0-SNAPSHOT is missing, no dependency information available
Downloading: http://internal-jenkins-build-server-1925901387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/io/cucumber/cucumber-guice/2.0.0-SNAPSHOT/cucumber-guice-2.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] qa-fw ........................................ SUCCESS [  0.173 s]
[INFO] qa-fw-core ......................................... FAILURE [ 14.518 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.786 s
[INFO] Finished at: 2017-08-09T12:02:33-03:00
[INFO] Final Memory: 12M/206M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project qa-fw-core: Could not resolve dependencies for project com..qa:qa-fw-core:jar:1.0-SNAPSHOT: Could not find artifact io.cucumber:cucumber-guice:jar:2.0.0-SNAPSHOT in nexus (http://internal-jenkins-build-server-19259
01387.us-east-1.elb.amazonaws.com:8081/repository/maven-public/) -> [Help 1]

## Expected Behavior
The cucumber-guice 2.0.0-SNAPSHOT should be found and downloaded, along with the rest of the io.cucumber dependencies.

## Current Behavior
The cucumber-guice 2.0.0-SNAPSHOT is not found, but the rest of the io.cucumber dependencies are correctly downloaded.

## Steps to Reproduce (for bugs)

1. Add the following dependency to the pom:

> <dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-guice</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <type>jar</type>
</dependency>

2. Do a `mvn clean -U install`
3. Notice that the dependency couldn't be found and the process will fail

## Context & Motivation
I'm trying to migrate from cucumber-jvm version 1.2.5 to 2.0.0 to see if some of the execution bugs are fixed in that version:
https://github.com/cucumber/cucumber-jvm/pull/1134
https://github.com/cucumber/cucumber-jvm/issues/1120

The projects are using Guice for DI, that's why the interest in updating cucumber-guice too.

## Your Environment
* Version used: 2.0.0-SNAPSHOT
* Operating System and version: Windows 7 Ultimate x64
* Maven version: 3.5.0
* JAVA version: 1.8.0_131

**Comment by mpkorstanje** [comment]
Did you add the sonatype repository?

https://cucumber.io/docs/reference/jvm#snapshot-releases

**Comment by cdiminutto** [comment]
Yep, and the result is the same: all the io.cucumber dependencies are downloading just fine, except the cucumber-guice one:
![no_guice](https://user-images.githubusercontent.com/7122314/29220752-7ed09c06-7e92-11e7-8e16-beeb9dd391ff.JPG)

**Comment by mpkorstanje** [comment]
I can't reproduce the issue locally. After cleaning my m2 repository the dependency downloads as expected. I do notice however that you are caching your dependencies in a Nexus. Please try to remove any potential confounding factors first.

If you can still reproduce this issue after removing all confounding factors please reopen this ticket and provide a minimal reproducer. Preferably in the form of a Github repository build by [Travis CI](https://travis-ci.org/).

```
mpkorstanje@localvoid:~/Projects/cucumber$ rm -rf ~/.m2/repository/io/cucumber/
mpkorstanje@localvoid:~/Projects/cucumber$ mvn clean compile
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building cucumber 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-java8/2.0.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-java8/2.0.0-SNAPSHOT/maven-metadata.xml (778 B at 0.5 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-java8/2.0.0-SNAPSHOT/cucumber-java8-2.0.0-20170811.131454-76.pom
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-java8/2.0.0-SNAPSHOT/cucumber-java8-2.0.0-20170811.131454-76.pom (5 KB at 13.8 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-jvm/2.0.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-jvm/2.0.0-SNAPSHOT/maven-metadata.xml (602 B at 1.8 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-jvm/2.0.0-SNAPSHOT/cucumber-jvm-2.0.0-20170811.130920-74.pom
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-jvm/2.0.0-SNAPSHOT/cucumber-jvm-2.0.0-20170811.130920-74.pom (39 KB at 84.9 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-java/2.0.0-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-java/2.0.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-java/2.0.0-SNAPSHOT/maven-metadata.xml (777 B at 2.4 KB/sec)
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-java/2.0.0-SNAPSHOT/maven-metadata.xml (777 B at 1.4 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-java/2.0.0-SNAPSHOT/cucumber-java-2.0.0-20170811.130944-74.pom
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-java/2.0.0-SNAPSHOT/cucumber-java-2.0.0-20170811.130944-74.pom (7 KB at 21.5 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-core/2.0.0-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-core/2.0.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-core/2.0.0-SNAPSHOT/maven-metadata.xml (777 B at 2.6 KB/sec)
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-core/2.0.0-SNAPSHOT/maven-metadata.xml (777 B at 2.4 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-core/2.0.0-SNAPSHOT/cucumber-core-2.0.0-20170811.130926-74.pom
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-core/2.0.0-SNAPSHOT/cucumber-core-2.0.0-20170811.130926-74.pom (5 KB at 13.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-jvm-deps/1.0.6/cucumber-jvm-deps-1.0.6.pom
Downloading: https://repo.maven.apache.org/maven2/io/cucumber/cucumber-jvm-deps/1.0.6/cucumber-jvm-deps-1.0.6.pom
Downloaded: https://repo.maven.apache.org/maven2/io/cucumber/cucumber-jvm-deps/1.0.6/cucumber-jvm-deps-1.0.6.pom (7 KB at 66.6 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/gherkin/4.1.3/gherkin-4.1.3.pom
Downloading: https://repo.maven.apache.org/maven2/io/cucumber/gherkin/4.1.3/gherkin-4.1.3.pom
Downloaded: https://repo.maven.apache.org/maven2/io/cucumber/gherkin/4.1.3/gherkin-4.1.3.pom (6 KB at 156.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/tag-expressions/1.0.1/tag-expressions-1.0.1.pom
Downloading: https://repo.maven.apache.org/maven2/io/cucumber/tag-expressions/1.0.1/tag-expressions-1.0.1.pom
Downloaded: https://repo.maven.apache.org/maven2/io/cucumber/tag-expressions/1.0.1/tag-expressions-1.0.1.pom (5 KB at 159.3 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-junit/2.0.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-junit/2.0.0-SNAPSHOT/maven-metadata.xml (778 B at 1.5 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-junit/2.0.0-SNAPSHOT/cucumber-junit-2.0.0-20170811.130928-74.pom
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-junit/2.0.0-SNAPSHOT/cucumber-junit-2.0.0-20170811.130928-74.pom (3 KB at 8.6 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-picocontainer/2.0.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-picocontainer/2.0.0-SNAPSHOT/maven-metadata.xml (786 B at 2.7 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-picocontainer/2.0.0-SNAPSHOT/cucumber-picocontainer-2.0.0-20170811.130950-74.pom
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-picocontainer/2.0.0-SNAPSHOT/cucumber-picocontainer-2.0.0-20170811.130950-74.pom (4 KB at 10.7 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-guice/2.0.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-guice/2.0.0-SNAPSHOT/maven-metadata.xml (778 B at 2.7 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-guice/2.0.0-SNAPSHOT/cucumber-guice-2.0.0-20170811.131050-74.pom
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-guice/2.0.0-SNAPSHOT/cucumber-guice-2.0.0-20170811.131050-74.pom (2 KB at 7.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/gherkin/3.2.0/gherkin-3.2.0.pom
Downloading: https://repo.maven.apache.org/maven2/io/cucumber/gherkin/3.2.0/gherkin-3.2.0.pom
Downloaded: https://repo.maven.apache.org/maven2/io/cucumber/gherkin/3.2.0/gherkin-3.2.0.pom (5 KB at 115.6 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/gherkin-jvm-deps/1.0.4/gherkin-jvm-deps-1.0.4.pom
Downloading: https://repo.maven.apache.org/maven2/io/cucumber/gherkin-jvm-deps/1.0.4/gherkin-jvm-deps-1.0.4.pom
Downloaded: https://repo.maven.apache.org/maven2/io/cucumber/gherkin-jvm-deps/1.0.4/gherkin-jvm-deps-1.0.4.pom (5 KB at 132.9 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/gherkin/4.1.3/gherkin-4.1.3.jar
Downloading: https://repo.maven.apache.org/maven2/io/cucumber/gherkin/4.1.3/gherkin-4.1.3.jar
Downloaded: https://repo.maven.apache.org/maven2/io/cucumber/gherkin/4.1.3/gherkin-4.1.3.jar (334 KB at 2692.9 KB/sec)
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ cucumber ---
[INFO] Deleting /home/mpkorstanje/Projects/cucumber/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cucumber ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ cucumber ---
[INFO] Nothing to compile - all classes are up to date
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.667 s
[INFO] Finished at: 2017-08-11T17:54:23+02:00
[INFO] Final Memory: 16M/164M
[INFO] ------------------------------------------------------------------------
```

**Comment by cdiminutto** [comment]
You were right, the problem was that the project was searching in the nexus repo only. Thanks for the help!
