### ISSUE TITLE
Cannot generate cucumber json report with testng.xml as testNGCucumberRunner.runScenario method

### ISSUE THREAD

**Issue by yisake** [cucumber/cucumber-jvm#1198]
## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.##testng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
suite name="Suite" parallel="methods" thread-count="200"
 	test name="测试用例demo"
 		classes
        	class name="cucumberTraining.RestDemo"class
        classes
    test
 suite

##RestDemo.java
package cucumberTraining;

import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import cucumber.api.testng.PickleEventWrapper;
import cucumber.api.testng.TestNGCucumberRunner;
import utils.BaseTestCase;

public class RestDemo extends BaseTestCase {
	
	private TestNGCucumberRunner testNGCucumberRunner;
	
    @BeforeMethod
    public void setUp() throws Exception {
        testNGCucumberRunner = new TestNGCucumberRunner(TrainingRunner.class);    	
    }
	
	@Test
	public void test_1 ( ) throws Throwable {
		Object[][] scenarios = testNGCucumberRunner.provideScenarios();
		System.out.println("scenarios.length:"+scenarios.length);
		System.out.println(scenarios[0].length);
        Object[] scenario = scenarios[0];
        PickleEventWrapper pickleEvent = (PickleEventWrapper) scenario[0];
		testNGCucumberRunner.runScenario(pickleEvent.getPickleEvent());
	}
}

##TrainingRunner.java
package cucumberTraining;

import org.junit.runner.RunWith;
import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import cucumber.api.testng.AbstractTestNGCucumberTests;

@CucumberOptions (
		monochrome = true,
		features = "src/test/java/features", 
		plugin = {"pretty", "html:target/cucumber-html-reportdiary","json:target/json-report/training.json"},
		glue = {"cucumberTraining"},//指定到报名即可，指定到类会报错
		tags = {"@测试training用例"},
		strict = true
		)
public class TrainingRunner extends AbstractTestNGCucumberTests {
}

2.Run as "mvn test"
3.Check the target folder(error, the training.json is empty, there's no json result in the file.

## Your Environment

* Version used: 2.0.0-SNAPSHOT
* Operating System and version: Windows7
* Link to your project:

**Comment by yisake** [comment]
'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite" parallel="methods" thread-count="200">
 	<test name="测试用例demo">
 		<classes>
        	<class name="cucumberTraining.RestDemo"></class>
        </classes>
    </test>
</suite>'''

**Comment by yisake** [comment]
Does any body looking into this? ~~

**Comment by aslakhellesoy** [comment]
Not that I'm aware of

**Comment by brasmusson** [comment]
When you don't let your runner class inherit from `AbstractTestNGCucumberTests`, which is the simple way to create a runner class (see the [java-calculator-testng example](https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-calculator-testng)), you need to note the importance of using and `@AfterClass` method to finish the execution of Cucumber-JVM, see the [example runner class](https://github.com/cucumber/cucumber-jvm/blob/master/examples/java-calculator-testng/src/test/java/cucumber/examples/java/calculator/RunCukesByCompositionTest.java#L36-L39) for that case in the example

**Comment by yisake** [comment]
@brasmusson  

Many thanks, another quesion, how can I run a single Scenario a in a @Test method not all scenarios as below.

    @Test(groups = "cucumber", description = "Runs Cucumber Feature", dataProvider = "scenarios")
    public void scenario(PickleEventWrapper pickleEvent, CucumberFeatureWrapper cucumberFeature) throws Throwable {
        testNGCucumberRunner.runScenario(pickleEvent.getPickleEvent());
    }
