### ISSUE TITLE
Spring-mybatis return NullPointer in stepdefination(How can I integrate Spirng-mybatis with cucumber-java)

### ISSUE THREAD

**Issue by yisake** [cucumber/cucumber-jvm#1203]
## Current Behavior
I use Spring-mybatis with cucumber-jvm and testng, in testng @Test method I can use the @Autowire  mybatis mapper normally,but in stepdefination return Null Pointer.

~~~
~~~
## Steps to Reproduce (for bugs)

1. In this situation, execution is right.

##CukesRunner.java
public class CukesRunner extends BaseTestCase {
	@Autowired
	PpdaiBidMapper ppdaiBidMapper;	
	
    @Test
    public void scenario( ) throws Throwable {
    	PickleEventWrapper pickleEvent = (PickleEventWrapper) this.scenarios[0][0];
    	testNGCucumberRunner.runScenario(pickleEvent.getPickleEvent());
    	System.out.println("Print bid mapper listingid "+ppdaiBidMapper.findOne(9).getLenderid());
    }
##StepDefination.java
public class StepDefinitionTest {
	String url = "https://www.baidu.com/";
	
	@When("^I have the current testdiary url$")
	public void i_have_the_current_testdiary_url() throws Throwable {
		System.out.println("Thread id:"+Thread.currentThread().getId());
		Thread.sleep(3000);
	}

2.In this condition, return Null Pointer.
##CukesRunner.java
public class CukesRunner extends BaseTestCase {	
    @Test
    public void scenario( ) throws Throwable {
    	PickleEventWrapper pickleEvent = (PickleEventWrapper) this.scenarios[0][0];
    	testNGCucumberRunner.runScenario(pickleEvent.getPickleEvent());
    }
##StepDefination.java
public class StepDefinitionTest {
	@Autowired
	PpdaiBidMapper ppdaiBidMapper;

	@ When("^I have the current testdiary url$")
	public void i_have_the_current_testdiary_url() throws Throwable {
		System.out.println("Thread id:"+Thread.currentThread().getId());
    	        System.out.println("Print bid mapper listingid "+ppdaiBidMapper.findOne(9).getLenderid());
		Thread.sleep(3000);
	}
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by yisake** [comment]
I have a question that Can cucumber-jvm work with spring-boot?

**Comment by mpkorstanje** [comment]
We should be able to. Have a look at the [spring-txn](https://github.com/cucumber/cucumber-jvm/tree/master/examples/spring-txn) example. 

Right now I can't help you with your problem. There just isn't enough information to reproduce anything. Please create a [minimal complete verifiable example](https://stackoverflow.com/help/mcve).
