### ISSUE TITLE
Checkstyle warnings on throwing Throwables in Step Definitions

### ISSUE THREAD

**Issue by filfreire** [cucumber/cucumber-jvm#1207]
## Summary

If a given Cucumber Java project uses [CheckStyle](http://checkstyle.sourceforge.net/), one of the warnings raised is the `IllegalThrowsCheck` for Step Definitions, because, by default, they throw a Throwable.

## Expected Behaviour

We could try to improve the default throws of step definitions to ensure that types (Like Error or Throwable) are not declared to be thrown and are not allowed.

## Current Behavior
The current behaviour is that by default, we allow throwing Throwables.

## Context & Motivation
Like mentioned above, if a given Cucumber Java project uses [CheckStyle](http://checkstyle.sourceforge.net/) and depends on its validations, a common failure is the throwing of Throwables.

**Comment by mpkorstanje** [comment]
It is not required for a step definition to declare any exceptions thrown. You can remove these to satisfy your check style.

Now I'm assuming that you are using an IDE plugin which uses the `SnippetGenerator`. By default the `JavaSnippet` declares `Throwable` which is indeed a bit of overkill. `Exception` should be sufficient.
