### ISSUE TITLE
Jars missing from the snapshot repo

### ISSUE THREAD

**Issue by LCartwright** [cucumber/cucumber-jvm#1228]
Hi, I'm trying to get the latest snapshot with the following `pom.xml` config however maven is complaining that it could not resolve the jar artifact `Could not find artifact io.cucumber:cucumber-jvm:jar:2.0.2-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)`
```xml
<dependency>
  <groupId>io.cucumber</groupId>
  <artifactId>cucumber-jvm</artifactId>
  <version>2.0.2-SNAPSHOT</version>
  <scope>test</scope>
</dependency>
...
<repository>
  <id>sonatype-nexus-snapshots</id>
  <url>https://oss.sonatype.org/content/repositories/snapshots</url>
  <snapshots>
      <enabled>true</enabled>
  </snapshots>
</repository>
```
A quick peek in https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-jvm/2.0.2-SNAPSHOT/ seems to confirm that the jar files are missing. 2.0.0-SNAPSHOT and 2.0.1-SNAPSHOT are in the same state.

**Comment by aslakhellesoy** [comment]
There is no `cucumber-jvm` artifact. If you're using Java7, use `cucumber-java`, Java8, use `cucumber-java8`, Clojure, use `cucumber-clojure` etc.

If you want to launch Cucumber from JUnit you also need `cucumber-junit`

**Comment by LCartwright** [comment]
@aslakhellesoy thanks for clearing that up for me
