### ISSUE TITLE
RuntimeOptions.cucumberfeatures method is broken in latest master

### ISSUE THREAD

**Issue by abhisheksreepal** [cucumber/cucumber-jvm#1230]
## Summary
Following method, cucumberFeatures in RuntimeOptions class is not returning filtered cucumber features

## Expected Behavior
Based on arguments passed from cli, cucumberFeatures method should return filtered features.
This is working fine on cucumber-jvm 1.2.5

## Current Behavior
 ```

cucumberFeatures is not returning filtered features based on args passed
```
        

~~~
~~~

## Steps to Reproduce (for bugs)

**Precondition**:

Multiple cucumber feature files are present under resources folder and **each scenarios have unique tags associated to it**. 

For example,
`args -> [--plugin, pretty, --plugin, html:uiwebtest/output/cucumber/html, --plugin, json:uiwebtest/output/cucumber/json/cucumber.json, -t, not @pending and not @wip and not @defect and not @manual and @settings_test_1, --glue, com.cuke.webrtc.tests, uiwebtest/src/main/resources]
`

**Steps:**

```
RuntimeOptions opt = new RuntimeOptions(args);
List<CucumberFeature> cucumberFeatures = opt.cucumberFeatures(new MultiLoader(Thread.currentThread().getContextClassLoader()),new EventBus(TimeService.SYSTEM));

**Current Behaviour**: cucumberFeatures contains all features and not filtered based on args passed
For above args, It should return only 1 feature(which has a scenario associated to tag @settings_test_1)



```
Note: 

> It is working fine with cucumber-jvm 1.2.5

## Context & Motivation

Motivation:            

> Run cucumber scenarios parallelly (each scenario are independent)

How do we do it:   

> Each scenario will have a unique tag associated with it.
>                               From build.gradle, we get all filtered scenario tags and run each tag on separate 
>                                JVM process. During this, we consume RuntimeOptions class as we don't want to 
>                               re-write logic to get filtered scenarios

 

## Your Environment

* Version used: cucumber-jvm 2.0.1
* Operating System and version: Macos Sierra 
* Link to your project:

**Comment by brasmusson** [comment]
The class [`cucumber.runtime.RuntimeOptions`](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/RuntimeOptions.java), is not in a `cucumber.api.*` package, and is therefore not considered to part of the public API. Yes, its semantic has changed in v2.0.0, and the underlying reason is that the Gherkin library has changed substantially (when upgraded from v2.12.2 to v4.1.3), but it is not broken. When you use internal API:s, they may change at any time.

**Comment by abhisheksreepal** [comment]
@brasmusson Thanks for the reply. 
Could you direct me if any API exists for above problem or any other way?

Thanks,
Abhishek

**Comment by mpkorstanje** [comment]
I'd recommend looking at [temyers/cucumber-jvm-parallel-plugin](https://github.com/temyers/cucumber-jvm-parallel-plugin). It can be configured to generate a junit or testng runner for each scenario. I'm not familiar with gradle but I assume that just like maven you can tell it to run junit tests in parallel on different vms.

**Comment by abhisheksreepal** [comment]
Thanks for the tip @mpkorstanje .  Looks like a maven plugin.
In Gradle, we run multiple scenarios using cucumber cli each having its own scenario tag on a separate jvm (Using the help of GParsPool) and we could not use junit tests as cucumber-junit and gradle had an issue long back which i dont remember. Please fine link [**here**](https://groups.google.com/forum/#!topic/cukes/OF2974WAE1w). Even here , they suggest maven . But again, we had most of the things on gradle. Hence, we went with cli and above approach.

**Comment by mpkorstanje** [comment]
Mmh. Adding a unique scenario tag to each scenario is a bad practice. It adds error prone manual labor. It would be better if you were to address the pickles the their uri. If you have a look at the current code in Runtime it shouldn't be too difficult to figure out how to compile pickles and filter those that will be executed and extract their uris. Though I also can not endorse any hacking onto cucumber runtime. We might change it again and again in the future.

As such I would recommend that you create a custom Formatter that listens to `TestCaseStarted` events. When used in combination with `--dry-run` you can use it to create a list of uris of pickles that will be executed. This you can then pass onto your parallel runner.

**Comment by abhisheksreepal** [comment]
Thank you @mpkorstanje for the info. Will look into it and For now, I will close this issue.
