### ISSUE TITLE
How do i execute a particular step in StepDefinition class

### ISSUE THREAD

**Issue by nagarjuna1304** [cucumber/cucumber-jvm#1232]
Hi All,

I'm new to cucumber and RestAssured framework.

In my class Stepdefinition is having 4 steps methods.It supposed to run only 4th step in Stepdefinition file.Is it possible to run only one step?

I follow standard maven project structure, i.e. step definitions in src/test/java and feature file in src/test/resources

Please let me know if you need any more information on this regard

Could you please help on this.

**Comment by mpkorstanje** [comment]
Github is not the best place to ask for help with cucumber. Please check the options provided at https://cucumber.io/support or ask your question at https://stackoverflow.com/
