### ISSUE TITLE
Will Cucumber Java 8 runs outside constructor ?

### ISSUE THREAD

**Issue by mmaryo** [cucumber/cucumber-jvm#1233]
Hello, 

I would like to use the Cucumber Java 8 lambda expressions 

Like this : https://cucumber.io/docs/reference/jvm

    public class ShoppingStepsDef implements En {
	 
	    private int budget = 0;
	 
	    public ShoppingStepsDef() {
		Given("I have (\\d+) in my wallet", (Integer money) -> budget = money);
	 
		When("I buy .* with (\\d+)", (Integer price) -> budget -= price);
	 
		Then("I should have (\\d+) in my wallet", (Integer finalBudget) -> 
		  assertEquals(budget, finalBudget.intValue()));
	    }
	}

This syntax is amazing, but runs inside constructor there are problems :

- we cannot run @Before and @After methods of JUnit 

- we cannot instantiate Spring context with @Autowired

Have you got a plan about that ?

Regards

**Comment by mpkorstanje** [comment]
> Will Cucumber Java 8 runs outside constructor? 

Given the current possibilities of Java 8 no. Perhaps with Java 9 we could use the repl but somebody will have to feel like building it. 

> we cannot run @before and @after methods of JUnit

Are you certain you do not have these confused with cucumbers `@Before` and `@After`? To wit cucumber-junit will only pick up on `@BeforeClass`, `@AfterClass` and `@ClassRule` in the runner class. The java8 equivalent of `@Before` is `Before(() -> { // do stuff});` Its various method definitions are located in the parent class of `En`.

> We cannot instantiate Spring context with @Autowired

Please check your implementation against the [spring-txn example](https://github.com/cucumber/cucumber-jvm/blob/master/examples/spring-txn/src/test/java/cucumber/examples/spring/txn/SeeMessagesStepdefs.java#L21). If the problem persists please create a [minimal complete verifiable example](https://stackoverflow.com/help/mcve).

Do keep the caveat emptor of [How soon will my ticket be fixed?](https://github.com/cucumber/cucumber-jvm#how-soon-will-my-ticket-be-fixed) in mind though.

**Comment by mmaryo** [comment]
thanks
