### ISSUE TITLE
[Spring, Kotlin] Kotlin Metadata annotations breaks SpringFactory

### ISSUE THREAD

**Issue by jensbaitingerbosch** [cucumber/cucumber-jvm#1240]
## Summary

kotlin-spring does not work together with Kotlin Step classes

## Expected Behavior

*Given* Two different  Kotlin Steps definition classes like 
```
@ContextConfiguration(classes = arrayOf(TestConfig::class))
class SomeSteps1 {
    // some step definitions
}

@ContextConfiguration(classes = arrayOf(TestConfig::class))
class SomeSteps2 {
    // some step definitions
}
```
*When* A scenario is executed using this step class as glue code
*Then* The scenario is executed without an error 
## Current Behavior

An exception is thrown: 
` cucumber.runtime.CucumberException: Annotations differs on glue classes found: com.xxx.SomeSteps1, com.xxx.SomeSteps2`

Background: Kotlin adds an additonal Annotation `kotlin.Metadata` to each class. These Metadata differ for each class, therefore the check in SpringFactory.checkAnnotationsEqual() fails. 

## Possible Solution

Before comparing the annotations, remove annotations of type `kotlin.Metadata` (can be done by its name so there is no dependency to Kotlin)

## Steps to Reproduce (for bugs)
(see above in Expected behaviour)

## Context & Motivation

We use in our project Cucumber with Spring and Java for a while and I tried out to add a Kotlin step definition class, which did not work out that good...

## Your Environment

* Version used: 1.2.5
* Operating System and version: Windows 10
* Link to your project: -

**Comment by mpkorstanje** [comment]
The proposed solution works but over time has the potential to explode into a list of exceptions. This is undesirable. I think we should improve the solution to the underlying issue.

I'd have to study #711 to see if it would be possible to limit the number of step definition annotated with `@ContextConfiguration` to exactly one so we need not check for equality.

As a work around I'd either suggest manually ensuring there is only one step definition annotated by `@ContextConfiguration` or copying the `SpringFactory` and applying your solution locally. You can enforce factory selection by adding `cucumber.api.java.ObjectFactory=package.of.MyFactory` to cucumber.properties.

**Comment by brasmusson** [comment]
@mpkorstanje It is absolutely possible to limit the number of glue classes annotated with `@ContextConfiguraion` (or `@ContextHierarcy`) to exactly one, in a sense that is the preferred usages after #711 (although that usage is not well documented). The only problem is that it is a non-backward compatible change. We could right not add a deprecation warning when more that one `@ContextConfiguration` glue class is found, and in the next major release start to fail on it.

**Comment by mpkorstanje** [comment]
Deprecating it now and adding a ticket to the 3.0.0 mile stone should do it then.
