### ISSUE TITLE
Generate documentation from step definitaion(java) and feature files written in cucumber and gherkin

### ISSUE THREAD

**Issue by saxenadeepakkumar** [cucumber/cucumber-jvm#1250]
Need your help guys for following :

I am using cucumber, gherkin and feature files in our automation project for testing purpose. This is a java project. So our step definition files are written in java using gherkin tags. I want to generate documentation (may be in html) like [yard-cucumber](http://burtlo.github.io/yard-cucumber/requirements.html) from java and feature files. Yard-cucumber generates the documentation after read/scan the feature and steps definition(written in ruby) files. I used the similar approach for java using jruby. But it is not scanning java files and giving error. Is there any tool/pluing to generate document after reading/scan feature and step definition files written in java? or any parser available in jruby with yard-cucumber to scan java files?

Please help. Thanks in advance.

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
