### ISSUE TITLE
Not able to produce screenshots after failed Scenario

### ISSUE THREAD

**Issue by telangn** [cucumber/cucumber-jvm#1261]
Hi, I have followed your direction and put the screenshot in an After hook, but nothing happens when a scenario fails (no snapshot). Am I using the wrong cucumber versions? What am I missing? - 
 
Also, can you tell me how to navigate to your step definitions regarding web browser testing?
I've searched your repo but cannot find anything. 
Many thanks in advance,

    @After("@destroy")
	public void tearDown() throws Throwable {

		driverC.close();
	}
    
    @After
	public void screenShot(Scenario scenario) throws Throwable {
		try {
			if (scenario.isFailed()) {

				final File screenshot = ((TakesScreenshot) driverC).getScreenshotAs(OutputType.FILE);
				FileUtils.copyFileToDirectory(screenshot, new File("/home/ninad/eclipse-workspace/Reports/html"));
			}
		} catch (WebDriverException somePlatformsDontSupportScreenshots) {
			System.err.println(somePlatformsDontSupportScreenshots.getMessage());
		}
	}

    <dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.11</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.4</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<version>1.2.4</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.4</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.6.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>3.6.0</version>
		</dependency>
	</dependencies>

**Comment by mlvandijk** [comment]
@telangn You have two After annotations, where the first is closing the driver that the second should use to make the screenshot. If I remember correctly, they will run in the order they are defined, so the driver will be closed before taking the screenshot? (run in debug mode to check if you like). 

You might change the order or try something like this:

@After
public void screenShot(Scenario scenario) throws Throwable {
	try {
		if (scenario.isFailed()) {

			final File screenshot = ((TakesScreenshot) driverC).getScreenshotAs(OutputType.FILE);
			FileUtils.copyFileToDirectory(screenshot, new File("/home/ninad/eclipse-workspace/Reports/html"));
		}
	} catch (WebDriverException somePlatformsDontSupportScreenshots) {
		System.err.println(somePlatformsDontSupportScreenshots.getMessage());
	} finally {
             driverC.close();
        }
}

**Comment by telangn** [comment]
Thank you. Dont I need to use the "@destroy" in @After("@destroy") ? If I
put them together...

**Comment by telangn** [comment]
Also, I don't need to call and pass something into tearDown(Scenario scenario) ? i

**Comment by telangn** [comment]
I made the changes you requested, but still nothing happens.

**Comment by mlvandijk** [comment]
@telangn Here's how we do it in one of our projects:

import cucumber.api.Scenario;
import cucumber.api.java8.En;
import cucumber.shared.util.WebDriverManager;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.remote.Augmenter;

public class ScreenshotOnErrorHook implements En {

    public ScreenshotOnErrorHook() {
        After((Scenario scenario) -> {
            if (scenario.isFailed()) {
                TakesScreenshot browser = (TakesScreenshot) new Augmenter().augment(WebDriverManager.getWebDriver());
                final byte[] screenshot = browser.getScreenshotAs(OutputType.BYTES);
                scenario.embed(screenshot, "image/png");
                scenario.write("URL: " + WebDriverManager.getWebDriver().getCurrentUrl());
            }
        });
    }
}

Note: We use cucumber-java8 instead of cucumber-java
We use Cucumber v1.2.5, Selenium v3.0.1 and Junit v4.12

**Comment by mlvandijk** [comment]
cucumber.shared.util.WebDriverManager is where we get the WebDriver.

**Comment by mpkorstanje** [comment]
I reckon our slack channel is a better place for discussion and questions.

https://cucumberbdd-slack-invite.herokuapp.com/
