### ISSUE TITLE
~@tag_name from command line is included in the test run with -Dcucumber.options

### ISSUE THREAD

**Issue by chetand24** [cucumber/cucumber-jvm#1262]
## Summary: When I am running my test with tag (included) its working fine but when excluding with ~ its still including the excluded tag (When I provided the ~ in CucumberOption then also its working fine), FYI: when I have no tag, all my tests are running successful.

My setup/configuration includes:
Gradle + TestNG + Java + cucumber-JVM
I am using TestNGCucumberRunner to run my test, I am directly running Runner class (with @CucumberOptions annotation) from testng (gradle useTestNG() option)

My working run command:
gradle <task-name> -Dcucumber.options="--tags @tui"

My **not-working** run command:
gradle <task-name> -Dcucumber.options="--tags {\"~@tui\"}"
gradle <task-name> -Dcucumber.options="--tags ~@tui"

## Possible Solution
The test with ~tag should be excluded from the test run 

## Context & Motivation
This impact me because I am running my tests on CI using jenkins and when there is issue, I need to exclude the test immediately 

## Your Environment
* Version used: 2.0.1
* Operating System and version: Mac10.12.6, Java8, TestNG6.12, Gradle
* Link to your project: Sorry, Its internal project.

**Comment by mpkorstanje** [comment]
Depending on your shell or ci system you may need apply additional escape characters. If you think this is a bug with cucumber could you provide a a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)?

**Comment by mlvandijk** [comment]
@chetand24 
cucumber.runtime.TagExpressionOld line 25 gives the following warning: Support for '~@tag' will be removed from the next release of Cucumber-JVM. Please use 'not @tag' instead.
Have you tried using the new syntax? (no need to escape the ~)

**Comment by chetand24** [comment]
@mlvandijk  Thanks  "not @tag" worked perfectly for me. I guess documentation needs to be updated.

**Comment by chetand24** [comment]
@mpkorstanje Thanks for response, the "Minimal, Complete and Verifiable example" would have been my next step but this got resolve by using "not" instead of "~".

**Comment by mlvandijk** [comment]
@chetand24 Glad to hear it was solved! If you'd like to update the documentation, please (also) have a look here: https://github.com/cucumber/docs.cucumber.io

**Comment by papesch** [comment]
More specifically https://docs.cucumber.io/tag-expressions/ , so the original problem is resolved with
`gradle -Dcucumber.options="--tags 'not @dev'"`
