### ISSUE TITLE
Document supported JUnitAnnotations

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1268]
The only supported annotations are `@ClassRule`, `@BeforeClass` and `@AfterClass` in the runner class. They are invoked around the execution of the selected suite of feature files. This is not documented in [Cucumber.java](https://github.com/cucumber/cucumber-jvm/blob/master/junit/src/main/java/cucumber/api/junit/Cucumber.java). In fact it documents the exact opposite.

```java
 * Classes annotated with {@code @RunWith(Cucumber.class)} will run a Cucumber Feature.
 * The class should be empty without any fields or methods.
```

I would however discourage the use of these annotations. They are not portable between runners and should not be relied upon. If for example the commandline runner is used, the JUnit rules will not be invoked. This may lead to a different test execution.

**Comment by jhorstmann** [comment]
> If for example the commandline runner is used, the JUnit rules will not be invoked

They also won't be used by some IDE integrations, which will be very confusing. For example IntelliJ cucumber plugin internally uses the commandline runner instead of JUnit.
