### ISSUE TITLE
java.lang.ClassNotFoundException: gherkin.GherkinDialectProvider

### ISSUE THREAD

**Issue by Stoni1986** [cucumber/cucumber-jvm#1269]
Hi,

if i want to run the cucumber-java-skeleton in eclipse oxygen 4.7.0 with junit i get:
java.lang.ClassNotFoundException: gherkin.GherkinDialectProvider
Same with mvn test.
If i downgrade to 1.2.5 all works fine.

![image](https://user-images.githubusercontent.com/17159891/32005976-e2b68034-b9a5-11e7-967c-94325cb69b3f.png)

i use the projekt from:
https://github.com/cucumber/cucumber-java-skeleton

Can someone help?

**Comment by mpkorstanje** [comment]
Given the cucumber-java-skeleton passes on the build server I am fairly confident this is not a problem with cucumber. Looks like like your dependencies have not been downloaded.
