### ISSUE TITLE
The Cucumber report is not html sanitized

### ISSUE THREAD

**Issue by octavian-h** [cucumber/cucumber-jvm#1277]
## Summary
I have problems with Cucumber reports because the step names and data is not sanitize (ex: replace < with "&amp;lt;").

## Expected Behavior
The java file contains this step:
~~~java
@Given("^I set description as "([^"]*)"$")
public void set_description(String text) throws Throwable {
}
~~~

The feature file contains:
~~~
Given I set description as "<script>alert('Injected!');</script>"
~~~

When I open the Cucumber report in browser (Firefox, Chrome) I want the scripts (or other HTML/JS/CSS tags) to not be interpreted.

## Current Behavior
A bunch of popup messages and some color changes.

## Possible Solution
Insert a method in "formatter.js" similar with "cleanHtml" from [Mustache.js](https://github.com/janl/mustache.js/blob/master/mustache.js)

## Your Environment
I have win 7, jdk 8 and I use the following Maven dependencies:
~~~
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-spring</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>
~~~

**Comment by mpkorstanje** [comment]
Currently I would recommend using https://github.com/damianszczepanik/cucumber-reporting or the related maven or jenkins plugins. The html formatter is somewhat unmaintained.

**Comment by aslakhellesoy** [comment]
It's unmaintained indeed, and the plan is to replace it with a cross-platform implementation that consumes the same events emitted by all Cucumber implementations.
