### ISSUE TITLE
Parsing floats with e-notation

### ISSUE THREAD

**Issue by king-tyler** [cucumber/cucumber-jvm#1279]
Cucumber-jvm doesn't seem to parse floats/doubles that use the e-notation correctly.

For example, given the following step and step definition:
`Given example step 1e-25`

```
@Given("^example step (.+)$")
public void example_step(double value) {
  Assert.assertEquals(1e-25, value, 1e-30);
}
```

The assert fails because the value is parsed as 1 (cucumber parses everything up to the letter 'e').

The current work around would be

```
@Given("^example step (.+)$")
public void stepDefinition(String value) {
  Assert.assertEquals(1e-25, Double.parseDouble(value), 1e-30);
}
```

**Comment by mpkorstanje** [comment]
Cucumber uses a localized instance of `java.text.NumberFormat` to determine what a double or float should look like. This is controlled by your jvm.  You may be able to tweak something there.

It should also be possible  to create a `ScientificDouble` wrapper class with a single constructor that accepts a string and does the conversion when unwrapping the value. 

Once cucumber-expressions are integrated in cucumber you'll be able to register a custom converter that works without the need to wrap.

**Comment by mlvandijk** [comment]
This appears to be a Java question, rather than a Cucumber question. Can it be closed?

**Comment by mpkorstanje** [comment]
Yes.
