### ISSUE TITLE
Cucumber sends the value of two column titles from the Examples table into a single placeholder even though the placeholder name matches only a single column title in the Examples table

### ISSUE THREAD

**Issue by rraghuna** [cucumber/cucumber-jvm#1280]
**Summary**

Cucumber sends the value of two column titles from the Examples table into a single placeholder even though the placeholder name matches only a single column title in the Examples table. This is happening when the placeholder names are seperated by a comma and the examples table values contain a comma as well.

**Expected Behavior**

The value of placeholder for the below scenario should be as follow:

accountType = bankaccount
heldBy = individual
servicesSupported = Deposit,Withdrawal

```gherkin
Scenario Outline: update Account
    Given an account with following details: <accountType>,<heldBy>,<servicesSupported>
    When I update the acccount <field> to a <newValue>
    Then I should be informed of the successful account update    
    Examples:
    |accountType | heldBy       | servicesSupported  |
    |bankaccount | individual  | Deposit,Withdrawal |
```

**Current Behavior:**

The value of placeholder for the mentioned scenario is as follow:

accountType = bankaccount,individual
heldBy = Deposit
servicesSupported = Withdrawal

**Your Environment**

Using maven to run my test

```xml
       <java.version>1.8</java.version>
        <junit.version>4.12</junit.version>
        <cucumber.version>2.1.0</cucumber.version> <!-- 1.2.5 -->
        <maven.compiler.version>3.7.0</maven.compiler.version>
```

[sample.zip](https://github.com/cucumber/cucumber-jvm/files/1484341/sample.zip)

**Comment by aslakhellesoy** [comment]
Thanks for the test case! This is not related to `Scenario Outline`, and it's not a bug either.

Before executing your scenario, Cucumber will rewrite it to the following:

```gherkin
Scenario: Buy Apples
  Given the account with following details: bankaccount,individual,Deposit,Withdrawal
  When I update the acccount <field> to a <newValue>
  Then I should be informed of the successful account update    
```

The first step is then matched agains your regexp: `^the account with following details: (.*),(.*),(.*)$`

Regular expression matching is greedy, so the first capture group will be `bankaccount,individual`

Illustrated [here](http://rubular.com/r/DeMMDCWhZA)

You need to make your regexp less ambiguous.

**Comment by rraghuna** [comment]
Thank you, Aslak Hellesoy. Following your advise, I refined the regexp to match the words in the way I wanted and it works fine.
