### ISSUE TITLE
Add generic step definition with lambda expression

### ISSUE THREAD

**Issue by dhmoclex** [cucumber/cucumber-jvm#1281]
## Summary

Please add generic step definition with lambda expression :

For instance :

```
public class Events implements En {
    public Events() {
        Step("^arrange$", () -> {...});
        Step("^action$", () -> {...});
        Step("^assert$", () -> {...});
    }
}
```

instead of :

```
public class Events implements En {
    public Events() {
        Given("^arrange$", () -> {...});
        When("^action$", () -> {...});
        Then("^assert$", () -> {...});
    }
}
```

## Current Behavior

Actually, if I write every step with Given(), the following feature still works and the steps are correctly matched :

  ```
Scenario: First Scenario
    Given arrange
    When act
    Then assert
```

## Possible Solution

This is great, but I lost some times understanding that the lambda keyword isn't reallyusefull. So I think it could be great to have a "Step" lambda.

**Comment by aslakhellesoy** [comment]
I'm not in favour of this. Steps have keywords for a reason, and this plays down the importance of using those keywords thoughtfully.

**Comment by dhmoclex** [comment]
I would have sworn that was supported by the ruby implementation.

I first used cucumber with specflow in C#, which support such a feature (https://github.com/techtalk/SpecFlow/wiki/Step-Definitions - [StepDefinition(regex)]), and must have been lured to believed it was native to cucumber by the section "Given, When Then Are the Same" from the cucumber book.

Actually, it seems to be something specific to specflow, I think my request can be ignored.

However it seems that the feature:
Scenario: First Scenario
  Given arrange
  When act
  Then assert

works perfectly with these steps definition:
public class Events implements En {
    public Events() {
        Given("^arrange$", () -> {...});
        Given("^action$", () -> {...});
        Given("^assert$", () -> {...});
    }
}
