### ISSUE TITLE
AmbiguousStepDefinitionsException being thrown for two step definitions

### ISSUE THREAD

**Issue by jamesmeade42** [cucumber/cucumber-jvm#1300]
I am currently experiencing a `AmbiguousStepDefinitionsException` being thrown when trying to run Cucumber tests. This has confused me because from what I understand, using $ at the end of a step definition should avoid ambiguity. Please correct me if I'm wrong.

For what I am testing, I want two different steps like this, so that I can easily append different parameters onto the initial `^I perform a type '(.+)' authorisation for (\d+) with (.+)$` step where appropriate.

These are the two step definitions that are causing the issue:

`^I perform a type '(.+)' authorisation for (\d+) with (.+) and (.+) merchant type$`
`^I perform a type '(.+)' authorisation for (\d+) with (.+)$`

**Comment by mpkorstanje** [comment]
The issue tracker is not the best place to get help with cucumber. 

Try the mailing list or slack: https://cucumber.io/support
