### ISSUE TITLE
Command line output for steps contains additional characters

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/cucumber-jvm#1305]
## Summary
Command line output for steps with capture groups/variables contains additional characters
e.g. 
Step: Given a **business seller** with ID **123456788** 
Command line output: Given a **;1**business seller with ID **;1**123456788 

## Expected Behavior
Command line output: Given a **business seller** with ID **123456788** 

## Current Behavior
Command line output: Given a **;1**business seller with ID **;1**123456788 

    @Given("^a (business seller|supplier) with ID (\\d+)$")

## Possible Solution
Need to investigate further

## Steps to Reproduce (for bugs)
Will try to narrow it down

## Context & Motivation
Not as pretty as it could be... :)

## Your Environment

* Version used:
Cucumber version 2.3.1 
<cucumber.version>2.3.1</cucumber.version>
with the following dependencies
<dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId> io.cucumber </groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-spring</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
* Operating System and version:
Mac OS Sierra 10.12.6
* Link to your project:
n/a (work project)

**Comment by brasmusson** [comment]
What do you mean with "command line output"? Output from the Pretty Formatter?

**Comment by mlvandijk** [comment]
I mean System.out

**Comment by mpkorstanje** [comment]
Try `--monochrome`. I think its the ansi colours

**Comment by brasmusson** [comment]
> I mean System.out

Yes, but is it the Pretty Formatter that writes to System.out?

**Comment by mlvandijk** [comment]
Running from this runner:
@RunWith(Cucumber.class)
@CucumberOptions(
        plugin = {"json:target/cucumber.json", "pretty"},
        features = "classpath:com.bol.cucumber.sit",
        format = "json:target/cucumber.json",
        tags = {"not @skip"}
)
public class RunCukesTest {
}

Getting this result:
![screen shot 2017-12-22 at 9 17 08 am](https://user-images.githubusercontent.com/20927578/34290709-393fdae2-e6f9-11e7-86a8-15deca8fe5a4.png)

I'll need to figure out how to add --monochrome to the runner to try @mpkorstanje 's suggestion

**Comment by mlvandijk** [comment]
@mpkorstanje was right! 

Added monochrome = true to @CucumberOptions, result is now:
Given a business seller with ID 123456788
