### ISSUE TITLE
Using Cucumber-jvm 2.0.o version with testng. Cucumber testng is not able to read the stepdef file mentioned in the glue option

### ISSUE THREAD

**Issue by it-shivani** [cucumber/cucumber-jvm#1313]
Trying to run cucumber-jvm 2.0 with testng. Even though I gave path to stepdef in the glue option of cucumber runner, whne running the file I get the error to implement the stepdef.

When I ran the individual feature file I got the warning stating to notify the maintainers of the cucumber-jvm.

See warning below:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cucumber.deps.com.thoughtworks.xstream.core.util.Fields (file:/Users/sdave/Downloads/cucumber%202.0/cucumber-jvm-deps-1.0.6.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of cucumber.deps.com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Below is my build.gradle:

apply plugin: 'java-library'
apply plugin: 'application'
apply plugin: 'java'

mainClassName = 'com.bdc.neo.main.BdcNeoMain'

repositories {
    jcenter()
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api 'org.apache.commons:commons-math3:3.6.1'

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation 'com.google.guava:guava:23.0'

    // Use JUnit test framework
    testImplementation 'junit:junit:4.12'
    testCompile group: 'org.testng', name: 'testng', version: '6.13.1'

    
    compile group: 'io.cucumber', name: 'cucumber-jvm', version: '2.0.0', ext: 'pom' 
    compile group: 'io.cucumber', name: 'gherkin', version: '4.1.3'
    compile group: 'io.cucumber', name: 'cucumber-core', version: '2.0.0'
    compile group: 'io.cucumber', name: 'cucumber-java', version: '2.0.0'
    compile group: 'io.cucumber', name: 'cucumber-testng', version: '2.0.0'
    compile group: 'io.cucumber', name: 'cucumber-guice', version: '2.0.0'
    compile group: 'info.cukes', name: 'cucumber-html', version: '0.2.6'
    
    compile group: 'io.cucumber', name: 'gherkin-jvm-deps', version: '1.0.4'
    compile group: 'io.cucumber', name: 'cucumber-jvm-deps', version: '1.0.6'
    
    compile group: 'com.google.inject', name: 'guice', version: '4.0'
    
    compile group: 'javax.inject', name: 'javax.inject', version: '1'
    testCompile group: 'javax.inject', name: 'javax.inject-tck', version: '1'
    
    compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.8.1'   
}

test {
    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
}

## Summary

It asks to implement stepdefs even though they are already implemented

**Comment by brasmusson** [comment]
> Even though I gave path to stepdef in the glue option of cucumber runner, whne running the file I get the error to implement the stepdef.

If Cucumber-JVM had found the step definitions it would not told you to implement the step definitions, so Cucumber-JVM did found the step definitions. How did you specify where Cucumber-JVM should look for step definitions?

**Comment by it-shivani** [comment]
Here is my runner where I specified the glue

> package com.bdc.neo.runner;

import cucumber.api.CucumberOptions;
import cucumber.api.testng.AbstractTestNGCucumberTests;

@CucumberOptions(
        features = {"Feature/BdcNeoTestOne.feature"},
        	glue= {"com.bdc.neo.stepdef.BdcNeoTestOne"},
        	plugin = {
                	   "pretty",
                    "html:target/site/cucumber-pretty",
                    "rerun:target/rerun.txt",
                    "json:target/cucumber1.json" 
                }
)

public class BdcNeoTestOneTR extends AbstractTestNGCucumberTests {

}

> 

And here is my stepdef class:

> 
package com.bdc.neo.stepdef;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import cucumber.api.java.en.And;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;

@Test
public class BdcNeoTestOne {
	} 

> 

Not sure why is it not able to read it.

**Comment by brasmusson** [comment]
The glue option shall specify the package (or packages) where the step definition classes are located (Cucumber-JVM will also search sub-packges for step definition classes), so you need to specify
` glue =  {"com.bdc.neo.stepdef} `.

BTW, none of the
```
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;
```
annotations has any meaning in a step definition class.

**Comment by it-shivani** [comment]
Thanks a lot. It is working now. I took off those temporary annotations.
