### ISSUE TITLE
Android: Cucumber execution does not work on Gradle

### ISSUE THREAD

**Issue by cgnuechtel** [cucumber/cucumber-jvm#1314]
## Summary

The default mechanism to execute Android tests on devices is:

```gradlew connectedCheck```

This should also work out of the box with Cucumber feature files.

## Expected Behavior

- Go to Cukeulator examples directory
   `cd <cucumber-jvm-source-root>/examples/android/android-studio/Cukeulator`
- Execute the feature files
  `gradlew connectedCheck`
- Find the correct test reports under  
  `<cucumber-jvm-source-root>/examples/android/android-studio/Cukeulator/app/build/reports`
  - `androidTests/connected/index.html` for Gradle HTML report
  - `app/build/reports/cucumber` for all Cucumber reports
    - `cucumber.html/index.html` for Cucumber HTML report
    - `cucumber.xml` for Cucumber JUnit report
    - `cucumber.json` for Cucumber JSON report

## Current Behavior

No test reports will be created on the local developer machine.  
Instead, the following error occurs:
~~~
FAILURE: Build failed with an exception.
              
* What went wrong:
Execution failed for task ':app:connectedAndroidTest'.
> There were failing tests. See the report at: file:///<cucumber-jvm-source-root>/examples/android/android-studio/Cukeulator/app/build/outputs/reports/androidTests/connected/index.html
~~~

## Possible Solution

Use the code of [pull request 1094](https://github.com/cucumber/cucumber-jvm/pull/1094).

The pull request solves the following issues for the Cukeulator example project:

- Uses the newest Android build tools
- Uses AndroidJUnitRunner (JUnit 4+) and ActivityTestRule instead of deprecated ActivityInstrumentationTestCase2
- Sets the required permissions to write Cucumber reports
- Creates unique test names for Gradle HTML reports

To try out the solution, perform the following steps

- Checkout the source code of pull request 1094 (either from https://github.com/cgnuechtel/cucumber-jvm or via the instructions of https://gist.github.com/kennethreitz/3709868)
- Build Cucumber-JVM locally (with source of the pull request 1094)
- Edit `<cucumber-jvm-source-root>/examples/android/android-studio/Cukeulator/app/build.gradle` to use that locally build Cucumber-JVM (look at the comments in build.gradle)

If you leave out the last two steps (do not build Cucumber JVM locally and edit the `build.gradle`), the Gradle execution is still working and contains the correct Cucumber reports. But, in that case the Gradle HTML reports are not correct (it display 9 executed tests instead of 25).

## Steps to Reproduce (for bugs)

1. Install Android SDK + Android Studio
2. Download Cucumber Source Code
3. Goto examples directory (as described above)
4. Invoke Gradle (as described above)

## Context & Motivation

Just want to use Cucumber-JVM for Android with the latest Android build tools.

## Your Environment

* Version used: Latest Cucumber-JVM source
* Operating System and version: Windows 10

**Comment by brasmusson** [comment]
The title of this issue is misleading as it only identifies an issue with using Gradle and cucumber-android, and not with Gradle and Cucumber-JVM in general.

**Comment by cgnuechtel** [comment]
@brasmusson Thanks! Changed it.
