### ISSUE TITLE
cannot find symbol (variable classOf, variable Cucumber,..)

### ISSUE THREAD

**Issue by mlotfi2005** [cucumber/cucumber-jvm#1316]
Hi,
Can you please help me, I got this errors when I tried to run a class that has a feature .

C:\Users\alotfi2\IdeaProjects\CucumberTest\src\test\java\org\softpost\Mytest.java

Error:(7, 10) java: cannot find symbol
  symbol: variable classOf

Error:(7, 18) java: cannot find symbol
  symbol: variable Cucumber

Error:(9, 20) java: cannot find symbol
  symbol: method Array(java.lang.String)

Error:(10, 16) java: cannot find symbol
  symbol: method Array(java.lang.String)

Error:(11, 16) java: cannot find symbol
  symbol: method Array(java.lang.String)

**Comment by mlvandijk** [comment]
@mlotfi2005 To ask questions, please have a look at the options provided here: https://cucumber.io/support
If you want help, please also provide your code that is getting these errors so we can help you better. 

If you do find a bug in Cucumber, you can log it as an issue in GitHub.

**Comment by mpkorstanje** [comment]
This does not appear to be related to cucumber at all.
