### ISSUE TITLE
Enhancement Request: Scenario Failure Retry + Context Injection support within Cucumber

### ISSUE THREAD

**Issue by 599139** [cucumber/cucumber-jvm#1322]
Hi,
     Below are 2 extremely useful and important features I think Cucumber is missing today and users would be immensely benifitted : 

1. Ability to configure test execution with "Failure Retry" option - often UI test are flaky and rerunning them reveals the test has passed. This feature would allow retrials of failed scenarios within the execution flow based on the count set for the option.

2. Out of the box support for context injection. I know this is possible today using other libraries, but would be nice to have one integrated within the Cucumber framework.

Thanks

**Comment by mpkorstanje** [comment]
Heya,

1. This is currently not supported out of the box. And I doubt it will happen unless someone implements it in a PR. However if you are using the JUnit runner, once https://github.com/apache/maven-surefire/pull/150 is released you will be able to rerun failed scenarios by using surefires rerun mechanism.

2. I am a bit confused by this request. While not entirely out of the box dependency injection is provided with cucumber-jvm. The simplest way is by adding cucumber-picocontainer. Once you've done that you'll have DI.

**Comment by mpkorstanje** [comment]
Lets not wait for that. Surefire has been released.
