### ISSUE TITLE
cucumber-android does not integrate very well with Android Orchestrator

### ISSUE THREAD

**Issue by mariusbob** [cucumber/cucumber-jvm#1324]
I have just added android orchestrator in my project and it seems that the tests are running, the reports are generated, but I get this error:
```
com.android.builder.testing.ConnectedDevice > No tests found.[Moto G (4) - 7.0] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
```

As I know, orchestrator takes every test method(annotated with @Test, obviously) and executes it in a separate process. Is it really a problem for cucumber-android?

**Comment by brasmusson** [comment]
Cucumber-JVM executes Pickles compiled from Scenarios in Feature files, not methods annotated with `@Test`. If the Android Orchestrator searches for methods annotated with `@Test`, I'm not surpriced it reports "No tests found". Were do you expect it to find methods annotated with `@Test`?

**Comment by mariusbob** [comment]
You're right, I don't have methods annotated with `@Test`, but The thing is that the tests are executed, reports are generated but the error on console is "No tests found."

**Comment by brasmusson** [comment]
> the thing is that the tests are executed, reports are generated but the error on console is "No tests found."

So?? You have both cucumber-android and Android Orchestrator in your projekt (and no `@Test` methods). Cucumber-android executes its test (not relying on any `@Test` methods), at the same time Android Orchestrator searches for `@Test` methods, finds none, and says exactly that on the console. I do not see that cucumber-android can to anything about Android Orchestrator reporting that it did not find any `@Test` methods. 

I do not understand why you added Android Orchestrator to your project when you have no `@Test` methods, which is what Android Orchestrator searches for and executes.

I thinks this issue should be closed, but feel free to provide a pull request if you see any possibility that cucumber-android and Android Orchestrator can be integrated in any way.

**Comment by nbransby** [comment]
I had to create a testInstrumentationRunner (replacement for android.support.test.runner.AndroidJUnitRunner) and a org.junit.runner.Runner (replacement for cucumber.api.junit.Cucumber) that combines cucumber-android and cucumber-junit to run scenerios isolated in seperate processes via orchestrator.

**Comment by bandyguy** [comment]
@nbransby Is there any way you could provide more details / an example of how you got this working? I have observed the same scenario. It would be nice to achieve isolation in tests that the Android Orchestrator attempts to provide.

**Comment by nbransby** [comment]
@bandyguy I've added my work to a gist here: https://gist.github.com/nbransby/24013c6b335a085c0d875244bcefb70e

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber-android#2
