### ISSUE TITLE
Cucumber tag expressions not working via maven command line/terminal

### ISSUE THREAD

**Issue by priyasetty** [cucumber/cucumber-jvm#1334]
## Expected Behavior
below new style of tags should be supported when tests are run from maven command line or any terminal
--tags @dev stays the same
--tags ~@dev becomes --tags 'not @dev'
--tags @foo,@bar becomes --tags '@foo or @bar'
--tags @foo --tags @bar becomes --tags '@foo and bar'
--tags ~@foo --tags @bar,@zap becomes --tags 'not @foo and (@bar or @zap)'

## Current Behavior

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.455 sec <<< FAILURE! - in xyzTestRunnerfile 
initializationError(runnerTestFile)  Time elapsed: 0 sec  <<< ERROR!
java.lang.IllegalArgumentException: Not a file or directory:

works fine with old style of tags 
-DCucumber.options=" --tags @a,@b"

## Steps to Reproduce (for bugs)

1. Run tests using IntelliJ maven command line with command -DCucumber.options=" --tags @a or @b"

## Context & Motivation

most of my project tests are run using command line, without this issue been resolved there is no usage of updating our project to latest cucumber version

## Your Environment

  
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>2.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>2.4.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>2.4.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>2.4.0</version>
            <scope>test</scope>
        </dependency>

**Comment by aslakhellesoy** [comment]
You need to put quotes around the entire expression:

```
-Dcucumber.options="--tags '@A or @b'"
```
