### ISSUE TITLE
Maven distribution relocation

### ISSUE THREAD

**Issue by boaty82** [cucumber/cucumber-jvm#1336]
Please can you for each project setup a relocation notification of your move from `info.cukes` to `io.cucumber`

e.g. as per jackson
https://mvnrepository.com/artifact/org.codehaus.jackson/jackson-mrbean 
![screen shot 2018-03-20 at 16 18 08](https://user-images.githubusercontent.com/8507223/37667627-5834495a-2c5a-11e8-8ee1-4a277f9dbf4c.png)

https://github.com/cucumber/cucumber-jvm/blob/7e5e4d1ceac8816aa5ed2e3e10fbf762877df9b1/pom.xml#L1

**Comment by mpkorstanje** [comment]
It's actually [quite involved]( https://maven.apache.org/guides/mini/guide-relocation.html) to do this and all of the 0.57 people involved in project are volunteering their time. If you want to help out that'd be awesome!

You could checkout the 2.0.0 version, create a branch, remove all the code and prepare the relocation poms with signing plugin as described in [this stackoverflow post](https://stackoverflow.com/questions/24494974/how-do-i-deploy-a-relocation-pom-xml-to-sonatypes-oss-repository).

**Comment by boaty82** [comment]
0.57 people how’s that possible? LOL

Sure thing I’m on vacation soon but will endeavour to do this on the train one day

**Comment by mlvandijk** [comment]
That would be: less than one full time person... (As we all have day jobs.)

**Comment by mlvandijk** [comment]
Therefore: help much appreciated!

**Comment by boaty82** [comment]
I assumed you meant FTEs 😜

**Comment by mpkorstanje** [comment]
> Sure thing I’m on vacation soon but will endeavour to do this on the train one day

Awesome!

**Comment by mlvandijk** [comment]
@boaty82 yes :)

**Comment by boaty82** [comment]
I haven’t forgot about this. Just been working on the parallel feature

**Comment by mpkorstanje** [comment]
So  I tried to set this up locally. 

https://github.com/cucumber/cucumber-jvm/tree/relocation-notification

And I can't get this to work. The version update is shown but not the change in `groupId`.  Puzzling.  I've send an email to mvnrepository.com to see how they do this.

```
mpkorstanje@logarithmicwhale:~/Projects/cucumber/cucumber-java-skeleton$ mvn versions:display-dependency-updates 
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Cucumber-Java Skeleton 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.5:display-dependency-updates (default-cli) @ cucumber-java-skeleton ---
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   info.cukes:cucumber-java .............................. 1.2.5 -> 2.0.0
[INFO]   info.cukes:cucumber-junit ............................. 1.2.5 -> 2.0.0
[INFO]   junit:junit ...................................... 4.12 -> 4.13-beta-2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.776 s
[INFO] Finished at: 2019-03-02T18:06:11+01:00
[INFO] Final Memory: 15M/212M
[INFO] ------------------------------------------------------------------------
```

**Comment by mpkorstanje** [comment]
I'm giving up on this. It would be nice but I can't work out how it is supposed to be done.

**Comment by mpkorstanje** [comment]
@nhopatrik just pushed

probably easier to do a new clone and then switch to the new branch “v1.2.6-relocation-release”

info.cukes subdir has the relocation information and very slim pom files
- the scm tag might need to be removed so the install/deploy/release process does that
- other deploy/release config might need to be added back in like gpg, developers, license, etc

io.cucumber subdir is a copy of 1.2.5 but with the io.cucumber groupId and versioned 1.2.6. So if people upgrade they won’t get anything new but maven etc will notify them of the groupId relocation in the build output

**Comment by mpkorstanje** [comment]
Just did the release. After updating to 1.2.6 I get the message:

```
mpkorstanje@nyx:~/Projects/cucumber/cucumber-java-skeleton$ mvn clean test
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< cucumber:cucumber-java-skeleton >-------------------
[INFO] Building Cucumber-Java Skeleton 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The artifact info.cukes:cucumber-java:jar:1.2.6 has been relocated to io.cucumber:cucumber-java:jar:1.2.6
[WARNING] The artifact info.cukes:cucumber-junit:jar:1.2.6 has been relocated to io.cucumber:cucumber-junit:jar:1.2.6
[INFO] 
```

After changing `groupIds` I get:

```
mpkorstanje@nyx:~/Projects/cucumber/cucumber-java-skeleton$ mvn versions:display-dependency-updates
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< cucumber:cucumber-java-skeleton >-------------------
[INFO] Building Cucumber-Java Skeleton 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.5:display-dependency-updates (default-cli) @ cucumber-java-skeleton ---
[INFO] artifact io.cucumber:cucumber-java: checking for updates from central
[INFO] artifact io.cucumber:cucumber-junit: checking for updates from central
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   io.cucumber:cucumber-java ......................... 1.2.6 -> 5.0.0-RC1
[INFO]   io.cucumber:cucumber-junit ........................ 1.2.6 -> 5.0.0-RC1
[INFO]   junit:junit ........................................ 4.12 -> 4.13-rc-1
[INFO] 
```
Thanks for looking into all this @nhojpatrick
