### ISSUE TITLE
Provide multiple annotations support for Cucumber-JVM

### ISSUE THREAD

**Issue by priyasetty** [cucumber/cucumber-jvm#1341]
## Summary

Provide multiple annotations support for Cucumber-JVM

## Expected Behavior
 @And("^the response body tag \"(.*)\" contains the following values:$")
 @Then("^the response body attribute \"(.*)\" contains the following values:$")
    @Then("^the response body XPath\"(.*)\" contains the following values:$")

## Current Behavior
we get below error if we use same annotation and if we change the annotation and use the step then we get undefined step.
java: cucumber.api.java.en.Then is not a repeatable annotation type

## Possible Solution
we need these multiple annotations with same code logic as while reading the gherkin it makes more sense for PO's and other stake holders.

Note : Specflow supports multiple annotations

## Your Environment
below is the cucumber version that i'm using in my project.
  
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>2.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>2.4.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>2.4.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>2.4.0</version>
            <scope>test</scope>
        </dependency>

**Comment by mlvandijk** [comment]
Hi @priyasetty 
I was able to use all three steps provided without error. Have a look at [my project](https://github.com/mlvandijk/reproduceissues/commit/222486107f1212dcb79eef74b5f9b56f8ba6a9ae).
Perhaps I'm not understanding your question correctly; in which case, could you please provide some more information? for instance your feature file? You can also contact us on on Slack to discuss. (Register for an account [here](https://cucumberbdd-slack-invite.herokuapp.com/) if you don't already have one.)

**Comment by brasmusson** [comment]
This looks like a duplicate of #957.

**Comment by priyasetty** [comment]
Yup @mlvandijk , currently i can use max of 5 different matches per step def and unfortunately the step file looks awkward, so fixing this shall help us

if i put Then keyword or any keyword multiple times for different matches
it throws below error

Duplicate annotation. The declaration of 'cucumber.api.java.en.Then' does not have a valid java.lang.annotation.Repeatable annotation.

**Comment by priyasetty** [comment]
any ETA to fix this?

**Comment by mpkorstanje** [comment]
> ### How soon will my ticket be fixed? ###
> 
> The best way to have a bug fixed or feature request implemented is to fork the cucumber-jvm repo and send a pull request. If the pull request has good tests and follows the coding conventions (see below) it has a good chance of making it into the next release.

You're welcome to help out. I reckon the best place to start would be:

> This feature would need Java 1.8; the main hurdle there is we don't know how well Android supports it and we currently have nobody that knows Android.
