### ISSUE TITLE
Issue on writing text to Cucumber Java HTML Reports( example: scenario.write)

### ISSUE THREAD

**Issue by pavanswt** [cucumber/cucumber-jvm#1349]
Description:
========

There is a bug in writing text to Cucumber Java HTML report(example: scenario.write), If you write text under @Given step reports are not displaying. 

If you write text under @When it is going under @Given. That is one step before.  

This issue occurs after migrating the Cucumber JVM from info.cukes to cucumber.io

Work Around:
=========
use info.cukes Maven repository to get rid of this issue

<dependency>
    <groupId>info.cukes</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>1.2.5</version>
</dependency>

Environment:
=========

OS= Windows 7 and 10

Maven Repository 

 <dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>2.3.1</version>
    <scope>test</scope>
</dependency>

Steps to Reproduce:
=============
Attached sceen shot shows the steps to reproduce
![cucumber-java-scenariowrite](https://user-images.githubusercontent.com/4628225/39098882-05060490-468f-11e8-8394-582929d63946.png)

**Comment by mlvandijk** [comment]
@pavanswt Could you please paste your code, to make it easier for us to reproduce (without having to type it ourselves)? 
Or better yet, you could provide a small project with your code and dependencies reproducing your error, that would make it easiest.

**Comment by pavanswt** [comment]
Hi,

I will send you the code and steps to reproduce in few mins. Please don't
close this bug. You can see the attached screen shot for your reference. It
is pretty clear.
Thanks,
Pavankumar.PS

**Comment by mpkorstanje** [comment]
No worries. It has already been fixed.

**Comment by pavanswt** [comment]
Good news, Thanks, buddy. could you tell me the release date?

Regards,
Pavan

**Comment by pavanswt** [comment]
Hi,

Please tell me what was the problem? how did you fix?

**Comment by mpkorstanje** [comment]
>Please tell me what was the problem? how did you fix?Please tell me what was the problem? how did you fix?

If you look at the Github thread you'll see this:

![image](https://user-images.githubusercontent.com/6946919/40284197-c1e575c0-5c8b-11e8-8d8b-776f54914332.png)

You can click the link to see the commit that resolved the problem.

> could you tell me the release date?

Releases are not made to any schedule. Right now you can use the [snapshot version](https://docs.cucumber.io/installation/java/#snapshot-releases).

**Comment by pavanswt** [comment]
Thank you very much

**Comment by sureshkammari** [comment]
Is this available in latest adapter 4

**Comment by SachinB75** [comment]
scenario.write does not write to the Cucumber report on Jenkins. I am able to see the details printed on my local report though. Any help will be appreciated
