### ISSUE TITLE
Cucumber version 1.2.5 java.lang.IllegalArgumentException: Not a file or directory

### ISSUE THREAD

**Issue by allensalmassi** [cucumber/cucumber-jvm#1353]
Using Windows 10
Cucumber version 1.2.5
trying to run TestRunner.java
Having the following as features 
/src/test/resources/features

I have killed .m2 and regenerated played around with cucumber version 1.2.0 - 1.2.5
But to no success.  
I am gettingjava.lang.IllegalArgumentException: Not a file or directory: C:\Users\myuserid\Int_workspace\myprojectname\src\test\resources\features

Interesting is that it is giving me the full path in the error message eventhough I have only provided the classpath as you can see above.

**Comment by mlvandijk** [comment]
Please be aware you're using a rather old version; we're upto 2.4.0 atm (note that the goupid changed to `cucumber.io`). That said, I'd guess it's a Windows problem.

**Comment by mlvandijk** [comment]
Try this? https://sqa.stackexchange.com/questions/13059/cucumber-java-lang-illegalargumentexception-not-a-file-or-directory (remove `/` before `src`)

**Comment by allensalmassi** [comment]
Are you saying I should change the cucumber version from 1.2.5 to 2.4.0


I do not have / before src my line in TestRunnger is "src/test/resources/features"

**Comment by mlvandijk** [comment]
Yes, please upgrade to latest version to make sure we're not trying to solve an issue that may have been fixed in the mean time.
It may still be a configuration issue, however.

**Comment by allensalmassi** [comment]
went to pull out cukes/cucumber-core/2.4.0/cucumber-core-2.4.0 junit  java picocontainer 2.4.0 could not be resolve.....got build failure are you sure about the version
Apparently those version are not present!!!!!

**Comment by mpkorstanje** [comment]
Feel free to reopen after you've upgraded to 2.x and please include a stack trace or a way for us to reproduce your problem.
