### ISSUE TITLE
cucumber.runtime.CucumberException: java.io.FileNotFoundException: C:\Selenium\Cucumber%20Jar\cucumber-core-1.2.2.jar

### ISSUE THREAD

**Issue by Parvindranegi20** [cucumber/cucumber-jvm#1358]
## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by mpkorstanje** [comment]
Please provide as much information as you can to help us solving your problem
