### ISSUE TITLE
Cumber-jvm feature file and step definition file implementation issue

### ISSUE THREAD

**Issue by GarimaKoushik** [cucumber/cucumber-jvm#1363]
Hi, I am new to cucumber framework, and designed one selenium maven project using cucumber framework.
But I am struggling to get rid of an issue for last one week , I have explored all possible solutions on internet. eg. putting runner and step definition file under src/test dir and feature file under test/resources dir ..and many thing,  I tried everything possible from my end but nothing could help me.
I have shared the [git hub link ](https://github.com/GarimaKoushik/com.CRM.cucumber.git) at the bottom.
Here is the issue I am getting -

##-----------------------issue/error ---------------------------------
1 Scenarios ([33m1 undefined[0m)
3 Steps ([33m3 undefined[0m)
0m0.000s

You can implement missing steps with the snippets below:

@Given("^User is already on login page$")
public void user_is_already_on_login_page() throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@When("^title of login page is Free CRM$")
public void title_of_login_page_is_Free_CRM() throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@Then("^user enters username and password$")
public void user_enters_username_and_password() throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

#------------------------------------------------------------------------------------

project available on git hub -

**Comment by mlvandijk** [comment]
@GarimaKoushik, please note that issues are for reporting bugs or making feature requests. For questions, you can use any one of the support options listed here: https://cucumber.io/support
Therefore, I'm closing your issue.

That said, I'll have a look at your project to see if I can help you. I'm away at conference atm, so don't know when I'll get to it. You can find me on Slack, or ask others in the #help-cucumber-jvm channel :)
In the mean time you might also want to look at the [cucumber-java-skeleton](https://github.com/cucumber/cucumber-java-skeleton) project, which was created to work out of the box. Or have a look at the [10-minute tutorial](https://docs.cucumber.io/guides/10-minute-tutorial/) to get started.

**Comment by GarimaKoushik** [comment]
thanks so much @mlvandijk  :) , it really helped me. thanks again for detailed explanation. cheers !!

**Comment by mlvandijk** [comment]
You're welcome. Hop into Slack anytime, if you have more questions!
