### ISSUE TITLE
Mechanism To Conditionally Load Class Containing StepDefs

### ISSUE THREAD

**Issue by michaelmcfadyen** [cucumber/cucumber-jvm#1372]
## Summary
Support for marking a class of step defs as conditional so that it does not add them to the classpath if the condition is not met. This could follow a similar work flow to the spring/spring boot annotations ie. @ConditionalOnClass.

My use case is as follow - we have a shared ft-commons library that contains common step definitions and configuration code. For example, some of our services use kafka so we have some common step defs and configuration code for setting up and integrating with embedded kafka. However, as not all of our services use kafka I don't want these step defs to be on the classpath when the kafka dependencies are not on the classpath. 

## Expected Behavior
Provide an annotation that will only load the class onto the classpath when the class provided is on the classpath ie.
 ```
@ConditionalOnClass(name = "org.springframework.kafka.listener.KafkaMessageListenerContainer")
public class CommonKafkaStepDefs {
```

## Current Behavior
Currently, all classes found under the classpath provided in the "glue" cucumber option are loaded on to the classpath. For the example above, if the service does not provide kafka as a dependency the code will fail.

**Comment by mpkorstanje** [comment]
At a glance it looks like the `JavaBackend` and the `MethodScanner` would need to be re-factored such that 1) discovering glue classes is separated from 2) processing those glue classes. After which the glue classes can be filtered based on some criteria. Currently the discovery and processing is combined. 

It would also be nice if the scanning and filter process could log some information to help analyze Glue activation problems.

Assuming we can get a consensus on the utility and functionality of this feature  willing to do the implementation and provide a PR?

**Comment by michaelmcfadyen** [comment]
I'm up for giving the implementation a go. It would be good, like you said, to get a few more eyes on this and agree upon a scope and a naming convention for these annotations. 

The one functionality I would like is to have it conditional based on the presence of a class on the classpath but another option could be have it conditional on the presence of a system property.

**Comment by michaelmcfadyen** [comment]
Had an initial stab at some of the code. Can you have a look over and let me know if this is the direction that you were thinking?
https://github.com/michaelmcfadyen/cucumber-jvm/commit/d822457c1f613830040a47c7a6c06888bbafaeb9

**Comment by mpkorstanje** [comment]
Yes. I haven't got it all thought through yet. But I was thinking we should do a single pass over all classes. 

```
Load the classes ---> Filter out the conditionals --> Create glue based and lambda based step defs (flatmap). 
```

It'd be easier with streams and lambda's but we don't have those yet.

**Comment by mpkorstanje** [comment]
As to the utility of the functionality:

1. I really like that this automagically enables and disables step definitions based on what you have available. This is a good system for transparently enabling and disabling functionality. 

2. What I worry about is that this closely couples the step definitions to specific bits of technology. This suggests that your step definitions are quite detailed. This is not a bad thing perse but step definitions that contain *incidental* detail are a bad thing. So I wonder if we're trying to solve the right problem here.

You mention that:

> For example, some of our services use kafka so we have some common step defs and configuration code for setting up and integrating with embedded kafka.

Could you provide an example of these?

**Comment by michaelmcfadyen** [comment]
We have an endpoint in one of our services that will produce a message on to kafka when hit. So we have a scenarios similar to:

```
Given <mock setup>
And <data setup>
When endpoint is hit
Then message is produced on to kafka
| fieldName1 | fieldName2 | fieldName3 |
| value1         | value2          | value3         | 
```

```
Given <mock setup>
And <data setup>
When endpoint is hit
Then no message is produced on to kafka
```

Because we have multiple services that produce messages to kafka that we want to validate during our functional tests we moved these step defs to a shared library as to not repeat ourselves. The shared library also contains code for configuring a message listener container for consuming the messages and adding them to an internal state object. We also have pre and post hooks setup to start and stop this message listener container.

However, not all of our services use kafka and as a result won't have the kafka dependencies on the classpath. In this case if the kafka step defs/hooks are automatically picked up by cucumber we will get a class def not found exception.

We can work around this by adding each tech specific step defs to their own subpackage ie. `stepdefs/kakfa/KafkaStepDefs` and then explicitly specify the packages we want in the glue code option of `CucumberOptions`.

**Comment by michaelmcfadyen** [comment]
I don't know how you would write step defs without tying them to the specific technology they are trying to test? The name of the step def could be generic ie. `message is produced to queue` but the underlying implementation will still to have a dependency on the queuing technology you use if you want to interact with it.

**Comment by mpkorstanje** [comment]
There appears to be no business logic here. For an example of what I mean by that have a look at the [Introduction to Example Mapping](https://www.youtube.com/watch?v=VwvrGfWmG_U). 

Do your product owners and testers also use these terms to talk about their product? Who reads and writes these feature files?

**Comment by michaelmcfadyen** [comment]
These tests are written and used by the developers. The example I gave was probably a bit vague to be honest. A more concrete example would be like

```
Scenario: Create new user
When I create a user with details
| firstname | lastname | email |
| test           | user         | test@test.com |
Then response should be ...
And user should exist in db
And CREATE_USER audit event should be created
```

In this example the audit event would be pushed to a kafka topic, so to confirm it has been sent we consume from that topic and verify the details of the audit event match what we expect. Yet again, the audit event step def would require the kafka dependencies (or whatever queue technology you are using).

**Comment by michaelmcfadyen** [comment]
Firstly, from my experience of using cucumber and junit for testing I have found cucumber to be a lot more efficient in writing functional tests than junit. You can get to a point quite quickly where you are adding new scenarios without writing any java code. Also, a lot of the developers I have worked with, even though they can understand code, still prefer to read feature files when trying to understand the functionality of a service. However, these are just my opinions which you disagree with.

Secondly, I still don't quite get your previous point on not tying your tests to specific technology. In my example scenario above how would you verify that the audit event was sent or that the user was created successfully without integrating the test with a specific queuing/db technology?

**Comment by mpkorstanje** [comment]
The problem is that your example isn't a well written feature. It already references specific bits of technology. A database, a response, events, ect. Decoupling is impossible if you do that. 

A better example would be:

```gherkin
Scenario: A relation can login after confirming their email address
  Given Sally wants to sign up
  When she signs up using her personal information
  And she confirms her email address
  Then she can login

Scenario: The spending limit is increased after an account is approved
  Given Sally has created an account
  When Alice from customer service approves her account
  Then the account spending limit is increased to €5,000
```

As an example this step is entirely free from technology :
```gherkin
  Then the account spending limit is increased to €5,000
```
Can have this step definition:

```java
public class Accountsteps {
  public Accountsteps(AccountService accounts){
        Given("Then the account spending limit is increased to €5,000", () => {
           assertThat(accountService.getSpendingLimit(), is(5000))
        });
  }
}
```

`AccountService` is an interface. An depending on the DI context either an `UiAccountService`, `RestApiAccountService` or a `InMemoryAccountService` is provided.
