### ISSUE TITLE
PatternSyntaxException is thrown in CucumberInstrumentationCore::create

### ISSUE THREAD

**Issue by jsmo93** [cucumber/cucumber-jvm#1373]
## Summary

In Android, creating the CucumberInstrumentationCore throws a PatternSyntaxException. This makes it impossible to run tests. The exception is generated by this recently changed line in SnippetGenerator.java
~~~
private static final ArgumentPattern[] DEFAULT_ARGUMENT_PATTERNS = new ArgumentPattern[]{
        new ArgumentPattern(Pattern.compile("\\{.*?}")),
    };
~~~

## Expected Behavior

The create method returns successfully
## Current Behavior

~~~
    java.lang.ExceptionInInitializerError
        at cucumber.runtime.java.JavaBackend.<init>(JavaBackend.java:74)
        at cucumber.runtime.android.CucumberExecutor.createBackends(CucumberExecutor.java:181)
        at cucumber.runtime.android.CucumberExecutor.<init>(CucumberExecutor.java:102)
        at cucumber.api.android.CucumberInstrumentationCore.create(CucumberInstrumentationCore.java:70)
     Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 6
    \{.*?}
          ^
        at java.util.regex.Pattern.compileImpl(Native Method)
        at java.util.regex.Pattern.compile(Pattern.java:1340)
        at java.util.regex.Pattern.<init>(Pattern.java:1324)
        at java.util.regex.Pattern.compile(Pattern.java:946)
        at cucumber.runtime.snippets.SnippetGenerator.<clinit>(SnippetGenerator.java:22)
        	... 6 more
~~~

## Possible Solution

I think this is an issue with Android Java, if the closing curly brace is escaped, the code runs as expected. The original code also works correctly in a pure Java project. 

Possible solution: escape the closing curly brace in SnippetGenerator.java
~~~
//This will generate the log message in Android
try {
    Pattern pattern = Pattern.compile("\\{.*?}");
} catch (PatternSyntaxException e){
    Log.e("Create", "PatternExceptionOccurred");
}
//This will not generate the log message
try {
    Pattern pattern = Pattern.compile("\\{.*?\\}");
} catch (PatternSyntaxException e){
    Log.e("Create", "PatternExceptionOccurred");
}
~~~

## Steps to Reproduce (for bugs)

~~~
private Bundle bundle = new Bundle();
private CucumberInstrumentationCore helper = new CucumberInstrumentationCore(this);
helper.create(bundle)
~~~

## Context & Motivation

Cucumber cannot run on Android in its current state and I would like to continue to use it.
## Your Environment

* Version used: Cucumber-Android:3.0.1, Cucumber-Java:3.0.1, Cucumber-Core:3.0.1
* Operating System and version: Android Oreo

**Comment by mpkorstanje** [comment]
See #1370.

**Comment by mpkorstanje** [comment]
#1370 has just been merged and the integration tests are passing. 

1. Would you be able to test this build using the [snapshot repository](https://docs.cucumber.io/installation/java/#snapshot-releases)? A release can be made afterwards.

2. This problem is fundamentally caused by a difference between OpenJDK and Androids implementation of Pattern. Please star [this bug report](https://issuetracker.google.com/issues/80198022) and use any connections you may have (colleagues, twitter, ect) to get it attention to it.

3. It would also appear that the example android project could use some love. Things are getting outdated. If you have any time to spare please consider spending some of it to help maintaining this project!

**Comment by jsmo93** [comment]
Ah, sorry, I missed that issue. I'd be happy to test the new build and I've starred the bug report. I can also make some additions to the sample project once I get my current project migrated from Cucumber-Android 1.2.5 to 3.0.1 and back in working order. Thank you for your quick response!

**Comment by mpkorstanje** [comment]
No worries. Good luck with the upgrade.
