### ISSUE TITLE
org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?

### ISSUE THREAD

**Issue by HMaheshwari** [cucumber/cucumber-jvm#1376]
While running scenario outline in cucumber, gettting exception and scenarios failed.

Note : As First scenario works fine the rest of scenarios were failed.

in cucumber After hooks i have called "quit()" method while launching browser again getting below exception

Environment:

Selenium webdriver version : 3.12
Chrome version : 66
Cucumber version : 1.2.5 (from info.cukes sources)

++++++++++++++++++++++++++++++++++++++++++++++++++++
Exception:

org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'XYS', ip: 'XYZ', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:273)
at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.to(RemoteWebDriver.java:856)
at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringNavigation.to(EventFiringWebDriver.java:509)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++

Expected behavior 

while running new scenario in outline it should open new browser.

**Comment by mbn217** [comment]
Can you share your code please?

**Comment by mbn217** [comment]
@HMaheshwari see this example [https://github.com/MWAK94/fanniemae-uat/blob/master/src/test/java/com/fanniemae/step_defs/Hook.java](url)

**Comment by mbn217** [comment]
Well Not sure about that cause you doing some inheritance and I will prefer to use static variable and method myself. But what you can do to make sure that the problem is the initialization of driver you can put the code itself , means in voidBefore() method write this and see if it works on Chrome
            System.setProperty("webdriver.chrome.driver", "src\\main\\java\\config\\chromedriver.exe");
            driver = new ChromeDriver();

If it works , that means that you were initializing the driver the wrong way and you need to fix it

**Comment by HMaheshwari** [comment]
@mbn217 thanks, will check and let you know.

**Comment by mpkorstanje** [comment]
This is a an issue tracker. Not a good place to ask questions.

**Comment by HMaheshwari** [comment]
@mpkorstanje correct. I 've reported issue but folks are saying that its not an issue and i have tried all possibilities at my end but got same error. if you have some input on this please let me know over my id h_maheshwari@ymail.com
thanks
