### ISSUE TITLE
Features and step definitions are glued and working, but Eclipse shows warning for no step definition

### ISSUE THREAD

**Issue by osuser2018** [cucumber/cucumber-jvm#1378]
All of my features and step definitions are working just fine.  But, in each feature, most if not all of the steps show a yellow underline warning with a message similar to this:  "No definition found for 'I log into the system'".  I'd like to get rid of this warning line as it confuses new developers coming onto the project.

What is crazy is that some steps do not show this error but they reside in the exact same step definition file as the ones that do show the error.  

I am not using regular expressions.  I do however pass parameters into a couple of steps, but probably 99% are just basic English phrases like "I log out of the system."

In my runner, I have the following CucumberOptions:
```
@CucumberOptions(
		features = {"classpath:test/features/facility"},
		glue = {"classpath:test/java/stepDefinitions/facility",
				"classpath:test/java/stepDefinitions/shared",
				"classpath:test/java/stepDefinitions/background"},
		plugin = {
				"progress",
				"json:target/cucumberFacility.json"
				},
		strict = false,
		dryRun = false,
		monochrome = true,
		tags = {"@Facility_Manage"}
				)
```

I am using Eclipse Oxygen (March 2018), 
Cucumber Eclipse Feature v. 0.0.21.201802160922	cucumber.eclipse.feature.feature.group	
Cucumber Editor	v. 0.7.6.201505100000	org.agileware.natural.cucumber.feature.feature.group

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber-eclipse#263
