### ISSUE TITLE
Scenario vs Scenario Outline

### ISSUE THREAD

**Issue by a13519** [cucumber/cucumber-jvm#1382]
## Summary

Scenario outline precondition steps

## Expected Behavior
In a case that I need to execute many steps as precondition procedues to reach the point I can do a serial of validations, I only want to execute the repeatable steps for validation, I don't want to repeat all pre-validation steps. How Can I do it?

## Current Behavior
I put a serial of steps in Scenario to prepare the test before going into Scenario Outline to loop the validation, this can't make it.

## Possible Solution
Please provide a way to prepare the steps to test and use Examples table to loop the repeatable tasks.

**Comment by aslakhellesoy** [comment]
You can use `Background` for this.
