### ISSUE TITLE
Use fully-qualified class names in snippets

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#1383]
Snippets don't qualify `PendingException`, and this often causes people to import the wrong class, or simply be confused about what class to use.

We should just make it fully qualified.

**Comment by mpkorstanje** [comment]
This is a fairly simple change in `Java8Snippet` and `JavaSnippet` but does affect a whole bunch of tests.

**Comment by aslakhellesoy** [comment]
Yeah that's what I thought :-)

**Comment by aslakhellesoy** [comment]
Also: `io.cucumber.datatable.DataTable`

**Comment by mlvandijk** [comment]
Fully qualified name: `cucumber.api.PendingException`

**Comment by mpkorstanje** [comment]
#1398 addressed the `PendingException` but didn't address the snippets containing `DataTable` yet. For example `JavaSnippetTest.generatesSnippetWithDataTable` currently has

```java
            "public void i_have(DataTable dataTable) {\n" +
```

Which should be

```java
            "public void i_have(io.cucumber.datatable.DataTable dataTable) {\n" +
```

so copy paste works instantly.

**Comment by mlvandijk** [comment]
There's an open PR for this one
