### ISSUE TITLE
Registering plugin for Cucumber

### ISSUE THREAD

**Issue by cliviu** [cucumber/cucumber-jvm#1387]
Hi ,
  I am not sure anymore how to register a plugin for Cucumber. Until this change (https://github.com/cucumber/cucumber-jvm/pull/1287) I was overriding the createRuntime() method of the Cucumber class 
and I added the plugin in the runtimeOptions of the runtime object. What is he new way of adding a plugin with Cucumber-jvm 3.0.0 ?  
  Thanks !

**Comment by mpkorstanje** [comment]
You can use the plugin parameter with a fully classified class name. E.g.:  `@CucumberOptions(plugin="com.example.MyPlugin:/some/optional/output/file.txt")` on your runner. 

The documentation is a a teeny bit spotty but here is the relevant code:

https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/api/Plugin.java
https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/formatter/PluginFactory.java

**Comment by cliviu** [comment]
Is it any other possibility to programmatically register a plugin ?

**Comment by mpkorstanje** [comment]
You can reimplement the JUnit runner without extending from the Cucumber class. It is mostly boiler plate. Then you can make what ever modifications you need. Keep in mind though that none of this is designed for extension and not part of the public API and subject to change.

**Comment by mpkorstanje** [comment]
That said, if you have a compelling use case and are willing to write the PR for it this might change.
