### ISSUE TITLE
DataTable - Automatic conversion to custom type stopped working

### ISSUE THREAD

**Issue by kathyrollo** [cucumber/cucumber-jvm#1388]
## Summary
After updating `cucumber-testng` (and subsequently all transient dependencies) from `2.4.0` to `3.0.2` in `pom.xml`, automatic conversion for datatables using custom types stopped working and now throws `UndefinedDataTableTypeException`.

## Expected Behavior
Only change required is to update imports to `import io.cucumber.datatable.DataTable;` and tests to run as per usual.

## Current Behavior
Getting this exception from steps that worked prior to update:

> io.cucumber.datatable.UndefinedDataTableTypeException: Can't convert DataTable to List<jcucumberng.steps.pojos.Income>. Please register a DataTableType with a TableEntryTransformer or TableRowTransformer for class jcucumberng.steps.pojos.Income

~~~
// Feature
When I Enter My Regular Income Sources
  | name   | amount | frequency     |
  | Salary | 25000  | every 2 weeks |


// Stepdef
@When("^I Enter My Regular Income Sources$")
public void I_Enter_My_Regular_Income_Sources(DataTable dataTable) throws Throwable {
    List<Income> incomes = dataTable.asList(Income.class);

    // More code    
}


// Custom type
public class Income {

    private String name = null;
    private String amount = null;
    private String frequency = null;

    public Income(String name, String amount, String frequency) {
        this.name = name;
        this.amount = amount;
        this.frequency = frequency;
    }

    // Getters and setters
}
~~~

## Possible Solution
Show more useful comments/javadocs for DataTable specially if updating from v2.x.x to v3.x.x for major changes to its usage. Allow easier automatic conversion like before.

## Context & Motivation
A revamp of the DataTable usage will break a lot of existing tests and can totally prevent people from updating to v3.x.x. It also outdates a lot of widely available tutorials and references.

**Comment by mpkorstanje** [comment]
I am going to assume you've found what you've needed. If not, or if anybody else searches github for this specific problem:

The [release announcement for cucumber-jvm 3.0.0](https://cucumber.io/blog/2018/05/19/announcing-cucumber-jvm-3-0-0) includes some basic instructions on how to use the datatables. It also contains a brief explanation on removal of xstream which underpinned the automatic conversions.

**Comment by aslakhellesoy** [comment]
I’ve got a pending PR for this (haven’t pushed yet). I’m reopening since I plan to fix it next week.

Context: I just ran a public training where a few people remarked that while the new data tables are great, they do require more boilerplate/configuration code. I think I’ve found a pragmatic middle ground, where you’ll still need to register a `DataTableType`, but doing so will be a one-liner.

**Comment by mpkorstanje** [comment]
Excellent. It was one of those problems I hoped some one else would solve.

**Comment by kathyrollo** [comment]
@mpkorstanje Thank you for linking the release announcement. Yes, I also asked for help [here](https://stackoverflow.com/questions/50771856/cucumber-jvm-io-cucumber-datatable-undefineddatatabletypeexception) where I also posted my solution for anyone who may be looking.

@aslakhellesoy One-liner sounds like a good compromise. I also run Cucumber-JVM training sessions to colleagues at work (many with little to no programming experience) who want to get into test automation. I did realise the additional Configurer class adds to the learning curve and considered if sticking to v2.4.0 is better for the time being.

A comprehensive and easily searchable migration guide/documentation from v2.x.x to v3.x.x is quite timely. Thank you for your work.

**Comment by mlvandijk** [comment]
@kathyrollo I've been planning a migration guide, but haven't gotten around to it. Any chance you'd be willing to help? If so, please have a look at the [documentation project](https://github.com/cucumber/docs.cucumber.io) and/or join us on Slack to discuss (you can get access [here](https://cucumberbdd-slack-invite.herokuapp.com/))

**Comment by grasshopper7** [comment]
@mlvandijk Have been attempting to document migration here - https://github.com/grasshopper7/cuke3-migration. Its a work in progress and kind of covered ParameterType till now. Hopefully finish up DataTableType  soon. Was hoping to create an article out of it and post it online. If you like the end product, happy to merge it into existing documentation.

**Comment by kathyrollo** [comment]
@mlvandijk Thank you, @grasshopper7 has a lovely writeup in progress. I'll look into the docu repo as well.

**Comment by mlvandijk** [comment]
@kathyrollo We just added some info on Type Registry to the docs; you can find it in [Cucumber configuration](https://docs.cucumber.io/cucumber/configuration/). (@grasshopper7 Please feel free to add to it, if anything is still missing)

**Comment by mlvandijk** [comment]
And ofcourse, you too @kathyrollo - feel free to add clarification yourself, or let us know what could be improved ;)

**Comment by mlvandijk** [comment]
Some information on [SO](https://stackoverflow.com/questions/50771856/cucumber-jvm-io-cucumber-datatable-undefineddatatabletypeexception)

**Comment by kathyrollo** [comment]
@mlvandijk That SO thread is me. :)

**Comment by lsuski** [comment]
I think that oneliner introduced in https://github.com/cucumber/cucumber/pull/408 PR is still too much, I have hundreds of data table classes in couple of projects and need to register all of them. I think that this oneliner should be default fallback and no one would need to do anything while migrating to cucumber v3.

**Comment by aslakhellesoy** [comment]
@Isuski if this is important to you we’d welcome a pull request.

**Comment by lsuski** [comment]
Yeah, I've just started working on this

**Comment by lsuski** [comment]
As usual the problem is more complicated. There are 2 things that does not work in v3:
1. Automatic object creation for class without default empty constructor (Gson can do this - probably with Unsafe, without additional annotations)
2. Automatic conversion of multiword space-separated column names to Java field name, e.g. "column no 1" to "columnNo1".

Therefore I think that the best solution would be to slightly change `DataTableTypeRegistry` to allow registering types taking into account inheritance.

This code could be sufficient to migrate to v3:
```
override fun configureTypeRegistry(typeRegistry: TypeRegistry) {
        typeRegistry.defineDataTableType(DataTableType(Object::class.java, TableEntryTransformer {map,type->
            val map = map.mapKeys { CamelCaseConcatenator().concatenate(it.key.splitBySpace().toTypedArray()) }
            val objectMapper = Gson()
            objectMapper.fromJson(JsonObject().apply { map.forEach { addProperty(it.key,it.value) } }, type)
        }))
    }
```

To have this work:
1. DataTableTypeRegistry.lookupTableTypeByType(Type) should search for best matching type
2. TableEntryTransformer.transform(Map<String, String>) should have additional parameter with actual type declared in step method.

Do you think this is a good idea, so I could make a PR?

**Comment by aslakhellesoy** [comment]
`sun.misc.Unsafe` doesn't work in Java 9 unless you use [hacks](https://dzone.com/articles/using-sunmiscunsafe-in-java-9-1), so we shouldn't rely on that.

The code you've pasted looks like Kotlin. I assume that was just for illustration purposes - I don't assume you are suggesting we use Kotlin?

Regarding 1 - what criteria would you use to find a matching type?
Regarding 2 - sounds like a good idea to me.

What are your thoughts, @mpkorstanje / @mlvandijk?

**Comment by aslakhellesoy** [comment]
Disregard my Kotlin comment - it's obviously user code now that I read it again :-)

**Comment by lsuski** [comment]
1. I use such strategy in my apps
  - find exact type 
  - if not found find all supertypes in registry
  - sort them by inheritance level and get closest 
      superclass


Regarding `Unsafe` its up to user, on Android it works, on another platform one can use Jackson or something else. That's why I've abandoned he idea of putting default fallback to Cucumber

**Comment by mpkorstanje** [comment]
> TableEntryTransformer.transform(Map<String, String>) should have additional parameter with actual type declared in step method.

This converter should be given a special status. There can only be one. 

It will match any list(X), where X is not a collection and there is no other converter for list(X). This requires some extra logic in the lookup.

I don't see a problem here, but perhaps we can rename it to default object mapper? Also make it work for the cell converter.

> DataTableTypeRegistry.lookupTableTypeByType(Type) should search for best matching type

This sounds like something you can implement in your implementation of the default object mapper.

I don't think this is generally applicable.

**Comment by mpkorstanje** [comment]
> Automatic conversion of multiword space-separated column names to Java field name, e.g. "column no 1" to "columnNo1".

This too can go into your default implementation of the object mapper. I know Jackson allows plugins that do this.

**Comment by lsuski** [comment]
Default mapper/transformer sounds good for me as well.

**Comment by mpkorstanje** [comment]
Sure. Transformer is probably better given the context. But we can bikeshed about that later.

**Comment by aslakhellesoy** [comment]
👍

**Comment by lsuski** [comment]
Couple of problems:
1. Do you preffer to add second parameter to Table...Transformer interfaces - this will break compatibility and all the people who already migrated would have to change their code - or we should add other interfaces
2. `DataTableTypeRegistry` returns `DataTableType` by type, not knowing if this is cell, row or table type as knowledge about that belongs to `DataTableTypeRegistryTableConverter` - as a user I'd like to register default transformer for row/entry and this complicates it a lot - in most simple case I just need to register `DataTableType` for `List<T>` whre T is not known by me and get specific T type in transformer `transform(Map<String, String>, Type)` and pass it to `ObjectMapper` or `Gson` - currently I don't have any idea how to implement it without hard refactoring to achieve 2 goals: simplicity of cucumber implementation and simplicity of use

**Comment by mpkorstanje** [comment]
I reckon the configuration might look like this:

```java
public class TypeRegistryConfiguration implements TypeRegistryConfigurer {

    @Override
    public Locale locale() {
        return ENGLISH;
    }

    @Override
    public void configureTypeRegistry(TypeRegistry typeRegistry) {
        typeRegistry.defaultDataTableTransformer(new DefaultDataTableTransformer() {
            ObjectMapper objectMapper = new ObjectMapper();

            public <T> T transform(Map<String, String> value, Class<T> type) {
                return objectMapper.convertValue(value, type);
            }

            @Override
            public <T> T transform(String value, Class<T> type) {
                return objectMapper.convertValue(value, type);
            }
        });
    }
}
```

Then look up might use it like this:

```java
            public DataTableType lookupTableTypeByType(final Type tableType) {
                JavaType targetType = constructType(tableType);
                DataTableType dataTableType = tableTypeByType.get(targetType);
                
                if(dataTableType != null){
                    return dataTableType;
                }

                if(defaultDataTableTransformer == null){
                    return null;
                }
                if(!targetType.isCollectionLikeType()){
                    return  null;
                }

                JavaType contentType = targetType.getContentType();
                if(contentType.isCollectionLikeType()){
                    return new DataTableType(contentType.getContentType().getRawClass(), targetType, new DataTableType.TableCellTransformer<>(new TableCellTransformer<Object>() {
                        //Use DefaultDataTableTransformer.transform(String value, Class<T> type) here
                    }));
                    
                } else {
                    return new DataTableType(contentType.getRawClass(), targetType, new DataTableType.TableEntryTransformer<>(new TableEntryTransformer<Object>() {
                        //Use DefaultDataTableTransformer.transform(Map<String, String> value, Class<T> type) here
                    }));
                }
            }
```

The trick is that rather then storing the transformer, it creates one adhoc for the `tableType`. By looking at the structure of the type it it can determine if this should be a table entry or table cell transformer.

**Comment by lsuski** [comment]
I think that similar logic that you proposed is in `DataTableTypeRegistryTableConverter.transform` so I wouldn't duplicate it in `lookupTableTypeByType`. Maybe `DataTableTypeRegistry` should only return `DefaultDataTableTransformer` and `DataTableTypeRegistryTableConverter` should decide when to call proper method

**Comment by mpkorstanje** [comment]
Setting a default mapper (jackson in our case) requires that header values are written in a specific way and must be derived from the property name.

So if our property is: `dataTableExampleMapper` what should the table header be?

A few suggestions:

```
Data Table Example Mapper | data table example mapper | dataTableExampleMapper | DataTableExampleMapper |
```

**Comment by mpkorstanje** [comment]
Alternatively we can also rename the table headers before doing the mapping. This is a bit more flexible.

**Comment by mpkorstanje** [comment]
Still not solved.

**Comment by Madhusudan-Devaraju** [comment]
I'm facing the problem as well. Below is the error found in the stack trace.
 
[cucumber-Datatable-error.txt](https://github.com/cucumber/cucumber-jvm/files/2959838/cucumber-Datatable-error.txt)

**Comment by mpkorstanje** [comment]
> Setting a default mapper (jackson in our case) requires that header values are written in a specific way and must be derived from the property name (not the other way around).
> 
> So if our property is: `dataTableExampleMapper` what should the table header be?
> 
> A few suggestions:
> 
> ```
> Data Table Example Mapper | data table example mapper | dataTableExampleMapper | DataTableExampleMapper |
> ```

I'm going to leave this to the discretion of the people who configure Jackson. The whole point of using an external object mapper is that Cucumber can of load these concerns.

**Comment by maximus321** [comment]
Is there a quick fix for this?
I have a project with cucumber version 2.4.0 that I need to bump to 7.17

This is a blocker for me. This change is way too much work and not doable for a company project.
I can't register every pojo by hand.
Is there a way to have a smooth upgrade path for this? I.e keeping using XStream and not have to recode everything?

Thanks

**Comment by mpkorstanje** [comment]
You are looking for a quick fix for what exactly? The context of this issue allows for a number of problems.

To wit the default object mapper receives the same information that XStream would. So if anything you can use XStream as the default object mapper, though you may have to copy the exact configuration from Cucumbers source to retain all features and functionality.

You can find documentation here, though I'd suggest reading the context around it too:
 * https://github.com/cucumber/cucumber-jvm/tree/main/java#default-transformer
 * https://github.com/cucumber/cucumber-jvm/tree/main/datatable#default-table-types

Do bear in mind that this is an open source project, developed primarily by volunteers and available free of charge. While it is unfortunate that you are working with professional constraints and requirements that put you in a bind they are yours to solve.

**Comment by maximus321** [comment]
hey @mpkorstanje 
Thanks for the context, I will take the time to read and understand it.
I appreciate the project and thank you for taking the time to reply.

The issue we have is the bump to this version that has the XStream removal. 
https://cucumber.io/blog/open-source/announcing-cucumber-jvm-3-0-0/
`io.cucumber.core.exception.CucumberException: Could not convert arguments for step xyz
It appears you did not register a data table type.
`

Looking to keep our .feature files working with the minimal amount of code possible. it seems there is a few good propositions here already, so I will have a look.
I guess just a code example of a migration that is up to date with the latest cucumber version would have been appreciated.

Cheers,
