### ISSUE TITLE
Cannot use spring @Autowire within a formater 

### ISSUE THREAD

**Issue by crashnick16** [cucumber/cucumber-jvm#1395]
## Summary

I crated a cucumber formatter plug-in and I would like to inject objects with Spring but unfortunately this does not seem to work

## Expected behaviour 
I would expect to be able to use @Autowire annotation within a formatter

Essentially I want to integrate the webdriverpllugin download as a formatter so that I can use the setup and tear down to do the download before the run.

Any ideas?

**Comment by mpkorstanje** [comment]
This is not feasible in anyway.

When using the spring module, spring is used to creates the execution context in which a pickle (scenario) is executed. The life time of the formater spans the entire test execution - across multiple pickles. So creating a test context for the formater wouldn't make much sense.

Downloading a webdriver or any other preparations are best handled by your build system. 

If you're using maven have a look at the [java-webbit-websockets-selenium](https://github.com/cucumber/cucumber-jvm/blob/master/examples/java-webbit-websockets-selenium/pom.xml)  example. It uses the [selenium-driver-downloader](https://github.com/cucumber/cucumber-jvm/blob/master/examples/java-webbit-websockets-selenium/pom.xml#L18) to download the webdrivers, then [passes the driver location to environment](
https://github.com/cucumber/cucumber-jvm/blob/master/examples/java-webbit-websockets-selenium/pom.xml#L36) after which [the driver factory creates the right webdriver](https://github.com/cucumber/cucumber-jvm/blob/master/examples/java-webbit-websockets-selenium/src/test/java/cucumber/examples/java/websockets/WebDriverFactory.java#L24). A setup step is not required. The driver is [created through dependency injection of SharedDriver](https://github.com/cucumber/cucumber-jvm/blob/master/examples/java-webbit-websockets-selenium/src/test/java/cucumber/examples/java/websockets/SharedDriver.java).
