### ISSUE TITLE
Android Example : Failed to download cucumber report

### ISSUE THREAD

**Issue by aygalinc** [cucumber/cucumber-jvm#1396]
I simply download and run the android studio example and the gradle task downloadCucumberReports failed because the specified files not exist. I check with the device file explorer.

I think that you have to uncomment in the CucumberRunner in the onCreate method the plugin configuration. It will allowed the creation of the several files and so on their downloading.

Moreover, i have a side question : You provide a debug Manifest.xml with WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE so the gradle task allowedgrantedpermession is redundant with this or not ? (because it raises some warning during compile time)

**Comment by mpkorstanje** [comment]
For Android 5 and earlier permissions need to be granted in the manifest. For Android 6 and later they're requested by the app during runtime. See  https://github.com/cucumber/cucumber-jvm/issues/1065#issuecomment-255021481

Improvements are welcome though. If you're willing to send a PR I reckon https://github.com/cucumber/cucumber-jvm/pull/1394 would be a good starting place.

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber-android#1
