### ISSUE TITLE
[Core] Deprecate the Formatter interface

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1401]
They formatter interface is a marker interface that used to inform Cucumber that the class implementing it was a plug-in that should be provided with events. This functionality has since fallen apart into `Plugin` and `EventListener`. 

All usages of `Formatter` can be replaced with `Plugin` and `EventListener`. The class itself can be deprecated.

**Comment by aslakhellesoy** [comment]
Sounds good. There will be a lot of breaking changes when we integrate https://github.com/cucumber/cucumber/pull/416. I suggest we remove it then.
