### ISSUE TITLE
Issue in executing tests when tests have more than one tag

### ISSUE THREAD

**Issue by srinu-kodi** [cucumber/cucumber-jvm#1406]
Hi @aslakhellesoy 

Subject: Issue in executing tests when tests have more than one tag

My feature file is as below:
Feature: Wordpress SignUp/SignIn Feature

  @android  @ios @web
  Scenario: Wordpress Signup scenario
    Given User chooses "Signup" option

  @ios @web @android
  Scenario: Wordpress Forgot Password scenario
    Given User chooses "ForgotPassword" option

  @web
  Scenario: Wordpress Login scenario
    Given User chooses "Login" option

My cucumber profile for the runner is:

@CucumberOptions(features = {"src/test/java/features"},
        glue = "stepDefs",
        tags = {"@web", "~@android", "~@ios", "~@ignore"},
        format = {"pretty", "html:target/cucumber"})
@RunWith(Cucumber.class)
public class WebRunner extends WebHooks {

}

Requirement: I would like WebRunner to run all the tests which are tagged with @web tag, however, it should exclude tags other than @web if there is more than one tag in the scenario as above.

So when I am running, Only one test is running.

Execution log is:

objc[2402]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java (0x106eb84c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x106f444e0). One of the two will be used. Which one is undefined.
Feature: Wordpress SignUp/SignIn Feature
Running the web test scenarios
Starting ChromeDriver 2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8) on port 35385
Only local connections are allowed.
Jun 28, 2018 11:20:45 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Navigating to HomePage
Navigating to LoginPage
Closing the web session

  @web
  Scenario: Wordpress Login scenario  # HomePage.feature:12
    Given User chooses "Login" option # HomePageSteps.userChoosesOption(String)

1 Scenarios (1 passed)
1 Steps (1 passed)
0m13.748s

Process finished with exit code 0.

How to get my scenarios to run as 3 scenarios are tagged with @web.
Can you please fix this issue or help me if I am missing anything here.

**Comment by mlvandijk** [comment]
@srinu-kodi You should be able to use [tag expressions](https://docs.cucumber.io/cucumber/tag-expressions/) for this. So in your case that would be something like `@web and not (@iOS and @android)`.

Sidenote: For questions, please use one of the [support](https://cucumber.io/support) options.
