### ISSUE TITLE
Change Datatable package to io.cucumber.api.datatable

### ISSUE THREAD

**Issue by sebrose** [cucumber/cucumber-jvm#1409]
## Summary

The package names for Cucumber classes are moving into the io.cucumber namespace. However, the 'old' `api` package was useful for identifying classes that were available for use by users of Cucumber

## Expected Behavior

Classes used by step definitions should all live in `io.cucumber.api` - so DataTable should be in `io.cucumber.api.datatable`

## Current Behavior

Datatable lives in `io.cucumber.datatable`

## Possible Solution

Move to the suggested package and update committer guidelines

## Context & Motivation

It would be useful to partition Cucumber classes, so that it is easier to find the relevant class/import statement. By putting all usable classes iunder an `api` package, discoverability is improved.

**Comment by mpkorstanje** [comment]
Looking forward to Java9 and beyond I would rather take the opposite approach and remove everything not intended for the use from sight. As of version 9 Java finally provides the tools to do so. 

Additionally the `cucumber.api` package is a split-package. It exists in different libraries. This will no longer be allowed in java 9.

**Comment by mpkorstanje** [comment]
For java 9 the the package structure will be `io.cucumber.<module>`. So we can use `io.cucumber.datatable.api` as an API package in the data table module.

This is something that can be done right now by extracting an interface from `DataTable` and placing it in the api package. Then update all usages to the interface. Though will be a few exceptions when type checking is involved.

The source for DataTable can be found in [cucumber/datatable](https://github.com/cucumber/cucumber/tree/master/datatable).

**Comment by mpkorstanje** [comment]
I am going to settle on using `@API Guardian` to mark the public API. While it lacks the discoverability of a named package it reduces the technical challenges of keeping packages isolated - which in turn makes it hard to keep the publicly accessible API small.
