### ISSUE TITLE
Move Cucumber-Android out of Cucumber-JVM

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#1410]
A few months ago [we moved](https://cucumber.io/blog/2018/05/19/cucumber-jvm-languages-support) the JVM language modules out of cucumber-jvm into standalone git repositories/maven projects.

Last week we removed OSGi - see #1404.

I want to move `cucumber-android` to a separate project too, for the same reasons:

* It's hard to build, and most of the core team are not familiar with the toolchain
* It only accounts for 0.14% of all Cucumber usage (according to the metrics in the blog post above)

Are there any @cucumber/committers who are interested in taking over ownership of this? There isn't a [cucumber-android](https://github.com/orgs/cucumber/teams/committers/teams) team yet, but I'm happy to set one up.

If nobody steps up this is likely to go the same way as OSGi I'm afraid.

@friederbluemle @SierraGolf @cgnuechtel @K76154 @mfellner you have contributed to cucumber-android in the past. Are you interested in taking this over?

/cc @mattwynne

**Comment by kutzi** [comment]
one favor: could you please stop putting .@cucumber/committers on all issues?
I don't want to be subscribed to all new issues

**Comment by aslakhellesoy** [comment]
Sorry my bad - should have used @cucumber/cucumber-jvm

**Comment by lsuski** [comment]
`cucumber-android` is quite simple and does not require much maintenance due to `cucumber-core` or `cucumber-java` changes. I could take ownership of this project but I'm not sure about exact responsibility - what kind of work should be done by me now and in the future?

**Comment by lsuski** [comment]
Is it required to upgrade version to match `cucumber-java`? E.g. while `cucumber-android` `v3.0.0` works fine with `cucumber-java` `v3.5.0` it is ok for me and does not require updating

**Comment by aslakhellesoy** [comment]
@lsuski brilliant!

I'll set up a new github repository and team and add you. The responsibilities are mainly:

* Merge pull requests / fix bugs
* Keep the CI build green
* Make new releases whenever necessary
* Document how to use it and how to build it

The next major release of `cucumber-java` and `cucumber-core` will have some backwards breaking issues, so there will be some work to be done then. Always happy to help out with specific questions, on GitHub or in Slack.

Thanks! ❤️

**Comment by aslakhellesoy** [comment]
Ok @lsuski I have moved the code and given you full access:

* Repo: https://travis-ci.org/cucumber/cucumber-android
* GitHub team: https://github.com/orgs/cucumber/teams/cucumber-android/members
* Travis: https://travis-ci.org/cucumber/cucumber-android
* Slack rooms: `#committers-android` and `#help-cucumber-android` - see https://cucumber.io/support for details about how to join

The Travis build is currently failing, and I couldn't get it to build locally either. I'm sure that's easy for you to fix! :-)

**Comment by mpkorstanje** [comment]
There is some stuff in #1389  that will make it easy to migrate android to cucumber 4.0.0 once it is done. Might be good to merge #1411 after #1389.

**Comment by friederbluemle** [comment]
Hi @aslakhellesoy, I'm also volunteering for `cucumber-android` maintenance. Thanks 🙇

**Comment by aslakhellesoy** [comment]
I think #1389 will have to wait. I've already pushed the `android` subtree from #1411 to the new `cucumber-android` project. The build is broken, but it should be easy to fix @friederbluemle and @lsuski.

**Comment by aslakhellesoy** [comment]
I'm closing this since it's done.
