### ISSUE TITLE
Reported duration time of scenario is about 0ms on Android 

### ISSUE THREAD

**Issue by lsuski** [cucumber/cucumber-jvm#1413]
Hi, 
I've recently build locally cucumber 4.0.0-SNAPSHOT and tried it on Android and encounter issue with scenario duration time. For most of scenarios it is about 0ms or 25ms or 75ms so generally it is very short but test takes naturally longer. With Cucumber 2.4.0 execution time is normal (average 2s per scenario). I was digging whole day  in code base but could not find any reason for that.
Was there any change between 2.4.0 and 4.0.0-SNAPSHOT which could introduce such issue on Android?

**Comment by mpkorstanje** [comment]
If you can tell me where the time is reported I might be able to help.

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber-android#3
