### ISSUE TITLE
No way to get gherkin statement keyword from pickle step

### ISSUE THREAD

**Issue by paulsjohnson91** [cucumber/cucumber-jvm#1415]
## Summary

No way to get gherkin keyword from pickle step since v1

The package gherkin.formatter.model.Step allows for both the keyword and the step text to be extracted from the gherkin statement, this is useful for when writing 
reporters.

## Expected Behavior

PickleStepTestStep.getStepKeyword() should get the keyword (e.g. And, When, Then)

## Current Behavior

PickleStepTestStep.getStepText() only provides you with the text.

## Context & Motivation

I'm writing a cucumber.api.formatter formatter for custom cucumber reporting and since upgrading from version 1 to version 2.4 or 3.0.2 I am no longer able to add the keyword to my reports.

**Comment by mlvandijk** [comment]
Note there were breaking changes to the Formatter in v2.0.0; see [announcement](https://cucumber.io/blog/2017/08/29/announcing-cucumber-jvm-2-0-0) and the Formatter interface will be deprecated (#1401).

**Comment by aslakhellesoy** [comment]
We're not going to add the Gherkin keyword to pickles. In the future, pickles may originate from non-Gherkin documents such as Markdown, where there wouldn't be a keyword.

If you need the keyword of a step, you should get it from the AST.

We're in the process of changing the formatter API to use a new message protocol.

See the [roadmap](https://docs.google.com/document/d/12Y3Ut-SVSGdw9L_aW6NGQY9JaCcn3z0alY4d7kzOndU) for more details.
