### ISSUE TITLE
Snippets using TypeRegistery incorrectly

### ISSUE THREAD

**Issue by paulsjohnson91** [cucumber/cucumber-jvm#1416]
## Summary

When you have TypeRegistryConfigurers set up for cucumber parameter type configuration the snippets for unknown steps are using the custom parameter types incorrectly.

## Expected Behavior
For gherkin step 'Then 4 minus 2 equal 2'
The snippet should be:
```You can implement missing steps with the snippets below:

@Then("^(\\d+) minus (\\d+) equal (\\d+)$")
public void minus_equal(int arg1, int arg2, int arg3) {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}
```

## Current Behavior
I have the following boolean parameter type as boolean is not supported out of the box
```
public class BooleanTypeRegisteryConfigurer implements TypeRegistryConfigurer {
  @Override
  public void configureTypeRegistry(TypeRegistry typeRegistry) {
    typeRegistry.defineParameterType(new ParameterType<>(
        "booleanType",
        "\\w+",
        Boolean.class,
        (Transformer) (arg) -> Boolean.valueOf(arg)
    ));
  }

  @Override
  public Locale locale() {
    return ENGLISH;
  }
}
```

And I have a gherkin step for test purposes 'Then 4 minus 2 equal 2'

The snippet recommendation now comes out as
```
You can implement missing steps with the snippets below:

@Then("{int} {booleanType} {int} {booleanType} {int}")
public void (Integer int1, Boolean booleanType, Integer int2, Boolean booleanType2, Integer int3) {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}
```
So any string is being assumed to be a boolean

## Context & Motivation

I'm writing a custom plugin and need to pass the snippets through to custom reports.

**Comment by aslakhellesoy** [comment]
Can you please reformat your issue using [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) so we can read the code?

**Comment by aslakhellesoy** [comment]
First off, Cucumber-JVM 3.0.0 and above generates snippets using [Cucumber Expressions](https://docs.cucumber.io/cucumber/cucumber-expressions/) and not Regular Expressions.

The Cucumber Expressions in the generated snippets will attempt to use registered parameter types if they match part of your undefined steps.

In your case, `\w+` matches both `minus` and `equal`, so it will suggest that parameter type.

If you don't want this behaviour you can either use a less generic regexp for your parameter type, or you can define your parameter type using `useForSnippets=false`.
