### ISSUE TITLE
default DataTableType.cell and DataTableType.entry are not available in TypeRegistryConfiguration

### ISSUE THREAD

**Issue by jlin412** [cucumber/cucumber-jvm#1418]
## Summary

From
https://github.com/cucumber/cucumber/blob/master/datatable/README.md
says, that I can use the following but .entry and .cell static methods. are not available in DataTableType.

```
public class TypeRegistryConfiguration implements TypeRegistryConfigurer {
    @Override
    public void configureTypeRegistry(TypeRegistry typeRegistry) {
      registry.defineDataTableType(DataTableType.cell(Airport.class));
      registry.defineDataTableType(DataTableType.entry(Geolocation.class));
    }
}
```
## Context & Motivation
For now, I can only define transformers.

## Your Environment
* Version used: 3..0.2
* Operating System and version: Mac 10.13.3
* Link to your project:

**Comment by aslakhellesoy** [comment]
It's not yet released (and therefore not available in Cucumber-JVM):

https://github.com/cucumber/cucumber/blob/master/datatable/CHANGELOG.md

**Comment by jlin412** [comment]
@aslakhellesoy Got it.  Looks like that it is done already.  When will it be released?

**Comment by aslakhellesoy** [comment]
It will be released when someone finds enough time to make a release, and decide to do that rather than something else ;-)

**Comment by mpkorstanje** [comment]
`datatable:1.1.3` has just been released to maven central. You can add that as a dependency for now or use the snap shot versions of cucumber 4.0.0.
