### ISSUE TITLE
ContextConfiguration can not be used on Base (Abstract) Step Definition class

### ISSUE THREAD

**Issue by obrejla** [cucumber/cucumber-jvm#1420]
## Summary

Hi, we have a lot of Step Definition classes and all of them extend `AbstractSteps` class where we have `ContextConfiguration` annotation defining Spring context. We have only one context.

But despite that Cucumber still complains that `cucumber.runtime.CucumberException: Glue class class ... and class ... both attempt to configure the spring context. Please ensure only one glue class configures the spring context`. But there is not any other option how to handle that, or we do not see any. Inserting annotation to just a random definition file is not a solution.

## Expected Behavior

Everything works and no exception complaining about more context configurations appears.

## Current Behavior

Exception is thrown
~~~
cucumber.runtime.CucumberException: Glue class class ... and class ... both attempt to configure the spring context. Please ensure only one glue class configures the spring context
~~~

## Possible Solution

Support `ContextConfiguration` on parents of Step Definition classes and do not throw an exception (or in general to not throw an exception when the context annotation is the same). Or document how to handle such a situations and provide best practice how to handle more step definition classes.

## Steps to Reproduce (for bugs)

1. To have e.g. 2 step definition classes, both extending `AbstractSteps`
2. Use `ContextConfiguration` Spring annotation on that Abstract base class
3. Try to run test with `@RunWith(Cucumber.class)`
4. Profit...

## Context & Motivation

This issue prevents us from upgrading cucumber from v2 to v3.

## Your Environment

* Version used: 3.0.2
* Operating System and version: Ubuntu 16.04 LTS

Thanks in advance.

**Comment by mpkorstanje** [comment]
Spring is setup such that only one class can provide the context configuration. Past implementations of cucumber picked an arbitrary class in an undefined manner. There was some logic to prevent you from shooting yourself in the foot. However this logic produces false positives when used in combination with Kotlin.

If you don't have a suitable step definition file to add the ContextConfiguration to you can always create [a step definition with an empty before hook](https://github.com/cucumber/cucumber-jvm/blob/master/examples/spring-txn/src/test/java/cucumber/examples/spring/txn/CucumberContextConfiguration.java). Cucumber will recognize any class that implements as step or hook as glue.

If you have a better solution please do provide a PR.

**Comment by obrejla** [comment]
Oki thanks, we already tried this "hack" but thought that there must be a better solution ;) Fair enough, thanks.

**Comment by ianyulianto** [comment]
Hi, i had the same problem before. I looked it up and found an answer. Place a file called `cucumber.xml` in root of your resources folder. That file will act as _context config xml_. Import all of your xml context to that file, and there you go~
