### ISSUE TITLE
Intellij IDEA - Cucumber for java

### ISSUE THREAD

**Issue by olyv** [cucumber/cucumber-jvm#1421]
Hi,

This is rather a question: as I can see, Cucumber 3.0 uses curly braces in step definitions to enclose parameters. For example 
```
I have {int} cucumbers in my belly
```

with correspondent 
```
@When("Trip Type: {tripType}")
public void cucumbers_inMyBelly(int cucumbers) {
   // my step
}
```
 
Is there any way to enable navigation in Intellij IDEA 2018.1? Or is the only way to modify Intellij "Cucumber for Java" plug-in?

**Comment by mlvandijk** [comment]
The "Cucumber for Java" plug-in will have to be updated. You can check https://youtrack.jetbrains.com to see if this issue has been reported yet and vote for it, or create an issue yourself.

**Comment by aslakhellesoy** [comment]
Dupe of cucumber/cucumber#434
