### ISSUE TITLE
Code is not getting executed, every time it is skipping

### ISSUE THREAD

**Issue by prashantsinha789** [cucumber/cucumber-jvm#1422]
1 Scenarios ([33m1 undefined[0m)
5 Steps ([33m5 undefined[0m)
0m0.000s

You can implement missing steps with the snippets below:

@Given("^User is already on login page$")
public void user_is_already_on_login_page() throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@When("^Title of login page is FreeCrm$")
public void title_of_login_page_is_FreeCrm() throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@Then("^User enters username and password$")
public void user_enters_username_and_password() throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@Then("^User clicks on the login button$")
public void user_clicks_on_the_login_button() throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@Then("^User is on home page$")
public void user_is_on_home_page() throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

This is my Repo : https://github.com/prashantsinha789/BDDTestFramework

**Comment by grasshopper7** [comment]
U shld check the glue value mentioned in the cucumberoptions, use java package instead. Post this on the help sites like - https://groups.google.com/forum/#!forum/cukes or https://stackoverflow.com/questions/tagged/cucumber
