### ISSUE TITLE
Check if step has failed

### ISSUE THREAD

**Issue by kathyrollo** [cucumber/cucumber-jvm#1429]
## Summary
We have `scenario.isFailed()` to determine if a scenario has failed but does not identify the particular step.

## Expected Behavior
Works similarly like the `Scenario` passed as param for scenario hooks, but this time a `Step` param for step hooks.

## Possible Solution
~~~
@AfterStep
public void afterStep(Step step) {
	if (step.isFailed()) {
		// Take screenshot and embed in HTML report
	}
}
~~~

## Context & Motivation
With the introduction of step hooks in 3.x.x, accessing various properties of a specific step becomes more useful.
In the above example, using `scenario.isFailed()` in `@After` hook will take the screenshot and embed it below the _last_ step which may not necessarily be the step where the failure has occurred (and has already been skipped). `step.isFailed()` will take the screenshot and embed it below the specific failing step.

## Your Environment
* Version used: 3.0.2
* Operating System and version: Win7 Pro SP1 x64

**Comment by mpkorstanje** [comment]
This should work with Scenario. It is unfortunately bugged and `isFailed` won't return the correct result.

I am hesitant to expose more functionality though. This is what the formatters are for.
