### ISSUE TITLE
Only a single snippet is generated when multiple parameter types match

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#1433]
Cucumber-Expressions can generate multiple expressions. We're only using [the first one](https://github.com/cucumber/cucumber-jvm/blob/5d4e181fb0ece7d86c7390f196bf50bf8a35d526/core/src/main/java/cucumber/runtime/snippets/SnippetGenerator.java#L37-L38).

We should print snippets for all expressions, the same way Cucumber.js does it.

**Comment by mpkorstanje** [comment]
Do you happen to have a sample handy somewhere? I don't have cucumber.js setup.
