### ISSUE TITLE
Incorrect test result status when run tests using cucumber-testng

### ISSUE THREAD

**Issue by chibux** [cucumber/cucumber-jvm#1435]
## Summary
If you scenario fails in the middle step and there are other steps after it then tests result is marked as _ignored_ if you ran your tests using IDE (IntelliJ) or it shows BUILD SUCCESS if you use `mvn test`
However result is reported correctly as _failed_ if the last step fails (remove the last step from feature file in the sample project).
Also same test reports correct results (as _failed_) both using IDE and Maven if we use _cucumber-junit_ instead. (see _junit_ branch of [sample project](https://github.com/chibux/cucumber-testng))
And same test reports correct result (as _failed_) both using IDE and Maven if we use _info.cukes:cucumber-testng:1.2.5_ (see _info.cukes_ branch of [sample project](https://github.com/chibux/cucumber-testng))

## Expected Behavior
if one of the steps fails the test result should be FAIL

## Current Behavior
if one of the steps fails but there are other steps after the failed one - test result shows as _ignored_ if run from IDE and BUILD SUCCESS if run using maven cmd.

## Steps to Reproduce (for bugs)

1. Run the test using IDE or cmd `mvn test`
2. If run the test from IDE (IntelliJ) then test result shows: _ignored_
3. If run from cmd using `mvn test` then test result shows:  _BUILD SUCCESS_

## Context & Motivation
We're trying to migrate to cucumber 3.0.2 but this issue is showstopper for us. And it requires a lot of changes to switch big project to junit.

## Your Environment

* Version used: cucumber - 3.0.2, java 8
* Operating System and version: MacOS, Windows
* Link to your project: [sample project](https://github.com/chibux/cucumber-testng)

**Comment by mpkorstanje** [comment]
Hey thanks for the excellent reproducer. I can't reproduce this with the latest snapshot so I think this is fixed. You can find instructions on getting the latest snapshot here: https://docs.cucumber.io/installation/java/#snapshot-releases

Feel free to reopen if the issue is somehow not resolved.

**Comment by chibux** [comment]
unfortunately I still see the same behavior with 3.0.3-SNAPSHOT.
The only time test shows as failed if you right-click the feature file and run it using IntelliJ in that case it runs using IntelliJ cucumber-plugin and somehow the test result is correct.
But if you right-click the _TestRunner_ class and run the test it still shows as ignored (this uses testng plugin I believe?).
Or if you run using `mvn clean test` - the result is _BUILD SUCCESS_.
I would reopen this ticket if you don't mind

**Comment by mpkorstanje** [comment]
Try 4.0.0-SNAPSHOT.

**Comment by chibux** [comment]
![mvn_cmd_screenshot](https://user-images.githubusercontent.com/8534108/44751245-82d75300-aacc-11e8-9e72-8dad95e0466d.png)
![testng_report_screenshot](https://user-images.githubusercontent.com/8534108/44751251-866ada00-aacc-11e8-8bde-3505cf3a05e0.png)

**Comment by chibux** [comment]
unfortunately couldn't find a way to reopen the issue. Would appreciate if you could take a look and reopen this.

**Comment by chibux** [comment]
confirming the fix for the scenarios described above in 4.0.0-SNAPSHOT.
Thanks!
