### ISSUE TITLE
StepDefAnnotation should be annotated with @Target(ElementType.ANNOTATION_TYPE)

### ISSUE THREAD

**Issue by lgoldstein** [cucumber/cucumber-jvm#1437]
## Current Behavior

```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface StepDefAnnotation {
}
```

## Possible Solution

```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.ANNOTATION_TYPE)
public @interface StepDefAnnotation {
}
```

## Context & Motivation

`@StepDefAnnotation` is a meta-annotation so it makes sense to allow it to be used only on other annotations (I am not aware of its semantics if used on classes, enum(s)).

## Your Environment

* Version used: 3.0.2
* Operating System and version: Fedora 28 + Java 8
* Link to your project: N/A

**Comment by mpkorstanje** [comment]
Thanks for pointing this out.
