### ISSUE TITLE
New option extraGlue in @CucumberOptions - adds packages to search, keeping default package

### ISSUE THREAD

**Issue by ekalin** [cucumber/cucumber-jvm#1438]
## Summary

It would be nice to have a new option in `@CucumberOptions` to specify packages to search for glue in addition to the default search path.

## Context & Motivation

The `glue` option in `@CucumberOptions` allows the glue search path to be specified, but it it is used, the default path (the current package) is not considered (unless it's also included in the list passed to `glue`).

It would be nice to have an option, say `extraGlue` that allows packages to be added to the search path, in addition to the current package. It would be useful in adding common steps and especially hooks.

## Possible Solution

I've looked at the code and I believe I can provide a pull request implementing this (including tests). I'm just checking before if someone would be against this feature.

**Comment by ekalin** [comment]
I guess I can implement accepting classes as well as package names, but it would need to be a separate option (extraGluePackageClasses or something like that).

**Comment by mpkorstanje** [comment]
Okay. Lets leave it out for now.

**Comment by kathyrollo** [comment]
Hi,

How does `extraGlue` differ from:
~~~
@CucumberOptions(glue = {
		"jcucumberng.project.datatable", "jcucumberng.project.hooks", "jcucumberng.project.stepdefs" })
~~~

**Comment by mpkorstanje** [comment]
When no glue is provided the glue defaults to the package of the runner (the class annotated with `@CucumberOptions`). 

When glue is provided this default is ignored. Not so with extra glue.

**Comment by mpkorstanje** [comment]
Ideally you put the runner one level above your glue and features. This means you dont have to configure them.

However this also means you can't add extra glue from a library that is a sibling package of your Runner.
