### ISSUE TITLE
Cucumber steps with lambdas defined outside of constructor (in a class method)

### ISSUE THREAD

**Issue by nenaddrop** [cucumber/cucumber-jvm#1444]
Hi,

I was looking at the cucumber documentation and found this reference (https://github.com/cucumber/cucumber-eclipse/wiki/Lambda-Expression-support-for-Cucumber-Java8) where it is mentioned that "..You may write step-definitions by using lambda-expression with both constructors and methods.". I have tried moving my step definitions using lambdas into a method (as described in the code snippet from the document page) but it doesn't seem to work. Cucumber signals that steps are unimplemented. What is strange is that I can still follow through to the correct step definition from my feature file using control+click on a scenario step

This discussion (found here https://github.com/cucumber/cucumber-jvm/issues/1233) gives out different impression. It is stated that Cucumber steps are not available outside of class constructor. What is the reason for this contradiction and which source tells the truth given that the issue page predates the actual cucumber-eclipse document page?

Thanks,
Nenad

**Comment by nenaddrop** [comment]
Just noticed documentation is actually for cucumber-eclipse plugin which doesn't need to have anything in common (and probably doesn't) with cucumber-JVM. Closing.

**Comment by mpkorstanje** [comment]
There are some cucumber derivatives that use lambda step definitions in a different way. Eclipse supports these derivatives.
