### ISSUE TITLE
Support adding class instances in the PicoContainer with the PicoFactory

### ISSUE THREAD

**Issue by ianlet** [cucumber/cucumber-jvm#1446]
## Summary

Improvement request: support adding class instances when extending the `PicoFactory` to setup the global context.

## Expected Behavior

As the `PicoContainer` supports adding component that are class instances, it could be interesting to also offer this functionality using the `PicoFactory`.

## Current Behavior

It is only possible to add a component in the `PicoContainer` based on a given `Class` with the `public boolean addClass(Class<?> clazz)` method.

## Possible Solution

I wrote a custom `PicoFactory` based on yours and the changes were quite simple:

I replaced the following line:
```java
private final Set<Class<?>> classes = new HashSet<Class<?>>();
```
By:
```java
private final Set<Object> classes = new HashSet<Object>();
```

And I added this method:
```java
public void addClass(Object classInstance) {
    classes.add(classInstance);
}
```

## Context & Motivation

I wanted to inject mocks of some interfaces in my support classes to run my acceptance tests in a smaller scope but I couldn't find an elegant way to do so using the `PicoFactory`.

I can submit a PR with these changes if you want.

**Comment by aslakhellesoy** [comment]
This would be a great addition @ianlet! For example, I think it might make it easier to inject different kinds of adapters into step definitions, allowing the same stepdefs to interact with various layers of the app (UI, HTTP, direct method call). I use this a lot to reuse scenarios against different assemblies of an app. This makes it possible to have high confidence at the cost of speed, and really fast scenarios at the cost of some reduced confidence.

I think the question is - what's the user API for configuring PicoContainer?

Could we add a configuration interface similar to [`cucumber.api.TypeRegistryConfigurer`](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/api/TypeRegistryConfigurer.java)? For example `io.cucumber.picocontainer.PicoConfigurer`.

Something like this:

```java
public interface PicoConfigurer {
    void configure(MutablePicoContainer pico);
}
```

I'm super pleased to see interest in this space. PicoContainer was my first successful open source project, and it's still holding up :-)

**Comment by mpkorstanje** [comment]
Regardless of the actual mechanism use to configure the object factory the most important part to making this work right is to ensure that we don't have a single global configuration. I.e. we should only search for object factory configures on the glue path.

To do this we'll have to pull the object factory creation out of the `JavaBackend` and into the core so we can instantiate some `ObjectFactoryProvider` with the `RuntimeOptions`. In this case the `PicoObjectFactoryProvider` would then search for it's specific plugins on the glue path.

Once configured we can create the backend with the object factory. This has the added benefit of removing the static ENV object from the java backend too.

**Comment by mpkorstanje** [comment]
Comes to mind that it would actually be helpful to invest some time in setting up internal DI for cucumber. It would rid us of allot of hacks.

**Comment by ianlet** [comment]
I'm currently scrolling through the cucumber codebase to know more about what's going on. So excuse me if I don't get everything right.

@mpkorstanje when you say `ensure we don't have a single global configuration`, do you mean we should be able to create multiple configurers?

So based on @aslakhellesoy idea, it would be something like a `TypeRegistryConfigurer` but instead of instantiating exactly one subclass (like [this](https://github.com/cucumber/cucumber-jvm/blob/e471442b0bd6a6d263bbcac03c8079107a36d84d/core/src/main/java/cucumber/runtime/BackendModuleBackendSupplier.java#L46)) we would try to instantiate every subclasses we could find on the glue path?

In that case, I don't think we would need to have a specific `PicoConfigurer` @aslakhellesoy . It could be an `ObjectFactoryConfigurer` such as:
```java
public interface ObjectFactoryConfigurer {
  void configure(ObjectFactory objectFactory);
}
```

And based on my use case I could use it like that:

```java
public class MediumScopeConfigurer implements ObjectFactoryConfigurer {
  @Override
  public void configure(ObjectFactory objectFactory) {
    String scope = System.getProperty("acc-test.scope", "");
    if (!scope.equals("medium-appservice")) return;
    
    objectFactory.addClass(mock(SomeService.class));
    objectFactory.addClass(MediumSupportClass.class);
  }
}

public class LargeScopeConfigurer implements ObjectFactoryConfigurer {
  @Override
  public void configure(ObjectFactory objectFactory) {
    String scope = System.getProperty("acc-test.scope", "");
    if (!scope.equals("large-ctrldb")) return;
  
    objectFactory.addClass(SomeServiceMySQL.class);
    objectFactory.addClass(LargeSupportClass.class);
  }
}
```

**Comment by mpkorstanje** [comment]
> @mpkorstanje when you say ensure we don't have a single global configuration, do you mean we should be able to create multiple configurers?

Yes. And through the glue you should have the ability to select which ones are enabled.

```
tests
  |- login
  |  |- RunCukes.java
  |  |- login.feature
  |  |- LoginSteps.java
  |  |- LoginPicoFactoryConfiguration.java
  |  |- LoginTypeRegistryConfiguration.java
  |- signup
  |  |- RunCukes.java
  |  |- signup.feature
  |  |- SignupSteps.java
  |  |- SignupPicoFactoryConfiguration.java
  |  |- SignupTypeRegistryConfiguration.java
  |- common
  |  |- CommonSteps.java
  |  |- SharedSteps.java
  |  |- CommonPicoFactoryConfiguration.java
  |  |- CommonTypeRegistryConfiguration.java

```

**Comment by aslakhellesoy** [comment]
Give us some more time stalebot - I’m still interested in this.

**Comment by ianlet** [comment]
Sorry, I didn't have time to get back to you on this thread.

**Comment by mpkorstanje** [comment]
I've made a start with extracting the the `ObjectFactory` from the Java module. It's on the `develop-v5` branch.

**Comment by mpkorstanje** [comment]
With the introduction of the `object-factory` option the class path scanning approach is no longer preferable. Instead you can select your object factory through the command line or `@CucumberOptions`. In the example below `JavaApiContainer` and `RestApiContainer` are implementations of `ObjectFactory` that are registered as SPIs.

```java
@RunWith(Cucumber.class)
@CucumberOptions(objectFactory = JavaApiContainer.class)
public class RunCucumberApiTest {

}

@RunWith(Cucumber.class)
@CucumberOptions(objectFactory = RestApiContainer.class)
public class RunCucumberRestApiTest {

}
```

The implementation of these classes would then decorate the `PicoFactory`.

```java
public class JavaApiContainer implements ObjectFactory {

    private final PicoFactory delegate = new PicoFactory();

    public MyFactory() {
        // Add concrete implementation classes here
        delegate.addClass(SomeImplementation.class);
    }

    @Override
    public void start() {
        delegate.start();
    }

    @Override
    public void stop() {
        delegate.stop();
    }

    @Override
    public boolean addClass(Class<?> glueClass) {
        return delegate.addClass(glueClass);
    }

    @Override
    public <T> T getInstance(Class<T> glueClass) {
        return delegate.getInstance(glueClass);
    }
```

Now this solution does involve quite some boiler plate. Which isn't nice. However given that we don't know if the `addClass` method will be sufficient or if deeper access to the `PicoContainer` backing the `PicoFactory` is needed I'm hesitant to provide more access.

If this solution does prove to be sufficient for most use cases we can come up with a way to reduce the boiler plate.

If this solution does not prove to be sufficient I then we best recommend that users re-implement `PicoFactory`. Cucumber can not  and should be aware of the vagaries of each and every container.

**Comment by mpkorstanje** [comment]
@aslakhellesoy after v5 you might want to update that blog post with this information.

**Comment by mpkorstanje** [comment]
We should still document `ObjectFactory` extension point.

**Comment by jnernest** [comment]
Can we also get instances retuned something like
 

public <T> List<T> getInstances(Class<T> aClass) {
    return pico.getComponents(aClass);
}

**Comment by mpkorstanje** [comment]
The `ObjectFactory` interface exists for the benefit of Cucumber. If you want to do more complicated things you might be better of reimplementing `PicoFactory` entirely.
