### ISSUE TITLE
Use ServiceLoader to find Backend and Object Factory implementations

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1450]
## Summary

We currently use class path scanning to find backend and factory implementations. This is slow and makes setting up mock for tests a pain (they are also discovered). A ServiceLoader avoids this problem. This wasn't possible earlier versions of Cucumber because we compiled these against java 6.

https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html

**Comment by aslakhellesoy** [comment]
Yes, this would be a great improvement!

**Comment by mpkorstanje** [comment]
Great! And yes, please use the v5 branch! You'll notice it has significant structural changes. 

This will help move us towards automatic module names, expose less of cucumbers implementation details, ect.

**Comment by mpkorstanje** [comment]
Resolved by a03dd01.
