### ISSUE TITLE
Code Mismatch

### ISSUE THREAD

**Issue by jk1121** [cucumber/cucumber-jvm#1457]
The code for testNGCucumberRunner instantiation is different in maven to what is available on Github . 
For version 3.0.2, code available in maven central is  : 
![3 0 2_maven_central_code](https://user-images.githubusercontent.com/16221733/45291416-b88a2c00-b50f-11e8-83ee-b953a902db9a.PNG)

And on github , code is :
![3 0 2_github_code](https://user-images.githubusercontent.com/16221733/45291505-04d56c00-b510-11e8-9296-6a6edb7f9e55.PNG)

Is the code being correctly published to maven central ?
Please revert in case I am missing something !!!!!
Thanks in advance.

**Comment by mpkorstanje** [comment]
The v3.02 source matching your first screenshot be found at the [v3.0.2 tag](https://github.com/cucumber/cucumber-jvm/blob/v3.0.2/testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java).

Your second screenshot shows the source from [master](https://github.com/cucumber/cucumber-jvm/blob/master/testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java) which is part of the most recent 4.0.0-SNAPSHOT release. 

I am not sure if your branching model has a name. It mostly resembles github flow but only non-snapshot versions are released to maven central. The SNAPSHOTS go to OSS Sonatype.
