### ISSUE TITLE
Allow parameter types acces to the test context

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1458]
## Summary

Allow parameter types to be defined as part of the Glue.

## Expected Behavior

The transform of a parameter type should be able to access the test context. This allows parameter types to be mapped to objects which can only be created by services inside the test context. 

For example:

```feature
    Given the awesome catalog
    When a user places the awestruck eels in his basket
    Then you will be shocked at what happened next
```

And I would like to implement the second step as `When("a user places the {product name} in his basket", (Product p) -> ...}`

Then my parameter type transform would have to know about "awestruck eels" as a product. However this product doesn't exist until after the awesome catalog has been loaded. So the only way to create an instance of this product would be by converting it in the step itself. This is quite distracting.

If I could instead define the parameter type as part of the glue it would be possible to do:

```java
public SomeGlueClass(Catalog catalog) implements En {
  ParameterType("product", ".*", Product.class, (String name) -> catalog.findProductByName(name));
}
```

```java
private final Catalog catalog;

@ParameterType(name="product", pattern=".*")
public Product findProductByName(String name) {
  return catalog.findProductByName(name);
}
```

## Possible Solution

Create annotations and lambda's to register a parameter type and pick them up as part of the glue. This will require a hierarchical type registry that delegates to the parent type registry when a parameter type could not be found.

**Comment by mpkorstanje** [comment]
If any one is interested in picking this up there is a small prototype in #1536.

**Comment by fslev** [comment]
Is there also support for anonymous parameter types {} ?

**Comment by mpkorstanje** [comment]
Yes. They go through the default parameter transformer which you can now define like a step.
