### ISSUE TITLE
Issues while migrating JBehave to Cucumber

### ISSUE THREAD

**Issue by muthupondi** [cucumber/cucumber-jvm#1468]
Currently we are using JBehave with serenity for our automation.We are trying to migrate our JBehave feature files and their implementations to cucumber and facing the following challenges.

Issues  :
1.We have multiple step names  in single the same  step definition as shown below .
How the below step definition can be changed as per cucumber ?
Note : We have 300 step definitions in our project similar to this.
**JBehave Step Definition:**
    @When("there are no items for $transaction")
    @Then("there are zero items for $transaction")
public void cleanEnv(String modality) throws InterruptedException{
    	login.cleanupEnv(modality);
    }

2.We have aliases with multiple values in a step definition as given below .Is there was we can write same pattern in cucumber  and call it from feature file
**JBehave Step Definition Eg :**
@When ( "user selects a $item item name from the list" )
    @Aliases ( values = {"user selects a $itemName item name from the list with no protocol",
                         "user selects a $itemId which contains list with same technical setting UID, name, population and anatomy with different checksum",
                         "user selects a $itemId which contains list with same technical setting UID and checksum with different DMID",
  public void selectitemNameFromItemList( String itemName) {
}

Please recommend the best way of how to migrate the above patterned step definitions  to cucumber.

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
