### ISSUE TITLE
Add verbose output

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#147]
From CLI: `--verbose`

From JUnit: `@Opts(verbose=true)`

This would make it easier to diagnose problems like #146 and #1234.

**Comment by mpkorstanje** [comment]
Most common problems seem to come from misconfigures paths. So logging which feature files and which glue files are found would be a good first step.

Logging what the DI container is doing would be a good second step.

**Comment by mpkorstanje** [comment]
I guess logging which back ends was loaded also helps

**Comment by mpkorstanje** [comment]
We can either log directly to standard out or we can use a logger framework. I would prefer the latter because it will work with existing frameworks and keep us from having to re-invent the wheel when it comes to log levels, parameter interpolation, ect, ect.

We are already using slf4j as a logging facade. Unfortunately it doesn't actually log. This is left to actual logger frameworks like log4j and logback. We can't use logback or  log4j because `cucumber-core` is library and not an application. Our choice of logging framework will conflict with theirs. 

A reasonable way to solve this would be to move `cucumber.api.cli.Main` and the option parsing to its own module and then set the log level programatically depending on the value of `--verbose`. This also requires that we untangle the option parsing from the actual runtime options and from the junit module.

**Comment by dkowis** [comment]
Another way to handle it, if we want to forcibly include a logging output framework, is to shade log4j2 into the cucumber namespace. 

SLF4j complains each time an API is not included to standard out, so it does be annoying, but you have to be watching for it.

**Comment by mpkorstanje** [comment]
Shading won't solve the right problem. When using slf4j there can only be one slf4j binding. 

https://www.slf4j.org/codes.html#multiple_bindings
> SLF4J API is designed to bind with one and only one underlying logging framework at a time. If more than one binding is present on the class path, SLF4J will emit a warning, listing the location of those bindings.
> ...
> Note The warning emitted by SLF4J is just that, a warning. Even when multiple bindings are present, SLF4J will pick one logging framework/implementation and bind with it. The way SLF4J picks a binding is determined by the JVM and for all practical purposes should be considered random. As of version 1.6.6, SLF4J will name the framework/implementation class it is actually bound to.
> ...
> Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose. When you come across an embedded component declaring a compile-time dependency on any SLF4J binding, please take the time to contact the authors of said component/library and kindly ask them to mend their ways.

**Comment by aslakhellesoy** [comment]
I'd prefer if the code that logs does not have a dependency on a logging framework, but rather on an internal `Log` interface. Classes that need to log can have a `Log` object injected.

We'll provide a `Log` implementation that delegates to a real logging framework.

**Comment by mpkorstanje** [comment]
Delegating to a real logging framework is what slf4j was created for. I suppose we could wrap slf4j with our own `Log` implementation that delegates to two different loggers.

````
CompositeLogger ---> Slf4j ---> Slf4jBinding (e.g. Logback) --> Output
 | --->  Simple Logger ---> Verbose output
````

**Comment by dkowis** [comment]
Well, that's the SLF4j interface. It's just not very flexible about binding to an underlying logging framework.

 We could move away from SLF4j, and use log4j2 directly, ensuring that it's always doing the right thing, properly shaded. Thus guaranteeing log output, but always requiring it to be configured within cucumber, and preventing others from integrating it...

**Comment by mpkorstanje** [comment]
Slf4j was introduced in #742/#696 because our dependency injection containers were all bringing their own logging dependencies along with them. It isn't used much outside of the DI modules though.

What would be the advantage of preventing others from integrating with our logging?

**Comment by mpkorstanje** [comment]
I'm going ahead with https://github.com/cucumber/cucumber-jvm/commit/31a9d500eb0aca62b597ec67fad1b9a67ce9c262 for now. But I am not married in anyway to this particular implementation. 

I do however need something to keep @mlvandijk busy. :D

**Comment by mlvandijk** [comment]
Very slowly making some progress, and adding log messages to the branch.
Some of my coworkers suggested it might be nice to be able to (also) configure the VerboseLogger? (as opposed to always to System.out)

**Comment by mpkorstanje** [comment]
The verbose logging is intended for the commandline tool. The output will be expected on system out.

The configurable logging goes through slf4j. This is up to the end user. Provided we leave that part  in.

**Comment by mlvandijk** [comment]
Makes sense, thanks!

**Comment by mpkorstanje** [comment]
We now have logging capabilities. What we log needs to grow organically. So I'm now closing this issue.

I don't think implementing `--verbose` will be possible until we have a proper stand alone CLI.
