### ISSUE TITLE
Expose ParameterType internal 'transformer' field via getter

### ISSUE THREAD

**Issue by lgoldstein** [cucumber/cucumber-jvm#1473]
## Summary

The `ParameterType` exposes all its internal fields via public getters - except for the _transformer_. I see no reason why it should not be exposed as well via such a getter - especially since it can be re-used by other code. E.g., in our project, I would like to automatically use it for internal conversions related to the type the parameter represents.

## Expected Behavior

```java
public CaptureGroupTransformer<T> getTransfomer() {
    return transformer;
}
```
## Current Behavior

```java
private final CaptureGroupTransformer<T> transformer;
```

## Possible Solution

```java
public CaptureGroupTransformer<T> getTransfomer() {
    return transformer;
}
```
## Context & Motivation

The `ParameterType` class contains useful code beyond the immediate _Cucumber_ usage - in our case, the transformer that can be used to convert a string (or a list of them) into some internal type. We would like to use the transformer for "internal" (i.e., non-Cucumber related) conversions as well in order to avoid code duplication as well have a standard and consistent way to execute such conversions.

## Your Environment

* Version used: 4.0.0
* Operating System and version: Fedora 28 + OpenJDK 1.8.181
* Link to your project: N/A

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber#489
