### ISSUE TITLE
First time Runner.java launch the browser ,Second time While run same class without changing the code its ask for " You can implement missing steps with the snippets below"

### ISSUE THREAD

**Issue by abhigaur** [cucumber/cucumber-jvm#1481]
## Summary

If I run the runner class first time its work fine,second time its not running and ask for adding the missing function.

## Step definition 
package stepDefinition;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;

public class loginStepDefinition {
	
	

@When("^browser is launched$")
public void browser_is_launched() throws Throwable {
	
	
	System.out.println("browser launched");
	

	 
System.setProperty("webdriver.chrome.driver", "C:\\POMbdd\\src\\test\\java\\resources\\chromedriver.exe");

WebDriver driver=new ChromeDriver();

driver.get("https://staging.evolution-system.com");
 
// Maximize browser
 
driver.manage().window().maximize();
	
	
}

@When("^user enter \"([^\"]*)\" and \"([^\"]*)\"$")
public void user_enter_and(String arg1, String arg2){
   
	
	
	System.out.println("user entered usernamt and password");
}

@Then("^user login successfully$")
public void user_login_successfully()  {
  
	
	
	System.out.println("user succesfuul login to the syustem");
}

@Then("^user is on Evo Home page$")
public void user_is_on_Evo_Home_page()  {
   
}
	

	
	
	

}

## Runner class
import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import cucumber.api.testng.AbstractTestNGCucumberTests;

@CucumberOptions(
		features = "src\\test\\java\\feature",
		glue={"src\\test\\java\\stepDefinition"})

public class EvoRunner extends AbstractTestNGCucumberTests {

}

[RemoteTestNG] detected TestNG version 6.14.3

1 Scenarios ([33m1 undefined[0m)
4 Steps ([33m4 undefined[0m)
0m0.000s

You can implement missing steps with the snippets below:

@When("^browser is launched$")
public void browser_is_launched() throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@When("^user enter \"([^\"]*)\" and \"([^\"]*)\"$")
public void user_enter_and(String arg1, String arg2) throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@Then("^user login successfully$")
public void user_login_successfully() throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@Then("^user is on Evo Home page$")
public void user_is_on_Evo_Home_page() throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

PASSED: feature(Login verificaion on evo)
        Runs Cucumber Feature

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

##POM.xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>POMbdd</groupId>
  <artifactId>POMbdd</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>POMbdd</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    
 
		
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.14.3</version>
			
		</dependency>

<dependency>
    <groupId>info.cukes</groupId>
    <artifactId>cucumber-junit</artifactId>
    <version>1.2.5</version>
    <scope>test</scope>
</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.11.0</version>
		</dependency>
		
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.5</version>
		</dependency>
 
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-jvm-deps</artifactId>
			<version>1.0.5</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>1.2.5</version>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<groupId>junit</groupId>
					<artifactId>junit</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>3.8.0</version>
		</dependency>
		
	</dependencies>
 
</project>

**Comment by mlvandijk** [comment]
@abhigaur Please note you are using an old version of Cucumber, and I'm not sure you have all of the right dependencies (afaik you don't need the `cucumber-jvm-deps`). 
Please see the [documentation](http://docs.cucumber.io/installation/java/) for which dependencies you need and their latest version. Make sure to use the same cucumber version for all cucumber dependencies.
Note that the `<groupId>` for Cucumber has changed since v2 and there were some breaking changes in v2, v3 and v4.
