### ISSUE TITLE
Running TestFX with Cucumber

### ISSUE THREAD

**Issue by Jeredriq** [cucumber/cucumber-jvm#1482]
## Expected Behavior

Running TestFX with Cucumber.

## Actual Behavior

TestFX doesnt create a new instance for Cucumber tests and therefore could not find any nodes. Even though my base class perfectly works with only testfx tests.

[For more details, please check stackoverflow question here](https://stackoverflow.com/questions/52853515/using-testfx-with-cucumber)

Seems like testfxbase doesnt start the application therefore couldnt find any nodes. Is there a way to achieve this?

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
