### ISSUE TITLE
Migrating 3.0.2 -> 4.1.0 and ScenarioImpl issue

### ISSUE THREAD

**Issue by tomaszwojciechowski** [cucumber/cucumber-jvm#1488]
In project that uses 3.0.2 I have:
`String error = ((ScenarioImpl) scenario).getError().toString();`
In 4.1.0 ScenarioImpl is not present. What will be the best way to refactor this code to use 4.1.0?

**Comment by mpkorstanje** [comment]
Using `ScenarioImpl` should have been a hint that this was an implementation detail. I am assuming you're using this for reporting purposes? In that case please consider implementing a `Plugin` instead.

You can enable your custom implementation of plugin by passing its fully qualified class name to `--plugin` or the `@CucumberOptions` equivalent.

For example:

https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/formatter/ProgressFormatter.java
