### ISSUE TITLE
New Feature: Include ThreadId/ExecutorId in Events

### ISSUE THREAD

**Issue by james-bjss** [cucumber/cucumber-jvm#1491]
## Summary
Propose that Events include the ThreadId/ExecutorId of the runner they originated from.

## Expected Behavior
Include the threadId of the executing runner in the events consumed by plugins.

## Current Behavior
The current behaviour only includes the TimeStamp and reference to the result/test step.

## Possible Solution

Add details of executing thread to events or as an alternative perhaps a mechanism to access the current executing step?

## Context & Motivation

Currently we use a request/response logging filter which ascertains the current executing step by querying the state of a reporter plugin.

This functionality no longer works since Cucumber 4.x as the event messages are not processed until the end of the test run when using a non-ConcurrentEventListener.

However even if this worked concurrently, it would not be possible to determine the current executing step when tests run in a parallel fashion. I believe one solution to this would be to add a ThreadId/ExecutorId to the messages received by these plugins in order make it easier to correlate.

In this instance I am referring to Allure formatter and it's Rest-Assured logging filter, so I will raise this separately on their issues page. However there may be other use cases for this?
*see:* https://github.com/allure-framework/allure2/issues/849

I may be barking up the wrong tree here though and there may be a better way to uniquely identify the current running step.  Would appreciate your thoughts.

## Your Environment

* Version used: 4.1.0

**Comment by james-bjss** [comment]
Discussed this on the other ticket and now understand that this is not needed. Please feel free to reject this.

**Comment by mpkorstanje** [comment]
No worries. Closed per request.
