### ISSUE TITLE
Use cucumber-parent pom

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/cucumber-jvm#1493]
## Summary

Aslak made [cucumber/cucumber-parent](https://github.com/cucumber/cucumber-parent) which extracts quite a bit of shared settings for all the java modules.

If you like you can start with setting it up in `cucumber-jvm`

## Expected Behavior

Cucumber-jvm builds with cucumber-parent pom
Remove a lot of duplication from cucumber-jvm pom

## Current Behavior

Lots of duplication

## Possible Solution

Cucumber-jvm builds with cucumber-parent pom

## Steps to Reproduce (for bugs)
N/A

## Context & Motivation
Remove duplication

## Your Environment
N/A

**Comment by mpkorstanje** [comment]
Resolved by #1494
