### ISSUE TITLE
Not able control the threads using maven failsafe plugin

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#1496]
_From @abhishek8908 on November 6, 2018 13:16_

I am using cucumber v4 . I configured my maven threads failsafe plugin to execute scenarios based on the number of threads provided. However, it executes all of them in parallel and ignores the thread count set.

## Expected Behavior
The scenarios should execute based on the number of threads provided.

## Current Behavior

All scenarios are getting executed in parallel.

below is my testRunner class:

```
package hook;

import cucumber.api.CucumberOptions;
import cucumber.api.testng.AbstractTestNGCucumberTests;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

@CucumberOptions(plugin = {"json:target/cucumber-report.json","html:target"}
,features = "D:/git-projects/cucumberVer4/src/test/features"
,extraGlue = "abhishek8908.stepdefs"
,monochrome = true)
public class TestRunner extends AbstractTestNGCucumberTests{
    @Test(dataProvider = "scenarios")

    @Override
    @DataProvider(parallel = true)
    public Object[][] scenarios() {
        return super.scenarios();
    }

}

```
POM config:

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.0</version>
                <executions>
                    <execution>
                        <id>acceptance-test</id>
                        <phase>integration-test</phase>
                        <goals>
                            <!--<goal>integration-test</goal>-->
                            <goal>integration-test</goal>
                        </goals>

                        <configuration>

                            <threadCount>1</threadCount>
                            <includes>
                                <include>**/*Runner.java</include>
                            </includes>
                            <!--<parallel>classes</parallel>-->
                            <testSourceDirectory>src/test/java/hook</testSourceDirectory>


                        </configuration>

                    </execution>
                </executions>
            </plugin>
```

## Steps to Reproduce (for bugs)

1. Create a runner in example
2. Configure threads in the failsafe plugin
3. Run the test using failsafe plugin.

## Your Environment

* Version used: 4.2.0
* Link to your project: https://github.com/abhishek8908/cucumber-v4-example

_Copied from original issue: cucumber/cucumber#525_

**Comment by mpkorstanje** [comment]
You are using Cucumber in combination with TestNG. In this scenario Cucumber acts like a regular TestNG test. As such you should consult TestNGs documentation on parallel execution. 

Currently in transit but you may find these useful. Leads me to think you have to use `
dataproviderthreadcount`.

https://stackoverflow.com/questions/31521466/testng-parallel-execution-with-dataprovider
https://stackoverflow.com/questions/31521466/testng-parallel-execution-with-dataprovider

**Comment by mpkorstanje** [comment]
@aslak this tweet says issues can now be moved by github. You can retire the issue mover.
https://twitter.com/natfriedman/status/1057678371256119297?s=19

**Comment by abhishek8908** [comment]
Thanks  @mpkorstanje it worked for me below is the config I am using

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>

                <configuration>
                    <properties>
                        <property>
                            <name>parallel</name>
                            <value>classes</value>
                        </property>
                        <property>
                        <name>threadCount</name>
                        <value>1</value>
                        </property>
                        <property>
                            <name>dataproviderthreadcount</name>
                            <value>5</value>
                        </property>
                    </properties>
                    <testSourceDirectory>src/test/java/hook</testSourceDirectory>


                </configuration>

                <executions>
                    <execution>
                        <id>acceptance-test</id>
                        <phase>integration-test</phase>
                        <goals>
                            <!--<goal>integration-test</goal>-->
                            <goal>test</goal>
                        </goals>

                    </execution>
                </executions>
            </plugin>
```
@mpkorstanje now since version 4 allows parallel execution I want to discontinue using cucumber-parallel-plugin , in that case how it generates runner , or if i understood correctly is this "extraglue" in the   options gonna helps us ?could you please elabrote a bit?

**Comment by mpkorstanje** [comment]
The parallel plugin only generated multiple runners for parallel execution of each runner. Bc. tests in a runner can now be executed in parallel you can discard the parallel plugin and you only need one runner. You'll have to write it though.

Otherwise it works the same as using a single runner. 
This is not in anyway related to extra glue.
