### ISSUE TITLE
Cannot use customer runner with intellij cucumber plugin

### ISSUE THREAD

**Issue by abhishek8908** [cucumber/cucumber-jvm#1497]
## Summary

Cannot use customer runner with Inteljj cucumber plugin

I have a custom Testng runner and want to configure intellij cucumber plugin to use the custom testng runner instead creating its own. I have gone through the cucumber cli and I cannot specify the runner package.

The Runner works fine when run through the surefire plugin but using the Cucumber IntelliJ it cannot figure out where is the runner to be used for the config.

What can be the possible solution for it?

**Comment by mlvandijk** [comment]
Can you provide some additional info like which version of Cucumber and IntelliJ, your runner and your configuration?

**Comment by abhishek8908** [comment]
Hi I am using cucumber 4.2.0 and Intellij Ultimate 182.4892.20 below is my runner

```
@CucumberOptions(plugin = {"json:target/cucumber-report.json", "html:target"}
        , features = "src/test/features"
        , extraGlue = {"com.tests.glue.commons"}
        , monochrome = true
        , strict = true)

public class HTFCucumberBaseTests extends AbstractTestNGCucumberTests {

    @BeforeClass(alwaysRun = true)
    public void prepareEnv() {
       BaseTests.prepareEnv();
    }

    @BeforeClass(alwaysRun = true)
    public void prepareBrowserEnv() {
      BaseTests.prepareBrowserEnv();
    }


    @Test(dataProvider = "scenarios")

    @Override
    @DataProvider(name = "scenarios", parallel = true)
    public Object[][] scenarios() {
        return super.scenarios();
    }
}
```

**Comment by mlvandijk** [comment]
Not sure IntelliJ plugin has been updated for v4.x tbh. You can always check youtrack

**Comment by aslakhellesoy** [comment]
Please report issues about Jetbrains products to Jetbrains.

**Comment by mpkorstanje** [comment]
> I have a custom Testng runner and want to configure intellij cucumber plugin to use the custom testng runner instead creating its own. I have gone through the cucumber cli and I cannot specify the runner package.

Cucumber has three runners, JUnit, TestNG and the CLI. They are mutually exclusive. So if you are using the CLI it will not start JUnit or TestNG for you.

In your TestNG runner you are preparing the environment, so you will have to use TestNG for everything. Since you also appear to be wanting to run in parallel you may want to consider moving this setup code to Cucumbers before hooks to ensure each scenario  has it's own clean environment.

**Comment by abhishek8908** [comment]
@mpkorstanje thanks for your consideration and thought on the issue.
All the preparation work needs to be done one time and the best solution I can think here is having a @beforeAll hook, I have seen a lot of urge for this feature do you have any thoughts on this?

**Comment by mpkorstanje** [comment]
BeforeAll hooks won't solve your problem. Multiple instances of cucumber can be run in parallel in the JVM.

In your scenario, you may need to synchronize your setup/teardown and use reference counting to determine when the environment can be disposed off.

https://en.m.wikipedia.org/wiki/Reference_counting

**Comment by mpkorstanje** [comment]
If it is this important to you, you can have a shot at trying to implement a before all hook but I reckon you'll find it an unreasonable amount of work.

If you need to run single tests consider using the various methods exposed in cucumber options to select tests or the `cucumber.options`.

**Comment by abhishek8908** [comment]
Not sure but looks likes this works for me 

```
    private static boolean dunit = false;
    @Before
    public void beforeAll() {
        if (!dunit) {
            Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            }));
            HTFBaseTests.prepareEnv();
            HTFBaseTests.prepareBrowserEnv();
            dunit = true;
        }
    }
```

**Comment by mpkorstanje** [comment]
Cool! Beware of the edge cases and race conditions.
