### ISSUE TITLE
Parallel Tests, define # of threads

### ISSUE THREAD

**Issue by mpaquettePax8** [cucumber/cucumber-jvm#1500]
## Summary

Apologies if this has been discussed elsewhere, couldn't find any documentation on this! 
Would like the ability to not only specify parallel =true in the cucumber options, but also to specify  exactly how many feature or scenarios I would like to be executed in parallel. 

## Possible Solution
I believe this could be achieved by using Selenium grid and limiting browser instances per node. 
BUT this would be super awesome to be able to specify in Cucumber. 

## Your Environment

* Version of core used: 4.0.2
*Java8:4.0.2

**Comment by mpkorstanje** [comment]
There is no parallel option in `CucumberOptions`. So I am assuming you are using testing. 

https://github.com/cucumber/cucumber-jvm/issues/1496

> In this scenario Cucumber acts like a regular TestNG test. As such you should consult TestNGs documentation on parallel execution.

> you may find these useful. Leads me to think you have to use dataproviderthreadcount.

> https://stackoverflow.com/questions/31521466/testng-parallel-execution-with-dataprovider
> https://stackoverflow.com/questions/31521466/testng-parallel-execution-with-dataprovider

And that should probebly be put into the readme.

**Comment by mpaquettePax8** [comment]
Ah yes my mistake! We are using TestNG for parallel execution by overriding the DataProvider. Thank you so much!

**Comment by mpkorstanje** [comment]
No worries. Would you mind helping out with a bit of documentation? This should be added to the readme of the TestNG module.

**Comment by mpkorstanje** [comment]
Cheers!
