### ISSUE TITLE
Cucumber with Junit in gradle project on JVM

### ISSUE THREAD

**Issue by kavikuma** [cucumber/cucumber-jvm#1512]
Not able to run stepdefinition file as it is giving me error "Test Ignored".

In Runner class i have given  path as feature="pathname" glue = ''pathname" and its executing feature file but after that its not executing step definition file instead it is giving me error of "Test Ignored"

**Comment by mlvandijk** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
