### ISSUE TITLE
Incorrect/Missing output inside the generated JUnit scenarios/steps

### ISSUE THREAD

**Issue by fslev** [cucumber/cucumber-jvm#1514]
## Incorrect/Missing output in generated Junit scenarios/steps

Hi,
I am using the latest version of cucumber-jvm **4.2.0**.
It seems that it has a problem in generating the JUnit test results.
After JUnit finishes running all features, when I click on one of the generated feature results inside Intellij Idea, the output shows the results from another feature.
Example in image attached:
![edited](https://user-images.githubusercontent.com/17047317/49602720-d8f04800-f991-11e8-9c85-25eaa2bd9d65.png)
I changed cucumber-jvm back to version **3.0.2** and it works fine.
Also, while scenarios are executed inside the JUnit report dialog, nothing is shown. After all scenarios are executed, only then the step definitions are displayed inside the JUnit console.

![edited1](https://user-images.githubusercontent.com/17047317/49603001-a5fa8400-f992-11e8-999e-3c030ee40aa5.png)

This also happens when I am running the features using Maven (mvn clean test): inside the terminal nothing is logged from Cucumber behalf, until all tests finish.
When using Cucumber version 3.0.2, everything seemed to work fine. The JUnit was displaying the cucumber steps inside the console, in real-time.

Here are my CucumberOptions:
```
@RunWith(Cucumber.class)
@CucumberOptions(features = "src/test/resources/features",
        glue = {"ro.cucumber.core.context.config", "ro.cucumber.core.basicstepdefs",
                "ro.cucumber.core.features.stepdefs"},
        plugin = {"pretty", "html:target/cucumber-html-report",
                "json:target/cucumber-report/report.json"}, tags = "not @Ignore")
public class CucumberCoreTest {
}
```

**Comment by mpkorstanje** [comment]
Cheers. But please report issues with IntelliJ and Cucumber 4.2.0 to Jetbrains.

https://youtrack.jetbrains.com/issue/IDEA-203098
https://youtrack.jetbrains.com/issue/IDEA-203099
https://youtrack.jetbrains.com/issue/IDEA-203395
