### ISSUE TITLE
Incorrect Match Step Definitions if no parameter

### ISSUE THREAD

**Issue by sgrillon14** [cucumber/cucumber-jvm#1517]
## Summary

`cucumber.runtime.junit.UndefinedThrowable: The step "I clean download directory." is undefined` because no parameter.

I want Cucumber match for:

```
    Given I start video capture in 'hello'.
    And I clean download directory.
    Given I start video capture in 'hello'?
    And I clean download directory?
```

but not match for:

```
    Given I start video capture in 'hello':
    And I clean download directory:
```

I use `[\\.|\\?]` for `dot` OR `question mark`  online =>  https://regex101.com/r/JC2T3L/1

## Expected Behavior

My gherkin code:

```
    Given I start video capture in 'hello'.
    And I clean download directory.
```

My java code:

    ```
    @And("I start video capture in '(.*)'[\\.|\\?]")
    public void startVideoCapture(String screenName) throws IOException, AWTException {
        ...
    }

    @Given("I clean download directory[\\.|\\?]")
    public void cleanDownloadDirectory() {
        ...
    }
```

## Current Behavior

I have this error message only on my 2nd sentence (without parameters):

```
You can implement missing steps with the snippets below:

@Then("I clean download directory.")
public void i_clean_download_directory() {
    // Write code here that turns the phrase above into concrete actions
    throw new cucumber.api.PendingException();
}
```

## Possible Solution

?? cucumber.runner#runStep(Scenario scenario) is never call

## Context & Motivation

I want migration from 2.1.0 to 4.2.1-SNAPSHOT

## Your Environment
* Version used: 4.2.1-SNAPSHOT
* Operating System and version: Unix, Windows
* Link to your project: https://noraui.github.io/

**Comment by mpkorstanje** [comment]
Cucumber 3.0.0 introduced [Cucumber Expressions](https://docs.cucumber.io/cucumber/cucumber-expressions/). Because Java doesn't have a way to see the difference between a regular expression and a string we're using [some heuristics](https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/java/heuristics.adoc).

So you can either try `^I start video capture in '(.*)'[\\.|\\?]$` or a more readable `I start video capture in {string}./?`.

**Comment by sgrillon14** [comment]
@mpkorstanje, you read too quickly this issue. The problem is not on the 1st sentence. Problem is only if no parameter.

`@Given("I clean download directory[\\.|\\?]")`

**Comment by mpkorstanje** [comment]
Quite possibly the same problem. Try adding the start and end sybols to that expression.

**Comment by sgrillon14** [comment]
` @Given("I clean download directory\\./\\?")` is OK for me, Thanks.

**Comment by sgrillon14** [comment]
I have a last question with this new syntax (expression).

before I use this:

`@Et("Je valide le mail d'activation (.*)[\\.|\\?]")`

But when I change to : 

`@Et("Je valide le mail d'activation {string}\\./\\?")` I have this error:

`cucumber.runtime.CucumberException: io.cucumber.cucumberexpressions.CucumberExpressionException: Parameter types cannot be alternative: Je valide le mail d'activation {string}\./\?`

I try with this but the same error:

`@Et("Je valide le mail d\'activation (.*)[\\.|\\?]")`

**Comment by Kaka69** [comment]
@mpkorstanje, I have same issue for my French customer: https://stackoverflow.com/questions/53859944/cucumber-no-match-gherkin-in-french-if-sentence-contain-apostrophe

**Comment by mpkorstanje** [comment]
@sgrillon14 I think you are confusing cucumber and regular expressions. If you intend to use regular expressions start your step definition with `^` and end it with `$`.  If you intend to use Cucumber expressions remove the regular expression bits from your step definition.

**Comment by mpkorstanje** [comment]
@Kaka69 that does not look like the same problem. Please create a new issue. Preferably with an MCVE as a github repository because I can't reproduce that. I suspect there may be some encoding issues going on.
