### ISSUE TITLE
Feature request: Generate Kotlin step defs

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/cucumber-jvm#1520]
## Summary
Would like to have the option to generate snippets in Kotlin instead of Java.

## Expected Behavior
Generate snippets in Kotlin, instead of Java

## Current Behavior
Generates snippets in Java (annotation style or lamdba) only

~~~
~~~

## Possible Solution
Add Kotlin snippets

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context & Motivation
Being able to generate Kotlin snippets would simplify development.
It would also make it easier for people to get started with Cucumber in Kotlin.
(Finally, it would simplify the tutorial in the docs, but that's a sidenote ;))

## Your Environment
N/A

* Version used:
* Operating System and version:
* Link to your project:

**Comment by mpkorstanje** [comment]
This is probably best done by implementing a backend for Kotlin. This will be easier to do after I've merged  `develop-v5` into `master`.

**Comment by bodiam** [comment]
Hi @mpkorstanje , I might be able to help on this. What exactly do you mean with 'implementing a backend for Kotlin' ?

**Comment by mpkorstanje** [comment]
Cucumber can be used with several JVM languages. Each language has a module responsible for discovering step definitions and creating the test context (the world). This module is called a backend.

On the `develop-v5` branch you can find a really clear example of how this is supposed to work for Java 8 in the [Java8Backend](https://github.com/cucumber/cucumber-jvm/blob/develop-v5/java8/src/main/java/io/cucumber/java8/Java8Backend.java). The maven module also contains the code that generates the step definition interfaces and everything else.

For the current `master` you can find the same information in the [`java`](https://github.com/cucumber/cucumber-jvm/tree/master/java/src/main/java/cucumber/runtime/java) but bear in mind that it hasn't been refactored yet and is burdened with several pragmatic solutions.

**Comment by bodiam** [comment]
Thanks for that! That looks pretty straightforward. Our project uses Cucumber and Kotlin a lot, so this would be a nice  feature to have. Let me get back to you on this.

**Comment by mpkorstanje** [comment]
@bodiam you mentioned you'd get back to me on this. Any news?

**Comment by bodiam** [comment]
Sorry, I switched jobs, and we're not as heavily invested in cucumber as what we used to, so didn't have the time to look into this, sorry!

**Comment by mpkorstanje** [comment]
Cheers. No problem. Any one else feel free to pick this up if you're interested.

**Comment by mpkorstanje** [comment]
Continued in #1829
