### ISSUE TITLE
Replace ResourceIterable with standard Java solutions

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1526]
Cucumber-JVM has rather inconsistent support for uri's in the feature path.

For example: `cucumber classpath:com/example/my/app.feature` and `cucumber src/main/java/com/example/my/app.feature` work but `cucumber file:src/test/resources/com/example/my/app.feature` does not. Nor does `cucumber hdfs:path/to/cloud/location/app.feature` or any other protocol that could be supported by the jvm.

At the same time we do support custom `ResourceIteratorFactory` implementations but only for resources on the classpath So `cucumber classpath:features.jar#!com/example/app.feature` works but `cucumber jar:src/test/resources/features.jar#!/com/example/app.feature` does not.

In essence we are mimicking functionality provided by [`FileSystem`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystem.html) and [`Path`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html) and are doing so poorly. Looking back in time this made sense as Cucumber was originally written for Java 6 when we didn't have nice things yet. 

Never the less it makes it rather hard to explain what exactly the feature path is and what people can do with it. This can be resolved by:

* [x] Ensuring that after parsing the feature path consists of proper URI's #1544.
* [x] Using [`Paths.get(URI uri)`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Paths.html#get-java.net.URI-), [`Files.walkFileTree`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#walkFileTree-java.nio.file.Path-java.util.Set-int-java.nio.file.FileVisitor-) and related utilities to scan and discover features. An example of this can be found in [junit-jupiter/PathScanner](https://github.com/cucumber/cucumber-jvm/blob/junit-jupiter/junit-platform-engine/src/main/java/io/cucucumber/jupiter/engine/resource/PathScanner.java). #1820

**Comment by mpkorstanje** [comment]
An example of this can be found in [junit-jupiter/PathScanner](https://github.com/cucumber/cucumber-jvm/blob/junit-jupiter/junit-platform-engine/src/main/java/io/cucucumber/jupiter/engine/resource/PathScanner.java).

**Comment by mpkorstanje** [comment]
https://groups.google.com/forum/m/#!topic/cukes/MIJLvqapbK8

Tangentially related, the plugin system has the same issues due to the URL output stream.

**Comment by 34875634567** [comment]
Also I think current implementation is failing to load feature files from the classpath when embedded in a JAR on account of using the `file:` scheme.

**Comment by mpkorstanje** [comment]
That is correct.

**Comment by 34875634567** [comment]
Related to this proposed fix:
<https://stackoverflow.com/questions/44069165/cucumber-no-backend-found-when-running-from-spring-boot-jar>

**Comment by mpkorstanje** [comment]
Nicely found.

**Comment by mpkorstanje** [comment]
https://github.com/cucumber/cucumber-jvm/issues/1117#issuecomment-308452834
> [It was not an option] to scan in the container (ie from the backend) since we can not have the right filesystem handling (jndi://, vfs://, ...)

Our home grown path scanning is also hindering the implementation of custom back ends.

**Comment by mlvandijk** [comment]
As #1544 was merged, does that mean first TODO is done?

**Comment by mpkorstanje** [comment]
Yes.

**Comment by mpkorstanje** [comment]
Another consideration. The resource loading should be provided as an interface that can be re implemented to facilitate various containers (e.g. a spring boot executable jar). In combination with a programmatic API this should make it possible to easily run cucumber tests from inside an application.

**Comment by mpkorstanje** [comment]
Reference to current problem/solutions with the spring jar:
 * https://stackoverflow.com/a/46564059/3945473
 * https://stackoverflow.com/questions/57995598
