### ISSUE TITLE
Documentation link not working

### ISSUE THREAD

**Issue by jsa34** [cucumber/cucumber-jvm#1538]
Location: https://github.com/cucumber/cucumber-jvm/tree/master/testng

> This will execute all scenarios in same package as the runner, by default glue code is also assumed to be in the same package. The @CucumberOptions can be used to provide **additional configuration** to the runner.

The link in the Readme.md for **additional configuration** links to an invalid page location.

**Comment by mlvandijk** [comment]
Hi @jsa34 - thanks for pointing that out. Should be fixed now!
