### ISSUE TITLE
SerenityRuner.initializationError » NoClassDefFound gherkin/ast/GherkinDocumen.

### ISSUE THREAD

**Issue by musiro77** [cucumber/cucumber-jvm#1539]
currently, when I run serenity with cucumber, I get the error

SerenityRuner.initializationError » NoClassDefFound gherkin/ast/GherkinDocumen.

its seems there is  a conflict with versions to support gherkin, gherkin seems to be used indrectly via serenity, hence no impact to change the gehrkin version

I use the following connfigurations:

<serenity.version>2.0.23</serenity.version>
<serenity.cucumber.version>1.9.20</serenity.cucumber.version>
 <serenity.maven.version>2.0.20</serenity.maven.version>

enclosed the trace and pom.xml..any suggestion? thanks

BR

Musiro

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running de.telekom.msp.qa.run.SerenityRuner
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.005 sec <<< FAILURE! - in de.telekom.msp.qa.run.SerenityRuner
initializationError(de.telekom.msp.qa.run.SerenityRuner)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.NoClassDefFoundError: gherkin/ast/GherkinDocument
	at cucumber.runtime.FeatureBuilder.parse(FeatureBuilder.java:56)
	at cucumber.runtime.model.CucumberFeature.loadFromFeaturePath(CucumberFeature.java:113)
	at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:49)
	at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:31)
	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:311)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:81)
	at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runner.Computer.getRunner(Computer.java:40)
	at org.apache.maven.surefire.junitcore.pc.ParallelComputerBuilder$PC.getRunner(ParallelComputerBuilder.java:317)
	at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at org.junit.runners.Suite.<init>(Suite.java:81)
	at org.junit.runner.Computer.getSuite(Computer.java:28)
	at org.apache.maven.surefire.junitcore.pc.ParallelComputerBuilder$PC.getSuite(ParallelComputerBuilder.java:291)
	at org.junit.runner.Request.classes(Request.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:96)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:77)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:53)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.ClassNotFoundException: gherkin.ast.GherkinDocument

pom.xml
----------

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>
        <groupId>myproject.com/groupId>
        <artifactId>gkcom</artifactId>
        <version>1.1.2-SNAPSHOT</version>
        <properties>
                <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
                <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                <serenity.version>2.0.23</serenity.version>
                <serenity.cucumber.version>1.9.20</serenity.cucumber.version>
                
                <serenity.maven.version>2.0.20</serenity.maven.version>
                <jira.plugin.version>1.8.0</jira.plugin.version>
                <webdriver.driver>firefox</webdriver.driver>
                <surefire.rerunFailingTestsCount>0</surefire.rerunFailingTestsCount>
                <serenity.take.screenshots>BEFORE_AND_AFTER_EACH_STEP</serenity.take.screenshots>
                <parallel.tests>1</parallel.tests>
                <webdriver.base.url></webdriver.base.url>
                <timestamp>${maven.build.timestamp}</timestamp>
    		<maven.build.timestamp.format>yyyy-MM-dd</maven.build.timestamp.format>
              			 	
   
        </properties>
        <repositories>
                <repository>
                        <snapshots>
                                <enabled>false</enabled>
                        </snapshots>
                        <id>central</id>
                        <name>bintray</name>
                        <url>http://jcenter.bintray.com</url>
                </repository>
        </repositories>
        <pluginRepositories>
                <pluginRepository>
                        <snapshots>
                                <enabled>false</enabled>
                        </snapshots>
                        <id>central</id>
                        <name>bintray-plugins</name>
                        <url>http://jcenter.bintray.com</url>
                </pluginRepository>
        </pluginRepositories>
        <dependencies>
    
               <dependency>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>properties-maven-plugin</artifactId>
                        <version>1.0-alpha-2</version>
                </dependency>
        
  
                <dependency>
                        <groupId>io.rest-assured</groupId>
                        <artifactId>rest-assured</artifactId>
                        <version>3.0.6</version>
                        <scope>test</scope>
                </dependency>

                <dependency>
                        <groupId>io.rest-assured</groupId>
                        <artifactId>json-schema-validator</artifactId>
                        <version>3.0.6</version>
                </dependency>

                <dependency>
                        <groupId>org.hamcrest</groupId>
                        <artifactId>hamcrest-all</artifactId>
                        <version>1.3</version>
                </dependency>
                <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-rest-assured</artifactId>
                        <version>${serenity.version}</version>
                         <scope>test</scope>
                </dependency>

                <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                         <scope>test</scope>
                </dependency>
                <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-screenplay</artifactId>
                        <version>${serenity.version}</version>
                         <scope>test</scope>
                </dependency>
                <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-screenplay-webdriver</artifactId>
                        <version>${serenity.version}</version>
                         <scope>test</scope>
                </dependency>
                <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-junit</artifactId>
                        <version>${serenity.version}</version>
                         <scope>test</scope>
                </dependency>
                <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-cucumber</artifactId>
                        <version>${serenity.cucumber.version}</version>
                        <scope>test</scope>
                </dependency>
              
                        <groupId>junit</groupId>
                        <artifactId>junit</artifactId>
                        <version>4.12</version>
                        <scope>test</scope>
                </dependency>

                <dependency>
                        <groupId>org.assertj</groupId>
                        <artifactId>assertj-core</artifactId>
                        <version>1.7.0</version>
                        <scope>test</scope>
                </dependency>
                
  
             <dependency>
                      <groupId>net.serenity-bdd</groupId>
		         <artifactId>serenity-jira-plugin</artifactId>
 	               <version>${jira.plugin.version}</version>
		</dependency>
  				<dependency>
                  <groupId>net.serenity-bdd</groupId>
                  <artifactId>serenity-jira-requirements-provider</artifactId>
                  <version>${jira.plugin.version}</version>
                </dependency>
             
			
		  	
					
			
					
					</dependencies>
      
	
        <build>
                     
            
               
                <plugins>
                
			      
                 
                        <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.2</version>
                                <configuration>
                                       <source>1.8</source>
                                       <target>1.8</target>
                                </configuration>
                        </plugin>

                      
                        <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-surefire-plugin</artifactId>
                                <version>2.19</version>
                                <configuration>
                                    <forkCount>1</forkCount>
							        <reuseForks>true</reuseForks>
							        <includes>
							            <include>*.class</include>
							        </includes>
					   			       <testFailureIgnore>true</testFailureIgnore>
                                       <skip>true</skip>
                                </configuration>
                        </plugin>

                    
                        <plugin>
                                <artifactId>maven-failsafe-plugin</artifactId>
                                <version>2.18</version>
                                <configuration>
                                       <includes>
                                               <include>**/*.java</include>
                                       </includes>
                                       <systemProperties>

                                               <tags>${tags}</tags>
                                       </systemProperties>
                                       
                                        <parallel>classes</parallel>
					                    <threadCount>1</threadCount>
					                    <perCoreThreadCount>true</perCoreThreadCount>

                                </configuration>
                                <executions>
                                       <execution>
                                               <goals>
                                                       <goal>integration-test</goal>
                                                       <goal>verify</goal>
                                               </goals>
                                                       </execution>
                                </executions>
                        </plugin>

     
                        <plugin>
                                <groupId>net.serenity-bdd.maven.plugins</groupId>
                                <artifactId>serenity-maven-plugin</artifactId>
                                <version>${serenity.maven.version}</version>
                                
                                <executions>
                                  <execution>
                                     <id>serenity-reports</id>
                                     <phase>post-integration-test</phase>
                                     <goals>
                                       <goal>aggregate</goal>
                                     </goals>
                                  </execution>
                                </executions>
                        
                        </plugin>
                </plugins>
                
        </build>

</project>

**Comment by mlvandijk** [comment]
Hi @musiro77 - this looks like an issue with Serenity, please open an issue there: https://github.com/serenity-bdd/serenity-cucumber
