### ISSUE TITLE
cucumber-jvm can't find step definitions on the classpath when running in a windows environment because cucumber.runtime.io.ResourceLoaderClassFinder#PACKAGE_PATH_SEPARATOR is hardcoded to '/'

### ISSUE THREAD

**Issue by ivelkov** [cucumber/cucumber-jvm#1540]
## Summary

cucumber-jvm can't find step definitions on the classpath when running in a windows environment because cucumber.runtime.io.ResourceLoaderClassFinder#PACKAGE_PATH_SEPARATOR is hardcoded to '/' and ResourceLoaderClassFinder#getClassName doesn't replace path separators with '.'.
Resources have been  generated using the cucumber.runtime.io.FileResourceIteratorFactory which on windows uses '\'.

## Possible Solution

Change cucumber.runtime.io.ResourceLoaderClassFinder#PACKAGE_PATH_SEPARATOR to java.io.File.separator

**Comment by mpkorstanje** [comment]
It would probably be better to fix this in [`FileResource`](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/io/FileResource.java#L31) as `ZipResource` will return paths separated by forward slashes.

**Comment by ivelkov** [comment]
Just tested it. Seems ok. Thanks for the prompt response.

**Comment by mpkorstanje** [comment]
Thanks for spotting/debugging. There should be a new version out in a short while.
