### ISSUE TITLE
Running cucumber scenarios using TestNG (Scenario level)

### ISSUE THREAD

**Issue by ankitsuhane** [cucumber/cucumber-jvm#1542]
Dear Team,

There is already an issue logged earlier but unfortunately I am not able to find its documentation. May be also because i am new to Git Community and do not know much about how to traverse.

Issue: [#1113](https://github.com/cucumber/cucumber-jvm/issues/1113)

I see that issue is close so i presume that now we can map and run one TestNG Test case with one Cucumber scenario irrespective to Feature.

I request you to please help me asap as I have to deliver this kind of code to customer, 
Since I knew that I am not asking anything new but asking but more like a help thats why i have not write issue in standard template. 

Please help

**Comment by mpkorstanje** [comment]
Have a look at the [testng example](https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-calculator-testng). If you need more (possibly professional) support please try one of the options here: https://cucumber.io/support
