### ISSUE TITLE
Additional context in BeforeStep / AfterStep hook

### ISSUE THREAD

**Issue by SJrX** [cucumber/cucumber-jvm#1546]
## Summary

I would like more information passed into ```BeforeStep``` and ```AfterStep``` hooks so that I can do more powerful things such as enforce code coventions and smarter fixture setup and tear down.

## Expected Behavior

If I implement a ```BeforeStep``` or ```AfterStep``` hook I should have the ability to somehow know which step I'm before or after so that I can do more advanced functionality.

1) Enforce rules 

1) Enforce that no Given step is called after a When or Then clause has been executed.
2) Do some post processing or system initialization. 

## Current Behavior

The ```cucumber.api.Scenario``` object currently has only the following methods:

```java

    Collection<String> getSourceTagNames();

    Result.Type getStatus();

    boolean isFailed();

    void embed(byte[] data, String mimeType);

    void write(String text);

    String getName();

    String getId();

    String getUri();

    List<Integer> getLines();
```

So there is almost know information about the test steps being executed.

## Possible Solution

Add the following methods to Scenario ```cucumber.api.Scenario```
```
TestCase getTestCase();
```
One other method that tells me where in the test case I am, and finally the addition of a way of determining the Keyword of the current step I'm on (i.e., Given, When or Then).

## Context & Motivation

There are a couple uses cases right now:

1. We'd like to force people to use steps in the right order, (i.e., Given/When/Then) 

In this case, with more information we could do something like (I'm glossing over the fact that test steps include hooks):
```
@Before
    public void before(Scenario scenario) {

        int nextTestStep = scenario.getStepResults().size();
        String keyword = scenario.getTestCase().getTestSteps().get(nextTestStep).getStepDefinitionMatch().getStepDefinition().getKeyword();
        
        if(keyword.equals("Given"))
        {
            if(lastKeyword != null && lastKeyword.equals("Given"))
            {
                throw new IllegalStateException("You cannot call a Given step after after calling " + lastKeyword);
            }
        }
    }
```

2. We'd like to specify our fixtures using the Given stages and only build once.

We have a bunch of `Given` step definitions and they are reusable and nice to use and we are using another layer of abstraction to simplify state management. So we always have a full picture of the system in memory and each Given step makes the incremental changes to it as needed.

However right now each `Given` step needs to actually build and commit this picture because it doesn't know whether the next step is a `Given` which specifies more state or a `When` which expects the system to have already been built.

With more information we could do something like (I'm glossing over the fact that hooks):

```
 String lastKeyword = null;

    @Before
    public void before(Scenario scenario) {

        int nextTestStep = scenario.getStepResults().size();
        String keyword = scenario.getTestCase().getTestSteps().get(nextTestStep).getStepDefinitionMatch().getStepDefinition().getKeyword();
        
        if(!keyword.equals("Given"))
        {
            if(lastKeyword != null && lastKeyword.equals("Given"))
            {
                doBuild();
            }
        }
    }
```

## Workarounds

With Java (and not Java 8) style of declaring fixtures you can use reflection to get everything you need, although one class `cucumber.runtime.java.JavaStepDefinition` is not public even though the java8 version is `cucumber.runtime.java8.Java8StepDefinition`.

With Java 8, this information is seemingly lost as the methods that are declared do not capture their names.

**Comment by SJrX** [comment]
A summary of my points from slack, cleaned up a bit (I didn't want to just put them in the edited version of the ticket, since I thought it would look weird) :smile:, and since this ticket will remain open.

1.  A linter is sub optimal even if there were a good linter which works with the Java ecosystem, as it's infrastructure we don't otherwise need, and it delays feedback to developers until after they have created all their API tests and either they remember to run the linter or they wait for the PR scan to fail.  

2. You are correct my example is not a general use case, they are specific for me and I should solve the problem on my end. However this is why frameworks develop hooks, to allow people to implement their own functionality. If this request was "Please create an `@BeforeFirstWhen` annotation and the method should be invoked only one time before the first when, then yeah I'd say it shouldn't be implemented. But this feature request is that about the hooks functionality that are [advertised as part of the public documentation](https://docs.cucumber.io/cucumber/api/#beforestep), as a tool for giving me the test developer a chance to add custom functionality. I struggle to see looking at the information available for `cucumber.api.Scenario` what some examples of useful step hooks are. Why do they merit documenting on the main page. They seem to be tailor made for HTML report generation, and provide just enough support for that. I noticed in the example code that there seem to be no examples of step hooks. To me it seems right now they just not have been publicly documented as they are internal only.

By analogy `cucumber.api.junit.Cucumber` is about hooking into JUnit functionality and extending it for use with Cucumber. They added the `org.junit.runner.RunWith` annotation, and construct that class passing in enough context for you to do useful things in particular they pass in the `java.lang.Class` pointing to where the class is defined. They could certainly have implemented `org.junit.runner.RunWith` and not pass any context, it would just be far less useful and most people probably could not use it as an extension point. [Junit5 's beforeEach](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/extension/BeforeEachCallback.html) gives you an `ExensionContext` with all sorts of useful information.

This was the [commit](https://github.com/SJrX/cucumber-jvm/commit/32f2f11794b33efad99395c2820b6bbd1b3e0a33) I did which implemented feature, although as we discussed it wouldn't be accepted so I didn't bother figuring out where the best place to put tests was, although I did implement an example of the hooks to force the conventions in [Java style](https://github.com/SJrX/cucumber-jvm/blob/32f2f11794b33efad99395c2820b6bbd1b3e0a33/examples/java-calculator/src/test/java/cucumber/examples/java/calculator/RpnCalculatorStepdefs.java#L57) and [Java 8 style](https://github.com/SJrX/cucumber-jvm/blob/32f2f11794b33efad99395c2820b6bbd1b3e0a33/examples/java8-calculator/src/test/java/cucumber/examples/java/calculator/RpnCalculatorStepdefs.java#L56) as examples of usages.

There is no need to reply to the above, but if you decide in the future that you'd be open to this in 5.0.0 or beyond, I'd be open to re-implementing it and sending a PR.

Anyway thank you for spending the time to discuss this with me in Slack and cheers!

**Comment by mpkorstanje** [comment]
> There is no need to reply to the above, but if you decide in the future that you'd be open to this in 5.0.0 or beyond, I'd be open to re-implementing it and sending a PR.

I you want to help out and develop a proper test context after v5 that'd be great. I believe JUnit 5 picked the right architecture but it is orthogonal to Cucumbers current architecture.
