### ISSUE TITLE
Filtering based on line number of feature file not working in version 4.2.1 and 4.2.2

### ISSUE THREAD

**Issue by grasshopper7** [cucumber/cucumber-jvm#1547]
## Summary

In the runner I have a feature file with a specific line number mentioned. In version 4.2.1 and 4.2.2 it does not work correctly. It works perfectly in 4.2.0. Tried with both junit and testng.

`features = "src/test/resources/feature/scenarios.feature:8"`

## Expected Behavior

It should only run the scenario at the specified line number.

## Current Behavior

Version 4.2.1 - It says that all the steps are undefined.
Version 4.2.2 - It runs all the scenarios in the feature file.

## Your Environment

* Version used:  4.2.2, 4.2.1
* Operating System and version: Windows 8.1
* Link to your project:

**Comment by grasshopper7** [comment]
private Map<String, List<Long>> lineFilters;
{src/test/resources/feature/scenarios.feature=[3]}

In 4.2.0
String picklePath = pickleEvent.uri;
picklePath  value is **src/test/resources/feature/scenarios.feature**

In 4.2.2 and 4.2.1
String picklePath = pickleEvent.uri;
picklePath  value is **"src\test\resources\feature\scenarios.feature"**

This if condition does not work correctly as the fileseparators of the picklePath variable differs in the versions.
if (!lineFilters.containsKey(picklePath)) {
            return true;
        }

I am on Windows 8.1. Which windows u have tested on?

**Comment by mpkorstanje** [comment]
I don't have access to a windows machine. Ever since BYOD became the norm they just disappeared. It's all Mac and Unix these days. 

And you are correct. I've got a fix for this in https://github.com/cucumber/cucumber-jvm/pull/1544 we'll just stop passing files around and instead use URI's.

**Comment by mpkorstanje** [comment]
Doesn't look like Travis is working today. Could you build that branch from source and confirm it works?

**Comment by grasshopper7** [comment]
It is not working, getting same behavior as 4.2.2. All scenarios are running.

Was getting build errors with these two tests failing in cucumber-core -> snippets_are_generated_for_correct_locale() in UndefinedStepsTrackerTest and UndefinedStepsTrackerTest() in FileResourceTest. Set them to ignore to build.

Will try and debug a bit later in the day and update here.

**Comment by grasshopper7** [comment]
It works. Back to 4.2.0 behavior on windows.

Though while building the following tests are failing in cucumber-core. Had set them to ignore to build.
UndefinedStepsTrackerTest - snippets_are_generated_for_correct_locale
RuntimeOptionsTest - understands_whitespace_in_rerun_filepath
FeaturePathTest - can_parse_absolute_path_form
FeaturePathTest - can_parse_windows_absolute_path_form

Also cucumber-weld build fails in this test with NPE.
WeldFactoryTest - stopCalledWithoutStart

**Comment by grasshopper7** [comment]
Does not work for me even after setting encoding to JVM, it gives below error -
Caused by: gherkin.ParserException$CompositeParserException: 
Parser errors:
(2:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '???????:'
(3:3): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '????????:'
(4:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '* ?'
(5:0): unexpected end of file, expected: #TagLine, #FeatureLine, #Comment, #Empty
	at cucumber.runtime.UndefinedStepsTrackerTest.snippets_are_generated_for_correct_locale(UndefinedStepsTrackerTest.java:129)

Though if I run the test on its own it works.
