### ISSUE TITLE
Build on Windows machine is broken

### ISSUE THREAD

**Issue by amozhenin** [cucumber/cucumber-jvm#1551]
When building cucumber on Windows machine, several tests  are failing:

Environment
OS: Windows 10
System encoding: Cp1251
Cucumber version used: git master branch

1.  cucumber.runtime.UndefinedStepsTrackerTest.snippets_are_generated_for_correct_locale
fails with

cucumber.runtime.CucumberException: 
gherkin.ParserException$CompositeParserException: Parser errors:
(2:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'пїЅпїЅпїЅпїЅпїЅпїЅпїЅ:'
(3:3): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ:'
(4:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '* пїЅ'
(5:0): unexpected end of file, expected: #TagLine, #FeatureLine, #Comment, #Empty
	at cucumber.runtime.UndefinedStepsTrackerTest.snippets_are_generated_for_correct_locale(UndefinedStepsTrackerTest.java:127)
Caused by: gherkin.ParserException$CompositeParserException: 
Parser errors:
(2:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'пїЅпїЅпїЅпїЅпїЅпїЅпїЅ:'
(3:3): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ:'
(4:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '* пїЅ'
(5:0): unexpected end of file, expected: #TagLine, #FeatureLine, #Comment, #Empty
	at cucumber.runtime.UndefinedStepsTrackerTest.snippets_are_generated_for_correct_locale(UndefinedStepsTrackerTest.java:127)

This is due to the bad encoding used to convert from String to InputStream in several methods.

2. cucumber.runtime.java.weld.WeldFactoryTest.stopCalledWithoutStart
fails with

java.lang.AssertionError: 
Expected: is a string starting with "\nIf you have set enabled=false in org.jboss.weld.executor.properties and you are seeing\nthis message, it means your weld container didn't shut down properly. It's a Weld bug\nand we can't do much to fix it in Cucumber-JVM.\n\njava.lang.NullPointerException\n\tat cucumber.runtime.java.weld.WeldFactory.stop"
     but: was "
If you have set enabled=false in org.jboss.weld.executor.properties and you are seeing
this message, it means your weld container didn't shut down properly. It's a Weld bug
and we can't do much to fix it in Cucumber-JVM.

java.lang.NullPointerException
	at cucumber.runtime.java.weld.WeldFactory.stop(WeldFactory.java:50)

This test fails because Unix line endings are hardcoded in the test.

**Comment by mpkorstanje** [comment]
Cheers! Much appreciated.
