### ISSUE TITLE
Add support for per-feature json reports

### ISSUE THREAD

**Issue by ekalin** [cucumber/cucumber-jvm#1553]
## Summary

I'd like a reporting plugin that instead of grouping all features in one JSON report, outputs one JSON report per feature.

The motivation is the case when there are multiple runners, sharing a common configuration via @CucumberOptions in a base class. If all tests are run with `mvn verify` (or something equivalent), the JSON report will only have the results of the last feature run.

Having a plugin that outputs one report per feature would solve that problem.

## Possible Solution

I've looked at the code and the JSONFormatter plugin and it seems reasonably simple to implement. To avoid making JSONFormatter too complex by having to handle the current functionality and the per-file reports, I'd extract most of the JSON formatting to a super class, make JSONFormatter and the new plugin inherit from it, and each of these plugins would only have code relevant to the parts that differ (mostly the ~~TestSourceRead~~TestCaseStarted event).

Let me know if you think this is a worth feature and if the proposed solution seems adequate.

**Comment by mpkorstanje** [comment]
Hey thanks for looking to contribute! Much appreciated.

Unfortunately while this solution solves your specific problem but doesn't solve it in general. It's possible to define multiple runners for the same feature, each targeting a different scenario. So I don't think it would be good to have this as part of `cucumber-core`.

However you can still use `plugin=com.example.MyCustomPlugin` in `CucumberOptions` to launch your plugin and solve your specific problem.
