### ISSUE TITLE
feature path listing same feature file with multiple lines only runs first test

### ISSUE THREAD

**Issue by nishantvas** [cucumber/cucumber-jvm#1556]
## Summary

When providing list of scenarios in a feature file using the line number like so
```
features = {
"Folder1/featureFile1.feature:10",
"Folder1/featureFile1.feature:13",
"Folder1/featureFile1.feature:15",
"Folder1/featureFile1.feature:17"
}
```
The 
cucumber.runtime.model.CucumberFeature#loadFromFeaturePath
Function only runs the first line i.e. Scenario or Example on Line 10

## Expected Behavior

If we're providing multiple line ids like so, it should run all the tests

## Current Behavior

```
features = {
"Folder1/featureFile1.feature:10:13:15:17"
}
```

The above however is parsed normally and each scenario is run

**Comment by grasshopper7** [comment]
This works as expected on Windows with cucumber version 4.2.3. Tried with multiple scenarios in same feature file and across different feature file. What OS u on?

**Comment by mpkorstanje** [comment]
@nishantvas please feel free to reopen this if this is a problem with the latest version.
