### ISSUE TITLE
Java11 support - Feature Request

### ISSUE THREAD

**Issue by rpjesivac** [cucumber/cucumber-jvm#1557]
## Summary

Java is now coming with more frequent releases (we’ll be getting Java updates twice a year and a LTS version every three years) and as much as it is not practical to support every single release I believe there should be a Cucumber support for LTS releases. 

Currently Cucumber supports Java  8 and it does not support Java9, Java 10, and Java11.
However, Java 11  is the LTS release and I would expect that LTS releases are supports by Cucumber. (JBehave supports it but we don't want to make that switch)

When we can expecte Cucumber support for Java 11?

Thanks!

**Comment by mpkorstanje** [comment]
Cucumber can be build on OpenJDK 11 and the examples all pass. Could you be a bit more specific about the problems you encounter and/or the features you are missing?

> When we can expect Cucumber support for Java 11?

Cucumber is an open source project and generally moves at the at the speed of it's contributors. As the contributors are primarily unpaid volunteers there are no time tables or schedules. Would you be willing and able to contribute?

**Comment by Blackwolf291** [comment]
the split package org.springframework.test.context prevents cucumber spring from being on a single module path with spring-test, this is one thing that would help if it were changed

**Comment by mpkorstanje** [comment]
There is a lovely bit of technical debt attached to that. Please see: 
https://github.com/cucumber/cucumber-jvm/issues/1470 for a solution.

In short the split package exists to ensure parallel execution is possible with spring. It need not exist but fixing it does require a reimplementation of cucumber-spring.

**Comment by treaves** [comment]
The documentation also still states only up to Java 8 is supported.

**Comment by mlvandijk** [comment]
@treaves afaik that is still true

**Comment by treaves** [comment]
The documentation likely needs to be updated. As @mpkorstanje refers to above, it seems to work. I got in running tests in two Dropwizard JDK 11 projects yesterday.

**Comment by mpkorstanje** [comment]
I think the documentation needs a bit more nuance.

For some use cases (e.g. running tests) Cucumber can be used with Java 11 without any problems. However other use cases that require Cucumbers code to be modularized (e.g. frameworks that use Cucumber) are not yet supported.

**Comment by mpkorstanje** [comment]
@Blackwolf291 @rpjesivac  @treaves would you mind trying with the latest `5.0.0-SNAPSHOT` and see how Java 9+ works for you?

https://cucumber.io/docs/installation/java/#snapshot-releases

**Comment by mpkorstanje** [comment]
With all the split packages gone and all modules having an automatic module name I reckon we're done here. Next step will be `module-info.java` but it is not required for Java 9+.
