### ISSUE TITLE
I am using a feature-scenario Outline steps, which need to use data from a table, but the suggested step definitions are either not uniform or correct.

### ISSUE THREAD

**Issue by PrasadNutalapati** [cucumber/cucumber-jvm#1559]
## Current Behavior

```


```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by mpkorstanje** [comment]
Please provide sufficient information tounderstand and reproduce the problem.
