### ISSUE TITLE
Windows running feature file throws IllegalArgumentException

### ISSUE THREAD

**Issue by jsa34** [cucumber/cucumber-jvm#1564]
## Summary
Running a feature file throws exception:
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported scheme: C:/Users/me/IdeaProjects/automated-tests/src/test/resources/features/subgroup/test.feature
	at cucumber.runtime.io.MultiLoader.resources(MultiLoader.java:28)
	at cucumber.runtime.model.FeatureLoader.loadFromFeaturePath(FeatureLoader.java:41)
	at cucumber.runtime.model.FeatureLoader.load(FeatureLoader.java:35)
	at cucumber.runtime.model.FeatureLoader.load(FeatureLoader.java:21)
	at cucumber.runtime.FeaturePathFeatureSupplier.get(FeaturePathFeatureSupplier.java:23)
	at cucumber.runtime.Runtime.run(Runtime.java:67)
	at cucumber.api.cli.Main.run(Main.java:26)
	at cucumber.api.cli.Main.main(Main.java:8)

This was not a problem in version 4.2.0, but is in 4.2.3.

## Expected Behavior
When running a feature file, it should pick up the classpath.  It is currently not passing any scheme so throws exception

## Current Behavior
In version 4.2.0, when cucumber gets to this method:
```
    public Iterable<Resource> resources(URI path, String suffix) {
        if ("classpath".equals(path.getScheme())) {
            return this.classpath.resources(path, suffix);
        } else if ("file".equals(path.getScheme())) {
            return this.fs.resources(path, suffix);
        } else {
            throw new IllegalArgumentException("Unsupported scheme: " + path);
        }
    }
```
It would pass the arg "path" as "classpath: " followed by the classpath of the variable.

Now, when I evaluate this method, in version 4.2.3 it returns JUST the classpath of the feature file, but not the prefix "classpath: " so wrongly returns for "path.getScheme()" as C because the path = C:/......

## Steps to Reproduce (for bugs)
Run any test in windows

## Your Environment
* Version used: 4.2.3
* Operating System and version: Windows 10
* Link to your project: https://gitlab.developers.cam.ac.uk/jsa34/selenium-java-framework

**Comment by mpkorstanje** [comment]
Thanks for the clear reproducer!

Looks like we're missing a case in [FeaturePath.parse](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/io/cucumber/core/model/FeaturePath.java#L30).

For now you can work around this by using `file:C:/path/to/my.feature` or by using a relative path to your feature.

**Comment by jsa34** [comment]
Apologies - I didn't provide an example as all projects/features in Windows env appear to behave the same

**Comment by kwishna** [comment]
Seems, This Issue Is Only With v4.2.3. feature File Is Running Fine With v4.2.2.

**Comment by mpkorstanje** [comment]
That is quite possible. v4.2.1 introduced a fix that would ensure only valid paths to features were used. This allows us to properly error on non existing features, but it has been a tad too restrictive so far.

**Comment by jsa34** [comment]
Hello,

Thanks for the pointer.

I have checked:

Calling method FeatureFile.parse:
featureIdentifer arg is passed as: C:/path/to/file.feature
Line 31 returns false (nonStandardPathSeparatorInUse)
Line 36 returns true (probablyURI)
which calls method parseProbableURI, but this method returns no scheme

**Comment by jsa34** [comment]
I also checked - works fine v4.2.2 and below, only introduced in v4.2.3 - I think the regex is considering the windows file location passed as a valid URI at the point mentioned above.

**Comment by mpkorstanje** [comment]
Ah. Great. `file:path/to.feature` and `C:path/to.feature` don't have much to disambiguate. It's good windows file systems are still limited to a single character drive letters. May just check if the OS is Windows and if the path starts with a drive letter.

**Comment by jsa34** [comment]
Sounds like a good plan.

Just had a quick Google as it's something I'd never really thought about (drive naming in windows)

It appears that the officially supported drive naming system is single-letter, but it is technically possible to mount drives with other non-alphabetic chars (trusty wikipedia, so take with a pinch of salt!)

[Link](https://en.wikipedia.org/wiki/Drive_letter_assignment)

> If access to more filesystems than Z: is required under Windows NT, Volume Mount Points must be used.[11] However, it is possible to mount non-letter drives, such as 1:, 2:, or !: using the command line SUBST utility in Windows XP or later (i.e. SUBST 1: C:\TEMP), but it is not officially supported and may break programs that assume that all drives are letters A: to Z:.

**Comment by mpkorstanje** [comment]
Ideally windows paths are written using the non-standard path seperator `\`. So handling the most common case is good enough.

**Comment by mpkorstanje** [comment]
I do realize it is less then perfect. But it (try the file system if it's not on the classpath) was a broken systems to start with.

Eventuality `cucumber-jvm` should use `FileSystem` to work it all out but that does require URI inputs.

**Comment by jsa34** [comment]
I agree.  Sounds like a good approach with the logic it is using at the moment.

Were you thinking something like:

```
    public static URI parse(String featureIdentifier) {
        if (nonStandardPathSeparatorInUse(featureIdentifier)) {
            String standardized = replaceNonStandardPathSeparator(featureIdentifier);
            return parseAssumeFileScheme(standardized);
        }

        **if (isWindowsOS() && probablyWindowsWithStandardPathSeparatorInUse(featureIdentifier)) {
            return parseAssumeFileScheme(featureIdentifier);
        }**

        if (probablyURI(featureIdentifier)) {
            return parseProbableURI(featureIdentifier);
        }

        return parseAssumeFileScheme(featureIdentifier);
    }

    private static URI parseProbableURI(String featureIdentifier) {
        return URI.create(featureIdentifier);
    }

    private static boolean probablyURI(String featureIdentifier) {
        return featureIdentifier.matches("^\\w+:.*$");
    }

    **private static boolean isWindowsOS() { return System.getProperty("os.name").contains("Windows");}

    private static boolean probablyWindowsWithStandardPathSeparatorInUse(String featureIdentifier) {
        return featureIdentifier.matches("^(?:[a-zA-Z]:.*)$");
    }**

.....

```

**Comment by mpkorstanje** [comment]
That looks good in general. I do have some comments but I would rather address them in a PR. Are you able to create one?

If you have an alternative way to distinguish between paths and URIs, suggestions are welcome.

**Comment by jsa34** [comment]
Pull request raised - should really add some unit tests, which I will have to return to.

**Comment by jsa34** [comment]
Tests now added
