### ISSUE TITLE
How to run my cucumber/serenity feature file, providing command line options(login credentials) to the program ? 

### ISSUE THREAD

**Issue by PrasadNutalapati** [cucumber/cucumber-jvm#1570]
## Summary

My serenity project feature is working perfect, by running maven project by using
`mvn clean verify`

But our leadership is against keeping login credentials(userId, password) in the feature file or any external properties file. Only supplying them in the command line like
`mvn exec:java -Dexec.mainClass="com.module.test.Main" -Dexec.args="arg0 arg1 arg2" `
But in Serenity, there is no Main.java file with main() method. Then

**how do I invoke my serenity feature file to run using Maven with the provided 2 arguments ?**

Your suggestions are highly appreciated,
## Expected Behavior
Instead of providing login credentials in feature file, I needed to run the feature file from maven command line, providing userId and password. Not even an external properties file would be acceptable.

## Current Behavior
currently
`mvn clean verify
`
is running the project perfectly, producing reports and results.
```


```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by PrasadNutalapati** [comment]
Sorry, I would on the other forum.
