### ISSUE TITLE
Empty glue value in CucumberOptions behaves differently in various versions.

### ISSUE THREAD

**Issue by grasshopper7** [cucumber/cucumber-jvm#1571]
I have a runner in which the glue option is present but is empty. Below is the runner and the project structure.

```
@CucumberOptions(glue="", plugin = {"json:target/json-cucumber-reports/cukejson.json"} ,features="src/test/resources/feature/")
public class Default {
}
```
![untitled](https://user-images.githubusercontent.com/10829355/53699549-7df2b380-3e0f-11e9-8a85-9b8f4703a299.png)

4.1.1 - Works perfectly.
4.2.0 - Works perfectly.
4.2.1 - Steps are undefined.
4.2.2 - Works perfectly.
4.2.3 - Gives the following exception - java.lang.IllegalArgumentException: Expected scheme-specific part at index 10: classpath:
	at io.cucumber.core.model.GluePath.parseAssumeClasspathScheme(GluePath.java:64)
4.2.4 - Same error as above.

There is also a SO question regarding this - https://stackoverflow.com/questions/54971380/feature-file-executes-with-an-error-expected-scheme-specific-part-at-index-10

**Comment by mpkorstanje** [comment]
Nice find. Cheers! The root package is indeed a valid glue path and should be recognized as such. For now you can work around it by using `classpath:/`.

Though I would discourage the use of the root package. This will result in every dependency being scanned by Cucumber.

**Comment by mpkorstanje** [comment]
The SO issue seems to be somewhat related but rather then passing in the empty string it passes in `classpath:` which is not a valid URI. Older versions of Cucumber allowed it, the prefix was simply trimmed without any validation. I've added this case as a special exception to the glue parsing.
