### ISSUE TITLE
add ability to inject runtime parameters as tags

### ISSUE THREAD

**Issue by triesz** [cucumber/cucumber-jvm#1580]
## Summary
Adding capability to inject tags from runtime parameters.

## Expected Behavior
for example 
`mvn -q clean test -Dcucumber.options="--tags @acceptance" -Druntime.tags="@en;@desktop"`

would run all Scenarios with @acceptance tag and additionally would inject @en and @desktop in tags to the executed scenarios, in the generated .json report.

Benefit: https://plugins.jenkins.io/cucumber-reports plugin would create report aggregation for the injected @en and @desktop tags as well, out of the box.

## Current Behavior

I have not found currently supported way to inject additional tags runtime. Is there any way?

## Possible Solution
The approach suggected by @abcautomate ( or @aditya ? ) here worked fine:
https://www.youtube.com/watch?v=AuWzPpHbVfs

Is it OK for the community and the maintainers if I submit a PR with this approach or is there a better/nicer way to achieve this?

## Context & Motivation
We run cucumber tests in batches with various input parameters (I.e. screen width, language, system-under-test site...). The jenkins cucumber report publisher plugin has a great aggregation capability for @tags. 

If it was possible to inject tags from runtime parameters this would allow us to leverage on the jenkins cucumber plugin (out of the box) aggregation capabilities better.

**Comment by mpkorstanje** [comment]
I can see the need for and the use of a system that allows you to include information about the build into your reports. However the only merit of your suggested solution would be its expediency.

Using tags to include build information would merely use cucumber to pass data from the build system to a reporting system also ran by the build system. It would be technically much less involved to write the build meta data to file as part of the build process. This file could then be combined with the output generated by cucumber and picked up by your reporting tool.

I imagine you could do this by either post processing the output generated by cucumber or by providing a composition of cucumbers output and the build meta to a reporting tool.

So for example:

- run cucumber --> `report.json`
- report build info --> `build.json`
- post process `report.json` with `build.json` --> `report-with-extra-tags.json`
- run cucumber reports plugin on `report-with-extra-tags.json`

Or:

- run cucumber --> `report.json`
- report build info --> `build.json`
- run cucumber reports plugin on `report.json` and `build.json`

**Comment by mpkorstanje** [comment]
> I have not found currently supported way to inject additional tags runtime. Is there any way?
> The approach suggected by @abcautomate ( or @aditya ? ) here worked fine:
https://www.youtube.com/watch?v=AuWzPpHbVfs

Not in a way that is supported or could have any reasonable expectation of being able to function over time. Everything @abcautomate/@aditya is doing depends on internal API's.

If you are going to put any programming effort in to this I would urge you to post process cucumber json output instead. I believe Cucumber Reports project contains an object representation of the json structure that you should be able to borrow.
