### ISSUE TITLE
Regular Expressions Match Inconsistently 

### ISSUE THREAD

**Issue by SJrX** [cucumber/cucumber-jvm#1581]
## Summary

A valid regular expression fails to match with Cucumber JVM 4.2.6

## Expected Behavior

When a step definition has a regular expression using \d+ (more than one digit) and no anchors, it should match.

## Current Behavior

Crash

## Possible Solution

Not sure

## Steps to Reproduce (for bugs)

```
Feature: Feature

  Scenario: Anchors
    Given 0 anchors1
    Given 0 anchors2
    Given 0 anchors3
```
```
public class Steps {

    @Given("(\\d+) anchors1$")
    public void anchorsOne(Integer int1) {    }

    @Given("{int} anchors2")
    public void anchorsTwo(Integer int1) { }

    @Given("(\\d+) anchors3")
    public void anchors(Integer int1) { }
}
```

0 anchors1 (PASS)
0 anchors2 (PASS)
cucumber.runtime.CucumberException: Step [(\d+) anchors3] is defined with 1 parameters at 'foo.Steps.anchors(Integer) in file:/.../classes/'.
However, the gherkin step has 0 arguments.
Step text: 0 anchors3
    at cucumber.runner.PickleStepDefinitionMatch.arityMismatch(PickleStepDefinitionMatch.java:84)
    at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:36)
    at cucumber.runner.TestStep.executeStep(TestStep.java:63)
    at cucumber.runner.TestStep.run(TestStep.java:49)
    at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
    at cucumber.runner.TestCase.run(TestCase.java:45)
    at cucumber.runner.Runner.runPickle(Runner.java:40)
    at cucumber.runtime.Runtime$1.run(Runtime.java:82)
    at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:217)
    at cucumber.runtime.Runtime.run(Runtime.java:79)
    at cucumber.api.cli.Main.run(Main.java:26)
    at cucumber.api.cli.Main.main(Main.java:8)

## Context & Motivation

The lack of matches hurt me while upgrading from Cucumber 2.x to 4.2.6, I had to redo a number of regular expressions, by adding anchors.

## Your Environment

* Version used: 4.2.6
* Operating System and version: Linux, Arch.
* Link to your project: n/a

**Comment by SJrX** [comment]
I did notice that replacing \\d with [0-9] does work as expected. I spent ~5 minutes digging into the code, but did not notice or figure out what exactly the cause is, other than it doesn't seem to recognize the capture group as an argument.

**Comment by mpkorstanje** [comment]
With the introduction of cucumber expressions all regular expressions should start with `^` and end with `$`.  There is an exception build in when the symbols `[].*+` are used inside brackets, but I think we should remove that exception to allow for more consistent behavior.

https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/java/heuristics.adoc
https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/ExpressionFactory.java

**Comment by SJrX** [comment]
Yeah I think removing the exception makes a lot of sense as I had no clue about that feature and would never have guessed that was by design.
