### ISSUE TITLE
sharing spring context with plain junit tests

### ISSUE THREAD

**Issue by MarcHauptmann** [cucumber/cucumber-jvm#1583]
## Summary

A spring context is not shared between a junit test and cucumber. See #1582 for tests to reproduce this issue.

## Expected Behavior

It would be nice if cucumber was able to share the spring context with other tests.

## Current Behavior

Cucumber manages its own context cache(s) and does not share these. 

## Steps to Reproduce (for bugs)

Run the tests from the pull request mentioned above.

**Comment by mpkorstanje** [comment]
Excellent thanks! I agree. Unfortunately the way `cucumber-spring` is implemented make this impossible to do while also supporting parallel execution. The only way forward is to implement a new spring module that doesn't add step definitions to the spring context.

Have a look at https://github.com/cucumber/cucumber-jvm/issues/1470 for details.

**Comment by MarcHauptmann** [comment]
Ok, thanks for your answer! I will see what I can to do implement this feature.
