### ISSUE TITLE
Consider state sharing between background and scenarios via guice, picocontainer etc

### ISSUE THREAD

**Issue by fslev** [cucumber/cucumber-jvm#1584]
Hi,
I don't know if this breaks the cucumber Background or testing principles, but I think it is useful to have the possibility to access state which was set inside Background from a Cucumber Scenario.
Since Background runs before each scenario, in order to setup test data, I believe it is quite handy to access that data from a Scenario, via Guice, PicoContainer etc.

Suppose within a Background you insert some data inside a database, and inside each Scenario you directly play with the row ids that were generated within the Background section by calling Guice @Inject for example:

Background:
```
@Inject
TestData data;
public void generateData(){
  //do some SQL inserts
  //populate test data object with the generated ids
  data.getIds().put(id1,id2);
}
```

Scenario:
```
@Inject
TestData data;
public void playWithData(){
  for (int id: data.getIds()){
    //do something
  }
}
```

**Comment by mpkorstanje** [comment]
Background steps are syntactic sugar. So

```feature
Feature: Background

  Background:
    Given context
    And context

  Scenario: Do a thing
    Given precondtion
    When action
    Then result
  
```
is compiled down to

```feature
Feature: Background

  Background:

  Scenario: Do a thing
    Given context
    And context
    Given precondtion
    When action
    Then result
```

And so I am not sure what you are asking

**Comment by fslev** [comment]
I've updated the issue description with an example

**Comment by mpkorstanje** [comment]
I would expect so.

**Comment by fslev** [comment]
I've tried this once, in the past, and it didn't work. I used Cucumber 3.0.2 and didn't work.
I will try again and come back here

**Comment by mpkorstanje** [comment]
I'm guessing you forgot to add `@ScenarioScoped` to your step definition class then. Have a look at:

https://github.com/cucumber/cucumber-jvm/blob/master/guice/src/test/java/cucumber/runtime/java/guice/integration/ScenarioScopedSteps.java

**Comment by fslev** [comment]
No it's not that. I've made a small example and it worked now. Probably I did something wrong then.
My bad. I will close this as not an issue.
Thanks a lot for the quick response :)
