### ISSUE TITLE
Diffing a table with an empty list throws wrong error

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#159]
It currently fails with a `java.lang.IndexOutOfBoundsException` in `checkColumns(DataTable a, DataTable b)` where it compares dimensions. Instead it should fail with a `TableDiffException` showing all rows as missing.

Special care should be taken in the (unlikely) event that the table also has 0 rows. In that case the diff should not raise (empty==empty).

@cedric-lamalle assigning this to you to check if you're still interested in helping out. If not, just give me a nod.

**Comment by mlvandijk** [comment]
Is this issue still relevant? 
TableDifferTest contains a test comparing a table to an empty list and generating a TableDiffException:

@Test(expected = TableDiffException.class)
    public void should_diff_with_empty_list() {
        try {
            List<List<String>> other = new ArrayList<List<String>>();
            table().diff(other);
        } catch (TableDiffException e) {
            String expected = "" +
                    "Tables were not identical:\n" +
                    "    - | Aslak | aslak@email.com | 123 |\n" +
                    "    - | Joe   | joe@email.com   | 234 |\n" +
                    "    - | Bryan | bryan@email.org | 456 |\n" +
                    "    - | Ni    | ni@email.com    | 654 |\n";
            assertEquals(expected, e.getMessage());
            throw e;
        }
    }

Note: Parsing an empty source String (i.e.: TableParser.parse("", null);) does generate an IndexOutOfBoundsException.

**Comment by mpkorstanje** [comment]
Does it contain a test that takes the difference of an empty table and an empty list or table?

**Comment by mlvandijk** [comment]
@mpkorstanje It contains a test that diffs a non-empty table with an empty list (and throws the expected TableDiffException. 
I've added tests to verify empty DataTable throws same Exception, and diffing empty List with empty Table does not. Will create a PR containing those tests.

**Comment by mlvandijk** [comment]
@mpkorstanje Created the PR. If someone could have a look to see if 1. I understand correctly and/or 2. have not added unnecessary tests, we could hopefully get this issue closed :)

**Comment by mpkorstanje** [comment]
This issue had already been resolved at some undetermined time in the past. 

@mlvandijk thanks for investigating!
