### ISSUE TITLE
Cannot pass tag expression to maven-surefire-plugin

### ISSUE THREAD

**Issue by Mike-Now** [cucumber/cucumber-jvm#1596]
## Summary

The new multi-token expression syntax makes it impossible to declare multi token tag expression in the --tags flag inside the -Dcucumber.options flag in maven-surefire-plugin configuration.

## Expected Behavior

It should be possible possible to pass multi token tag expression in the -Dcucumber.options flag.

## Current Behavior

maven-surefire-plugin crashes throwing either VM crash, IllegalArgumentException or doesn't run any tests depending on the input.

## Possible Solution

Make it possible to make single token tag expression without any whitespace characters.

## Steps to Reproduce (for bugs)

1. Create a basic cucumber project using maven with maven-surefire-plugin
2. In the pom.xml define argLine tag inside maven-surefire-plugin configuration
3. Inside argLine tag add -Dcucumber.options=" --tags 'not @ignored'" or -Dcucumber.options=' --tags "not @ignored"'
4. run `mvn test`

## Context & Motivation

My use case is injecting tag expression from parent pom.

## Your Environment

* Version used: 3.0.2
* Operating System and version: Linux Mint 19

**Comment by mpkorstanje** [comment]
Try 
Try:
```
<argLine>-Dcucumber.options="--tags 'not @ignored'"</argLine>
```

**Comment by Mike-Now** [comment]
I entered that flag slopily in the description.
I have already tried your suggestion, but it doesn't work. If you don't believe me, I can make a minimal example project.

**Comment by mpkorstanje** [comment]
Please do. I copied that out of an existing project.

**Comment by Mike-Now** [comment]
Bad call - I cannot reproduce it in a minimal example. I must a have problem in a configuration then. 
Thank you very much.

**Comment by mpkorstanje** [comment]
Any chance you were using multiple tags?

**Comment by Mike-Now** [comment]
Just a negation.

**Comment by mpkorstanje** [comment]
You probably have to report this to surefire. The command line is valid.

**Comment by Mike-Now** [comment]
I made it work for maven-surefire-plugin:2.22.1 using verbatim command from the 2.12.4 version. If anybody wonders, here's the solution:

```<argLine>-Dcucumber.options="--tags '\''not @ignored'\''"```

**Comment by mpkorstanje** [comment]
Perhaps we should also consider making tags work without explict `@` symbols.

**Comment by mpkorstanje** [comment]
We can't disambiguate between `--tags not @it` and `--tags not @it path/to/features `. So that's already not possible.

**Comment by mpkorstanje** [comment]
@Mike-Now at version `2.22.2` and up this will work:

```
<argLine>-Dcucumber.options='--tags "not @ignored"'</argLine>
```

**Comment by mpkorstanje** [comment]
Looks like this fixed properly in [maven-shared-utils/33659](https://github.com/apache/maven-shared-utils/commit/336594396f2e9be8a572100e30a611f8123a837d) but hasn't made it into the latest Surefire yet. It will be a matter of patience.
