### ISSUE TITLE
Cucumber JVM formatter, thread safe?

### ISSUE THREAD

**Issue by VinnieM** [cucumber/cucumber-jvm#1597]
Cucumber-jvm version: 4.2.6

I am trying to do parallel execution of scenario using cucumber. As a tester I would like to add comments to my step definitions. I am doing this in the @AfterStep by using Scenario.write. I created a Singleton class called ReporterList (enum), which will has a SynchronizedConcurrent List. I am calling this function inside my stepDefinition using 

`ReporterList.INSTANCE.addValue("Launched the browser");`

And I have added the ReporterList inside @AfterStep

```
    @AfterStep
    public void afterStepTasks(Scenario scenario){
        ReporterList.INSTANCE.getStoredStepValue().forEach(scenario::write);
        ReporterList.INSTANCE.clear();
    }
```

But at the end, when the reports are generated, all the comments are jumbled up. So my question is, Are cucumber standard formatters thread safe?

Attaching my ReporterList class for reference.

```
public enum ReporterList {

  INSTANCE;
  private List<String> stepReporter;

  ReporterList() {
    stepReporter = Collections.synchronizedList(new ArrayList<>());
  }


  public synchronized void addValue(String message) {
    stepReporter.add(message);
  }

  public synchronized int size() {
    return stepReporter.size();
  }

  public synchronized List<String> getStoredStepValue() {
    return stepReporter;
  }

  public synchronized void clear() {
    stepReporter.clear();
  }
}
```

**Comment by mpkorstanje** [comment]
The formatters are thread-safe. Only one thread can submit an event at a time. Your code however is not threads safe.


Considered using the before step to store a reference to the scenario in a class variable and writing your report lines directly to the scenario.

Alternatively consider using a ThreadLocal in your instance.
