### ISSUE TITLE
Running feature file with multi line description

### ISSUE THREAD

**Issue by grasshopper7** [cucumber/cucumber-jvm#1605]
Was trying to see if a multi-line description (name) is possible for scenario or scenario outline. The complete multi-line description was not returned by scenario.getName() just the first part adjacent to **Scenario :** or **Scenario Outline :** . Neither any error is thrown that feature file format is incorrect.
Also tried with using the triple quotes used for multi-line within steps ('''').

Below is a sample of the feature file.
```
Feature: Scenario and Scenario Outline Combination

  Scenario: Scenario 11
    Extra Line

    And this is "FIRST" step
    And this is "SECOND" step

  Scenario: 
    """
    Extra Line
    Extra Line
    """

    And this is "FIRST" step
    And this is "SECOND" step

  Scenario Outline: Scenario Outline 11
    Extra Line
    Extra Line

    Given this is "<num>" step
    When this is "<num>" step

    Examples: 
      | num    |
      | FIRST  |
      | SECOND |
```

Not sure if multi-line description is possible or should a parsing error be thrown.
Running on windows.

**Comment by mpkorstanje** [comment]
This is allowed. 

According to the [Gherkin Syntax](https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin.berp) a scenario can have a small description between the title and its first step.

**Comment by grasshopper7** [comment]
Thanks... Got hold off the additional lines using getDescription() from ScenarioDefinition.
