### ISSUE TITLE
{Need Help}cucumber.api.transform not working in cucumber 4.2.0 

### ISSUE THREAD

**Issue by srinivasbudh** [cucumber/cucumber-jvm#1606]
**_cucumber.api.transform_**  is not available in cucumber 4.2.0 is there any  alternative of it.

I was using transformer in older versions like below, where  **TransformUserAccount** is a Transformer of **User account**

```
@When("^I signIn \"([^\"]*)\" user$")
    public void loginAsAUser((TransformUserAccount.class) UserAccount account) {

        loginPage.loginToAccount(account.getCredentials().getUsername(), account.getCredentials().getPassword());
    }
```
Is there a way to use it with cucumber 4.2.0

**Comment by grasshopper7** [comment]
U need to register a ParameterType in a class extending TypeRegistryConfigurer. Make sure the class is in the glue path. The logic from the old transformer class will now be in this new class. Refer to this for more details - https://docs.cucumber.io/cucumber/configuration/

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
