### ISSUE TITLE
Gradle + TestNG didn't find any tests to run

### ISSUE THREAD

**Issue by sirdir** [cucumber/cucumber-jvm#1610]
## Summary

Gradle+TestNG project didn't find any tests to run.

## Expected Behavior

Run all tests in specified cucumber runner

## Current Behavior

run `./gradlew test --tests com.CR`

where **com.CR**  path to class with @CucumberOptions

```
* What went wrong:
Execution failed for task ':test'.
> No tests found for given includes: [com.CR](--tests filter)
```

## Context & Motivation

Want to run cukes/scenarios in parallel using single jvm.
jUnit4 currently parallel test via processes instead of threads, thats why TestNG.

---

after each test run creates file **build/tmp/tests/jar_extract_SOMENUMBERS_tmp** and it contains hex-data

```
<=>testNGCucumberRunner*Lcucumber/api/testng/TestNGCucumberRunner;<init>()VCodeLineNumberTableLocalVariableTablethis1Lcucumber/api/testng/AbstractTestNGCucumberTests;
setUpClass
Exceptions?RuntimeVisibleAnnotations$Lorg/testng/annotations/BeforeClass;	alwaysRunrunScenarioW(Lcucumber/api/testng/PickleEventWrapper;Lcucumber/api/testng/CucumberFeatureWrapper;)V
pickleWrapper(Lcucumber/api/testng/PickleEventWrapper;featureWrapper,Lcucumber/api/testng/CucumberFeatureWrapper;@Lorg/testng/annotations/Test;groupscucumberdescriptionRuns Cucumber ScenariosdataProvider	scenarios()[[Ljava/lang/Object;
StackMapTable%Lorg/testng/annotations/DataProvider;
tearDownClass#Lorg/testng/annotations/AfterClass;
SourceFile AbstractTestNGCucumberTests.java(cucumber/api/testng/TestNGCucumberRunnerABC
DEFG[[Ljava/lang/Object;H+I/cucumber/api/testng/AbstractTestNGCucumberTestsjava/lang/Objectjava/lang/Exceptionjava/lang/ThrowablegetClass()Ljava/lang/Class;(Ljava/lang/Class;)V&cucumber/api/testng/PickleEventWrappergetPickleEvent()Lgherkin/events/PickleEvent;(Lgherkin/events/PickleEvent;)VprovideScenariosfinish!


```
I din't know how to debug cucumber as dependency library, ask on stackoverflow but still have no answer
https://stackoverflow.com/questions/55266485/how-to-debug-in-gradle-dependency-library-code

## Your Environment

repo: https://github.com/sirdir/cucumber-testng-gradle

* Version used:
io.cucumber:cucumber-java:4.3.0
io.cucumber:cucumber-testng:4.3.0

* OS
linux/mac

**Comment by mpkorstanje** [comment]
From the way you've described this, it doesn't appear to be a Cucumber problem. It sounds as if you'd have the same problem if you were using just TestNG without Cucumber. If you do think it is a Cucumber problem please provide an [MCVE](https://stackoverflow.com/help/mcve) in the form of a github repo and  feel free to reopen this issue.

**Comment by sirdir** [comment]
@mpkorstanje funny I'm attached MCVE repo in my general post. https://github.com/sirdir/cucumber-testng-gradle

**Comment by mpkorstanje** [comment]
Can you  show it's a Cucumber problem? It sounds as if you'd have the same problem if you were using just TestNG without Cucumber.

**Comment by tymur-kubai-exa** [comment]
Yeap it was gradle issue, you just need add in build.gradle test task additional setting.

```
test {
    useTestNG()
    scanForTestClasses = false //this one
}
``` 

I will try to contribute to your documentation.

----
P.S. and in mean time here wast explanations how to parallel scenarios in cucumber-gradle+tests
https://medium.com/@phddir/gradle-testng-and-paralleling-scenarios-in-cucumber-jvm-a826ac305ff2

**Comment by sirdir** [comment]
Yeap it was gradle issue, you just need add in build.gradle test task additional setting.

```
test {
    useTestNG()
    scanForTestClasses = false //this one
}
```
I will try to contribute to your documentation.

---

P.S. and in mean time here wast explanations how to parallel scenarios in cucumber-gradle+tests
https://medium.com/@phddir/gradle-testng-and-paralleling-scenarios-in-cucumber-jvm-a826ac305ff2

**Comment by mlvandijk** [comment]
@sirdir If you would like to add this information to the documentation, we would **very much appreciate it**! The best way to reach us, is on the [Cucumber Slack](https://cucumberbdd-slack-invite.herokuapp.com/). We discuss documentation in the `#docs` channel. Ping me if you need any help. :)
