### ISSUE TITLE
datatable-java: Empty cell are not converted to `null`'s for `String` class

### ISSUE THREAD

**Issue by gkalnytskyi** [cucumber/cucumber-jvm#1617]
## Summary
The empty cell is not converted to `(Double)null` in Cucumber 4.3.0, as it happened in Cucumber 1.2.5

In Cucumber 1.2.5 empty cell was converted to null of type `Double`, when performing `asMap(String,Double)` table conversion. This no longer happens in Cucumber 4.3.0. I also couldn't find the way to override this behavior because just adding new `DataTableType` definition results in `io.cucumber.datatable.DublicateTypeException`.

    typeRegistry.defineDataTableType(
        new DataTableType(
            Double.class,
            (TableCellTransformer<Double>) value ->
                (!value.isEmpty()) ? (Double.parseDouble(value)) : (null)));

## Expected Behavior
Empty cell is converted to `null` by default for nullable number types (`Double`, `Float`, `Int` etc.). So that the table in the following step 

    Then the marker values are
      | M1   | 1.7988 |
      | M2   |        |
      | M3   | 1.5312 |
      | M4   | 1.7720 |
      | M5   | 1.6840 |
      | M6   | 0.0000 |
      | M9   |        |
      | M12 | 1.7002 |

is transformed to

    {
        "M1": 1.7988,
        "M2": null,
        "M3": 1.5312,
        "M4": 1.7720,
        "M5": 1.6840,
        "M6": 0.0,
        "M9": null,
        "M12": 1.7002,
    }

## Current Behavior
Exception is thrown:
    io.cucumber.datatable.CucumberDataTableException: 'java.util.List<java.util.List<java.lang.Double>>' could not transform

## Possible Solution
Convert empty cells to null values, or allow to override default build-in type transformations.

## Steps to Reproduce (for bugs)

1. The table in the following step:

    Then the marker values are

      | M1   | 1.7988 |
      | M2   |        |
      | M3   | 1.5312 |
      | M4   | 1.7720 |
      | M5   | 1.6840 |
      | M6   | 0.0000 |
      | M9   |        |
      | M12 | 1.7002 |

2. Is trasformed to a `Map`

    @Then("Then the marker values are")
    public void theMarkerValuesAre(DataTable expectedValues) {
        Map<String, Double> expected = expectedValues.asMap(String.class, Double.class);
    }
3. `CucumberDataTableException` is thrown with message: _'java.util.List<java.util.List<java.lang.Double>>' could not transform_

## Context & Motivation
It could be useful to represent the clearing of the input value in the form where user can enter/update several similar values in one go.

## Your Environment

* Version used: 4.3.0
* Operating System and version: Windows 10
* Link to your project: N/A

**Comment by mpkorstanje** [comment]
This should be fixed with a PR against [cucumber/datatable](https://github.com/cucumber/cucumber/tree/master/datatable).

To remain consistent the empty string should always be converted to null (so also for strings) and doing this would be a breaking change. Meaning this would have to be picked up with v5.

**Comment by mpkorstanje** [comment]
For the the time being fixing this for all types but String would be good too.

**Comment by gkalnytskyi** [comment]
@mpkorstanje , sorry for asking, but where I can find some information about how to build datatable project in monorepo?
At the moment when I try to build the datatable-parent project I receive several errors of the following type: `package io.cucumber.datatable.dependency.com.fasterxml.jackson.databind does not exist`

**Comment by mpkorstanje** [comment]
Try running `mvn clean install` first. The dependency module is shading in some jars. IDEA doesn't pick that up automatically.

**Comment by gkalnytskyi** [comment]
Thanks! That was easy.

**Comment by mpkorstanje** [comment]
Data table version still needs to be updated.

**Comment by mpkorstanje** [comment]
And then we have to wait for 5.0.0 to make the empty String convert to null.

**Comment by hsynkrtl** [comment]
how can now passed an empty string to a datatable. Not null just "" empty?

**Comment by mpkorstanje** [comment]
@hsynkrtl you're replying to a closed issue which means that chances of anybody reading this are absolutely terrible. I happened to see this by sheer chance.

I would suggest that you make empty strings explicit by using the text `[empty]` and then prior to converting the entry to an object replace the `"[empty]"` strings with `""`.
