### ISSUE TITLE
Upgrade cucumber-expressions

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1621]
Upgrade Cucumber expressions to inclue: https://github.com/cucumber/cucumber/pull/604

**Comment by timtebeek** [comment]
Had a quick look; it appears Boolean handling ought to be available in 7.0.1, which has been released:
https://github.com/cucumber/cucumber/releases/tag/cucumber-expressions%2Fv7.0.1

But two weeks later is still does not seem to be available from Maven Central: https://mvnrepository.com/artifact/io.cucumber/cucumber-expressions

Any idea what might be causing the delay?

**Comment by mpkorstanje** [comment]
Looks like the build process failed and didn't push the tags to the mirror repos (e.g. `cucumber/tag-expressions-java`) that do the actual release.

I'd do another one but looks like the mono repo is currently broken. Looks like @aslakhellesoy is looking into it.
