### ISSUE TITLE
Please i need help with this issue that i am getting with my test being ignored for some reason

### ISSUE THREAD

**Issue by AbasSunday** [cucumber/cucumber-jvm#1624]
`<!--` 

Hi, Please see my runner class

`package runner;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import cucumber.api.testng.AbstractTestNGCucumberTests;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)

@CucumberOptions(
        features = {"features"},
        glue = {"steps.MainPageSteps"},
        plugin = { "pretty", "html:test-output", "json:target/cucumber-reports/report.json"},
        //tags={"@Scenario1"},
        monochrome = true,
        strict = false,
        dryRun = false)

public class TestRunner extends  AbstractTestNGCucumberTests {
}
<img width="264" alt="Structure" src="https://user-images.githubusercontent.com/24472150/57455653-86c69200-7263-11e9-8dd1-6f945dbed298.png">
`

You are about to create an issue - great!

Please read this first: you'll be more successful.

Before you do so, please consider the following:

 * Use the [support](https://cucumber.io/support) forums for questions 
   and discussions which are not related to bug reports or feature requests. 

 * Search for related issues and check the documentation before opening a 
   new issue. https://docs.cucumber.io/support

 * If your issue is related to other tools (Serenity, Selenium, etc.),
   please open an issue on the related tool. Only open an issue here once
   you have confirmed the issue is with Cucumber. 

  * If you are reporting a bug, please provide as much information as you 
    can to help us in solving your problem. 
    

Finally, the sections below are meant as guidance, to help you give the kind of 
information we'll need to help with your issue. Please try your best. 

If a section doesn't seem to fit, just delete it.

-->    
    
## Summary
Have created a cucumber project with a feature file but for some reason the step definitions are not being run instead its `ignored`

## Current Behavior
cucumber.runtime.junit.UndefinedThrowable: The step "User visit pet insurance url" is undefined

```


```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
