### ISSUE TITLE
All features are run instead of none

### ISSUE THREAD

**Issue by tommywo** [cucumber/cucumber-jvm#1630]
## Summary

If rerun report is empty and specified by `cucumber.options` property ALL features are run instead of none.
That doesn't happen when rerun file is specified in `@CucumberOptions` annotation.

## Expected Behavior

None of features are run.

## Current Behavior

All features are run when empty rerun report file is provided via `cucumber.options` property.

## Possible Solution

 - Parse `cucumber.options` property in `cucumber.runtime.RuntimeOptionsFactory` before running `addDefaultFeaturePathIfNoFeaturePathIsSpecified(args, clazz);`

## Steps to Reproduce

1. Create empty rerun file
2. Create testng cucumber test class
2. Set `cucumber.options` to `@empty-rerun-file.txt`
3. Run cucumber testng class

**Comment by tommywo** [comment]
I've created a [workaround](https://github.com/cucumber/cucumber-jvm/compare/handle-empty-rerun-file-in-props) for this but i don't like the idea of parsing `cucumber.options` twice - so suggestions are welcomed.

**Comment by mpkorstanje** [comment]
I reckon that if you add an condition here to check if this parse method encountered a rerun file as argument you can get the behavior to match again.

https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/RuntimeOptions.java#L204
```
        if (!parsedFeaturePaths.isEmpty() || <did we use a rerun file?>) {
            featurePaths.clear();
            featurePaths.addAll(parsedFeaturePaths);
        }
```
