### ISSUE TITLE
StepDefinitionReporter fails to report Java8 Lambda StepDefinitions

### ISSUE THREAD

**Issue by timtebeek** [cucumber/cucumber-jvm#1633]
Ok so I feel silly asking about this here, but I can't workout why the `StepDefinitionReporter` isn't triggered anymore when I follow the steps to implement my plugin here:
https://blog.jdriven.com/2019/01/cucumber-jvm-plugin/

This is in a new project, using recent (4.2.0, 4.2.6, 4.3.1) versions of cucumber-jvm. Somehow the `@Override public void stepDefinition(StepDefinition stepDefinition) {}` isn't triggered, and I can't find out why. @mpkorstanje we've both seen this work before, any idea why?

The only noticeable difference between this new project and my previous attempts, is that this project uses the `cucumber.api.java8.Nl` together with `#language: nl`.

**Comment by mpkorstanje** [comment]
Does it work with annotation based step definitions?

**Comment by timtebeek** [comment]
Created a sample project here: https://github.com/timtebeek/cucumber-jvm-issues-1633
It appears as though `StepDefinitionReporter#stepDefinition(StepDefinition stepDefinition)` is only ever invoked for the Annotation based step; Language appears not to be a factor (luckily).

So any clue how as to I can have the `StepDefinitionReporter` invoked for Java lambda based step definitions? Or is there any other hook I can use to pick up on those being defined?

**Comment by mpkorstanje** [comment]
So Tim, how do you feel about contributing to open source? I'm afraid this will require a PR.
 :smile: 

Lamda step definitions are only registered when a step definition class is instantiated. This is done in  `JavaBackend.buildWorld`. However we trigger `Runner.reportStepDefinitions` way before that happens. So there you could invoke `Runner.buildWorld` before `glue.reportStepDefinitions`. Problem is that building the world can be a rather expensive operation (e.g. when used with Spring). 

I would prefer that whenever `Glue.addStepDefinition` is invoked we put an event on the bus and deprecate the `StepDefinitionReporter` interface all together. Plumbing wise it shouldn't be too difficult. The `Runner` is already instantiated with an instance of `EventBus` and it instantiates the `Glue` class itself.

**Comment by timtebeek** [comment]
@mpkorstanje Perfect, thanks for the detailed instructions; there's a first attempt in: https://github.com/cucumber/cucumber-jvm/pull/1634
If you agree with the changes there I can add tests if needed.

**Comment by mpkorstanje** [comment]
Looks good! Please continue. Does it work as expected with your test project?

**Comment by timtebeek** [comment]
Yes, confirmed to be working with: https://github.com/timtebeek/cucumber-jvm-issues-1633/pull/1/files
Which now prints: `2 Unused steps` and writes out: ```
{
  "SampleSteps.java:17": "this step is unused",
  "SampleSteps.maar()": "another unused step"
}
```
I'd even suggest to add this plugin to core if you don't mind, but I'll leave that up to you. Could be a nice sample of usage of these new events.

**Comment by mpkorstanje** [comment]
Let's consider that separately. I think the current json structure would give us problems in the future. I'd have to consider it more carefully.

**Comment by timtebeek** [comment]
Perfect; I'll just update the blogpost then for my own future reference. How best to proceed on the PR? Or should we discuss that in #1634 ?

**Comment by mpkorstanje** [comment]
I am going to call it a day. I'll have a look tomorrow.
