### ISSUE TITLE
Remove StepDefinitionReporter

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1635]
The `StepDefinitionReporter` interface was deprecated in #1634. It can be removed for version 5. 

This can be done of the `develop-v5` branch after #1634 is merged.

**Comment by timtebeek** [comment]
This has indeed been done; Since the ticket lists the develop-v5 branch as target, can we close this ticket?

**Comment by mpkorstanje** [comment]
I usually try to use the 

Fixes: #1634 syntax. That closes the issue automatically.

Anyway, cheers!
