### ISSUE TITLE
Spring annotation equality check prevents use of other annotations

### ISSUE THREAD

**Issue by dupirefr** [cucumber/cucumber-jvm#1637]
## Bug explanation

I'm getting a "CucumberException: Annotations differs on glue classes found" when running my Cucumber test. I understand this is due to a check preventing from using different Spring annotations on different classes.

But, here, I'm using an extra non-Spring annotation on a class that makes the annotations count differ from the other classes. This is merely a documentation annotation I intend to use to export documentation about my Cucumber sentences.

Wouldn't it be more correct that the annotations check only verifies Spring annotations?

## Environment

* Cucumber version used: 1.2.5
* Spring version used: 5.0.2
* Operating System and version: Windows 10 Pro

**Comment by mpkorstanje** [comment]
This was fixed way back in 3.0.0

https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md#300-2017-09-27---release-announcement

**Comment by dupirefr** [comment]
Hi @mpkorstanje ,

Thanks for the quick answer. We tried, unsuccessfully, to migrate to version 3 these last days, but had to revert the commits because of a bad merge. I'm sure we'll try again soon though and the problem will then be gone :-).
