### ISSUE TITLE
plugin vs formatt cucumber options

### ISSUE THREAD

**Issue by skAutomation12** [cucumber/cucumber-jvm#1638]
Hi, 

I see Format is deprecated and suggestive use is Plugin.
I wanted to generate cucumber Pretty (maven-cucumber-reporting) along with extent reports. Observed that one of those is getting overlapped or over ridden and I only see Extent reports as a result. 
`@CucumberOptions(
        strict = true,
        monochrome = true,
        features = "src/test/resources/FeatureFiles/",
        glue = "com.xx.ft.steps",
        tags = {
                "~@ignore", "@abc"
        },

        plugin = {
                "html:target/cucumber-reports/cucumber.html",
                "json:target/cucumber-reports/cucumber.json",
                "pretty:target/cucumber-reports/cucumber.txt",
                "com.vimalselvam.cucumber.listener.ExtentCucumberFormatter:"}
)`

Please suggest.

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
