### ISSUE TITLE
gherkin: Failed to parse UTF-8-BOM encoded feature-files. (cucumber-jvm)

### ISSUE THREAD

**Issue by Susirya** [cucumber/cucumber-jvm#1639]
## Summary

Getting 
```
Caused by: gherkin.ParserException$CompositeParserException: Parser errors:
(1:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '﻿<fist-line-of-the-feature-file>'
```
when trying to run cucumber-jvm tests after update to v.4.2.6(gherkin 5.1.0) (from 1.2.2(gherkin 2.12.2) :0 ) 
Some of feature files just failed to be parsed though they worked ok with old gherkin version.

As appeared the problem was in the file encoding - 'non-parse-able' feature-files was in _UTF-8-BOM_. Plus IDEA shows both _UTF-8_ and _UTF-8-BOM_ files as just _UTF-8_ which gives you false confidence that everything is ok. Used notepad++ to detect and fix encoding.
## Expected Behavior
Both  _UTF-8_ and _UTF-8-BOM_ feature-files are parsed normally.
## Current Behavior
Passing _UTF-8-BOM_ feature-files (either the single one or as a path containing such file) causing 
`gherkin.ParserException$CompositeParserException` on the first line of the feature-file. Editing the fist line (removing the whole line, commenting/uncommenting - doesn't help as not removing the BOM sequence at the beginning of the file)
## Possible Solution
a) Change gherkin parser so that BOM sequence was detected and skipped when parsing feature-files with _UTF-8-BOM_ encoding.
b) clearly state in Documentation that using _UTF-8-BOM_ is prohibited for feature-files
## Steps to Reproduce (for bugs)
See sample project [README.MD](https://github.com/Susirya/GherkinIssueSampleProj)
## Context & Motivation
While upgrading from the very old version of cucumber stumbled on parser failing on absolutely normal feature-file.

## Your Environment
* Version used: cucumber-jvm 4.2.6, gherkin 5.1.0
* Operating System and version: Windows 10/7, Ubuntu/Debian
* Link to your project: https://github.com/Susirya/GherkinIssueSampleProj

**Comment by mpkorstanje** [comment]
I'm moving this issue to `cucumber-jvm`. It's not practical to fix this in the Gherkin parser because we've already geared up for the next version of Gherkin.

To fix this you would have to manually check for a byte order marker in `FeatureParser`. This should be fairly trivial as the entire feature is read as a `String` before being passed onto the parser.

**Comment by grasshopper7** [comment]
@mpkorstanje This can be done by using the [BOMInputStream](https://commons.apache.org/proper/commons-io/javadocs/api-2.6/org/apache/commons/io/input/BOMInputStream.html#hasBOM()) from [commons.io jar](https://mvnrepository.com/artifact/commons-io/commons-io/2.6). 
 
Just added the BOMInputStream constructor to [readFile method of Encoding class](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/util/Encoding.java#L20) and it removed the BOM encoding if it exists in the feature file.

Is this a feasible solution?

**Comment by mpkorstanje** [comment]
Not really. As a test library/framework we can not use any external dependencies. Especially ones that might be used in the application under test. 

When different versions are used this may result in undefined behavior, making the outcome of the test unrepresentative for the behavior of the system under test.

**Comment by grasshopper7** [comment]
Fair enough. Changed approach to check if file starts with the mark and replace if present
