### ISSUE TITLE
Get Runner class inside cucumber event handler

### ISSUE THREAD

**Issue by vagraw** [cucumber/cucumber-jvm#1644]
## Summary

I need to define a custom annotations in cucumber runner class. I have a event handler class where i get a callback when a test case is finished/started etc.

The issue i am facing is i am not able to get the runner class inside the event handler class, and hence i am unable to read the custom annotations applied in the runner class.

Is there a way for that in cucumber.

Eg. in junit , i can get the custom annotation applied in the test class as : `public void testFinished(Description description) { description.getTestClass();}` from where i could read my annotation.

in testng, `itestContext.getTestClass().getRealClass();.`

Any help would be highly appreciated.

I need to read the annotations here,

```
private EventHandler<TestCaseFinished> caseFinishedEventHandler = new EventHandler<TestCaseFinished>() {
    @Override
    public void receive(TestCaseFinished event) {
     //Read annotations here...
    }
}; /*Or here*/ private EventHandler<TestRunFinished> runFinishedEventHandler = new EventHandler<TestRunFinished>() {
    @Override
    public void receive(TestRunFinished event) {

    }
};
```

## Expected Behavior

Event handler classes should return the runner class.

## Current Behavior

No method in event handler classes to return runner class.

```
```
## Possible Solution

Provide a method in event handler class that would return the runner class.

## Steps to Reproduce (for bugs)

1. Apply custom annotations in runner class.
2.Create an event handler class, and try to read the custom annotation applied to the runner class.

## Context & Motivation

Apply Custom annotation annotation in runner class.

Eg. My software will update the result of cucumber tests in HP ALM. User will use tags to define testId for each scenario, and provide one time ALM configurations in runner class (eg project, domain, username, password, testSetId etc). But currently i am unable to read the annotations from the runner class.

## Your Environment

* Version used: 4.3.1
* Operating System and version: Windows
* Link to your project:

**Comment by mpkorstanje** [comment]
It's not possible to do this. Cucumber can be run by multiple runners and as such it's been decoupled from the `Runner` class. 

> one time ALM configurations in runner class (eg project, domain, username, password, testSetId etc).

Consider using environment variables instead. Esp for the username/password. You don't want to check those into source control.

Finally please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
