### ISSUE TITLE
Run parallel features in cucumber using CLI

### ISSUE THREAD

**Issue by hemanth-dunzo** [cucumber/cucumber-jvm#1651]
If we provide --threads 2 then this runs the **scenarios** in parallel.

As an enhancement request, it would be better to give the user an option with run level = scenarios (which runs **scenarios** in parallel) or run level = features (which runs the **features** in parallel)

**Example of the enhancement request:**
-Dcucumber.options="--threads=3 runLevel=scenarios" will run the scenarios in parallel
-Dcucumber.options="--threads=3 runLevel=features" will run the features in parallel
-Dcucumber.options="--threads=3 runLevel=tags" will run the tags in parallel

**Comment by mpkorstanje** [comment]
What advantage would that provide? Scenarios should be independent.

**Comment by mlvandijk** [comment]
Note you can run scenarios in parallel with TestNG.
