### ISSUE TITLE
Support for '@tag1,@tag2' will be removed from the next release of Cucumber-JVM. Please use '@tag or @tag2' instead

### ISSUE THREAD

**Issue by mjm987mj** [cucumber/cucumber-jvm#1652]
## Summary

Hi i'm encountering some issues with cucumber-java 4.3.0. When I execute the following mvn command:

`mvn test -Dtest="runners.android.tablets.**", -Dcucumber.options="--tags @tag1,@tag2"`

it will give me the following warning:

> Found tags option '@tag1,@tag2'. Support for '@tag1,@tag2' will be removed from the next release of Cucumber-JVM. Please use '@tag or @tag2' instead

When I change the mvn commando to `mvn test -Dtest="runners.android.tablets.**", -Dcucumber.options="--tags @tag1 or @tag2"`

Then I get the following message

> java.lang.IllegalArgumentException: Not a file or directory:...

When I change cucumber.options to cucumerOptions like this:
`mvn test -Dtest="runners.android.tablets.**", -DcucumberOptions="--tags @tag1 or @tag2"`

Then it will run but it will execute all my scenarios and not just the ones tagged with @tag1 or @tag2.

## Expected Behavior

I would expect that the scenarios that have @tag1 or @tag2 will run. However this is not the case.

## Current Behavior
All scenarios are executed.

## Your Environment
`   <properties>
        <cucumber.version>4.3.0</cucumber.version>
        <brand/>
    </properties>
`

    <dependencies>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
            <scope>compile</scope>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.25</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>3.14.0</version>
        </dependency>
        
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>7.0.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>
        
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.typesafe</groupId>
            <artifactId>config</artifactId>
            <version>1.3.1</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>gherkin</artifactId>
            <version>5.1.0</version>
        </dependency>
    </dependencies>`

**Comment by mpkorstanje** [comment]
Depending on your version of surefire you may have to add some quotes and/or escape characters. have a look at: https://github.com/cucumber/cucumber-jvm/issues/1596

**Comment by mjm987mj** [comment]
thanks! I'll check it out

**Comment by mjm987mj** [comment]
@mpkorstanje Could yo maybe tell me what the difference is between cucumber.options and cucumberOptions in the mvn command. They do show different behavior.

Thanks

**Comment by mpkorstanje** [comment]
When used as environment parameter `cucumberOptions` would appear to be a typo and should have no effect what so ever.
