### ISSUE TITLE
Cucumber JVM 4.2.0

### ISSUE THREAD

**Issue by skAutomation12** [cucumber/cucumber-jvm#1653]
using Cucmber 4.2.0+TestNG 
Issue: `  CucumberTestRunner>AbstractTestNGCucumberTests.setUpClass:16 » IllegalArgument`

Runner class":

`
@CucumberOptions(
        dryRun = false,
        strict = true,
        monochrome = true,
        snippets = SnippetType.CAMELCASE,
        features = "src/test/resources/FeatureFiles/",
        glue = "classpath:com.test.ft.steps",
        tags = {
               " @IN , @OUT"
        },
        plugin = {
                "pretty",
                "com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:",
//                "json:target/cucumber.json",
                "html:target/cucumber-reports/cucumber-pretty.html"}
)

public class CucumberTestRunner extends AbstractTestNGCucumberTests {

    @BeforeClass
    public void setupTestNGCucumber() {
        SeleniumDriver.setUpDriver();
           }

    @AfterClass
    public void publishreport() {
        SeleniumDriver.tearDown();
    }`

used command to fire test: 
mvn surefire:test -Dtest=CucumberTestRunner -Dcucumber.options="--tags @IN , @OUT"

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
