### ISSUE TITLE
Improve Cucumber-jvm json formatter memory effectiveness.

### ISSUE THREAD

**Issue by cranphin** [cucumber/cucumber-jvm#1661]
## Summary

The Cucumber-jvm json formatter is not very memory effective.
It could probably be improved by not creating one giant String.

## Expected Behavior

No out of memory errors, even on big reports with the json formatter.

## Possible Solution

Currently the following line uses gson.toJson(featureMaps) to create a String containing the full json document. There is also a gson.toJson(Object, java.lang.Appendable), which writes to the given Appendable in parts. If the given Appendable goes directly to the file stream, it will save a lot of memory.

https://github.com/cucumber/cucumber-jvm/blob/ba57542aba8371f7dd2455ad98fdb77e6f9b48c4/core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java#L173

**Comment by mpkorstanje** [comment]
Cheers. Feel free to send a pull request!

**Comment by aslakhellesoy** [comment]
We're going to deprecate the JSON formatter in favour of a new message protocol:

* https://github.com/cucumber/cucumber/tree/master/cucumber-messages
* https://docs.google.com/document/d/12Y3Ut-SVSGdw9L_aW6NGQY9JaCcn3z0alY4d7kzOndU/edit#

We might build a tool that can consume the new message protocol and create a cucumber JSON file, but we'll encourage people to start using the new message protocol instead.

It's probably 6-12 months away before we see the protocol implemented in all Cucumbers, but I wouldn't recommend putting more work into the current JSON formatter at this point.

**Comment by mpkorstanje** [comment]
It's a simple high impact fix.

And until we have message protocol I wouldn't deprecated the json formatter.

**Comment by mpkorstanje** [comment]
@aslakhellesoy did you by any chance mean to reply to:

- https://github.com/cucumber/cucumber-jvm/pull/1657
- https://github.com/cucumber/cucumber/issues/633

**Comment by cranphin** [comment]
Hi!
The reason we want json is the cluecumber report plugin uses it (https://github.com/trivago/cluecumber-report-plugin), I don't see any signs that project is intending to switch to another format soon.
What is the best way to notify downstream projects of the json change? Is there an issue or page somewhere regarding the new format?

I'll see if I can do a pull request :)

**Comment by mpkorstanje** [comment]
I just made a PR. It was rather easy. But looks like the build is failing.

**Comment by schmidt-fu** [comment]
Hey, thanks for integrating this, I currently have some problems with memory usage of the JSON serialization.

It seems to me that the Travis build is broken because it is not possible to install Java 8.

Maybe this would help?
https://travis-ci.community/t/oracle-jdk-11-and-10-are-pre-installed-not-the-openjdk-builds/785/17

**Comment by mpkorstanje** [comment]
Thanks for looking into that!

Time to drop Java 8 as a runtime from the matrix I think.

**Comment by schmidt-fu** [comment]
You're welcome!

I am personally quite happy that Java 8 is still supported (and frequently run). Have you tried the workaround from the article (using `dist: trusty` in the .travis.yml file)? Would it make sense in your setup?

**Comment by mpkorstanje** [comment]
Not really. Eventually `trusty` will be phased out and we'd have to solve the same problem then.

Looks like `openjdk8` is still available though. So while upgrading the default runner to `openjdk11` we'll still have a version that validates against `openjdk8`.

**Comment by mpkorstanje** [comment]
Blech. `openjdk11` became rather strict about the java doc. Wouldn't mind upgrading but too much work right now so `openjdk8` it is.

**Comment by laxersaz** [comment]
Hello all, is there any official plan on the phasing out of the JSON reporter? It is important for the further development of Cluecumber.

**Comment by mpkorstanje** [comment]
There are no concrete plans yet. 

[Gherkin 6 introduces the `Rule` key word](https://github.com/cucumber/cucumber/pull/416) and this poses a challenge for the current Json formatter. The Json formatter provides a facsimile of the original feature file. This once rules are introduced this will facsimile will be harder to maintain. 

Unfortunately there is no pure Java implementation of Gherkin 6 yet. As a result Cucumber JVM support for the Rule keyword has been lagging behind and with it the need to introduce a new reporting system. 

So in line with https://github.com/cucumber/cucumber/issues/734 what I currently see as the most likely chain of events is that:

 1) We'll create a pure java version of Gherkin 6.
 2) Additionally I suspect we will introduce the message protocol formatter at the same time.
 3) We'll introduce Gherkin 6 in Cucumber JVM without breaking the the Json format.
 4) Eventually we'll deprecate the Json formatter

I would like to introduce #2 earlier but we'd then risk consumers of the message protocol being stuck on Gherkin 5 while we introduce Gherkin 6.

**Comment by laxersaz** [comment]
Thanks for the detailed explanation @mpkorstanje !

**Comment by aslakhellesoy** [comment]
There is a new JSON formatter that will work as a backwards compatibility layer when we remove the native JSON formatters from Cucumber

- https://github.com/cucumber/cucumber/tree/master/json-formatter
- https://github.com/cucumber/cucumber/releases/tag/json-formatter%2Fv1.0.0

**Comment by mpkorstanje** [comment]
I'm not sure if that will work for a migration. Ideally consumers go from json to message protoc.

**Comment by aslakhellesoy** [comment]
> I'm not sure if that will work for a migration. Ideally consumers go from json to message protoc.

Sorry, not sure what you mean.

The plan is that Cucumber v6 will use Gherkin 8, and the native JSON formatter will be removed. People who still need to produce a JSON report will have to:

- `--format protobuf:target/results.bin`
- `cat target/results.bin | json-formatter > target/results.json`

**Comment by mpkorstanje** [comment]
Wouldn't we have deprecate it first to follow https://github.com/cucumber/cucumber/issues/734?

**Comment by aslakhellesoy** [comment]
Yes, it should be deprecated before it's removed. Still need to figure out how Gherkin 8/cucumber messages can co-exist with Gherkin 5. They have the same groupId, but different packages, so I assume that can still work?

**Comment by mpkorstanje** [comment]
If they have different package it shouldn't be a problem. We could schedule some pairing time on Thursday and try to make it work?

**Comment by aslakhellesoy** [comment]
Yes sounds like a plan!

**Comment by mpkorstanje** [comment]
Cool. I cheated a little and extracted the facades so we have a skeleton to work from on Thursday - avoid the drudery. 

https://github.com/cucumber/cucumber-jvm/tree/prep-work-gherkin-8
