### ISSUE TITLE
Test Context which has Dependency Injection

### ISSUE THREAD

**Issue by idaamit** [cucumber/cucumber-jvm#1662]
Hi,
I created a small project when the text context is simple class:
```
public class TestContextImpl  {

    String sharedParam1;
    int sharedParam2;
}
public class StepImpl1 {
    private TestContextImpl testContext;

    public StepImpl1(TestContextImpl testContext) {
        this.testContext = testContext;
    }

```
The code works as expected.
I now want to change the test context to : 
```
public class TestContextImpl  {

    SampleService sharedParam1;
    int sharedParam2;
}
```
`SampleService `  is a bean in the production code.
How I make picocontainer inject the `SampleService `?

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
