### ISSUE TITLE
Do not try to instantiate an Enum

### ISSUE THREAD

**Issue by dankito** [cucumber/cucumber-jvm#1664]
I have a wrapper class around Selenium WebDriver with constructors like these:

```
        public SeleniumDriver() {
		this(new SeleniumDriverFactory().create());
	}

	public SeleniumDriver(DriverType driverType) {
		this(new SeleniumDriverFactory().create(driverType));
	}

	public SeleniumDriver(WebDriver driver) {
		super(driver);

		addShutdownHook();
	}
```

DriverType is an enum.

Cucumber / Picocontainer always tries to use the constructor with the enum, resulting in the following exception:

org.picocontainer.PicoCompositionException: Either the specified parameters do not match any of the following constructors: [private x.y.z.test.selenium.DriverType(java.lang.String,int)]; OR the constructors were not accessible for 'x.y.z.test.selenium.DriverType'

Is there any way to tell Cucumber / Picocontainer to use the parameterless constructor or could you adjust your code that either it takes one of the other constructors without an enum or takes the first value of the enum for injection?

**Comment by mpkorstanje** [comment]
I don't believe there is.

You may be able to achieved by implementing your own `ObjectFactory`. The implementation of `cucumber-pico` is not that complicated and should be easy to replicate.

Alternatively you could make all but the default constructor public and use static methods to instantiate objects that way.
