### ISSUE TITLE
Feature request: Parallelisation by feature rather than scenario

### ISSUE THREAD

**Issue by jsa34** [cucumber/cucumber-jvm#1669]
## Summary

Feature request:

Adding a mode for making tests run in parallel by feature level, rather than scenario.
Much akin to how Cucable works:
https://github.com/trivago/cucable-plugin#parallelizationmode

Parallelisation is only possible by scenario level.

## Context & Motivation

Some tests cannot be run in parallel and need to be run sequentially.  Enabling a scenario to not be split into individual runners would solve the problem.

**Comment by mpkorstanje** [comment]
Scenarios are supposed to be independent. Could you give me a real world example and explanation as to why it is not possible to make them independent?

Please note that I am looking for more then merely impractical or time consuming. There is a common anti pattern in which scenarios in a feature build upon each other. I suspect that this lies at the root of your request. I'd rather not spend any effort to facilitate bad test design.

**Comment by jsa34** [comment]
Some scenarios are not possible to happen at the same time due to the fact they interact with the same component, for example, and due to restrictions placed on the environment under test I don't have the luxury of having isolated users under which to conduct the test.  There is no way I can find that would allow the tests for the same feature to run in parallel without them affecting each other as they have to be conducted using the same test user, so impossible for these tests to run in parallel.
I understand from your comment that you consider this bad test design, and I consider this a restriction over which I have no control and boundaries within which I have to work in, so I will close the request and look to 3rd party solutions.
Apologies for the inconvenience.

**Comment by mpkorstanje** [comment]
No worries.

Your situation is unenviable. However I am of opinion that the burden of these constraints and their associated (technical) cost should fall within the system that creates them.

For your use case parallelizing on feature files is only a stop gap. There will come a time when features can not be executed in parallel.

So in the end you will end up with two test executions. One that runs serial scenarios in serial, and one that runs parallel scenarios in parallel.

**Comment by mpkorstanje** [comment]
That said coincidently the JUnit runner will execute features in parallel due to limitations in the JUnit framework.

You may find that useful.
