### ISSUE TITLE
Not able to attach a screenshots in the report

### ISSUE THREAD

**Issue by pradeepuniq** [cucumber/cucumber-jvm#1671]
Hi
I am trying to write a text and attach a screenshot in the Extent Report

	@AfterStep
	public void screen() {
		 TakesScreenshot browser = (TakesScreenshot)driver;
         final byte[] screenshot = browser.getScreenshotAs(OutputType.BYTES);
         scenario.embed(screenshot, "image/png");
 		scenario.write("hieee--------------------");

	}

In the below version I was able to add text to the Report but nit able to add screenshot using the methods scenario.embed() and scenario.write()
		<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports-cucumber4-adapter</artifactId>
    <version>1.0.7</version>
</dependency>
In the below I was able to add screenshot but not the text
		<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports-cucumber4-adapter</artifactId>
    <version>1.0.5</version>
</dependency>

Please help me to add text and screenshot in the report

**Comment by mpkorstanje** [comment]
You should probably ask the creators of the `extentreports-cucumber4-adapter`.
