### ISSUE TITLE
[JVM] Link cucumber feature file with external CSV or JSON test data

### ISSUE THREAD

**Issue by shivam9ronaldo7** [cucumber/cucumber-jvm#1676]
Hello CukesTeam,

Currently I am facing issue not as in a coding issue but need any workaround or solution.

I am have a feature file with multiple of scenarios and all the scenarios are using nearly common test data. 
Now if I want to change test data in 3-4 scenarios I have to find that scenario and specifically change that value and do the same for other scenarios as well. 
So is there a way that I can have an external test data CSV or JSON where I can keep my test data and change the value in my test data sheet at while execution it will pick test data from that CSV or JSON.

Please refer below example as of my suggestion:

Expected Result:

/Register.feature

Feature: Test Registration page

  @reg@smoke
  Scenario: Successful registration with valid credentials
    Given user enter url "www.registerme.com"
    And user is successfully navigated to web-page
    When user clicks Register Me button
    Then user is navigated to registration page
    And user enters First Name as |First Name|
    And user enters Middle Name as |Middle Name|
    And user enters Last Name as |Last Name|
    And user clicks Register button
    Then "Registration Successful" message is displayed

  @reg
  Scenario: First name mandatory for registration
    Given user enter url "www.registerme.com"
    And user is successfully navigated to web-page
    When user clicks Register Me button
    Then user is navigated to registration page
    And user enters Middle Name as |Middle Name|
    And user enters Last Name as |Last Name|
    And user clicks Register button
    Then "First Name mandatory" error message is displayed

  @reg
  Scenario: Last name mandatory for registration
    Given user enter url "www.registerme.com"
    And user is successfully navigated to web-page
    When user clicks Register Me button
    Then user is navigated to registration page
    And user enters First Name as |First Name|
    And user enters Middle Name as |Middle Name|
    And user clicks Register button
    Then "Last Name mandatory" error message is displayed
	
/test-data.json
{
"First Name":"Shivam",
"Middle Name":"Pratap",
"Singh Name":"Singh",
}
	
Currently:	

/Register.feature

Feature: Test Registration page

  @reg@smoke
  Scenario: Successful registration with valid credentials
    Given user enter url "www.registerme.com"
    And user is successfully navigated to web-page
    When user clicks Register Me button
    Then user is navigated to registration page
    And user enters First Name as "Shivam"
	And user enters Middle Name as "Pratap"
	And user enters Last Name as "Singh"
	And user clicks Register button
	Then "Registration Successful" message is displayed

  @reg
  Scenario: First name mandatory for registration
    Given user enter url "www.registerme.com"
    And user is successfully navigated to web-page
    When user clicks Register Me button
    Then user is navigated to registration page
	And user enters Middle Name as "Pratap"
	And user enters Last Name as "Singh"
	And user clicks Register button
	Then "First Name mandatory" error message is displayed

  @reg
  Scenario: Last name mandatory for registration
    Given user enter url "www.registerme.com"
    And user is successfully navigated to web-page
    When user clicks Register Me button
    Then user is navigated to registration page
    And user enters First Name as "Shivam"
    And user enters Middle Name as "Pratap"
    And user clicks Register button
    Then "Last Name mandatory" error message is displayed

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
