### ISSUE TITLE
Cucumber Expressions not working with Scenario Outline

### ISSUE THREAD

**Issue by kathyrollo** [cucumber/cucumber-jvm#1678]
## Summary

Cucumber Expressions are not being passed as arguments when used with Scenario Outline with Examples table.

## Expected Behavior

Should work like regular expressions.
```
@When("^I Add Item To Cart: (.*)$")
public void I_Add_Item_To_Cart(String itemName) {
	// arg from regex is passed to method
}
```

## Current Behavior

**Feature:**
```
Scenario Outline: Cart Summary
	...
	When I Add Item To Cart: <name>
	...
	
	Examples:
		| name                  | color  | size | qty |
		| Printed Chiffon Dress | Yellow | S    | 1   |
```

**StepDef:**
```		
@When("I Add Item To Cart: {string}")
public void I_Add_Item_To_Cart(String itemName) {
	// arg from cucumber expression is not passed to method
}
```

**Output:**
Cucumber thinks stepdef is missing.
```
You can implement missing steps with the snippets below:

@When("I Add Item To Cart: Printed Chiffon Dress")
public void i_Add_Item_To_Cart_Printed_Chiffon_Dress() {
    // Write code here that turns the phrase above into concrete actions
    throw new cucumber.api.PendingException();
}
```
## Possible Solution

Workaround is to use regex instead for Scenario Outline.

## Context & Motivation

While regex is versatile, Cucumber Exp is closer to human-readable code.

## Your Environment

* Version used: 4.2.0
* Operating System and version: Win10 x64

**Comment by grasshopper7** [comment]
I think u need to use single or double quotes around the text in the scenario that u want to be captured by the string argument. Try this in the feature file - `When I Add Item To Cart: "<name>"`. https://cucumber.io/docs/cucumber/cucumber-expressions/#parameter-types - Check the "{string}" row for details.

**Comment by mpkorstanje** [comment]
@grasshopper7 is correct.

The pattern: `^I Add Item To Cart: (.*)$` is prone to over matching. It will consider anything after the colon an argument. In this case it is okay because the step has been structured in such a away to make that clear. However this isn't always the case.

Therefor it is recommended to quote your arguments. You can do this with the `"[^"]*"` pattern. The Cucumber Expression `{string}` does this automatically.

Aside from putting the qoutes around `<name>` you can also put them around the `Printed Chiffon Dress` e.g:

```
Scenario Outline: Cart Summary
	...
	When I Add Item To Cart: <name>
	...
	
	Examples:
		| name                  | color  | size | qty |
		| "Printed Chiffon Dress" | Yellow | S    | 1   |
```

**Comment by kathyrollo** [comment]
Putting quotes like `'<name>'` worked, thanks! 

Putting quotes in the Examples table values failed, as it is also taking the quotes as part of the value.
