### ISSUE TITLE
Broken link in JavaDoc for deprecated annotations

### ISSUE THREAD

**Issue by Riggs333** [cucumber/cucumber-jvm#1680]
## Summary

With release 4.5.0 the annotations `@Given`, `@When`, `@Then`, ... in the package `cucumber.api.java.en` are marked as `deprecated`. (Same applies to their counterparts for other languages.)
The **JavaDoc** says

> use {@link io.cucumber.java.api.en.Given} instead"

But the package `io.cucumber.java.api` does not exist in 4.5.0.

Nevertheless, the package `io.cucumber.api.en` does exist and even contains the relevant annotations.

## Possible Solution

Fix the JavaDoc in the template file `deprecated-annotation.java.gsp`:
https://github.com/cucumber/cucumber-jvm/blob/master/java/src/main/groovy/deprecated-annotation.java.gsp#L28

to
```java
 * @deprecated use {@link io.cucumber.api.${lang}.${kw}} instead.
```
## Your Environment

* Version used: 4.5.0

**Comment by mpkorstanje** [comment]
Thanks for pointing that one out.
