### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [cucumber/cucumber-jvm#1684]
Hi
The following lines have cryptographic API misuses. <br> File name => core/src/main/java/cucumber/runtime/model/FeatureBuilder.java: Line number => 37: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR> File name => core/src/main/java/cucumber/runtime/model/FeatureBuilder.java: Line number => 69: API name => MessageDigest:<BR> File name => core/src/main/java/cucumber/runtime/model/FeatureBuilder.java: Line number => 69: API name => MessageDigest:<BR>

**Comment by mpkorstanje** [comment]
https://github.com/cucumber/cucumber-jvm/commit/b6a58ea851bc6155f539c64fa0aab59837193a83

You'll have to upgrade your Cucumber.
