### ISSUE TITLE
Unable To Extend PicoFacory after upgrading to io.cucumber versions

### ISSUE THREAD

**Issue by Naumansh** [cucumber/cucumber-jvm#1686]
**Summary**
I have been working with info.cukes dependency versions of cucumber and pico-container. And the standard way of using PicoFactory to handle instantiation of webdriver classes was to extend PicoFactory in a customPicoFactory class and there on everything worked fine.

I recently decided to upgrade the project to io.cucumber versions. Also updated the pico conainer to 4.5.0 but after the update i am unable to extend the PicoFactory class. I wonder if there is anyother or modified way to handle this thing now.

**Project POM.XML**: 
```
cucumber.version = 4.4.0
picocontainer.version=4.4.0
<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.maven.surefire</groupId>
			<artifactId>surefire-junit4</artifactId>
			<version>3.0.0-M3</version>
		</dependency>
		<dependency>
			<groupId>com.trivago.rta</groupId>
			<artifactId>cucable-plugin</artifactId>
			<version>${cucable.version}</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<version>${picocontainer.version}</version>
			<scope>test</scope>
		</dependency>
```
**Extending class:**
```
public class CustomPicoFactory extends PicoFactory {
    public CustomPicoFactory() {
        if (System.getProperty("device") != null) {
            switch (System.getProperty("device").toLowerCase()) {
                case "firefox":
                    addClass(FireFoxManager.class);
                    break;
                case "chrome":
                    addClass(ChromeManager.class);
                    break;
} else {
            addClass(ChromeManager.class);
        }
    }
}
```
**Issue**: Unable to extend PicoFactory
Error: Cannot resolve symbol PicoFactory

**Comment by mpkorstanje** [comment]
`PIcoFactory` has moved from `cucumber.runtime.java.picocontainer` to `io.cucumber.picocontainer` and is now part of public API. Because it was not part of the public API you should not have relied upon it. 

A much less complicated way to achieve the same effect would have been to create a wrapper around your concrete device managers and use this wrapper in every step definition. Depending on the system property the `DynamicBrowserManger` will delegate to a different `BrowserManager`.  For example:

```java
public class DynamicBrowserManager implements BrowserManager {

    private final BrowserManager delegate;

    public DynamicBrowserManager() {
        if (System.getProperty("device") == null) {
            delegate = new ChromeManager();
        } else if ("firefox".equals(System.getProperty("device").toLowerCase())) {
            delegate = new FireFoxManager();
        } else {
            delegate = new ChromeManager();
        }
    }

    @Override
    public void doThing() {
        delegate.doThing();
    }
}


interface BrowserManager {

    void doThing();

}
```

Picofactory has recently been added to the public API and moved to `io.cucumber.pico`. If you are to use it this way you should prefer extension over inheritance (because the `PIcoFactory` is now final). 

```java
public class CustomPicoFactory implements ObjectFactory {

    private PicoFactory delegate = new PicoFactory();

    public CustomPicoFactory() {
        if (System.getProperty("device") != null) {
            switch (System.getProperty("device").toLowerCase()) {
                case "firefox":
                    addClass(FireFoxManager.class);
                    break;
                case "chrome":
                    addClass(ChromeManager.class);
                    break;
            } else{
                addClass(ChromeManager.class);
            }
        }
    }

    @Override
    public void start() {
        delegate.start();
    }

    @Override
    public void stop() {
        delegate.stop();
    }

    @Override
    public boolean addClass(Class<?> aClass) {
        return delegate.addClass(aClass);
    }

    @Override
    public <T> T getInstance(Class<T> aClass) {
        return delegate.getInstance(aClass);
    }
}
```

**Comment by Naumansh** [comment]
Thanks for the response.
**Updated version to 4.4.0**
**PicoFactory is not a final class here**

So the way i approached earlier was something like

interface Controller {
void getDriver();
// implemented in all DriverManagers. And passed in the constructor of the framework startup class
}

public class CustomPicoFactory extends PicoFactory {
    public CustomPicoFactory() {
        if (System.getProperty("device") != null) {
            switch (System.getProperty("device").toLowerCase()) {
                case "firefox":
                    addClass(FireFoxManager.class);
                    break;
                case "chrome":
                    addClass(ChromeManager.class);
                    break;
} else {
            addClass(ChromeManager.class);
        }
    }
}

**So the dots were connect successfully.** 
...........................................................................................
Now as far as your suggested solutions are i am facing below issues

1- 
public class CustomPicoFactory implements ObjectFactory {

    **private PicoFactory delegate = new PicoFactory();**

Unable to create Object of this class. Unable to import class.

2-
public class DynamicBrowserManager implements BrowserManager {

    private final BrowserManager delegate;

// I am not sure how is the instance reference gonna get added to the picofactory container with this approach. Also what do you exactly want to try in  BrowserManager interface with doThing() method. I tried it too but since the object reference for the drivermanager class doesnt get loaded to picofactory so its a null pointer.

**Comment by mpkorstanje** [comment]
> Unable to import class.

Try importing the class from `io.cucumber.java`. 

> I am not sure how is the instance reference gonna get added to the picofactory container with this approach

When `DynamicBrowserManager` is used as a constructor parameter in a step definition pico container will create an instance of it.

**Comment by Naumansh** [comment]
@mpkorstanje I am getting the below error with your suggested DynamicBrowserManager Approach

org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: automation.bots.Register has unsatisfied dependency 'interface automation.bots.controller.BrowserManager

I think its not able to fetch the instance from the implementing class.
Also in my older implementaion i was using a cucumber.properties file as below
cucumber.api.java.ObjectFactory=.automation.bots.controller.CustomPicoFactory

**Comment by mpkorstanje** [comment]
Change the constructor of `Register` to use `DynamicBrowserManager` instead of `BrowserManager`. 

Observe the `.` before `automation`.

```
cucumber.api.java.ObjectFactory=.automation.bots.controller.CustomPicoFactory
```

**Comment by Naumansh** [comment]
Got it.

Since the DynamicBrowser will initialized by the constructor, do i still need the cucumber.properties file with Objectfactory?

**Comment by Naumansh** [comment]
Thanks a lot man !!!!! It's working.

**Comment by mpkorstanje** [comment]
You're welcome.

> Since the DynamicBrowser will initialized by the constructor, do i still need the cucumber.properties file with Objectfactory?

Nope

**Comment by nikhilnicks** [comment]
Tried above mentioned solution. *Cucumber runner is not picking CustomPicoFactory*
I am not using DynamicBrowserManager at this moment because I am writing BDD for REST API's

```
public class CustomPicoFactory implements ObjectFactory {

    private PicoFactory delegate = new PicoFactory();

    public CustomPicoFactory() {
       addClass(SomeImplementation.class)
    }

    @Override
    public void start() {
        delegate.start();
    }

    @Override
    public void stop() {
        delegate.stop();
    }

    @Override
    public boolean addClass(Class<?> aClass) {
        return delegate.addClass(aClass);
    }

    @Override
    public <T> T getInstance(Class<T> aClass) {
        return delegate.getInstance(aClass);
    }
}
```
Even added entry of CustomPicoFactory to cucumber.properties
No error while running feature files
Logs
```
INFO: Loading ObjectFactory via service loader: io.cucumber.picocontainer.PicoFactory
```
Cucumber Version = 4.7.2

**Comment by hareharey** [comment]
@nikhilnicks Hey did you ever find a solution to your issue? What's needed to get Cucumber to recognize the CustomPicoFactory?

**Comment by mpkorstanje** [comment]
You have to use SPI. So don't forget to declare your implementation in the right files  in META-INF.


https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html
