### ISSUE TITLE
Migration from 4.3.1 to 4.5.2 lead to steps undefined

### ISSUE THREAD

**Issue by AlexPeshkov** [cucumber/cucumber-jvm#1688]
Dear Team

Migrated from io.cucumber 4.3.1 to 4.5.2 and replaced deprecated keywords @After/@Then etc and the steps became undefined:

**Was**
import cucumber.api.java.en.Then

@Then("^We use 4.3.1 version$")
public void test1() {}

**NOW**
import io.cucumber.java.en.Then

@Then("^We use 4.3.1 version$") -> became undefined/not clickable from .feature
public void test1() {}

Is there any new pattern of naming of steps?

Thank you for the help!

**Comment by mpkorstanje** [comment]
https://youtrack.jetbrains.com/issue/IDEA-217391

If you use idea. 

https://github.com/cucumber/cucumber-eclipse

If you use eclipe

**Comment by AlexPeshkov** [comment]
Thanks for sharing the know issue. So i have to roll back the version
