### ISSUE TITLE
Allow to name embeddings in JSON report

### ISSUE THREAD

**Issue by Dzieciak** [cucumber/cucumber-jvm#1692]
## Summary

Add "name" parameter to embeddings in JSON report. There was a similar issue #926, but it was closed.

## Expected Behavior

Scenario should have a method where name of the embedding can be passed as an argument

```void embed(byte[] data, String mimeType, String name);```

## Current Behavior

Currently there is no possibility to specify a name for the embedding. 

## Possible Solution

Add new method to Scenario interface where embedding name can be passed. Working solution can be found [here](https://github.com/Dzieciak/cucumber-jvm/commit/7e063c60225090fd7ff669cb45d88255f3a9c538). In #926 it was stated that this is a breaking change, but is it really?

## Context & Motivation

It would be useful for reporting libraries like [cucumber-reporting](https://github.com/damianszczepanik/cucumber-reporting). Currently, when you embed something in the report, e.g. HTML, everything is named Attachment. My particular use case is that I can have multiple REST calls in one step and I attach request and response details in the report. It looks like that:

![default-names](https://user-images.githubusercontent.com/8470504/61054966-cf7c0200-a3f0-11e9-8719-68b8148ceb89.png)

If embedding naming was enabled, I could have more meaningful names in the report, like called service methods names:

![custom-names](https://user-images.githubusercontent.com/8470504/61055103-0b16cc00-a3f1-11e9-9cab-714d7e81a893.png)

**Comment by mpkorstanje** [comment]
To rehash my comments from #1657 I think this is a good addition. While [the JSON formatter will be phased out](https://github.com/cucumber/cucumber-jvm/issues/1661#issuecomment-501259804) adding `Scenario.embed(byte[] data, String mimeType, String name)` would still be a useful addition. 

If you're willing and able to provide a PR please also update the `JSONFormatter` and `HTMLFormatter` to make use of this new functionality.

If you are going to provide a PR against the current `master` branch please also provide a PR against the `develop-v5` branch and bear in mind that you'll have to add this method to both `cucumber.api.Scenario` and `io.cucumber.core.api.Scenario`.

**Comment by Dzieciak** [comment]
I created a PR #1693 against `master`. If everything is OK, I will do the same for `develop-v5`

**Comment by Dzieciak** [comment]
Added a PR #1698  for `develop-v5` branch.

**Comment by beardedqa** [comment]
Pull request #1693 has been tested and merged. Thanks for that feature!
