### ISSUE TITLE
Test run count in cucumber log is giving Scenario+Test case count instead of Scenario count.

### ISSUE THREAD

**Issue by sravan-bade** [cucumber/cucumber-jvm#1696]
Test run count in cucumber log is giving Scenario+Test case count instead of Scenario count. I tried using junit-no-step-notification-option but of no use.

If Possible can some one give what should be updated to get proper count.

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
