### ISSUE TITLE
Step does not have a matching glue code error

### ISSUE THREAD

**Issue by vrbcntrl** [cucumber/cucumber-jvm#1699]
Hi,
I am pretty new to Cucumber-Java development. I have written a Scenario shown below along with a StepDef.java with matching glue code, however in my eclipse I see an error "Step does not have a matching glue code"

My BDD:

```
 Scenario: test scenario
    Given I have testResource defined
    When it contains listener
```
StepDef.java

```
@Given("^I have \"([^\"]*)\" defined$")
	public void i_have_resource_defined(String searchResourceType) throws Exception {
.......
}
```

Error message I see in eclipse: `Step 'I have testResource defined' does not have a matching glue code`

However, when I change the Scenario to Scenario Outline as shown below, the BDD works fine

```
Scenario Outline: test scenario
   Given I have "<resource>" defined
    When it contains "<property>"
    
    Examples:
    | resource                   | property        |
    | testResource             |  listener         |
```

I am not sure what I am missing here, and why my Scenario is not working and Scenario Outline works.

any help/input is greatly appreciated. Thanks!

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
