### ISSUE TITLE
Feature Request: Adding glueClass to CucumberOptions

### ISSUE THREAD

**Issue by daMupfel** [cucumber/cucumber-jvm#1707]
## Summary

I was wondering if the project would be open to add something like this:

```
  /**
   * @return class(es) to look for glue code (step definitions and hooks).
   *         Optional.
   */
  Class<?>[] glueClass() default {};
```

To the CucumberOptions (which now seem to be split by test framework).

## Context & Motivation

The use of actual classes allows the option for easier code refactoring (renaming the class containing the glue code will automatically also rename this since it is not a string).

We as well need a more fine granular configuration in our project on which classes should be loaded (we do have classes in the same package that should not be loaded together).

We currently have a custom runner based on an older cucumber version that implements this behavior for us.

**Comment by mpkorstanje** [comment]
Definitely! If you're willing and able to provide a PR I would be happy to accept it.

Please do take into account that development on Cucumber v4 will soon cease so we can get v5 out of the door so please provide a PR against `develop-v5` first before providing a PR against `master`.

**Comment by mpkorstanje** [comment]
@daMupfel Are you still interested in implementing this feature?

**Comment by daMupfel** [comment]
In principal yes. I don't have much time at the moment though. Since it is not a pressing issue for us at the moment i might come back later when we updated to cucumber 5 :wink:

**Comment by mpkorstanje** [comment]
No worries. I'll label this so every one who feels free to can pick this up.

**Comment by etSingh** [comment]
Hi @mpkorstanje, I would like to pick this up if you don't mind!

**Comment by mpkorstanje** [comment]
Btw. My earlier comments about `develop-v5` are no longer relevant. You can develop against `master`.

**Comment by etSingh** [comment]
Thanks will do!

**Comment by rasklaad** [comment]
I've started to implement this feature and I have a question.
Looks like I need to change `io.cucumber.core.backend.Backend`interface to something like this:
`void loadGlue(Glue glue, List<URI> gluePaths, List<Class<?>> glueClasses);`. Is it safe to do? Interface is marked as `Api.Stattus.STABLE`

**Comment by mpkorstanje** [comment]
That's not safe to do on a feature release but it is on a major. That said. How would this work when used from the CLI?

**Comment by rasklaad** [comment]
I was going to add new CLI argument `--glue-classes`. For example:
`--glue-classes io.cucumber.examples.java.RpnCalculatorSteps --glue-classes io.cucumber.examples.java.ParameterTypes`
If glueClasses is defined -> no default glue is picked, extraGlue or glue allowed

**Comment by mpkorstanje** [comment]
It feels like we're starting a primitive obsession and passing too many arguments to a single method. Perhaps we can introduce an class that lists the sources of glue explicitly.

We currently support:
  - packages
  - files kinda (for groovy)
  - classes

**Comment by rasklaad** [comment]
Could you provide example how do we support file uris and classes right now? I tried `--glue io.cucumber.examples.javaRpnCalculatorSteps` and it is not working.

**Comment by mpkorstanje** [comment]
We don't support classes yet but we would if were were to implement support for classes. 

The important bit is that `loadGlue` is getting too many arguments. I'd rather see something like:

```
loadGlue(Glue glue, GlueSelectors selectors)
```

Where you'd do `selectors.getSelectorsFor(PackageSelectors.class)` to get the package selectors.

**Comment by rozenshteyn** [comment]
I would like to try to implement this feature request, assuming it's still relevant.  I propose allowing to specify either packages or classes via the --glue command line arg (or its properties and env variable equivalents) and let the Backend logic figure out whether a URI is a package or a class and treat it accordingly.  I understand that some option parsing logic might need to be adjusted as well.  Would this approach be acceptable?

**Comment by mpkorstanje** [comment]
>  I propose allowing to specify either packages or classes via the --glue command line arg (or its properties and env variable equivalents) and let the Backend logic figure out whether a URI is a package or a class and treat it accordingly. 

I don't believe this can be done reliably. For example using `--glue com.example.NoSuchClass` should complain about the class not existing rather then assume it is a package.

**Comment by rozenshteyn** [comment]
I think the following should address your concern
For each glue URI:

1. Check whether the URI path is a class using [this method](https://cr.openjdk.java.net/~iris/se/11/latestSpec/api/java.base/java/lang/Class.html#forName(java.lang.String,boolean,java.lang.ClassLoader))
2. If check 1 fails, check whether the URI path is a package using [this method](https://cr.openjdk.java.net/~iris/se/11/latestSpec/api/java.base/java/lang/ClassLoader.html#getDefinedPackage(java.lang.String)).  If success, proceed to find all the classes with glue as per the current logic.
3. If both checks 1 and 2 fail, complain.

**Comment by mpkorstanje** [comment]
I'm not convinced. From what I can tell there is no guarantee that a package exists, even if a class in that package exists. That would be up to the exact implementation of the classloader.

**Comment by rozenshteyn** [comment]
Ok.  While I've never seen this happen, and I tried a few tests, maybe it could occur under some circumstances.  Currently, JavaBackend gets a List<URI> and assumes the URIs are those of packages.  My proposal is to modify the JavaBackend to not assume that and first check if the URI is a class and if not use the current logic to map the package URI to list of its classes.

**Comment by jenisys** [comment]
The normal procedure is somewhat like that:

* Clone the original repository in your workspace: git clone ...
* Create a new branch for your changes: `git checkout -b MY_BRANCH_1`  
  HINT: `MY_BRANCH_1` is an example for the desired branch name.
* Make the changes and commit them in your workspace
* Push the changes to your repository with your branch, like:
  `git push mine MY_BRANCH_1`
* Go to your repository on Github and create a pull-request

NOTES:

* Your pull-request should only contain the one thing your trying to solve (like: a bug to be fixed or an new feature/enhancement that was implemented).

**Comment by mpkorstanje** [comment]
> . My proposal is to modify the JavaBackend to not assume that and first check if the URI is a class and if not use the current logic to map the package URI to list of its classes.

So I'd rather see that we make it explicit what we are requesting the backend to look for, classes, packages, files, ect. This avoids the problem entirely.

I already outlined some thing here:

https://github.com/cucumber/cucumber-jvm/issues/1707#issuecomment-602711086

And it's not too different from JUnit 5s discovery request.

Doing this properly will be a breaking change but that's what major versions are for.

**Comment by mpkorstanje** [comment]
With JUnit 5 the `CucumberOptions` annotation for JUnit 4 becomes less important and I do not see a reason to provide support for tech that is on its way to obsoletion.

Additionally the refactoring needed to implement https://github.com/cucumber/cucumber-jvm/issues/1707#issuecomment-602711086 is considerable. The benefit however would be marginal.
