### ISSUE TITLE
No features found at classpath without trailing slash

### ISSUE THREAD

**Issue by MatheusHSA** [cucumber/cucumber-jvm#1708]
Hello! I'm trying to use Cucumber in a Scale project I'm working on, however Intellij does not recognize the .feature file. And when I try to run the tests I get the following error:

```
jul 19, 2019 3:52:43 PM cucumber.runtime.FeaturePathFeatureSupplier get
AVISO: No features found at classpath:src/test/functional/features

0 Scenarios
0 Steps
0m0,374s
```

Thanks in advance.

**Comment by mpkorstanje** [comment]
> The second one I got got by simply adding a / at the end of the file location.

That part is handled by core. Might be worth investigating.

**Comment by mpkorstanje** [comment]
Can't reproduce this at all.

**Comment by Azhagu-selenium** [comment]
> Hello! I'm trying to use Cucumber in a Scale project I'm working on, however Intellij does not recognize the .feature file. And when I try to run the tests I get the following error:
> 
> ```
> jul 19, 2019 3:52:43 PM cucumber.runtime.FeaturePathFeatureSupplier get
> AVISO: No features found at classpath:src/test/functional/features
> 
> 0 Scenarios
> 0 Steps
> 0m0,374s
> ```
> 
> Thanks in advance.

Hi,
Same issue am facing while execute the first script using cucmber BDD.
Please find the attachment for your reference . Can i get solution here?
![cucumber initial setup error](https://user-images.githubusercontent.com/54054096/73151183-0fd27180-40f0-11ea-9ade-600dabc53d03.JPG)

**Comment by mpkorstanje** [comment]
Your project looks odd. Try this project:
https://github.com/cucumber/cucumber-java-skeleton

And follow this tutorial first:
https://cucumber.io/docs/guides/10-minute-tutorial/

**Comment by Diego11914** [comment]
i have the same issue 
![imagen](https://github.com/cucumber/cucumber-jvm/assets/49316187/4192ea8c-3b19-4862-ad24-e9171cc72d73)

**Comment by mpkorstanje** [comment]
Do read all the warnings. You've got your imports mixed up.
