### ISSUE TITLE
Expression should provide access to parsed tree

### ISSUE THREAD

**Issue by laeubi** [cucumber/cucumber-jvm#1712]
This is related to [link](https://github.com/cucumber/cucumber-eclipse/issues/368)

Currently a Expression has only a "Expression.match(String, Type...)" that allows to match a concrete string with the Expression (e.g "I have {int} cookies in my belly").

The problem is for tools and IDEs that there is no way to tell what exactly is wrong, e.g. in the above expression if the user gives "I have no cookies in my belly", then the expression does not match and the IDE can simply not find anything.
What a user would expect is that the IDE offers the following two thing:

1. Tell that the first parameter must be an integer
2. Allow some kind of auto completion that print the whole string, jumps to the position of the first parameter and then let the user enter a value, jumps to the next parameter (if ther is any) and so on.

Internal the expression parser already builds a tree of parts and then generates a regular expression, but the parsing result is not exposed to the API.
It would be goo that at least an expressiontree is available that list constants and parameter positions with parameter types.

This would also allow cucumber itself to have more sophisticated hints about missing expressions.

**Comment by mpkorstanje** [comment]
Did you mean https://github.com/cucumber/cucumber-eclipse/issues/368? Plain numbers don't link across projects. But if you post the full link Github will shorten it.

**Comment by laeubi** [comment]
Yes, I have posted the full link, but it seems some github magic has removed it :-1:

**Comment by mpkorstanje** [comment]
I'm not keen to let an IDE look into everything. That will make it very hard to evolve Cucumber-JVM. Rather I'd provide all the information you need in some sort of platform agnostic format. e.g. JSON. So lets this just becomes more information points you need. Let's fold this back into #1711.

**Comment by laeubi** [comment]
IDE is just one usecase, as you cann see in #1386 there are other use cases as well where it would be usefull to have more information about the expression.

**Comment by mpkorstanje** [comment]
Perhaps, but lets discuss that in the context of #1386.
