### ISSUE TITLE
Use JUnit 5 internally

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1718]
While Cucumber does not support JUnit5 yet. We should at least use it internally.

 * [x] We can use `junit-vintage` to keep the `@RunWith(Cucumber.class)` annnotation working 
 * [x] We should replace all `ExpectedException` rules with `Assertions.assertThrows`.
 * [x] We should remove all other `@RunWith` and `@Rules` annotations.
 * [x] Use the right dependencies in the poms
 * [x] There is a test dependency not marked with scope test (fix it!).
 * [x] Get rid of AssertJ

**Comment by nhojpatrick** [comment]
@mpkorstanje I don't mind picking this up and leading it. I assume develop-v5 to branch from.

**Comment by mpkorstanje** [comment]
Please do! You can create pull requests directly against `master`. I've merged the `develop-v5` branch into master a few days ago.

**Comment by nhojpatrick** [comment]
Going to do them as quicker seperate branches building off each other so smaller and faster to get back into master. Everything that uses @Rule ExpectedException which converted quickly has been done.

**Comment by nhojpatrick** [comment]
I'm making multiple branches, each off the last pull request, to try and make each change easier to check. If you just want to check it all in one go, pick the highest pr number associated with 1718 and that will be the last one.

**Comment by mpkorstanje** [comment]
Cheers! I've merged yesterdays batch. Please beware that I'm squashing all commits to keep the commit history readable. You may have to rebase but you can resolve all conflicts using your version.

**Comment by nhojpatrick** [comment]
Only "@RunWith(Cucumber.class)" is left

**Comment by mpkorstanje** [comment]
Nice!
