### ISSUE TITLE
 Use lambdas for event handlers

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1719]
Internal `Plugin` implementations declare event handlers using anonymous inner classes. These are quite verbose and can be replaced with lambdas.

**Comment by Canarygo1** [comment]
do you refer to the plugins.java file?

**Comment by mpkorstanje** [comment]
Yes!

And also: 
 * JUnitFormatter.java
 * RerunFormatter.java
 * UsageFormatter.java
 * PrettyFormatter.java
 * ProgressFormatter.java
 * TimelineFormatter.java

Probably the quickest way to find them all is to check the callers of `EventPublisher.registerHandlerFor`.
