### ISSUE TITLE
issue when I upgrade to 4.5.0 (end synthesis)

### ISSUE THREAD

**Issue by sgrillon14** [cucumber/cucumber-jvm#1742]
## Summary

I want upgrade cucumber-jvm version from 4.4.0 to last version. in version 4.4.0, at the end of the run, the logs display this information:

```
22 Scenarios (13 failed, 9 passed)
1642 Steps (13 failed, 897 skipped, 732 passed)
5m41.703s
```
but since version 4.5.0, is no longer displayed.

## Expected Behavior

I want find this again at the end of execution:

```
22 Scenarios (13 failed, 9 passed)
1642 Steps (13 failed, 897 skipped, 732 passed)
5m41.703s
```

## Current Behavior

This information block, is no longer displayed at the end of the run since version 4.5.0

## Possible Solution

I see all commit between version 4.4.0 and 4.5.0 but I have not found

## Steps to Reproduce (for bugs)

1. upgrade cucumber-jvm version from 4.3.0 to 4.4.0 => OK
2. upgrade cucumber-jvm version from 4.4.0 to 4.5.0 => **KO**

## Context & Motivation

upgrade cucumber-jvm version from 4.4.0 to last version

## Your Environment

* Version used: 4.5.0
* Operating System and version: unix
* Link to your project: https://noraui.github.io/

**Comment by a1dutch** [comment]
Have you added the ‘summary’ plugin?

**Comment by sgrillon14** [comment]
@a1dutch, ‘summary’ plugin?

**Comment by a1dutch** [comment]
Yeah just add “summary” to the list, you will get the results at the end

**Comment by a1dutch** [comment]
Check out the release notes for 4.5.0 it was mentioned in there: https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md

**Comment by sgrillon14** [comment]
great, thank you
