### ISSUE TITLE
External typetools Automatic-Module-Name

### ISSUE THREAD

**Issue by nhojpatrick** [cucumber/cucumber-jvm#1750]
## Summary

I've raised a pull request for typetools to get Automatic-Module-Name 'net.jodah.typetools' into 0.6.2-SNAPSHOT.

For the already open issue: https://github.com/jhalterman/typetools/issues/54
For the pull request: https://github.com/jhalterman/typetools/pull/57

**Comment by mpkorstanje** [comment]
Resolved by 4d98e02b22e2a1293c7907309aa6740ed0030627
