### ISSUE TITLE
How to launch the mobile app inside Then keyword in Cucumber 

### ISSUE THREAD

**Issue by bradzy** [cucumber/cucumber-jvm#1752]
Hello,

I want to re-launch the mobile application in the step definition java file once a set of input parameters are executed in the data table in the cucumber feature file.

Framework Details:
Appium, Cucumber, TestNG, Java, Android

Scenario:
Validate Login credentials of mobile application(Username and Password) for multiple input parameters

Code:
I am using data table in cucumber feature file and listed out multiple input parameters.
But the logout feature for the mobile application is not implemented, so I have to clear the app cookies and close the app and re-launch the app for the next set of user name and password values of the data table.

Problem Statement:
How to relaunch the application in the "@When" section in stepdefinitions.java file, as the app launch is taken care in the appium connection java file.

Thanks in advance!

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.

**Comment by bradzy** [comment]
Hello @mpkorstanje, 

Could you please help me on this issue, If you're aware of this?.

Thanks a lot!
