### ISSUE TITLE
Rename java8 to lambda

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#1772]
Now that java13 is around the corner it's misleading to use java8. What's special about this module is that it uses lambdas. The JDK version that introduced lambdas is irrelevant.

**Comment by mpkorstanje** [comment]
I am considering holding this off a bit longer (so after v6 or even later).

Type detection in `cucumber-java8` depends on `typetools`. Type tools was introduced as a replacement for our own constant pool hacking. However it also uses the constant pool. Its just much better at it.

The constant pool is part of Javas internal API. This access will eventually be removed. There will be replacement APIs but it remains to be seen if `typetools` will be updated to use these.

Depending on how this plays out we will have to make a decision. Having a new module name may be an advantage we can use to make migration smooth.

 1. Access to the constant pool is removed. Type tools is updated (either by us, jhalterman or some one else). We can continue as planned.

2. Access to the constant pool is removed and type tools is not updated. We pin Cucumber Java8 to a specific JVM version, deprecate type dependent code paths and continue the module as Cucumber Lamda with reduced functionality.

This will allow for an extended period of migration. One that will be much needed. Automatic type conversion is a major productivity advantage but also hard to migrate out of.

Personally I would prefer option 1 but I would like to have the freedom to go with option 2. We may not be in a position to update type tools ourselves in the future.

**Comment by mpkorstanje** [comment]
References w.r.t future compatibility:

https://github.com/jhalterman/typetools/issues/34
https://github.com/jhalterman/typetools/issues/52

**Comment by mpkorstanje** [comment]
Superseded by: https://github.com/cucumber/cucumber-jvm/issues/2174
