### ISSUE TITLE
Attribute 'errors' must appear on element 'testsuite'

### ISSUE THREAD

**Issue by alexKazarin** [cucumber/cucumber-jvm#1777]
**Describe the bug**
I'm trying to configure Publish xUnit test result report in Jenkins and faced with problems of format differences.

**To Reproduce**
1. Use in pom
<argument>--plugin</argument>
<argument>junit:${project.build.directory}/cucumber-results.xml</argument>
(cucumber-core v.4.7.2 is used, so cucumber.runtime.formatter.JUnitFormatter is used in it)
2. Configure in Jenkins 'Post-build Action' step "Publish xUnit test result report" (xUnit plugin version 2.3.1) using generated xml: ./target/cucumber-results.xml
3. Run the build
4. In console log multiple warings occure

`WARNING: The file '.../target/cucumber-results.xml' is an invalid file.
WARNING: At line 2 of file: .../target/cucumber-results.xml:cvc-pattern-valid: Value '110.107047' is not facet-valid with respect to pattern '(([0-9]{0,3},)*[0-9]{3}|[0-9]{0,3})*(\.[0-9]{0,3})?' for type 'SUREFIRE_TIME'.
WARNING: At line 2 of file:.../target/cucumber-results.xml:cvc-attribute.3: The value '110.107047' of attribute 'time' on element 'testsuite' is not valid with respect to its type, 'SUREFIRE_TIME'.
WARNING: At line 2 of file:.../target/cucumber-results.xml:cvc-complex-type.4: Attribute 'errors' must appear on element 'testsuite'.
WARNING: The result file '.../target/cucumber-results.xml' for the metric 'JUnit' is not valid. The result file has been skipped.
INFO: Skipping tests recording.`

**Expected behavior**
No parce problems occure

**Context & Motivation**

Was trying to do an integration with Slack notification from Jenkins. Plugin could send to Slack from Jenkins list with names of failed tests. But to work correct, xml report needed. So step  "Publish xUnit test result report" is needed.

**Your Environment**
 - Jenkins xUnit plugin version 2.3.1
 - cucumber-core version 4.7.2

**Additional context**
Workaround could be done by using Custom tool with providing valid XSL template.

**Comment by mpkorstanje** [comment]
Thanks for pointing this out. Looks like we should use the [XSD used by Maven Surefiren](https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd).
