### ISSUE TITLE
User test findings

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1780]
- [X] When using Maven + JUnit + Non Strict no snippets are suggested when they should be #1790
- [X] Strict should default to true https://github.com/cucumber/cucumber-jvm/issues/1788
- [X] Multiple classes named TypeRegistry and Scenario is confusing https://github.com/cucumber/cucumber-jvm/pull/1781
- [x] The cucumber-glue scope does not appear to work as it used to in 3.0.0.

**Comment by aslakhellesoy** [comment]
All of this can be reproduced by upgrading https://github.com/cucumber-ltd/shouty.java

Other issues:
* Don't suggest snippets with `And` and `But` (use the previous GWT keyword)
* Don't generate annotations (java) and functions (java8) for `And` and `But`

**Comment by mpkorstanje** [comment]
> Don't generate annotations (java) and functions (java8) for And and But

This has been Cucumber since 2.0.0. We'll have to pull it through a deprecation process. 

https://github.com/cucumber/cucumber-jvm/blob/v2.0.0/java/pom.xml#L94

**Comment by mpkorstanje** [comment]
> Don't suggest snippets with And and But (use the previous GWT keyword)

Resolved by: https://github.com/cucumber/cucumber-jvm/pull/1783

**Comment by mpkorstanje** [comment]
> The cucumber-glue scope does not appear to work as it used to in 3.0.0.

@aslakhellesoy or @sebrose can you describe this issue a bit better? There is a unit test to confirm that beans annotated with `@Scope(CucumberTestContext.SCOPE_CUCUMBER_GLUE)` are not reused between scenarios.

https://github.com/cucumber/cucumber-jvm/blob/master/spring/src/test/java/io/cucumber/spring/SpringFactoryTest.java#L274

**Comment by mpkorstanje** [comment]
@aslakhellesoy I suggested to remove strict altogether in https://github.com/cucumber/cucumber/issues/714 wdyt? It will be easier to remove strict then it will be to flip it around.

**Comment by mpkorstanje** [comment]
> Don't generate annotations (java) and functions (java8) for And and But

Will be resolved by #1787
