### ISSUE TITLE
Retain line filter from scenarios in retry-file when setting runtimeOptions from EnvironmentOptionsParser(resourceLoader)

### ISSUE THREAD

**Issue by malte-smartbear** [cucumber/cucumber-jvm#1785]
**Problem description**
We are running multiple Jenkins (test) builds for different environments and use tags in cucumber.options to filter which tests to run e.g.
ENV1: mvn verify -Dcucumber.options=" 'not @excludeThis'"
ENV2: mvn verify -Dcucumber.options="@Smoke"
etc..

When running a full test suite any failed scenarios are recorded in a rerun file (e.g. "rerun:target/cucumber/rerun.txt"). Failed scenarios are then rerun at the end of the suite using a separate FailedTestRunner.class.

Up until Cucumber v4.2.0 the behaviour is that the line filter from failed scenarios is retained/passed in when runtimeOptions are set. This line filter is used in addition to the tag filter that was passed in when the build was kicked off.

Behaviour from Cucumber v4.2.1 onwards is that the original tag filter is retained during the rerun and the line filter is not set here: https://github.com/cucumber/cucumber-jvm/blob/37e20ae014db49dc59bc22a0035100cf21086fdf/testng/src/main/java/io/cucumber/testng/TestNGCucumberRunner.java#L59
...resulting in all scenarios in a feature file being retried instead of just the failed scenario(s). This means 2 things:
1. Additional scenarios are run unnecessarily.
2. Counts of total tests run changes all the time (a problem for reporting).

**Describe the solution you'd like**
Apply tag filtering (as per current behaviour) during the first test execution run, however when subsequently executing scenarios via rerun.txt file the line filter of each scenario is applied to the feature file (instead of tag filter that was originally passed in when kicking off the build - as per behaviour in v4.2.0).

**Describe alternatives you've considered**
Will need to figure out another effective way to filter out different scenarios for different environments (not using cucumber.options).

**Additional context**
Filters set in runtimeOptions during retry of failed scenarios:
<img width="931" alt="filters" src="https://user-images.githubusercontent.com/25171642/66033040-63e09700-e4fe-11e9-8e13-72d498cb9b6c.png">

Example project:
v4.7.2 branch: https://github.com/malte-smartbear/rerun-scenarios/tree/version4.7.2
v4.2.0 branch: https://github.com/malte-smartbear/rerun-scenarios/tree/version4.2.0

It looks like this commit may have changed the behaviour: https://github.com/cucumber/cucumber-jvm/commit/19cc359b05e2595498639fd132c12ead0e35b244#diff-d1e1ce02dbccd46003bc3a4a5c041a6cR56

```
RerunFilters rerunFilters = new RerunFilters(runtimeOptions, featureLoader);
filters = new Filters(runtimeOptions, rerunFilters);
```
was replaced with 
`filters = new Filters(runtimeOptions);`

...so **rerunFilters** is no longer included in **filters**.
Is it possible to bring back **rerunFilters**?

**Comment by mpkorstanje** [comment]
Again thanks for the sleuthing!

Looks like we don't quite do the configuration options inheritance right. Currently rerun files are treated as regular line filters. But they are in fact their own category and merging them into line filters was wrong.

Rule: Features over ride each other.

```
1. path/to/features
2. path/to/other/features
---
3. path/to/other/features
```
Rule: Features and filter combine 
```
1. path/to/features
2. --tags @someTag
---
3. --tags @someTag path/to/features
```
Rule: Filters replace filters

```
1. path/to/features:12
2. --tags @someTag
---
3. --tags @someTag path/to/features
```
```
1. path/to/features  --tags @someTag
2. path/to/features:12 
---
3. path/to/features:12
```

_this example fails because the line filters are dropped_
```
1. path/to/rerun --tags @someTag
2. --tags @someOtherTag
---
3. --tags @someOtherTag path/to/rerun
```

Rule: Rerun files replace features

```
1. path/to/features
2. path/to/rerun
---
3. path/to/rerun
```

Rule: Rerun file replaces filters

```
1. path/to/features:12
2. path/to/rerun
---
3. path/to/rerun
```

```
1. path/to/features --tags @someFeature
2. path/to/rerun
---
3. path/to/rerun
```

Rule: Features (with line filters) replace rerun

```
1. path/to/rerun
2. path/to/features:12
---
3. path/to/features:12
```

Rule: Rerun files and tags combine

```
1. path/to/rerun
2. --tags @someTag
---
3. --tags @someTag path/to/rerun
```

**Comment by mpkorstanje** [comment]
Fixed. There should be a `v4.7.4` out in a few hours. Cheers.

**Comment by malte-smartbear** [comment]
Verified in v4.7.4.
Thanks for addressing this!
