### ISSUE TITLE
Deprecate And and But keywords

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1787]
# Summary 

The `And` and `But` keywords are used as syntactic sugar in Gherkin. For example an `And` step precedented by a `Given` step is itself a `Given` step. As such there is no need for lambdas and annotations for `And` and `But`.

Allowing step definitions to be written with `And` and `But` might result in the creation of that do do not either arrange, act or assert something.

See: #1780

**Comment by aslakhellesoy** [comment]
My biggest issue with `And` in step definitions is that it carries an implicit and ambiguous coupling to another previous step definition. By removing it we avoid such confusion.

**Comment by mpkorstanje** [comment]
How would you avoid that coupling?

```feature
Given a user named Carl
And feature toggle X is enabled
When Carl does a thing
Then something happened
```

Being able to turn on a feature toggle implies the existence of some user.

It could be rewritten as:

```feature
Given feature toggle X is enabled for Carl
When Carl does a thing
Then something happened
```

And implicitly create a user named Carl, but that gets complicated quickly. It's easier to enable the feature toggle for whom ever is the current acting user.

**Comment by mpkorstanje** [comment]
I'm closing this. Technically it is possible to deprecate and eventually remove the keywords but I don't think it is worth the impact on existing projects. The suggested snippets already avoid the use of And and But so that should curb new usages.
