### ISSUE TITLE
Cucumber 4.7.3 Uses jquery 1.8.2 with a security vunerability

### ISSUE THREAD

**Issue by foxy82** [cucumber/cucumber-jvm#1791]
**Describe the bug**
Thanks for fixing: https://github.com/cucumber/cucumber-jvm/issues/1786

However the HTML formatter still uses jquery 1.8.2 which again has a high impact security vulnerability. 

https://github.com/cucumber/cucumber-jvm/blob/8e7957fb7d2995bcc155ca5a2db648924653468c/core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java#L59

Can this one also be updated?

Thanks

**Comment by aslakhellesoy** [comment]
Can you please send a pull request with a fix @foxy82?

Many thanks

**Comment by clarkead** [comment]
PR Submitted: https://github.com/cucumber/cucumber-jvm/pull/1794

**Comment by mpkorstanje** [comment]
Fixed by https://github.com/cucumber/cucumber-jvm/pull/1794
