### ISSUE TITLE
Parse error while using Example and Rule keyword 

### ISSUE THREAD

**Issue by tgoswami013** [cucumber/cucumber-jvm#1796]
Getting below error when I am using example and rule keyword in my feature file. 

`Caused by: gherkin.ParserException$CompositeParserException: Parser errors:
(40:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Rule: VAT is 20%'
(41:3): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Example: hello'`

Keywords Example and Rule are not showing in class public class GherkinDialect {}, although I am using all the latest dependencies.

**Comment by mpkorstanje** [comment]
Unfortunately rule keywords are not yet support in Cucumber JVM v4.x. They won't be supported in v5.0 either but a version of Gherkin to make that possible is in the works. Please keep an eye out for the release announcements on https://cucumber.io/blog/
