### ISSUE TITLE
Deprecate TypeRegistryConfigurer

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1797]
With the implementation of #1764 and #1677 done there is no need to support the `TypeRegistryConfigurer`. We should deprecate and eventually remove it.

**Comment by mlvandijk** [comment]
Should we deprecate in v5 so we can remove in v6?

**Comment by mpkorstanje** [comment]
Yes. I was planning to do this in in v5.x rather then v5.0 because it would make updating the documentation a bit easier but since we're working with release candidates now I think we can prepare the MR for v5.0 along with the release of v5.0.
