### ISSUE TITLE
Remove noisy output from build

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#1801]
Running `mvn clean test` from a clean checkout passes, but there is a lot of disturbing noise printed to the console:

* Stack traces. Disturbing because it's not clear whether these are swallowed errors or just debug information
* Logging (System.out.println). Disturbing because the information is not useful.

Let's delete all of this stuff.

**Comment by mpkorstanje** [comment]
I'd love to. But I don't think it will be that easy. Quite a few stack traces come from logging that informs the user something went wrong. And we have tests to assert that the system behaves properly when that happens. Thus creating the log information.

**Comment by mpkorstanje** [comment]
Some of the `System.out` spam could be reduced by refactoring the `RuntimeOptionsParser` to print to a `PrintStream` instead. But to do that effectively it that requires https://github.com/cucumber/cucumber-jvm/issues/1779 to be done so we decouple the `RuntimeOptionsParser` from everything but the CLI.

**Comment by mpkorstanje** [comment]
This will happen in due time.
