### ISSUE TITLE
io.cucumber.core.feature.GluePathTest failure

### ISSUE THREAD

**Issue by janosvitok** [cucumber/cucumber-jvm#1802]
`mvn install` on Windows produces:

```
[INFO] Running io.cucumber.core.feature.GluePathTest
[ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.025 s <<< FAILURE! - in io.cucumber.core.feature.GluePathTest
[ERROR] absolute_windows_path_form_is_not_valid  Time elapsed: 0.013 s  <<< FAILURE!
java.lang.AssertionError:
Unexpected exception message
Expected: is "The glue path must have a classpath scheme"
     but: was "The glue path must have a classpath scheme C:/com/example/app"
        at io.cucumber.core.feature.GluePathTest.absolute_windows_path_form_is_not_valid(GluePathTest.java:125)
```

https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/io/cucumber/core/feature/GluePath.java#L97 contains:

```
 throw new IllegalArgumentException("The glue path must have a classpath scheme " + uri);
```
while the test https://github.com/cucumber/cucumber-jvm/blob/master/core/src/test/java/io/cucumber/core/feature/GluePathTest.java#L125

```
 assertThat("Unexpected exception message", actualThrown.getMessage(), is(equalTo(
            "The glue path must have a classpath scheme"
        )));
```

Most probably the check should be 
`startsWith("The glue path must have a classpath scheme"`

**Your Environment**
 - Versions used : current master (12fab9b)
 - Operating System and version: Win 10 1903
 - Build tool: Apache Maven 3.6.2

I may provide PR if needed.

**Comment by mpkorstanje** [comment]
Cheers. Fixed by 5ae5cb54b3767c5c76f8b7cd62a73cdc38f2395e. Hope it works because I don't have a windows machine around. :laughing:

**Comment by janosvitok** [comment]
Yes, that helped.

BTW. have you considered appveyor for windows CI?

**Comment by mpkorstanje** [comment]
We'll move to docker builds on Circle-CI. I don't know if it's worth the effort  to add a windows image into the mix. For two platform specific tests I am happy to rely on the occasionall bug report.

**Comment by aslakhellesoy** [comment]
We've been using Appveyor for Cucumber-Ruby. It's fine, but it's more practical to use the same CI for everything. I'm looking into upgrading our CircleCI plan so we can have Windows builds (as well as more parallelism -> faster builds).
