### ISSUE TITLE
Add JavaDoc to all @API annotated classes

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1810]
JavaDoc is the most easilly available source of information for developers using Cucumber. Each class annotated with `@API` should have a brief explanation what the class is for and how it should be used.

**Comment by m-a-ge** [comment]
Can I work on this issue?

**Comment by mpkorstanje** [comment]
Definitly! Feel free!

**Comment by mlvandijk** [comment]
Looks like this is done
