### ISSUE TITLE
Access to ObjectFactory Before Runtime.run() is Called

### ISSUE THREAD

**Issue by mricken** [cucumber/cucumber-jvm#1813]
I would like to use Cucumber outside of unit tests, which means I'm invoking it programmatically, similar to what happens in `Main.run`.

I'm using PicoContainer and am creating my own custom `PicoFactory`. However, to give the steps access to the rest of the program, I need to have access to the `ObjectFactory` before invoking `Runtime.run()`.

How do I get access to the instance of the `ObjectFactory` that Cucumber uses?

Can you refactor the `Runtime` class so there is a `getObjectFactory()` method, or something like that?

**Comment by mpkorstanje** [comment]
Cucumber doesn't create a single instance of the `ObjectFactory`. They are created as needed -currently one per thread- while Cucumber is executing.

If you want to share an instance of an object between scenarios you'll have to wrap it and inject the wrapper into your step definitions using DI as normal. The wrapper can then maintain a singleton instance of that object. Note that you'll have to make sure this singleton is thread-safe if you want to run in parallel.

**Comment by mricken** [comment]
Thanks for your response. Do you have an example for how to do that with PicoContainer?

To be clear, I don't just want to re-use the same instance between two scenarios (or `StepDefinitions implements En` classes), I have a whole object that has been created by the application already, and I want to access it inside my `StepDefinitions` class.

**Comment by mpkorstanje** [comment]
Something like this. You could even leave out the getters/setters and access the static field directly. It's a bad example of how to use singletons all over but should get the point across. 

```java
public class Container {

    private static Application application;

    public Application getApplication() {
        return application;
    }

    public void setApplication(Application application) {
        this.application = application;
    }
}

public class Main {

    public static void main(String[] args){
        
        Application application = ;//create application
        Container container = new Container();
        container.setApplication(application);
        
        // run cucumber
    }

}

public class StepDefinitions {

    public StepDefinitions(Container container) {
        Application application = container.getApplication();
        // do stuff
    }
}
```

> To be clear, I don't just want to re-use the same instance between two scenarios (or StepDefinitions implements En classes), I have a whole object that has been created by the application already, and I want to access it inside my StepDefinitions class.

Unless you create the object you are interested in during the execution of a scenario you will have to share something between scenarios. Either a reference to your application or a reference the object you've created.

**Comment by mricken** [comment]
Thank you, that was super helpful!
