### ISSUE TITLE
Bug in cucumber json report :  Scenario Outline:1 tags are not updating with example tags

### ISSUE THREAD

**Issue by NLRKUM1** [cucumber/cucumber-jvm#1830]
**Scenario Outline:1 tags are not updating with example tags**
 Scenario Outline:1 Examples tags are not getting update with different tags in cucumber json report.

**To Reproduce**
```
 Scenario Outline:1 UnHappy path to test all the fields with Language EN and other fields
    Given call to "Get Agency rating" with parameters "AllParameter" "inCorrect"
    When  URL path is /XX/rating/agency-XX/<Path>
    Then  the status code should be "<ReturnCode>"
    And   I validate response content "<ResponsePath>" "<Response msg>"

    @TA-123
    Examples:
    |Path |ReturnCode|ResponsePath|Response msg|
    | SPR?language_code=EN| 500 | response..XX._code|EN|

    @TA-121
    Examples:
    |Path |ReturnCode|ResponsePath|Response msg|
    | 11261220/SPR?language_code=JA| 200 | response.data.XX.language_XX|EN|
```

**Expected behavior** 
  CucmberTestReport.json is having same tag everywhere for all scenario in the genertated jsonfile ie.@TA-123

**Context & Motivation**

How has this issue affected you? What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world.

**Screenshots**

**Your Environment**
 - Versions used [e.g 5.0.0]
 - Operating System and version [e.g. * Operating System and version:]
 - Build tool [e.g. Apache Maven 3.6.0]

**Additional context**

**Comment by mpkorstanje** [comment]
Would you be able to include which version and language of Cucumber you are using?

**Comment by mpkorstanje** [comment]
Can't reproduce this. Make sure you are on a recent version of Cucumber.
