### ISSUE TITLE
Make plugins available to use

### ISSUE THREAD

**Issue by Watster69** [cucumber/cucumber-jvm#1833]
I'm relatively new to this, it's more of a question than a bug or a feature.

I've created a gradle file which does a dry run and pulls out all of the scenarios which would run (based on tags etc) and writes this to a file which I then iterate through and can run these scenarios in parallel. Everything works absolutely fine but I'd like to tidy up the output. currently I use the pretty formatter which I think is great but it's rather verbose for what I need.

I have created a new formatter (based off of the pretty formatter) which also works fine but to do so I had to copy the existing pretty formatter and then make my edits and in doing so it cant import various classes so I also have to create them and then what should be simple task turns out to be multiple files of which already exists but are inaccessible.

Am I approaching this in the wrong way / is there a better way to do this?

For example the pretty formatter uses TestSourcesModel, NiceAppendable, Formats, AnsiFormats, Monochrome Formats but I cannot just import these and use them.

What I'm trying to achieve is the removal of all text highlighted in the red box because I don't feel it's nessecary information when I'm running all of the tests as a scenario.

![CucumberOutput](https://user-images.githubusercontent.com/35819753/70260914-3972ba80-1789-11ea-9881-837d351b8f3b.png)

Any help would be greatly appreciated.

**Comment by mpkorstanje** [comment]
> For example the pretty formatter uses TestSourcesModel, NiceAppendable, Formats, AnsiFormats, Monochrome Formats but I cannot just import these and use them.

There are several problems with the `core.plugin` package. I'll avoid enumerating them for now but safe to say that I hope to get rid of `TestSourcesModel` and `NiceAppendable` at some point in the future.

Additionally these classes were never designed for reuse and somewhat depend on implementation details. To ensure everything remains working across versions of Cucumber you may be better of copying the implementation. 

> is there a better way to do this?

Not yet. But we are removing the scenario outline from the pretty formatter as part of of the Gherkin v8 implementation. So the pretty formatter should do what you expect it to do out of the box.

> I've created a gradle file which does a dry run and pulls out all of the scenarios which would run (based on tags etc) and writes this to a file which I then iterate through and can run these scenarios in parallel. 

That seems awfully complicated. Cucumber has build in support for parallel execution for a while now. What prompted you to do this?

If you need more control the v5.0.0-RC2 implements the JUnit Platform API which allows you more control over discovery, filtering and selection.

You may also want to consider looking into the `gradle-cucumber-runner` plugin. It already supports parallel execution.

https://github.com/tsundberg/gradle-cucumber-runner

**Comment by Watster69** [comment]
Thanks for the update on the pretty formatter. I might as well wait until you guys have done the work to remove the scenario outline. It's not a major issue, I'm just a bit OCD on how I want things to look :)

> That seems awfully complicated. Cucumber has build in support for parallel execution for a while now. What prompted you to do this?

I wanted to be able to have the granularity of running the scenarios in parallel and as far as I'm aware you only support running features in parallel.

It's a fairly simple implementation...

- A basic formatter plugin which extracts the feature filepath and line number of the scenario being run to a file.
- Run the cucumber cli from the gradle plugin with the dry run parameter the new formatter.
- Using GParsPool, iterate through the list of scenarios and run the cucumber cli.

**Comment by mpkorstanje** [comment]
> I wanted to be able to have the granularity of running the scenarios in parallel and as far as I'm aware you only support running features in parallel.

- The CLI can execute scenarios in parallel. 
- The `gradle-cucumber-runner` can execute scenarios in parallel. 
- The TestNG runner can execute scenarios in parallel.

Only the JUnit runner when used with Maven Surefire can execute features in parallel. If used with Gradle it can't run anything in parallel at all.
