### ISSUE TITLE
[junit-platform-engine] ClassCastExceptions running Surefire while test succeeds in IntelliJ

### ISSUE THREAD

**Issue by nickstolwijk** [cucumber/cucumber-jvm#1837]
**Describe the bug**
I have a working test with a DefaultParameterTransformer (using Jackson). When I run this test in IntelliJ it succeeds. Although when running with Surefire, the test fails.

Output with Intellij:
```
Mapping '1.1.0' to 'java.lang.String'.
We wants a version: 1.1.0
Mapping '1.1.0' to 'nl.blue4it.stolwijk.sandbox.cucumber5.model.Version'.
We gets a version: Version{major=1, minor=1, patch=0}

1 Scenarios (1 passed)
2 Steps (2 passed)
0m0,513s
```

Output with Surefire:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running Version number check
Mapping '1.1.0' to 'java.lang.Object'.
We wants a version: 1.1.0
Mapping '1.1.0' to 'java.lang.Object'.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.422 s <<< FAILURE! - in Version number check
[ERROR] User wants to use 1.1.0 as version.  Time elapsed: 0.416 s  <<< ERROR!
java.lang.ClassCastException: class java.lang.String cannot be cast to class nl.blue4it.stolwijk.sandbox.cucumber5.model.Version (java.lang.String is in module java.base of loader 'bootstrap'; nl.blue4it.stolwijk.sandbox.cucumber5.model.Version is in unna
med module of loader 'app')
```
**To Reproduce**
1. Clone the repository at 'https://github.com/nickstolwijk/cucumber-platformengine-surefire-issue'
2. Run `mvn verify`
3. See the build fail.
4. Import into IDE.
5. Run feature
6. See the feature succeed

**Expected behavior**
The feature should succeed both in Surefire as in IntelliJ.

**Your Environment**
 - Cucumber version 5.0.0 RC2
 - Operating System and version: Windows 10
 - IntelliJ 2019.3
 - Build tool: Maven 3.6.3
 - Java: OpenJDK 11.0.2

**Comment by mpkorstanje** [comment]
Could you show me your scenario and step definitions?

**Comment by nickstolwijk** [comment]
Everything is in the mentioned GitHub repository.

**Comment by mpkorstanje** [comment]
Looks like you are you are running into: https://github.com/cucumber/cucumber-jvm/issues/1817


```
        Then("The user gets an {} version.", (Version version) -> {
            System.out.println("We gets a version: " + version);
        });
```

Java erases the parameter types of lambdas. So for the snippet above we use `type-tools` to fish that information out of the constant pool. This unfortunately type tools doesn't work on Java 12 yet. 

Unless you're interested in fixing `type-tools` your best option is to use annotation based stepdefinitions from `cucumber-java` or oddly enough Kotlin.

**Comment by nickstolwijk** [comment]
I'm sorry, this indeed is a duplicate. I had JDK 13 on my terminal. :-( 

Duplicate: #1817
