### ISSUE TITLE
How to run the same cucumber feature file more than once

### ISSUE THREAD

**Issue by Karthick3290** [cucumber/cucumber-jvm#1839]
**Describe the bug**
I need to run the same feature file multiple times by just mentioning the count somewhere in configuration. This feature file actually creates a record but the name is randomly generated.

**Your Environment**
Java
Cucumber

Please suggest us the ways to run the same feature file multiple times without changing anything except the number of times it should run.

**Comment by mpkorstanje** [comment]
It appears you are trying setup some test data. This doesn't fall within the scope of Cucumber.

You may want to consider re-factoring your step definition in such a way that you can also invoke them from another Java program and executed that program instead.

**Comment by mohanaraosv** [comment]
@Karthick3290 You are trying to do something which is out of feature file scope may be in another way can we do within feature file what you are trying to do. It would be nice to share the user story(scenario) here.
