### ISSUE TITLE
Examples should not have parent pom

### ISSUE THREAD

**Issue by josephks** [cucumber/cucumber-jvm#1853]
I am trying to get https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-calculator-junit5 to work.  If I clone this repo and run it it works fine, but if I try to copy and paste into my own pom it does not.

The problem is that that pom inherits from the example pom, which inherits from the cucumber-jvm pom, which inherits from the cucumber-parent pom.  Somewhere in there there is a plugin inclusion or setting that makes the example work but I can't tell what it is.  The example is not doing a good job of being an example.

After taking the parent out of the java-calculator-junit5 pom the features do not run.  I've been adding various things found in the parent poms to try to get it to work for a while now but so far I haven't hit upon the winning combination.

**Comment by mpkorstanje** [comment]
These examples are not intended to be skeleton projects people can use directly. The https://github.com/cucumber/cucumber-java-skeleton and https://github.com/cucumber/cucumber-archetype are used for this.

That said you don't have to setup much to get this to work. So I'm assuming you don't have a version of surefire/failsafe configured that supports the JUnit Platform. The pom below should work for the skeleton project. Note that you'll have to add the marker class (see the readme of the junit platform engine module).

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cucumber</groupId>
    <artifactId>cucumber-java-skeleton</artifactId>
    <version>0.0.1</version>
    <packaging>jar</packaging>
    <name>Cucumber-Java Skeleton</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
        <cucumber.version>5.0.0-RC4</cucumber.version>
        <maven.compiler.version>3.3</maven.compiler.version>
        <maven.surefire.version>2.22.1</maven.surefire.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.version}</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

```

**Comment by josephks** [comment]
I have the marker class.  The features run fine in IntelliJ, but I just can't figure out how to kick them off from the command line using maven.  cucumber-java-skeleton hasn't been updated for cucumber-junit-platform-engine

**Comment by josephks** [comment]
I'm trying to make a bigger point about the examples.  If they aren't self contained they don't make for good examples.

**Comment by mpkorstanje** [comment]
With the pom `mvn test` should do it. You got a github project to reference?

**Comment by josephks** [comment]
https://github.com/josephks/cucumber-demo
mvn test run the unit test.  mvn verify runs CLI-test but the feature is not actually run.  java-calculator-junit5 does the exact same thing if I take out the reference to the parent pom.

**Comment by mpkorstanje** [comment]
You should rename `RunCukes` to `RunCukesTest`. See http://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html and https://github.com/cucumber/cucumber-jvm/blob/master/junit-platform-engine/README.md

> the feature is not actually run. java-calculator-junit5 does the exact same thing if I take out the reference to the parent pom.

You would have seen these warnings:

```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.example:launch-from-cli:jar:1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 98, column 17
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-failsafe-plugin is missing. @ line 101, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

If you look up the versions provided by the parent pom (you can use `mvn help:effective-pom`) you'll see that you should use version 1.8 of the `maven-antrun-plugin`.

**Comment by josephks** [comment]
Upping the version of maven-antrun-plugin to 1.8 does indeed get the feature to run.  Thank you.  I still think the examples should be standalone.

**Comment by mpkorstanje** [comment]
As I mentioned before the docs, skeleton projects and Maven archetype are provided to cover that usecase.

Once the ecosystem advances to the point the JUnit Platform Engine is sufficiently supported we'll switch those over.

For the project itself we assume proficiency with Maven. The maintaince cost would be rather high otherwise. And since you are looking to be ahead of the curve that doesn't seem to be an unreasonable expectation.
