### ISSUE TITLE
BeanDefinitionOverrideException thrown when running scenarios in parallel with TestNG

### ISSUE THREAD

**Issue by Dzieciak** [cucumber/cucumber-jvm#1855]
**Describe the bug**
When running tests in parallel using Cucumber 5.0.0-RC4, TestNG and Spring Boot, the following exception is thrown by Spring:
`org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'io.cucumber.examples.spring.SimpleMathSteps' `

If scenarios are run in one thread, everything is OK. It seems to be caused by [#1848](https://github.com/cucumber/cucumber-jvm/pull/1848). This error does not occur on version 5.0.0-RC3.

**To Reproduce**
I prepared simple project to demonstrate this:
[cucumber-spring-boot-testng-example](https://github.com/Dzieciak/cucumber-spring-boot-testng-example)
You can run it with command:

`mvn clean verify -Pcucumber-test -Dcucumber.options="--tags '@Math'" -Dthread.count=N`
where N is the numberof threads

**Expected behavior**
Scenarios are run successfully, as when running with in one thread.

**Comment by mpkorstanje** [comment]
Great reproducer thanks!

Prior to #1848 each thread would have it's own  application context. Looks like all our test cases all allow bean overriding because we're testing against spring rather then spring boot.
