### ISSUE TITLE
Pass Scenario object to Step definitions by default?

### ISSUE THREAD

**Issue by gautham27** [cucumber/cucumber-jvm#1861]
Hi,

Is it possible to pass Scenario object to every step definition function by default? Just like it is passed to Hooks?

Example:

@Given("My given scenario")
public void given(Scenario scenario){}

Requirement/ Motivation:

If i have to build a custom logging and report for my BDD framework, during parallel execution i cannot confidently specify which scenario is executing current step definition function. So I feel this argument to every step will be of great help for distinguishing our tests.

**Comment by mpkorstanje** [comment]
This seems implausible. Hooks and steps in the same scenario are always invoked on the same thread. You should be able to use a `ThreadLocal` to keep track of the current scenario for that thread.

Nevertheless do consider using the `Plugin` API instead. It provides much more information and doesn't clutter up the glue code.

- https://grasshopper.tech/468/
- http://www.thinkcode.se/blog/2019/03/07/how-to-implement-a-cucumberjvm-plugin
