### ISSUE TITLE
Default glue to classpath root when no glue is defined

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1875]
A typical problem new users of Cucumber experience is that they've got everything configured but forget to setup the glue or configure it incorrectly. 

We can try to solve this problem by defaulting to the classpath root when no glue is defined. This way tutorials and explanations can simply skip the step to define the glue removing a possible avenue for errors.

**Comment by mpkorstanje** [comment]
And warn when the wrong @CucumberOptions is used?

**Comment by beardedqa** [comment]
I think it could be confusing if the classpath root won't be a proper glue. My assumption is that it's easier to spot missing glue than incorrect glue, especially for not experienced users.

I would suggest to just handle the error message that glue is not set up and what should it contain (path to the directory with files containing step definitions).

**Comment by mpkorstanje** [comment]
If we default to the classpath root then Cucumber will scan all packages and all available glue will be found. Could you give an example of what you mean by the classpath root not being a proper glue?

**Comment by beardedqa** [comment]
> If we default to the classpath root then Cucumber will scan all packages and all available glue will be found.
I was not aware of that. In that case, I love the idea.
