### ISSUE TITLE
Cucumber Junit reporter reports no failures (and no tests run) if initialization fails (e.g. using Spring fails to start a context)

### ISSUE THREAD

**Issue by dom54** [cucumber/cucumber-jvm#1879]
Summary

Not sure if this is related to core, junit or spring - but our maven build passes even when there is a failure starting the application context.  When we have a step annotated with "@WebAppConfiguration" and the application context is invalid, the tests are marked as ignored and appear in the junit report as "zero tests run" .

If the world fails to build, all the tests should be marked as failed.

Update:  I found a workaround, specifying <failIfNoTests>true</failIfNoTests>  in the surefire plugin.  Probably good enough.

Expected Behavior
Cucumber should mark all scenarios as failed

Current Behavior
Maven outputs:
[ERROR] Tests run: 0

and the build passes

Steps to Reproduce (for bugs)
WIP

Version used: Cucumber - 4.8.0, Junit - 4, Maven 3, Java 8
Operating System and version: Windows

**Comment by mpkorstanje** [comment]
Some of that was fixed in v5:

https://github.com/cucumber/cucumber-jvm/commit/0e41a1a40248adb2a5307857fe751813d99c9809

But you may also want to consider using `failIfNoTests` in surefire:

http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#failIfNoTests

**Comment by dom54** [comment]
Thanks - upgraded to V5 now
