### ISSUE TITLE
Fail Fast : that is as soon as a step in the scenario fails

### ISSUE THREAD

**Issue by ebundy** [cucumber/cucumber-jvm#1880]
I'm always frustrated when I have to guess where exactly a Cucumber test has failed.
Indeed, with some workarounds (hooks before() and after()) I can prevent other scenarios to execute after an initial failure in a scenario. But the problem is that inside the failing scenario, the test execution goes on, which in my cases produces noise. 
I would like to have a way to make it possible via a configuration.
Does it exist ?  
If that is not the case, does I have some fair alternative solutions or features that could solve my issue ?
If that is not the case and that the features makes sense, I can contribute.

Regards,
David

**Comment by mpkorstanje** [comment]
What have you tried? Cucumber integrates with JUnit and TestNG. I believe Maven provides fail fast options for both?

Have you tried these and if so, how were they not sufficient?

**Comment by ebundy** [comment]
In fact, I don't see what I could try. My point is preventing the next steps of the current scenario that fails but the executions of the steps inside a scenario looks to be managed by the cucumber test runner.

**Comment by mpkorstanje** [comment]
> Indeed, with some workarounds (hooks before() and after()) I can prevent other scenarios to execute after an initial failure in a scenario.

So this is what I assume Maven Surefire might cover. 

> But the problem is that inside the failing scenario, the test execution goes on, which in my cases produces noise.

This part I don't think I understand now. You can throw an exception from every step if you detect something is not as expected.

What do you mean by the test excution goes on.

**Comment by ebundy** [comment]
Hello,

I think that a real example would be clearer. I come back the next week with that.
