### ISSUE TITLE
Tags are not working with JUnit 5

### ISSUE THREAD

**Issue by pehguerra** [cucumber/cucumber-jvm#1890]
Hi all,

Cucumber tags are not being recognized with JUnit 5. I tried many things, but nothing worked. It doesn't show any error, but no tests are executed:

`@CucumberOptions(tags = "@addPlace and @deletePlace")`

**Result:**
0 Scenarios
0 Steps
0m0.003s

I followed all the instruction in Cucumber documention but it still not work.
I also downloded junit-vintage-engine but it's still not working.

I changed for JUnit 4.8.0 and tags were working properly. I also tried call test execution using Maven, but it also doesn't work.

`mvn test -Dcucumber.filter.tags="@addPlace and @deletePlace"`

**Result:**
0 Scenarios
0 Steps
0m0.002s

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.323 sec

Could anyone help please?

Thank you

**Comment by mpkorstanje** [comment]
You're not providing sufficient information for any one to help you. If you're looking to get your questions answered it may be worth reviewing [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example). Not only will this help other people answer your question, it usually also allows you to discover the problem by yourself.

That said, I strongly suspect you mean "@addPlace **or** @deletePlace".

And for future reference please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
