### ISSUE TITLE
Rename Scenario methods to be consistent with other Cucumber implementations

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1893]
https://github.com/cucumber/cucumber/issues/897

Apply the usual deprecation strategy before removing old methods.

**Comment by timtebeek** [comment]
@mpkorstanje first go in #1937 ; how far do we want to take this rename? Should we add an `AttachEvent` in parallel to `io.cucumber.plugin.event.EmbedEvent` ?

**Comment by timtebeek** [comment]
And if we do add an `AttachEvent`; should it replace both `EmbedEvent` and `WriteEvent` as somewhat alluded to in https://github.com/cucumber/cucumber/issues/897#issuecomment-588090766 ?

**Comment by mpkorstanje** [comment]
Only the `Scenario` objects should be sufficient. The goal of of this to harmonize the different implementations of Cucumber. 

The attach event is part of the Cucumber messages protocol. But I'm not sure how that will be exposed to Plugins yet.

https://github.com/cucumber/cucumber/tree/master/messages

**Comment by timtebeek** [comment]
@mpkorstanje since we're now targeting 6.0.0+ on master, should we by now clean up the old `Scenario.write(String)` & `Scenario.embed(byte[], String, String)` methods?

**Comment by mpkorstanje** [comment]
Didn't I do that already?

**Comment by timtebeek** [comment]
Yes you did! Missed that part.. Was just upgrading my projects when I came across the deprecated methods; figured I'd go and clean them up here but you already did in https://github.com/cucumber/cucumber-jvm/commit/89781436ac024a0e1a7001061f400258cc74330f
