### ISSUE TITLE
Unable to get Scenario step text at runtime

### ISSUE THREAD

**Issue by Phonesis** [cucumber/cucumber-jvm#1901]
I am trying to retrieve the Scenario step text at run time. This used to be possible in the Java implementation via reflection. See answer here: 

https://stackoverflow.com/questions/39664422/in-cucumber-is-it-possible-to-programmatically-get-the-current-step-being-execu

```
    Field f = scenario.getClass().getDeclaredField("testCase");
    f.setAccessible(true);
    TestCase r = (TestCase) f.get(scenario);

    //You need to filter out before/after hooks
    List<PickleStepTestStep> stepDefs = r.getTestSteps()
            .stream()
            .filter(x -> x instanceof PickleStepTestStep)
            .map(x -> (PickleStepTestStep) x)
            .collect(Collectors.toList());
```

However, with the more recent cucumber (from 4.8.0) this is no longer possible. I get the following error: 

java.lang.NoSuchFieldException: testCase

Is there any other means to obtain the step text? I can do it with Cucumber.js via the Scenario.pickle object

**Comment by Phonesis** [comment]
> Using reflection to reach into the bellows to use a non-public API is a surefire way to make upgrades difficult, because there is no guarantee that non-public APIs will remain unchanged.
> 
> This sounds like an [XY problem](http://xyproblem.info/) to me.
> 
> @Phonesis what kind of loggin/reporting are you doing that cannot be done with a plugin?

It's possible to achieve with Cucumber.js and I find it useful for basic logging in After Hooks. Using the plugin approach feels a bit like overkill for our purposes and would require a large rewrite in places. 

I just think if it's easily added then why not make it available in the Scenario object along with tags, name, etc

**Comment by aslakhellesoy** [comment]
Can you clarify what you mean by “Scenario step text”? Do you mean the text of e.g a Given step? Or do you mean the text of the scenario? A scenario typically has many steps. What exactly do you expect to access in an After hook (which runs once after all the steps have finished).

**Comment by Phonesis** [comment]
So for example, if we have the following scenario: 

```
    Given I navigate to the homepage
    When I select my account
    Then I can see the summary table
```

It would be great if we were able to obtain the text of the current step at runtime in the Hooks. For example,

```
    @AfterStep
    public void LogStepCompleted(Scenario scenario) {
        //get step text here perhaps in the scenario object as an array:
        scenario.getSteps()
       //or get current step
       scenario.getStep()
    }
```

**Comment by Naumansh** [comment]
I wonder why it is marked closed and why an open source is not giving access to the step information on runtime.

**Comment by Naumansh** [comment]
@Phonesis please try (PickleStepTestStep) event.getTestStep()).getStep().getText()

**Comment by mpkorstanje** [comment]
> I wonder why it is marked closed and why an open source is not giving access to the step information on runtime.

Reporting on test execution is a cross cutting concern that can be handled by using the plugin system rather then hooks. The plugin system also provides much more information then what is available in hooks.

And one of the challenges of developing software, open source or otherwise, is evolving the functionality. The larger the public API, the harder this becomes. Because this information is already available elsewhere in a system much better suited to the purpose of reporting on test execution there is no need to duplicate that functionality here.

If you do know a good use case - one that is not related to reporting - we can always reconsider.

**Comment by Phonesis** [comment]
Would it be possible to provide an example of how to get the step text / info via the plugin approach?

**Comment by mpkorstanje** [comment]
Something like:

```java
package com.example;

import io.cucumber.plugin.ConcurrentEventListener;
import io.cucumber.plugin.event.EventPublisher;
import io.cucumber.plugin.event.HookTestStep;
import io.cucumber.plugin.event.HookType;
import io.cucumber.plugin.event.PickleStepTestStep;
import io.cucumber.plugin.event.Result;
import io.cucumber.plugin.event.Status;
import io.cucumber.plugin.event.TestCase;
import io.cucumber.plugin.event.TestCaseFinished;
import io.cucumber.plugin.event.TestStep;

public class MyTestListener implements ConcurrentEventListener {
    @Override
    public void setEventPublisher(EventPublisher publisher) {
        publisher.registerHandlerFor(TestCaseFinished.class, this::handleTestCaseFinished);
    }

    private void handleTestCaseFinished(TestCaseFinished event) {
        TestCase testCase = event.getTestCase();
        Result result = event.getResult();
        Status status = result.getStatus();
        Throwable error = result.getError();
        String scenarioName = testCase.getName();

        TestStep testStep = testCase.getTestSteps().get(0);
        if (testStep instanceof PickleStepTestStep) {
            PickleStepTestStep pickleStepTestStep  = (PickleStepTestStep) testStep;
            String text = pickleStepTestStep.getStep().getText();
        }

        if (testStep instanceof HookTestStep) {
            HookTestStep hookTestStep = (HookTestStep) testStep;
            HookType hookType = hookTestStep.getHookType();
        }
        
        

        String id = "" + testCase.getUri() + testCase.getLine();
        System.out.println("Testcase " + id + " - " + status.name());
    }
}
```


When using JUnit 4 and TestNG you can activate this plugin using:

```java
@CucumberOptions(plugin="com.example.MyTestListener")
```

With JUnit 5 you add it to `junit-platform.properties`:

```properties
cucumber.plugin=com.example.MyTestListener 
```

Or if you are using the CLI

```bash
--plugin com.example.MyTestListener 
```

**Comment by vzenzo** [comment]
This would be great to have for reporting purposes. 
I have a script where failed step opens a JIRA ticket, I want to write in that ticket previous steps and how did I come to this failed step. All info that I get is through some workarounds.

This should be possible...I do not see any reason why you couldn't get info on current step, failed steps, execution of previous steps and skipped next tests. If reports can use that, I don't see why this isn't considered as a feature.

**Comment by mpkorstanje** [comment]
> The plugin solution does not work properly or at all.

Please open a new ticket to describe your problem.

**Comment by agolubev81** [comment]
Hi, it's really interesting discussion about enabling step information in hoosk API. 
I came to this page when I was looking for similar feature. 

Regarding plugins - can we use and rely on them for setting a kind of context before actual step is executed. For instance, I have a requirement to integrate tests with 3rdparty framework which is responsible for logging and error handling. Ideally all test-related information should be available to that integration code, which can be implemented as AOP btw, including text with test step. Will plugins allow to do that ? My concern is that plugins API is event-based, unlike hooks, and thus order of test start and end events might be not exactly "around" actual test execution, which is important for managing context.

**Comment by mpkorstanje** [comment]
It is not productive to discuss multiple disparate issues on a closed ticket. Please open a new issue and take the time to describe the problem you are trying solve and in which ways you think Cucumber is deficient in that.
