### ISSUE TITLE
Caused by: gherkin.parser.ParseError: Parse error. Found scenario_outline when expecting one of: comment, row, tag. (Current getState: examples)

### ISSUE THREAD

**Issue by pareaadi1987** [cucumber/cucumber-jvm#1906]
@config-cms-iwc-tests.yml @login

Feature: CMS IWC - Login Page

  @login-01
  Scenario Outline: Validate Login pop up.
    Given user navigate to iwc for <zone> in <language>
    When user clicks on Login link
    Then Login Popup should be displayed
    And Login popup heading should be displayed
  Examples:
 ## ${iwc-test.login}

  @login-02
  Scenario Outline:Validate Forgot Your Password Link
    Given user navigate to iwc for <zone> in <language>
    And user clicks on Login link
    #Then Login Popup should be displayed
    When user clicks on Forgot Your Password link
    Then Forgot Password popup should be displayed
    And Forgot Password popup heading should be displayed
    Examples:
 ## ${iwc-test.login}

**Comment by mpkorstanje** [comment]
```
  Examples:
 ## ${iwc-test.login}
```

I think you're missing some examples. Or you're not using Cucumber in which case you should seek assistance elsewhere.
