### ISSUE TITLE
Scenario no longer contains error?

### ISSUE THREAD

**Issue by Whiperdief** [cucumber/cucumber-jvm#1907]
Problem: after each scenario (@After hook) our framework marks the results on browserstack (failed/passed) using a REST call. We used the error field from Scenario to make following REST call .../sessions/{sessionId}.json?status=failed&reason={**reason**}

The results were this:

<img width="282" alt="Screenshot 2020-03-02 at 13 45 48" src="https://user-images.githubusercontent.com/9571065/75677646-415cd080-5c8c-11ea-8b78-1adb1a24dc1b.png">

Now the results are:

<img width="198" alt="image" src="https://user-images.githubusercontent.com/9571065/75677710-618c8f80-5c8c-11ea-8de2-3b466193a621.png">

We liked our flow and will like to keep it. So my first stop is here, is it possible to bring this feature back? Or can anyone point me in a direction of how to keep this behaviour using Cucumber? I know about the plugins cucumber package offers, but I don't see how they can benefit us in this situation. 

ps: sorry if this is not a feature. But it's not a bug either since this is intended behaviour (the removal of error in Scenario).

**Comment by mpkorstanje** [comment]
I'm having a rather hard time understanding what you are talking about? Do you have an example of the code that no longer works?

**Comment by Whiperdief** [comment]
Sure! This is more or less what happens ...

`@After
public void after(Scenario scenario){
...
markTestAsFailedInBrowserStack(getFailureReasonIfPossible(scenario))
...
}`

`
    private String getFailureReasonIfPossible(Scenario scenario) {
        try {
            Throwable cause = (Throwable) ReflectionTestUtils.invokeGetterMethod(scenario, "error");

            if (cause != null) {
                return Optional.of(cause).map(Throwable::getMessage).orElse(cause.getClass().getSimpleName());
            }
        } catch (RuntimeException e) {
            LOG.warn("Unable to get failure reason", e);
        }

        return "";
    }
`

**Comment by mpkorstanje** [comment]
```
ReflectionTestUtils.invokeGetterMethod(scenario, "error");
```

With this you are reaching into features that were not exposed and not part of the public API. This is essentially the same problem as: https://github.com/cucumber/cucumber-jvm/issues/1901

> I know about the plugins cucumber package offers, but I don't see how they can benefit us in this situation.

So essentially you'd use the plugin to mark the test case as failed in browser stack. Something like:

```java
    @Override
    public void setEventPublisher(EventPublisher publisher) {
        publisher.registerHandlerFor(TestCaseFinished.class, event -> {
            Result result = event.getResult();
            Throwable error = result.getError();
            if (error != null) {
                markTestAsFailedInBrowserStack(error);
            }
        });
    }
```

**Comment by Whiperdief** [comment]
Thank you. I will take this approach.
