### ISSUE TITLE
Redefine default processing for ParameterType and DocStringType

### ISSUE THREAD

**Issue by john-caleb-phillips** [cucumber/cucumber-jvm#1909]
In issue #1884 asked if it would be possible to allow redefinition of the default DataTableType of String -> String, so that replaceWithEmptyString could be defined.  

Would it be possible to also allow redefinition of the default ParameterType and DocString types for String?  I have a use case that is outside the bounds of what Cucumber is "supposed" to do, and to make it work I've had to do some highly questionable things with the Reflection API to unregister the default converters so I can define my own.

For reference, the odd use case is that my boss wanted to be able to pre-parse the inputs, so that if the parameter contains a specific pattern it can be converted to a value from a properties file.  The correct approach would have been to define a new object like "ConvertedString", and used that in the step definitions, but my boss rejected that as too complex.

**Comment by mpkorstanje** [comment]
Have you considered using a cucumber expression and/or custom docstring type?

```java
@ParameterType("some regex pattern")
public String interpolatedString(String string){
  return interpolate(string);
}

@Given("some {interpolatedString}")
public void some_interpolated_string(String interpolated){

}
```

```
Scenario: Example
  Given some "{interpolated string}"
```
```java
@DocStringType
public String interpolated(String docString){
  return interpolate(docString);
}
```

```
Scenario: Example
  Given some doc string
     """interpolated
      {interpolated string}
     """
```

**Comment by john-caleb-phillips** [comment]
Yes, this was suggested as well, but also rejected.  The boss wants the conversion to be invisible to the people who are writing the steps and features in our projects.

**Comment by mpkorstanje** [comment]
Unfortunately I don't see a good reason to support this. Cucumber is a tool to support BDD and assumes that all people involved are communicating and collaborating. It would be rather weird to hide behavior like this.

**Comment by john-caleb-phillips** [comment]
Fair enough.  I just figured I'd ask.
