### ISSUE TITLE
Error when passing empty table to step

### ISSUE THREAD

**Issue by john-caleb-phillips** [cucumber/cucumber-jvm#1912]
My project was recently upgraded to Cucumber 5 from Cucumber 4, and we are having a regression when attempting to pass an empty list to a step.

I have a step like the following:
<pre>
@Then("I see only the following buttons:")
public void validateButtons(List<String> buttonNames) {
    // Check for the buttons
}
</pre>
Importantly, this step throws an error if there are unexpected buttons.  So, we use it to both ensure the presence of expected buttons, and the invisibility of other buttons.  For example, we use it to make sure that there is not an "Edit" button for certain users, like so:
<pre>
Then I see only the following buttons:
  | Send Record for Approval | Validate Record |
</pre>
However, sometimes we need to validate that there are no buttons on the page.  To make that happen we would call the step like so:
<pre>
Then I see the following buttons:
  | 
</pre>
This would then pass an empty list to the step.  
After upgrading to Cucumber 5, scenarios that are passing the empty list are failing when attempting to initialize the runner class with the following error:
<pre>
RunnerClass.initializationError  Time elapsed: 0.012 s  <<< ERROR!
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
</pre>
I've checked through the code, and the issue appears to be that when the constructor of <b>GherkinVintageDataTableArgument</b> is called, it calls the <b>getLocation()</b> method from <b>PickleTable</b>, and this method just returns the <b>getLocation()</b> method from <b>PickleCell</b>.  Since there are no cells in this situation, the error is thrown.  

I recognize that passing an empty table to a step might not be something that you want to support.  But it was something that was allowed earlier, and I'd appreciate it if there is some way to allow it again.

**Comment by mpkorstanje** [comment]
As ugly as it looks, the parser accepts it so the feature file is valid. This will be fixed with #1913.
