### ISSUE TITLE
[Java] Switch useRegexpMatchAsStrongTypeHint default to false

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1915]
## Summary

Regular expressions providing strong type hints turn out to be rather annoying when mixing cucumber expressions and regular expressions. Especially when the patterns involved are short and common. See: https://github.com/cucumber/cucumber-jvm/pull/1914, https://github.com/cucumber/cucumber/pull/918

As such we should consider changing the default behaviour for type hints.

**Comment by s4ik4t** [comment]
Can I try this one pls?

**Comment by mpkorstanje** [comment]
Certainly, but the coding involved is changing a simple boolean in `ParameterType` and perhaps fixing a few tests. The actual work would be writing the release notes and explaining to people what has changed. 

If you're willing to do this you can find the code for the next major release on the `v6.x.x` branch. Release notes are kept in the [release-notes](https://github.com/cucumber/cucumber-jvm/tree/v6.x.x/release-notes). You can add a file there for v6.0.0. 

In the release notes it is important to describe:

1. What changed technically.
2. How will this affect a users test implementation (typically this would include one or two scenarios).
3. How can a user get the old behaviour back.

**Comment by s4ik4t** [comment]
Working on it, will try to close by this week. Thanks!

**Comment by mpkorstanje** [comment]
Cheers! And no worries. You are volunteering your time, there is no need to rush.
