### ISSUE TITLE
cucumber-jvm/examples/spring-txn isn't really run

### ISSUE THREAD

**Issue by christianhujer** [cucumber/cucumber-jvm#1916]
**Describe the bug**
cucumber-jvm/examples/spring-txn isn't really run. When you run `mvn package` or `mvn verify` there, the report is as follows:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```
This means that the tests aren't really run.
(Also, there is no output from Spring.)

**To Reproduce**
1. `git clone cucumber-jvm`
2. `cd cucumber-jvm/examples/spring-txn`
3. `mvn package`

If you like, modify `src/test/java/io/cucumber/examples/spring/txn/SeeMessagesStepDefinitions.java` and insert `org.junit.jupiter.api.Assertions.fail();` as the first statement in method `there_is_a_User()`.

**Expected behavior**
Tests are run.

**Context & Motivation**
I wanted to use test isolation via Spring transactions in a project and couldn't get it running, so I thought of checking the Cucumber example, and that's when I figured that the Cucumber example for how to do this actually isn't run.

**Screenshots**

**Your Environment**
 - Versions used: Cucumber 5.4.2
 - Operating System and version: Ubuntu 18.04.4 LTS
 - Build tool: Apache Maven 3.6.3

**Workaround (also possible solution)**
1. Point the Maven Surefire Plugin to version 3.0.0-M4
2. Add a dependency (to the normal bom, not the plugin) for org.junit.platform:junit-platform-commons:1.6.0
Now the tests are running as expected (and they pass).

**Comment by mpkorstanje** [comment]
Cheers!

**Comment by thinkingdyw** [comment]
@txn don't work

Environment
Versions used: Cucumber 5.6.0
springboot:1.2.3
Build tool: Apache Maven 3.6.3
junit :4.12
