### ISSUE TITLE
A question: Is there anyway to get the count of executed scenarios and in queue scenarios at runitme ?

### ISSUE THREAD

**Issue by Naumansh** [cucumber/cucumber-jvm#1922]
**Question**

I need to perform certain action only after last scenario has been executed in any test execution. Is there a way to get information from cucumber that how many scenarios are executed till the time or how many are left. I know we can do using a static variable but it doesnt work in parallel execution. Appreciate your help in it. Thanks.

Cucumber v : 5.4.2

**Comment by mpkorstanje** [comment]
What kind of action are you thinking of? If it's reporting have a look at the `TestRunFinished` event. Otherwise you'll be waiting for https://github.com/cucumber/cucumber-jvm/pull/1876

**Comment by Naumansh** [comment]
Indeed i am looking forward for 1876. I need to perform some api calls for updating tfs. So need to do it at the end of executions.

**Comment by mpkorstanje** [comment]
I would suggest using the plugin system to generate the desired output and then have your build system interact with TFS using that output. Trying to use hooks for this will cause you more problems then its worth.

**Comment by Naumansh** [comment]
I am not sure how can i do it with plugin. I can do things after every test run or step but how can i get information that all scenarios are executed ?

**Comment by mpkorstanje** [comment]
You can use the `TestRunFinished` event for that. You can find a fairly recent tutorial on a plugin that reports unused steps that you should be able to adapt to you needs.

https://blog.jdriven.com/2019/01/cucumber-jvm-plugin/
