### ISSUE TITLE
Cucumber spring doesn’t support multithread test run

### ISSUE THREAD

**Issue by marinasaln** [cucumber/cucumber-jvm#1924]
**Describe the bug**
We use Cucumber with Spring Boot and Maven Surefire plugin for parallel test run in several threads. Parallel test run worked well until 5.0.0-RC3 cucumber-jvm version. Since that version drivers factory creates only one driver for all threads which makes parallel test run impossible

**Expected behavior**
Cucumber spring should allow multithread bean creation in case of parallel test execution. 

**Context & Motivation**
With current solution it’s impossible to use bean factory to create drivers for each thread for maven parallel test execution. 

**Your Environment**
- cucumber-jvm 5.4.0
- cucumber-testng 5.4.0 for test runner
- maven-surefire-plugin 3.0.0-M4
- Selenium version 3.141.59
- Spring boot version 2.2.4.RELEASE
- Apache Maven 3.6.3
- macOS Catalina, version 10.15.3

**Comment by mpkorstanje** [comment]
With #1848 `cucmber-spring` shares the application context between threads in the same way JUnit/TestNG would through `. This provides a significant speed up. Prior to #1848 cucumber would create a new application context for each thread and you've come to depend on this behavior in your tests.

Currently your options are to either:

1. Use the glue scope to create a bean that is scoped to a scenario. This will create a webdriver for each scenario.

```
import org.springframework.stereotype.Component;
import org.springframework.context.annotation.Scope;
import static io.cucumber.spring.CucumberTestContext.SCOPE_CUCUMBER_GLUE;

@Component
@Scope(SCOPE_CUCUMBER_GLUE)
public class MyComponent {
}
```

2. Use a `ThreadLocal` to store a reference to the webdriver for each thread.

3. Ensure the web driver factory produces thread scoped beans.

**Comment by marinasaln** [comment]
Thanks for describing. I'll try one of the suggested options to fix the parallel test execution.

**Comment by mpkorstanje** [comment]
I'll close this for now. If you need help you may want to try the slack channel.
