### ISSUE TITLE
Characters like umlauts are stripped before being passed to Java methods

### ISSUE THREAD

**Issue by wtho** [cucumber/cucumber-jvm#1925]
**Describe the bug**
When using characters like German umlauts (ä, ö, ü) in `.feature` files, they get stripped before being passed to the Java method.
E. g. the line `Then I can read the title "Menü"` becomes `Men` as the string argument in the java method.

**To Reproduce**
Setup a project with a feature file and a Step with an umlaut (like "ü").

**Expected behavior**
The umlauts are supported, or there is at least an option to enable support.

**Context & Motivation**
I cannot test functionality of website if the dynamic elements (like titles or buttons) contain these letters.

**Your Environment**
Versions:
* `io.cucumber:cucumber-java:5.5.0`
* `io.cucumber:cucumber-junit:5.5.0`
* `io.cucumber:cucumber-picocontainer:5.5.0`
* `org.junit.jupiter:junit-jupiter-api:5.6.0`
* Gradle 2.11
* Windows 10

**Additional context**
I researched for a while online now, but there are no cases describing this. In the docs and FAQ this problem is also not mentioned.

I tried to set `# encoding: ...` and saving the `feature` file in this format, but it still was stripped.

In case this should be issued to the cucumber monorepo, feel free to move it.

**Comment by mpkorstanje** [comment]
I did a really quick test and umlauts seem to be passed in properly. Could you create a minimal reproducer in the form of a github repo?

![image](https://user-images.githubusercontent.com/6946919/77567048-e010d180-6ec6-11ea-93af-5c812bacc307.png)

**Comment by wtho** [comment]
Ok, interesting, great to know that it is supposed to work.
I am quite sure now that this is either a gradle or a Java Encoding problem.

I will close this issue for now, a quick look from a more experienced java-programmer would be much appreciated from my side!
https://github.com/wtho/gradle-cucumber-umlaut

**Comment by mpkorstanje** [comment]
Let's leave it open. I'll have look, if your example works for me the problem can still be in Cucumber.

**Comment by wtho** [comment]
After several different approaches with encoding I finally found a workaround by placing the `.feature` files inside the `main/java` folder instead of `main/resources`.
Still I think there should be a way from gradle to not strip these characters.

Feel free to close this.
