### ISSUE TITLE
Feature request: @AfterStep get the throwable, if present

### ISSUE THREAD

**Issue by joerg1985** [cucumber/cucumber-jvm#1926]
## Summary

Currently it is not possible to get the throwable of the executed step in an @AfterStep. 
Using the injected Scenario it is possible to get the state, not the throwable.

## Expected Behavior

It would be great to get the throwable e.g. to read the message from and e.g. add this to the screenshot for further analysis.

## Your Environment

* Version used: 5.5.0 / Java bindings
* Operating System and version: Windows 10 x64

**Comment by mpkorstanje** [comment]
I'm a bit confused. Most reporting tools already report the exception. Why would you need to report it again? Are you using hooks to create your report? If so please consider the solution outlined in https://github.com/cucumber/cucumber-jvm/issues/1901.

**Comment by joerg1985** [comment]
hi, 
i need the exception to keep the corelation between the exception and the collected additional informations.

I think i can not use the ConcurrentEventListener it will not block the execution until the events are received?

Kind regards

**Comment by mpkorstanje** [comment]
Could you provide an example of what you're trying to achieve? I don't think I quite understand it.
