### ISSUE TITLE
Guidance on using Scenario Interface

### ISSUE THREAD

**Issue by gkalnytskyi** [cucumber/cucumber-jvm#1934]
**Describe the bug**
I'm looking for information on how to use `io.cucumber.core.api.Scenario` interface. I looked through [Cucumber Reporting](https://cucumber.io/docs/cucumber/reporting/) page and [Scenario API](https://javadoc.io/static/io.cucumber/cucumber-core/4.7.2/index.html?io/cucumber/core/api/Scenario.html) pages, but those don't really describe how reporting works in general.

**Context & Motivation**

I am maintaining sizable test automation framework, and trying to improve and simplify it by introducing dependency injection. Previous developer used `scenario.write` as a logging tool and I curious what is the best way keep the concept of what he was trying to achieve, but use `Scenario` interface correctly, and move to constructor injection instead of `@Before` parameter injection.

Here is an example:

    // Let's assume that code below resides in some Java class that defines Gherkin steps
    private Scenario scenario;
    
    @Before()
    public void before(Scenario scenario) {
        this.scenario = scenario;
    }
    
    @Then("^Received XML file should match \"([^\"]*)\"$")
    public void receivedXmlFileShouldMath(String expectedFilePath) {
    
        // ignoring how we read expected file and where received file content is stored
    
        scenario.write("Ignoring date field in xml message");
        compareXml(expectedXml, actualXml)
    }

**Comment by mpkorstanje** [comment]
Currently the only way to get hold of `Scenario` is to use hooks so this looks alright.

**Comment by gkalnytskyi** [comment]
@mpkorstanje, thank you for answer. Sorry for inconvenience, will do next time.
