### ISSUE TITLE
[Spring] Run tests within different profiles / separate context configurations

### ISSUE THREAD

**Issue by borisskert** [cucumber/cucumber-jvm#1938]
Hi!

### Summary
My spring application uses separate Beans for different active profiles which are annotated with @Profile.
I want to test them with cucumber but I dont see a way to test them all within separate context configurations because cucumber forbids me to do so:

`Glue class class [...] and [...] both attempt to configure the spring context. Please ensure only one glue class configures the spring context`

### Feature Request
I want to be able to run the steps in separate contexts, at least with different profiles activated.
It would be nice if I could annotate my step definition classes.

### What i tried
I tried to activate profiles with spring's ConfigurableEnvironment.addActiveProfile, but it does reinitialize the Beans which are depending on.
I also have seen when I am using @DirtiesContext annotation, cucumber runs my spring context several times but always with the same configuration.

### Further information
I have tried to setup my problem here: https://github.com/borisskert/spring-cucumber-profiles

**Comment by borisskert** [comment]
Hi.

I found a solution using separate @CucumberOptions-annotated entry points.
I will push my solution into the mentioned repo.

Thanks.

**Comment by mpkorstanje** [comment]
That's the way to do it. You may find `extraGlue` useful.

https://github.com/cucumber/cucumber-jvm/blob/master/release-notes/v4.0.0.md#extra-glue
