### ISSUE TITLE
CucumberOptions(Strict=true) not failing the Undefined Steps present in Feature File

### ISSUE THREAD

**Issue by suri1990** [cucumber/cucumber-jvm#1946]
Steps To Reproduce : 
1. Created a sample feature file in Java maven project.
2. For few steps in feature for a particular test scenario , didn't defined the step definition code.
3. Using @CucumberOptions(strict=true) in Runner class with other mandatory options as well.
4. Run the maven project from Eclipse IDE.

Actual Result : Undefined Steps are not failing and instead showing pass in HTML report.(Although getting warning in eclipse console to implement undefined steps).

Expected Result : As per strict= true option, undefined steps should fail.

Note : Even with strict=false, undefined tests are getting PASSED instead of getting skipped

Below are some required details -

OS : Windows 8.1
Java Version : 8
Cucumber Version : 5.6.0
Maven version : 3.3.9

[eclipse_console.txt](https://github.com/cucumber/cucumber-jvm/files/4484882/eclipse_console.txt)
![feature_file](https://user-images.githubusercontent.com/63767017/79414006-2c7f9680-7fc7-11ea-9abe-8ef431845df3.PNG)
![html_extent_report](https://user-images.githubusercontent.com/63767017/79414011-2db0c380-7fc7-11ea-8e4c-af6fccfff926.PNG)
![runner_file](https://user-images.githubusercontent.com/63767017/79414012-2e495a00-7fc7-11ea-81fd-f058043eddf3.PNG)
[step_definiton_file.txt](https://github.com/cucumber/cucumber-jvm/files/4484884/step_definiton_file.txt)

**Comment by mpkorstanje** [comment]
It would appear that the `ExtentCucumberAdaptor` does not implement `io.cucumber.plugin.StrictAware`. You should report this with the creators of the `ExtentCucumberAdaptor`.

**Comment by suri1990** [comment]
@mpkorstanje , I removed the ExtentCucumberAdaptor from CucumberOptions and its related dependency from POM.xml file. After execution , its giving me the same result in the HTML report generated by Cucumber.

![cucumber_html_report](https://user-images.githubusercontent.com/63767017/79443614-adef1d00-7ff7-11ea-924c-88e273fcc518.PNG)

**Comment by mpkorstanje** [comment]
At a glance that appears to be the right colour for undefined and pending steps.

Your build failed with a non-zero exit code right?

**Comment by suri1990** [comment]
Can you let me know what is this exit code concept in cucumber? How to get exit code?
Since my understanding is that if strict =true, cucumber should fail the undefined/pending steps(marked as RED in report)
And if strict=false, cucumber should skip the undefined/pending steps(marked as YELLOW in report)

Can you please try to elaborate if I am missing something here?

**Comment by mpkorstanje** [comment]
Cucumber scenarios and steps can have any one of these states: PASSED, SKIPPED, PENDING, UNDEFINED, AMBIGUOUS and FAILED. Cucumbers native html reporter shows these states with different colours.

The test frameworks and reporting tools Cucumber integrates with typically only support PASSED, SKIPPED and FAILED. When strict mode is enabled PENDING and UNDEFINED are mapped to FAILED, otherwise they're mapped to SKIPPED.

Your reporting tool seems to map them PASSED regardless of strict mode.

Command line applications typically can exit with a success code or any number of failures. See https://en.wikipedia.org/wiki/Exit_status and google around a bit. Most build systems (Maven, Gradle) are command line applications and can only support PASSED and FAILED builds. So they map the result of the test framework. SKIPPED becomes PASSED.

So when you're using Maven with Junit and Cucumber JUnit integration and have strict mode enabled the following happens:

```
Cucumber   | JUnit      | Maven      |
PASSED     | PASSED     | PASSED     |
SKIPPED    | SKIPPED    | PASSED     |
PENDING    | FAILED     | FAILED     |
UNDEFINED  | FAILED     | FAILED     |
AMBIGUOUS  | FAILED     | FAILED     |
FAILED     | FAILED     | FAILED     |
```

So if you have any PENDING or UNDEFINED steps and you run `mvn test` your build should fail.

**Comment by suri1990** [comment]
Thanks for the above elaboration. I am somewhat able to understand it.
But just have doubts with color marking in native HTML cucumber report.
In my case, I have one scenario with 3 steps and I haven't defined any of them.
So if strict is enabled, then during execution first step will be marked as Undefined(Yellow color should be shown in native html report which is working correctly) and remaining subsequent 2 steps are marked as Skipped(should be marked as CYAN color in native HTML Report), but the **Skipped** steps are showing in **YELLOW color instead of CYAN** in report.

Why is this happening, since I also went through Cucumber documentation, there its written SKIPPED steps are marked in CYAN color.

**Comment by mpkorstanje** [comment]
For a step to be skipped it has to be defined first.

**Comment by suri1990** [comment]
Ok.So after defining it, how will that the step be skipped?

**Comment by mpkorstanje** [comment]
Either by throwing a skip exception (see the JUnit and TestNG docs) or by having a prior step end with a state a non passed state.

**Comment by suri1990** [comment]
Yes tried throwing skip exception. Its working.
But what do you meant by "....having a prior step end with a non passed state."?

**Comment by mpkorstanje** [comment]
It's probably easier if you look at the source code.

https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/io/cucumber/core/runner/TestCase.java#L39
