### ISSUE TITLE
[Build] Automatically format source code

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1947]
Working through the code base I'm seeing quite a few changes caused by different IDE settings over time. I'd be good to include a step in the build that automatically formats the code. Because this will significantly change large amounts of code, this should be done just before/after releasing v6.

One example we could use:

https://github.com/google/google-java-format

Aside from the build, this should be included in the contribution documentation.

**Comment by a1dutch** [comment]
have you seen [spring-javaformat](https://github.com/spring-io/spring-javaformat)?

**Comment by mpkorstanje** [comment]
Thanks for that! I like the tooling support.

I'll have to look the differences in the style guide and see which one works better.

**Comment by aslakhellesoy** [comment]
This would be awesome! We have this for TypeScript and Ruby in most other places.

**Comment by mpkorstanje** [comment]
I should start rolling this out in the mono repo already. The projects are smaller there.

**Comment by mpkorstanje** [comment]
> spring-javaformat?

 * Uses tabs rather then spaces. 
 * doesn't sort imports

And with spring provided check style enabled:
 * Expects all files to have a copyright header
 * Expects `@author` tags to be present
 * Requires `this.property` to be used in getters.
 
> google-java-format

 * Uses 2 spaces rather then 4
 * Also fixes java doc
 * doesn't sort imports

----

I'd put up with the tabs/spaces thing if only either plugin fixed more things like methods and import order. Check style on its own wouldn't be a bad idea but any configuration that doesn't also come with an automatic fix is going to be too much menial work.

What I'm looking for is something equivalent to IDEA's "Reformat code" option packaged as a maven plugin that takes some settings file.

**Comment by mpkorstanje** [comment]
> https://code.revelc.net/formatter-maven-plugin/plugin-info.html

 * 4 spaces!
 * No Fancy IDE support but probably also not needed.
 * Closely matches default idea/eclipse settings
 * There seems to be some disagreement between IDEA using `indent_size=4` from `.editorconfig` for continuations https://github.com/editorconfig/editorconfig-jetbrains/issues/57 Could be solved by removing `indent_size` from editor config.

**Comment by mpkorstanje** [comment]
And that one is out too. Chained method calls are not allowed to stay on different lines.

E.g:

```
    private static final Comparator<CoreHookDefinition> ASCENDING = Comparator
            .comparingInt(CoreHookDefinition::getOrder)
            .thenComparing(ScenarioScoped.class::isInstance);
```

Must be formatted as: 
```
    private static final Comparator<CoreHookDefinition> ASCENDING = Comparator
            .comparingInt(CoreHookDefinition::getOrder).thenComparing(ScenarioScoped.class::isInstance);
```

**Comment by toepi** [comment]
Why not checkstyle, put it into build and break it instead of do something. Checkstyle is supported by IDE's so you must format all code once and than nobody should be able to contribute code that doesn't match.

**Comment by mpkorstanje** [comment]
I find that feedback cycle to be rather painful. There is always something you forget. While this can be mitigated by configuring your IDE this has to be done for each project. Given that Cuucmber-JVM has a hand full of dependencies that is also rather annoying.

I'm also of the opinion that if our tools are smart enough to spot formatting problems they should be smart enough to at least take a stab at fixing them. Otherwise the cure is worse then the disease.

**Comment by toepi** [comment]
yes, but the formatting should be done in a pre-commit hook. think the worst case is, if somebody push messy-formatted code and the ci-build format it and commit it. Than you make a git blame try to understand why a given line was there and you only see "CI has formatted this line".
For me the best compromise in the last times was checkstyle into build ... 
You change code and you should build and run tests locally before checkin - so it will not build if it is not formatted correctly (this will happens two times than you import check style into your IDE :) ). This means the ci build is only a saftynet if somebody push code without check it locally?
What I have learned about autoformating - mostly doing stuff wrong - for me sometimes:
```
list.stream()
  .filter(...)
  .map(...)
  .collect(...)
```

is more readable than
```
list.stream().filter(...).map(...)
  .collect(...);
```
and most autoformaler try to get the second one ... max line length should be reached?

other think, but is a personal think is:
```
if (isNotNull()
   && isNotEmpty()) {
```
and not
```
if (isNotNull() && isNotEmpty()) {
```

But I fully agree with you code style should be checked automatically.

**Comment by mpkorstanje** [comment]
I'd prefer to format the code at compile time. The `process-sources` step is perfect for this and it keeps the entire thing inside maven.

Anyway looks like there are only two formatters out there. Eclipse and Google. Perhaps I can tweak the Eclipse format to not mess up the return statements. That does however mean that we'd have duplicate these settings across all projects. 

So looking at Spotless I think I might have an idea:

https://github.com/diffplug/spotless/tree/master/plugin-maven

Perhaps we can make it possible to do this:

```
<plugin>
  <groupId>com.diffplug.spotless</groupId>
  <artifactId>spotless-maven-plugin</artifactId>
  <version>${spotless.version}</version>
 <dependencies>
  <dependency>
     <groupId>io.cucumber</groupId>
     <artifactId>cucumber-format</artifactId>
     <version>1.0.0</version>
  </dependency>
 </dependencies>
  <configuration>
    <java>
      <eclipse>
        <file>classpath:io/cucumber/format/eclipse-fmt.xml</file>
        <version>4.7.1</version>
      </eclipse>
    </java>
  </configuration>
</plugin>
```
