### ISSUE TITLE
Called out on "ambiguous" rule because word permits starting with a minus sign

### ISSUE THREAD

**Issue by trejkaz** [cucumber/cucumber-jvm#1968]
**Describe the bug**

Scenarios like this:

```
    Scenario: Adding two tuples
        Given a1 ← tuple(3.0, -2.0, 5.0, 1.0)
        And a2 ← tuple(-2.0, 3.0, 1.0, 0.0)
        Then a1 + a2 = tuple(1.0, 1.0, 6.0, 1.0)

    Scenario: Negating a tuple
        Given a ← tuple(1.0, -2.0, 3.0, -4.0)
        Then -a = tuple(-1.0, 2.0, -3.0, 4.0)
```

Result in writing two steps which are literal opposites:

```kotlin
        Then("{word} = tuple\\({real}, {real}, {real}, {real})") {
                v: String, x: Double, y: Double, z: Double, w: Double ->
            assertThat(-tuples[v]!!).isEqualTo(Tuple(x, y, z, w))
        }

        Then("-{word} = tuple\\({real}, {real}, {real}, {real})") {
                v: String, x: Double, y: Double, z: Double, w: Double ->
            assertThat(-tuples[v]!!).isEqualTo(Tuple(x, y, z, w))
        }
```

This causes the following failure:

```
"-a = tuple(-1.0, 2.0, -3.0, 4.0)" matches more than one step definition:
  "-{word} = tuple\({real}, {real}, {real}, {real})" in TupleStepDefinitions.<init>(TupleStepDefinitions.kt:94)
  "{word} = tuple\({real}, {real}, {real}, {real})" in TupleStepDefinitions.<init>(TupleStepDefinitions.kt:64)
io.cucumber.core.runner.AmbiguousStepDefinitionsException: "-a = tuple(-1.0, 2.0, -3.0, 4.0)" matches more than one step definition:
  "-{word} = tuple\({real}, {real}, {real}, {real})" in TupleStepDefinitions.<init>(TupleStepDefinitions.kt:94)
  "{word} = tuple\({real}, {real}, {real}, {real})" in TupleStepDefinitions.<init>(TupleStepDefinitions.kt:64)
```

**To Reproduce**

Define step definitions analogous to above.

**Expected behavior**

Presumably this occurs because whatever pattern matches a word happens to match a hyphen character, in order to match hyphenated words. But words, at least where I come from, cannot start with a hyphen, so this should not be ambiguous.

**Context & Motivation**

I'm following the Ray tracer challenge.

https://pragprog.com/book/jbtracer/the-ray-tracer-challenge
https://forum.raytracerchallenge.com/thread/169/negate-rule-ambiguous

**Your Environment**
 - Version used: 5.7.0
 - Running on Java 11 on Windows 10, building with Gradle 6.1

**Comment by mpkorstanje** [comment]
`word` is a reference to the word characters as defined by the regex `\w`, not necessarily a single word.

I'd suggest using a dedicated parameter type for your value reference. Or alternatively explicitly including an expected value for the `-` tuple in tuples so only one step definition is needed.

**Comment by aslakhellesoy** [comment]
I would recommend defining your own `tuple` parameter type. That makes your step definitions shorter and more expressive:

```java
Then("-{word} = {tuple}") {
  name: String, tuple: Tuple -> assertThat(-tuples[name]!!).isEqualTo(tuple)
}
```

Cucumber will also keep recommending `{tuple}` if you write another undefined step that contains something that looks like a tuple.

**Comment by trejkaz** [comment]
I'm definitely considering that approach but it does put the parsing of all those complex values into my own hands. :(

**Comment by trejkaz** [comment]
You'll still get a problem though, where these two will clash:

```
Then("-{word} = {tuple}") {
  name: String, tuple: Tuple -> assertThat(-tuples[name]!!).isEqualTo(tuple)
}
Then("{word} = {tuple}") {
  name: String, tuple: Tuple -> assertThat(-tuples[name]!!).isEqualTo(tuple)
}
```

Hyphen isn't even in the set of characters matched by `\w`.

**Comment by mpkorstanje** [comment]
Owh my bad. I forgot that we redefined `word` that to `[^\s]+` because other languages have words don't necessarily use `a-z`. 

Like I said before I would suggest that you either use:

```
Then("{word} = {tuple}") {
  name: String, tuple: Tuple -> assertThat(tuples[name]!!).isEqualTo(tuple)
}
```
And store an separate entry for "-a" in `tuples`. 

Or alternatively that you define a separate parameter type for your identifiers that only matches `[a-z]`. 

@aslakhellesoy while useful the ambiguity was not caused by the tuples but rather the by `{word}` and `-{word}` matching the same things.

**Comment by trejkaz** [comment]
ah, the test is testing the unary `-` operator so that I can't really change...

**Comment by mpkorstanje** [comment]
So `-a` is an `{operator}` followed by a `{variable}`. It would help to make that explicit.
