### ISSUE TITLE
[Spring] Scope 'cucumber-glue' is not allowed for standard (not glue) Spring Bean during context loading

### ISSUE THREAD

**Issue by kochetkov-ma** [cucumber/cucumber-jvm#1970]
Environmet: `io.cucumber:cucumber-spring:5.7.0`

Actual: In my Spring Configuration I use Scope 'cucumber-glue' before its registration by `TestContextAdaptor#registerGlueCodeScope(org.springframework.context.ConfigurableApplicationContext)`.
This scope registers after Spring Context loading on glue loading stage.
But I want use this Scope for my Spring-beans because this scope is allowed for me in `CucumberTestContext`
And I cannot (in right way) register it manually because `GlueCodeScope` class has package-default visibility.

Expected: Register this scope erlier

`Caused by: java.lang.IllegalStateException: No Scope registered for scope name 'cucumber-glue'`

**Comment by mpkorstanje** [comment]
Could you explain how to reproduce this problem and what you are trying to achieve?

>  But I want use this Scope for my Spring-beans because this scope is allowed for me in CucumberTestContext

This may be a documentation issue. I'm not aware of any use-case where you might want to access a glue scoped bean outside the context of a running scenario.

**Comment by kochetkov-ma** [comment]
> Could you explain how to reproduce this problem and what you are trying to achieve?

Sorry I should did it in advance. I think few people can face it, but
```
import io.cucumber.java.en.Given;
import io.cucumber.spring.SpringFactory;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Scope;
import org.springframework.test.context.ContextConfiguration;

public class Issue1970 {

    @Test
    public void issue1970() {
        var factory = new SpringFactory();
        factory.addClass(GlueClass.class); // Add glue with Spring configuration
        factory.start();
    }

    @ContextConfiguration(classes = MySpringConfiguration.class)
    public static class GlueClass {

        @Given("step")
        public void step() {
            /* do nothing */
        }
    }

    public static class MySpringConfiguration {

        /**
         * It need {@link #simpleGlueScopeBean}.
         * By default Spring try to create singleton bean in an eager manner on start up.
         * There are no "cucumber-glue" scope at this moment.
         */
        @Bean
        // @Lazy // Lazy is a workaround. But every bean in init chain must be lazy.
        public String singletonBean(@Autowired String simpleGlueScopeBean) {
            return simpleGlueScopeBean + " singleton";
        }

        /**
         * Bean with 'cucumber-glue'. Not glue. 
         * I want use it in multi-thread scenario execution and Spring will manage it via scope.
         */
        @Bean
        @Scope("cucumber-glue") // This is Cucumber Glue scope
        public String simpleGlueScopeBean() {
            return "cucumber-glue";
        }
    }
}
```

**Comment by mpkorstanje** [comment]
Makes sense. Cheers.

If I understand this correctly, you're trying to stub out some behaviour of your application?

**Comment by mpkorstanje** [comment]
>  I want use it in multi-thread scenario execution and Spring will manage it via scope.
>  Lazy is a workaround. But every bean in init chain must be lazy.

Neither of these things work the way you think it does. Scoped beans require a proxy, this proxy will initalize the been as needed when invoked in a particular scope. For this to work however you have to set the proxyMode.

```
@Scope(value = SCOPE_CUCUMBER_GLUE, proxyMode = ScopedProxyMode.TARGET_CLASS)
```

**Comment by kochetkov-ma** [comment]
I know about proxies, I just missed this point in the example. I created it to demonstrate the specific situation with the scope registration, but it does not matter, because the error is reproduced with a proxy.
The essence of the problem is that the registration of the scope "cucumber-glue" in the class `io.cucumber.spring.TestContextAdaptor` calls after initialization of my Spring Context. If in the context there is a singleton using a bean with scope "cucumber-glue", then the application crashes because the scope has not yet been registered. And I can’t register scope myself, because `GlueCodeScope.class` is not public.

**Comment by mpkorstanje** [comment]
The `cucumber-glue` scope is not active when a scenario is not executed. If you do not use a proxy you'll instantiate a scenario scenario scoped bean, but this bean will be reused between scenarios. This shouldn't happen.

For example:

```java
class Issue1970 {

    @Test
    public void issue1970() {
        ObjectFactory factory = new SpringFactory();
        factory.addClass(GlueClass.class); // Add glue with Spring configuration
        factory.start();
        GlueClass instance = factory.getInstance(GlueClass.class);
        String response = instance.service.get();
        factory.stop();
        factory.start();
        GlueClass instance2 = factory.getInstance(GlueClass.class);
        String response2 = instance2.service.get();
        factory.stop();

        assertNotEquals(response, response2);
    }

    @CucumberContextConfiguration
    @ContextConfiguration(classes = TestApplicationConfiguration.class)
    public static class GlueClass {

        @Autowired
        ExampleService service;

    }

    @Configuration
    public static class TestApplicationConfiguration {

        @Bean
        public BeanFactoryPostProcessor beanFactoryPostProcessor(){
            return factory -> factory.registerScope(SCOPE_CUCUMBER_GLUE, new GlueCodeScope());
        }

        @Bean
        public ExampleService service(ScenarioScopedApi api) {
            return new ExampleService(api);
        }

        @Bean
        @Scope(value = SCOPE_CUCUMBER_GLUE)
        public ScenarioScopedApi api() {
            return new ScenarioScopedApi();
        }

    }

    public static class ExampleService {

        final ScenarioScopedApi api;

        public ExampleService(ScenarioScopedApi api) {
            this.api = api;
        }

        String get(){
            return "Api response: " + api.get();
        }
    }

    public static class ScenarioScopedApi {

        private static final AtomicInteger globalCounter = new AtomicInteger(0);
        private final int instanceId = globalCounter.getAndIncrement();

        public String get() {
            return "instance " + instanceId;
        }

    }

}
```

Will fail with: `java.lang.AssertionError: Values should be different. Actual: Api response: instance 0`.

This happens because the `GlueCodeContext` currently allows beans to be created before any scenario has started. If we fix the `GlueCodeContext` to require an active scenario then the spring application fails to launch with:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'api': Scope 'cucumber-glue' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: cucumber-glue is not active
```

So if we follow these instructions and use the `ScopedProxyMode.TARGET_CLASS` then we'll see different instances of the api object and the test passes. And because the bean is lazily initialized the `cucumber-glue` scope doesn't need to be registered at start up.

```java
   @Configuration
    public static class TestApplicationConfiguration {

        @Bean
        public ExampleService service(ScenarioScopedApi api) {
            return new ExampleService(api);
        }

        @Bean
        @Scope(value = SCOPE_CUCUMBER_GLUE, proxyMode = ScopedProxyMode.TARGET_CLASS)
        public ScenarioScopedApi api() {
            return new ScenarioScopedApi();
        }

    }
```

So I don't see why you'd have to have access to the `GlueCodeScope`.

**Comment by kochetkov-ma** [comment]
I use glue scope to save scenario vars
```
@Slf4j
@Component
@Scope(value = PumpConstants.SCENARIO_SCOPE, proxyMode = ScopedProxyMode.TARGET_CLASS)
public class ScenarioVars extends AbstractVars {
    @Value("${pump.bind.scenario:#{null}}")
    private String overriddenBind;

    @Override
    public String bindName() {
        return overriddenBind == null ? "scenario" : overriddenBind;
    }
}
```
Then inject it to hook
```
public class CoreCucumberHook {

    private final ApplicationEventPublisher eventPublisher;
    private final Collection<String> directBindings;
    private final ScenarioVars scenarioVars;
    private final FeatureVars featureVars;

    public CoreCucumberHook(ApplicationEventPublisher eventPublisher,
                            Collection<String> directBindings,
                            ScenarioVars scenarioVars,
                            FeatureVars featureVars) {
        this.eventPublisher = eventPublisher;
        this.directBindings = directBindings;
        this.scenarioVars = scenarioVars;
        this.featureVars = featureVars;
        Execution.checkRunner();
    }

    @Before(value = "@StepVars", order = 0)
    public void extractStepVars() {
        directBindings.add(scenarioVars.bindName());
    }
```
And `private final Collection<String> directBindings` has glue scope too
Now everything is ok, because my hooks with my beans are created after test execution start.
May be it not good to call methods while creationing a bean, but if you add this line, it will throw an exception
```
   @Configuration
    public static class TestApplicationConfiguration {

        @Bean
        public ExampleService service(ScenarioScopedApi api) {
            api.get(); // call some method here
            return new ExampleService(api);
        }

        @Bean
        @Scope(value = SCOPE_CUCUMBER_GLUE, proxyMode = ScopedProxyMode.TARGET_CLASS)
        public ScenarioScopedApi api() {
            return new ScenarioScopedApi();
        }

    }
```

**Comment by mpkorstanje** [comment]
> May be it not good to call methods while creationing a bean, but if you add this line, it will throw an exception java.lang.IllegalStateException: No Scope registered for scope name 'cucumber-glue'

Can you try this with https://github.com/cucumber/cucumber-jvm/pull/1974. It should correctly complain about 'cucumber-glue' scope not being active.
