### ISSUE TITLE
Cant find CucumberOptions in cucumber-core 5.5.0

### ISSUE THREAD

**Issue by qaschevychelov** [cucumber/cucumber-jvm#1975]
Hi!
I'm using cucumber-core 2.4.0 (in Serenity BDD framework). I want to update cucumber-java and cucumber-core upto 5.5.0. But i've stumbled upon with an issue. I cant find "CucumberOptions" in 5.5.0. How to work around this issue?

**Comment by gaeljw** [comment]
Hello,

There's been a lot of change between 2.x and 5.x. I encourage you to read the [CHANGELOG](https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md).

Especially packages have changed, it's now `import io.cucumber.junit.{Cucumber, CucumberOptions}` (from cucumber-junit).
