### ISSUE TITLE
Cucumber: Multiple Scenario Outlines are not getting executed in Cucumber 5.x.x: A possible bug?

### ISSUE THREAD

**Issue by chetanSrajiv** [cucumber/cucumber-jvm#1980]
In my feature file, I have two Scenario Outlines, with their own Examples section. I have tagged each of these Scenario Outlines differently(@test1, @test2). When I try to run both Scenario Outlines with Cucumber 5.6.0, I get the following error:-

0 Scenarios
0 Steps
0m0.001s
Only one Scenario Outline at a time is getting executed successfully with Cucumber 5.6.0. I get the same result with Cucumber 5.0.0

**Comment by mpkorstanje** [comment]
Please ensure that you are using a correct tag expression. For example `@cucumber and not (@gherkin or @lettuce)`.

**Comment by chetanSrajiv** [comment]
while using tags for execution it is working properly!! we are using below command which was executing perfectly before updating to 5.6.0 from 1.2.6

we are creating a jar with cucumber and our tests and using below command to execute scenario with path. this is working with **scenario** keyword but not with ***scenario outline***
both cases are working when we are using cucumber-java version 1.2.5

below is the command that specifies scenario outline number (75) in feature file

**java -jar C:\repos\testPlatform\platform\test\cucumber-webdriver\build\libs\cucumber-webdriver.jar CaseTree\gherkin\ConfigureStages.feature:75 --strict --plugin pretty --glue classpath:com.test --plugin html:C:\repos\testPlatform\platform\test\cucumber-webdriver\build\results\cucumber\html_results\cucumber-report --plugin junit:C:\repos\testPlatform\platform\test\cucumber-webdriver\build\results\cucumber\xml_results\cucumber-junitreport.xml --plugin json:C:\repos\testPlatform\platform\test\cucumber-webdriver\build\results\cucumber\json_results\cucumber-report.json**

**Comment by gaeljw** [comment]
There has been a tremendous amount of changes since version 1.x. I would suggest you to take a look at the [CHANGELOG](https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md).

Anyway it will be easier if you give sample of your code to help you.

**Comment by chetanSrajiv** [comment]
hi @mpkorstanje,
is there any workaround to fix this issue temporarily?
also how can we use the latest code which has the fix #1981 ?

**Comment by mpkorstanje** [comment]
>  is there any workaround to fix this issue temporarily?

You can reference the individual example lines.

>  also how can we use the latest code which has the fix #1981 ?

The quickest would be to clone the repository and build it yourself.
