### ISSUE TITLE
Cucumber report junit 5

### ISSUE THREAD

**Issue by JimmySimard** [cucumber/cucumber-jvm#1983]
Unable to generate the report with junit 5 and cucumber platform engine

Only use platform engine @Cucumber

Generate a report at the end of the test.

The json file is needed to complete my dashboard. 

windows 10
eclipse

**Comment by timtebeek** [comment]
Have you configured the appropriate plugin through `src/test/resources/junit-platform.properties` ? When I have such a file containing:
```properties
cucumber.plugin=pretty,json:target/cucumber/report.json
```
And I run my tests through something like:
```java
package my.company.cucumber;
@io.cucumber.junit.platform.engine.Cucumber
public class RunCucumberIT {
	// Allow Maven failsafe to discover Cucumber tests
}
```
Then I get pretty output on stdout, and json output in `target/cucumber/report.json`.
[The relevant documentation for all of this is here](https://github.com/cucumber/cucumber-jvm/tree/master/junit-platform-engine#configuration-options). Does any of that help?

If not then we definitely need more information on what you are and aren't using to run your tests.

**Comment by mpkorstanje** [comment]
Please feel free to reopen with more information.
