### ISSUE TITLE
Data Table Headers Transformation: edge cases 

### ISSUE THREAD

**Issue by ddsultan** [cucumber/cucumber-jvm#1984]
**Is your feature request related to a problem? Please describe.**
As [the documentation](https://github.com/cucumber/cucumber-jvm/blob/master/release-notes/v5.0.0.md#default-transformer) implies _"To facilitate the transformation of data table entries the table headers are converted from title case to camel case..."_ There some cases where a header is all capital like `ID` or `Client ID`

**Describe the solution you'd like**
Is there any option to override the default behavior?

**Describe alternatives you've considered**
I have just changed the header `ID` to `id`

**Additional context**
This would make feature descriptions more natural rather than adapting them per Step Definitions.

Thanks!

**Comment by mpkorstanje** [comment]
Check the java doc on the annotation.
