### ISSUE TITLE
Tag expressions are lost when specifying external feature file locations

### ISSUE THREAD

**Issue by edwardcallow-gw** [cucumber/cucumber-jvm#1985]
**Describe the bug** 
When specifying the command line argument `cucumber.features`, the tag expressions that classes are annotated with are lost while the cucumber options are being parsed. I am using multiple annotated classes to define contexts which run different sets of features. The tag expression tells each context which set of features they should be running. This is important as we're using Spring profiles to inject a set of components, including the glue code, depending on the current context. An example annotated class is as follows :
```
@RunWith(Cucumber.class)
@CucumberOptions(features = "classpath:features/context1",
    plugin = {"pretty", "json:build/cucumber/context1/cucumber.json"},
    tags = "@Context1")
public class Context1Test {
}
```
The respective glue code located within the same package is annotated so that a spring context is created with a specific profile. 
```
@ActiveProfiles("context1")
@SpringBootTest
public class Context1Definitions
```
This structure works perfectly using the command line tag filter, e.g. `-Dcucumber.filter.tags="not @Context1"` will ignore this sub set of tests. However, when specifying externalised feature files the tag expression gets set to an empty list. This lack of filtering results in each context attempting to run the feature file and many errors due to unmatched glue code.

**To Reproduce**
1. Create a feature file `tmp/features/ctx1.feature` tagged with '@Context1`. 
2. Add `-Dcucumber.features=/tmp/features` command line argument to test execution.
3. Both `context1` and `context2` contexts are loaded and attempt to run the feature file. 
4. A `PendingException` is thrown. 

**Expected behavior**
When external feature files are provided at runtime, I would expect the tag expression to be retained so that each context can run any features/scenarios in that path that match this expression. 

**Context & Motivation**
There is a requirement that the testing framework I've created is able to run in multiple environments, where each environment may have it's own set of test cases. So externalising the feature file location, while still retaining the defined tag expressions, would allow us to satisfy this requirement. 

**Your Environment**
 - Versions used 5.5.0 (cucumber-java, cucumber-junit, cucumber-spring)
 - Operating System and version Ubuntu 18.04.4 LTS
 - Build tool Gradle 5.6

**Comment by mpkorstanje** [comment]
Cheers!
