### ISSUE TITLE
Usage Report doesn't output the correct times for durations of 1 second or greater

### ISSUE THREAD

**Issue by woodybrood** [cucumber/cucumber-jvm#1988]
**Describe the bug**
The durationJsonSerializer is using getNano() instead of toNanos() when getting the duration in nanoseconds. As a result the seconds part of the duration time in the usage report is being dropped and the result is random looking numbers less than a second for all test steps.

**To Reproduce**
1. Create a test step with a Thread.sleep(2000) in it
2. Write a scenario that calls that step
3. Run the scenario defined with the usage report plugin defined
4. In the resulting usage report, the durations will be 0.

**Expected behavior**
The durations for a test step with a 2 second sleep in it should have a duration of ~2 seconds. 

**Context & Motivation**
I have used the usage report to understand the run times of my test steps and look for opportunities to speed things up.

**Screenshots**
n/a

**Your Environment**
 - Version 5.6.0 (also in master)
 - OS n/a
 - Maven 3.6.0

**Additional context**
I have a fix and will be providing a pull request with the fix and a modified test that verifies the fix.

**Comment by timtebeek** [comment]
Fixed in https://github.com/cucumber/cucumber-jvm/pull/1989 ; Thanks a lot!
