### ISSUE TITLE
CDI Jakarta support

### ISSUE THREAD

**Issue by rmannibucau** [cucumber/cucumber-jvm#1996]
Hi,

Javax migrated to jakarta namespace.
Wonder if we should have a cdi-jakarta module, can be as easy as:

1. using jakarta dependencies (https://github.com/apache/openwebbeans/blob/master/src/site/apt/jakarta.apt) - to have the right pom
2. shading cdi module as openwebbeans does (https://github.com/apache/openwebbeans/blob/master/pom.xml#L363) - to have the right bytecode

wdyt?

Romain

**Comment by mpkorstanje** [comment]
So with option #1 we would do the following:

1. Copy the `cdi2` module to `cdi-jakarta`. 
2. Replace `javax.enterprise:cdi-api` and `javax.annotation:javax.annotation-api` with their `jakarta` equivalents.
3. Eventually deprecate the `cdi2` module in favour of `cdi-jakarta`?

**Comment by rmannibucau** [comment]
@mpkorstanje I had more in mind 1 and 2 being the 2 steps of a single work unit but both are options. So to summarize:

1. we can fork cdi2 to do a cdi-jakarta and just copy/relocate the code/deps
2. we can keep cdi code in cdi2 module (or jakarta it is symmetric) and create the other module just by defining the new pom and using the other module (cdi2 in my example) relocated with shade plugin (or any build relocator), since code is 1-1 if you ignore the package renaming it is the less costly option for cucumber IMO while cdi2 is not dropped (I suspect javax will stay something we should keep in the project for ~2 years, then dropping would be sane)

So personally I think having the shade for 1 year, deprecated cdi2 for 1 year then dropping it is not a bad plan but happy with whatever solution works for you too.

**Comment by mpkorstanje** [comment]
I'd prefer copy-paste-deprecate. It has less complexity and will allow us to keep evolving the new version while the old one stays frozen.
