### ISSUE TITLE
No error reported when no matching cucumber tag found

### ISSUE THREAD

**Issue by connectashish91** [cucumber/cucumber-jvm#2008]
When running a cucumber test with no existing scenario tag, using Cucumber-Junit runner file, no message is displayed from the code.

1. Create a runner file with tag that does not exist in the feature file
2. The message is reported.

**Expected behavior**
Message from code:

0 Scenarios
0 Steps
0m0.048s

**Comment by connectashish91** [comment]
It was working till version 5.7.0

**Comment by mpkorstanje** [comment]
This output was disabled intentionally. Cucumber integrates with JUnit and JUnit in turn integrates with various tools. It is the responsibility of these tools to report on test execution. For example when using JUnit 4 and Maven you'd see this in the output:

```
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ java-calculator ---
[INFO] Toolchain in maven-surefire-plugin: JDK[/usr/lib/jvm/java-11-openjdk-amd64]
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.cucumber.examples.java.RunCucumberTest
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in io.cucumber.examples.java.RunCucumberTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
```

You can restore the old behaviour by enabling the `summary` printer: 

```
package com.example;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(plugin = { "summary" })
public class RunCucumberTest {

}
```

**Comment by connectashish91** [comment]
Is there any plans to disable this feature in future.

@CucumberOptions(plugin = { "summary" })

**Comment by mpkorstanje** [comment]
Wouldn't expect so. What make it so important to you?

**Comment by connectashish91** [comment]
We have developed a test automation framework where testers develop/execute the tests in Eclipse IDE, so whenever there is a human error in passing the scenario tag, no log is displayed and the run is terminated. 
Our test automation framework is designed in a way that allows non-technical guys to execute tests, so when they don't see any log they become clueless and raise it as bug in the framework.

**Comment by mpkorstanje** [comment]
If you are using the Eclipses JUnit integration you'll see a list of executed scenarios in the JUnit tool bar. Or none if nothing was executed because of a non-existing tag. If you are using something else in your framework, it is now your responsibility to report on the execution of the tests.

![image](https://user-images.githubusercontent.com/6946919/84259152-51e8d680-ab18-11ea-98c2-8d3a1f980f1d.png)
