### ISSUE TITLE
Getting "No features found at classpath:/makroRunner" while try to run with testng xml

### ISSUE THREAD

**Issue by vipulkumar1804** [cucumber/cucumber-jvm#2014]
I am using io.cucumber dependency and try to run feature file with testNG xml but getting "No features found at classpath:/makroRunner" , able to run with junit runner but not with testng xml.

**Comment by mpkorstanje** [comment]
Heya, please review https://stackoverflow.com/help/how-to-ask 

Specifically the section on how to create a Minimal, Complete, and Verifiable example. Then feel free to reopen this issue.
