### ISSUE TITLE
unable to pass cucumber options through maven sure fire plugin after updating cucumber-java, cucumber-testng to 6.0.0

### ISSUE THREAD

**Issue by chetanSrajiv** [cucumber/cucumber-jvm#2017]
unable to pass --tags through maven sure fire plugin after updating cucumber-java, cucumber-testng to 6.0.0. 
This was working fine with 5.6.0 version of cucumber dependencies

- update cucumber dependencies to 6.0.0 in your pom.xml
cucumber-java
cucumber-testng
cucumber-core
cucumber-guice
- run maven install by providing tag name of a cucumber feature file or scenario in maven sure fire plugin 

**Expected behavior**
test case matching to that tag needs to be executed

**Actual behaviour**
all the test cases are being executed

**Context & Motivation**
i am trying to run a single test case by providing cucumber options in sure fire plugin, which was working fine before i updated cucumber-dependencies to 6.0.0 from 5.6.0

**Your Environment**
 - cucumber 6.0.0]
 - Operating System and version [windows 10]
 - Build tool [ Apache Maven 4.0.0]

Maven sure fire plugin
```
<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-surefire-plugin</artifactId>
		<version>3.0.0-M4</version>
		<configuration>
			<systemPropertyVariables>
			<runMode>${runMode}</runMode>
			<device>${device}</device>
			</systemPropertyVariables>
			<argLine>-Dcucumber.options=" --tags
			"@TC-123"
			--plugin pretty
			--plugin
			html:target/cucumber-htmlreport
			--plugin
			json:target/cucumber-report.json"
			-Dguice.injector-source=com.pega.config.guice.GuiceInjector
			-Dfile.encoding=UTF-8
			-DbaseClass="${baseClass}"</argLine>
		</configuration>
</plugin>
```

**Comment by mpkorstanje** [comment]
Please consult the changelog and release notes. 

https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md
https://github.com/cucumber/cucumber-jvm/blob/master/release-notes/v6.0.0.md
