### ISSUE TITLE
Getting warning "No features found at classpath:/makroRunner" while try to run with testng xml

### ISSUE THREAD

**Issue by vipulkumar1804** [cucumber/cucumber-jvm#2018]
Getting Warning in console "No features found at classpath:/makroRunner" while try to run with testng xml, but its working fine with Junit runner
**Warning:**
Jun 11, 2020 3:51:23 PM io.cucumber.testng.TestNGCucumberRunner <init>
WARNING: By default Cucumber is running in --non-strict mode.
This default will change to --strict and --non-strict will be removed.
You can use --strict or @CucumberOptions(strict = true) to suppress this warning
Jun 11, 2020 3:51:23 PM io.cucumber.core.runtime.FeaturePathFeatureSupplier get
WARNING: No features found at classpath:/makroRunner

0 Scenarios
0 Steps
0m0.010s

Using JUnit 4  with io.cucumber dependencies. Below is using dependencies:
    
    <artifactId>cucumber-core</artifactId>
    <version>5.7.0</version>

    <artifactId>cucumber-jvm</artifactId>
    <version>5.7.0</version>

    <artifactId>cucumber-java</artifactId>
    <version>5.7.0</version>

    <artifactId>selenium-java</artifactId>
    <version>3.141.59</version>

    <artifactId>selenium-server</artifactId>
    <version>3.141.59</version>

    <artifactId>selenium-support</artifactId>
    <version>3.141.59</version>

    <artifactId>cucumber-testng</artifactId>
    <version>5.7.0</version>

    <artifactId>webdrivermanager</artifactId>
    <version>4.0.0</version>

    <artifactId>testng</artifactId>
     <version>7.1.0</version>

    <artifactId>junit</artifactId>
    <version>4.13</version>

<artifactId>maven-compiler-plugin</artifactId>
<version>3.8.1</version>
<artifactId>maven-surefire-plugin</artifactId>
<version>2.22.2</version>

**And below is test runner class:**
@RunWith(Cucumber.class)		
@CucumberOptions(
		features="src/test/resources/features",
		plugin = {"pretty","html:target/cucumber","json:target/cucumber/cucumber.json"},
		glue="makroStepDefinations",
		monochrome = true,
		tags= {"@signIn"},
		strict = true
		
		)
public class RunnerTest extends AbstractTestNGCucumberTests {
	@Override
    @DataProvider(parallel = true)
    public Object[][] scenarios() {
        return super.scenarios();

    }

**Comment by mpkorstanje** [comment]
Remove `cucumber-junit` from your dependencies and fix the compile errors.

**Comment by vipulkumar1804** [comment]
@mpkorstanje After removing cucumber-junit dependency, not able to run junit runner and getting error because of dependency is missing to run @RunWith(Cucumber.class).

**Comment by mpkorstanje** [comment]
While you can use `cucumber-junit` and `cucumber-testng` together it is not recommend to do so. By removing `cucumber-junit` you can focus on getting `cucumber-testng` to work. This may mean that you'll have to remove JUnit specific code.
