### ISSUE TITLE
6.1.0 - Html formatter produces report with no contents

### ISSUE THREAD

**Issue by grasshopper7** [cucumber/cucumber-jvm#2020]
Using this plugin setting `"html:target/htmlold/report.html"`. The report file size is around 1.8 mb, but nothing is visible when opening in browser. Tried with different browsers. I can see the contents when opening with a text editor in the script tag. On windows and using version 6.1.0. 

[report.zip](https://github.com/cucumber/cucumber-jvm/files/4769683/report.zip)

The link in this wiki page - https://github.com/cucumber/cucumber-jvm/blob/master/release-notes/v6.0.0.md for `To resolve these issues Cucumber now has a message based output format.` is giving 404 error.

**Comment by mpkorstanje** [comment]
Would you mind reporting the output from:

```
import java.nio.charset.Charset;
import java.io.InputStreamReader;
import java.io.FileInputStream;

public class PrintCharSets {
        public static void main(String[] args) throws Exception {
                System.out.println("file.encoding=" + System.getProperty("file.encoding"));
                System.out.println("Charset.defaultCharset=" + Charset.defaultCharset());
                System.out.println("InputStreamReader.getEncoding=" + new InputStreamReader(new FileInputStream("pom.xml")).getEncoding());
        }
}
```

**Comment by grasshopper7** [comment]
```
file.encoding=Cp1252
Charset.defaultCharset=windows-1252
InputStreamReader.getEncoding=Cp1252
```

**Comment by mpkorstanje** [comment]
Should be fixed in v6.1.1 and available from maven central in a few hours.

**Comment by mpkorstanje** [comment]
Let me know if it fails. I can't reproduce this without a Windows machine. So the fix was a bit of guess work.

**Comment by grasshopper7** [comment]
Will check it out. One additional query - I tried the new HTML and JSON formatters, and am getting the same output for both. Just the file extensions are different. Is this the designed behavior?

**Comment by mpkorstanje** [comment]
It depends on what you mean by the same. Their outputs should be quite similar, but not identical. The html formatter is a single page javascript application. The json is embedded into it.

**Comment by grasshopper7** [comment]
It is identical. Used this in runner - `"message:target/html/cucumber-report.html", "message:target/json/cucumber-report.ndjson"`.
Got the below 2 reports. Compared in a text editor and both are the same.
[report.zip](https://github.com/cucumber/cucumber-jvm/files/4772559/report.zip)

**Comment by mpkorstanje** [comment]
I think you may want to look at your commands quite carefully.

**Comment by mpkorstanje** [comment]
Ah. Right. I see where you got it from.

**Comment by grasshopper7** [comment]
aaahhh got it... i copied from the wiki. light bulb finally went off
