### ISSUE TITLE
datatable/java:  replaceWithEmptyString doesn't work properly

### ISSUE THREAD

**Issue by emaks** [cucumber/cucumber-jvm#2048]
## Steps to Reproduce

I have code
```
    private final ObjectMapper objectMapper = new ObjectMapper().registerModule(new JavaTimeModule());

    @DefaultParameterTransformer
    @DefaultDataTableCellTransformer
    @DefaultDataTableEntryTransformer(replaceWithEmptyString = "<empty>")
    public Object defaultTransformer(Object fromValue, Type toValueType) {
        JavaType javaType = objectMapper.constructType(toValueType);
        return objectMapper.convertValue(fromValue, javaType);
    }

    @Given("I have data:")
    public void getData(List<Map<String, String>> data) {
      System.out.println(data);
    }

  Scenario: Scenario1
    Given I have data:
      | index | user    |
      | 2     | <empty> |
      | 3     | user3   |
```
##  Actual result

```"<empty>"``` value is not replaced on ```""``` in Map
```[{index=2, user=<empty>}, {index=3, user=user3}]```

##  Expected result
```[{index=2, user=}, {index=3, user=user3}]```

## Note.
will work if I define parameter like List<HashMap<String, String>> data

**Comment by mpkorstanje** [comment]
That is more or less as expected but I suppose it could be documented a bit better.

Cucumber only uses the `DefaultDataTableCellTransformer` when it doesn't have a parameter type defined for a particular java type. By default there is a transform for `Strings` so the `DefaultDataTableCellTransformer` is not used.

So you have redefine the the default transform for `String`. You'd do that like so:

```feature
Feature: Whitespace
  Scenario: Whitespace in a table
   Given a blank value
     | key | value   |
     | a   | [blank] | 
```

```java
@Given("A blank value")
public void given_a_blank_value(Map<String, String> map){
    // map contains { "key":"a", "value": ""}
}

@DataTableType(replaceWithEmptyString = "[blank]")
public String listOfStringListsType(String cell) {
    return cell;
}
```

**Comment by emaks** [comment]
Thank you for your quick response!

> By default there is a transform for Strings

Could you tell me where I can find which java types have transform rules by default?

**Comment by mpkorstanje** [comment]
https://github.com/cucumber/cucumber/tree/master/datatable#table-types
