### ISSUE TITLE
Cucumber reports generated doesn't have screenshot attached

### ISSUE THREAD

**Issue by chetanSrajiv** [cucumber/cucumber-jvm#2050]
Json files generated after upgrading to Cucumber-JVM 6.0.0 does not attach screenshots to Cucumber html reports generated through 'npm cucumber-html-reporter' plugin 
Note: not just cucumber reports ,everying that are part of hooks are not displayed (eg. scenario.log("mymessage"), screenshots)
no npm plugin is able to generate cucumber reports with screenshot from these json files (probably json file format is now changed for latest version of cucumber-jvm
attaching JSON file that is generated after upgrading to CUCUMBER-JVM 6.1.1
[cucumber-report.zip](https://github.com/cucumber/cucumber-jvm/files/4924625/cucumber-report.zip)
)

**Context & Motivation**

generating cucumber reports through npm plugin is much easier and faster (_easy to install npm and few lines of javascript would generate reports_) when compared using maven/gradle plugins in docker container images. now this cucumber-reports are generated without screenshot for tests which is not ideal for debugging. this issue is happening only for latest cucumber-jvm. 

**Screenshots**
![image](https://user-images.githubusercontent.com/13467788/87537000-93d8df80-c6b7-11ea-980c-dbeece4063aa.png)

**Your Environment**
 - cucumber-jvm [e.g 6.1.1]
 - windows 10
 - cuucmber-html-reporter [5.2.0]

**Additional context**
able to generate reports through maven-cucumber-reporting only.
[cucumber-html-reporter.zip](https://github.com/cucumber/cucumber-jvm/files/4924697/cucumber-html-reporter.zip)

**Comment by mpkorstanje** [comment]
So at a glance this sounds like a problem with the `cucumber-html-reporter` which is a different project and maintained by different people. Now it might be that a change in `cucumber-jvm` caused this but you're not showing what that change might be. 

Can you provide the json produced before and after upgrading Cucumber? When dealing with attachments/log messages please keep them minimal. There is no point in including several MBs of base64.

**Comment by mpkorstanje** [comment]
Please feel free to reopen if you can provide additional information.

**Comment by chetanSrajiv** [comment]
Hi @mpkorstanje  thanks for your response.
as you requested i am uploading 2 json files one generated with CUUCMBER-JVM 2.4.0 and another with 6.0.0

[JsonforCucumberJVM.zip](https://github.com/cucumber/cucumber-jvm/files/4931894/JsonforCucumberJVM.zip)

**Comment by chetanSrajiv** [comment]
> Please feel free to reopen if you can provide additional information.
Unable to reopen
