### ISSUE TITLE
Cucumber plugin for setting up a context before every test step

### ISSUE THREAD

**Issue by agolubev81** [cucumber/cucumber-jvm#2052]
Hello, can Cucumber plugins be used for setting some context before actual step is executed? 

For instance, I have a requirement to integrate tests with 3rdparty framework which is responsible for logging and error handling. Ideally all test-related information should be available to that integration code, which can be implemented as AOP btw, including text with test step. Will plugins allow to do that ? 

My concern is that plugins API is event-based, unlike hooks, and thus order of test start and end events might be not exactly "around" actual test execution, which is important for managing context.

I'm aware about existing tickets https://github.com/cucumber/cucumber-jvm/issues/1805 for adding step information into hooks, which seems quite straight forward approach for my case, but it's not implemented yet and on other hand plugins  are proposed as alternative.

**Comment by mpkorstanje** [comment]
In brief, no. events are not guaranteed to be provided to the plugin around the invocation of a step. For example when implementing the `EventListener` interface and executing scenarios in parallel, all events will be offered in canonical order to the plugin after test execution has completed. The `ConcurrentEventListener` does not suffer from this problem but also does not guarantee that you'll be able to use `ThreadLocal` to share data between your step execution and the plugin.

Now at a glance it sounds like you already have solution in mind and are looking for help implementing that solution. However I also get the impression that you have not explained your actual problem. This phenomenon is called the [XY-Problem](http://xyproblem.info/).

So which framework are you using? Why do you need invoke around guarantees from the plugin? What problem would these solve?

> I'm aware about existing tickets #1805 for adding step information into hooks, which seems quite straight forward approach for my case, but it's not implemented yet and on other hand plugins are proposed as alternative.

It's open source. If nobody cares enough to implement it, it doesn't get done. Are you looking to submit a pull request?

**Comment by agolubev81** [comment]
> So which framework are you using? Why do you need invoke around guarantees from the plugin? What problem would these solve? What data are you trying to share between the step and plugin and why?
-  The framework is proprietary
-  Logging and error handling are to be delegated to the framework 
-  Integration is a must requirement (problem yeah :)
-  Info about step definition and java method should be available. 

Let's look at the example (it's a not a real but conceptually very close):
```
@When("example step is executed with parameter {string}")
public void example(String parameter) {
  TestFramework.logTestStart("test step: {} , method : {}", 
    String.format("example step is executed with parameter %s", parameter) , 
    "example()");
  try {
// actual test code 
  } catch (Throwable th) {
    TestFramework.handleCriticalException("%s", th);
  }
  TestFramework.logTestEnd("test step: {} , method : {}", 
    String.format("example step is executed with parameter %s", parameter) , 
    "example()");
}
```
So we need both cucumber step and java test methods details. It would be nice to decouple the actual code from integration aspects:
```
@When("example step is executed with {string}")
public void example(String parameter) {
// actual test code 
}
```
AOP with Cucumber hooks would allow to do such that easily if step information from Gherkin is accessible. Taking text from annotation and replace parameters with values during interception is also possible, but it would be more convenient to access text from Gherkin step directly and use as is, otherwise custom data types could be another challenge.

>It's open source. If nobody cares enough to implement it, it doesn't get done. Are you looking to submit a pull request?

Not yet, but could be an option.

**Comment by mpkorstanje** [comment]
From your example I don't think there is a reason not to use the `ConcurrentEventListener`. You are not using any information that isn't already provided by Cucumber.

You can access:
 - step text via: `TestStepStarted -> PickleStepTestStep -> Step -> Text`
 - method name via: `TestStepStarted -> TestStep -> CodeLocation`
 - arguments via: `TestStepStarted -> PickleStepTestStep -> DefinitionArgument` and `TestStepStarted -> PickleStepTestStep -> Step.Argument`
 -  exceptions via:  `TestStepFinished -> Result -> Error`

If your framework also adds a timestamp, you'll have to change the framework to allow providing time stamps which can be obtained via `TestStepStarted -> Instant`.

**Comment by mpkorstanje** [comment]
> TestFramework.logTestStart

I would be careful about considering a single step a test. When using Cucumber a scenario is considered of multiple steps. So multiple methods together are one test. This is quite unlike other frameworks say JUnit.

**Comment by agolubev81** [comment]
Thanks for your prompt feedback! 

I still have a feeling that my need is a bit more than creating a report, but the described plugin functionality fully covers the example needs so I have no arguments for not trying it :)

**Comment by agolubev81** [comment]
> 
> 
> > TestFramework.logTestStart
> 
> I would be careful about considering a single step a test. When using Cucumber a scenario is considered of multiple steps. So multiple methods together are one test. This is quite unlike other frameworks say JUnit.

Yes, and sounds like another advantage of plugins since it's possible to execute custom code in different scopes : methods, scenarios.

**Comment by mpkorstanje** [comment]
Let me know if you can work out what there might be missing.
