### ISSUE TITLE
Pass null value through feature file

### ISSUE THREAD

**Issue by Akash-Narang** [cucumber/cucumber-jvm#2055]
I have created a method and I am using .replace to update "Movement_Type" in the json file
I send this field from feature file as other actions are dependant on it.
Now Movement_Type is a mandatory field
I am not able to pass null value from the feature file to check the mandatory field validation

**Comment by mpkorstanje** [comment]
Feature files are written in human language. And people generally speaking don't talk about null values. They might say a field is empty, or left blank. So you'd do something like this:

```feature
Scenario: A form field is left blank
  Given a person who's first name is "Jack"
  And his last name is left blank
```

```java
@Given("a person who's first name is {string}")
public void given_first_name(String firstName){
   person.setFirstName(firstName);
}

@Given("a his last name is left blank")
public void given_last_name(){
   person.setLastName(null);
}
```

Now  that said, I don't really your question or what your problem might be here. Perhaps you can start by asking a co-worker, a colleague or a friend instead.  The issue system of an open source library is not the best place to get help with general programming problems.
