### ISSUE TITLE
Unable to obtain Spring context with @CucumberContextConfiguration

### ISSUE THREAD

**Issue by EmkaMk** [cucumber/cucumber-jvm#2060]
**Describe the bug**
Hi! We are migrating from cucumber 5 to 6 and decided to use the new annotation @CucumberContextConfiguration
 to setup the test configuration. Unfortunately either something in the scarce documentation is lacking, either we are doing something wrong or there is some bug since we are using the latest version, 6.2.2

**Expected behavior**
Adding @CucumberContextConfiguration together with @SpringBootTest should be enough according to [here ](https://github.com/cucumber/cucumber-jvm/pull/1911/commits/bc2962150f7142082e2def3dc213bd50fe0f98a0) and [here](https://community.smartbear.com/t5/Cucumber-Open/How-to-share-the-Spring-Boot-context-between-steps-in-cucumber/td-p/201696)
With this configuration, we are unable to Autowire other spring beans into the test classes. We get the following exception : 
Error creating bean with name.... Unsatisfied dependency expressed through field

**Context & Motivation**
Its multi module spring boot application. The module for integration tests ( which uses cucumber ) has only test implementation,not source. The starter class is in another module ( if that makes any difference ). 
Using java 11 with cucumber 6.2.2 . Added are screenshots of the configuration : 

**Screenshots**
![image](https://user-images.githubusercontent.com/9258377/87969671-dc7f0700-cac2-11ea-85dc-8ce64aa4d8b0.png)
![image](https://user-images.githubusercontent.com/9258377/87969719-f15b9a80-cac2-11ea-89c6-c90f908a38a5.png)
![image](https://user-images.githubusercontent.com/9258377/87969737-fd475c80-cac2-11ea-9ce3-15ca4f98b774.png)
![image](https://user-images.githubusercontent.com/9258377/87969760-0801f180-cac3-11ea-8e12-ae1bd3b2ea95.png)

**Your Environment**
 - Versions used 6.2.2
 - Operating System and version Windows 10
 - Build tool  Apache Maven 3.6.2

**Comment by mpkorstanje** [comment]
At a glance I don't see any obvious problems.

However screenshots are rather hard to read. For future reference please copy paste your code. You can [use markdown to for syntax highlighting](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown). To get a textual representation of a directory tree, you can use the `tree` command. 

For now, could you provide your project as a minimal reproducer, preferably in the form of a github repo?

Alternatively you may benefit from looking at this working example:

https://github.com/mpkorstanje/cucumber-spring-boot-parallel

**Comment by mpkorstanje** [comment]
And it comes to might that it might be worth checking if a JUnit test with the same context configuration boots up. I reckon the application context does not contain the beans you are trying to auto wire.

**Comment by EmkaMk** [comment]
Unfortunately I cannot share the code, but I will try to reproduce this issue on a small project and share it with you. 
The issue is indeed with the application context, but this was working code with cucumber 5, we just switched to 6 and tried to use the new annotation when we got this issue. I will update you during the day with a small git repo.

**Comment by mpkorstanje** [comment]
Then I suspect you were using the fall back application context rather then the one you've defined now. This fall back was deprecated in 5.5 and you may have missed the logged warnings.

Might be worth reading:

 - https://github.com/cucumber/cucumber-jvm/blob/main/release-notes/v5.1.0-v5.7.0.md#v550-a-better-way-to-configure-the-application-context-in-cucumber-spring
- https://github.com/cucumber/cucumber-jvm/blob/main/release-notes/v6.0.0.md

**Comment by EmkaMk** [comment]
@mpkorstanje I will take a look at the documentation you provided.
In the meanwhile, I created a small repo and I did my best of reconstructing the project setup. I still get the same issue. [Here ](https://github.com/EmkaMk/cucumber6) you can take a look. 
All I could find in the documentation is that it is enough to have class which will have both @CucumberContextConfiguration
and Spring Context configuration, such as @SpringBootTest ( in the sample code that is SpringIntegrationTestBase class).
Are we missing something obvious in the configuration?

**Comment by mpkorstanje** [comment]
So the `Application` class is in a different package from your tests. By default a `@SpringBootApplication` will component scan the package of the annotated class. Because this package is different from the packages in your test project the `@Component` annotated classes are not discovered.

This doesn't have to be problem but since you do not add these beans in any other way to the application context they can not be auto wired.

One way to add these beans would be:

```
@SpringBootTest(classes = {
        Application.class, 
        SpringIntegrationTestBase.Configuration.class},
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@CucumberContextConfiguration
public class SpringIntegrationTestBase {

    @TestConfiguration
    @ComponentScan("com.example.util")
    public static  class Configuration {

    }

}
```

Though which ever way you chose, make sure to annotate the beans with `@ScenarioScoped` to avoid sharing state between tests.

**Comment by mpkorstanje** [comment]
That said, this doesn't appear to be a bug in Cucumber but rather a problem in the way your Spring Boot tests are setup and it might be worth referencing the note from the read me for this:

> [spring/README.md](https://github.com/cucumber/cucumber-jvm/tree/main/spring#configuring-the-test-application-context)
> Note: Cucumber Spring uses Spring's `TestContextManager` framework internally.
> As a result a single Cucumber scenario will mostly behave like a JUnit test.
> 
> For more information configuring Spring tests see:
>  - [Spring Framework Documentation - Testing](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/testing.html)
>  - [Spring Boot Features - Testing](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-testing)

**Comment by mpkorstanje** [comment]
Now one question remains. 

That this worked for you in v5 is rather puzzling. I suspect that you were not using `cucumber-spring` to start and test an existing spring application but rather that you've created a separate application context to hold your test utilities.

If this is what you intended to do you should not use `@SpringBootTest` but rather a `@ContextConfiguration` to create a new application context.

```
package com.example;

import io.cucumber.spring.CucumberContextConfiguration;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.test.context.ContextConfiguration;


@ContextConfiguration(classes = SpringIntegrationTestBase.Configuration.class)
@CucumberContextConfiguration
public class SpringIntegrationTestBase {

    @TestConfiguration
    @ComponentScan("com.example.util")
    public static  class Configuration {

    }
}
```

**Comment by EmkaMk** [comment]
Hi @mpkorstanje ,thanks for the input. We actually use `cucumber-spring` together with Cucumber 5 in all our projects. We have 5 other projects with the same setup ( multimodule maven applications ). In almost all of them the integration-test module where we use cucumber uses Application class from another module. We used @SpringBootTest to start and test the application. 

I tried the approaches you have provided, first things first I changed the layout of the packages to be consistent. Only the first setup with the additional component scan works for us since we don't want to create another context for the utility classes if they can be identified with the component scan. 
So this solution works and the tests are running ok now. Thanks for your input :)

**Comment by mpkorstanje** [comment]
> I tried the approaches you have provided, first things first I changed the layout of the packages to be consistent. Only the first setup with the additional component scan works for us...

That is odd. I could resolve the problem by making the packages consistent in your MCVE. If you follow springs assumptions you shouldn't need much configuration at all.
