### ISSUE TITLE
Add "Rule" to list of taggable keywords since it covers multiple Scenarios/Examples.

### ISSUE THREAD

**Issue by Bogghead** [cucumber/cucumber-jvm#2071]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Bogghead** [comment]
The ability to test a _subset_ of the rules in a feature would be a value-add.

**Comment by mpkorstanje** [comment]
Closed in favor of:

https://github.com/cucumber/cucumber/issues/1123
