### ISSUE TITLE
Data Tables stopped working with maven.

### ISSUE THREAD

**Issue by Ash4669** [cucumber/cucumber-jvm#2077]
Hello, would anyone be able to help me with this error? I don't have a clue how to fix it.

**Describe the bug**
When I run a standard test with the IntelliJ IDE I have no problems, but when running the tests with mvn from the terminal, I receive the following error:
``` 
Don't know how to convert "value" into net.jodah.typetools.TypeResolver$Unknown.
Try writing your own converter:

@cucumber.deps.com.thoughtworks.xstream.annotations.XStreamConverter(UnknownConverter.class)
public class Unknown {}
```

**To Reproduce**
Whenever I run a test with a data table by using the command:
```
mvn clean verify -Dcucumber.options="--tags @tagWithDataTableTest"
```

**Screenshots**
<img width="1729" alt="Screenshot 2020-08-05 at 15 45 20" src="https://user-images.githubusercontent.com/45691732/89427048-b304e300-d732-11ea-9975-c47cb605810c.png">

**Your Environment**
 - Versions used [e.g 5.0.0]
- IntelliJ IDEA 2020.1.1 (Community Edition)
- -Build #IC-201.7223.91, built on April 30, 2020
- -Runtime version: 11.0.6+8-b765.40 x86_64
- -VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- -Non-Bundled Plugins: uk.co.itmoore.intellisubsteps, gherkin, cucumber-java
- - Build tool [e.g. Apache Maven 3.6.0]
- macOS 10.15.5

**Comment by mpkorstanje** [comment]
You are using Cucumber v1.x.x. This version depends on the XStream library which is not compatible with Java 9+. So presumably you are using a different JVM when running with Maven. Consider upgrading your version of Cucumber or downgrading your version of Java.

Also for future reference: do not use screenshots for text. They're impossible to read on mobile.
