### ISSUE TITLE
Why io.cucumber.junit.Cucumber class is FINAL ?

### ISSUE THREAD

**Issue by DiptangshuS** [cucumber/cucumber-jvm#2078]
**Describe the bug**
Class `io.cucumber.junit.Cucumber` is now marked as Final. So no custom Runner can be created for Cucumber-JUnit for project needs. In earlier versions till **4.8.0**, it was not final. Please mark it non-FINAL

**Expected behavior**
**io.cucumber.junit.Cucumber** class should be **non-Final**

**Context & Motivation**

no custom Runner can be created for Cucumber-JUnit for project needs

 - Versions used [e.g **6.4.0**]
 - Build tool [e.g. Apache Maven 3.6.0]

**Comment by mpkorstanje** [comment]
Extension is something that should be designed for. This ensures the extension points can be documented and tested. This inturn ensure we don't break an extension by accident.

Could you elaborate on what are you trying to achieve by creating a custom runner?

**Comment by GeekAni** [comment]
@mpkorstanje - Yes we have custom annotation to use with Test methods, the values/parameters of which we fetch from the Cucumber EventListener. 

This is **only for Cucumber-JUnit** 

Thus, we also had to write a Custom Runner class, by extending Cucumber provided Runner class. Earlier that "**Cucumber**" class was _not_ final, but **starting from 5.x** it is FINAL. That's why we cannot extend it anymore.

Our code:

**RUNNER class** (this will be _used by TEST class in @RunWith_ annotation):

```
public class CustomCucumberJunitRunner extends Cucumber {
        public CustomCucumberJunitRunner (Class clazz) throws InitializationError {
               super (CustomCucumberListener.setTestRunner(clazz);
        }
}
```

**LISTENER class**:

```
public class CustomCucumberListener implements EventListener {
      private static volatile Class classRunner;
      private EventHandler <TestRunStarted> testRunStarted = 
                         event -> {
                                // do our custom stuff, reading values/properties from custom annotation, etc.
                         };

      public static Class setTestRunnerClass(Class clazz) {
                 classRunner = clazz;
                 return clazz;
      }

     @Override
      public void setEventPublisher (EventPublisher publisher) {
                 publisher.registerHandlerFor(TestRunStarted.class, testRunStarted);
      }
}
```

Could you please make the Classes in `io.cucumber.junit` **Non-FINAL** ?

Thanks !

**Comment by mpkorstanje** [comment]
Have you considered reading the settings from a properties file rather then an annotation? This would avoid the custom runners as well as using a static variable to pass information around. Cucumber supports passing a single argument to a plugins constructor for example:

```java
@RunWith(Cucumber.class)
@CucumberOptions(plugin = "com.example.MyPlugin:settings1.properties")
public class RunCucumberTest1 {

}

@RunWith(Cucumber.class)
@CucumberOptions(plugin = "com.example.MyPlugin:settings2.properties")
public class RunCucumberTes2t {

}

public class MyPlugin {

   public MyPlugin(String config){
    // read config from either settings1 or 2 here
   }
}
```

**Comment by Nihnyoki** [comment]
Hello @mpkorstanje ,

I am also in support of @DiptangshuS on this request, I have the need to extend Cucumber.class to listen to TestStepStarted.class and TestStepFinished.class so I can get stepDefs names to write in a report. I am using cucumber version "7.12.0". I am happy to try an ulternative method if you can propose one?

**Comment by jkronegg** [comment]
@Nihnyoki listening to TestStepStarted/TestStepFinished and generating reports seems something to be done using a plugin.

You reference the custom plugin in your cucumber test class:

    @Suite
    @IncludeEngines("cucumber")
    @SelectClasspathResource("features")
    @ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value="mypackage.MyPlugin")
    public class RunCucumberTest {
    }

Then you write a plugin:

    package mypackage;
    import io.cucumber.plugin.EventListener;
    import io.cucumber.plugin.Plugin;
    import io.cucumber.plugin.event.EventHandler;
    import io.cucumber.plugin.event.EventPublisher;
    import io.cucumber.messages.types.Envelope;
    
    public class MyPlugin implements EventListener, Plugin {
        private final EventHandler<Envelope> testParameterTypeHandler = (event) -> {
            // do something with the envelope, e.g. collect the events (it contains TestStepStarted/TestStepFinished events and a lot of other stuff)
            if (event.getTestRunFinished().isPresent()) {
                // write the report
            }
        };
    
        public void setEventPublisher(EventPublisher eventPublisher) {
            eventPublisher.registerHandlerFor(Envelope.class, this.testParameterTypeHandler);
        }
    }
