### ISSUE TITLE
cucumberOptions-tags: Type mismatch error for tags in latest cucumber version

### ISSUE THREAD

**Issue by jay14687se** [cucumber/cucumber-jvm#2091]
## Summary

When I try to give tags under CucumberOptions i get an error for tags saying cannot convert from String[] to String, not sure why. this issues is not present in version 5.7.0.

## Expected Behavior
No error should come when we provide tags in cucumber option in the format tags = {"@AddPlace"}

## Current Behavior

tags = {"@AddPlace"} resulting Type Mismatch error

~~~
~~~

## Steps to Reproduce (for bugs)

1. Make a Runner file and add tags under Cucumber Options using cucumner-junit 6.4.0

## Context & Motivation
Trying to create a BDD framework using Cucumber for API Testing

## Your Environment

* Version used: cucumber-junit JAVA JVM, 6.4.0
* Operating System and version: Windows 10

**Comment by mpkorstanje** [comment]
You can't use multiple tag expressions any more. Its hard to understand for people how they're combined. Instead try using a single tag expression `tags = "@Cucumber and not @Gherkin or @Zucchini"`. The javadoc should tell you as much.

https://github.com/cucumber/cucumber-jvm/blob/v6.4.0/junit/src/main/java/io/cucumber/junit/CucumberOptions.java#L71-L78

**Comment by jay14687se** [comment]
@mpkorstanje Thank you for the clarification. Will start using single tag expression going forward.
