### ISSUE TITLE
Allow more truthy values for `CUCUMBER_PUBLISH_ENABLED`

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#2095]
I tried `CUCUMBER_PUBLISH_ENABLED=1` and nothing was published. Any value should be considered truthy except `/false|no|0/`. This is how it's implemented in Cucumber-Ruby.

**Comment by mpkorstanje** [comment]
The convention in Java is `"true".equalsIgnoreCase(s)`. This convention is followed by all major frameworks (JUnit 5, Spring, ect). And according to the principle of least surprise Cucumber JVM should follow suit.

When it comes to documenting this cross platform I would suggest using only `true` and `false`. This is always correct. Any other values are up to the conventions used by that language.

**Comment by aslakhellesoy** [comment]
I get that it's the convention for code and system properties which are Java-specific, but for environment variables I'm not so sure.

When people specify an environment variable, they don't know how we've implemented the processing of that variable. How would they know it's processed with `"true".equalsIgnoreCase(s)`?

Can you give me a concrete example where the proposed change would yield an unexpected result?

**Comment by aslakhellesoy** [comment]
And where can I read more about those conventions in JUnit 5 and Spring?

**Comment by aslakhellesoy** [comment]
I found the JUnit 5 one: https://junit.org/junit5/docs/5.0.2/api/org/junit/platform/engine/ConfigurationParameters.html#getBoolean-java.lang.String- - as you said.

**Comment by aslakhellesoy** [comment]
What you said about Spring's conventions appears to be contradicted by this:

https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/convert/support/StringToBooleanConverter.java

**Comment by mpkorstanje** [comment]
`"true".equalsIgnoreCase(s)` is the implementation of `Boolean.parseBoolean` in Java. So I'm not sure how to make a more compelling argument. What I'm looking for however is a compelling reason to add any complexity beyond `Boolean.parseBoolean`. The important part is that `"true" -> true` and `"false" -> false`. The way other values are parsed doesn't seem important enough to justify the added complexity.

> What you said about Spring's conventions appears to be contradicted by this:

The `StringToBooleanConverter` is used as a general purpose converter. It also differs from both Java and Ruby. It throws an illegal argument exception when a value was not one of the the eight expected true or false values.

A better example would be [SpringProperties.java]( https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/SpringProperties.java#L134) and if you [search for `parseBoolean` in the spring-projects](https://github.com/search?q=org%3Aspring-projects+parseBoolean&type=Code) you'll find that it is widely used. There are a few more exceptions that accept values other then `"true"` as `true`. However those would be the exception to the rule and as a result using anything but `"true"` would be suspect.

**Comment by rmannibucau** [comment]
This feature sounds really important because it is not about code but user facing configuration - and potentially not technical people - so it should probably be more flexible than languages defaults - and to be cucumber friendly it should be i18n no? ;)

If it helps, Deltaspike has also a kind of extended enum for "true" in its [TypeResolverImpl](https://github.com/apache/deltaspike/blob/da93fe7882bfaaa816daba7a71401a21823d4e92/deltaspike/core/impl/src/main/java/org/apache/deltaspike/core/impl/config/TypedResolverImpl.java#L481).

Interesting thing is that it is sane to whitelist "truthy" values but considering that everything which is not falsy is true sounds more risky - if you put it in an unknown spoken language then it is wrong - so maybe the opposite can be less risky (assuming enabling the publishing when undesired is worse than not enabling it when desired)?

**Comment by mpkorstanje** [comment]
> This feature sounds really important because it is not about code but user facing configuration - and potentially not technical people - so it should probably be more flexible than languages defaults - and to be cucumber friendly it should be i18n no? ;)

Given that the context in which the properties are used is both technical and predominantly English I would consider the configuration of Cucumber to be strictly aimed at English speaking people with some programming experience. Unlike say the feature files themselves.

> Interesting thing is that it is sane to whitelist "truthy" values but considering that everything which is not falsy is true sounds more risky

Good point!

**Comment by aslakhellesoy** [comment]
Who can give me a concrete example where the behaviour in this PR would give a surprising or unexpected result?

**Comment by rmannibucau** [comment]
@aslakhellesoy put "no" in french (non), you get "true" instead of false which means you enable a feature which is requested to be disabled. As mentionned, I think it is worse than not enabling a feature on a wrong "true" value.

**Comment by mpkorstanje** [comment]
> Who can give me a concrete example where the behaviour in this PR would give a surprising or unexpected result?

Can you give me a reason to accept the added complexity?

**Comment by aslakhellesoy** [comment]
I already did. It's at the first line in this issue. I'll elaborate for clarity:

Environment variables were introduced in UNIX in the late seventies, and the way C code and shell scripts behave is that *any* value of an environment variable resolves to a truthy value. This is because the stdlib [getenv](https://man7.org/linux/man-pages/man3/getenv.3.html) function either returns a string (truthy) or `NULL` (falsy).

This works fine in most cases. If you want falsy, just don't specify the variable. If you want truthy, specify *any* value. This means `0`, `1`, `true`, `false`, `whatever` are *all* truthy.

This is why I was surprised when `1` was not interpreted as truthy. It deviates from standard UNIX behaviour, and the underlying programming language is irrelevant.

The fact that *all* values are truthy might not be intuitive to some, but it's the way environment variables are designed to work. Some tools have adopted conventions that deviate from the original behaviour by interpreting a small set of values as falsey. The most common ones seem to be `0`, `false` and `no`.

Git for example, interprets `0` and `false` as falsey. `1` and `true` as truthy. Any other value is an error. (Try `GIT_TRACE=1 git status`).

For users who are using the values `true` and `false`, this change will not alter the behaviour.

Users who have specified `1` or `banana` will now get a truthy value instead of a falsey one.

Are you suggesting there are users out there who might have been expecting falsey for `1` and other non-`true` strings that will now be confused about the new behaviour? 

(BTW, I agree we should not attempt to internationalise this).

**Comment by rmannibucau** [comment]
It is common to alter script adding a meaningless char to come from a truthy to falsy value (true => true_). Current impl makes both true which is unexpected.
Also unix behavior is true but good practise is to test the value so not sure we should stick to inherit something inherited from years ago and no more up to date.

**Comment by aslakhellesoy** [comment]
> Current impl makes both true which is unexpected.

Unexpected to you perhaps, but nonetheless correct according to a 50 years long tradition of environment variables.

**Comment by aslakhellesoy** [comment]
From vincent: https://theburningmonk.com/2020/04/hit-the-6mb-lambda-payload-limit-heres-what-you-can-do/

**Comment by rmannibucau** [comment]
@aslakhellesoy hmm, I only saw 1 used by some specific language guys but saw true_/truee/... (any derivative of true) by most dev and ops so guess it can be a fifty/fifty thing? Doesn't it mean it should fail when the truthy/falsy value is unknown to avoid surprises and enforce a consistent behavior with the config?
