### ISSUE TITLE
Upgrading to Cucumber 6.x.x does not cause build to fail in gradle even when scenarios fails

### ISSUE THREAD

**Issue by soumyarao82** [cucumber/cucumber-jvm#2098]
**Describe the bug**
Upgrading to Cucumber 6.x.x does not cause build to fail in gradle even when scenarios fails. The build.gradle task has not been changed. Only upgrading the cucumber version to 6.4.4 and Junit version 5.3.0 makes Gradle behave differently and does not Fail the build in any case

**To Reproduce**
1. We have 
Steps under src/test/java/steps
Runner class under src/test/java
2. The build.gradle has the following information
`cucumberVersion ='6.4.0'
junitVersion = '5.3.0`
imported the dependency for 
io.cucumber:cucumber-core
io.cucumber:cucumber-java
io.cucumber:cucumber-java8
io.cucumber:cucumber-junit
io.cucumber:cucumber-spring
3. We have added a test task which says
test{
system.propert "x.x.x", System.getProperty("x.x.x")
//have few more system properties
}
task cucumber(dependsOn: test{
}

4. I have purposefully made few of the cuke tests to fail

**Expected behavior**
On running the gradle build, the cuke tests should fail resulting in complete build failure

**Actual behavior**
On running the gradle build, the cuke tests fail but the build says it is SUCCESS
**Context & Motivation**

**Comment by mpkorstanje** [comment]
I can't reproduce this with the https://github.com/cucumber/cucumber-java-skeleton can you provide and MCVE in the form of a github repo? Please take care to remove everything that isn't relevant to reproducing the problem. For example if your system properties are do not influence this failure, do not include them.

**Comment by soumyarao82** [comment]
@mpkorstanje  I am not able to provide in the form of gitHub as it is restricted.

What is see is when I had Cuke version 4.8.0, with same gradle task, I would get expected results. Now as soon as I upgrade to 6.4.0, I see that the Build behave differently without me making any changes. If I revert the version I see correct behaviour.

In 6.4.0 version, even if the unit tests fails, it reports Build Failed correctly.  If the unit tests passes and if any of the cuke tests fail, it ignores the cuke tests failure and reports a BUILD Success.

**Comment by mpkorstanje** [comment]
If you can upload an MCVE as a zip file that may also work. And if that doesn't work you could copy the individual files into a comment. 

But without a minimal reproducer I can't help you.

**Comment by s4ik4t** [comment]
Hi @mpkorstanje should there be a label for e.g. `waiting-for-author` to label issues where input awaited from submitter? This might be useful to filter out such issues.

**Comment by soumyarao82** [comment]
@mpkorstanje  sorry for the delay in providing feedback. The build issue was caused due to configurations in jenkins and way we were reading the report. In Jenkins --> configure --> Publish Junit test result report --> Test Reports XMLs
resolved this issue
