### ISSUE TITLE
I am eagerly hope to there is a hook before running each feature for example: @BeforeFeature @AfterFeature

### ISSUE THREAD

**Issue by shellphxiao** [cucumber/cucumber-jvm#2112]
Currently, the cucumber-jvm only support @Before @After which is used by every Scenario. But in my test features, almost every features have 80 scenarios, and only the first scenario need execute  @Before or @After hook. therefore, It takes a lot of time to open and log in the browser, If the feature level hooks can be applied, Assume there are like @BeforeFeature @AfterFeature hook , then each scenario in one feature will run in one browser, which will save about 70% of testing time, that's my requirement, thanks.

**Comment by mpkorstanje** [comment]
A features is not an execution unit. So having hooks around it wouldn't make much sense. Additionally each scenario should be independent. Sharing state (i.e. a browser) between them would break this isolation. 

Now browsers are slow to start up so you may want to consider using an [object pool pattern](https://en.wikipedia.org/wiki/Object_pool_pattern) to reuse browser. This will allow your scenarios to check out a clean browser from the pool or create one if the pool doesn't have any yet. Upon completion of the scenario the browser can be returned to the pool and cleaned of its state.  

The object pool pattern has additional benefits when using a limited resource such as remote webdrivers. The size of the pool can be limited to the size of the remote webdriver instances. When the pool runs dry while executing scenarios in parallel the scenarios will simply wait for a browser to become available.
