### ISSUE TITLE
Is it possible to freely choose to run cucumber by feature or scenario level and implement failed retry functions

### ISSUE THREAD

**Issue by jiawade** [cucumber/cucumber-jvm#2113]
I would like to:
![Snipaste_2020-09-05_12-30-45](https://user-images.githubusercontent.com/66766526/92297619-d7dbb880-ef73-11ea-8c5c-948305ad8c89.png)

**Comment by mpkorstanje** [comment]
Please don't use screen shots to report problems with code. [You can find a long list of reasons here](https://meta.stackoverflow.com/questions/285551/why-not-upload-images-of-code-errors-when-asking-a-question).

That said. No this is not possible. Parallel execution is handled by a combination of JUnit and Surefire. Neither support parallel execution of `ParentRunner` (i.e. @RunWith(Cucumber.class)) implementations below the first level.

**Comment by danyflorez** [comment]
Hi, I'd like to have a guidance on how to develop the retry I have the time to work on it and make a PR
