### ISSUE TITLE
Chinese Scenario name lead to messy code

### ISSUE THREAD

**Issue by fanchaofree** [cucumber/cucumber-jvm#2114]
I start my cucumber test case like this :
![image](https://user-images.githubusercontent.com/45627974/92318134-5f8bfa80-f03a-11ea-9940-2c9eab87583e.png)

execution config as following:
![config](https://user-images.githubusercontent.com/45627974/92318145-8a764e80-f03a-11ea-8088-cd170a4a1ef4.png)

when the case run, I find that the input argument leads to messy code : 
![main](https://user-images.githubusercontent.com/45627974/92318151-b1cd1b80-f03a-11ea-9b2d-b78272affd87.png)

and the messy code finally results in the regex errror:
![image](https://user-images.githubusercontent.com/45627974/92318177-10929500-f03b-11ea-97dd-3fb7791695ea.png)

I have ensured that all the related file encodings is UTF-8. 
My Idea is 2020.2.1 community Edition. And the cucumber is installed after 9/1/2020.

**Comment by mpkorstanje** [comment]
Heya, please don't use screen shots to report problems with code. [You can find a long list of reasons here](https://meta.stackoverflow.com/questions/285551/why-not-upload-images-of-code-errors-when-asking-a-question). In this instance I can't easily copy the problematic text to see if I can reproduce the problem.

That said, at a glance it would appear that IDEA doesn't pass the string correctly to Cucumber main method. This means Cucumber isn't involved and you'll have to work out how to get IDEA to correctly pass UFT-8 Strings to java on your own.

**Comment by fanchaofree** [comment]
Thanks for you advice.
It is the OS region configuration that leads to the problem above.
Control Panel\Clock and Region\Region to change the config.
*************************************************************
![image](https://user-images.githubusercontent.com/45627974/92340674-e352ef00-f0ed-11ea-8c90-2674ffd25017.png)
*************************************************************
