### ISSUE TITLE
Separate results for each example in Scenario Outline

### ISSUE THREAD

**Issue by aftabmannan** [cucumber/cucumber-jvm#2115]
Hi Team,

Is there a way to generate separate [html] results set for each example row for Scenario Outline in cucumber 6+. I needed to add custom logs after the scenario completes .

Currently, I see a single step set and each example marked in green

**Comment by mpkorstanje** [comment]
There is no such feature. However you can use the `Scenario` object in an `@After` hook to attach additional information to the report.
