### ISSUE TITLE
--publish: use banner provided by server

### ISSUE THREAD

**Issue by vincent-psarga** [cucumber/cucumber-jvm#2116]
The messages.cucumber.io server responds with the banner as part of the 202 pesudo-redirect response. We should use it instead of computing our own like we do in [cucumber-js#1424](https://github.com/cucumber/cucumber-js/pull/1424).

**Advantages:**
 - people can override CUCUMBER_PUBLISH_URL and no longer get a banner pointing to reports.cucumber.io
 - server implementation can provide their own banner
 - no need to release new cucumber-ruby when changing the wording/styling of the banner or location of the report web app
 - more consistency between cucumber implementations

**Comment by mpkorstanje** [comment]
At this point it might be good to duplicate the URL output stream and only use it for the publish plugin.

**Comment by aslakhellesoy** [comment]
Are you suggesting we remove the ability to specify a URL for arbitrary plugins, or are you suggesting we have 2 implementations of `URLOutputStream`?

**Comment by mpkorstanje** [comment]
For now duplicate it. In the long run, deprecate and remove it for arbitrary plugins. I don't see much value in abitrary uploads.

With Gitlab the file is uploaded to pages. Don't know how other CIs do it but I would expect a similar flow.

Or if the file server is remote I would expect people to upload the report with curl. I wouldn't expect anyone to implement a server and use the exact protocol we are creating right now.

**Comment by aslakhellesoy** [comment]
> With Gitlab the file is uploaded to pages

What do you mean?

**Comment by mpkorstanje** [comment]
Gitlab pages.

https://docs.gitlab.com/ee/user/project/pages/

**Comment by mpkorstanje** [comment]
Actual looks like this can be done without changing much of the protocol.
