### ISSUE TITLE
--publish banner does not mention junit-platform.properties

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#2117]
```
┌─────────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io    │
│ Activate publishing with one of the following:                              │
│                                                                             │
│ src/test/resources/cucumber.properties:    cucumber.publish.enabled=true    │
│ Environment variable:                      CUCUMBER_PUBLISH_ENABLED=true    │
│ JUnit:                                     @CucumberOptions(publish = true) │
│                                                                             │
│ More information at https://reports.cucumber.io/docs/cucumber-jvm           │
│                                                                             │
│ To disable this message, add cucumber.publish.quiet=true to                 │
│ src/test/resources/cucumber.properties                                      │
└─────────────────────────────────────────────────────────────────────────────┘
```

When using JUnit 5 the `cucumber.publish.quiet=true` should be added to `src/test/resources/junit-platform.properties`. Otherwise the banner is not suppressed.

**Comment by kanika-anetcorp** [comment]
How do I access the URL? Is there an API to do it?

**Comment by mpkorstanje** [comment]
See: https://github.com/cucumber/cucumber-js/issues/1458

**Comment by kanika-anetcorp** [comment]
No, but after pasting that variable in say: cucumber.properties, how will I use it?

Can I say: Reportbuilder.generateReport("<URL here>")

Could you elaborate?

**Comment by kanika-anetcorp** [comment]
> No, but after pasting that variable in say: cucumber.properties, how will I use it?
> 
> Can I say: Reportbuilder.generateReport("")
> 
> Could you elaborate?

Also: How do I email it? Most importantly

**Comment by mpkorstanje** [comment]
If you don't want to publish reports online you can use the standalone html formatter. It currently produces a single html file.

See: https://github.com/cucumber/cucumber-jvm/blob/main/release-notes/v6.0.0.md#improved-html-formatter

**Comment by kanika-anetcorp** [comment]
I'll see if I can use this.
But what I really want is to publish online and email the link 

For that I need to write Java code that knows the UI.

It's a super good reporting by the way

**Comment by mpkorstanje** [comment]
@aslakhellesoy sounds like a feature request :point_up:

**Comment by kanika-anetcorp** [comment]
> If you don't want to publish reports online you can use the standalone html formatter. It currently produces a single html file.
> 
> See: https://github.com/cucumber/cucumber-jvm/blob/main/release-notes/v6.0.0.md#improved-html-formatter

Is this as pretty as the one online?

**Comment by aslakhellesoy** [comment]
> Is this as pretty as the one online?

No, because our efforts on styling have been on the web app rather than the static report. They do share the same React’ components, so we may move the stylesheets from Cucumber Reports to the standalone HTML formatter.

**Comment by aslakhellesoy** [comment]
> But what I really want is to publish online and email the link

I assume you want to email the link so that others can discover the report.

As mentioned in https://github.com/cucumber/cucumber-js/issues/1458 we are working on better discoverability from within Cucumber Reports (stable overview url).

If we ship this, would you still want emails @kanika-anetcorp?

**Comment by kanika-anetcorp** [comment]
@aslakhellesoy your approach of doing it is two stepped.
Connect with token.
Connect with Git.
Get a better fit URL.

This is no doubt good for storing all reports in one place.

But for all general purposes, managers can get the link in their mailbox.

Something like
ggetReport().getLink().mailTo(XX);
