### ISSUE TITLE
Fail the build if there are CVE issues in the repo

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#2127]
The CI process should fail the build if dependabot or other have discovered a CVE alert in a (transitive) dependency

**Comment by aslakhellesoy** [comment]
This is going to be fun because Spring has many CVEs. We want to avoid this just becoming busywork.

**Comment by aslakhellesoy** [comment]
https://owasp.org/www-project-dependency-check/
https://github.com/jeremylong/DependencyCheck

**Comment by denim2x** [comment]
Hi - I'd like to start working on this. Is the bounty still available?

**Comment by aslakhellesoy** [comment]
Hi @denim2x it is indeed! We’ll pay anyone who implements this via opencollective (see the fund button at the top).

Do you think you could make it work for all languages?

**Comment by mpkorstanje** [comment]
Superseded by https://github.com/cucumber/cucumber/pull/1268
