### ISSUE TITLE
Resourcelocks does not work

### ISSUE THREAD

**Issue by boris779** [cucumber/cucumber-jvm#2129]
I'm using the `cucumber.execution.exclusive-resources.<tag-name>.read-write` but scenarios whith the same resource-tags are executed at the same time

1. Clone my repo from github 'https://github.com/boris779/CucumberJunit5ParallelExample' 
2. run `mvn clean verify` (parameters are in the propertiesfiles)
3. open the timeline report within the target folder to get a overview which scenario run in parallel with others
4. Scenario with @tag-a should not run at the same time

**Expected behavior**
Scenarios with @tag-a should not run at the same time

I also tried different parameters for strategy (fixed and dynamic)

**Screenshots**
![image](https://user-images.githubusercontent.com/10259016/94008643-a0f30880-fda3-11ea-90c3-12e1b5fe012c.png)

**Your Environment**
- Cucumber 6.7.0 
 - Maven 3.6
 - Tested on Ubuntu and Windows 10
 - Kotlin 1.4.10

**Additional context**
If I used it not correctly then I can help to complete the documentation with PR

**Comment by mpkorstanje** [comment]
Note the the spelling of `exclusive-resource**s**`

```
cucumber.execution.exclusive-resources.<tag-name>.read-write
```

You are using:
```
cucumber.execution.exclusive-resource.tag-b.read-write=resourceB
```

**Comment by adimusilek** [comment]
oh man! 
we were stumbling around for at least an hour and a half and didn't notice the typo!

Thank you so much @mpkorstanje

**Comment by boris779** [comment]
Thx for the quick response
