### ISSUE TITLE
Trying to get scenario exec status and test steps and its exec status after completion of each scenario though TestNg Listner

### ISSUE THREAD

**Issue by SakthiIsaiBharathi** [cucumber/cucumber-jvm#2136]
Hi,

I am trying to fetch the execution status of scenario and its test steps and test steps exec status.. I am doing this for capturing realtime executions status for our scripts.

I am able to find to get the scenario name and its execution status , test step names

But i am not able to get the teststep execution status.. can someone please guide on this.

![16013760742736731152896530494740](https://user-images.githubusercontent.com/47920071/94548576-9090d100-026e-11eb-9225-2a0cb009801f.jpg)

**Comment by mpkorstanje** [comment]
This is not possible with TestNG. TestNG does not support sub-test progress notifications. Consider using `@CucumberOptions(plugin="pretty")` instead to log the scenario progress.

Owh and don't share images of code. Please read:

https://meta.stackoverflow.com/a/285557/3945473

**Comment by SakthiIsaiBharathi** [comment]
@mpkorstanje - Pretty is we are able to get only after executions.. there are scripts we run for hours.. we want to track as realtime executions

**Comment by mpkorstanje** [comment]
Consider writing your own `Plugin`.  You use `@CucumberOptions(plugin="com.example.MyPlugin")` to enable it. See the pretty formatter for an example of how to do that.

https://github.com/cucumber/cucumber-jvm/blob/main/core/src/main/java/io/cucumber/core/plugin/PrettyFormatter.java

**Comment by SakthiIsaiBharathi** [comment]
@mpkorstanje Thanks mate.. If you dont find, do u have few mins to explain how to create a plugin and use it
