### ISSUE TITLE
Cucumber 6.8.0 and Junit5

### ISSUE THREAD

**Issue by tillias** [cucumber/cucumber-jvm#2137]
Hello folks,

Thanks a lot for a lot of work done and awesome product. Can you please advise me how to use 6.8.0 together with Junit 5 and Spring Boot?

I have tried following sample https://github.com/bonigarcia/mastering-junit5/blob/master/junit5-cucumber/pom.xml

```
@CucumberOptions(plugin = { "pretty" })
@ExtendWith(CucumberExtension.class)
public class SomeTest {
```

but CucumberExtension is not available anymore. Is there anywhere documentation available?

Also those dependencies make me crazy:
```
  <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-spring</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
```

There are so many transient ones. If you help me I can contribute with article of how to use Spring Boot + Junit5 + Cucumber. Or maybe there is already such a documentation available?

**Comment by mpkorstanje** [comment]
Extensions are a concept from JUnit Jupiter. Jupiter is a test engine that uses the JUnit Platform. Cucumber is a different test engine that also uses the JUnit Platform. Together with JUnit Vintage, JUnit Jupiter and the JUnit Platform form JUnit 5.

Have a look at:
 - https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine

**Comment by tillias** [comment]
Can you please advise where are the step definitions? I can launch it in intelliJ by running *.feature files. I also do have
```
@SpringBootTest
@CucumberContextConfiguration
@ActiveProfiles("test")
public class TestStepDefinitions {
    @When("Some condition")
    public void someCondition() {
        ...
    }
```

When I edit *.feature file in IntelliJ it doesn't see "Some condition" (autocomplete doesn't work)

When I run it with maven-surefire:
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test
```

**Comment by tillias** [comment]
There is of course junit-platform.properties in /src/test/resources with 
`cucumber.glue=my.package.where.TestStepDefinitions.is`

**Comment by mpkorstanje** [comment]
Try and make a regular unit test that boots tbe application first. You're probably missing the application class or you haven't annotated it with `@SpringBootApplication`.

Dunno about IDEA. Make sure it's up to date.
