### ISSUE TITLE
Run one SpringContext for all features or run one SpringContext for one feature

### ISSUE THREAD

**Issue by benjaminbatista** [cucumber/cucumber-jvm#2150]
Hello,

My Cucumber Tests are taking too much time. As seen in logs, the spring context is creating for each Scenario.

Is there a way to handle it for all features or at least for each feature?

I couldn't find anything about that in the cucumber documentation.

Thank you for your help.

**Comment by mpkorstanje** [comment]
Which version of Cucumber are you using?

**Comment by benjaminbatista** [comment]
Thank you for answering,

@mpkorstanje we are using the last version

**Comment by benjaminbatista** [comment]
We found out the solution !
It was an issue on WireMock that set DirtyContext for spring. 

We fixed it by using the last wiremock version.

Thank you
