### ISSUE TITLE
Incompatibility with Android Studio 4.1

### ISSUE THREAD

**Issue by matheusribeirozup** [cucumber/cucumber-jvm#2157]
**Describe the bug**
The plugin is experiencing compatibility issues with version 4.1 of Android Studio.

**To Reproduce**
1. Open the Android Studio IDE version 4.1
2. Install any version of [Cucumber for Java](https://plugins.jetbrains.com/plugin/7212-cucumber-for-java) plugin
3. Open any project in Android Studio IDE version 4.1
4. The plugin will not be displayed as installed and will not work

**Expected behavior**
The plugin should be displayed as installed and work correctly.

**Context & Motivation**
The plugin is extremely useful, it's a great tool! It is a fundamental part in the development of my projects, so it would be very positive to have it working correctly.

**Screenshots**
<img width="468" alt="Captura de Tela 2020-10-21 às 23 27 31" src="https://user-images.githubusercontent.com/57918064/96817747-59898780-13f6-11eb-90bc-aa9d39e18b5e.png">
<img width="395" alt="Captura de Tela 2020-10-21 às 23 29 16" src="https://user-images.githubusercontent.com/57918064/96817754-6017ff00-13f6-11eb-8fc1-32154905296f.png">

**Your Environment**
Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.7
Memory: 1981M
Cores: 8
Non-Bundled Plugins: org.jetbrains.kotlin, gherkin, net.lagerwey.cucumber-kotlin, cucumber-java

**Additional context**
After the project is open, when I ask to reinstall the plugin, even though it gives me a warning of incompatibility, as long as the IDE is open, **it works**. However, when I **close the Android Studio process** and **open the IDE again**, the plugin does not display as installed and I am forced to download and install again.

**Comment by mpkorstanje** [comment]
The Cucumber  for Java plugin is maintained by JetBrains.

https://github.com/JetBrains/intellij-plugins/tree/master/cucumber-java
