### ISSUE TITLE
About java.lang.NoSuchFieldException: TestCase error

### ISSUE THREAD

**Issue by alikatircio** [cucumber/cucumber-jvm#2161]
Hi, when i try get scenario test case it's give it ` java.lang.NoSuchFieldException: TestCase` error.
If I don't get it wrong, the versions after version 4.8.0 cannot be used in this way, so how can we get this attribute in new versions?

```
@Before
public void InitializeTest(Scenario scenario) throws Throwable {

        Field f = scenario.getClass().getField("TestCase");
        f.setAccessible(true);
        TestCase r = (TestCase) f.get(scenario);

        //You need to filter out before/after hooks
        List<PickleStepTestStep> stepDefs = r.getTestSteps()
                .stream()
                .filter(x -> x instanceof PickleStepTestStep)
                .map(x -> (PickleStepTestStep) x)
                .collect(Collectors.toList());
}
```

**Comment by mpkorstanje** [comment]
You are using reflection to access fields that weren't normally accessible. So it is to be expected that when the implementation changes these fields move. If you are looking to create a custom report consider using the `Plugin` interface. Have a look at the existing plugins to see how to write one.
