### ISSUE TITLE
If you're using `6.0.0-RC2` you could use something like this:

### ISSUE THREAD

**Issue by karthikratnam1** [cucumber/cucumber-jvm#2171]
If you're using `6.0.0-RC2` you could use something like this: 

```java
@CucumberContextConfiguration
@SpringBootTest(classes = TestConfig.class)
public class CucumberSpringConfiguration {

  @MockBean
  public MyService service;

}
```

The class annotated with `@CucumberContextConfiguration` is passed to springs `TestContextManager` and subject to the same processing the class would be in JUnit. So this should result in the application context being created with a mocked `MyService` bean. 

You'll have to figure out the edgecase yourself.

_Originally posted by @mpkorstanje in https://github.com/cucumber/cucumber-jvm/issues/1470#issuecomment-638688625_

@SpyBean similar to @MockBean is not working with this configuration. Is there any additional configuration is required or it is not supported?

**Comment by mpkorstanje** [comment]
As I said:

> You'll have to figure out the edgecase yourself.

Cucumber does currently not invoke the before/after test method hooks on Springs TestContextManager so any test execution listeners that depend on this will not work.

You can look at the SpyBean related test execution listeners and see what goes wrong.
