### ISSUE TITLE
Cucumber 6.9.0 and customising feature location files not working as expected

### ISSUE THREAD

**Issue by Darkvater** [cucumber/cucumber-jvm#2175]
**Describe the bug**
It is not possible to have feature files in a location different from the classpath of the cucumber test class defined using ```cucumber.features``` in ```cucumber.properties```. It is possible to define a custom feature location folder using ```@CucumberOptions(features={"path/"})```.
This is especially an issue with JUnit5 where ```@CucumberOptions``` annotation is gone and only ```cucumber.properties``` or ```junit-platform.properties``` remains. As such feature files now *have* to live in the same package as the test class in resources. Tests are run using gradle

**To Reproduce**
### Steps to reproduce the behavior for JUnit5: ###
1. Clone repository https://github.com/bonigarcia/mastering-junit5/tree/master/junit5-cucumber
2. update the cucumber version to 6.9.0 (although 6.6.1 in the example repo behaves the same)
3. run the tests using gradle ```./gradlew clean test``` see that it works; output:
> org.junit.platform.launcher.core.LauncherConfigurationParameters fromClasspathResource
> INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/.../resources/test/junit-platform.properties]
> UnknownClass.Addition STANDARD_OUT
> ... test results
4. now change the path of ```calculator.feature``` to "io.github.bonigarcia1" for example
5. try any combination in ```junit-platform.properties``` for "cucumber.features" and run the tests (step #3). Nothing will work, there will be no tests found

### Steps to reproduce the behaviour for JUnit4: ###
1. as before
2. update the cucumber version to 6.9.0 and change dependencies to JUnit4:
in ```build.gradle```
```
ext {
    junitVersion = '4.3.1'
    cucumberVersion = '6.9.0'
}
...
test {
   //useJUnitPlatform()
...
    testImplementation("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
    testImplementation("io.cucumber:cucumber-java:${cucumberVersion}")
    testImplementation("io.cucumber:cucumber-junit:${cucumberVersion}")
```
in ```CucumberTest.java```
```
@RunWith(Cucumber.class)
```
3. as before
4. as before
5. as before, specifying the path in ```cucumber.options``` does not work. it says the below even we specified something else in the properties file
> io.cucumber.core.runtime.FeaturePathFeatureSupplier get
> WARNING: No features found at classpath:/io/github/bonigarcia
6. add ```CucumberOptions(features = {"src/test/resources/io/github/bonigarcia1"})``` to CucumberTest.java and it will work

**Expected behaviour**
Expecting to be able to specify the path to the feature files such that one is not tied to the same path as the test class

**Context & Motivation**
We upgraded from Cucumber 4 to Cucumber 6 and found that the current code broke.

**Your Environment**
 - Versions used: 6.9.0
 - Operating System and version: N/A
 - Build tool: Gradle 6.6.1, but same on Gradle 5.6.4

**Comment by mpkorstanje** [comment]
This is the expected behavior.

Maven Surefire and Gradle do not yet support discovery of non-class based tests (see: [gradle/#4773](https://github.com/gradle/gradle/issues/4773),  [SUREFIRE-1724](https://issues.apache.org/jira/browse/SUREFIRE-1724)). As a workaround you can either use the `@Cucumber` annotation or the JUnit Platform Console Launcher --

 * https://github.com/cucumber/cucumber-jvm/blob/main/junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/Cucumber.java#L12-L22
*  https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine#surefire-and-gradle-workarounds
