### ISSUE TITLE
More verbosity when no tests are run

### ISSUE THREAD

**Issue by flyhard** [cucumber/cucumber-jvm#2179]
I used a lot of time today trying to find out why my features wouldn't run. I thought cucumber junit engine wasn't been discovered, but it turned out I had my folders messed up. 

What I was missing was some output saying "I was looking in folder X for features, but found none" or "couldn't find any class annotated with X" to point me in the right direction. 

I think this should be something it should output just like it outputs the publish stuff. 

This improvement would be a lot of help to anyone who is new to cucumber or the junit 5 way of setting it up.

**Comment by mpkorstanje** [comment]
Would this help:

```
Dec 09, 2020 2:27:50 AM org.junit.platform.launcher.core.LauncherConfigurationParameters loadClasspathResource
INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/home/mpkorstanje/Projects/cucumber/cucumber-jvm/junit-platform-engine/target/test-classes/junit-platform.properties].
Dec 09, 2020 2:27:50 AM org.junit.platform.launcher.core.LauncherConfigurationParameters loadClasspathResource
INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/home/mpkorstanje/Projects/cucumber/cucumber-jvm/junit-platform-engine/target/test-classes/junit-platform.properties].
Dec 09, 2020 2:27:51 AM io.cucumber.junit.platform.engine.FeatureResolver resolvePackageResourceWarnIfNone
WARNING: No features found in package 'io.cucumber.junit.platform.engine.nofeatures'
```

Depends a bit on your tooling where this ends up.

**Comment by flyhard** [comment]
Was a gradle build and I ran with the --info flag. I haven't seen that warning.

**Comment by mpkorstanje** [comment]
That's expected. I just added it. :smile: 

I wanted to know if it would have helped or if the message might not be informative enough.

Did you see the INFO log lines anywhere? The error message would be printed in the same place.

**Comment by flyhard** [comment]
Seems like it would be very usefull. And yes, I saw the info messages, I believe.

**Comment by mpkorstanje** [comment]
Can you try v6.9.1?
