### ISSUE TITLE
Its throwing: io.cucumber.core.runner.AmbiguousStepDefinitionsException:  matches more than one step definition:

### ISSUE THREAD

**Issue by naveenanimation20** [cucumber/cucumber-jvm#2183]
In my feature file with scenario outline and Examples, having int and double data init. When I generate step definition file it gives me two methods (overloaded) : one is with int and another is with double. 

But when I run my feature file, it gives me following exception:
      io.cucumber.core.runner.AmbiguousStepDefinitionsException: "user enters tax amount 10" matches more than one step definition:
  "user enters tax amount {double}" in stepdefinitions.BillingSteps.user_enters_tax_amount(double)
  "user enters tax amount {int}" in stepdefinitions.BillingSteps.user_enters_tax_amount(int)

This should pick the specific step method as it is already defined with overloaded method and data is coming from feature file examples table in the form of int and double.
--------------------------
I'm using Cucumber JVM.
<java.version>1.8</java.version>
<junit.version>4.13.1</junit.version>
<cucumber.version>6.9.0</cucumber.version>
--------------------------
The same feature is perfectly working fine with 4.x cucumber version. Something has been changed in cucumber 6.x and it needs to be fixed.
--------------------------

//This is my feature file:

Feature: Calculate billing amount
Scenario Outline: billing amount
 Given user is on billing page
 When user enters billing amount <billingamount>
 When user enters tax amount <taxamount>
 And user clicks on calculate button
 Then it gives the final amount <finalamount>
    Examples: 
      | billingamount| taxamount | finalamount|
      | 1000 | 10   | 1010   |
      | 500  | 20   | 520    |
      | 100  | 5.5  | 105.5  |
===================
//This is my step definition class:
package stepdefinitions;

import org.junit.Assert;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

public class BillingSteps {

	int billingAmount;
	double taxAmount;
	double finalAmount;

	@Given("user is on billing page")
	public void user_is_on_billing_page() {
	}

	@When("user enters billing amount {int}")
	public void user_enters_billing_amount(int billingAmount) {
		this.billingAmount = billingAmount;
	}

	@When("user enters tax amount {int}")
	public void user_enters_tax_amount(int taxAmount) {
		this.taxAmount = taxAmount;
	}

	@When("user enters tax amount {double}")
	public void user_enters_tax_amount(double taxAmount) {
		this.taxAmount = taxAmount;
	}

	@When("user clicks on calculate button")
	public void user_clicks_on_calculate_button() {
	}

	@Then("it gives the final amount {int}")
	public void it_gives_the_final_amount(int expectedFinalAmount) {
		this.finalAmount = this.billingAmount + this.taxAmount;
	}

	@Then("it gives the final amount {double}")
	public void it_gives_the_final_amount(double expectedFinalAmount) {
		this.finalAmount = this.billingAmount + this.taxAmount;
	}

}

**Comment by mpkorstanje** [comment]
This is working as intended. For future reference:

 - https://guides.github.com/features/mastering-markdown/
 - https://teejeetech.medium.com/etiquette-in-open-source-projects-f302b6e19c38
 - https://dzone.com/articles/never-use-float-and-double-for-monetary-calculatio

**Comment by Ashafa11** [comment]
Even with the use of version 4.8.1, is throwing this error.

package stepdefinitions;

import org.junit.Assert;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

public class BillingSteps {
	
	double  billingAmount;
	double taxAmount;
	double finalAmount;
	

@Given("user is on billing page")
public void user_is_on_billing_page() {
   
}

@When("user enters billing amount {int}")
public void user_enters_billing_amount(Integer billingAmount) {
	this.billingAmount = billingAmount;
    
}
@When("user enters tax amount {double}")
public void user_enters_tax_amount(Double taxAmount) {
	this.taxAmount = taxAmount;
    
}
@When("user enters tax amount {int}")
public void user_enters_tax_amount(Integer taxAmount) {
	this.taxAmount = taxAmount;
}

@When("user clicks on calculate button")
public void user_clicks_on_calculate_button() {
}

@Then("it gives the final amount {int}")
public void it_gives_the_final_amount(Integer finalAmount) {
	this.finalAmount = this.billingAmount + this.taxAmount ;
	
	Assert.assertTrue(this.finalAmount == finalAmount);

} 
@Then("it gives the final amount {double}")
public void it_gives_the_final_amount(Double finalAmount) {
	this.finalAmount = finalAmount;
	
	Assert.assertTrue(this.finalAmount == finalAmount);

    }    
}




Jun 06, 2021 12:56:32 AM cucumber.api.cli.Main run
WARNING: You are using deprecated Main class. Please use io.cucumber.core.cli.Main
Exception in thread "main" java.lang.NoClassDefFoundError: Scenario
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3325)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3350)
	at java.base/java.lang.Class.getMethods(Class.java:1996)
	at cucumber.runtime.java.MethodScanner.scan(MethodScanner.java:39)
	at cucumber.runtime.java.JavaBackend.loadGlue(JavaBackend.java:111)
	at cucumber.runner.Runner.<init>(Runner.java:39)
	at cucumber.runner.SingletonRunnerSupplier.createRunner(SingletonRunnerSupplier.java:38)
	at cucumber.runner.SingletonRunnerSupplier.get(SingletonRunnerSupplier.java:32)
	at cucumber.runtime.Runtime.run(Runtime.java:85)
	at io.cucumber.core.cli.Main.run(Main.java:43)
	at cucumber.api.cli.Main.run(Main.java:28)
	at cucumber.api.cli.Main.main(Main.java:15)
Caused by: java.lang.ClassNotFoundException: Scenario
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more

**Comment by PravinBaravkar** [comment]
With cucumber version 4.8.1, its working fine for me.
Howevr getting same error with version 6.9.0
