### ISSUE TITLE
No space after *.feature:linenr 

### ISSUE THREAD

**Issue by unSinn** [cucumber/cucumber-jvm#2184]
**Describe the bug**
When a Scenario failes I get:

`failed scenarios:
file://D:/git/Some.feature:6# Some Description
`
IntelliJ creates a clickable link `file://D:/git/Some.feature:6#` but cannot navigate to the file because of the # at the end.

I think a space after the line number should solve the issue.

**To Reproduce**
1. Use IntelliJ
2. Create a failing Cucumber test
3. Try to click the link to the *.feature file

**Expected behavior**
Link should work. 

**Context & Motivation**

Clicking instead of searching for the file saves a lot of time.

**Screenshots**
![image](https://user-images.githubusercontent.com/1630658/101761910-07eba800-3add-11eb-9e1a-3f3792132c79.png)

**Your Environment**
 - Versions used 6.9.0
 - Operating System and version: Windows 10
 - Build tool Apache Maven

**Comment by mpkorstanje** [comment]
Cheers! Nice find.
