### ISSUE TITLE
cucumber.publish.quiet=true not working

### ISSUE THREAD

**Issue by mjaggard** [cucumber/cucumber-jvm#2189]
**Describe the bug**
When I try to remove the advert by setting cucumber.publish.quiet=true in my cucumber.properties file I have other issues that I don't understand.

**To Reproduce**
1. Create a cukes-rest example project.
2. Create cucumber.properties and insert cucumber.publish.quiet=true
3. Run tests
4. See the following error
```
More than one Cucumber ObjectFactory was found in the classpath

Found: lv.ctco.cukes.core.internal.di.SingletonObjectFactory, io.cucumber.guice.GuiceFactory
```
**Expected behavior**
The advert banner should be suppressed.

**Context & Motivation**

I'm attempting to get my new team to use Cucumber REST tests and the advert is a distraction.

**Your Environment**
 - Versions used 6.9.0
 - Operating System and version Mac Big Sur
 - Build tool Gradle 6.7.1

**Additional context**
If I attempt to fix the problem using `cucumber.object-factory=io.cucumber.guice.GuiceFactory` I get the following error
```
      com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for java.util.Set<lv.ctco.cukes.core.extension.CukesPlugin> was bound.

```

**Comment by mpkorstanje** [comment]
It would appear that you are using https://github.com/ctco/cukes rather then Cucumber. I would recommend that you post your issue there. If you do believe this a problem with Cucumber please create a [Minimal, Reproducible Example](https://stackoverflow.com/help/mcve) in the form of a Github repository and reopen this issue.

**Comment by mjaggard** [comment]
You're quite right. I found that Cukes has created its own cucumber.properties and so if I created one, regardless of contents, it broke their implementation.

For anyone else's reference, the fix was this:

```
cucumber.publish.quiet=true
cucumber.object-factory=lv.ctco.cukes.core.internal.di.SingletonObjectFactory
```
