### ISSUE TITLE
Cucumber command line options not overriding

### ISSUE THREAD

**Issue by a1dutch** [cucumber/cucumber-jvm#2190]
**Describe the bug**
The `cucumber.plugin` command line options are not overriding the ones set on the CucumberOptions.

with the following runner

```
@RunWith(Cucumber.class)
@CucumberOptions(
    plugin = {
        "pretty",
        "summary",
        "html:target/cucumber-html/index.html",
        "json:target/cucumber-report.json",
        "junit:target/cucumber.xml"
    },
    features = "classpath:features",
    tags = "not @manual and not @ignored")
public class TestRunner {
    // not required
}
```

when the following maven command is ran

```
./mvnw --no-transfer-progress clean test -Dcucumber.plugin=pretty
```

gives the following error

```
io.cucumber.core.exception.CucumberException: Only one plugin can use STDOUT, now both pretty and pretty use it. If you use more than one plugin you must specify output path with pretty:DIR|FILE|URL
```

Removing `pretty` from the CucumberOptions makes it work from the command line, but does not add the pretty formatter when run from eclipse.

**Expected behavior**
Command line options should override the CucumberOptions annotation

**Your Environment**
 - Cucumber 6.4.0 +
 - MacOS
 - Maven 3.6

**Comment by mpkorstanje** [comment]
The `cucumber.plugin` options are merged rather then overridden like most others.

I don't quite understand the practical problem you are facing though. Are you intentionally trying to disable the plugins specified in `CucumberOptions` by providing only `pretty` in `cucumber.plugin`?

**Comment by a1dutch** [comment]
We have a common pipeline to run all our test jobs in jenkins that tries to enable the `pretty` plugin and some others.  

The pretty plugin is also specified in the CucumberOptions.

If these are merged shouldnt the check be done after merging them together?

**Comment by mpkorstanje** [comment]
The merge is pretty naive. It doesn't filter out duplicates, but that is something that could be implemented.

**Comment by a1dutch** [comment]
Wow @mpkorstanje that was quick! Thankyou very much
