### ISSUE TITLE
How to convert event.timestamp to date and time format .. Please suggest

### ISSUE THREAD

**Issue by SakthiIsaiBharathi** [cucumber/cucumber-jvm#2195]
Hi, I am working on creating on a new plugin.. I need some suggestions to convert event.timestamp to date and time format.

**Comment by mpkorstanje** [comment]
I am assuming you are talking about [`TimeStampedEvent.instant`](https://github.com/cucumber/cucumber-jvm/blob/main/plugin/src/main/java/io/cucumber/plugin/event/TimeStampedEvent.java#L8). `Instant` is part of the `java.time` API. You'd convert it the usual way.

E.g: https://stackoverflow.com/questions/25229124/format-instant-to-string

**Comment by SakthiIsaiBharathi** [comment]
Is event.timestamp is nanseconds or millseconds ?

**Comment by mpkorstanje** [comment]
nano seconds since the epoch, but you are using an older version of Cucumber.
