### ISSUE TITLE
Need Suggestions or help on how to get Throwable error - cause and detail message in custom plugin

### ISSUE THREAD

**Issue by SakthiIsaiBharathi** [cucumber/cucumber-jvm#2200]
![image](https://user-images.githubusercontent.com/47920071/103912848-ce36ad00-512d-11eb-88f8-d75b306c7a6e.png)

**Comment by SakthiIsaiBharathi** [comment]
@mpkorstanje Please suggest

**Comment by mpkorstanje** [comment]
Please use the [support forums](https://community.smartbear.com/t5/Cucumber-Open/bd-p/CucumberOS)  for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
