### ISSUE TITLE
Is there an option where we can pass paramters to the custom plugin under cucumber options from runner file. Please let us know if this can be added as future request

### ISSUE THREAD

**Issue by SakthiIsaiBharathi** [cucumber/cucumber-jvm#2205]
Hi,

I have created an custom plugin. I wanted to pass couple of parameters to this plugin. Is there an option i can do or do we need to introduce this feature ?

**Comment by mpkorstanje** [comment]
Not really well documented but this works: `cucumber.plugin=com.example.MyPlugin:some-information-here`. See: https://github.com/cucumber/cucumber-jvm/blob/main/plugin/src/main/java/io/cucumber/plugin/Plugin.java or https://github.com/cucumber/cucumber-jvm/blob/main/core/src/main/java/io/cucumber/core/plugin/PluginFactory.java
