### ISSUE TITLE
Include Error information in GherkinMessagesFeatureParser / FeatureParserException

### ISSUE THREAD

**Issue by laeubi** [cucumber/cucumber-jvm#2209]
**Is your feature request related to a problem? Please describe.**
If a feature contains pare errors they are converted into a string and the thrown as FeatureParserException, but the original information about the error is lost.

**Describe the solution you'd like**
It would be good to attach the errors to the FeatureParserException so it could be accessed programtically, This would allow better debugging and/or toolsupport.

**Comment by mpkorstanje** [comment]
I would expect tooling to use the gherkin parser directly rather than through Cucumber JVM. What kind of tooling do you have in mind.

**Comment by laeubi** [comment]
If I call for example the CLI API from code and catch the error. I can for sure parse the feature first, the call the CLI but that seems a bit of double work....

**Comment by mpkorstanje** [comment]
That's not really a use-case for the CLI though.

This will probably popup if/when the programmatic API comes by.

**Comment by laeubi** [comment]
Anyways its good practice to at least reference the cause in the thrown exception and this doesn't hurt. I find it a bit frustrating that such valid request are getting simply closed. Whenever I *not* using the CLI you told me I should use the CLI and when I'm using the CLI I'm getting tol "don't use the CLI for that"....

**Comment by mpkorstanje** [comment]
There seems to be a misunderstanding.

In the past I have suggested  that you use Cucumbers documented API. The CLI being the most suitable replacement.  However it remains a CLI, this means that there will be use-cases that it does not facilitate. This appears to be one.

In this issue you mentioned that the parse exception would be used by tooling. However I would not expect tooling to use the CLI to parse Gherkin. This seems rather roundabout. I would expect tooling involving Gherkin to use the Gherkin parser. You seem to have taken my expectation a a suggestion.

That said, I've given the request consideration.

I would not expect a CLI to throw an exception when dealing with expected problems but rather pretty print a detailed message. So making that exception part of the API would be a step in the wrong direction. Ultimately properly printing a detailed error message and your request for more details in the exception are use cases that could be facilitated by a programmatic API (covered by #1711) so there is no need to keep this issue around.

I can understand that it is frustrating to see a request closed but I find closing issues is preferable over letting them languish in the backlog. It provides clarity.

**Comment by laeubi** [comment]
Thanks for the clarification, but I think there is a misunderstanding, I actually don't want to "parse" the gherking, I like to run cucumber.

So assume the following case:

- User writes a feature-file (or open it from somewhere)
- User asks my tool to run the feature but the feature has error and thus the run fails
- I can catch the error and print a (textual) error that the run failed, but like to give the user a clue where the error happen (e.g. he can click on the error message and then my tool opens the feature-file and jumps to the error location)

Because at the moment the actual information is lost (e.g. original exception not provided as a linked exception) I can only guess the feature has errors and parse it afterward (again) to get additional information about the error.
