### ISSUE TITLE
{word} parameter type doesn't convert to an enum value

### ISSUE THREAD

**Issue by andrewpeeltws** [cucumber/cucumber-jvm#2210]
I'm unable to get the {word} placeholder to automatically get converted to an enumeration value. 

Tests 1 and 3 below pass, but test 2 fails with:
```
Step failed
io.cucumber.core.exception.CucumberException: Could not invoke step [I supply enum value {word} as word] defined at 'CucumberEnumTest.test2(CucumberEnumTest$TestEnum)'.
It appears there was a problem with the step definition.
The converted arguments types were (java.lang.String)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.couldNotInvokeStep(PickleStepDefinitionMatch.java:130)
	at
```

```
import io.cucumber.java.en.When;

public class CucumberEnumTest {

    @When("^I supply enum value (.*?) as regex$")
    public void test1(TestEnum arg1) {
        testMyEnum(arg1);
    }

    @When("I supply enum value {word} as word")
    public void test2(TestEnum arg1) {
        testMyEnum(arg1);
    }

    @When("I supply string value {word} as word")
    public void test3(String arg1) {
        testMyEnum(TestEnum.valueOf(arg1));
    }

    public enum TestEnum {
        GET
    }

    protected void testMyEnum(TestEnum testEnum) {
        System.out.println(testEnum);
    }
}
```

```
Feature: Cucumber enum parameters

  Scenario: regex
    When I supply enum value GET as regex

  Scenario: word placeholder with enum
    When I supply enum value GET as word

  Scenario: word placeholder with String
    When I supply string value GET as word
``` 

```
   <dependencies>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>6.9.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

**Comment by mpkorstanje** [comment]
That is the expected behaviour. Capture groups in regular expressions and the anonymous parameter in a cucumber expression look at the step definition for type hints. All other parameter types are typed. 

Consider defining a parameter type for your enum.

**Comment by laeubi** [comment]
@mpkorstanje [according to the docs](https://cucumber.io/docs/cucumber/cucumber-expressions/) cucumber is supposed to support enums for words (but maybe I misunderstand the wording here?):

> Aside from Enum it supports conversion to ...

anyways if it not right now supports it I think it would be great to support this out-of-the-box, even if only supported as a custom one like 

> On the JVM, there are additional parameter types for biginteger, bigdecimal, byte, short, long and double

could we pobably simply add {enum}? Enum is really a must-support for any java-tool as its very common. If you have not time to implement this I could try to create a PR for this.

**Comment by laeubi** [comment]
I checked the code and shouldn't [this](https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/BuiltInParameterTransformer.java#L81) do the job of string->enum conversion?

**Comment by mpkorstanje** [comment]
>  cucumber is supposed to support enums for words

The three sentences in the paragraph are all on the subject of the anonymous parameter type (i.e. `{}`):

>> The anonymous parameter type will be converted to the parameter type of the step definition using an object mapper. Cucumber comes with a built-in object mapper that can handle most basic types [when using the anonymous parameter type]. Aside from Enum [the build in object mapper used by the anonymous parameter type] supports conversion to ... To automatically convert to other types it is recommended to install an object mapper.

> I checked the code and shouldn't this do the job of string->enum conversion?

That is the build in object mapper mentioned in the docs. It supports converting regular expressions and the anonymous parameter in a cucumber expression to a limited set of java types. It uses the parameter type from the step definition method as a type hint.

This allows the following to work:

```java
    @When("I supply enum value {} as anonymous parameter")
    public void test(TestEnum arg1) {

    }
    @When("I supply a big integer value {} as anonymous parameter")
    public void test(BigInteger arg1) {

    }    
```

Additionally if you register an object mapper with `@DefaultParameterTransformer` any type supported by the object mapper will work. For example:

```java
    @When("I supply a local date value {} as anonymous parameter")
    public void test(LocalDate arg1) {

    }
```

> could we pobably simply add {enum}? 

The use case is already covered by the anonymous parameter type.

**Comment by laeubi** [comment]
> The use case is already covered by the anonymous parameter type.

I think an explicit {enum} type would be much more expressive to use, if I provide a patch for this would it be accepted?

**Comment by mpkorstanje** [comment]
I think you have the process backwards. You could first write your step definition:

```java
@Given("A(n) {enum} {enum} account")
public void an_account(AccountStatus s, AccountType t) { }
```

But then you have to use `Enum.name()` in your feature file.

```gherkin
Given an IN_CLOSING RETAIL account
```

But really you should first write your feature like a normal human being:

```gherkin
Given an in closing retail account 
```

And then facilitate that by writing your step definition using:

```java
@Given("A(n) {accountType} {accountState}  account")
public void an_account(AccountState s, AccountType t) { }

@ParameterType("retail|private")
public AccountType accountType(String s) { }

@ParameterType("open|closed|in closing")
public AccountState accountState(String t) { }
```

There are a few exceptions where `Enum.name()` and the domain language are identical. Though this also suggests the domain is quite technical. Cucumber may not be the right tool for the job here. For example when using HTTP verbs you are probably better of using a dedicated DSL for testing such as RestAssured, or documentation such as OpenAPI. Or as a more generic solution you can use Asciidoctor to include examples form your test suite in your documentation.

**Comment by laeubi** [comment]
The advantage of enums is of course that IDEs can give you good typehints and one can't forget to add/map new values.

But your right that enum constants are 'ugly', thats a good point, but I could think about if the parameter type is an enum, we do match against the [Enum.toString()](https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html#toString()) value. That would allow to define 'user friendly representation' but remove the need to define a special mapping. If this is still not suitable one can always choose the approach you have described above.
