### ISSUE TITLE
Using Cucumber options from annotation @CucumberOptions and system properties

### ISSUE THREAD

**Issue by mrbaco** [cucumber/cucumber-jvm#2211]
**Is your feature request related to a problem? Please describe.**
In our project we use several TestRunners to run tests in different browsers and environment. Every TestRunner contains **@CucumberOptions** annotation with field **tags**. I know that we can use system properties to change default (coded) value of **tags**. Moreover we use **cucumber.filter.name** via system property to filter tests by name (for example, we need to find tests which contain "Desktop", "Tablet" etc in their name).

The problem is: we can't use both default value of **tags** from **@CucumberOptions** annotations and **cucumber.filter.name** that was set via system property. The second value overrides the first one and value of **tags** is empty.

**Describe the solution you'd like**
I think it can be very useful if we can use both params from every source (configuration annotation, system property etc).

**Comment by mpkorstanje** [comment]
Could you give an example of what you are trying to achieve?

**Comment by mrbaco** [comment]
Ok, I'll try to explain. I prepared sample project for this: https://github.com/mrbaco/CucumberOptionsSample
There are 2 TestRunners that used to run tests in 2 different environments (desktop and mobile).

I use Desktop/Mobile etc words in scenarios title to make TestRunners understand which scenario they should run. To understand this I add filter by name on line 29 in TestRunnerBase (/src/test/java/cucumberRunners/TestRunnerBase.java) via system properties.

Take a look to feature-file (/src/test/resources/features/test.feature). For example we have 3 scenarios annotated with **@regression** and **@ignore** tags. I expect that when I start a build, ignored scenarios won't be run cause I add **@regression and (not @ignore)** to CucumberOptions but unfortunately they run.

The only way I found to run it correctly is to put **filter.tags** in System.properies in the same way as I do with **filter.name**. But I think it would be comfortable if we can use system properties with Cucumber options to merge filter params.

**Comment by mpkorstanje** [comment]
I'm trying to understand what you are trying to achieve. However you are describing what you are doing right now and I can't really tell which parts of your explanation are a work around for another problem you may have and which are trying to solve your actual problem. It's called the https://xyproblem.info/.

I'm guessing though that you want:
 - A runner that runs all mobile tests tagged with regression and not ignored
 - A runner that runs all desktop tests tagged with regression and not ignored 
 
 Have you considered using the `name` and `tags` filter in a single ` @CucumberOptions` annotation?
 
 ```
 @CucumberOptions(
		tags = "@regression and (not @ignore)",
		name = "^Desktop\\. "
		....
 )
public class TestRunnerDesktopChrome extends TestRunnerBase {
```

**Comment by mrbaco** [comment]
> I'm guessing though that you want:
> A runner that runs all mobile tests tagged with regression and not ignored
> A runner that runs all desktop tests tagged with regression and not ignored

I am sorry for long explanation of the problem. But you are absolutely right: I want to achieve the behavior you've just described.

> Have you considered using the name and tags filter in a single @CucumberOptions annotation?

I tried use it and it works well but there is no possibility to change `filter.tags` via system property and to not lost `filter.name` after it. I found that options override after this condition https://github.com/cucumber/cucumber-jvm/blob/31c1361be8d95fd1b0cc3430f1ebfa5dcc9b4d0e/core/src/main/java/io/cucumber/core/options/RuntimeOptionsBuilder.java#L117

So what do you think is it possible to make ability to use params from every source (configuration annotation, system property etc)?

**Comment by mpkorstanje** [comment]
So if you can use `name` and `tags` together in `@CucumberOptions`, what are you trying to achieve by also using `cucumber.filter.tags`?

> there is no possibility to change filter.tags via system property and to not lost filter.name after it.

That is intentional. Filters from different sources replacing each other is intentional. The idea is that you can run `mvn test -Dtest=RunCucumberTests -Dcucumber.filter.tags=....` to select a specific test from the CLI.

**Comment by mrbaco** [comment]
> So if you can use name and tags together in @CucumberOptions, what are you trying to achieve by also using cucumber.filter.tags?

We use Bamboo as CI and integrate it with Jira via XRay plugin. When XRay plugin gets features list from Jira it creates one huge feature with all scenarios inside. To run them plugin puts `-Dcucumber.filter.tags` property with value `@PROJECT-TASK_NUMBER`. So `filter.name` doesn't work after it.

> That is intentional. Filters from different sources replacing each other is intentional.

Ok, now I understand, I think we can close this issue.
Thanks for explanation!

**Comment by mpkorstanje** [comment]
> We use Bamboo as CI and integrate it with Jira via XRay plugin. When XRay plugin gets features list from Jira it creates one huge feature with all scenarios inside. To run them plugin puts -Dcucumber.filter.tags property with value @PROJECT-TASK_NUMBER. So filter.name doesn't work after it.

Ah, you should have lead with that. :smile: 

There is often an implicit assumption that there is only a single runner. You may be able to accommodate this by using [Conditional Hooks](https://cucumber.io/docs/cucumber/api/#conditional-hooks) to setup your webdriver instead. This does require tagging your tests with the device they'll run on though.

**Comment by mrbaco** [comment]
> Ah, you should have lead with that. 😄

Sorry, I didn't think that it is important in this situation :)
Thanks a lot for you advice about Conditional Hooks!
