### ISSUE TITLE
ClasspathScanner fails if classloader contains custom URI scemes

### ISSUE THREAD

**Issue by laeubi** [cucumber/cucumber-jvm#2212]
**Describe the bug**
ClasspathScanner uses Path.get(URI) to convert an URI to a path. This fails if the URI does not conforms to the contracts of that method and throws an FileSystemNotFoundException

**Expected behavior**
ClasspathScanner ignores URIs it can not convert.

**Additional context**
Caused by: java.nio.file.FileSystemNotFoundException: Provider "bundleresource" not installed
	at java.base/java.nio.file.Path.of(Path.java:212)
	at java.base/java.nio.file.Paths.get(Paths.java:97)
	at io.cucumber.core.resource.CloseablePath.open(CloseablePath.java:23)
	at io.cucumber.core.resource.PathScanner.open(PathScanner.java:39)
	at io.cucumber.core.resource.PathScanner.findResourcesForUri(PathScanner.java:26)
	at io.cucumber.core.resource.ClasspathScanner.findClassesForUri(ClasspathScanner.java:72)
	at io.cucumber.core.resource.ClasspathScanner.lambda$findClassesForUris$3(ClasspathScanner.java:64)

**Comment by laeubi** [comment]
an invalid URI might look like this bundleresource://18.fwk442924399/ but depending on the runtime there might be other patterns of URI/URL that are not convertible to a path.

**Comment by mpkorstanje** [comment]
Cucumber uses the `FileSystem` api to scan the classpath for resources. This works for the most common use cases and is relatively easy to maintain. 

The problem you are facing is that `bundleresource` is not recognized as a valid file system. If OSGI does not provide implementation of `FileSystem` that supports `bundleresource` you may have to provide one yourself. Given that in OSGI you already have the `FileLocator.toFileUR` I imagine it wouldn't be too difficult.

**Comment by laeubi** [comment]
FileLocator is Eclipse API. bundleresources do not necessarily have a file representation. The problem is that the cucumber-run is aborted completely just because some (irrelevant) resources that are not compatible. At the moment I setup a special class-loader that simply filters the offending URLs from the returned enumeration of ClassLoader.getResources(String) but that's really a hack... so I would suggest to simply ignore URIs that are incompatible with the way cucumber scans the classpath.

**Comment by mpkorstanje** [comment]
I can log some warnings if `findResourcesForUri` runs into problems instead of failing, but this will get quite spammy if you have a lot of resources that can't be loaded.

Does reducing the scope to specific packages with `cucumber.glue=com.example` and `cucumber.features=classpath:com/example` make your problem go away?

**Comment by laeubi** [comment]
I think a warning is fine (as it seems a rare case), reducing the scope works, but I need to scan as much as possible and its user-configurable so I don't know in advance what the user will configure to scan.
