### ISSUE TITLE
Failed scenario step image is not included in the html report.

### ISSUE THREAD

**Issue by obulreddy143** [cucumber/cucumber-jvm#2221]
**Describe the bug**
Failed scenario step image is not included in the HTML report.

**To Reproduce**

1. Added the below method
2.@After(order = 1)
    public void tearDown(Scenario scenario){
        if(scenario.isFailed()){
            //take screenshot
            String screenShotName = scenario.getName().replaceAll(" ", "");
            byte[] sourcePath = ((TakesScreenshot)driver).getScreenshotAs(OutputType.BYTES);
            scenario.attach(sourcePath, "image.png", screenShotName);
        }
    }

3. Executed the feature file, in the feature file one of the scenario is got failed, and for the same image is not attached in HTML report.

4. seeing an error in the HTML report as "Couldn't display image.png attachment because the media type is unsupported. Please submit a feature request at https://github.com/cucumber/cucumber/issues"

**Expected behavior**
Failed scenario image should be attached to the HTML report.

![image](https://user-images.githubusercontent.com/20371115/106696780-6af04b80-6603-11eb-88d9-8ca7d4a28436.png)

**Comment by mpkorstanje** [comment]
The second argument should be a media type such as `image/png` rather then `image.png`.
