### ISSUE TITLE
Junit5 BeforeAll with cucumber not working

### ISSUE THREAD

**Issue by sharti** [cucumber/cucumber-jvm#2222]
Hi Team,

I'm trying to run JUnit5 with cucumber and would like to achieve beforeAll to do some operation before the cucumber feature file is triggered. Below is the test runner:

@Cucumber
public class TestRunner  {
}

Also, have added a class LifeCycle:
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.ExtensionContext;

public class LifeCycle implements BeforeAllCallback, ExtensionContext.Store.CloseableResource{
  @Override
  public void beforeAll(ExtensionContext context) {
    System.out.println("before allll");
  }

  @Override
  public void close() throws Throwable {

  }
}
And also, have added the /META-INF/services under /test/resources/
org.junit.jupiter.api.extension.Extension and it contains at.LifeCycle

Any help is highly appreciated..

**Comment by mpkorstanje** [comment]
That's expected. JUnit 5 consists of the JUnit Platform, JUnit Jupiter and JUnit Vintage.

Cucumber like JUnit Jupiter and JUnit Vintage is a Test Engine in the JUnit Platform. The extensions you are using are part of Jupiter and not executed by Cucumber.

https://junit.org/junit5/docs/current/user-guide/#overview-what-is-junit-5

Before and after all hooks are still on the todo list.
