### ISSUE TITLE
[junit-platform-engine] TestSourceRead events emmited for features that wont be executed

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [cucumber/cucumber-jvm#2236]
**Describe the bug**
TestSourceRead emmited for every feature even for those that wont be executed due to cucumber tag expression was provided

**To Reproduce**
1. Create at least two feature files with one scenario each
2. Mark scenario in the first feature file with unique tag (e.g. @test)
3. Start test run using junit platform runner with given tag expression (provide cucumber.filter.tags="@test" property)
4. Check how many times TestSourceRead event emmited

**Expected behavior**
TestSourceRead should be emmited only for first feature that have scenario that suites provided tag expression (feature with scenario tagged with @test)

**Actual behavior**
TestSourceRead emmited for both feature files

**Context & Motivation**
This behavior not reproduced with Junit4 cucumber runner and command line cucumber runner
And makes useless such plugins like: https://github.com/allure-framework/allure-java/tree/master/allure-cucumber6-jvm
Cos due to extra TestSourceRead events invalid report generated

**Your Environment**
- cucumber core 6.9.1
- cucumber-junit-platform-engine 6.9.1
 - junit-platform-console-standalone 1.7.1

**Comment by mpkorstanje** [comment]
The expected behaviour is that `TestSourceRead` events are emitted for all test sources that have been read. These are intentionally not filtered, allowing reporting tools to to render these as skipped. 

You mentioned that JUnit 4 does not emit `TestSourceRead` for all test sources read. I can not reproduce this. You may want to provide an executable example that shows otherwise.

**Comment by ocherniavskyi-lohika-tix** [comment]
@mpkorstanje did you try with cucumber console runner? "io.cucumber.core.cli.Main"

**Comment by mpkorstanje** [comment]
Rather then going back and forth with both of us guessing and wasting time I'd prefer it if you were to show a minimal complete and executable example of your problem first. Preferably in the form of a github repo.

You can find an reasonable guide on creating an MCVE here, please follow it carefully:

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ocherniavskyi-lohika-tix** [comment]
@mpkorstanje 
each of execution methods gives different results:
io.cucumber.core.cli.Main:
![image](https://user-images.githubusercontent.com/47743040/107852450-6a349200-6e19-11eb-8419-fb86e1a6c1be.png)

junit4:
![image](https://user-images.githubusercontent.com/47743040/107852377-0c07af00-6e19-11eb-84a3-c54a797ea159.png)

junit5:
![image](https://user-images.githubusercontent.com/47743040/107852530-d911eb00-6e19-11eb-874c-bf5dd7b72f5e.png)

"These are intentionally not filtered, allowing reporting tools to to render these as not executed." so this unfiltered tests appears only for junit-platform

**Comment by ocherniavskyi-lohika-tix** [comment]
@mpkorstanje sorry to waisting your time, issue was due to implicit listener injection of allure (its automatically listening junit events) - so cucumber events was overlapped with junit events therefore - totally wrong report
