### ISSUE TITLE
Pass comments to JSON results file

### ISSUE THREAD

**Issue by fslev** [cucumber/cucumber-jvm#2237]
Right now, comments reside only inside the Gherkin feature file.
It would be very useful, especially for reporting plugins to be able to read these comments from the JSON report file.

Now, this issue was already raised in the past:
https://github.com/cucumber/cucumber-jvm/issues/1329

Reason why issue was not implemented:
```
I think that in general, steps should be self-explanatory. Ideally we don't want comments in Gherkin at all
```
However, a step should also be reusable. This means that same step can be invoked over and over again, with different input parameters. _For example:_
```gherkin
When I invoke XYZ Service API with requestBody=<pathToFileWithLargeRequestBody> and check response={"status":200}
```
This step can be invoked within many scenarios with different inputs.
Since this step is so generic (thus, quite reusable), I need some comments on it, in order to describe what I want to achieve.

Having these comments inside a report, will make it much more readable.

**Comment by aslakhellesoy** [comment]
We're not making any more changes to the JSON format. In fact, the long term goal is to deprecate it and phase it out in favour of [cucumber messages](https://github.com/cucumber/cucumber/tree/master/messages#cucumber-messages).

The Cucumber Messages format preserves comments. You can get them from the `comments` property on [GherkinDocument](https://github.com/cucumber/cucumber/blob/master/messages/messages.md#gherkindocument) messages. Alternatively, the entire [source](https://github.com/cucumber/cucumber/blob/master/messages/messages.md#io.cucumber.messages.Source) is also available.
