### ISSUE TITLE
Gradle -Dcucumber.options doesn't override the Junit cucumberOptions  from cucumber v6.0.0

### ISSUE THREAD

**Issue by SaravananAnnatchi** [cucumber/cucumber-jvm#2240]
**Describe the bug**
When I pass cucumber.options using gradle command, It does not override the Junit cucumberOptions. It just ran all the test cases based on Junit Runner cucumberOptions configured in the project. Till v5.7.0 If we pass cucumber options from Gradle command, It used to override the Junit cucumberOptions setup in the project with the support of below property in build.gradle
test {
    systemProperty "cucumber.options", System.getProperty("cucumber.options")
} 
It has stopped working from v6.0.0 onwards

**To Reproduce**
1. Configure Junit runner in the project to run all the test cases if suppose we don't pass any cucumberOptions from Gradle command
eg:
```
@RunWith(Cucumber.class)
@CucumberOptions(features = "src/test/resources/features/",
       tags = "not @ignore",
        glue = "stepDefinations",
        plugin = {"pretty" ,"html:build/cucumber-report/cucumber.html", "json:build/cucumber-report/cucumber.json"})
public class Runner {
}
```
2. Configure the property inn the build.gradle to override the Junit runner configuration
```
test {
    systemProperty "cucumber.options", System.getProperty("cucumber.options")
} 
```
3. Now try to run the test with gradle command with -Dcucumber.options in it
eg: gradle clean test -Dcucumber.options="--tags 'not @ignore' src/test/resources/features/Get.feature"
4. Till v5.7.0 it used to run specific test cases based on gradle cucumber.options. From v6.0.0 Gradle -Dcucumber.options doesn't override the Junit cucumberOptions.

**Expected behavior**
With all the above configuration mentioned in the steps to reproduce, it is expected to run the test cases only matching the Gradle cucumber.options .

**Context & Motivation**

When I try to run specific test cases from Jenkins, It doesn't support. It just runs all the test cases in the project.

**Your Environment**
 - Cucumber v6.0.0
 - Windows
 - Gradle v6.8.2

**Comment by mpkorstanje** [comment]
`cucumber.options` was deprecated in v5 and removed in v6. There should be a warning in your logs informing you of this. Starting with v5 you can use individual properties for each option. See:

https://github.com/cucumber/cucumber-jvm/tree/main/core#properties-environment-variables-system-options

**Comment by SaravananAnnatchi** [comment]
Thanks for your comments @mpkorstanje
