### ISSUE TITLE
Cucumber Option monochrome does not work as expected

### ISSUE THREAD

**Issue by ufjena** [cucumber/cucumber-jvm#2246]
The class io.cucumber.junit.CucumberOptions contains the following code:

  @return true if terminal output **should be without colours**.
 boolean monochrome() default false;

But monochrome = true makes the **output more readable**.

**Solution**
Give the option a different name.
Set the default value to true.

**Comment by mpkorstanje** [comment]
The weird characters you are looking at are [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code). They can be used to add colour to the output. It look really nice if you have a terminal that supports them.

![image](https://user-images.githubusercontent.com/6946919/109329279-ae348780-785a-11eb-9a2f-d776eb8dbe2d.png)

The naming and documentation of `monochrome` is however a bit unfortunate. 

We could consider adding `--disable-ansi-colors` as an alias of  `monochrome`.

**Comment by ufjena** [comment]
The default value should be true. 
If my Eclipse console doesn't support color output, i wonder about the strange output:
  [32mGiven [0m[32m"[0m[32m[1mChrome_1024x768[0m[32m" is open[0m                                                                                         [90m# posters.cucumber.support.DriverHooks.setUp(java.lang.String)[0m
  [32mWhen [0m[32mhomepage is loaded[0m 
 
instead of
  Given "Chrome_1024x768" is open
  When homepage is loaded

**Comment by laeubi** [comment]
For Eclipse you can install https://github.com/mihnita/ansi-econsole

**Comment by ufjena** [comment]
The default value should be true. 
If my Eclipse console doesn't support color output, i wonder about the strange output:
  [32mGiven [0m[32m"[0m[32m[1mChrome_1024x768[0m[32m" is open[0m                                                                                         [90m# posters.cucumber.support.DriverHooks.setUp(java.lang.String)[0m
  [32mWhen [0m[32mhomepage is loaded[0m 
 
instead of
  Given "Chrome_1024x768" is open
  When homepage is loaded

**Comment by ufjena** [comment]
Thanks for the tip @laeubi. It works.

**Comment by ufjena** [comment]
@laeubi Thanks for the tip. It works fine.

**Comment by mpkorstanje** [comment]
> The default value should be true.

No. Most consoles support colors.
