### ISSUE TITLE
Eclipse's JUnit runner confused again

### ISSUE THREAD

**Issue by gisode** [cucumber/cucumber-jvm#225]
Context is the same as in #211.

Given 

```
Scenario Outline: Outline 1
  When foo
  Then bar concerning <fluffy thing>

  Examples:
    | fluffy thing          |
    | a fluffy spiked club  |

Scenario Outline: Outline 2
  When foo
  Then bang bang concerning <spiky thing>

  Examples:
    | spiky thing           |
    | a fluffy spiked club  |
```

The JUnit Descriptions of the `When foo` steps in both scenario outlines will be Java-equal because the scenario name in this case is the Examples row, which is the same for both outlines.

Any ideas how this could be fixed? We really need a unique identifier for steps to solve this once and for all. `hashCode()` springs to mind but is ugly.

**Comment by mpkorstanje** [comment]
Since we've moved to junit-4.12 and we're not using proper unique id's based on featurepath:pickleLine:pickleStepLine I'm closing this issue.
