### ISSUE TITLE
Exception thrown from a `TestRunStarted` Event Handler does not fail test run

### ISSUE THREAD

**Issue by MaxWaterfall** [cucumber/cucumber-jvm#2266]
**Describe the bug**
I'm not sure if this is a bug or intended behaviour. 

When an exception is thrown from a `TestRunStarted` event handler, the test run does not fail. Instead, 0 tests are run. Because 0 tests are run, our build pipeline passes, even though our tests have not been run.

**To Reproduce**
Throw an exception from a `TestRunStarted` event handler like so:
```java
  @Override
  public void setEventPublisher(EventPublisher eventPublisher) {
    eventPublisher.registerHandlerFor(
        TestRunStarted.class,
        ignored -> {
            throw new RuntimeException("Test");
        });
  }
```

Then run a test.

**Expected behavior**
The test run fails in some way, possibly by the test run process exiting with a non zero status code.

**Context & Motivation**
We setup infrastructure for our test run in a `TestRunStarted` event handler. When an exception occurs during this setup, we want our maven build to fail so that we get notified there is an issue.

**Your Environment**
```
Cucumber version: 6.9.1
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
```

**Additional context**
Currently we are using the following workaround:
```java
eventPublisher.registerHandlerFor(
    TestRunStarted.class,
    testRunStarted -> {
      try {
        // handle event
      } catch (Exception e) {
        // log error
        System.exit(1);
      }
    });
```

**Comment by MaxWaterfall** [comment]
I forget to mention: this is specifically when running with the cucumber-junit-platform-engine (https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine). I haven't tested with anything else.

**Comment by mpkorstanje** [comment]
At a glance it looks like Surefire is ignoring failures of the test engine root. When executing with the JUnit Platform Console Launcher any exceptions thrown from the root node are correctly reported. 

Would you mind filing a bug report with Surefire? As a reproducer you could include a minimal project that demonstrates the difference between the ConsoleLauncher and Surefire.  I believe that should be sufficiently convincing. You may also have to try the latest milestone releases of Surefire. 

```
Thanks for using JUnit! Support its development at https://junit.org/sponsoring

╷
└─ Cucumber ✘ OOps

Failures (1):
  Cucumber
    => java.lang.RuntimeException: OOps
       io.cucumber.junit.platform.engine.CucumberEngineDescriptor.before(CucumberEngineDescriptor.java:32)
       io.cucumber.junit.platform.engine.CucumberEngineDescriptor.before(CucumberEngineDescriptor.java:10)
       org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
       org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
       org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
       org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
       org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
       org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
       org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
       org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
       [...]

Test run finished after 103 ms
[         7 containers found      ]
[         0 containers skipped    ]
[         1 containers started    ]
[         0 containers aborted    ]
[         0 containers successful ]
[         1 containers failed     ]
[         8 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]


Process finished with exit code 1
```

**Comment by MaxWaterfall** [comment]
Thank you @mpkorstanje, this seems to be fixed in the latest milestone version for Surefire `3.0.0-M5`.
