### ISSUE TITLE
How to control the threadcount for the cucumber parallel execution for cucumber testng

### ISSUE THREAD

**Issue by santanughatak** [cucumber/cucumber-jvm#2269]
**Describe the bug**
Unable to control parallels execution with <name>dataproviderthreadcount</name>
script runs with the number of scenarios not with the number the thread values (described below).

**To Reproduce**
```javascript
<build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.1</version>
                    <configuration>
                        <release>11</release>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M5</version>
                    <configuration>
                        <properties>
                            <property>
                                <name>dataproviderthreadcount</name>
                                <value>1</value>
                            </property>
                        </properties>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build
```
Versions:
cucumber-testng: 5.6.0
cucumber-java: 5.6.0

**Comment by mpkorstanje** [comment]
Did you use the `@DataProvider(parallel = true)` annotation?

**Comment by santanughatak** [comment]
@mpkorstanje Yes I did
``` public class RunnerTest extends AbstractTestNGCucumberTests {
    @DataProvider(parallel = true)
    @Override
    public Object[][] scenarios() {
        return super.scenarios();
    }
} ```

**Comment by mpkorstanje** [comment]
So when you say:

>  runs with the number of scenarios

What exactly does that mean?

**Comment by santanughatak** [comment]
@mpkorstanje 
for example if a feature has 10 scenario and I run my script, all scenarios are running in parallel. Dosen't matter what is the dataprovider thread count you gave. 
Ex:
```javascript
 <property>
    <name>dataproviderthreadcount</name>
    <value>1</value>
</property>
```

**Comment by mpkorstanje** [comment]
If that is happening, then it's happening somewhere inbetween Surefire and TestNG rather then Cucumber. 

If all your scenarios are running parallel then this means that TestNG is calling `runScenario` in the `AbstractTestNGCucumberTests` in parallel. So you may want to debug Surefire and TestNG or if that doesn't get you anywhere create a minimal reproducer and ask on Stackoverflow.

https://github.com/cucumber/cucumber-jvm/blob/0f975e3e0dfe2164402be9536e3c6a3e29bdfb55/testng/src/main/java/io/cucumber/testng/AbstractTestNGCucumberTests.java#L26-L32

**Comment by santanughatak** [comment]
@mpkorstanje sure thank you
