### ISSUE TITLE
Release all Cucumbers with taggable rules

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-jvm#2284]
Need to release each of these Cucumbers with a dependency on gherkin v18

- [x] cucumber-ruby
- [x] cucumber-js
- [ ] cucumber-jvm

**Comment by mattwynne** [comment]
@mpkorstanje Ruby and JS are done, so I figured it's best to make this a ticket in the Cucumber-JVM repo now, for release with your next major version I guess?

**Comment by mpkorstanje** [comment]
Looking at the change log it should be in the next patch and looking at the commits nobody broke the rules and the repo is in a releasable state.

You can make the release if you want.

**Comment by mattwynne** [comment]
Cool!

Let's agree on the next version number though. For Ruby there was a [major version bump](https://github.com/cucumber/cucumber-ruby/blob/master/CHANGELOG.md#v600) though I see that @davidjgoss didn't feel that was neccesary and put it out in a [minor release](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#710-2021-04-06).

What are your thoughts? Do internal major upgrades neccesetate a major version bump of the main package? I don't thinkI have a strong opinion either way at this stage.

**Comment by davidjgoss** [comment]
From a cucumber-js perspective, there were no breaking changes for users, just tags on rules worked where they didn’t before. I don’t think we even had to change our internal touch points with gherkin, except for the streams library being split out (which was unrelated).

With cucumber-ruby looks like some deprecated things were removed which might be the reason for the major?

**Comment by mpkorstanje** [comment]
> Do internal major upgrades neccesetate a major version bump of the main package? I don't thinkI have a strong opinion either way at this stage.

We follow semver. Public api didn't change so we can continue.
