### ISSUE TITLE
Allow using a HTTP proxy to send results

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#2285]
We should allow users behind a HTTP(S) proxy to publish results. See https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html

**Comment by aslakhellesoy** [comment]
We should make sure all implementations use the same environment variables to configure proxy settings.

* https://github.com/cucumber/cucumber-ruby/issues/1526
* https://github.com/cucumber/cucumber-js/issues/1644

**Comment by mpkorstanje** [comment]
At this point it would be prudent to replace the `HttpURLConnection` with a proper shaded http client. When using the `http.*` properties will affect all components in `java.net` including those of the system under tests. So this may not be feasible. Especially in more complicated setups.

**Comment by mpkorstanje** [comment]
Java 11 does come with a `HttpClient` that is an overall improvement over the `HttpURLConnection`, but as Cucumber is currently still on Java 8 we can not use this yet.  We do have a major version in the works that would allow us to increase the minimum version of the JRE on which Cucumber is ran.

https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html

**Comment by aslakhellesoy** [comment]
Can't we just use a `java.net.Proxy` object and take the configuration from cucumber-specific environment variables? For example:

* `CUCUMBER_PUBLISH_HTTP_PROXY_HOST`
* `CUCUMBER_PUBLISH_HTTP_PROXY_PORT`

**Comment by mpkorstanje** [comment]
Not on a `HttpURLConnection`, you could create a `URL` instance with a custom implementation of `URLStreamHandler` but that's all sorts painful.

**Comment by aslakhellesoy** [comment]
> Not on a `HttpURLConnection`, you could create a `URL` instance with a custom implementation of `URLStreamHandler` but that's all sorts painful.

Why not? 

At https://github.com/cucumber/cucumber-jvm/blob/0a101a30464e9ba68432dd21d67e426aeb2d01bb/core/src/main/java/io/cucumber/core/plugin/UrlOutputStream.java#L72 we could pass in a proxy object. See https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#openConnection%28java.net.Proxy%29

**Comment by mpkorstanje** [comment]
Didn't even know you could do that.

**Comment by mpkorstanje** [comment]
We can probably extend the curl option syntax with the curl option for proxy:

```
curl https://example.com -x http://<proxy>:<port>
```

**Comment by aslakhellesoy** [comment]
> We can probably extend the curl option syntax with the curl option for proxy

Ooo nice idea!!!

**Comment by mpkorstanje** [comment]
And if we could use `PluginOption.forClass` with a curl option as an argument this would also be a bit simpler:

```java
    private List<Plugin> getPublishPlugin() {
        if (!enablePublishPlugin) {
            return emptyList();
        }
        if (publishToken != null) {
            return singletonList(PluginOption.forClass(PublishFormatter.class, publishToken));
        }
        if (publish) {
            return singletonList(PluginOption.forClass(PublishFormatter.class));
        }
        if (publishQuiet) {
            return emptyList();
        }
        return singletonList(PluginOption.forClass(NoPublishFormatter.class));
    }
```

Esp because then we wouldn't need `CucumberProperties.create();` in `PublishFormatter` which doesn't look at at `junit-platform.properties`.

```java
    private static CurlOption createCurlOption(String token) {
        Map<String, String> properties = CucumberProperties.create();
        String url = properties.getOrDefault(PLUGIN_PUBLISH_URL_PROPERTY_NAME, DEFAULT_CUCUMBER_MESSAGE_STORE_URL);
        if (token != null) {
            url = url + String.format(" -H 'Authorization: Bearer %s'", token);
        }
        return CurlOption.parse(url);
    }
```

**Comment by yasi512** [comment]
Is there any progress?
