### ISSUE TITLE
[ERROR]ParallelRunner>AbstractTestNGCucumberTests.tearDownClass:53

### ISSUE THREAD

**Issue by LiyakathPandu** [cucumber/cucumber-jvm#2287]
**Describe the bug**
Getting below error while using cucumber testng parallel execution

[ERROR]   ParallelRunner>AbstractTestNGCucumberTests.tearDownClass:53

ParallelRunner --> This is my parallel execution runner class. Below is the snippet

```
import org.testng.annotations.DataProvider;

import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;

@CucumberOptions(plugin = { "com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:",
		"json:target/cucumber/Cucumber.json",
		"rerun:reports/rerun.txt" }, features = "src/test/resources", glue = "com.stepdefinitions", tags = "@Different")

public class ParallelRunner extends AbstractTestNGCucumberTests {
	@Override
	@DataProvider(parallel = true)
	public Object[][] scenarios() {
		return super.scenarios();
	}

}
```

**To Reproduce**
Every time I am not getting that error. It's kind of an intermittent issue not sure how to reproduce it.

**Expected behavior**
At the end of execution as I mentioned my snipped it should generate Cucumber.json and rerun.txt file. Because of that error, both files are generating as null.

**Context & Motivation**

1. Using the Cucumber.json I am generating a cucumber report in Jenkins because of the empty file report generation is failing.
2. Using the rerun.txt file I am trying to rerun the failed scenarios in the Jenkins to reduce the failures of scenarios.

**Screenshots**
[ERROR]   ParallelRunner>AbstractTestNGCucumberTests.tearDownClass:53 » ClassCast io.cuc...

This is the error getting in the Jenkins console. It is not printing a complete error.

**Your Environment**
 - Versions used - [6.10.2]
 - Build tool [Maven and Jenkins]

**Additional context**
Scenarios are running but because of that error JSON,rerun.txt and HTML file also not generating.

**Comment by LiyakathPandu** [comment]
ParallelRunner>AbstractTestNGCucumberTests.tearDownClass:53 » NullPointer

I have observed one more error causing the same issue

**Comment by mpkorstanje** [comment]
> This is the error getting in the Jenkins console. It is not printing a complete error.

Without a full stack trace there is little anyone can do to help you.

However `ClassCast io.cuc...` suggests that there is a problem casting one class to another, typically this is caused by incompatible dependencies. You do happen to be using 

```
plugin = { "com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:",
```

So that would be first place to look. You can also use maven to display your dependencies and transitive dependencies.
