### ISSUE TITLE
How can I work with multiple spring boot cucumber contexts?

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [cucumber/cucumber-jvm#2294]
Hi,
I want to use a central module to create java cucumber java tests.
The module imports import different micro services projects and I have to create different cucumber spring contexts für each service.
The test cases (features, step functions,..)  are split into separate packages corresponding to the referenced micro services projects.

But I get this error if from cucumber

`io.cucumber.core.backend.CucumberBackendException: Glue class class milesahead.aal.customer.CucumberCustomerTest and class milesahead.aal.analyzer.CucumberAnalyzerTest are both annotated with @CucumberContextConfiguration.
Please ensure only one class configures the spring context`

QUESTION:  Is it possible to use different spring contexts in one cucumber project? If so - could you provide a little example?

@mpkorstanje you posted the same question in gitmemory - any update from your side?

If this setup should work in general but you don't have the time to setup an example - I can try to create a (non-working) multimode example...

**Comment by mpkorstanje** [comment]
In general: Yes, but you must execute cucumber multiple times. Once for each module, each time with a different glue path.

 * If you are using the CLI (directly or through an IDE), provide the `--glue` argument for the module your features are in.

  * If you are using `cucumber-junit` please read the java doc on [`Cucumber.class`](https://github.com/cucumber/cucumber-jvm/blob/main/junit/src/main/java/io/cucumber/junit/Cucumber.java#L66-L71) and [`CucumberOptions`](https://github.com/cucumber/cucumber-jvm/blob/main/junit/src/main/java/io/cucumber/junit/CucumberOptions.java#L46-L69). In brief, move and duplicate the `@RunWith(Cucumber.class)` annotated class into the package of each module.
  
 * If you are looking to use `cucumber-junit-platform-engine` then you can use https://github.com/junit-team/junit5/pull/2416 to declare multiple suites. Select the package using [`@SelectPackages`](https://github.com/junit-team/junit5/blob/main/junit-platform-suite-api/src/main/java/org/junit/platform/suite/api/SelectPackages.java) and use [`@ConfigurationParameter`](https://github.com/junit-team/junit5/blob/main/junit-platform-suite-api/src/main/java/org/junit/platform/suite/api/ConfigurationParameter.java) to set [`cucumber.glue`](https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine#configuration-options) for each module.

    Note: You'll find that this intentionally under documented. Until Cucumber JVM v7 and JUnit 5.8 are released `cucumber-junit-platform-engine` is not a feature complete replacement for `cucumber-junit`. Until then I am expecting that users have a good understanding of all parts involved. If this does not apply to you then you would be better of using `junit-vintage` in combination with `cucumber-junit`.

**Comment by mpkorstanje** [comment]
That said, the exception could be clearer and should explain that:

 * Cucumber scans the glue path for context configuration
 * Cucumber defaults to scanning the class path root unless glue is explicitly configured
 * Generically direct users to the documentation for their runner (e.g. CLI, `cucumber-junit`, ect)

https://github.com/cucumber/cucumber-jvm/blob/main/spring/src/main/java/io/cucumber/spring/SpringFactory.java#L93-L94

**Comment by Miles-Ahead-Digital** [comment]
Hi,
I created an example [repository](https://github.com/Miles-Ahead-Digital/cucumber-multimodule)  using JUnit5 and Spring Context.  The "acceptance" module bundle the acceptance test for the module service2 and the module service2.

Please advise how to apply the solution mentioned above to  the acceptance module 

Thanks a lot in advance
Stefan
