### ISSUE TITLE
Multiple tags are not working

### ISSUE THREAD

**Issue by anbajaj** [cucumber/cucumber-jvm#2295]
**Describe the bug**
Multiple tags are not working

**To Reproduce**
1. Try passing multiple tags as ` -Dcucumber.filter.tags="@TAG1and @TAG2"` in your maven goal

**Expected behavior**
Feature files with both the tags should be executed however the execution is failing with below exception:
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

Please see below the dependencies & the version which we are using:
`<dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>6.10.3</version>
</dependency>
<dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <version>6.10.3</version>
</dependency>
<dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-jvm</artifactId>
            <version>6.10.3</version>
            <type>pom</type>
</dependency>
<dependency>
            <groupId>tech.grasshopper</groupId>
            <artifactId>extentreports-cucumber6-adapter</artifactId>
            <version>2.8.0</version>
</dependency>`

Thank You.

**Comment by aslakhellesoy** [comment]
You’re missing a space before the and.

**Comment by anbajaj** [comment]
looks like there is no exception however the cucumber report shows: No match found for: "undefined" statement.

Below are the console logs at the end of the execution:

[INFO] Running TestSuite
<2021-05-10 12:07:18,601> <main> <INFO> <EnvironmentSetup>: setting environment properties..
┌──────────────────────────────────────────────────────────────────────────┐
│ View your Cucumber Report at:                                            │
│ https://reports.cucumber.io/reports/74e4e6ff-7ebc-4039-a38d-61a2bac7769f │
│                                                                          │
│ This report will self-destruct in 24h.                                   │
│ Keep reports forever: https://reports.cucumber.io/profile                │
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.582 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

**Comment by mpkorstanje** [comment]
> looks like there is no exception however the cucumber report shows: No match found for: "undefined" statement.

This is a bit ugly but indicates that no scenarios were executed. https://github.com/cucumber/common/issues/1539

> It was just a typo I believe. It's not working even with a space i.e. `-Dcucumber.filter.tags="@TAG1 and @TAG2"`

It's most likely that you do not have any features or scenarios tagged with both `@TAG1` and `@TAG2`. If you meant to run scenarios tagged with either `@TAG1` or `@TAG2` you should use `-Dcucumber.filter.tags="@TAG1 or @TAG2"`.

If this does not solve your problem please create a minimal reproducer using the [cucumber-java-skeleton](
https://github.com/cucumber/cucumber-java-skeleton) and open a new issue.

**Comment by anbajaj** [comment]
@mpkorstanje It looks like the keyword (AND or OR ) was the issue. I tried with Dcucumber.filter.tags="@TAG1 or @TAG2" & it worked perfectly fine. Thank you and it looks like you have already reported an issue in cucumber report file when where are are no matching tags.
