### ISSUE TITLE
Cannot choose between the following variants of project :api: - productionRuntimeClasspath - runtimeElements

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [cucumber/cucumber-jvm#2296]
If I run my cucumber gradle task in project which references an (api) module. This Error is thrown:

```
* What went wrong:
Execution failed for task ':micro:service1:cucumber'.
> Could not resolve all files for configuration ':micro:service1:cucumberRuntime'.
   > Could not resolve project :api.
     Required by:
         project :micro:service1
      > Cannot choose between the following variants of project :api:
          - productionRuntimeClasspath
          - runtimeElements
        All of them match the consumer attributes:
          - Variant 'productionRuntimeClasspath' capability milesahead.aal:api:0.0.1-SNAPSHOT:
              - Unmatched attributes:
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
          - Variant 'runtimeElements' capability milesahead.aal:api:0.0.1-SNAPSHOT:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.jvm.version '16' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it

```

I created a test [repository](https://github.com/Miles-Ahead-Digital/cucumber-apidep#readme)  to demonstrate the Error. Please check the Readme. 
If there is no module reference the tasks works.

Please advice.

**Comment by mpkorstanje** [comment]
While you seem to use Cucumber in your project it is not readily apparent that this is a problem with Cucumber.

To report a bug you should at least be able to describe what gradle expects from Cucumber and how Cucumber currently behaves.

As such I believe this question may be more suited to StackOverflow.

**Comment by Miles-Ahead-Digital** [comment]
Hi,

as described in the readme I defined the cucumber tasks in gradle which works with service2 (no api reference) but not with service1.

task cucumber() {
    dependsOn assemble, testClasses
    doLast {
        javaexec {
            main = "io.cucumber.core.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = ['--plugin', 'pretty', '--plugin', 'json:build/cucumber.json', '--plugin', 'html:build/cucumber-reports.html', '--glue', 'milesahead', 'src/test/resources']
        }
    }
}

**Comment by mpkorstanje** [comment]
So you are unable to configure gradle correctly. This does not appear to be a problem with Cucumber.
