### ISSUE TITLE
Getting tags from Command Line or Gradle 

### ISSUE THREAD

**Issue by goblinhecker** [cucumber/cucumber-jvm#2301]
Hi.

We use Cucumber for our testing (java based development) and I had a question.

Is it possible to retrieve the tag(s) used when running the java command. 

For example, if I run `./gradlew cucumber -Ptags="@smoke and @db2"` is it possible to get the tags `@smoke` and `@db2` ?

Similarly if I run `java -cp "*" io.cucumber.core.cli.Main *.feature --glue hellocucumber --tags "@regression and @aws"`, is it possible to get `@regression` and `@aws` from the code ?

I know there is getsourceTagNames which returns the scenario for the feature file, but I wanted the tags used to run the tests.

Thanks.

**Comment by mpkorstanje** [comment]
No. There is no such ability. But this question sounds very much like an example of the XY problem. What are you actually trying to do?

**Comment by goblinhecker** [comment]
Hi.

Our testing consists of testing different sources and target combination. Think [Debezium](https://debezium.io/). If you had to test end-to-end testing for Debezium you'd need to test replication works for all different sources and targets. i.e. replication between MySQL to Postgres, Postgres to Kafka, etc.

There are many possibilities.

One way to do this in feature files is have an example where you put the source and targets in data table and iterate over the combinations. That would work but if someone only wanted to test Debezium between MySQL to Kafka, they would have no way to specify this.

Another option would be to have a feature file and each example in the feature file is a different source - target combination. That is bad because it's just redundant lines of text.

So I thought of solving the problem by checking what tag was passed in the gradle or CLI. 

Our data table would be 
```
Tag              | Source | Target
MySQL-PG | MySQL | PG
PG-Kafka    | PG        | Kafka
```

When iterating over the combination, I want to check if the tag is passed in the gradlew or CLI command, if so run that combination. If not then skip it. 

Let me know what you think of this.

**Comment by mpkorstanje** [comment]
Sounds like the source and target are not a relevant part of the feature. The behavior doesn't change.

So you could extract these out to an environment variable, configuration file, or a dependency profile and run multiple suites, one for each combination. Most ci-systems have a matrix build feature for this.

And to make it easy on yourself, if no variable is defined, a default is picked.

**Comment by goblinhecker** [comment]
That sounds interesting. Can you provide more details please.

**Comment by mpkorstanje** [comment]
Not really. It's in essence the same as the mechanism by which you would select a browser in a build matrix. But now with two variables.

https://stackoverflow.com/questions/66374086/is-there-a-way-to-use-a-single-example-file-for-all-cucumber-test
