### ISSUE TITLE
Quarkus support

### ISSUE THREAD

**Issue by grandmaximum** [cucumber/cucumber-jvm#2302]
**Is your feature request related to a problem? Please describe.**
At our workplace we have been using Cucumber for some while now due to its excellent readability and the possibility to involve colleagues without coding knowledge into our testing process. However, we're currently migrating our code to Quarkus since we're jumping into OpenShift. Since Cucumber is only supporting JUnit 4 and Quarkus doesn't, the Quarkus team said that implementing Cucumber into Quarkus is currently impossible. 
https://github.com/quarkusio/quarkus/issues/11045

**Describe the solution you'd like**
For Cucumber to implement support for JUnit 5.

**Comment by mpkorstanje** [comment]
It is probably important to understand that Junit 5 isn't a monolith. Rather:

```
JUnit 5 = JUnit Platform + JUnit Jupiter + JUnit Vintage.
```

Cucumber currently supports JUnit 5 with the [cucumber-junit-platform-engine](https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine). Quarkus also supports JUnit 5 but as a JUnit Jupiter extension. While both JUnit 5, these are different things.

I can't verify this, but the solution suggested by @panchitoboy https://github.com/quarkusio/quarkus/issues/11045#issuecomment-825185972 looks like the correct one.

So we can support Qaurkus if you are willing to provide a pull request with a module that implements an `ObjectFactory` for Qaurkus. This module should behave reasonably like the other object factories and come with a minimal amount of documentation that explains its use. For example see [cucumber-spring](https://github.com/cucumber/cucumber-jvm/tree/main/spring).

The [example provided by panchitoboy](https://github.com/panchitoboy/quarkus-cucumber/blob/quarkus-target/src/test/java/CdiObjectFactory.java) looks usable as a starting point. Though you may want to move the starting of the application to the `start` method to ensure step definition instances are not shared between tests.

**Comment by mpkorstanje** [comment]
The Quarkus team has decided to support Cucumber through a quarkiverse plugin. When using `quarkus-cucumber` please direct any and all questions, issues, and bug reports there.

https://github.com/quarkusio/quarkus/issues/11045#issuecomment-894883127
