### ISSUE TITLE
Spring AOP doesnt work with Cucumber

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [cucumber/cucumber-jvm#2305]
**Describe the bug**
Seems spring aop doesnt work for classes loaded by cucumber Spring object factory

**To Reproduce**
create aspect: 

```
package com.foo

import org.aspectj.lang.ProceedingJoinPoint
import org.aspectj.lang.annotation.Around
import org.aspectj.lang.annotation.Aspect
import org.aspectj.lang.annotation.Pointcut
import org.springframework.stereotype.Component


@Aspect
@Component
class CucumberAspects {
    @Pointcut("@annotation(io.cucumber.java.DataTableType)")
    fun transformTemplatesInDatatable() {
    }

    @Around("transformTemplatesInDatatable()")
    fun doWrapDatatebleTranformers(pjp: ProceedingJoinPoint): Any {
        println("This should wrap all DataTableType")
        return pjp.proceed()
    }
}
```

Add some @DataTableType methods
execute cucumber test and check if "This should wrap all DataTableType" logged to console
**Expected behavior**
AOP should work cos classes created by spring

**Context & Motivation**
We need AOP in our test framework to reduce of code duplication

**Your Environment**
 - Cucumber: 6.9.1
 - SpingBoot: 2.4.2

**Comment by mpkorstanje** [comment]
>  AOP should work cos classes created by spring

So why doesn't it? Did you check to see if the aspect was registered in the right bean post processor? Did you check why the step definition beans were not post processed by this aspect? I think you might be missing `@ScenarioScope` to ensure the component is created in the same scope as the step definitions with the annotation but I don't know.

**Comment by ocherniavskyi-lohika-tix** [comment]
@mpkorstanje 
next class contains DataTableType methods:

```
@ScenarioScope
class DataTableTransformers @Autowired constructor(private val templateProcessor: TemplateProcessor) {
}
```
this class is a main configuration class:

```
@SpringBootTest(
    classes = [TestingApplication::class])
@CucumberContextConfiguration
class CommonStepsDefinitions(
    @Autowired private val vars: ContextVariables
) {}
```

test application:

```
@SpringBootApplication
@EnableConfigurationProperties(
    PlatformProperties::class, WiremockProperties::class, UserProfiles::class, OAuth2ClientProperties::class
)
@ComponentScan(
    "com.foo.*",
    excludeFilters = [ComponentScan.Filter(
        type = FilterType.REGEX,
        pattern = ["com\\.foo\\.client\\..*"]
    )]
)
class TestingApplication
```

we also had junit tests that works ok with AOP - with the same configuration

@mpkorstanje did you ever tried AOP with cucumber?

**Comment by mpkorstanje** [comment]
> @mpkorstanje did you ever tried AOP with cucumber?

Nope. But [`cucumber-spring`](https://github.com/cucumber/cucumber-jvm/tree/main/spring) is using Springs `TestContextManager` framework so the delta with JUnit is quite small. And since you know how to use AOP I'm also expecting you to be familiar enough with Spring internals to debug this.

>  next class contains DataTableType methods:

I don't see any method that could be targeted by ` @Pointcut("@annotation(io.cucumber.java.DataTableType)")`.

**Comment by ocherniavskyi-lohika-tix** [comment]
Gona create a dummy project

**Comment by mpkorstanje** [comment]
That's a good start. It will make it easier to debug your problem!

**Comment by mpkorstanje** [comment]
Just tried it. Got it to work almost instantly.

```
2021-05-18 03:02:32,167 [main] INFO  i.c.e.s.a.CucumberTestContextConfiguration - Started CucumberTestContextConfiguration in 3.602 seconds (JVM running for 6.61)
This should wrap all DataTableType
This should wrap all DataTableType
This should wrap all DataTableType
```

You don't have any method could be targeted by `@Pointcut("@annotation(io.cucumber.java.DataTableType)")`. That's your only problem.
