### ISSUE TITLE
JavaHookDefinitions should never be static

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#2310]
When using a `JavaHookDefinition` (@Before/After/BeforeStep/AfterStep`) Cucumber currently does not inform users that hook definitions probably should not be static. While the code itself is generic enough to correctly invoke a static hook definition [it does seem to confuse novice users](https://stackoverflow.com/questions/67725726/how-to-use-autowired-in-beforestep-cucumber-step-definition?noredirect=1#comment119716508_67725726).

So `createInvalidSignatureException` should be invoked when a hook is static.

```java
    @After
    public static void after() {
       // declaring this should result in an exception
    }
    

    @After
    public void after() {
       // this is fine
    }    
```

**Comment by laeubi** [comment]
I don't see why this should throw an exception just for the sake that **spring**-users are confused when using DI in a wrong way ...

**Comment by mpkorstanje** [comment]
Cucumber is used by people without a lot of programming experience. So the more Cucumber can explain to them what they are doing wrong, the better.

Anyway, do you have any concrete concerns? Will this impact some other use case in a bad way?

**Comment by kishore262** [comment]
Hello, I would like to try this as a first issue, trying to contribute to OSS. Can you give me a starting point in code which will help me get started with this issue?

**Comment by laeubi** [comment]
At least it will break existing codes without any value, to really help people (at least a basic understand of the used framework (spring here) should be assumed), the spring injection-module might better be enhanced to issue a warning/error instead of cucumber itself.

**Comment by mpkorstanje** [comment]
I'm looking for a scenario where it might be useful to have static hooks and step definitions -- regardless of the dependency injection container used. Something like https://github.com/cucumber/cucumber-jvm/issues/1950, https://github.com/cucumber/cucumber-jvm/pull/1953.

**Comment by laeubi** [comment]
Maybe its more a style thing, but if a method do not reference any instance field I prefer to make it static and as it is already supported why remove this support for little gain?

**Comment by mpkorstanje** [comment]
Fair enough. That makes sense.

@kishore262 I'm afraid you'll have to look at any one of the other issues tagged as help wanted.
