### ISSUE TITLE
How can I execute code only once?

### ISSUE THREAD

**Issue by agustingonzalez93** [cucumber/cucumber-jvm#2312]
For example, I have a feature with 40 scenarios. I want to execute a method only the first time before scenario 1. This should be like this every time I run the automation.

**Comment by mpkorstanje** [comment]
A before hook and a static variable should do the trick. 

https://zsoltfabok.com/blog/2012/09/cucumber-jvm-hooks/

Better support will come with the next major version (release date very much on available time)

https://github.com/cucumber/cucumber-jvm/issues/515
