### ISSUE TITLE
Run feature files parallel with Gradle

### ISSUE THREAD

**Issue by KrisztianZagonyiGrad** [cucumber/cucumber-jvm#2317]
**Is your feature request related to a problem? Please describe.**
Do cucumber supports running the feature files parallel with Gradle by officially?
I saw some old third party solutions, and I also saw the official documentation with maven, and it works perfect, but I would like to do it with Gradle.
What is the newest and best and easiest way to do this?
Thank you. :)

**Comment by mpkorstanje** [comment]
The answer is complicated and there are no ideal solutions yet. See:

* https://github.com/gradle/gradle/issues/15435
* https://github.com/gradle/gradle/issues/4773

Though using the [`cucumber-junit-platform-engine`](https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine) might get you reasonably far. If not, consider using it in combination with the [JUnit Console Launcher](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher) in a custom task.

**Comment by KrisztianZagonyiGrad** [comment]
Thank you. :)
