### ISSUE TITLE
Retry failed scenarios

### ISSUE THREAD

**Issue by y5v** [cucumber/cucumber-jvm#2318]
Please add retry support for failed scenarios as `--retry` in cucumber-ruby

**Comment by mpkorstanje** [comment]
Cucumber JVM will not support retry. 

There is no generalized case in which Cucumber can decide what the right way to rerun a failed scenario would be. Nor can we decide how to report it for that matter. 

While it may seem fairly straightforward -- if a test fails retry it up to N times until passed -- in practice it has many complications. For example, if a build fails more then 20% of the tests, there is a good chance that the entire build is broken and retrying all failed tests N times would be a waste  of time. Dealing with this would then require a mechanism to abort early, ect, ect. And while we could make this infinitely configurable and extensible, this is a project mostly maintained by volunteers. As such the complexity cost simply isn't worth it. 

Instead you may want to consider directing your energy towards either:

1. improving the reliability of your tests or;
2. implementing your own rerun strategy.

You can implement your own rerun strategy using the `--plugin rerun:out.txt` option and then passing the resulting `out.txt` to cucumber as if it was a feature file for up to N times until your tests pass.

Alternatively JUnit 5 has [an excellent API for selecting, running and potentially rerunning failed tests](https://junit.org/junit5/docs/current/user-guide/#launcher-api). Cucumber integrates with JUnit 5 through the [cucumber-junit-platform-engine](
https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine).
