### ISSUE TITLE
CucumberLog4jAppender that appends to the Cucumber log

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#2326]
**Is your feature request related to a problem? Please describe.**

Some users use Log4j and want their application logs to end up in the reports.

**Describe the solution you'd like**

A `CucumberLog4jAppender` appender class that outputs to `Scenario#log`. Since a new scenario instance is created for each scenario, we would probably need a static method on the appender that can be called from a hook:

```java
﻿﻿@Before﻿
﻿﻿public void updateAppender(Scenario scenario) {
﻿﻿    CucumberLog4jAppender.setScenario(scenario)﻿
﻿﻿}
```

**Additional context**

This should probably be implemented in a separate sub project (`/log4j`).

**Comment by mpkorstanje** [comment]
This seems like the thing users can implement and maintain themselves without our assistance. What would be the benefit of providing this as part of cuucmber-jvm?

**Comment by mpkorstanje** [comment]
If you want to run this as an experiment consider:

 * Use a seperate repository e.g. `cucumber-jvm-log2scenario`
 * Instead of using annotated hooks, implement a `Backend` that adds these hooks directly to the glue.
 * There are multiple logging frameworks for java. Consider either providing modules for all of them or using SLF4J.

**Comment by aslakhellesoy** [comment]
> What would be the benefit of providing this as part of cuucmber-jvm?

It would benefit users since they have a ready-to-use library. It would benefit maintainers because they don't have to explain over and over again how to implement this. (It's a question we've received three times over the past month in the Intercom support for reports.cucumber.io).

I think it would be easier to manage releases if it were just another module in this repo.

**Comment by aslakhellesoy** [comment]
I've added back the `good first issue` label because it's something I don't think the core team is interested in implementing. I want to sign-post that this is something we would rely on the wider community to contribute.

**Comment by mpkorstanje** [comment]
> I think it would be easier to manage releases if it were just another module in this repo.

Maybe after the prototype/incubator stage is done.

Until you've nailed down all the problems the release frequency and general churn is going to be much higher. Not something you can do while also commiting to semver.

> I've added back the good first issue label because it's something I don't think the core team is interested in implementing. I want to sign-post that this is something we would rely on the wider community to contribute.

Given the amount of uncertainty in the exact shape of the solution, the lack of clear acceptance criteria, knowledge of, both Cucumber and logging frameworks required and general lack of clear direction this is any thing but a good first issue.

> It would benefit maintainers because they don't have to explain over and over again how to implement this. (It's a question we've received three times over the past month in the Intercom support for reports.cucumber.io).

So it would benefit SmartBear, not the maintainers. Though there is some overlap. Yet at the moment it sounds like SmartBear is not interested in sponsoring this.

Perhaps you can start with a lower cost investment and write a blog post instead.
