### ISSUE TITLE
JUnit tests not executed or failures with Junit 5 & Surefire >= 3.0.0-M4

### ISSUE THREAD

**Issue by void-spark** [cucumber/cucumber-jvm#2331]
**Describe the bug**
With the latest versions of the surefire plugin, no features are executed, or the run fails entirely.

**To Reproduce**
Use the example from: https://github.com/bonigarcia/mastering-junit5/tree/b19313dc1f6a1b7c4421e84ac9d6afd117c218d5/junit5-cucumber
Run it once, everything works fine (surefire 2.22.2):
```
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
```

In the POM, change surefire to 3.0.0-M3, all still good:
```
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
```

In the POM, change surefire to 3.0.0-M4, tests are executed (can check with stdout 'ADD' in steps), but not reported:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
ADD
ADD
ADD
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

In the POM, change surefire to 3.0.0-M5, tests are executed (can check with stdout 'ADD' in steps), but not reported,
and an error is logged:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[ERROR] jul 06, 2021 9:47:26 AM org.junit.platform.launcher.core.LauncherConfigurationParameters loadClasspathResource
[ERROR] INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/C:/workspace/IdeaProjects/junit5-cucumber/target/test-classes/junit-platform.properties].
ADD
ADD
ADD
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

**Context & Motivation**
We just want to use Junit5 + Cucumber, but with the latest versions of everything it just doesn't work.
Since the results are not reported to surefire, it also doesn't fail on errors, so we don't notice if there's a problem.

**Your Environment**
 - Cucmber 6.10.4
 - Junit-Jupiter 5.7.2
 - Windows 10
 - Maven 3.8.1

**Comment by mpkorstanje** [comment]
You may be expecting a bit too much from a milestone release.

That said, as you are using Cucumber through the JUnit Platform the problem is probably somewhere between Surefire and the JUnit Platform rather then Cucumber. You may want to file an issue there instead.

**Comment by mpkorstanje** [comment]
And I think it's because this section does not include a check for `isRootContainer`.

https://github.com/apache/maven-surefire/blob/aff6eebe59721ac3c318e277aaba711aca55aee6/surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java#L108-L110

**Comment by mpkorstanje** [comment]
And there is quite a few more bits of code that assume that tests have a class source.

**Comment by void-spark** [comment]
I'll revert to an older surefire version for now then. Wasn't actually sure what -M meant, I know -RC and -Beta and such :)
We come up with too many acronyms..
Sounds like the surefire team isn't really paying attention to non class sources, I guess Cucumber is one of the few (if any) frameworks using that.
Since this doesn't seem to be a Cucumber issue I'll close this one with this comment.
I'll hold off on posting an issue with them for now, it makes more sense to me for someone who actually understands what's going on to do that :) (And I'm not very fond of their Jira system :) ).

**Comment by void-spark** [comment]
And thank you for your attention, it's certainly appreciated :)

**Comment by mpkorstanje** [comment]
Let's keep this open. Just in case some one else has time to do the leg work.

**Comment by mpkorstanje** [comment]
See:
 * https://issues.apache.org/jira/browse/SUREFIRE-1896
 * https://issues.apache.org/jira/browse/SUREFIRE-1849

**Comment by aSemy** [comment]
Ah, I've just found this issue. Thanks for making it. 

I've discovered that excluding nothing and including all .java files results in one test running (even though I have ~250 scenarios. It's better than `Tests run: 0`...

```
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M5</version>
        <configuration>
          <excludes>
            <!-- Don't exclude any @Test by default -->
            <exclude/>
          </excludes>
          <includes>
            <include>**/*.java</include>
          </includes>
        </configuration>
      </plugin>
```

**Comment by mpkorstanje** [comment]
This is not a problem with Surefire. Please do not report additional instances. Do upvote the issue in their bug tracker:

https://issues.apache.org/jira/browse/SUREFIRE-1849

**Comment by aSemy** [comment]
If it's not an issue with Surefire, why are you linking to an open Surefire issue?

**Comment by mpkorstanje** [comment]
Fixed.

**Comment by mpkorstanje** [comment]
With Cucumber v7 and JUnit 5.8 we will deprecate `@Cucumber` in favour of `@Suite`. This should coincidently fix the issue with Surefire > M4. 

Add:

```xml
<dependency>
   <groupId>org.junit.platform</groupId>
   <artifactId>junit-platform-suite</artifactId>
   <version>${junit-platform.version}</version>
   <scope>test</scope>
</dependency>
```

Then use:

```java
package com.example;

import org.junit.platform.suite.api.ConfigurationParameter;
import org.junit.platform.suite.api.SelectClasspathResource;
import org.junit.platform.suite.api.Suite;

import static io.cucumber.junit.platform.engine.Constants.GLUE_PROPERTY_NAME;

@Suite
@SelectClasspathResource("com/exmaple")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.example")
public class RunCucumberTest {
}
```


To improve the readability of the reports provide the
`cucumber.junit-platform.naming-strategy=long` configuration parameter.
