### ISSUE TITLE
Memory Leak on ThreadLocalRunnerSupplier 

### ISSUE THREAD

**Issue by jparams** [cucumber/cucumber-jvm#2334]
**Describe the bug**
ThreadLocalRunnerSupplier leaks memory because the thread local is not cleared at the end of the test.

The simplest fix would be to add a finalize method which clears the thread local. As your compile target is Java 8, this should still be fine. The other option is to make the supplier closable, and make sure the supplier is closed at the end of the test.

**Comment by mpkorstanje** [comment]
Could you explain the circumstances needed to reproduce this? 

Afaik once the `ThreadLocalRunnerSupplier` is eligible for garbage collection so should the thread local be.

**Comment by jparams** [comment]
The thread local will be garbage collected once the Thread is garbage collected, not when ThreadLocalRunnerSupplier is garbage collected.

Admittedly, I am not using Cucumber in the most conventional way, but I have a wrapper around Cucumber to run the same set of tests several times. The idea is to simulate a soak test. However, each execution of Cucumber leaks memory and eventually my soak test end with an out of memory error.

**Comment by mpkorstanje** [comment]
With normal use both the thread using the threadlocal and the threadlocal are eligible for garbage collection. So no references should remain. Do you have a memory dump or a reproducer?

**Comment by mpkorstanje** [comment]
Unless you can show this is a problem with normal use of Cucumber through a *minimal* reproducer in the form of a github repo I'm not going to make any affordances for this now and in the long run the thread locals will be removed. So this issue should eventually be moot.
