### ISSUE TITLE
How do we migrate the existing cucumber-java8 step definitions to cucumber-lambda style once deprecated?

### ISSUE THREAD

**Issue by mithunkoppal** [cucumber/cucumber-jvm#2340]
**Is your feature request related to a problem? Please describe.**
Currently we have a lot of step definitions written using cucumber-java8. If and when cucumber-java8 is deprecated and we have to start using cucumber-lambda, is there a plan to provide a converter or a migration tool to convert the java8-style step definitions to cucumber-lambda-style?

**Comment by mpkorstanje** [comment]
There is not. Would you potentially be wiling to open source a solution?
