### ISSUE TITLE
Look up step definitions in other module

### ISSUE THREAD

**Issue by chasangchual** [cucumber/cucumber-jvm#2347]
**Describe the bug**
- using IntelliJ for development
- step definition java files are in the across modules. the those step definitions have its own package path and they are different.
- specified step definition packages with "glue" option
- one of module has a feature file. from the feature file, it is not able to refer steps in the different module 

**To Reproduce**
1. create a two modules, 'price' & 'product',  
2. create a step definition in com.my.price.steps package in price modules
3. create a step definition in com.my.product.steps package in product modules
4. create a **Feature file in price modules**, and it uses steps in com.my.price.steps and com.my.product.steps
5. on running, specify "glue" options with com.my.price.steps and com.my.price.steps
6. it fails to run because it was not able to find step definition in **product module**

**Expected behavior**
success to run the Feature with step definitions across modules.

**Context & Motivation**
single code repo has been split to multiple modules, and we want to share common step definitions across modules.
Seeing other had experienced the same issue, https://stackoverflow.com/questions/66909568/cucumber-doesnt-find-steps-definition-in-other-module

**Screenshots**

**Your Environment**
 - gradle cucumber dependencies used 
    testImplementation "io.cucumber:cucumber-java:6.10.4"
    testImplementation "io.cucumber:cucumber-spring:6.10.4"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:6.10.4"

 - Operating System and version [e.g. * Operating System and version:] mac os 11.2.3
 - Build tool [e.g. Apache Maven 3.6.0]: Gradle 6.5

**Comment by mpkorstanje** [comment]
> on running, specify "glue" options with com.my.price.steps and com.my.price.steps

Is this a typo or intentional?

**Comment by mpkorstanje** [comment]
@chasangchual when looking for features, Cucumber scans the entire classpath for features and glue unless configured otherwise. So when you are talking about modules. Are you talking about maven modules, modules in IDEA/Eclipse, java modules or something else?

**Comment by mpkorstanje** [comment]
Can't reproduce this. If any one can, please provide a reproducer in the form of a github repo.

**Comment by marodrigues20** [comment]
@mpkorstanje, could you provide a code where this is possible to do, please?

Note: Share it in Github if possible.

Many Thanks!

**Comment by mpkorstanje** [comment]
It works the way you can expect it to work. Do bear in mind the difference between `src/test` and `src/main` though.

If not, please feel free to make a bug report with a minimal reproducer in the form of a GitHub project.

I'm asking you to make the reproducer not to be glib. If you were using JUnit you'd have the same problem. So a small project will help you figure out what you don't know yet. In the long term that's way less work for everyone.
