### ISSUE TITLE
Cucumber JUnit Platform Engine does not honour Discovery Filters

### ISSUE THREAD

**Issue by jlink** [cucumber/cucumber-jvm#2348]
**Describe the bug**

If a discovery filter is set, e.g. when using Intellij JUnit Configuration with a Pattern, the Cucumber test engine ignores this filter and runs all tests regardless. 

This is mostly a problem when Cucumber is used together with other engines and only a subset of tests is supposed to run.

**Expected behavior**

DiscoveryFilter instances, which can be retrieved through `EngineDiscoveryRequest.getFiltersByType()` should be evaluated.

**Solution suggestion**

Here's the relevant code from the jqwik engine, which creates a predicate to use for filtering all test classes:

```
	private static Predicate<String> buildClassNamePredicate(EngineDiscoveryRequest request) {
		List<DiscoveryFilter<String>> filters = new ArrayList<>();
		filters.addAll(request.getFiltersByType(ClassNameFilter.class));
		filters.addAll(request.getFiltersByType(PackageNameFilter.class));
		return composeFilters(filters).toPredicate();
	}
```

**Comment by mpkorstanje** [comment]
The discovery request IDEA creates when using Pattern:

```
request = {DefaultDiscoveryRequest@1460} 
 selectors = {ArrayList@1465}  size = 2
  0 = {ClasspathRootSelector@1475} "ClasspathRootSelector [classpathRoot = file:///path/to/project/target/test-classes/]"
  1 = {ClasspathRootSelector@1476} "ClasspathRootSelector [classpathRoot = file:///path/to/project/target/classes/]"
 engineFilters = {ArrayList@1466}  size = 0
 discoveryFilters = {ArrayList@1467}  size = 2
  0 = {IncludeClassNameFilter@1542} "IncludeClassNameFilter that includes class names that match one of the following regular expressions: 'com.example.*'"
  1 = {ExcludeClassNameFilter@1543} "ExcludeClassNameFilter that excludes class names that match one of the following regular expressions: 'com\.intellij\.rt.*' OR 'com\.intellij\.junit3.*'"
```

Cucumber tests are located in feature files. As such they do not have a class to filter on and are not removed from the result.

By generically calling it "Pattern" IDEA is creating the wrong expectations. I would suggest that you file a ticket with IDEA to and request that their UI matches the semantics of discovery selectors and filters more closely.

Note: package filters are supported for feature files is located on the class path.

https://github.com/cucumber/cucumber-jvm/blob/5203c4c316bd7cb450cab962406317a0a0c78671/junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolver.java#L30-L33

**Comment by mpkorstanje** [comment]
Also note that if you are using the `@Cucumber` annotated class as a work around, it is only used when explicitly requested through a `ClassSelector` to accommodate Gradle and Surefire. 


https://github.com/cucumber/cucumber-jvm/blob/5203c4c316bd7cb450cab962406317a0a0c78671/junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java#L163-L171

**Comment by mpkorstanje** [comment]
I'll leave this issue open for some one to do the leg work with InteliJ.

**Comment by jlink** [comment]
@mpkorstanje I'd argue that as soon as there is a Include/ExcludeClassNameFilter present the cucumber engine should not run any tests since this discovery request is clearly targeted at class-based engines.

**Comment by mpkorstanje** [comment]
That doesn't seem consistent with the design of the API. `getFiltersByType` allows a  test engine to provide and look for its own `DiscoveryFilter` implementations. Other test engines can't honor such a filter so categorically you can not expect a test engine to honor all filters in a discovery request.

**Comment by jlink** [comment]
I think you're right in principle. The contract, however, of ClasspathRootSelector (and other selectors as well), is not clear enough. At the time of design, we did not consider the problem of combining class-based with file-based engines in a single discovery request. I know, because I was there.
That's why I think that the best a file-based engine can do is use heuristics to determine if the current discovery request is really aimed at it.

@junit-team @junit-team/junit-committers What do you think: Should we differentiate between Classpath selector for files / for classes / for both? Or should the filter contract be reworked to include filters that MUST be honoured?

**Comment by mpkorstanje** [comment]
The contract mentions both class files or resources:

> A DiscoverySelector that selects a classpath root so that TestEngines can search for class files or resources within the physical classpath — for example, to scan for test classes.

What is your objection to petitioning IDEA for support for a package filter?

**Comment by mpkorstanje** [comment]
At a glance the `ExcludeClassNameFilter` should have been  an `ExcludePackageNameFilter` anyway.

```
 discoveryFilters = {ArrayList@1467}  size = 2
  0 = {IncludeClassNameFilter@1542} "IncludeClassNameFilter that includes class names that match one of the following regular expressions: 'com.example.*'"
  1 = {ExcludeClassNameFilter@1543} "ExcludeClassNameFilter that excludes class names that match one of the following regular expressions: 'com\.intellij\.rt.*' OR 'com\.intellij\.junit3.*'"
```

**Comment by jlink** [comment]
> The contract mentions class files _or_ resources:
> 
> > A DiscoverySelector that selects a classpath root so that TestEngines can search for class files or resources within the physical classpath — for example, to scan for test classes.
> 

Exactly, we missed that only one of those may be wanted sometimes. 

> What is your objection to petitioning IDEA for support for a package filter?

No objection. It’s just that some of my „suggestions“ and bug issues with JetBrains have been open for years. I’m looking for pragmatic ways to solve problem timely.

**Comment by jlink** [comment]
If JetBrains was committed they'd already added an Engine filter, which would also solve my problem.

**Comment by mpkorstanje** [comment]
Tell me about it:

https://github.com/cucumber/cucumber-jvm/blob/bb8f6bb1e007870b79d8d43d828be6490b6d3189/core/src/main/java/io/cucumber/core/options/PluginOption.java#L65-L75

I've considered adding a special case for IDEA. The `'com\.intellij\.rt.*' OR 'com\.intellij\.junit3.*'` pattern in the string representation is a fairly descent indicator.

Unfortunately when using the context menu on a package  with feature files we see:

```
request = {DefaultDiscoveryRequest@1461} 
 selectors = {ArrayList@1466}  size = 2
  0 = {ClasspathRootSelector@1476} "ClasspathRootSelector [classpathRoot = file:///path/to/project/target/test-classes/]"
  1 = {ClasspathRootSelector@1477} "ClasspathRootSelector [classpathRoot = file:///path/to/project/target/classes/]"
 engineFilters = {ArrayList@1467}  size = 0
 discoveryFilters = {ArrayList@1468}  size = 2
  0 = {IncludeClassNameFilter@1543} "IncludeClassNameFilter that includes class names that match one of the following regular expressions: 'nl.ing.lovebird.cucumbertests\..*'"
  1 = {ExcludeClassNameFilter@1544} "ExcludeClassNameFilter that excludes class names that match one of the following regular expressions: 'com\.intellij\.rt.*' OR 'com\.intellij\.junit3.*'"
 ```

So I can't apply a pragmatic solution without also breaking the expected usage for Cucumber.

**Comment by mpkorstanje** [comment]
Hah. When using "All in directory" for any directory inside the project:

```
request = {DefaultDiscoveryRequest@1461} 
 selectors = {ArrayList@1466}  size = 2
  0 = {ClasspathRootSelector@1476} "ClasspathRootSelector [classpathRoot = file:///path/to/project/target/test-classes/]"
  1 = {ClasspathRootSelector@1477} "ClasspathRootSelector [classpathRoot = file:///path/to/project/target/classes/]"
 engineFilters = {ArrayList@1467}  size = 0
 discoveryFilters = {ArrayList@1468}  size = 2
  0 = {IncludeClassNameFilter@1543} "IncludeClassNameFilter that includes class names that match one of the following regular expressions: 'com.example'"
  1 = {ExcludeClassNameFilter@1544} "ExcludeClassNameFilter that excludes class names that match one of the following regular expressions: 'com\.intellij\.rt.*' OR 'com\.intellij\.junit3.*'"
```

And for any directory below the project:

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Jul 29, 2021 3:15:13 PM org.junit.platform.launcher.core.LauncherConfigurationParameters loadClasspathResource
INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/path/to/project/target/test-classes/junit-platform.properties].
Internal Error occurred.
org.junit.platform.commons.PreconditionViolationException: LauncherDiscoveryRequest must not be null
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:281)
	at org.junit.platform.commons.util.Preconditions.notNull(Preconditions.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:72)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by jlink** [comment]
It's a mess.

**Comment by mpkorstanje** [comment]
I'm not interested in work around that mess. 

Jetbrains fixes issues by "interest". So how about you create the issue. Tweet something snarky, and hopefully get people to vote for it.

**Comment by mpkorstanje** [comment]
I'll see if I can get some Cucumber folks to join up to.

@aslakhellesoy :point_up:

**Comment by jlink** [comment]
I'm not really sure which feature I'd like to request. If IntelliJ supported File/DirectorySelector this would not solve my problem. If IntelliJ supported EngineFilter it would not solve Cucumber's problem.

**Comment by mpkorstanje** [comment]
You request what you need, and I'll request what I'll need. I'm sure we can fit more then one link in a tweet.

**Comment by mpkorstanje** [comment]
One done:

https://youtrack.jetbrains.com/issue/IDEA-276463
