### ISSUE TITLE
Developer onboarding

### ISSUE THREAD

**Issue by gphilipp** [cucumber/cucumber-jvm#235]
Hi guys, 

I'm quite new to Cucumber but I really love it already.
I want to get involved and help get the first version out (I already coded a feature to add support for enums), but I have a few (unrelated) questions :
1. I'd like to add some acceptance tests for my feature but don't know what is the best way to to it ? I saw Aslak added .feature files in the picocontainer module when he added support the java.util.Calendar. But the converters code lives in core... Aren't the features supposed to live there too ?
2. How do you communicate with each other to ask questions related to cucumber-jvm development ? GH issues ? Chat ? Irc ? The cukes google group ?
3. Correct me if i'm wrong but it seems that the master branch currently doesn't pass the tests (because of Xstream not being correctly added as a dependency : test scope used instead of runtime, so that the CLI tests don't run). Did you add the XStream lib directly your IDE (gasp !) ?
4. How do you generate the cucumber (HMTL) reports ? With a maven plugin ? No command line tool like in ruby ?

Sorry for all these questions, but i'm having a hard time to grasp everything. I volunteer to put up a developer_getting_started .md if necessary to lay the foundations :)

Gilles

**Comment by mlvandijk** [comment]
2) Communication
Also: https://cucumberbdd.slack.com

@plaindocs - Let's include this info in the docs, if still up to date/relevant? So we could close this issue?
