### ISSUE TITLE
Deletion created stepdef class instance from container after test

### ISSUE THREAD

**Issue by SubinDenis** [cucumber/cucumber-jvm#2352]
When starting large amount of test cases (~11000, permissions cross checks) there is memory leaks in java, as I think, because of large amount of stepdef instances that are not clearing by GC. Those instances are linked to org.aspectj.weaver.loadtime.Aj$WeaverContainer.

Maybe it's possible to delete such instances automatically after test run?

**Comment by mpkorstanje** [comment]
Without more information on how to reproduce this problem I don't think there is anything any one can do to help you. Especially because `org.aspectj.weaver.loadtime.Aj$WeaverContainer` is not part of Cucumber so it is not clear what Cucumber should clean up after a test, if anything at all.

Would you be able to provide a minimal reproducer in the form of a github repository that shows this is a Cucumber problem?

**Comment by SubinDenis** [comment]
Test.feature is:
 ```
 Feature: Test

    Background:
      Given user authenticated with "login" "password"
      
    Scenario: user can do some action number 1
      And user try to doing someAction_1 and expect status "200"

    ...
		78 sce
	...

    Scenario: user can do some action number 80
      And user try doing someAction_80 and expect status "200"
```

AuthStepDefs.java:
```
...

public class AuthStepDefs {
  ...
  
  @Given("user authenticated with {string} {string}")
  public void authenticateWith(String login, String password) {
	int status = someAuthRestClient.authenticateWith(login, password);
	assertEquals(200, status)
  }
}
```

TestStepDefs.java:
```
public class TestStepDefs {
	
	...
	
	@And("user try to doing someAction_1 and expect status {string}")
	public void action(string expectedStatus) {
		int status = someComponentARestClient.doAction();
		assertEquals(expectedStatus, status);
	}
	
	
	...
		ommited steps
	...
	
	@And("user try to doing someAction_80 and expect status {string}")
	public void otherAction(int expectedStatus) {
		int status = someComponentARestClient.doOtherAction();
		assertEquals(expectedStatus, status);
	}
}
```

Test.feature repeated 150 times for variety of users to check security implementation. We have 150*80=12000 tests. Each test creates 2 instances - new AuthStepDefs, new TestStepDefs. 24000 instances allocated in memory and tests become clow. When I used exlipse memory analyzer it shows enormous classloader. Almost 80 percent of memory was filled with classloader. The largest object in classloader is org.aspectj.weaver.loadtime.Aj$WeaverContainer.

After MAT analyzer I tried to do some 'dumb' analyzing. 
Example:
```
public class Util {
 public static Map<Class, List<String>> objects;
}
```

In each constructor I added 
```
List<String> strings = Util.objects.get(this.getClass());
if (strings == null) {
  strings = new ArrayList<>();
}
strings.add(this.toString());
Util.objects.put(this.class, strings);
```

In the last step I printed content of Util.objects and got something like this:
```
AuthStepDefs: [AuthStepDefs@111111, AuthStepDefs@222222, ..., AuthStepDefs@xxxxxx],
TestStepDefs: [TestStepDefs@111111, ..., TestStepDefs@xxxxxx]
```

GC cannot clean space, because every stepdef instance are reachable from gc root. Those duplicate instances are not needed for tests, but we cannot delete it anyway.

**Comment by mpkorstanje** [comment]
> GC cannot clean space, because every stepdef instance are reachable from gc root. 

Could you show how they are reachable from root?

**Comment by mpkorstanje** [comment]
> Those duplicate instances are not needed for tests, but we cannot delete it anyway.

The duplicate instances of step definition are intentional. It ensures that each scenario runs in an isolated context, this prevents the state from one test influencing the other.

**Comment by mpkorstanje** [comment]
Just did a relatively simple check. Could not reproduce the issue. If you do think this is a issue caused by cucumber please provide a *minimal* example that reproduces the problem in the form of a Github repo.
