### ISSUE TITLE
getting error Could not resolve version conflict among [io.cucumber:cucumber-testng:jar:6.10.2 -> io.cucumber:cucumber-core:jar:6.10.2 -> io.cucumber:messages:jar:14.0.1, io.cucumber:cucumber-testng:jar:6.10.2 -> io.cucumber:cucumber-core:jar:6.10.2 -> io.cucumber:html-formatter:jar:12.0.0 -> io.cucumber:messages:jar:[14.0.1,15.0.0), io.cucumber:cucumber-testng:jar:6.10.2 -> io.cucumber:cucumber-core:jar:6.10.2 -> io.cucumber:create-meta:jar:3.0.0 -> io.cucumber:messages:jar:[14.0.1,15.0.0), io.qameta.allure:allure-cucumber6-jvm:jar:2.14.0 -> io.cucumber:gherkin:jar:18.0.0 -> io.cucumber:messages:jar:[15.0.0,16.0.0)]

### ISSUE THREAD

**Issue by rajgopalrajesh** [cucumber/cucumber-jvm#2355]
<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>6.10.2</version>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>6.10.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>6.10.2</version>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.1.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.1.0</version>
		</dependency>
		<dependency>
			<groupId>tech.grasshopper</groupId>
			<artifactId>extentreports-cucumber6-adapter</artifactId>
			<version>2.8.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-cucumber6-jvm</artifactId>
			<version>2.14.0</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-cucumber6</artifactId>
			<version>5.1.0-RC-3</version>
		</dependency>
[ERROR] Failed to execute goal on project API: Could not resolve dependencies for project API:jar:1.0-SNAPSHOT: Failed to collect dependencies for com..cortellis:API:jar:1.0-SNAPSHOT: Could not resolve version conflict among [io.cucumber:cucumber-testng:jar:6.10.2 -> io.cucumber:cucumber-core:jar:6.10.2 -> io.cucumber:messages:jar:14.0.1, io.cucumber:cucumber-testng:jar:6.10.2 -> io.cucumber:cucumber-core:jar:6.10.2 -> io.cucumber:html-formatter:jar:12.0.0 -> io.cucumber:messages:jar:[14.0.1,15.0.0), io.cucumber:cucumber-testng:jar:6.10.2 -> io.cucumber:cucumber-core:jar:6.10.2 -> io.cucumber:create-meta:jar:3.0.0 -> io.cucumber:messages:jar:[14.0.1,15.0.0), io.qameta.allure:allure-cucumber6-jvm:jar:2.14.0 -> io.cucumber:gherkin:jar:18.0.0 -> io.cucumber:messages:jar:[15.0.0,16.0.0)] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project API: Could not resolve dependencies for project com.thomsonreuters.cortellis:API:jar:1.0-SNAPSHOT: Failed to collect dependencies for com.thomsonreuters.cortellis:API:jar:1.0-SNAPSHOT
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:269)

**Comment by mpkorstanje** [comment]
You are using `allure-cucumber6-jvm`. You should probably report your issue with them.
