### ISSUE TITLE
Configure cucumber options via testNG xml is not working

### ISSUE THREAD

**Issue by Melkas** [cucumber/cucumber-jvm#2375]
**Describe the bug**
Configure cucumber options via testNG xml is not working
It is not seeing the tags, feature files and glue as well.

  ..suite name="Suite" parallel="tests" thread-count="3" data-provider-thread-count="6">
    ..parameter name="cucumber.filter.tags" value='@test100' />
           ..test name="IOS">
           ..parameter name="environment" value="Q1"/>
            ..parameter name="cucumber.glue" value="Steps"/>
            ..parameter name="cucumber.features" value="src/test/resources/Features/LoginScenarios"/>
            ..classes>
                ..class name="Runner.LOCAL.Regression.LocalRunner_IOS_Login"/>
             ../classes>
             ../test>

Thanks

**Comment by mpkorstanje** [comment]
They'll be picked up automatically in v7 https://github.com/cucumber/cucumber-jvm/pull/2354 in v6 you'll have to use https://github.com/cucumber/cucumber-jvm/pull/2351#issuecomment-893777031.

> You'll have to copy the `AbstractTestNGCucumberTests` and modify the setup step:
> 
> ```java
>     @BeforeClass(alwaysRun = true)
>     public void setUpClass(ITestContext context) {
>         XmlTest currentXmlTest = context.getCurrentXmlTest();
>         CucumberPropertiesProvider properties = currentXmlTest::getParameter;
>         testNGCucumberRunner = new TestNGCucumberRunner(this.getClass(), properties);
>     }
> ```
