### ISSUE TITLE
How to get scenario name by using tag name in dry run from cucumber runtime

### ISSUE THREAD

**Issue by shivaram24** [cucumber/cucumber-jvm#2380]
Hello,
 We are migrating our automation framework from **info.cukes** to **io.cucumber.**, Following implementation, was done using info.cukes runtimeoptions and it worked perfectly.

List<String> arguments = new ArrayList<>();
arguments.add(".featureFile");
arguments.add("--tags");
arguments.add(tagValue);
arguments.add("--dry-run");
arguments.add("--strict");
final String[] argv = arguments.toArray(new String[0]);
log.debug("Argument value for Dry Run: "+argv);
List<String> scenarioNames = new LinkedList<>();
try {
    RuntimeOptions runtimeOptions = new RuntimeOptions(new ArrayList<>(Arrays.asList(argv)));
    MultiLoader resourceLoader = new MultiLoader(this.getClass().getClassLoader());
    List<CucumberFeature> features = runtimeOptions.cucumberFeatures(resourceLoader);            
    for (int i = 0; i < features.size(); i++) 
        for (int j = 0; j < features.get(i).getFeatureElements().size(); j++)
            scenarioNames.add(features.get(i).getFeatureElements().get(j).getGherkinModel().getName());

Now I wanted to have a similar approach and I have tried the following option from io.cucumber runtimeoptions but, it retrieves all the feature file details not based on the tag value provided.

//Created runtimeOptions from cli --- 
https://github.com/cucumber/cucumber-jvm/blob/ad17c7416f64a9427d7cec3e362e2eb267560b2c/core/src/main/java/io/cucumber/core/cli/Main.java 

io.cucumber.core.options.RuntimeOptions runOptions = this.runTimeOptionIoCucumber(argv);;
FeatureParser featureParser = new FeatureParser(() -> new CommonFunction().getUUID());
FeaturePathFeatureSupplier featureFile = new FeaturePathFeatureSupplier(() -> Thread.currentThread().getContextClassLoader(), 
        runOptions, featureParser);
List<Feature> featuresNew = featureFile.get();

**Note**: Not looking for a solution with hooks option. 
Please guide if already have this feature available in io.cucumber. I did ask question in forums and never got an answer to this.

**Additional context**

**Comment by aurelien-reeves** [comment]
Could you please format your code snippets? If you need some help, you can take a look at github documentation: https://guides.github.com/features/mastering-markdown/

**Comment by mpkorstanje** [comment]
You can add your own plugins by providing the command line option `--plugin com.example.MyPlugin`, For examples of how to implement a plugin see the existing plugins.

https://github.com/cucumber/cucumber-jvm/blob/main/core/src/main/java/io/cucumber/core/plugin/PrettyFormatter.java
