### ISSUE TITLE
Customize cucumber.properties file location

### ISSUE THREAD

**Issue by jnowakowskiWR** [cucumber/cucumber-jvm#2384]
**Is your feature request related to a problem? Please describe.**
The path of `cucumber.properties` relies on `CucumberProperties` location. When using multimodule projects this might differs and force to create unwanted location (`src/test/resources`).

**Describe the solution you'd like**
Pass as task parameter `-Dcucumber.properties="tests/e2e/resources"` 

**Describe alternatives you've considered**
Add option to `@CucumberOptions`:
```java
@CucumberOptions(
  properties = "tests/e2e/resources"
)
```

**Comment by mpkorstanje** [comment]
Cucumber looks for `cucumber.properties` on classpath. Have you considered adding the folder `tests/e2e/resources` to the test resources in your build system?
