### ISSUE TITLE
"cucumber.features" is ignored from cucumber.properties file

### ISSUE THREAD

**Issue by fslev** [cucumber/cucumber-jvm#2390]
**Describe the bug**
It seems that Cucumber ignores the "cucumber.features" property defined inside the _cucumber.properties_ file

**To Reproduce**
I have the following light project which can be used for reproducing this issue:
https://github.com/fslev/cucumber-showcase

It contains one feature file defined inside "src/test/resources/features" directory:
```gherkin
Feature: Calculator feature

  @happy
  Scenario: Add two numbers (happy)
    * Check 3 + 2 = 5

  @negative
  Scenario: Add two numbers (negative)
    * Check 3 + 2 != 4
```
Inside "src/test/resources" I have the following cucumber.properties file:
```
cucumber.filter.tags=not @negative
cucumber.features=src/test/resources/features
```
And I've also defined the following test class (TestNG):
```java
public class CalculatorTest extends AbstractTestNGCucumberTests {
}
```

1.) Run tests via Maven command:
```
mvn clean test
```
Actual:
```
WARNING: No features found at classpath:/io/example
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

```

2.) Add the features option on CalculatorTest class:
```
@CucumberOptions(features = "src/test/resources/features")
public class CalculatorTest extends AbstractTestNGCucumberTests {
}
```
3.) Run tests again:
Actual:
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```
As you can see, now Cucumber was able to find the feature files, since I defined the path directly inside the @CucumberOptions
Also, It seems that "cucumber.filter.tags" was read from cucumber.properties file, since only one test was executed.
However, the "cucumber.features" is always ignored from cucumber.properties.

Reproduced issue with the following versions of Cucumber for Java: _**7.0.0-RC1, 6.10.4**_

**Comment by mpkorstanje** [comment]
This is intentional.

Unless otherwise specified through the `@CucumberOptions` the JUnit and TestNG runners suggest the package of the runner class as the feature and glue paths. This always replaces any suggestion from `cucumber.properties`.

I'd say the best solution would be to put the features in the same package as the runner. This plays nicely with the common practices for organizing resources in a java project and I'm at a complete loss why every tutorial insists on using `src/test/resources/features`.

**Comment by AgingOrange** [comment]
Maybe because of [this](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html)? That's the structure I run into everywhere. As a newcomer myself, could you give a concrete example where you would put the runner and feature files?

**Comment by mpkorstanje** [comment]
Packages are usually organized by reverse TLD. Something like `com.example.projectname`. So features should sit in the `src/test/resources/com/example/projectname` directory or a sub directory. For example see:

https://github.com/cucumber/cucumber-java-skeleton

**Comment by fslev** [comment]
I understand this.
However, this doesn't make the "cucumber.features" property inside _cucumber.properties_ file (documented [here](https://cucumber.io/docs/cucumber/api/) ) useless ?

**Comment by mpkorstanje** [comment]
It still works when using the CLI. Or when provided as a TestNG suite parameter, system property or environment variable. All these take precedence over the runner provided options. Other then that I do agree that the property itself is of very limited use.

**Comment by fslev** [comment]
Ok,
Thanks for the feedback.
I'll close this issue now.
