### ISSUE TITLE
Undeprecating TypeRegistryConfigurer

### ISSUE THREAD

**Issue by shayantabrizi** [cucumber/cucumber-jvm#2391]
Assume that we have a property type like this:
```
    @ParameterType("(,? (name=\"[asdfghjklqwertyuiop;@ZVB1346890]*\")|,? (family=\"[asdfghjklqwertyuiop;@ZVB1346890]*\")|,? (country=\"[asdfghjklqwertyuiop;@ZVB1346890]*\"))+")
    public ObjectParameters ObjectParameters(String... s) {
    }
```
that I want to use to define a step definition like this:
```
    @When("user adds an object with{ObjectParameters}")
    public void test(ObjectParameters parameters) {
           ...
    }
```
in order to make it reusable and match the following examples (which may be more useful if we have many parameters and most of them are optional):

- When user adds and object with name=ss, family=ss, country=ss
- When user adds and object with country=ss, family=ss, name=ss
- When user adds and object with family=ss

Now, assume that to be able to reuse sub-expressions and make the expression cleaner I want to make it like this:
```
String possibleCharacters = "asdfghjklqwertyuiop;@ZVB1346890";
    @ParameterType("(,? (name=\"[" + possibleCharacters + "]*\")|,? (family=\"[" + possibleCharacters + "]*\")|,? (country=\"[" + possibleCharacters + "]*\"))+")
    public ObjectParameters ObjectParameters(String... s) {
    }

    @ParameterType("(another parameter type (" + possibleCharacters + "*)")
    public AnotherParameters anotherParameterType(String... s) {
    }

```

However, it seems that we cannot use a variable in the annotation value. My solution is to use a TypeRegistryConfigurer to register the parameter types and use variables like possibleCharacters in it.
But, TypeRegistryConfigurer is deprecated and I fear it may be removed after a while.

Do you agree that implementing some scenarios like above is not possible with the annotation-based parameter types? If yes, shouldn't TypeRegistryConfigurer be undeprecated?

**Comment by mpkorstanje** [comment]
To re-use parts of a regular expression in a annotation you can use constants:

```
    private static final String POSSIBLE_CHARACTERS = "a-z";
    
    @ParameterType("name=[" + POSSIBLE_CHARACTERS + "]+")
    public ObjectParameters objectParameters(){
        ....
    }
```

Though for the use case you've provided like could be covered with a Datatable and data table transform instead:

```
  Scenario: Example
    Given some object parameters
      | name    | example-name    |
      | family  | example-family  |
      | country | example-country |
```

And while data tables are transformed into object without checking if the values make sense, you could consider adding validation after the transform using for example JSR 380.

**Comment by shayantabrizi** [comment]
Interesting. Thank you.

**Comment by shayantabrizi** [comment]
Could you please also give a hint on how your solution can be implemented when we are testing multiple examples?
For example, assume that we had something like this:
```
    user adds an object with name="<name>", family="<family>", country="<country>"
    user adds another object with name="<name>", family="<family>", country="<country>"
    Examples:
      | name     | family | country |
      | John  | Smith   | England  |
      | Jack | Johnny   | Germany |
```
