### ISSUE TITLE
The cucumber options provided as parameters in the  testng.xml file is not considered.

### ISSUE THREAD

**Issue by ArunEYGDS** [cucumber/cucumber-jvm#2393]
**Describe the bug**
I am using the Cucumber TestNGCucumberRunner and testng.xml to run the cucumber scenarios in my test.  When I give the cucumber options in the testng xml file those are not considered and the test completes stating it couldn't find any features. But the same tests run when I give the cucumber options in the Runner class as "@CucumberOptions".

**To Reproduce**
- Run the cucumber test using TestNGCucumberRunner by giving the Cucumber options in the testng xml file

**Expected behavior**
- The cucumber options given in the testng xml should be considered and test executed accordingly

**Environment**
 - Versions used : 7.0.0-RC1
 - Operating System and version : Windows 11
 - Build tool : Maven

**Comment by mpkorstanje** [comment]
I can't reproduce this. Please provide a minimal reproducer in the form of a github repo.
