### ISSUE TITLE
Weld Initiator support with Junit in Cucumber

### ISSUE THREAD

**Issue by iliadelo** [cucumber/cucumber-jvm#2404]
I was writing some component tests for a project using Junit and Weld Junit containers. Now I am trying to convert them into feature acceptance tests using Cucumber.

As I can see Cucumber uses CDI2 a maven dependency where a non-customizable weld se container is started and enables dependency injection. This has some serious limitations , the biggest is that it reads from the main/beans.xml file and not from the test/beans xml.

It would be really amazing if Cucumber could have a customizable CDI container injection. 

https://github.com/weld/weld-junit <- Source.

Example.

`WeldInitiator weld = WeldInitiator.from(WeldInitiator.createWeld().enableDiscovery().addExtensions(ConfigExtension.class)
                                                                       .property("org.jboss.weld.se.archive.isolation", "false")
    ).activate(RequestScoped.class, ApplicationScoped.class)
                                                    .inject(this)
                                                    .setPersistenceContextFactory(SomePersistence)
                                                    .setEjbFactory(someFactory)
                                                    .setPersistenceUnitFactory(someUnit)
                                                    .build();`

I manage to get it work as a Classrule  with junit 4 and cucumber but has some problems and limitations.

```
@RunWith(Cucumber.class)
@CucumberOptions(features = "src/test/resources/cwm/something/adapter/foo")
public class RunCucumberTestIT {
    
    @ClassRule
    public static WeldInitiator weld = WeldInitiator.from(WeldInitiator.createWeld().enableDiscovery().addExtensions(ConfigExtension.class)
                                                                       .addBeanClass(someBeanClass.class)
                                                                       .property("org.jboss.weld.se.archive.isolation", "false")
    ).activate(RequestScoped.class, ApplicationScoped.class)
                                                    .inject(this)
                                                    .setPersistenceContextFactory(SomePersistence)
                                                    .setEjbFactory(someFactory)
                                                    .setPersistenceUnitFactory(someUnit)
                                                    .build();

}
```
Also with the new BeforeAll & AfterAll hooks i can use TestContainers with cucumber,
this approach could really be an alternative to Arquillian and cukespace.

**Comment by mpkorstanje** [comment]
Looking at the [WeldJUnit5Extension](https://github.com/weld/weld-junit/blob/master/junit5/src/main/java/org/jboss/weld/junit5/WeldJunit5Extension.java) I don't immediately see something that should prevent you from providing your own `ObjectFactory` implementation that uses similar semantics. You may even consider contributing a Cucumber module to the `weld-junit` project. 

Though The JUnit approach will require starting a new instance of CDI application for every scenario (as you would with JUnit for every test) . Should you want to start a single instance of the CDI application then you can do so using the Before/AfterAll hooks. Again looking at the `WeldJUnit5Extension` this doesn't seem to be too complicated. Most of the complications in the extension seem to come from supporting various configuration options. You would pick one.

> As I can see Cucumber uses CDI2 a maven dependency where a non-customizable weld se container is started and enables dependency injection. This has some serious limitations , the biggest is that it reads from the main/beans.xml file and not from the test/beans xml.

I'm not very familiar with CDI so I can't quite judge the significance of this. Suppose you were not relying on JUnit extensions to start the CDI container. How would you the container pick up that it should use `test/beans.xml`?
