### ISSUE TITLE
Unable to obtain Spring context with @CucumberContextConfiguration

### ISSUE THREAD

**Issue by nitinshinde8** [cucumber/cucumber-jvm#2405]
**Describe the bug**
Hey, we are using 6.11.0 version of Cucumber-Spring. we have multi-module project which has app module(contains application code) and tests module(contains just QA code i.e. feature files, test runner, cucuber spring config class)
Most of the code and project structure is similar to https://github.com/cucumber/cucumber-jvm/issues/2060.
Ref - https://github.com/cucumber/cucumber-jvm/issues/2060#issuecomment-661855658

**Expected behavior**
Adding @CucumberContextConfiguration together with @SpringBootTest should be enough according docs.
With this configuration, we are unable to Autowire other spring beans into the test classes. We get the following exception :
 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#481e91b6': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'entityManagerFactory' available
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)

**Context & Motivation**

Unable to use features of cucumber spring to test QA scenarios.

**Screenshots**

**Your Environment**
 - Versions used [e.g 5.0.0] - 6.11.0
 - Operating System and version [e.g. * Operating System and version:]  Windows 10, Unix
 - Build tool [e.g. Apache Maven 3.6.0] :- Gradle

**Additional context**
Please help us if we are missing any additional configuration.

**Comment by mpkorstanje** [comment]
This doesn't sound like a Cucumber problem. It would appear that your application context is starting and failing to find the `entityManagerFactory` within it. If you do think this is a problem with Cucumber please provide a  Minimal, Complete, Reproducible Example in the form of a github repo. See:

https://stackoverflow.com/help/mcve
