### ISSUE TITLE
Update codecov

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#2407]
The build pipeline reports coverage through codecov. We are currently using v1 and should upgrade to v2 as the former is being deprecated and will receive rolling brown outs.

 - https://about.codecov.io/blog/introducing-codecovs-new-uploader/
 - https://github.com/cucumber/cucumber-jvm/blob/main/.github/workflows/build.yml#L58-L81
 - https://github.com/codecov/codecov-action#migration-from-v1-to-v2

**Comment by SouGrati** [comment]
Hi !
is this issue still open ?

**Comment by aslakhellesoy** [comment]
Yes, this issue is open

**Comment by mpkorstanje** [comment]
Not any more! Fixed by #2429.
