### ISSUE TITLE
cucumber spring from jar execution getting exception "Please annotate a glue class with some context configuration."

### ISSUE THREAD

**Issue by hemant-karwade** [cucumber/cucumber-jvm#2414]
**Describe the bug**
Using maven we build project and configure CucumberSpringTest using annotations (@CucumberContextConfiguration, @ContextConfiguration) but when we used built jar package to execute we are getting following exception

![image](https://user-images.githubusercontent.com/53491176/140063231-bf77aeaa-cbfc-445d-8d34-bc5db536ec1f.png)

Where as when we we execute using IDE run configuration same thing works successfully.

**To Reproduce**
1. Create Test Runner class
2. Create CucumberSpringTest class using annotations (@CucumberContextConfiguration, @ContextConfiguration)
3. Create Context class with annotations (@TestConfiguration, @Bean and @ScenarioScope)
4. prepare cucumber,properties (located at resource) file with glue, feature and steps paths
5. create feature files and stepdefinations classes
5. Build maven jar package with assembly plug-in (jar-with-dependencies)
6. created jar has cucumber.properties at root level
6. Run jar file using "java -jar <path/jarfilename>"

**Expected behavior**
Execute all scenarios mentioned in feature file.

**Actual behaviour**
![image](https://user-images.githubusercontent.com/53491176/140064760-4a0db0f7-955d-4391-91ae-0d76fb797c9a.png)

**Your Environment**
 - Versions used [ 6.10.0 ]
 - Operating System and version [ Windows 10 ]
 - Build tool [ Apache Maven 3.6.3]

**Comment by pdinh001** [comment]
@hemant-karwade were you and to find a solution for this? I am running into the same error

**Comment by naveen1171** [comment]
Same error , any solution

**Comment by mpkorstanje** [comment]
I've hidden some "me too" comments.

This is an issue tracker, if you need general help please use Stackoverflow. If you do have a bug, please provide a minimal reproducible example. And for something as complex as this, preferably in the form of a Github repo.
