### ISSUE TITLE
Simple Gradle project showing the use of Cucumber-jvm 7

### ISSUE THREAD

**Issue by Arc-E-Tect** [cucumber/cucumber-jvm#2420]
**Is your feature request related to a problem? Please describe.**
Trying to get the @Suite to work to replace the @Cucumber, but whatever I do, I don't get the @Suite annotation on my classpath. The junit packages are not loaded.

**Describe the solution you'd like**
Simple example Gradle project that shows how to migrate from cucumber-jvm 6 to 7

**Comment by mpkorstanje** [comment]
Have a look at:

https://github.com/cucumber/cucumber-java-skeleton

**Comment by Arc-E-Tect** [comment]
Thanks, that was what I was looking for. Should have looked there before reaching out. Sorry about that.
