### ISSUE TITLE
Which formatter to use in idea when running cucumber tests with junit platform engine

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [cucumber/cucumber-jvm#2423]
**Describe the bug**
After switching from console runner to @Suite approach - all tests in IDEA Run windows has no grouping

I tries to add standard idea formatter but with no luck
```
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("com/cucumber")
@ConfigurationParameters(
    ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.stepdefs"),
    ConfigurationParameter(
        key = PLUGIN_PROPERTY_NAME,
        value = "org.jetbrains.plugins.cucumber.java.run.CucumberJvm5SMFormatter"
    )
)
class CucumberSuite

```
**Screenshots**
![image](https://user-images.githubusercontent.com/47743040/143443881-274ab3a2-e240-4a55-9965-94bafbdb1940.png)

**Your Environment**
 - Versions used 6.10.4
 - Operating System and version: Windows 11
 - Build tool gradle 6.8

**Comment by mpkorstanje** [comment]
You're using IDEA so you should probably ask this on: https://youtrack.jetbrains.com

Don't think you need the plugin in the first place though.
