### ISSUE TITLE
datatable.asMap throws exception Can't convert DataTable to Map<class java.lang.String,class java.lang.String>

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [cucumber/cucumber-jvm#2426]
**Describe the bug**
datatable.asMap throws exception Can't convert DataTable to Map<class java.lang.String,class java.lang.String>

However  its working on 6.8

**To Reproduce**
```  
data class User(
    val firstName: String,
    val lastName: String,
    val username: String
)

@DataTableType
    fun users(datatable: io.cucumber.datatable.DataTable): User {
        val user = datatable.asMap(String::class.java, String::class.java)
        return User(
            user.getValue("firstName")!!,
            user.getValue("lastName")!!,
            user.getValue("username")!!
        )
    }
```

and scenario:
```
  Scenario: Step table example
    Given i have user:
      | firstName | John         |
      | lastName  | Smith        |
      | username  | littleBirdie |

```
**Expected behavior**
datatable should be converted to map 

**Your Environment**
 - Versions used 7.0.0

**Comment by mpkorstanje** [comment]
When upgrading please read the changelog:

https://github.com/cucumber/cucumber-jvm/blob/main/release-notes/v7.0.0.md#datatable-api-changes

**Comment by ocherniavskyi-lohika-tix** [comment]
@mpkorstanje your link explain how to fix asMapS, but im interested at asMap
could you point me to code example how to implement it

**Comment by mpkorstanje** [comment]
Ah. Your table is sideways. Try transposing it first:

https://github.com/cucumber/cucumber-jvm/tree/main/java#transposing-tables

**Comment by ocherniavskyi-lohika-tix** [comment]
@mpkorstanje 
i figure out how to workaround asMap:
`@DataTableType
    fun users(datatable: DataTable): User {
        val user = datatable.transpose().entries().first()
        return User(
            user.getValue("firstName")!!,
            user.getValue("lastName")!!,
            user.getValue("username")!!
        )
    }`
and after your suggestion, i can remove .transpose() call, but anyway 
datatable.asMap() throws exception with message:
Can't convert DataTable to Map<class java.lang.String,class java.lang.String>. You have to write the conversion for it in this method

Do you have any examples how to "You have to write the conversion for it in this method"?

**Comment by mpkorstanje** [comment]
Please read the documentation I've linked you carefully.
