### ISSUE TITLE
Null Pointer Exception, when tests are run with a test group not annotated in the TestRunner

### ISSUE THREAD

**Issue by GayanSandaruwan** [cucumber/cucumber-jvm#2430]
**Describe the bug**
Context:
 * We have two test groups (uitest, nightly).
 * RunCucumberTests extends AbstractTestNGCucumberTests
 * RunCucumberTests has a @Test annotated method runNightly with groups = {"NIGHTLY"} . This runNightly method also calls the runScenario method in the end.
 * I can see AbstractTestNGCucumberTests has a @Test annotated method runScenarios with groups ={ "cucumber"}

**To Reproduce**
 1. When I run tests using the "nightly" group with testNG and surefire plugin there is no issue.
 2. When I run tests using the "uitest" group it still runs the tests but tests are executed twice, with one from the runNightly method and the other from the runScenarios method.
 3. The second run from the  AbstractTestNGCucumberTests#runScenarios provides a null pointer exception for the pickly object.

**Expected behavior**
When tests are run with a non annotated group for the @Test method in child classes of AbstractTestNGCucumberTests should not execute.

**Screenshots**
See the log
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[ERROR] Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.727 s <<< FAILURE! - in TestSuite
[ERROR] com.enactor.core.automation.cucumber.RunCucumberTests.runScenario  Time elapsed: 0.005 s  <<< FAILURE!
java.lang.NullPointerException

[ERROR] com.enactor.core.automation.cucumber.RunCucumberTests.runScenario  Time elapsed: 0 s  <<< FAILURE!
java.lang.NullPointerException

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] com.enactor.core.automation.cucumber.RunCucumberTests.runScenario
[ERROR]   Run 1: RunCucumberTests>AbstractTestNGCucumberTests.runScenario:31 » NullPointer
[ERROR]   Run 2: RunCucumberTests>AbstractTestNGCucumberTests.runScenario:31 » NullPointer
[INFO] 
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Your Environment**
 - Versions used - 6.11.0
 - Operating System and version - Ubuntu 20.04
 - Build tool - Apache Maven 3.6.3

**Comment by mpkorstanje** [comment]
So why the NPE? Did you attach a debugger to check?

And what's in the stacktrace?

**Comment by GayanSandaruwan** [comment]
No stacktrace was generated related to this. I'll debug and will find where it is failing

**Comment by mpkorstanje** [comment]
Closing this for now. Feel free to add the missing information and we can continue.
