### ISSUE TITLE
Generic annotation for asterisk prefix

### ISSUE THREAD

**Issue by Azukovs** [cucumber/cucumber-jvm#2435]
**Is your feature request related to a problem? Please describe.**
I have some very specific feature files that have long tests that validate multiple things written in non-english language, the `Given -> When -> Then` structure doesn't make sense here. I tried replacing feature file keywords with *, and that works just fine, however the problem is the step definition is not logical.
There doesn't seem to be any way to have a "universal" annotation to use for asterisk steps, only `Given`, `When`, `Then`, `And`, `But` exists. It's not very logical to have a `* Some step` in a feature and `@Given("Some step")` definition.
Additionally (but this would be IntelliJ IDEA problem) if I'm trying to generate a step definition from a new step in this form - `* Some step` - the generation intent doesn't function at all, probably because there is no annotation to assign when asterisk is used.

**Describe the solution you'd like**
An additional annotation that would correctly reflect the asterisk step in feature file and would function when generating the step definition, something like `@Step("Some step")` would be just fine.

**Describe alternatives you've considered**
Using different language for `Given -> When -> Then` steps doesn't make sense either due to test structure, which is too complex, and does multiple validations within the test. Not the best practice, I'm fully aware, but in my case unavoidable due to project specifics.

**Comment by mpkorstanje** [comment]
A generic step definition would also allow the complexity of `getPreviousGivenWhenThenKeyword` to be removed.

https://github.com/cucumber/cucumber-jvm/blob/75020783870f2769dcf8ab5221c8a1dd89f042f5/core/src/main/java/io/cucumber/core/snippets/SnippetGenerator.java#L53

**Comment by mpkorstanje** [comment]
Superseded by #2705
