### ISSUE TITLE
Possibility to retrieve examples title in scenario outline

### ISSUE THREAD

**Issue by UnleashSpirit** [cucumber/cucumber-jvm#2436]
**Is your feature request related to a problem? Please describe.**
More a question in fact and if answer is "No" so a feature :)

**Describe the solution you'd like**
Is there a possibility to retrieve examples title when running scenario outline to avoid the \#1 ?

**Describe alternatives you've considered**
Using a column to store title

**Additional context**
```
Scenario Outline: Test <something_here_like_Examples_Title>
  Given <a>
  Then <b>
  Examples: foo
    | a | b |
    | 1 | 2 |
  Examples: bar
    | a | b |
    | 2 | 1 |
```
Will print :
`Scenario Outline: Test #1`
`Scenario Outline: Test #2`

Would love a way to retrieve the examples title, "foo" and "bar" to print :
`Scenario Outline: Test foo`
`Scenario Outline: Test bar`

Is there a way ? (or I miss something in doc ?)

**Comment by mpkorstanje** [comment]
How are you running Cucumber? Where are you seeing the `#1`?

**Comment by UnleashSpirit** [comment]
Hi, I see the `#1` in jUnit eclipse panel
In the console (or CI, jenkins) I don't see the `#1` so having the Examples title, if possible, would be great

**Comment by mpkorstanje** [comment]
I'm afraid I'll need a much more detailed technical answer to the question how you are running Cucumber. There are quite a few ways to do this. So you will have to help me reproduce the problem by providing sufficient information.

Have a look at this for more pointers:

https://stackoverflow.com/help/how-to-ask

**Comment by mpkorstanje** [comment]
Ah. No, I don't think that can be fixed. JUnit 4 has some inherent limitations. Try running Cucumber with JUnit 5 instead.

https://github.com/cucumber/cucumber-java-skeleton

https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine

**Comment by UnleashSpirit** [comment]
It's seems that it's already JUnit 5 as runner (as the scrennshot shows)
But if I compare to the links you provide effectively the RunCucumberTest does not avec the same `@`
I'll give it a try, thanks
