### ISSUE TITLE
Cucmber-jvm rerun all scenarios and not only failed one.

### ISSUE THREAD

**Issue by lemitrou** [cucumber/cucumber-jvm#2437]
**Describe the bug**
I have a maven project, with cucumber-java and junit 4.13. 
The problem is that in rerun phase instead to run only the failed test, runner execute also and the pass test

**To Reproduce**
I have created 2 runners:
TestRunner.java :
```
@RunWith(Cucumber.class)
@CucumberOptions(features = "src/test/resources/com/bdd/jenkins",
        glue = {"com.bdd.helpers", "com.bdd.steps"},
        tags= "not @Fail", //not @ignore
        plugin = {"pretty", "html:target/cucumber", "json:target/cucumber.json", "rerun:target/failed.txt"}
)
public class TestRunner {
}
```
FailedTestRunner.java :
```
@RunWith(Cucumber.class)
@CucumberOptions(features = "@target/failed.txt",
        glue = {"com.bdd.helpers", "com.bdd.steps"},
        plugin = {"pretty", "html:target/cucumber", "json:target/cucumber.json"}
)
public class FailedTestRunner {
}
```

My configuration of maven-surefire plugin in pom.xml:
```
<groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/*TestRunner.java</include>
                    </includes>
                </configuration>
```

and my feature file : 
```Feature: Internal router - System with 2 available surveys, tests the internal router.

  Scenario: Pass scenario
    Given I give you 1 euro
    Then I have 1 euro

  Scenario: Fail scenario
    Given I give you 1 euro
    Then I have 2 euro
```

pretty simple junit assertion and intentional fail.

**Expected behavior**
Following rerun file created : 
`file:src/test/resources/com/bdd/jenkins/migrated/network/rerun.feature:7`

Only fail scenario should executed twice

**Context & Motivation**

I can't enable rerun phase in e2e execution pipeline

**Screenshots**
Not applicable

**Comment by mpkorstanje** [comment]
Can't seem to reproduce this at a glance. Do you have a minimal reproducer in the form of a github repo?

**Comment by lemitrou** [comment]
Sorry for my late answer. 
Thanks for the interest.
I create a project from scratch, and you are right. It's working. I also sync the dependencies between pom, and again rerun works like a charm.
I'll continue the investigation .
This issue should close as "Not reproducible"
