### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by YenikeRaghuRam** [cucumber/cucumber-jvm#2443]
**Describe the bug**
Below warning displayed when running RunnerTest.java

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cucumber.deps.com.thoughtworks.xstream.core.util.Fields (file:/C:/Users/yeniker/.m2/repository/io/cucumber/cucumber-jvm-deps/1.0.6/cucumber-jvm-deps-1.0.6.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of cucumber.deps.com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**To Reproduce**

**Expected behavior**
Expect no warnings to be displayed

**Context & Motivation**

Able to Run cucumber tests now seeing warning like in future such access will be removed
want clarification

**Screenshots**

**Your Environment**
 - Versions used [e.g 5.0.0] - jdk 11
 - Operating System and version [e.g. * Operating System and version:] Windows 10
 - Build tool [e.g. Apache Maven 3.6.0] - 3.6.3

Below are dependencies in POM

<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>6.10.0</version>
</dependency>

<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-jvm-deps</artifactId>
    <version>1.0.6</version>
    <scope>provided</scope>
</dependency>

<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-junit</artifactId>
    <version>6.10.0</version>
</dependency>

**Comment by mpkorstanje** [comment]
Please follow the tutorial:

https://cucumber.io/docs/guides/10-minute-tutorial/

**Comment by mpkorstanje** [comment]
And you should learn about Maven as explained here:

https://stackoverflow.com/a/60159391/3945473
