### ISSUE TITLE
Skipped Cucumber steps after running JUnit 

### ISSUE THREAD

**Issue by Fidaa-kharabsheh** [cucumber/cucumber-jvm#2446]
Cucumber steps always reported as skipped
When I run my project as Junit, the appear as passed but all the steps are skipped 
and the output appear as the stepdifinition steps
Is there missing jar or anything that may cause this ?

**TestRuner:**
package cucumberOptions;

import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

//in feature the path of the path will excute every feature file in the package, but if only one file name is provided only that file will be executed
@RunWith(Cucumber.class)
@CucumberOptions(
		features="src/test/java/features/Login.feature",
		glue="stepDinistion")

public class TestRunner {
	
	

}

**and this  is the steps definition :**
package stepDefinition;
import org.junit.runner.RunWith;
import cucumber.api.java.en.And;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;
import cucumber.api.junit.Cucumber;

@RunWith(Cucumber.class)
public class stepDefinistion {

    @Given("^User in on NetBanking landig page$")
    public void user_in_on_netbanking_landig_page() throws Throwable {
       
    	System.out.println("Navigating to login url");
    }

    @When("^User login into application with username and password$")
    public void user_login_into_application_with_username_and_password() throws Throwable {
        
    	System.out.println("Logged in successfully");
    }

    @Then("^Home page is populated$")
    public void home_page_is_populated() throws Throwable {
     
    	System.out.println("Validated homepage ");
    }

    @And("^Card are displayed$")
    public void card_are_displayed() throws Throwable {
    	
    	System.out.println("Validated cards");
        
    }

}

**Comment by mpkorstanje** [comment]
This looks like a typo: `glue="stepDinistion"`.

You are however using an old version of Cucumber. Have a look at:

* https://github.com/cucumber/cucumber-java-skeleton
* https://cucumber.io/docs/guides/10-minute-tutorial/

**Comment by Fidaa-kharabsheh** [comment]
When I use cucumber 7.1.0 errors appear in the step definition file 
cucumber can't be resolved in Cucumber. class 
the same as for Given, When, Then 
Given cannot be resolved to a type
When cannot be resolved to a type
Then cannot be resolved to a type
And cannot be resolved to a type
----------------------------------------------------------------------------
package stepDefinition;

import org.junit.runner.RunWith;

import cucumber.api.java.en.And;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;
import cucumber.api.junit.Cucumber;



@RunWith(Cucumber.class)
public class stepDefinistion {

    @Given("^User in on NetBanking landig page$")
    public void user_in_on_netbanking_landig_page() throws Throwable {
       
    	System.out.println("Navigating to login url");
    }

    @When("^User login into application with username and password$")
    public void user_login_into_application_with_username_and_password() throws Throwable {
        
    	System.out.println("Logged in successfully");
    }

    @Then("^Home page is populated$")
    public void home_page_is_populated() throws Throwable {
     
    	System.out.println("Validated homepage ");
    }

    @And("^Card are displayed$")
    public void card_are_displayed() throws Throwable {
    	
    	System.out.println("Validated cards");
        
    }

}

**Comment by mpkorstanje** [comment]
Yes, that is expected. Please, study the links I posted earlier.
