### ISSUE TITLE
Add better support for Dagger?

### ISSUE THREAD

**Issue by jamietanna** [cucumber/cucumber-jvm#2448]
**Is your feature request related to a problem? Please describe.**

[Dagger](https://dagger.dev) is a great tool for DI, and [I personally recommend using it](https://www.jvt.me/posts/2021/12/30/cucumber-dagger-dependency-injection/) for folks not already using it.

**Describe the solution you'd like**

I wonder if we can do something to produce an `ObjectFactory` for Dagger users, which would work in tandem with custom Dagger config?

**Describe alternatives you've considered**

Each user creating it themselves.

**Additional context**

I've not yet tried - but will - making it work in a project as-is, before upstreaming it.

**Comment by mpkorstanje** [comment]
Always welcome. But keep in mind that:

 * Dependency injection is not trivial and quite hard to get right. 
 * Contributing a module means that it will now have to be maintained. 

So before considering contributing support for Dagger I would suggest that you implement and publish the module yourself. This will provide the flexibility and freedom needed to incubate and mature the module and some metrics to gauge popularity.

Cucumber follows semantic versioning and the `ObjectFactory` and `Backend` interfaces are part of Cucumber's public API. This means you can implement these in a project of your own.

For an example of how to, I suppose you could look at https://github.com/cucumber/cucumber-jvm/pull/2432.

**Comment by jossmoff** [comment]
For those that are interested I wrote some tooling to provide some support for dagger https://github.com/jossmoff/dagger-cucumber
