### ISSUE TITLE
Clarify PicoContainer isn't ideal for all usecases

### ISSUE THREAD

**Issue by jamietanna** [cucumber/cucumber-jvm#2449]
**Is your feature request related to a problem? Please describe.**

We should better document gotchas with PicoContainer only working with zero-args constructors as per [this blog post](https://www.jvt.me/posts/2021/12/30/cucumber-picocontainer-gotcha/) and [this example repo](https://gitlab.com/jamietanna/cucumber-dagger/-/blob/defect/picocontainer/src/test/java/io/cucumber/skeleton/StepDefinitions.java).

**Describe the solution you'd like**

Improvements to the docs.

**Describe alternatives you've considered**

N/A

**Additional context**

I'm happy raising a PR for this.

**Comment by mpkorstanje** [comment]
The problem you've described in the blog isn't new or unknown. For example any project that uses a web driver will run into this. And a good way to deal with this is the decorator pattern. Unfortunately the documentation [only contains a small out-of-context sample](https://github.com/cucumber/cucumber-jvm/tree/main/picocontainer#step-scope-and-lifecycle) of this.

So I would not be opposed to a PR that amends the documentation with a better, more explicit explanation of the constructibility requirements of the dependency tree and a good-enough system to organize step definitions and state to avoid the most common problems that follow from the constructibility requirements.

I would be opposed to an update that steers users away from using Pico as the default choice when no other dependency injection system is already in use. So far it seems that most users can suffice with a the current limited and simplified dependency injection mechanism. For more advanced users, more complicated scenarios, or more puristic use other dependency injection options are available.
