### ISSUE TITLE
cucumber.json report  gives empty array []

### ISSUE THREAD

**Issue by KavithaRamkrishnan** [cucumber/cucumber-jvm#2460]
My project is cucumber testng. Cucumber.json is created but with empty []. 

when i used extends AbstractTestNGCucumberTests. script failed with null pointer exception. But cucumber.json is created with steps.

Kindly help me to resolve this .

**Comment by mpkorstanje** [comment]
Heya! Cucumber is an opensource project maintained primarily by people in their spare time. If you have a problem you'll have to make it easy for people to help you. This means you'll have to put in some effort to get it resolved.

The first step is creating a minimal reproducer of your project preferably in the form of a github repo.

For more information on how to do that have a look at:
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by KavithaRamkrishnan** [comment]
Not able to upload the project repo. But, what is required to debug just let me know

**Comment by mpkorstanje** [comment]
Closing this for now. We can reopen this once provide sufficient information to reproduce the problem is provided.
