### ISSUE TITLE
HTML Report invalid when upgrading from 7.1.0 to 7.2.2

### ISSUE THREAD

**Issue by morepe** [cucumber/cucumber-jvm#2464]
**Describe the bug**
After I changed the version from 7.1.0 to 7.2.2 the created HTML report using the standard reporting plugin is invalid. It works fine when I run the tests locally but the test report produced by our jenkins is invalid.

**To Reproduce**
Not completely sure. I can only reproduce it in our CI/CD pipeline. Jenkins executes the build and runs some tests with Cucumber. The created HTML Report is invalid. I get an java-script error something like: e.git is undefined.

**Expected behavior**
HTML Report should be valid. 

**Context & Motivation**

How has this issue affected you? What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world.

**Screenshots**
See attached invalid report.

**Your Environment**
    cucumber: 7.2.2
    Jenkins 2.289.2

**Additional context**
Without knowing the code, I think it might be related to https://github.com/cucumber/cucumber-jvm/issues/2454. Here a  fallback was added to make the build work. Maybe the same fallback is required for reporting as well.

See attached invalid report
[HTML_20Report_206.zip](https://github.com/cucumber/cucumber-jvm/files/7844837/HTML_20Report_206.zip)
.

**Comment by mpkorstanje** [comment]
@aslakhellesoy can you help with this one? Might need to release a fix to the html reporter before the other changes to messages land and propagate.

**Comment by mpkorstanje** [comment]
Fixed with work around in v7.2.3.
