### ISSUE TITLE
Parallel run - need state sharing example using spring DI

### ISSUE THREAD

**Issue by SachinB75** [cucumber/cucumber-jvm#2467]
Help wanted....

Hello

I am using Spring dependency injection with the example code. The state sharing using @Autowired works fine when I execute my scripts in sequential order. 
However I am unable to execute my tests in parallel as my helper class (java class with fields that need to shared across steps) is shared across threads. Example I have a field which stores session information for a logged in user, that session is used across threads causing only 1 feature to pass and others to fail since they try to use the same session instead of using it's own session
 
I have added the surefire maven plugin to execute my features in parallel. I am using Junit 4.13 version
with configuration as <parallel>methods</parallel> and useUnlimitedThreads to True.

Adding @Scope("prototype")  or @ScenarioScope on the helper class has also not helped.

Parallel runs using pico container worked fine and as expected. Any help or an example would be much appreciated.

Please let me know if you need any additional information.

**Comment by mpkorstanje** [comment]
It sounds like you've made the session object application scoped rather then scenario scoped. You'll have to use the scenario scoped class as a container for the session, not autowired it in.

But it's hard to say without a code example of what you're actually doing.

**Comment by SachinB75** [comment]
Hello

Thank you for a quick revert. Sorry about the confusion. I meant I am just storing the sesion id in an property field in the Shared helper class and that class itself is annotated as @Component and @ScenarioScope.. Below is a rough representation of the code. I hope it helps. Else please let me know any additional details you may need. I really appreciate your help.

//SharedHelper Class

@Component
@ScenarioScope
public class SharedHelper {

  
  private String transid;
  private jwsToken (this is used to make some api calls in some steps in one scenario)

	//getters //setters
}

===============================================================================================================
//POM.xml
 <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-spring</artifactId>
            <version>7.0.0</version>
            <scope>test</scope>
        </dependency>

      
            <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.19.1</version>
                    <configuration>
                        <parallel>methods</parallel>
                        <useUnlimitedThreads>true</useUnlimitedThreads>
                        <perCoreThreadCount>false</perCoreThreadCount>
                    </configuration>
                </plugin>

=========================================

//Runner -- Please note, The features and steps work without using the GLUE option as the springclass in main package has a package scan 

@RunWith(Cucumber.class)
@CucumberOptions(tags = "not @ignore",
 features = {

}, plugin = { "pretty", "json:target/cucumber-ui.json", "html:target/cucumber-ui"})
public class RunCucumberTest {
}

====================================================

//config context class

@CucumberContextConfiguration
@SpringBootTest
public class MBSUIRegression {
}

=================================================
//steps file 1

public class LoginStepDefs {

  @Autowired
  ApigeeCookieBean apigeeCookieBean;

  @Autowired 	
  private SharedHelper helper;


  private Scenario scenario;

  @When("Set the token"){
  	helper.setToken("get token from the browser"); -------------this work fine	
 }

}
=====================================================

//steps file 2

public class StepDefs2 {

  @Autowired 	
  private SharedHelper helper;

  private Scenario scenario;

  @When("Get the Token"){
      	helper.getToken("get token from the helper"); -------------this work fine when run in isolation
  }

}

========================================================================

//Feature1 

Scenario: Test Trans Type 1
          User logs in ---> assigned a unique user from user pool
          set the token
          Get the token  -- since parallel run - it is for each user logged in
          User with token to make api 1 call

//Feature2
Scenario: TEst Trans Type 2
          User logs in --- assigned a unique user from user pool 
          set the token
          Get the token  -- since parallel run - it is for each user logged in
          User with token to make api 2 call

=========================================================================

The issue is both users are trying get the same token from the shared helper class and 1 feature passes and the rest multiple subsequent features fail

**Comment by mpkorstanje** [comment]
I don't see anything wrong with your project though it also seems your are leaving a lot of detail out that could influence your problem. For example the `ApigeeCookieBean` looks like it may contain some shared state. Can you provide a reproducer in the form of a github repository?

I've got an example with JUnit 5 that you could reuse:

https://github.com/mpkorstanje/cucumber-spring-boot-parallel

Note that `System.out.println("Test component=" + testComponent.getUuid());` will show that each scenario scoped instance of `TestComponent` is unique.

**Comment by SachinB75** [comment]
Hello again.. I will try and use the Junit5 example. Will try and create a repo shortly with what I have tried. Thank you again. Appreciate it.

Regards

**Comment by mpkorstanje** [comment]
I'm going to assume it all worked out. Feel free to reopen if it didn't.
