### ISSUE TITLE
cucumber JVM run shows 0 Scenarios and 0 Steps

### ISSUE THREAD

**Issue by KavithaRamkrishnan** [cucumber/cucumber-jvm#2468]
Hi Team,

Created a cucumber testng framework with lot other integrations such as mobile cloud platform etc.,

The framework is working perfectly fine using testng. Because, we have used testng annotations only. But, when I tried to run the feature file separately .. getting issue with 0 scenarios and 0 steps and all the tests got skipped also.

Kindly help me to fix this.

**Comment by mpkorstanje** [comment]
This is the issue tracker of an open source project. For general help you'd be better of on Stackoverflow. Though before asking there please review  [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask) first.

If you want to report a bug please include enough information that some one else can reproduce the problem. The bug report template should contain some hints to help you out:

https://github.com/cucumber/cucumber-jvm/issues/new?assignees=&labels=Bug&template=bug_report.md&title=
