### ISSUE TITLE
Cucumber test with Spring Boot gets conflict for parallel execution

### ISSUE THREAD

**Issue by pcasano** [cucumber/cucumber-jvm#2470]
**Describe the bug**
I use Cucumber with Spring Boot and Maven. I have a feature with two scenarios. They are having conflicts when they run parallel with mvn test. The values of some variables are getting mixed between both scenarios.
If I run the feature file directly in Intellij (run as), it runs sequential with no conflicts

**Expected behavior**

Its expected that the transactions that are generated in both scenarios have unique ids
Scenario1
Transaction_A  id: Ncgphebvg
Transaction_B  id: Xalrafuke
Scenario2
Transaction_A  id: Ibphlfyur
Transaction_B  id: Vbhrkyrey
Transaction_C  id: Jxpebpmug

**Current behavior**
Transaction ids of one scenario are getting overwritten by the other scenario. Both scenarios are not isolated and that is causing conflicts
Scenario1
Transaction_A  id: Ncgphebvg
Transaction_B  id: Xalrafuke
Scenario2
Transaction_A  id: Xalrafuke
Transaction_B  id: Xalrafuke
Transaction_C  id: Xalrafuke

**Context & Motivation**
values of variables are getting mixed between both scenarios and test are failing

**Your Environment**
- io.cucumber. ArtifactId cucumber-java   6.10.4
- io.cucumber. ArtifactId cucumber-junit-platform-engine  6.10.4
- io.cucumber. ArtifactId cucumber-spring  6.10.4
- Step defs written in Kotlin 1.5.30
- Apache Maven 3.6.3

**Comment by mpkorstanje** [comment]
When reporting a bug please make sure to include the sufficient information to reproduce the problem.

And beware that
> Cucumber Spring creates an application context and uses Spring's TestContextManager framework internally. All scenarios as well as all other tests (e.g. JUnit) that use the same context configuration will share one instance of the Spring application. This avoids an expensive startup time.

Please consult the documentation for guidance on dealing with this:

https://github.com/cucumber/cucumber-jvm/tree/main/spring#sharing-state

**Comment by pcasano** [comment]
see updates

**Comment by mpkorstanje** [comment]
I'm sorry but this is not sufficient. Please have a look at:

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mpkorstanje** [comment]
Please feel free to reopen with more information. Preferably in the form of a github repo.
