### ISSUE TITLE
Add step notification option to junit platform

### ISSUE THREAD

**Issue by jpadre** [cucumber/cucumber-jvm#2471]
**Issue**
When migrating from JUnit 4 to JUnit 5 using the junit plaftorm suite and engine, we lost the option for steps notifications (making the steps the leafs in the test suite tree)

**Details**
Since this [change ](https://github.com/cucumber/cucumber-jvm/pull/1159) was incorporated, the option is set to false by default 

In the previous implementation, we could change the flag using the annotation or passing --step-notifications as a process parameter
`@CucumberOptions(..., stepNotifications = true,... )`

But there's no equivalent to use in junit-platform.properties to toggle that flag when using a JUnit suite

**Potential configuration**
(apologies I don't know the code well enough to provide a pull request)
Add a new configuration parameter to cucumber.properties (and junit-platform.properties) that could be named **cucumber.step-notifications** to toggle the behavior.

**Comment by mpkorstanje** [comment]
Unfortunately as with JUnit 4, the domain of JUnit 5 does not have anything to express sub-test steps.

While it would theoretically be possible to represent steps as indivial tests this would results in various other issues such as miscounting executed tests,

**Comment by mpkorstanje** [comment]
If JUnit 5 is not important to you, and you are using InteliJ IDEA you can use their Cucumber plugin to get step definitions.

Alternatively you can use the CLI with the `--plugin teamcity` to render indivial steps.

I don't believe there is any equivalent available for VS code or Eclipse.

**Comment by jpadre** [comment]
Thanks for the prompt reply!
Yes I understand the limitations would be the same as JUnit 4, and that being able to toggle the flag is important, unfortunately, it is JUnit 5 and Eclipse I am targeting. 

The main benefit is that with 4000+ steps and 350+ scenarios, having the steps showing in the IDE as tests makes it possible to quickly stop the execution and manage the first error(s), not having to wait for the whole test suite to complete and report the full (and sometimes difficult to read) details on the command line.

Is this a feature that could be integrated if I ever come up with a pull request, or does this goes against long term targets I am not aware of?

Again many thanks.

**Comment by mpkorstanje** [comment]
As a general principal we can't really exceed the constraints and assumptions of another framework. The conceptual mismatch would be a constant source of bug reports.

So I would say your options are to add support for sub-test steps to JUnit 5 and then implement that in Cucumber or to patch up the existing Cucumber eclipse plugin. The latter may require cleaning up a pile of technical debt in Cucumber, though I'm not sure exactly.
