### ISSUE TITLE
Plans about implementing rerun functionality

### ISSUE THREAD

**Issue by mikhalkaivan** [cucumber/cucumber-jvm#2478]
**Hi, all**

In our current implementation we have in use junit4 and cucumber-java combination, and plan to upgrade to junit5 and cucumber-junit-platform-engine. Unfortunately, new implementation doesn't contain such handy mechanism as rerun cucumber scenarios from rerun.txt files (generated by _rerun_ plugin)
files.

We use it like below in intial build:
```
@RunWith(Cucumber.class)
@CucumberOptions(..., plugin = {"rerun:target/rerun.txt"})
public class RunCucumber {
} 
```

And then in rerun build:
```
@RunWith(Cucumber.class)
@CucumberOptions(features = {"@target/rerun_wip.txt"},...})
public class RerunCucumber {
}
```

As I know, there is no analogue of _features_ cucumber option in new version, so we can generate rerun.txt by

```
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("features")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "rerun:target/rerun_wip.txt")
public class RunCucumber {
}
```

but have no idea, how to run from this file.

I know about rerunning through API from [https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine#readme](https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine#readme),
but that more convenient for single tests, and, as we have parallel execution and lot of logging, cannot apply this approach.

My question: is there some another way to run scenarios from rerun.txt in cucumber-junit-platform-engine, or there is plans about implementing this feature?

**Comment by mpkorstanje** [comment]
When using JUnit 5, the JUnit Platform handles the discovery, selection and execution of tests. I do not believe there a sensible way in which a rerun-file can be read by Cucumber through the JUnit Platform that does not get impossibly complicated when a rerun file is combined with other selectors.

> I know about rerunning through API from https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine#readme,
but that more convenient for single tests, and, as we have parallel execution and lot of logging, cannot apply this approach.

The example provided will rerun all failed scenarios. And both the original run and the rerun can execute scenarios in parallel. So I'm not sure what would block you here. Could you provide a concrete example of where and how you get stuck?

**Comment by mikhalkaivan** [comment]
No sure where to put this code for rerun. 

1. We use maven profiles as entry point to our tests:
```
        <profile>
            <id>parallel_full</id>
            <properties>
                <test.forkCount>3</test.forkCount>
                <junit.parallel>classes</junit.parallel>
                <cucumber-tag>parallel</cucumber-tag>
                <test.runner>**/*AllThread*.class</test.runner>
            </properties>
        </profile>
```
Piece of surefire plugin:

```
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <forkCount>${test.forkCount}</forkCount>
                    <reuseForks>false</reuseForks>
                    <useFile>true</useFile>
                    <includes>
                        <include>${test.runner}</include>
                    </includes>
                    <excludes>
                        <exclude>%regex[(?i).*RunCucumberParallel(${exclude.epic}).*Thread.*]</exclude>
                    </excludes>
```

Then running tests by maven command:
`mvn -B test -pl module -Pparallel_ful`

These runner classes contains mostly annotations, not real code, except @BeforeClass, @AfterClass hooks. I am just not sure, where to put entrypoint like `launcher.execute(request);`

I cannot post source code, but generally runners looks like:
```
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("features")
@ConfigurationParameter(key = FILTER_TAGS_PROPERTY_NAME, value = "@tag1 and @tag2")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "html:****,json:****,rerun:****")
public class RunCucumberParallelCreditControlAllThreadFull extends RunParallelTests {

}
```
Where RunParallelTests contains hooks (in junit4 version):

```
public class RunParallelTests {

    @BeforeAll
    public static void beforeRun() {
        ThreadLogger.initLogger();
        throw new UnsupportedOperationException();
    }

    @AfterAll
    public static void afterRun() {
        TestRunner runner = new TestRunner();
        try {
            runner.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

This is main entrypoint to tests. We have several such runners, each for specific test suites.
All steps placed in step definition classes, which contains @Before, @After, @Given, @When, @Then methods


2. Also we have some tuning parameters, like tag combinations `@tag1 and @tag2 and @tag3`, plugin parameters, for creating reports in Jenkins:
`@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "html:target/cucumber/2,json:target/credit_control.json,rerun:target/rerun_credit_control.txt")`
Doing this much easier by annotations

Could I run in parallel by tag combinations, and create needed report files from code directly? Or how can I reorganize my tests
to achieve same result with junit-platform API?

**Comment by mikhalkaivan** [comment]
Also my [question](https://stackoverflow.com/questions/70930674/implement-rerun-scenarios-with-junit-5-and-cucumber-junit-platform-engine) on stackoverflow with little addition

**Comment by mikhalkaivan** [comment]
Ok, thanks, need investigate
For now I am using junit 5 runners for initial build, and junit 4 for rerun, as a workaround.
I think, issue can be closed, as no easy solution here
