### ISSUE TITLE
Feature Request :TestNG support to run feature files in parallel(like Junit 4)

### ISSUE THREAD

**Issue by surajgupta7175** [cucumber/cucumber-jvm#2479]
**Is your feature request related to a problem? Please describe.**
With Version 4 Selenium and cucumber-jvm. We cannot run feature files parallely using TestNG . The same feature is available with Junit

Currently when we run 2 threads,
Scenario 1 & 2 present in same feature file gets executed
Problem - Scenario 2 is dependent on Scenario 1 to complete

Under maven-surefireplugin
```

<properties>
		<property>
		<name>dataproviderthreadcount</name>
		<value>2</value>
		</property>
</properties>
<parallel>classes</parallel> 
<useUnlimitedThreads>true</useUnlimitedThreads> 
					
<perCoreThreadCount>true</perCoreThreadCount>
<includes> 
	<include>Runner Path to be added</include>
</includes>

```

Article used to setup - https://cucumber.io/docs/guides/parallel-execution/?sbsearch=parallel

**Comment by mpkorstanje** [comment]
The execution unit of Cucumber is the Scenario. So you should make each scenario independent from the other scenarios. While JUnit 4 would only execute scenarios in parallel this was due to limitations of JUnit 4 rather then an intentional feature.

**Comment by mpkorstanje** [comment]
No. But have a look at:

https://specflow.org/challenges/chain-of-dependent-scenarios/

You may also find other suggestions on google. It's a fairly common problem that happens when test scripts are converted 1-to-1 into features.
