### ISSUE TITLE
Cucumber runner ignores JUnit @Rule declarations

### ISSUE THREAD

**Issue by g-hengeli** [cucumber/cucumber-jvm#249]
Most JUnit addons require either a custom runner or a Rule, since cucumber-jvm requires the Cucumber runner it must be possible to declare Rules.  Cucumber currently ignores them.

**Comment by vikramvi** [comment]
@ghengeli how did you call JUnit's @ClassRule from Cucumber ?
Is there a way to @Rule as well ?

**Comment by ghengeli** [comment]
lol - 5 years ago. sorry no clue.

**Comment by sumit4code** [comment]
Facing similar issue. Please reopen this.

**Comment by mlvandijk** [comment]
@sumit4code Afaik this is not supported.

> ### How soon will my ticket be fixed? ###
> 
> The best way to have a bug fixed or feature request implemented is to fork the cucumber-jvm repo and send a pull request. If the pull request has good tests and follows the coding conventions (see below) it has a good chance of making it into the next release.

You're welcome to help out.  Would you be able to do a PR?
