### ISSUE TITLE
Support @CucumberContextConfiguration as a meta-annotation

### ISSUE THREAD

**Issue by drekbour** [cucumber/cucumber-jvm#2491]
### 🤔 What's the problem you're trying to solve?

Support developers creating meta-annotations to wrap up common Spring testing stuff to also include `@CucumberContextConfiguration`

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Inherited

@CucumberContextConfiguration // Required for Cucumber + Spring
@EnableConfigurationProperties // Required for Cucumber + Spring Boot
@ComponentScan("some.test.stuff") 
@ContextConfiguration(classes = SomeGeneralPurposeTestContext.class)
@TestPropertySource(properties = "testprop=value_for_testing")
@ActiveProfiles("test")
public @interface MyTestAnnotation {}
```

```java
@SpringBootTest
@MyTestAnnotation
public class TestSteps {
...

```

All of the above works except for `@CucumberContextConfiguration` 

### Additional context

Currently causes this as cucumber-spring tries to directly instantiate the annotated class before considering it may be a meta-annotation.

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [my.package.MyTestAnnotation]: Specified class is an interface
```

**Comment by mpkorstanje** [comment]
I don't really see a reason not to do this.

It should be possible to use `AnnotatedElementUtils` to determine if a class is meta-annotated with `CucumberContextConfiguration` in the `SpringBackend`. And maybe filter out the annotations.

https://github.com/cucumber/cucumber-jvm/blob/main/spring/src/main/java/io/cucumber/spring/SpringBackend.java#L34

**Comment by mpkorstanje** [comment]
It should be possible to use `AnnotatedElementUtils` to determine if a class is meta-annotated with `CucumberContextConfiguration` or inherits the annotation somehow.

This is currently checked in both the `SpringFactory` and `SpringBackend`, this should become a single method:

https://github.com/cucumber/cucumber-jvm/blob/5853a06232194a99540413211fcee6048db6172f/spring/src/main/java/io/cucumber/spring/SpringFactory.java#L103-L105

https://github.com/cucumber/cucumber-jvm/blob/5853a06232194a99540413211fcee6048db6172f/spring/src/main/java/io/cucumber/spring/SpringBackend.java#L34

Additionally the `SpringBackend` should check that the annotated element is class and a non-abstract to prevent problems such as #2515.
