### ISSUE TITLE
@BeforeFeature / @AfterFeature

### ISSUE THREAD

**Issue by Johnlon** [cucumber/cucumber-jvm#2495]
### 🤔 What's the problem you're trying to solve?

There are actions I want to perform only once ber feature

### ✨ What's your proposed solution?

@BeforeFeature / @AfterFeature hooks
static void hook(Feature someFeatureInfo) {
}

"someFeatureInfo" might include the feature file name and the collection of scenarios.
Basically anything Feature level.

### ⛏Have you considered any alternatives or workarounds?

None available

**Comment by mpkorstanje** [comment]
The fundamental unit of execution is  a scenario (or example) and each scenario should be independent. If you have dependent scenarios have a look at what our friends at spec-flow wrote about this.

https://specflow.org/challenges/chain-of-dependent-scenarios/

**Comment by Johnlon** [comment]
Really surprised by your response....
1) you haven't even asked what my requirement is.
It has nothing to do with the spec steps  itself and is to do with reporting.
2) you already provide before and after scenario hooks, so how is before and after feature a threat?
3) what is the logic of your being proscriptive on this point , flexibility is a benefit. My requirement relates to reporting and I struggle to see the benefit to the evosystrm of rejecting my request
4) one can still hack a before feature hook by listening to events , I'm just asking for something cleaner and more consistent with the existing api

**Comment by aslakhellesoy** [comment]
@Johnlon people have been asking for feature hooks for a decade - in various forums, chats and issues. I don't think it's something anyone from the core team will prioritise implementing.

If you have a suggestion about how to implement them, and if you're willing to submit a pull request for it, we might be able to help you.

**Comment by mpkorstanje** [comment]
> If you have a suggestion about how to implement them, ... we might be able to help you.

@aslakhellesoy I'd say there is no possibility what so ever. Parallel execution of scenarios and a lack of scope to execute the feature hooks in make it possible.

I'd rather not spend time fruitlessly discussing this again even if a suggestion is made.

**Comment by Johnlon** [comment]
But I have a hand cranked before feature hook of sorts actually working fine by listening to the feature load event.
Could you perhaps explain in a bit more detail what's impossible?

**Comment by mpkorstanje** [comment]
> What am I missing?

Consider the solution you'd use if you could not use feature hooks, hand cranked or otherwise. Additionally consider the possibility that you may execute with unlimited paralism.

**Comment by Johnlon** [comment]
I think I am starting to see the potential issue however even without my proposed change I don't understand how the existing impl works reliably if the "--thread" option is used.

Reading the Runtime.java code I see that it looks like each pickled scenario is executed on an executor service.
Potentially this means scenarios exec in parallel .... if that parallel feature is enabled.

Where I'm doubtful is the common situation where a feature file has shared state across the steps in it's scenarios (surely this is the typical situation). In this situation how can concurrent scenario execution work at all? 
Surely the steps of one scenario will trample all over each other's scenario's state variables unless the state variables are stored in a thread local.

The "state" page in the documentation doesn't give advice that the only reliably safe method to share state is via a thread local.

----

I was further confused by the documentation vs the impl ....

I see this page says that the Junit features exec in parallel but the scenarios in a feature sequentially ... https://cucumber.io/docs/guides/parallel-execution/

However, noticed Runtime.java which has ... `executor.submit(executePickle(pickle))`  ... which appears to be running the scenarios themselves in parallel if the executor service has more than one thread configured by the "--threads" option. 

Looking back at the page https://cucumber.io/docs/guides/parallel-execution/ where we can see ...
"When the [CLI] parallel mode is used, the scenarios and rows in a scenario outline will be run in multiple threads."

Reading the code I now believe the Runtime class is used only by the CLI and not Junit so the issue around "--threads" and shared state between steps remains but only for the CLI execution.  

Is that correct?

Is it desirable that the CLI execution is so different from the Junit exececution? 
Is this intentional and why would this be beneficial?

-----

It would seem that when under Junit all the scenarios execute on a single thread.
But in the CLI then the scenarios might exec on multiple threads.

The problem then with having a "before feature" hook seems only to be a limitation of the CLI runner and not Junit.

In Junitsthe scenarios are run sequentially within a single feature and on a single thread, and so it seems pretty plausuble to usefully hook the execution just before the first scenario of a feature.

However, in the CLI then each scenarios runs in it's own thread (potentially) and so the "before feature" thing is harder to implement for sure.  The same is true of TestNg (but not JUnit).

Is that also correct?

------

Either way doesn't it seem advisable that the state page should be modified to highlight that if parallelism is in effect then state should only be shared via a thread local?  At present it mentions "global" and "static" vars as issues but does't recommend the thread local approach.

**Comment by mpkorstanje** [comment]
Cucumber was build with the following in mind:

> The fundamental unit of execution is a scenario (or example) and each scenario should be independent.

Also note that JUnit 4 is the exception among test runners.

**Comment by Johnlon** [comment]
Like is said this requirement is nothing to do with scenario independence

**Comment by mpkorstanje** [comment]
You've asked several "why" questions and they fundamentally all come down to that answer. It would be more productive to consider the solution you'd use if you could not use feature hooks.

**Comment by Johnlon** [comment]
Accepted - that this request is probematic.
