### ISSUE TITLE
Create a singleton bean per thread or per feature

### ISSUE THREAD

**Issue by shameekagarwal** [cucumber/cucumber-jvm#2507]
I am trying to use spring boot, cucumber, selenium in conjunction with each other.  
I am creating a singleton bean for the web driver.  
However, the beans are recreated across scenarios.  
Bringing and setting up a browser repeatedly can be expensive.  
How can I go about this?

[full code here](https://gitlab.com/shameekagarwal/end-to-end-test-framework)

RunnerTest.java - 

```java
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("feature")
@ConfigurationParameter(key = Constants.GLUE_PROPERTY_NAME, value = "com.example.framework")
public class RunnerTest {
}
```

CucumberConfig.java

```java
@CucumberContextConfiguration
@SpringBootTest(classes = TestConfig.class)
public class CucumberConfig {
}
```

TestConfig.java - 

```java
@Configuration
@ComponentScan("com.example.framework")
public class TestConfig {
}
```

how I am creating web drivers - 

```java
@Bean
@ConditionalOnProperty(name = "custom.browser", havingValue = "chrome")
public WebDriver chromeDriver() {
  WebDriverManager.chromedriver().setup();
  WebDriver driver = new ChromeDriver();
  return driver;
}
```

how I am creating page objects - 

```java
@Component
@ScenarioScope
@RequiredArgsConstructor
public class AccountPage {

  private final WebDriver driver;

  private final By links_ = By.xpath("//ul[@class='myaccount-link-list']//li");

  public List<WebElement> getLinks() {
    return driver.findElements(links_);
  }
}
```

**Comment by mpkorstanje** [comment]
Did you figure it out or did you close the issue by accident? I've done that before.

**Comment by shameekagarwal** [comment]
> Did you figure it out or did you close the issue by accident? I've done that before.

I actually couldn't figure out, could you help me?

**Comment by shameekagarwal** [comment]
> Then you are looking for an object pool. This example shows one, but you can also keep a list. And it's even better to use a library.
> 
> https://stackoverflow.com/questions/68546784/running-tests-with-cucumber-junit-platform-engine-and-selenium-webdriver-opens-t/68580593#68580593

yes, I had the same issue, thanks!
