### ISSUE TITLE
cucumber-java8 : 7.3.0 uses java10 method Collectors.toUnmodifiableList

### ISSUE THREAD

**Issue by anandshastri1990** [cucumber/cucumber-jvm#2530]
### 👓 What did you see?

Cucumber tests are failing with below error for the latest 7:3:0 version: 
```
java.lang.noSuchMethodError: java.util.stream.Collectors.toUnmodifiableList() Ljava/util/strea/Collector;
at io.cucumber.core.gherkin.messages.GherkinMessagesFeatureParser.parse(GherkinMessagesFeatureParser.java:33)
```

### ✅ What did you expect to see?

cucmber-java8 uses only Java8 and below versions.

### 📦 Which tool/library version are you using?

Java 8
cucumber-java8
cucumber-junit

### 🔬 How could we reproduce it?

1. Update existing test automation project to cucumber-java8 : 7.3.0, cucumber-junit : 7.3.0
2. Run the tests
3. See error 
```
java.lang.noSuchMethodError: java.util.stream.Collectors.toUnmodifiableList() Ljava/util/strea/Collector;
at io.cucumber.core.gherkin.messages.GherkinMessagesFeatureParser.parse(GherkinMessagesFeatureParser.java:33)
```

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by dmohapa** [comment]
I'm also facing this same issue since today morning. Looks like this change pointed out by @anandshastri1990 has made v7.3.0 incompatible with JDK8.

I had to revert to v7.2.3 to get my tests running again
