### ISSUE TITLE
Provide a openejb-jakarta artifact to handle TomEE 9.x

### ISSUE THREAD

**Issue by rzo1** [cucumber/cucumber-jvm#2548]
### 🤔 What's the problem you're trying to solve?

We are currently working on the next TomEE version (9.x), which will handle the Jakarta namespace. 

During our migration efforts (in the example section), we noticed, that a Jakarta artifact for "openejb" would be nice to have to avoid the need to shade / fork / maintain cucumber on our side.

### ✨ What's your proposed solution?

I think, that there are basically to solutions:

- (1) Use the existing "openejb" module, use relocation (javax -> jakarta for the packages needed), release "cucumber-openejb" with a "jakarta" classifier.

- (2) Add a new module "openejb-jakarta", which bascially duplicates the existing module, relocates the namespace and depends on the next TomEE version (currently: 9.0.0-M8-SNAPSHOT). 

### ⛏ Have you considered any alternatives or workarounds?

Currently we are using a shade / fork in TomEE to solve it for the example: https://github.com/apache/tomee/blob/master/deps/cucumber-openejb-shade/pom.xml

### 📚 Any additional context?

If we have discussed a possible solution, I can also create a related PR.

**Comment by mpkorstanje** [comment]
I would consider option 2 the better option. While it duplicates some code, it avoids the complexity of having to deal with one frozen and one evolving dependency. However I'd rather not depend on snapshot versions. Would it be possible to have a dependency on a milestone version (e.g. `-M8`) instead?

**Comment by mpkorstanje** [comment]
I'd be happy to accept a pull request.

Naming wise we already have a `jakarta-cdi` so for consistency I'd name the new module `jakarta-openejb`.

**Comment by rzo1** [comment]
Thanks for the fast feedback. 

We are currently working on `M8` and hope to have a milestone release in the near future, but there is still a lot of open work on the TODO list.

I am fine with option 2 and happy to provide a PR for it. If you like, you can assign the issue to me and I will come back to it, when we have a released milestone.

**Comment by mpkorstanje** [comment]
Fixed by #2583
