### ISSUE TITLE
GlueAdaptor::addDefinition() will create duplicated DocString transformers

### ISSUE THREAD

**Issue by liang-shen** [cucumber/cucumber-jvm#2581]
### 🤔 What's the problem you've observed?

When multiple glue path is configured, (parent->child), JavaBackend::loadGlue() will call GlueAdaptor::addDefinition() for each path. But glue.addDocStringType() won't check whether the input parameter is from same class method. 

### ✨ Do you have a proposal for making it better?

Should filter out the same annotated class method. 

### 📚 Any additional context?

N.A

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by mpkorstanje** [comment]
Cheers, well spotted. For now you can work around it by only providing the parent package.
