### ISSUE TITLE
Cucumber Spring context not loading when using CLI runner

### ISSUE THREAD

**Issue by ebendal** [cucumber/cucumber-jvm#2588]
### 👓 What did you see?

Spring Boot context does not start.

### ✅ What did you expect to see?

Spring Boot context starting.

### 📦 Which tool/library version are you using?

I am using `cucumber-java`, `cucumber-core`, `cucumber-spring`, and `spring-boot`. 

``` xml
<java.version>17</java.version>
<cucumber.version>7.4.1</cucumber.version>
<spring-boot.version>2.6.10</spring-boot.version>
```

### 🔬 How could we reproduce it?

- Make sure you have JDK 17 and Maven installed on your system
- Clone [this](https://github.com/ebendal/cucumber-spring-standalone) repository
- Run the following in your terminal:
``` shell
mvn clean package
java -jar target/cucumber-spring-standalone-0.0.1-SNAPSHOT-jar-with-dependencies.jar
```
You will see the assertion fail that checks whether the Spring context is loaded.

### 📚 Any additional context?

In our pipeline we want to deploy a fat jar to a platform where it runs a test suite when executed. The reports being produced by the test suite we retrieve from the platform and store in the pipeline. The test suite needs functionality that is easily coded with Spring.

Maven produces a fat jar with `io.cucumber.core.cli.Main` as main class. 

In our IDE (IntelliJ), the Cucumber plugin is able to execute the test suite, as provided in the repository:
![Screenshot 2022-07-22 at 08 57 01](https://user-images.githubusercontent.com/41417158/180381808-049f27bb-f2ce-4239-8d49-f2bcf2e95f85.png)

The plugin probably does not use the same `cucumber-core` CLI runner as I packaged in my fat jar, although it does use the CLI runner: 
![Screenshot 2022-07-22 at 08 55 22](https://user-images.githubusercontent.com/41417158/180381524-2b7b3ab0-2f30-46dc-ac7b-bcba9c22ab83.png)

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by mpkorstanje** [comment]
Having only looked but not executed your project please ensure that the plugin correctly merges `META-INF/services` files and does not clobber them. Cucumber depends on SPI to function correctly.

See: https://maven.apache.org/plugins/maven-assembly-plugin/examples/single/using-container-descriptor-handlers.html

Though as you're using Spring, chances are you'll be clobbering other files as well. Consider using Springs executable jar format instead.

**Comment by mpkorstanje** [comment]
Btw, you can verify the packing is the problem by running your tests with a regular jar and adding the depencies to the classpath.

There are many ways to do this but consider: https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-jar-with-dependencies-using-maven/23986765#23986765

**Comment by ebendal** [comment]
Thanks for your feedback. It was indeed a packaging plugin. I resolved the issue by using the Spring Boot Maven plugin for packaging and it works.

``` xml
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.6.10</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>io.cucumber.core.cli.Main</mainClass>
                </configuration>
            </plugin>
```

**Comment by zinking** [comment]
> Thanks for your feedback. It was indeed a packaging problem. I resolved the issue by using the Spring Boot Maven plugin for packaging and it works.
> 
> ```
>             <plugin>
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-maven-plugin</artifactId>
>                 <version>2.6.10</version>
>                 <executions>
>                     <execution>
>                         <goals>
>                             <goal>repackage</goal>
>                         </goals>
>                     </execution>
>                 </executions>
>                 <configuration>
>                     <mainClass>io.cucumber.core.cli.Main</mainClass>
>                 </configuration>
>             </plugin>
> ```

@ebendal  spring-boot-maven-plugin typically doesn't include test classes, and my tests all reside on the test scope (which is typical I think), how do you resolve that.  

do you mind sharing  key pieces of pom.xml here?

**Comment by ebendal** [comment]
@zinking see this [repo](https://github.com/ebendal/cucumber-spring-standalone) for a working example, including `pom.xml`.

When your tests are running during the Maven build, then a `test` scope would be correct. But in my use case (and maybe yours), I want to run these tests from an executable jar somewhere else. Therefore you should see the test suite as `main` code that should be packaged in your executable jar.

**Comment by zinking** [comment]
> repo

thanks for the reply.

and in the spring-boot-maven-plugin repo, devs replied they won't support repackage test scopes as well.

so yeah, since I need to run it standalone, maybe it's no longer test scope anymore.
