### ISSUE TITLE
Better TestNG integration 

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#2593]
### 🤔 What's the problem you're trying to solve?

The current integration with TestNG requires a rather awkward extension of an abstract class and doesn't render scenario names well.

Additionally configuration can be provided though the `@CucumberOptions` annotations or through TestNG.xml. The former is not very fitting for TestNG.

Finally because Cucumber uses TestNGs dataprovider, parallelism is hard to configure (because TestNG made it so). This might be less of an issue for testcases provided by a factory.

### ✨ What's your proposed solution?

Consider using TestNGs `@Factory` to generate a list of test case instances for each pickle. The testcases can implement `ITest` to provide a detailed name.

By using sensible defaults this should allow for a minimal configuration that just works:

```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Cucumber" verbose="1">
    <test name="Suite"  enabled="true">
        <classes>
            <class name="Io.cucumber.testng.Cucumber" />
        </classes>
    </test>
</suite>
```

### 📚 Any additional context?

[A user on Stackoverflow](https://stackoverflow.com/questions/73158232/how-to-control-the-number-of-threads-for-execution-in-cucumber-testng-parallel) claims their(?) project has native TestNG integration. Unfortunately this hasn't been contributed back to Cucumber.

Their(?) project however is stuck(?) on Cucumber V5. So before putting in too much time check if there are obvious technical blockers that keep the project from upgrading. I.e:

1. Check how parallism is supported for factories
2. Check if factories support beforall/afterall
3. Check naming
4. Check ordering
5. Check parameter passing

**Comment by mpkorstanje** [comment]
```java
import org.testng.ITest;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;


public final class Cucumber {

    @Factory
    public Object[] tests() {
        return new Object[] {
                new Scenario("A"),
                new Scenario("B")
        };
    }

    static class Scenario implements ITest {

        private final String name;

        public Scenario(String name) {
            this.name = name;
        }

        @Test
        public void test() {
             System.out.println("Test " + name);
        }

        @Override
        public String getTestName() {
            return name;
        }
    }
}
```

While this should work in theory, in practice the `ITestResult` interface through which this is made available is effectively a property bag. As a result reporters pick properties that are generally applicable (class name, method name, ect) rather  then the name provided through `getTestName`. 

And having looked a bit deeper into TestNG, overall I'd say it is not worth it.

**Comment by nicksav** [comment]
So what to do here? How to change name of the test method?

**Comment by mpkorstanje** [comment]
Without changing TestNG there isn't much that can be done.

Though none of the existing options are great. They all lose some fidelity. Using JUnit 5 with the Cucumber JUnit Platform Engine potentially has the best report names. But only if used directly with the Console Launcher. 

So if you must use TestNG you may have to look into contributing a fix to that project and/or the reporters involved.
