### ISSUE TITLE
I need to get the name of the scenario that will be executed next

### ISSUE THREAD

**Issue by dmchitra** [cucumber/cucumber-jvm#2597]
Is there a way to get the next scenario to be executed in hooks class?

Eg: 
Feature1:
          Scenario 1:
          Scenario 2:
          Scenario 3:

I need get the name of the Scenario 3 when Scenario 2 is running. Is it possible?

**Comment by mpkorstanje** [comment]
No. And it sounds like you are creating a dependency between your scenarios. That's generally speaking not advisable.

Try instead:

```
Scenario: 1
  Given I have a thing
  And another thing
  When I combine those things
  Then magic happens

Scenario: 2
  Given the magic happened
  When I check behind the curtain
  Then the wizard is gone
```  

You can then implement the step  "the magic happened" by doing the things you did in scenario 1 again before continue with the scenario. This keeps them independent.
