### ISSUE TITLE
Get Current Scenario type from hooks before method

### ISSUE THREAD

**Issue by dmchitra** [cucumber/cucumber-jvm#2603]
I want to get the current running scenario is a Scenario Outline or not. Based on that I need to do some modification in my reporting.

Eg: 
Scenario Outline: To test the reporting function
  Given ...
  When ..
Examples:

**Hooks class:**
scenario.getName().toString()  gives " To test the reporting function". 
But I need to fetch the name as "Scenario Outline: To test the reporting function" 

Is there anyway I can get the complete name of the current running scenario?

**Comment by mpkorstanje** [comment]
Hooks aren't made for reporting.

Consider using the plugin system instead. For a brief guide see [this blog](https://blog.jdriven.com/2019/01/cucumber-jvm-plugin/). After that consider looking at [the implementation of the existing plugins](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/main/java/io/cucumber/core/plugin/TeamCityPlugin.java) for more inspiration.

To solve your problem specifically bear in mind that scenario outlines are syntatic sugar. To find the scenario outline for a given testcases you'd have look at the parent(s) of the node with the same line as the testcases.

https://github.com/cucumber/cucumber-jvm/blob/c78d1e98b9ad3372d5c8073d202c7d0f8cd3dc0a/cucumber-core/src/main/java/io/cucumber/core/plugin/TeamCityPlugin.java#L152-L165
