### ISSUE TITLE
IllegalArgumentException path must exist when the path has spaces and the URI has replaced the space with %20 url encoded

### ISSUE THREAD

**Issue by figuedmundo** [cucumber/cucumber-jvm#2606]
When the path, in my case project path, has spaces. the below error observed

```
[ERROR] setUpClass(common.TestRunner)  Time elapsed: 2.057 s  <<< FAILURE!
java.lang.IllegalArgumentException: path must exist: /Users/edmundofigueroa/projects/test test test/automation-testcases-mobile/features

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestRunner>AbstractTestNGCucumberTests.setUpClass:27 » IllegalArgument path mu...
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[ERROR] There are test failures.
```

using cucumber-testng 7.6.1
```
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <version>7.6.1</version>
        </dependency>
```

In debugging mode, I could see that the exception is thrown in  cucumber-core-7.6.0.jar, 
```
package io.cucumber.core.resource
ResourceScanner class > scanForResourcesUri(URI classpathResourceUri)
// classpathResourceUri = file:/Users/edmundofigueroa/projects/test%20test%20test/automation-testcases-mobile/features
```
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/815466/188165827-b06bc1a5-097e-4c0f-9d82-ee6808b63626.png">

the spaces are replaced by %20 which is url encoded space

**Comment by mpkorstanje** [comment]
What does the `TestRunner` class look like.l?

**Comment by figuedmundo** [comment]
I tried the following:
```
@CucumberOptions(
        features = "features",
        glue = "steps",
        plugin = {
                "pretty",
                "html:target/cucumber-reports/cucumber-pretty.html",
                "json:target/cucumber-reports/CucumberTestReport.json",
                "timeline:target/test-output-thread/"
    }
)
public class TestRunner extends AbstractTestNGCucumberTests {
```

```
@CucumberOptions(
        features = "src/main/java/mt/com/automation/features",
        glue = "mt.com.automation.steps",
        plugin = {
                "pretty",
                "html:target/cucumber-reports/cucumber-pretty.html",
                "json:target/cucumber-reports/CucumberTestReport.json",
                "timeline:target/test-output-thread/"
    }
)
public class TestRunner extends AbstractTestNGCucumberTests {
```

**Comment by mpkorstanje** [comment]
I get the impression that the error message is correct and that the `features` directory does not exist in the root of your project.

**Comment by figuedmundo** [comment]
I remove parts of the path as they can be sensitive information, but I can assure you that the project is working as expected for a quite long now. The problem arises when the pipeline name in Jenkins was edited, and a space was added inadvertently in the path.

**Comment by mpkorstanje** [comment]
> But I consider this as a bug as for the filesystem path, as far as I know, the path can't contain the symbol %. While in this case, the path was encoded as an url, %20 is url encoded for a blank space.

I believe you are mistaken here. Note that `scanForResourcesUri` takes a `URI` as an argument. Spaces are not legal characters in a URI and so must be encoded:

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/URI.html

> An illegal character is quoted simply by encoding it. The space character, for example, is quoted by replacing it with "%20". UTF-8 contains US-ASCII, hence for US-ASCII characters this transformation has exactly the effect required by RFC 2396. 

So while your project may not work, it may not work for a different reason. Now I've tried to reproduce your project but unfortunately I seem to be unable to. Could you please provide a minimal reproducer in the form of a github repo? You can use https://github.com/cucumber/cucumber-java-skeleton as a starting point.

**Comment by mpkorstanje** [comment]
Please feel free to reopen this with a minimal reproducer.

**Comment by zgordon02** [comment]
@figuedmundo what was your resolution to this?

**Comment by srimanmittapally5** [comment]
It is solved by providing the right path of **features** directory.
**For Example**: "src/test/resources/features"
