### ISSUE TITLE
@BeforeAll and @AfterAll hooks with access to data about all tests

### ISSUE THREAD

**Issue by kamil1014** [cucumber/cucumber-jvm#2612]
### 🤔 What's the problem you're trying to solve?

I'm looking for global hooks @AfterAll with access to data about test results, their names etc.

### ✨ What's your proposed solution?

Give access to global Cucumber data or send parameter to method like Scenario for @After

### 📚 Any additional context?

I'm looking for static data that store data about all tests from single execution

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by mpkorstanje** [comment]
> I'm looking for global hooks @afterall with access to data about test results, their names etc.

This seems like a solution, not the problem you are trying to solve. What problem are you trying to solve?

**Comment by kamil1014** [comment]
I want to send notification after all tests with name of those which failed (via sms, email)

**Comment by mpkorstanje** [comment]
Ah. Consider implementing the `Plugin` interface. It's made for reporting. You can then use `--plugin com.example.MyPlugin` or the property `cucumber.plugin=com.example.MyPlugin` to enable it.

Or if you're using JUnit 5 to run Cucumber, you can also use a TestExecutionListener. 

[optional/output/file.txt](https://junit.org/junit5/docs/current/user-guide/#launcher-api-listeners-custom)
