### ISSUE TITLE
How to Execute Cucumber Features in Parallel using TestNG?

### ISSUE THREAD

**Issue by pabitra-qa** [cucumber/cucumber-jvm#2615]
Is there an option to pass the features through dataprovider to execute cucumber features in parallel instead of scenarios?

```
import org.testng.annotations.DataProvider;
import io.cucumber.testng.AbstractTestNGCucumberTests;

public class RunCucumberTest extends AbstractTestNGCucumberTests{

    @Override
    @DataProvider(parallel = true)
    public Object[][] scenarios() {
        return super.scenarios();
    }
}
```

**Comment by mpkorstanje** [comment]
There is no such feature.

Scenarios are assumed to be independent from each other. If this isn't the case for you, consider rewriting them so that they are.

**Comment by pabitra-qa** [comment]
@mpkorstanje I got you. I know that JUnit4 runs features in parallel. Is the same stuff possible in JUnit5 by any chance?

**Comment by mpkorstanje** [comment]
It was possible in JUnit 4 due to limitations of JUnit 4. It is possible in JUnit 5 for backwards compatibility. But you should not depend on it.
