### ISSUE TITLE
Exclude steps in scenarios marked as Ignored from the relevant plugin

### ISSUE THREAD

**Issue by sgkiokas** [cucumber/cucumber-jvm#2619]
I am using cucumber `7.7.0` along with JUnit 5 as my main runner. I have also put in my properties the use of the `unused` plugin as follows:

```
...
cucumber.plugin=pretty,io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm,unused:build/report/usage.log
...
```

The plugin works as expected and flags all the unused steps in my scenarios.

I was thinking that it would be nice to have a flag/property to exclude from the report any step within a scenario (or feature file) that has been marked as `@Ignored`. 

As a workaround for now I was thinking to simply parse the report created in combination with the feature files/scenarios' subset marked as ignored and amend the report accordingly by removing a step that belongs to the previous category from it. The problem with that is that if a step has been developed in such way that in its annotation has wildcards or alternative wording (e.g. `a/the user/customer/users/customers logs/log in`) then the permutations will start increasing.

**Comment by mpkorstanje** [comment]
You can execute Cucumber in dry-run mode using a property. If you combine this with a separate suite that does not filter on tags you'll get list of steps that are not used by any scenario.

https://github.com/cucumber/cucumber-jvm/blob/0b85df00b78cbfd45c07ae3fb28fe8d8c2363ccc/cucumber-core/src/main/java/io/cucumber/core/options/Constants.java#L27

**Comment by sgkiokas** [comment]
Thanks for the swift response @mpkorstanje. I will try some of your suggestions since they are definitely quicker that what I initially had in mind. I believe you could close this issue if you do not have to add anything more  :-)
