### ISSUE TITLE
cucumber.glue propertie from cucumber.properties always overwritten by default value.

### ISSUE THREAD

**Issue by reverant** [cucumber/cucumber-jvm#2622]
### 👓 What did you see?

When setting cucumber.glue property in cucumber.properties it is always overwritten by a package of class with cucumber options annotation.

### ✅ What did you expect to see?

If glue is set in cucumber.properties don't overwrite it by default value. 

### 📦 Which tool/library version are you using?

Cucumber 7.4.1 used with java 11.0.13 

### 🔬 How could we reproduce it?

Steps to reproduce the behaviour:
1. set glue in cucumber.properties.
2. run test

**Comment by reverant** [comment]
Ah sorry, I forgot to mention I'm using cucumber-testng version.

**Comment by mpkorstanje** [comment]
Ah, I see.

Then it is mostly the same problem. But if you are running your tests via the XML suite you can define the glue there and it will override the annotation.

https://github.com/cucumber/cucumber-jvm/tree/main/cucumber-testng#configure-cucumber-options-via-testng-xml

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Example Suite">
	<parameter name="cucumber.glue" value="com.example.glue"/>
	
	<test name="Vegetable garden" preserve-order="true">
        <parameter name="cucumber.features" value="classpath:com/example/features/vegetable"/>
		
		<classes>
			<class name="com.example.RunCucumberTests"/>
		</classes>
	</test>
 	
	<test name="Herb garden" preserve-order="true">
		<parameter name="cucumber.features" value="classpath:com/example/features/herbs"/><classes>
			<class name="com.example.RunCucumberTests"/>
		</classes>
	</test>
</suite>
```
