### ISSUE TITLE
UndefinedStepException in version 7.x

### ISSUE THREAD

**Issue by cmclopes** [cucumber/cucumber-jvm#2628]
### 👓 What did you see?

I've been using the cucumber-java lib version 6.11.0 until now on my projects, and I decided to try running my test suite with the latest 7.8.1. When I do so, the lib throws an `io.cucumber.junit.UndefinedStepException.`

This is the step definition which works fine on 6.11.0 but gets "UndefinedStepException" by 7.8.1

```java
@Given("(that )the http client {string} is set with {string} (from|as) {string} and invoked, expecting status code {int}")
public void setupHttpClientAndInvoke(String clientName, String sinkDef, String sourceDef,
        int expectedStatusCode) {
    ...
}
```

in the feature file:

```
Given the http client "clientName" is set with "sinkDef" from "sourceDef" and invoked, expecting status code 200
```

### ✅ What did you expect to see?

Upgrade the library without refactoring the tests unless I missed some migration documentation when the lib moved from 6.x to 7.x.

### 📦 Which tool/library version are you using?

Java 8, maven-surefire-plugin 2.17 and cucumber-java 7.8.1

**Comment by mpkorstanje** [comment]
You are using a Cucumber expression. And at glance `(from|as)` should be (from/as)`. The `|` worked in v6 because Regex characters in a Cucumber expression were not properly escaped in all situations.

https://github.com/cucumber/common/pull/771

**Comment by cmclopes** [comment]
Hi @mpkorstanje , thanks for your help. Yes, with your suggestion, it works fine with 7.x!
