### ISSUE TITLE
Eclipse JUnit reports inaccurate run count

### ISSUE THREAD

**Issue by dgradl** [cucumber/cucumber-jvm#263]
Using the eclipse JUnit feature cucumber junit is over-reporting the run count by seemingly double.  For example with 4 scenarios of 3 steps (with steps not written yet) each it reports Runs: 24/12.    In terms of the double counting it seems to be a matter of the way in which JUnitReporter is sending notifier events to the EachStepNotifier.  It doesn't seem to be consistent with JUnit itself, where if a test is ignored, it does a fireTestIgnored without a fireTestStarted.

I also question whether each individual cucumber step (GIVEN, WHEN, THEN) should be counted as a run as opposed to just the scenario or example itself.    I generally expect the run count to give me a number of tests invoked (in JUnit it is a reflection of number of @Tests).   However, its really only a count of steps.  After writing several scenarios with multiple GIVEN-AND and THEN-ANDs on a project I am working on it reported 390 runs, but its really only 90 some tests executed.

**Comment by mayanksahai** [comment]
hi any update on this. recently moved from old cuke4duke to cucumber-jvm and like it quite a lot but this issue is still a bottleneck. i am using teamcity for build. any deadlines yet ?

**Comment by proninja** [comment]
Are there any updates or solutions? This bug is a showstopper for me, because the number of tests is wrong, when they are run by the Team City or Jenkins.

**Comment by ArthurBilyk** [comment]
Hi guys,
Is there a workaround for this problem?
It's very sad that this bug won't be fixed :(

**Comment by mpkorstanje** [comment]
This will be fixed with #1135.
