### ISSUE TITLE
io.cucumber.junit.FeatureRunner$FeatureId cannot be cast to gherkin.formatter.model.Feature

### ISSUE THREAD

**Issue by JustinH1989** [cucumber/cucumber-jvm#2636]
Not really sure if this is a bug but I am not able to get passed this step in my Maven Build.
My integration tests pass successfully but I receive the following error message at the end of my build and the build fails:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project HostAPITesting:

[ERROR] ExecutionException There was an error in the forked process
[ERROR] Test mechanism :: io.cucumber.junit.FeatureRunner$FeatureId cannot be cast to gherkin.formatter.model.Feature
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException There was an error in the forked process
[ERROR] Test mechanism :: io.cucumber.junit.FeatureRunner$FeatureId cannot be cast to gherkin.formatter.model.Feature
`
I do see that The junit Feature runner class generates a feature ID, but it cannot cast to the Gherkin class which is on info.cukes:gherkin 2.12.2 version however this is not specified anywhere in the POM of my project and I am not sure where is it getting this dependency from. 

I have checked online but I cannot find any solution, any assistance will be appreciated, 

I am using io.cucumber version 7.8.1 in my project with a junit-surefire-plugin

**Comment by JustinH1989** [comment]
> Not really sure if this is a bug but I am not able to get passed this step in my Maven Build. My integration tests pass successfully but I receive the following error message at the end of my build and the build fails: `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project HostAPITesting:
> 
> [ERROR] ExecutionException There was an error in the forked process [ERROR] Test mechanism :: io.cucumber.junit.FeatureRunner$FeatureId cannot be cast to gherkin.formatter.model.Feature [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException There was an error in the forked process [ERROR] Test mechanism :: io.cucumber.junit.FeatureRunner$FeatureId cannot be cast to gherkin.formatter.model.Feature ` I do see that The junit Feature runner class generates a feature ID, but it cannot cast to the Gherkin class which is on info.cukes:gherkin 2.12.2 version however this is not specified anywhere in the POM of my project and I am not sure where is it getting this dependency from.
> 
> I have checked online but I cannot find any solution, any assistance will be appreciated,
> 
> I am using io.cucumber version 7.8.1 in my project with a junit-surefire-plugin

**Comment by mpkorstanje** [comment]
>  I do see that The junit Feature runner class generates a feature ID, but it cannot cast to the Gherkin class which is on info.cukes:gherkin 2.12.2 version however this is not specified anywhere in the POM of my project and I am not sure where is it getting this dependency from.

I suspect you may be pulling in this dependency transitively. You can try to use `mvn dependency:tree` to see where the dependency comes from. Alternatively you can [cucumber-java-skeleton](https://github.com/cucumber/cucumber-java-skeleton) to see the a minimal working setup.
