### ISSUE TITLE
None of the features at [classpath:features] matched the filters:

### ISSUE THREAD

**Issue by Khushburao35** [cucumber/cucumber-jvm#2646]
Hi I am trying to run cucumber runnable jar from cmd and getting error : None of the features at [classpath:features] matched the filters:
this is in my Runner class

@CucumberOptions(
		features = "classpath:features",
		glue= {"StepDefinition"},
		tags={"@SU_Smoke1"} 
		)

My main class  contains below:
public static void main(String args[]) throws Throwable {
		
		/*String[] arguments = {"SU_Smoke1.feature"};
	    cucumber.api.cli.Main.main(arguments);*/
		try {
			 cucumber.api.cli.Main.main(
					 new String[]{
							 
				"-g", "Tasks",
				"-g", "StepDefinition",
				"-g", "Runner",
				"classpath:features",
				"-t","@SU_Smoke1",				
				"-p", "pretty",			
				"-m"
			}
			);
		}

**Comment by mpkorstanje** [comment]
If you want to report a bug, you should include sufficient information to reproduce the problem. Currently that is impossible. 

Please have a look at https://stackoverflow.com/help/mcve and feel free to open a new issue afterwards.

Note that you can fork https://github.com/cucumber/cucumber-java-skeleton to get a good starting point.
