### ISSUE TITLE
Rewrite Groovy code generation to Java

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#2648]
### 🤔 What's the problem you've observed?

The `cucumber-java` and `cucumber-java8` module generate [annotations](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-java/src/main/groovy/generate-annotations.groovy) and [interfaces](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-java8/src/main/groovy/generate-interfaces.groovy) using a groovy script.

Unfortunately the `groovy-maven-plugin` doesn't support Java 17 source code yet (https://github.com/groovy/gmaven/issues/28). While we currently only have to run on Java 17 for https://github.com/cucumber/cucumber-jvm/pull/2644 it is not unimaginable that at some point in the future we'll also want to compile our own source code with 17 as well.

### ✨ Do you have a proposal for making it better?

With the increased release cadence of Java it would be prudent to keep the technology stack shallow and remove the dependency on Groovy and Groovy related components al together. So replacing the whole stack with pure Java would be beneficial.

### 📚 Any additional context?

There is a small chicken and egg problem to solve. Generating code with Java requires that the Java code is compiled. However because we are generating code, nothing has been compiled yet.

**Comment by mpkorstanje** [comment]
It is possible to execute the `maven-compile-plugin` in the `generate-sources` phase. So it should be possible to compile the source generation code before executing it.

https://stackoverflow.com/a/43187728/3945473

**Comment by mlvandijk** [comment]
Potential templating engines:
* [Apache Velocity](https://velocity.apache.org/)
* [Apache FreeMarker](https://freemarker.apache.org/)
* [StringTemplate](http://www.stringtemplate.org/)

**Comment by mlvandijk** [comment]
From quick search, FreeMarker looks to be the most popular / active, so I'll try that out.
