### ISSUE TITLE
None of the features at [classpath:features] matched the filters: [@SU_Smoke1]

### ISSUE THREAD

**Issue by Khushburao35** [cucumber/cucumber-jvm#2653]
Hi I am trying to run cucumber runnable jar from cmd and getting error : None of the features at [classpath:features] matched the filters:
command- C:\Users\01643K744\Downloads\CucumberAutomationSU\CucumberAutomationSU\CucumberAutomation\target>java -jar DHLCucumberFramework-0.0.1-SNAPSHOT-jar-with-dependencies.jar -Dcucumber.filter.tags="@SU_Smoke1"

this is in my Runner class

@CucumberOptions(
features = "classpath:features",
glue= {"StepDefinition"},
tags={"@SU_Smoke1"}
)

My main class contains below:
public static void main(String args[]) throws Throwable {

	/*String[] arguments = {"SU_Smoke1.feature"};
    cucumber.api.cli.Main.main(arguments);*/
	try {
		 cucumber.api.cli.Main.main(
				 new String[]{
						 
			"-g", "Tasks",
			"-g", "StepDefinition",
			"-g", "Runner",
			"classpath:features",
			"-t","@SU_Smoke1",				
			"-p", "pretty",			
			"-m"
		}
		);
	}

My Feature file (SU_Smoke1.feature) contains:
@SU_Smoke1
Feature: SU_Smoke1
Scenario: SU_Smoke1: Smoke WMS OMS
Given User clicks on OMS
And User clicks on WMS

**Comment by mpkorstanje** [comment]
Hi! Please include sufficient information to reproduce your problem. Have a careful look at:
- https://stackoverflow.com/help/how-to-ask
- https://stackoverflow.com/help/minimal-reproducible-example

When you've done so please open a new issue and follow the template for reporting bugs.
