### ISSUE TITLE
@MockBean not Working with SpringBootTest and Junit5

### ISSUE THREAD

**Issue by sashokbg** [cucumber/cucumber-jvm#2654]
### 👓 What did you see?

When running a SpringBootTest with JUnit5 (Jupiter) all @MockBean annotations are not populated.

### ✅ What did you expect to see?

Running the same test without cucumber configuration works with no issue.

### 📦 Which tool/library version are you using?

Java - JDK 17
SpringBoot 2.7
Junit Jupiter - 5.8.2
cucumber-java - 7.8.1
cucumber-spring - 7.8.1
cucumber-junit-platform-engine - 7.8.1

### 🔬 How could we reproduce it?

Cucumber Test as described in the documentation
```
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("features")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.proxym.bankerise.backend.messagecenter.domain")
@ConfigurationParameter(key = FILTER_TAGS_PROPERTY_NAME, value = "@Active")
public class MessageCenterApplicationIT {

}
```

StepsFile

```
@CucumberContextConfiguration
@SpringBootTest(classes = TestConfig.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@SpringJUnitConfig
public class MessageCenterSteps {
    @Autowired
    private ApplicationContext applicationContext; // <-- works properly injected

    @MockBean
    private EmailChannelAdapter emailChannelAdapter; <-- not working

```

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by mpkorstanje** [comment]
Could you sprinkle some breakpoints in the `MockitoTestExecutionListener` and see what happens?

**Comment by sashokbg** [comment]
Hello, thank you for prompt response !

I was already debugging and it turns out the spring context gets properly populated with the mocked beans.

I put a breakpoint in my @BeforeAll and did inject the Spring ApplicationContext then did in evaluate mode "context.getBean(EmailChannelAdapter.class)" and it returns the mock.

This means that the problem is in the injection of the beans.

After following your advice:

I found out that inside the following method in the MockitoTestExecutionListenr, if I set the property REINJECT_DEPNDENCIES_ATTRIBUTES to true - then everything works fine.

	@Override
	public void beforeTestMethod(TestContext testContext) throws Exception {
		if (Boolean.TRUE.equals(
				testContext.getAttribute(DependencyInjectionTestExecutionListener.REINJECT_DEPENDENCIES_ATTRIBUTE))) {
			initMocks(testContext);
			reinjectFields(testContext);
		}
	}

Any ideas ?

**Comment by mpkorstanje** [comment]
Sounds like https://github.com/cucumber/cucumber-jvm/issues/2572, specifically we don't invoke `prepareTestInstance`. 

https://github.com/cucumber/cucumber-jvm/blob/51cde873cc860c33665c777ffe3bdbb06612941e/cucumber-spring/src/main/java/io/cucumber/spring/TestContextAdaptor.java#L52-L58

As you can see we create a test instance by pulling it from the application context. This ensures the test instance is a bean that can be injected into other step definitions and other steps can be injected into it.

JUnit doesn't have this requirement (only one test class ever). So JUnit creates the test instance using the zero-arg constructor and outside of the application context. By invoking `prepareTestInstance` JUnit then auto wires the spring and mock beans.

I have no idea what would happen if we do call `prepareTestInstance` on a bean.

**Comment by mpkorstanje** [comment]
This may provide a solution with `AUTOWIRE_NO`.

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/config/AutowireCapableBeanFactory.html#initializeBean(java.lang.Object,java.lang.String)

**Comment by sashokbg** [comment]
Hello @mpkorstanje and thank you for your help.

Unfortunately I don't really understand how to properly configure the AutowireCapableBeanFactory for cucumber context :( - do you have any examples of how it is done ? I tried searching on the internet but results are sparse.

**Comment by mpkorstanje** [comment]
If you want to, you'd have to fix it in the `[TestContextAdaptor.java](https://github.com/cucumber/cucumber-jvm/blob/51cde873cc860c33665c777ffe3bdbb06612941e/cucumber-spring/src/main/java/io/cucumber/spring/TestContextAdaptor.java#L52-L58)` and send a pull request.

**Comment by sashokbg** [comment]
I will try to do that tonight after work hours - being busy at the moment.
Thank you

**Comment by mpkorstanje** [comment]
Cheers. No rush though.

**Comment by sashokbg** [comment]
@mpkorstanje #2655 opened. I mentioned you in the second commit message since you solved the issue :)
