### ISSUE TITLE
Update JUnit Platform Engine docs 

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#2677]
### 🤔 What's the problem you're trying to solve?

With https://github.com/junit-team/junit5/pull/3044 released in 5.9.1 the docs for the platform engine still state: 

> Note: Cucumber does not guarantee that the number of concurrently executing tests will not exceed the configured parallelism. The underlying ForkJoinPool used to execute scenarios may spawn additional threads. To obtain such guarantees us a custom parallel configuration strategy.

### ✨ What's your proposed solution?

Update the docs to explain that since 5.9.~1~2 the property can be used. Also add the property to the list of properties.

### 📚 Any additional context?

Fixes: https://github.com/cucumber/cucumber-jvm/issues/2512.

**Comment by fslev** [comment]
Since 5.9.2
