### ISSUE TITLE
Potential copy-paste error in `CucumberPropertiesParser.java`: `FEATURES_PROPERTY_NAME`

### ISSUE THREAD

**Issue by rubienr** [cucumber/cucumber-jvm#2678]
### 👓 What did you see?
While scrolling the code for an other issue I found this potential copy-paste error in [CucumberPropertiesParser.java](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/main/java/io/cucumber/core/options/CucumberPropertiesParser.java#L66-L74).

### ✅ What did you expect to see?
```java
        parseAll(properties,
            FEATURES_PROPERTY_NAME,
            splitAndThenFlatMap(CucumberPropertiesParser::parseFeatureFile),
            builder::addFeature);

        parseAll(properties,
            RERUN_PROPERTY_NAME, // not FEATURES_PROPERTY_NAME
            splitAndThenFlatMap(CucumberPropertiesParser::parseRerunFile),
            builder::addRerun);
```

### 📦 Which tool/library version are you using?
Branch main, latest file commit ee6b693.

### 🔬 How could we reproduce it?

Sorry, I didn't try it out.

**Comment by rubienr** [comment]
Thank you for the quick clarification.

**Comment by mpkorstanje** [comment]
I'll leave this open as a reminder to a comment.
