### ISSUE TITLE
Can not run parallel test with Spring boot 3 and AOT

### ISSUE THREAD

**Issue by ntthaibk** [cucumber/cucumber-jvm#2686]
### 👓 What did you see?

Please refer to this [Sample Github Repo](https://github.com/ntthaibk/spring-cucumber-parallel-demo.git)
When I run the test in parallel with `mvn clean test` without provide the -Dgroups for maven surefire plugins, the test is run smoothly, but when I do. running the test with `mvn clean test -Dgroups=DEBUG` it run into a racing condition and throw `java.lang.IllegalArgumentException: AOT attributes cannot be overridden. Name '[org.springframework.boot.test.context.SpringBootTestContextBootstrapper.SpringBootConfiguration.com](http://org.springframework.boot.test.context.springboottestcontextbootstrapper.springbootconfiguration.com/).mdaq.testing.api.ApplicationTests' is already in use.`

### ✅ What did you expect to see?

The test can run in parallel when providing tags

### 📦 Which tool/library version are you using?
- I'm using JDK 17 + Spring boot 3.0.1 with cucumber 7.10.1 and JUnit 5.9.2

### 🔬 How could we reproduce it?

[Sample Github Repo](https://github.com/ntthaibk/spring-cucumber-parallel-demo.git)

clone the sample github repo
run `mvn clean test -Dgroups=DEBUG` couple of time and the issue will show up

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by mpkorstanje** [comment]
In brief, the problem is that invoking `new TestContextManager(someContextConfiguration)` for identical instances of `someContextConfiguration` is not actually thread-safe. Spring caches the configuration derived from `someContextConfiguration` and when AOT is used, will fail to apply idempotent updates configuration .

It's not quite clear to me why `-Dgroups=DEBUG` is essential to reproducing the problem.
