### ISSUE TITLE
Unfinished sentence in Javadoc 

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#2690]
### 👓 What did you see?

> Thought to point out an unfinished sentence here. It's [still present in `main`](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/main/java/io/cucumber/core/options/Constants.java#L124).
> @timtebeek - https://github.com/cucumber/cucumber-jvm/commit/ad47dd5000c4d40151e99d35418ea58b76f41d2c#r98362078

**Comment by vishesh10** [comment]
Hi @mpkorstanje,
I have added a PR for this issue. Can you please have a look.
Thanks
