### ISSUE TITLE
Improve feature loading performance by changing UUID generator

### ISSUE THREAD

**Issue by jkronegg** [cucumber/cucumber-jvm#2698]
### 👓 What did you see?

The Cucumber Java event bus uses UUID as event identifiers. These UUIDs are generated using the JDK `java.util.UUID.randomUUID()`.
This kind of generators known to be slow (e.g. https://stackoverflow.com/questions/14532976/performance-of-random-uuid-generation-with-java-7-or-java-6). On my project (~450 test scenarios, ~50 rules) this UUID generator takes about 25% of the feature file loading time on the IntelliJ profiler flame graph (~2% of the total CPU time).

This generator is used for each each rule and each scenario step line : that corresponds to ~100'000 calls for my project.

### ✅ What did you expect to see?

Using a faster UUID generator would improve the feature file loading performance. For example, https://github.com/cowtowncoder/java-uuid-generator provides a time sequence UUID generator which is much faster. 

From what I've seen, the solution could be very simple as the `EventBus` is instanciated in `io.cucumber.core.runtime.Runtime.Builder` with `UUID::randomUUID` : we need to change this generator to get a good performance improvement. Note that other calls to `UUID.randomUUID()` are also made elsewhere in the project but I didn't saw big performance impact.

### 📦 Which tool/library version are you using?

Cucumber Java 7.11.1

### 🔬 How could we reproduce it?

1. Run IntelliJ profiler on a project with about 50 rules with cucumber-java 7.11.1.
2. Look for the `loadFeatures` block on the flame graph: on the top is the `java.util.UUID.randomUUID()` call
[uuid_flame_graph.zip](https://github.com/cucumber/cucumber-expressions/files/10825917/uuid_flame_graph.zip)

### 📚 Any additional context?

N/A

**Comment by mpkorstanje** [comment]
Unfortunately I haven't had time to consider this yet.

**Comment by mpkorstanje** [comment]
Unfortunately I've not been able to give this the consideration this is due just yet. Never the less this are my quick consideration:

 * I believe that #2035 is a major contributing factor this this problem. The resolution of this depends on the deprecation of `cucumber-java8` and it's replacement with `cucumber-lambda` (#2279).  This is unfortunately a long way away.
 * I would like to avoid adding a dependency to Cucumber. 
 * I would like to retain the ability to use random UUIDs. The messages from one process should not collide with those from another process. This becomes much more likely when using a time based UUID. 
 * A brief glance at the difference UUID generators shows a cacophony of possible options and properties for the different generators. I do not believe we can pick the correct one for all use cases.

Based on this I reckon the best course of action would be to 

1. Retain the random UUID generator as the default
2. Refactor the default UUID generator into a implementation that is loaded via SPI.
3. Provide a property to select other UUID generators via SPI (note: this should work with `cucumber.properties`, `junit-platform.properties`, `@CucumberOption`, environment variables and the CLI).

For reference look at the current [ObjectFactoryServiceLoader](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/main/java/io/cucumber/core/runtime/ObjectFactoryServiceLoader.java) implementation.

**Comment by jkronegg** [comment]
I think a time-based UUID will work (there is no collision risk when using multithreading in the same JVM because the generators are have a time-based component and a counter component).

But I agree on the other arguments:
- On my project, the parser generates about 5000 UUIDs when the rest of test framework generates about 90'000 UUIDs: thus, it's probably true that #2035 is a major contributing factor (although I didn't verify).
- It's better to avoid adding dependencies.
- There are lot of configuration options in UUID generators.

Configuring the UUID generator using SPI is a good solution to delegate the choice to the user. But as the user will need to add specific configuration, it's not guaranteed that many people will use this feature.

@mpkorstanje do you think it is worth doing it now, or is it better to invest development time on #2035 / #2279 ?

**Comment by mpkorstanje** [comment]
> I think a time-based UUID will work (there is no collision risk when using multithreading in the same JVM because the generators are have a time-based component and a counter component).

Reports may be generated on different JVMs at the same time. A typical example would be one suite that tests against Firefox and another against Safari.

There are ofcourse solutions for this as well but the advantage of the random UUID is that they'll work in all situations.

> But as the user will need to add specific configuration, it's not guaranteed that many people will use this feature.

That is rather unfortunate indeed. Though technically the cost is rather low. So in my estimation it evens out.

> @mpkorstanje do you think it is worth doing it now, or is it better to invest development time on https://github.com/cucumber/cucumber-jvm/issues/2035 / https://github.com/cucumber/cucumber-jvm/issues/2279 ?

As a maintainer I would generally favour the long term approach. But the 5% improvement you mentioned is something that can be achieved in the short term and mostly without my input. So I think it mostly depends on your willingness and interests.

**Comment by jkronegg** [comment]
Ok, I'll do it.
