### ISSUE TITLE
Fix release artifacts so cucumber-clojure can be released.

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#270]
/cc @nilswloka @rplevy-draker @hiredman

Release 1.0.0.RC23 does not include cucumber-clojure because sonatype-nexus (where jars are deployed) refuse to release artifacts that don't have javadoc (idiotic, but that's the way it is - see #231).

The workaround is to include a dummy java class (or perhaps a package.html) in cucumber-clojure now that the entire backend is implemented in clojure. 

At the same time, we should also exclude the various examples from the release.

**Comment by mpkorstanje** [comment]
Ran into this one again for  #1336. Fixed it using:

https://vzurczak.wordpress.com/2014/08/01/generate-an-empty-javadoc-jar-file/

```xml
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>empty-javadoc-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <classifier>javadoc</classifier>
                            <classesDirectory>${basedir}/javadoc</classesDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
