### ISSUE TITLE
Corrupted Cucumber.xml when using surefire.rerunFailingTestsCount parameter

### ISSUE THREAD

**Issue by carmenloghin** [cucumber/cucumber-jvm#2709]
### 👓 What did you see?

Using Cucumber 7.11.0 or 7.11.1  and **surefire.rerunFailingTestsCount** parameter in order to run the UI tests pack, I noticed the report is no longer generated on Azure DevOps and the following warning message is displayed:

##[warning]Failed to read /home/vsts/work/1/s/ui/target/cucumber-xml-reports/cucumber.xml. Error : Unexpected end of file while parsing Name has occurred. Line 44, position 10..

### ✅ What did you expect to see?

With other version of Cucumber (tested with versions from 7.5 to 7.10), I saw the report generated like 

![Screenshot 2023-03-17 at 11 13 05](https://user-images.githubusercontent.com/97223571/225862418-539b2ae2-2d68-4810-b3c7-3c096ab316ab.png)

### 📦 Which tool/library version are you using?

Cucumber 7.11.0/7.11.1, Selenium 4.8, Java 11, Maven compiler 3.10, Maven Surefire Plugin 3.0.0-M7, Azure DevOps

### 🔬 How could we reproduce it?

1. Install 'Cucumber' version '7.11.0 or 7.11.1', Java version 11, Selenium version 4.8, Maven compiler version 3.10, Maven Surefire Plugin version 3.0.0-M7
2. Have a feature file (with 4 scenarios, 2 of them need to fail in order to be rerun again and the cucumber report to be generated with the new results ) which run in an Azure DevOps pipeline, on a Docker machine, with the maven command: '-Dcucumber.filter.tags="@Smoke" **-Dsurefire.rerunFailingTestsCount=1**' and test results file being created at '$(Build.SourcesDirectory)/ui/target/cucumber-xml-reports/cucumber.xml'
3. Run the pipeline and inspect the results
4. The build is green, even if there are failed tests. When looking at the results in the logs, I could see: 
[WARNING] ForkStarter IOException: Element name cannot be empty
Element name cannot be empty. See the dump file /home/vsts/work/1/s/ui/target/surefire-reports/2023-03-20T06-39-40_033-jvmRun1.dumpstream

6. See warning 
##[warning]Failed to read xxxxxx/ui/target/cucumber-xml-reports/cucumber.xml. Error : Unexpected end of file while parsing Name has occurred. Line 44, position 10..
***********************************************
This defect is reproducing on my local machine as well:
1. Have a feature file with tag @Test(with 4 scenarios, 2 of them need to fail in order to be rerun again and the cucumber report to be generated with the new results ) and a TestRunner class 
@Suite
@IncludeEngines("cucumber")
@SelectDirectories("src/test/java/features")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "steps")
@SuiteDisplayName("UI tests")
@IncludeTags("Test")
public class RunCucumberTest {

} 
2. Run in maven terminal the command:  **mvn test -Dcucumber.filter.tags="@Test" -Dsurefire.rerunFailingTestsCount=1** 
3. Open the cucumber.xml, the file contains only the first test which failed, and after the tag </testcase> is closed, another tag for test case is not fully open, showing like this **<testcase**

### 📚 Any additional context?

From what I could see, this problem appears only when tests fail. 
The content of the cucumber.xml file generated after running the tests on my local machine looks like this 
```<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Cucumber" time="11.255" tests="2" skipped="0" failures="2" errors="0">
<testcase classname="Test" name="xxx" time="4.858">
<failure type="org.opentest4j.AssertionFailedError" message="Number of connections is not correct ==&gt; expected: &lt;20&gt; but was: &lt;0&gt;">
<![CDATA[org.opentest4j.AssertionFailedError: Number of connections is not correct ==> expected: <20> but was: <0>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:575)
	at steps
	at ✽.xxx(file:///Users/xxx/ui/src/test/java/features/Test.feature:65)
]]>
</failure>
<system-out><![CDATA[
Given xxxx..passed
And xxx......passed
And xxx......passed
And xxx......failed
And xx.......skipped
Then xx......skipped
]]></system-out>
</testcase>
<test</testcase>
<testcasecase
 ```

**Comment by mpkorstanje** [comment]
Do you have the full stacktrace for:

```
[WARNING] ForkStarter IOException: Element name cannot be empty
Element name cannot be empty. See the dump file /home/vsts/work/1/s/ui/target/surefire-reports/2023-03-20T06-39-40_033-jvmRun1.dumpstream
```

It should be in the dumpstream file.

**Comment by mpkorstanje** [comment]
I suppose you didn't configure your pipeline to capture it. Is the dump file also absent if you reproduce the problem locally? It would help a lot because it would provide the exact line that makes the mistake.

**Comment by mpkorstanje** [comment]
Okay. I think I found it.

You most likely have a scenario without a name. For example:

```feature
Feature: Example
  Scenario:
    Given a calculator I just turned on
    When I add 4 and 7
    Then the result is 2
```

As a work around you can  give your scenario a name.

**Comment by mpkorstanje** [comment]
Nope. That's not actually it. 

Weird thing is, I can get a stack trace, but it's nothing like yours:

```
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
        at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at io.cucumber.junitxmlformatter.XmlReportData.getFeatureName(XmlReportData.java:207)
        at io.cucumber.junitxmlformatter.XmlReportWriter.writeTestCaseAttributes(XmlReportWriter.java:86)
        at io.cucumber.junitxmlformatter.XmlReportWriter.writeTestcase(XmlReportWriter.java:77)
        at io.cucumber.junitxmlformatter.XmlReportWriter.writeTestsuite(XmlReportWriter.java:45)
        at io.cucumber.junitxmlformatter.XmlReportWriter.writeXmlReport(XmlReportWriter.java:34)
        at io.cucumber.junitxmlformatter.MessagesToJunitXmlWriter.close(MessagesToJunitXmlWriter.java:60)
```
And I do need two failing scenarios in a feature to trigger the problem. Otherwise nothing happens at all.

**Comment by mpkorstanje** [comment]
Cheers. Then I think I've got it.
