### ISSUE TITLE
Filter Execution with tag contains : character not working

### ISSUE THREAD

**Issue by ndagnhat** [cucumber/cucumber-jvm#2712]
1. Create scenario like below:
![image](https://user-images.githubusercontent.com/65029229/226798896-63020f95-bc85-41c8-b492-00e4153f7859.png)
2. Run command `mvn clean verify -Dtags="@id:6"`
3. You can see scenario with tag = @id:6 not run

**Comment by mpkorstanje** [comment]
Can you explain why you think that should work?

**Comment by ndagnhat** [comment]
I see that in ‘cucumber with serenity’ document. I should not log issue on this project. I will close it.
