### ISSUE TITLE
NullPointerException in GuiceFactory masks root cause

### ISSUE THREAD

**Issue by chriseldredge** [cucumber/cucumber-jvm#2716]
### 👓 What did you see?

Using Cucumber JVM with my own implementation of `InjectorSource`, if my Guice modules are misconfigured and the injector fails to initialize, a runtime exception is thrown with root cause details (e.g. missing binding for a required interface).

However, when this happens, [GuiceFactory.stop()](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-guice/src/main/java/io/cucumber/guice/GuiceFactory.java#L79) gets invoked by [Runner.disposeBackendWorlds()](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/main/java/io/cucumber/core/runner/Runner.java#L156) which is in turn invoked in a `finally` block in [Runner.runPickle()](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/main/java/io/cucumber/core/runner/Runner.java#L78).

GuiceFactory.stop needs a null check to avoid NullPointerException, but the cleanup code in Runner should ideally also suppress exceptions and add them to the root cause exception (using [Throwable.addSuppressed](https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#addSuppressed%28java.lang.Throwable%29)).

### ✅ What did you expect to see?

The root cause exception

### 📦 Which tool/library version are you using?

    testImplementation("io.cucumber:cucumber-guice:7.11.2")
    testImplementation("io.cucumber:cucumber-java:7.11.2")
    testImplementation("io.cucumber:cucumber-testng:7.11.2")

### 🔬 How could we reproduce it?

1. `git clone https://github.com/chriseldredge/cucumber-guice-startup-exception-masked.git`
2. cd cucumber-guice-startup-exception-masked
3. ./gradlew build
4. View failure error in ./lib/build/reports/tests/test/index.html

**Comment by mpkorstanje** [comment]
> GuiceFactory.stop needs a null check to avoid NullPointerException

Agreed. Would you like to send a pull request for this?

> the cleanup code in Runner should ideally also suppress exceptions and add them to the root cause exception (using [Throwable.addSuppressed](https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#addSuppressed%28java.lang.Throwable%29)).

That's a bit trickier. I'll have to look for a good solution.
