### ISSUE TITLE
Is it possible to support FeatureScoped?

### ISSUE THREAD

**Issue by NorthAlan** [cucumber/cucumber-jvm#2721]
### 👓 What did you see?

I only see @ScenarioScoped. In actual usage

### ✅ What did you expect to see?

 I hope to have the functionality of @FeatureScoped level, which will be very helpful to me.

### 📦 Which tool/library version are you using?

Cucumber 7.11.2 and Cucumber-Guice 7.11.2

**Comment by mpkorstanje** [comment]
> Is it possible to support FeatureScoped?

No. Cucumber is designed with the assumption that scenarios are independent from each other.

And in principle you should design your tests to be independent from each other. This may mean logging in for each scenario. This may mean re-starting your application for each scenario. This may mean creating fresh data for each scenario.

This may seem wasteful, especially if you have written manual test scripts before, but with automation it should be fast enough that you can afford the independent test executions.
