### ISSUE TITLE
How execute the cucumber test runner file from the compiled jar project

### ISSUE THREAD

**Issue by SakthiIsaiBharathi** [cucumber/cucumber-jvm#2722]
Hi,

Is there a way available to execute the cucumber test runner file from the project which is compiled as jar ?

Could you please help.

**Comment by mpkorstanje** [comment]
You can use the `Main` method. It is documented [on the documentation website](https://cucumber.io/docs/cucumber/api/?lang=java#running-cucumber). This documentation assumes you're familiar with Java. If not, then I can't help you. 

Beware that if you're going to make a fat jar, [you'll have to do it properly](https://github.com/cucumber/cucumber-jvm/issues/2689).
