### ISSUE TITLE
how to add a time stamp to file name of the plugin file ?

### ISSUE THREAD

**Issue by SakthiIsaiBharathi** [cucumber/cucumber-jvm#2723]
Hi ,

I have custom plugin for running cucumber tests. The log file name is static.

I wanted to change the file name embedded with timestamp. How can i achieve this ? Please share your thoughts.

**Comment by jkronegg** [comment]
This doesn't look like a Cucumber issue. So you should ask your question in the Slack channel, see https://cucumber.io/docs/community/get-in-touch/

**Comment by SakthiIsaiBharathi** [comment]
I am just looking for suggestions.
