### ISSUE TITLE
Unable to generate JSON report using junit 5

### ISSUE THREAD

**Issue by bachhavdipak** [cucumber/cucumber-jvm#2732]
Hi , 

I am trying to produce json report under target folder using cucumber junit 5 but facing issue. I already define the cucumber options in junit-platform.properties, located under test resources folder. 

```
cucumber.publish.enabled=true
cucumber.plugin=pretty, html:target/cucumber-reports/Cucumber.html, json:target/cucumber-reports/Cucumber.json, junit:target/cucumber-reports/Cucumber.xml
```

I cant see target folder is any json report generated after execution.

git repo path to reproduce the issue: https://github.com/bachhavdipak/CucumberJunit5

**Comment by mpkorstanje** [comment]
The settings in `build.gradle` override the settling from `junit-platform.properties`.

https://github.com/bachhavdipak/CucumberJunit5/blob/9f5cbf7e21d81cd88c77d5ea0555bb0ed29db5ce/build.gradle.kts#L42-L52
