### ISSUE TITLE
Native support for rerun in cucumber-junit-platform-engine

### ISSUE THREAD

**Issue by tingtaox** [cucumber/cucumber-jvm#2737]
### 🤔 What's the problem you're trying to solve?
i spent some time on figuring out if ```cucumber-junit-platform-engine``` could read in and parse ```@target/rerun.txt``` file. but eventually i found out that ```cucumber-junit-platform-engine``` doesn't support it. i really like the old cucumber version which could easily set ```@target/rerun.txt``` in ```features``` field in ```@CucumberOptions```. i see an example in github readme about how to rerun failing tests. but that relies on ```junit-platform-launcher```. if i do rerun in that way, i don't know how it works with other Cucumber features like parallelism (tbh i don't know. maybe it reads cucumber config as well).

i hope that we can set ```@rerun.txt``` for features and get it run.

### ✨ What's your proposed solution?
are you able to add a special case in test discovery when features starting with "@"? a leading "@" means it's a rerun.txt file.

### ⛏ Have you considered any alternatives or workarounds?
i consider launching cucumber tests via command line. i found that command line takes ```@target/rerun.txt``` with no problem. and at the same time, i can set other cucumber configuration parameters like parallelism and plugins. if possible, hopefully you can provide an example in readme.

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by mpkorstanje** [comment]
When using JUnit 5, the JUnit Platform takes care of test discovery, selection and execution. This system assumes that test discovery is deterministic over its input and that the input doesn't change during test execution. Rerun files however are written during test execution and would then have to be executed in the same test run.

In theory rerun files could be supported by implementing a new `TestEngine` that reruns files as dynamic tests. This engine would have to be executed after the Cucumber Engine. Unfortunately JUnit 5  does not provide a way to order test engines. So a pull request for JUnit 5 would have to be created first.

Now I would welcome a pull request for a test engine that can execute rerun files. However given that both are quite a lot of work, and given that the JUnit Platform Launcher provides an API that makes it relatively easy to rerun failed tests, I doubt anyone will go through the effort.

> i see an example in github readme about how to rerun failing tests. but that relies on junit-platform-launcher. if i do rerun in that way, i don't know how it works with other Cucumber features like parallelism (tbh i don't know. maybe it reads cucumber config as well).

There are quite a few possible stacks that you can use to run your tests:

```
Cucumber CLI -> Cucumber
Maven Surefire -> JUnit 4 -> Cucumber JUnit -> Cucumber
Maven Surefire -> JUnit Platform Launcher -> JUnit Vintage Engine -> JUnit 4 -> Cucumber JUnit -> Cucumber
Maven Surefire -> JUnit Platform Launcher -> Cucumber Engine -> Cucumber
JUnit 5 Console Launcher -> JUnit Platform Launcher -> Cucumber Engine -> Cucumber
The rerun example code  -> JUnit Platform Launcher -> Cucumber Engine -> Cucumber
```

When using the CLI or Cucumber JUnit 4, [Cucumber takes properties from the CLI, the system, the environment, `@CucumberOptions` and `cucumber.properties`](https://github.com/cucumber/cucumber-jvm/tree/main/cucumber-core#properties-environment-variables-system-options).

When using the JUnit Platform [the Cucumber Engine receives its configuration from the JUnit Platform](https://github.com/cucumber/cucumber-jvm/tree/main/cucumber-junit-platform-engine#configuration-options). Effectively this comes down to Surefire/Gradle/Console Launcher config, the system and `junit-platform.properties`.

The configuration is slightly different but the capabilities are comparable.
