### ISSUE TITLE
Support for environment variables in step

### ISSUE THREAD

**Issue by darsh9292** [cucumber/cucumber-jvm#2744]
### 🤔 What's the problem you're trying to solve?
Use env variables in the step to make the cucumber step richer and more dynamic. This will be helpful for making it dynamic steps for different instances like staging, prod, dev, etc.

### ✨ What's your proposed solution?

Support expression language to use env variables. For example,
`I type password "${env.user.password}" in input type "password-field"`
Again this is a very high-level suggestion but we can figure out how we can do it better.

### ⛏ Have you considered any alternatives or workarounds?
Alternatively, we can create a custom step and do it within java, but that does not make it more dynamic.

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by mpkorstanje** [comment]
The purpose of Gherkin is to create human readable descriptions of a systems behavior. Replacement patters are not human readable. And more importantly, in this scenario the password is an incidental detail that can be omitted.

Please have a look at:

* https://cucumber.io/blog/bdd/cucumber-antipatterns-part-one/
* https://cucumber.io/blog/bdd/cucumber-anti-patterns-part-two/
* https://docs.cucumber.io/docs/bdd/better-gherkin/
* https://cucumber.io/blog/bdd/keep-your-scenarios-brief-(1)/
* https://cucumber.io/blog/bdd/introduction-to-formulation/

If you do want easy access to environment variables without using `System.getenv()` you can use a dependency injection framework that supports it. For example if you are using [`cucumber-spring`](https://github.com/cucumber/cucumber-jvm/tree/main/cucumber-spring) you can use the `@Value` annotation in your step definitions:

```java
public class ExampleStepDefinitions {

  @Value("${user.password}")
  String userPassword;

  @Given("I type password in input type {string}")
  public void enterPassword(String inputType) {
   // Enter password into inputType
  }
}
```
