### ISSUE TITLE
cucumber-jvm package not available in mvn repository

### ISSUE THREAD

**Issue by gandhi2020** [cucumber/cucumber-jvm#2753]
Hi,
The jar file of  cucumber-jvm package is not present in the different versions of Cucumber-jvm in maven central repository. also not able to find the doc for them in javadoc.io https://javadoc.io/doc/io.cucumber/cucumber-jvm/6.10.0/index.html. can you kindly advise when this issue will be fixed. 

Thank you!!

**Comment by mpkorstanje** [comment]
If you look at the packaging of the `cucumber-jvm` module you'll see that it is a POM artifact. POM artifacts do not typically include Javadoc. I suspect you'll want to look at `cucumber-java`.

https://github.com/cucumber/cucumber-jvm/blob/v6.10.0/pom.xml#L8-L10
