### ISSUE TITLE
UnsatisfiableDependenciesException with Components in Picocontainer after update to version 7.12.0

### ISSUE THREAD

**Issue by cfroh1** [cucumber/cucumber-jvm#2762]
### 👓 What did you see?

Dependencies of classes treated by Picocontainer as components (e.g. by implementing the 'Disposable' interface) cannot be resolved in version 7.12.0. Class dependency hierarchies without components in them are no problem. If the component itself has no dependencies and is only injected, it works fine as well.

### ✅ What did you expect to see?

I expect a working constructor dependency injection as in version 7.11.2, which was independent whether a class is treated as component or not.

### 📦 Which tool/library version are you using?

Cucumber JVM 7.12.0

### 🔬 How could we reproduce it?

1. Create a cucumber test dependent on class A (Constructor DI)
2. Implement the Disposable interface in class A
3. Add a dependency from class A to another class B (Constructor DI)
4. Start the test: class B is now an unsatisfied dependency of class A

### 📚 Any additional context?

Probably caused by changes from #2724

**Comment by jkronegg** [comment]
Can you provide a code sample please ?

**Comment by cfroh1** [comment]
Thanks for the fast reply.

Sure, you can find a complete minimal example here:
https://github.com/cfroh1/cucumber_UnsatisfiableDependenciesException_sample

Otherwise, the relevant classes are:

MyStepdefs.class
`public class MyStepdefs {

    private final ComponentDependency componentDependency;

    public MyStepdefs(final ComponentDependency componentDependency) {
        this.componentDependency = componentDependency;
    }

    @Given("Some step")
    public void someStep() {
    }
}`

ComponentDependency.class
`// You could also use a different pico component interface like Startable
public class ComponentDependency implements Disposable {

    private final PojoDependency pojoDependency;

    public ComponentDependency(final PojoDependency pojoDependency) {
        this.pojoDependency = pojoDependency;
    }

    @Override
    public void dispose() {

    }
}`

PojoDependency.class
`public class PojoDependency {

}`

Running with Cucumber JVM 7.12.0 this will result in the following exception:

`org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: org.example.ComponentDependency has unsatisfied dependency 'class org.example.PojoDependency' for constructor 'public org.example.ComponentDependency(org.example.PojoDependency)' from org.picocontainer.DefaultPicoContainer`

**Comment by jkronegg** [comment]
@cfroh1 this issue is solved in cucumber 7.12.1

**Comment by cfroh1** [comment]
Awesome, thanks a lot! :)
