### ISSUE TITLE
Maven `messages` library has version conflicts

### ISSUE THREAD

**Issue by jkronegg** [cucumber/cucumber-jvm#2763]
### 🤔 What's the problem you've observed?

Using Cucumber 7.12.0, with the following Cucumber dependencies :

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

In the Maven dependency graph, I see library version conflicts on the `messages`library:

- library `cucumber-core` 7.12.0 uses `messages` 22.0.0
- library `gerkin` 26.2.0 uses `messages` 19.1.4 (`gherkin` is used in `cucumber-core`)
- library `junit-xml-formatter` 0.2.0 uses `messages` 21.0.1 (`junit-xml-formatter` is used in `cucumber-core`)
- library `html-formatter` 20.3.0 uses `messages` 18.0.0 (`html-formatter` is used in `cucumber-core`)

This occurs only when Cucumber is used in a project:
![when_used_in_project](https://github.com/cucumber/cucumber-jvm/assets/2843894/9b4715e9-681a-4fd3-bee7-7ff388e1dae7)

There is no version conflict when in `cucumber-core`:
![when_in_cucumber-core](https://github.com/cucumber/cucumber-jvm/assets/2843894/1ef99f1f-b66f-4045-9ba2-308c1bbc189b)

### ✨ Do you have a proposal for making it better?

N/A

### 📚 Any additional context?

N/A

**Comment by mpkorstanje** [comment]
I see that you're not using the `cucumber-bom`.

**Comment by mpkorstanje** [comment]
I also think the software you're using to visualize the dependency tree doesn't understand ranges because:
* `gherkin` depends on `[19.1.4,23.0.0)`  
* `html-formatter` depends on `[18.0.0,23.0.0)`
* `xml-formatter` depends on `[21.0.1,23.0.0)`
* `cucumber-core` depends on `22.0.0`

So this should converge to `22.0.0` without issue.

**Comment by jkronegg** [comment]
I rewrote the dependencies to use the BOM and got no more conflicts. Thanks.

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.cucumber</groupId>
                <artifactId>cucumber-bom</artifactId>
                <version>${cucumber.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <scope>test</scope>
        </dependency>
        ...
    </dependencies>

![when_used_in_project_and_bom](https://github.com/cucumber/cucumber-jvm/assets/2843894/eab5fb2f-7e1f-4bae-af33-622dec298c4e)
