### ISSUE TITLE
Retry cucumber Java Maven

### ISSUE THREAD

**Issue by Djonathan-Kaiper-Carguero** [cucumber/cucumber-jvm#2774]
Guys, would you like to retry cucumber with the failed scenarios and when running the maven command, it runs the informed -Dtest and the rerurn at the same time?

**Comment by Djonathan-Kaiper-Carguero** [comment]
@jkronegg 
When we run cucumber vi runner scenarios it generates a cucucumber_report.json, however we have the possibility of creating another runner to run the failed tests of the first run, but it will generate a new json
cucumber_report_rerun.json.

Would the proposal be to create a combination of all JSON, taking into account the re-execution?

Any doubt I am available

**Comment by Djonathan-Kaiper-Carguero** [comment]
@jkronegg In this case, you need to run runner and then rerun in the same jenkins job and I'm having trouble getting it to run.

Thinking we have the halls.
TestRunner - With all scenarios
TestRunnerRerun- Only tests fail on first run

The command would be this, but do not run anything in the second runner even testing failed data, this in the jenkins job.

**Comment by mpkorstanje** [comment]
It sounds like you've got a problem with Jenkins. This is the issue tracker for Cucumber, we can't really with Jenkins problems.
