### ISSUE TITLE
Json Cucumber mergeFeaturesWithRetest 

### ISSUE THREAD

**Issue by Djonathan-Kaiper-Carguero** [cucumber/cucumber-jvm#2775]
In Cucumber there is a function called "mergeFeaturesWithRetest" that merges two or more Json and generates an HTML.

Would you like to know how to create a consolidated JSON?

**Comment by jkronegg** [comment]
@Djonathan-Kaiper-Carguero It looks like you would like a new functionality in Cucumber... Could you please explain with greater details what is your current issue and what should Cucumber do in the future to solve your issue ?

**Comment by Djonathan-Kaiper-Carguero** [comment]
@jkronegg
When we run cucumber vi runner scenarios it generates a cucucumber_report.json, however we have the possibility of creating another runner to run the failed tests of the first run, but it will generate a new json
cucumber_report_rerun.json.

Would the proposal be to create a combination of all JSON, taking into account the re-execution?

Any doubt I am available

**Comment by mpkorstanje** [comment]
Unfortunately it is not possible to merge reports within Cucumber. The test run and the rerun are two separate executions of Cucumber. Because there no overarching session, Cucumber lacks the awareness needed to merge the results from multiple executions (#2672 is somewhat related).
