### ISSUE TITLE
@Before is not invoked when multiple tags are passed in the runner file

### ISSUE THREAD

**Issue by Prakash-QA** [cucumber/cucumber-jvm#2776]
I'm passing multiple tags  in my runner file `tags = "@set1,@set2"`

My Runner file looks like this 

```java
package com.qa.testrunners;


import io.cucumber.junit.Cucumber;
import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(
        features = {"src/test/java/features"},
        glue = {"stepdefinitions", "com.qa.hooks"},
        monochrome = true,
        tags = "@set1,@set2",
        dryRun = false,
        plugin = {"pretty", 
                  "json:reports/cucumber/json-report.json",
                  "html:reports/cucumber/html-report.html"}
)
public class TestRunner extends AbstractTestNGCucumberTests {
}
```

I have my Hooks class like this 

```java
public class AllHooks{
 @BeforeAll
  public static void globalSetup(){
    //Setup methods
  }

  @Before
  public static void scenarioSetup(Scenario scenario){
    //Scenario setup
  }

   @AfterAll
  public static void globalTearDown(){
    //Teardown implementation
  }
}
```

My cucumber version  - 7.12.1

When I execute the runner, I get @BeforeAll methods executed and then control goes to @AfterAll method and @Before method was not executed. When I pass only one tag in the runner file then it all work fine.

**Comment by shivam-sehgal** [comment]
@Prakash-QA, tags expect a logical operator between them. For example, if you pass "@set1 or @set2", it will work as expected. The "beforeall" will be executed first, and "before" will be executed before each scenario. However, I noticed that if we use a comma (",") between two tags like you did, it doesn't give the expected error. Let's proceed with running it, and I will look into it further.

**Comment by Prakash-QA** [comment]
> @Prakash-QA, tags expect a logical operator between them. For example, if you pass "@Set1 or @SET2", it will work as expected. The "beforeall" will be executed first, and "before" will be executed before each scenario. However, I noticed that if we use a comma (",") between two tags like you did, it doesn't give the expected error. Let's proceed with running it, and I will look into it further.

Thank you @shivam-sehgal . When I use conditional operator it works.

**Comment by shivam-sehgal** [comment]
Hello, @mpkorstanje has submitted a pull request [PR](https://github.com/cucumber/tag-expressions/pull/107) to address this issue. This PR aims to prevent others from encountering the same problem. I kindly request a review of the changes to ensure their effectiveness and potential integration into the project. Your assistance and feedback would be greatly appreciated.

**Comment by Prakash-QA** [comment]
> Hello, @mpkorstanje has submitted a pull request [PR](https://github.com/cucumber/tag-expressions/pull/107) to address this issue. This PR aims to prevent others from encountering the same problem. I kindly request a review of the changes to ensure their effectiveness and potential integration into the project. Your assistance and feedback would be greatly appreciated.

Thank you for the update
