### ISSUE TITLE
Retry Option In Cucumber Java?

### ISSUE THREAD

**Issue by pabitra-qa** [cucumber/cucumber-jvm#2777]
Hi, I see in Cucumber Ruby we have the retry option for failed scenarios. In Cucumber Java do we have any such option? If not, can you share an alternative to rerun failed scenarios in Cucumber JUnit5 setup?

**Comment by mpkorstanje** [comment]
JUnit 5 does not support retrying tests. But you can use the JUnit Platform API to rerun the failed scenarios a second time. 

https://github.com/cucumber/cucumber-jvm/tree/main/cucumber-junit-platform-engine#rerunning-failed-scenarios
