### ISSUE TITLE
Minimal Ivy example

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#279]
See

http://billcomer.blogspot.co.uk/2012/03/cucumber-jvm-first-very-tentative.html
https://github.com/bill-comer/cukes-jvm-helloworld

**Comment by mpkorstanje** [comment]
I'm closing this issue. Given that nobody bothered to pick this up in the last 5 years and given that I don't believe that Ant+Ivy has any relevance I see no compelling reason to provide an example.
