### ISSUE TITLE
Cant make Cucumber recognize my steps due to an accent in a word

### ISSUE THREAD

**Issue by Francisco-Brito** [cucumber/cucumber-jvm#2834]
### 👓 What did you see?

When I write a sentence with an accent for a feature in spanish, and try to run my test, I get an error indicating the step is not defined. If I remove the accent in the feature and the step definition, it is accepted and the test run.

### ✅ What did you expect to see?

My test should run, even if my feature is in spanish and has an accent.

### 📦 Which tool/library version are you using?

Java 19
Cucumber 7.15.0
Selenium 4.16.1
VSCode using UTF-8 encoding in every file

![image](https://github.com/cucumber/common/assets/102318816/85d8cf5d-0b7f-43ba-ab4b-2c22923e18ab)
![image](https://github.com/cucumber/common/assets/102318816/f5e642cd-dd28-4565-9207-cb5cc1ffaa99)

### 📚 Any additional context?

I already tried using \00F3 Unicode to replace the "ó" and I'm certain the code works if I use a regular "o". But my client talks in Spanish and wants to read the reports in his own language, and accents are part of our grammar rules.

**Comment by mpkorstanje** [comment]
You've made a screenshot of your problem. Unfortunately, it's rather hard to copy text from a screenshot. Could you provide the text of your step definitions and feature files.

Please use [Githubs Markdown formatting](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to keep it readable.

**Comment by Francisco-Brito** [comment]
My feature file

```
# language: es
# encoding: utf8

@Test
Característica: Estado de cuenta

    Escenario: Descargar estado de cuenta
        Cuando Se navega al módulo de estado de cuenta
        Y Se selecciona el periodo actual
        Entonces Se descarga el estado de cuenta
```

My step definition

```
package steps;

import io.cucumber.java.es.*;

import pages.MenuPage;
import pages.PromotionsPage;

public class AccountStateSteps {

    @Cuando("^Se navega al módulo de estado de cuenta$")
    public void showPromotionDetails() {
        
    }

    @Y("^Se selecciona el periodo actual$")
    public void showPromotionDetails2() {
        
    }

    @Entonces("^Se descarga el estado de cuenta$")
    public void assertPromotionDetails() {

    }
}
```

**Comment by mpkorstanje** [comment]
Mmmh. I can't reproduce the problem. Executing the scenario with those step definitions and features works fine.

Could you create a reproducer using the https://github.com/cucumber/cucumber-java-skeleton as a baseline?
