### ISSUE TITLE
Feature files don't run in parallel using 'cucumber.execution.execution-mode.feature=same_thread' instead scenarios run in parallel

### ISSUE THREAD

**Issue by gorakshasabnis** [cucumber/cucumber-jvm#2841]
### 👓 What did you see?

When cucumber.execution.execution-mode.feature=same_thread seeing scenarios are running in parallel.

### ✅ What did you expect to see?

Expecting feature files to run in parallel with scenarios in 1 feature file running in a single thread.

### 📦 Which tool/library version are you using?

I am using cucumber-junit-platform-engine with version 7.15.0

### 🔬 How could we reproduce it?

junit-platform.properties file
```
cucumber.execution.parallel.enabled=true
cucumber.execution.parallel.config.strategy=fixed
cucumber.execution.execution-mode.feature=SAME_THREAD
cucumber.execution.parallel.config.fixed.parallelism=2
cucumber.execution.parallel.config.fixed.max-pool-size=2
```

1. Install '7.15.0' version of cucumber, cucumber-junit-platform-engine using the pom file
```
       <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
```
2. Add cucumber tests. 2 or more feature files having 3, 4 scenarios each

3. Add the config mentioned above to junit-platform.properties file

4. run the cucumber tests using runner file
```
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("/features")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME,
        value = "pretty," +
                "timeline:target/test-results/timeline")
public class ParallelTestSuite {
}
```

**Comment by mpkorstanje** [comment]
Based on the information provided I could not reproduce the problem. Could you please fork https://github.com/cucumber/cucumber-java-skeleton and create the reproducer in there?

**Comment by mpkorstanje** [comment]
Please feel free to reopen/recreate this issue with a usable reproducer.
