### ISSUE TITLE
Erro "Found examples when expecting one of" no 'Examples' da feature do Cucumber

### ISSUE THREAD

**Issue by Falatulima** [cucumber/cucumber-jvm#2854]
Olá, estou com problema na feature do cucumber. Estou tentando usar variáveis na minha feature e o exemplos (examples) da feature está retornando a seguinte mensagem.
![erro cucumber](https://github.com/cucumber/cucumber-jvm/assets/57711092/e36b085a-c088-4b77-a29b-447bc3f526eb)

Este é o meu arquivo .feature. 
` 

	Dado que possuo valor <username> para campo "username"
	E que possuo valor <password> para campo "password"
	Quando crio o token para autenticação "https://dummyjson.com/auth/login"
	Entao valido que o status code é 200
	E valido no body "$" que o campo "id" existe
	E valido que o valor do campo "id" é "15"
	E valido no body "$" que o campo "username" existe
	E valido que o valor do campo "username" é "kminchelle"
	E valido no body "$" que o campo "token" existe
	Exemplos:
	| username 	 | password |
	| kminchelle | 0lelplR  |
`

Apresar do erro. o teste está sendo executado normalmente. Só queria descobrir o que está causando isso e resolver o problema.

**Comment by mpkorstanje** [comment]
Olá, não falo português. Você poderia falar inglês?

It looks like your IDE is using an older version of Gherkin than your Cucumber.  In older versions of Cucumber you always have to pair "Examples" with "Scenario Outline". Newer versions of Gherkin will let you use either.

If the warning annoys you, you could maybe use Scenario Outline. The translations are "Esquema do Cenário", "Esquema do Cenario",  "Delineação do Cenário" or "Delineacao do Cenario".

For all the translations please see:

* https://github.com/cucumber/gherkin/blob/584a472b3f79d9178893911b8341d6c68f9b1e73/gherkin-languages.json#L2699

And for more about the different keywords

* https://cucumber.io/docs/gherkin/reference/

**Comment by Falatulima** [comment]
I tried with "Cenário de Fundo" and "Cenario", it didn't work, now it works with "Esquema do Cenário". Thanks for your help.

**Comment by Falatulima** [comment]
I tried with "Cenário de Fundo" and "Cenario", it didn't work, now it works with "Esquema do Cenário". Thanks for your help.
