### ISSUE TITLE
Logs reported for no matching cucumber tag found after executing test

### ISSUE THREAD

**Issue by iamsethi** [cucumber/cucumber-jvm#2892]
When running a cucumber test with existing scenario tag, using Cucumber-Junit runner file, after executing the test it displays 'cucumber.filter.tags=@11507893' did not match this scenario

Create a runner file 
`@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("features")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.project.name")
@ConfigurationParameter(key = Constants.PLUGIN_PROPERTY_NAME, value = "summary")
@ConfigurationParameter(key = Constants.EXECUTION_DRY_RUN_PROPERTY_NAME,value = "false")

public class TestRunner {

}
`

junit-platform-properties

`cucumber.publish.quiet=true
cucumber.execution.parallel.enabled=true
cucumber.filter.tags=@11507893
cucumber.plugin=pretty,json:results/cucumber.json,junit:results/cucumber.xml`

<img width="1032" alt="image" src="https://github.com/cucumber/cucumber-jvm/assets/12969857/d78fb32d-3b9d-457c-adea-0d882fb87710">

**Comment by mpkorstanje** [comment]
While Cucumber produces this information, it isn't logged by by Cucumber. Looking at your screenshot I would guess that this is done by IDEA. 

As you are running Cucumber through JUnit 5, you may want to consider using one of the many options that JUnit 5 provides instead.  For example you can use the `@IncludeTags` or `@ExcludeTags` annotation. Note that when using JUnit Tag expressions the `@` should not be included.

https://github.com/cucumber/cucumber-jvm/tree/main/cucumber-junit-platform-engine#tags
