### ISSUE TITLE
How to continue execution even after the step failed in cucumber 7.18.0

### ISSUE THREAD

**Issue by ak270296** [cucumber/cucumber-jvm#2904]
### 🤔 What's the problem you're trying to solve?

I am using cucumber 7.18.0 with selenium java here if the step fails in the test case the execution of the next steps does not continue. So I want to mark the failed step as failed and continue the execution. This logic exists in my old project where I use info.cukes dependencies.

### ✨ What's your proposed solution?

looking to mark the failed step as failed(like make the step red) and continue to execute the remaining steps of the test case

**Comment by mpkorstanje** [comment]
> This logic exists in my old project where I use info.cukes dependencies.

I don't believe that that was ever possible. Could you clarify exactly how that was done?

**Comment by ak270296** [comment]
sorry for the confusion I am using @RunWith(CustomCucumberParallelRunner.class) which extends ExtendedParallelScenarioCucumber of package com.github.mkolisnyk.cucumber.runner; maybe this allows executing the remaining steps after the step failed.

snippet inside the ExtendedParallelScenarioCucumber 
public class ExtendedParallelScenarioCucumber extends Runner {

    private Class<?> clazz;
    private CucumberOptions cucumberOptions;
    private ExtendedCucumberOptions[] extendedCucumberOptions;

    public ExtendedParallelScenarioCucumber(Class<?> testClass) {
        super();
        this.clazz = testClass;
        this.cucumberOptions = testClass.getAnnotation(CucumberOptions.class);
        this.extendedCucumberOptions = testClass.getAnnotationsByType(ExtendedCucumberOptions.class);
    }
    @Override
    public Description getDescription() {
        return Description.createTestDescription(clazz, clazz.getCanonicalName());
    }
    public static Annotation setAttrValue(
            Annotation anno, Class<? extends Annotation> type,
            String attrName, Object newValue) throws Exception {
        InvocationHandler handler = new AnnotationInvocationHandler(anno, attrName, newValue);
        Annotation proxy = (Annotation) Proxy.newProxyInstance(
                anno.getClass().getClassLoader(), new Class[]{type}, handler);
        return proxy;
    }
    @Override
    public void run(RunNotifier notifier) {
        try {
            CucumberOptions dryRunOptions = (CucumberOptions) ExtendedParallelScenarioCucumber.setAttrValue(
                    cucumberOptions, CucumberOptions.class, "dryRun", true);
            ExtendedCucumber cucumber = new ExtendedCucumber(this.clazz, dryRunOptions, extendedCucumberOptions, false);
            cucumber.run(notifier);
            String jsonFile = "";
            for (String plugin : cucumberOptions.plugin()) {
                if (plugin.startsWith("json:")) {
                    jsonFile = plugin.substring("json:".length());
                }
            }
            CucumberSplitFeature report = new CucumberSplitFeature();
            String outputFolder = new File(jsonFile).getParentFile().getAbsolutePath() + File.separator + "features";
            report.setOutputDirectory(outputFolder);
            report.setSourceFile(jsonFile);
            report.execute(true);

            CucumberOptions parallelRunOptions = (CucumberOptions) ExtendedParallelScenarioCucumber.setAttrValue(
                    cucumberOptions, CucumberOptions.class, "features", new String[] {outputFolder});
            ExtendedParallelCucumber parallelRunner
                = new ExtendedParallelCucumber(
                        clazz, parallelRunOptions, extendedCucumberOptions);
            parallelRunner.run(notifier);

            String[] paths = parallelRunner.getOutputJsonPaths(false);
            Map<String, CucumberFeatureResult> featureIdMap = new LinkedHashMap<String, CucumberFeatureResult>();
            for (String path : paths) {
                CucumberFeatureResult[] features = report.readFileContent(path, true);
                for (CucumberFeatureResult feature : features) {
                    String tag = feature.getTags()[0].getName();
                    if (featureIdMap.containsKey(tag)) {
                        CucumberFeatureResult currentResult = featureIdMap.get(tag);
                        CucumberScenarioResult[] scenarios = currentResult.getElements();
                        scenarios = (CucumberScenarioResult[]) ArrayUtils.addAll(scenarios, feature.getElements());
                        currentResult.setElements(scenarios);
                        featureIdMap.put(tag, currentResult);
                    } else {
                        featureIdMap.put(tag, feature);
                    }
                }
            }
            CucumberFeatureResult[] consolidatedFeatures
                = new CucumberFeatureResult[featureIdMap.entrySet().size()];
            int index = 0;
            for (Entry<String, CucumberFeatureResult> entry : featureIdMap.entrySet()) {
                consolidatedFeatures[index] = entry.getValue();
                index++;
            }
            for (ExtendedCucumberOptions option : this.extendedCucumberOptions) {
                ReportRunner.run(new ExtendedRuntimeOptions(option), consolidatedFeatures);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
Please correct me if I am wrong.

**Comment by mpkorstanje** [comment]
I can't really comment on that code. But if that is what you use, I suppose you could:

1. Find the source code of the `ExtendedParallelScenarioCucumber` and upgrade it to work with Cucumber v7.

2. Look into using [soft assertions](https://assertj.github.io/doc/#assertj-core-soft-assertions). These can collect multiple failing assertions across multiple steps. You can then check the assertion in an after step to make it fail. The semantics are a bit different from what you are currently using but it also ensures you only continue on assertions for which you know it is sensible to continue.
