### ISSUE TITLE
FeatureRunner.create does not behave the same in 7.0.0 as in previous versions

### ISSUE THREAD

**Issue by Mangooos** [cucumber/cucumber-jvm#2906]
### 👓 What did you see?

I am migrating from Cucumber major version 6 to major version 7.0.0 right now.
In our project we used the method FeatureRunner.create the following way:
   
```
BackendSupplier backendSupplier = () -> {
            final PluginOsgiClassFinder osgiClassFinder = new PluginOsgiClassFinder(TestingApplicationContextProvider.getBundleContext());
            return Collections.singleton(new PluginJavaBackend(osgiSpringFactory, osgiSpringFactory, osgiClassFinder));
        };

        TypeRegistryConfigurerSupplier typeRegistryConfigurerSupplier = () -> new PluginDefaultTypeRegistryConfiguration(); //used to be just a simple subclass extending TypeRegistryConfigurerSupplier with a Locale setting
        ThreadLocalRunnerSupplier runnerSupplier =
                new ThreadLocalRunnerSupplier(runtimeOptions, bus, backendSupplier, () -> osgiSpringFactory, typeRegistryConfigurerSupplier);
        Predicate<Pickle> filters = new Filters(runtimeOptions);
        this.children = features.stream()
                .map(feature -> FeatureRunner.create(feature, filters, runnerSupplier, junitOptions))
                .filter(runner -> !runner.isEmpty())
                .collect(toList());
```

When migrating to 7.0.0 i tried to adapt the changes that happened in the major update, but when now running my cucumber tests during initialization I get a NoSuchElementException.

```
 BackendSupplier backendSupplier = () -> {
            final PluginOsgiClassFinder osgiClassFinder = new PluginOsgiClassFinder(TestingApplicationContextProvider.getBundleContext());
            return Collections.singleton(new PluginJavaBackend(osgiSpringFactory, osgiSpringFactory, osgiClassFinder));
        };

        ThreadLocalRunnerSupplier runnerSupplier =
                new ThreadLocalRunnerSupplier(runtimeOptions, bus, backendSupplier, () -> osgiSpringFactory);
        CucumberExecutionContext cucumberExecutionContext = new CucumberExecutionContext(bus, new ExitStatus(runtimeOptions), runnerSupplier);
        Predicate<Pickle> filters = new Filters(runtimeOptions);
        this.children = features.stream()
                .map(feature -> FeatureRunner.create(feature, null, filters, cucumberExecutionContext, junitOptions))
                .filter(runner -> !runner.isEmpty())
                .collect(toList());
```

I am not sure how to properly migrate my code. I would appreciate some assistance.

### ✅ What did you expect to see?

Cucumber tests should start up

### 📦 Which tool/library version are you using?

cucumber-bom 7.0.0

**Comment by mpkorstanje** [comment]
It's a bit hard to say what are trying to do currently or what you're doing wrong. If anything a minimal reproducer would help, preferably in the form of a Github repository. If that is not possible, consider looking at the current implementation of the `Cucumber` class in the `cucumber-junit` module. It does look like you are using a modified version of that. Perhaps you can "reapply" the old modifications to the new class.

You should also be aware that you are currently using internal APIs. For a more maintainable solution you can use SPI to provide the `ObjectFactory` and `Backend` implementations. Though there might be limitations in Cucumber. If so, please create a feature request.

**Comment by Mangooos** [comment]
Thanks, you are right. We used a custom of the Cucumber class. Adapting our class to those changes worked!
