### ISSUE TITLE
Possibility of setting up mock data just once for all the feature files

### ISSUE THREAD

**Issue by divyapuramshetty** [cucumber/cucumber-jvm#2915]
### 🤔 What's the problem you're trying to solve?

Is it possible to setup mock data just once before all the features run ?

### ✨ What's your proposed solution?

May be a global hook that could just run once for all the features and not before every feature file.

### ⛏ Have you considered any alternatives or workarounds?

yes, leveraging Java at the moment to do this.

**Comment by mpkorstanje** [comment]
I'm going to assume that solved the problem.
