### ISSUE TITLE
New Eclipse 2024  crashes with invalid charset of cucumber-java

### ISSUE THREAD

**Issue by glauciosouthier** [cucumber/cucumber-jvm#2916]
### 👓 What did you see?

All language packs with non-ASCII chars get this error : 

Errors occurred during the build.
Errors running builder 'CDI (Contexts and Dependency Injection) Builder' on project 'MyProject'.
Malformed input or input contains unmappable characters: ~/.m2/repository/io/cucumber/cucumber-java/7.18.1/cucumber-java-7.18.1.jar/io/cucumber/java/ca/Atès$Atèss.class

### ✅ What did you expect to see?

put non-ASCII packets in separate files, with optional import

### 📦 Which tool/library version are you using?

cucumber-java-7.18.1.jar

### 🔬 How could we reproduce it?

reate new Java springboot project  on Eclipse, add this dependencies:

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>7.18.0</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>7.18.0</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>

run Maven->Update Project
the error apears!

Type CTRL+O, the error apears...

**Comment by mpkorstanje** [comment]
What is your locale set to? It sounds like Eclipse is not using UTF8.

**Comment by mpkorstanje** [comment]
Closing due to a lack of response.
