### ISSUE TITLE
naming-strategy without package name causes new Surefire (3.5.0) to fail with NPEx

### ISSUE THREAD

**Issue by pzygielo** [cucumber/cucumber-jvm#2918]
### 👓 What did you see?

On upgrading `maven-surefire-report-plugin` from 3.4.0 to 3.5.0 I observed `NPEx` in that plugin, reported first at
https://issues.apache.org/jira/browse/SUREFIRE-2257.

I believe it's because of the `classname` of `testcase` element:
```xml
  <testcase name="X Y - xx yy" classname="X Y" time="0.266">
```

Framework-generated `classname` attribute, dotless, causes `package` to be empty (then `null`) in surefire belly.

### ✅ What did you expect to see?

I expected the report for surefire to be created.

### 📦 Which tool/library version are you using?

cucumber-java:7.18.1

**Comment by mpkorstanje** [comment]
Without a minimal reproducer, I've only got a vague idea of what you're doing and I suspect the folks are Surefire are likely just as puzzled. You might want to create one using https://github.com/cucumber/cucumber-java-skeleton as a base.

That said, judging by the error message you got, this can also be reproduced with a regular JUnit Jupiter test in the default package. Those also don't include a package in their name.

I'll close this as there is nothing that can be done on the Cucumber side of things.

**Comment by pzygielo** [comment]
Thanks for checking.

> Without a minimal reproducer, I've only got a vague idea of what you're doing 

Seems it was enough.

> That said, judging by the error message you got, this can also be reproduced with a regular JUnit Jupiter test in the default package. Those also don't include a package in their name.

True. I didn't think about that.

> I'll close this as there is nothing that can be done on the Cucumber side of things.

The reported classname could be changed here to be proper class name. This currently isn't if it is with spaces.

If test IS in package, perhaps it could be reflected in classname.

**Comment by mpkorstanje** [comment]
> The reported classname could be changed here to be proper class name. This currently isn't if it is with spaces.

You are under the mistaken impression that Cucumber generates the class name. This was true for JUnit 4 but it is not the case with JUnit 5.

With the JUnit Platform, there are no reported class names. Rather there is a tree of [`TestDescriptor`](https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/TestDescriptor.html#getDisplayName()) with display names. These can be arbitrary strings.

Surefire uses the JUnit Platform, which then calls Cucumber. Cucumber provides JUnit with a tree of `TestDescriptor`s and Surefire then has to squeeze that into the their legacy report format by only looking at all leaf nodes (name) and their parents (class name). So any mistakes and assumptions are for Surefire to fix.

**Comment by pzygielo** [comment]
Appreciate additional information.

> > The reported classname could be changed here to be proper class name. This currently isn't if it is with spaces.
> 
> You are under the mistaken impression that Cucumber generates the class name. This was true for JUnit 4 but it is not the case with JUnit 5. 

Guilty.

> With JUnit 5 comes the JUnit Platform and there are no reported class names. Rather there is a tree of [`TestDescriptor`](https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/TestDescriptor.html#getDisplayName()) with display names. These can be arbitrary strings.

> Surefire uses the JUnit Platform, which then calls Cucumber. Cucumber provides JUnit with a tree of `TestDescriptor`s

https://junit.org/junit5/docs/current/api/org.junit.platform.engine/org/junit/platform/engine/TestDescriptor.html#getLegacyReportingName(): 

> *default getLegacyReportingName*
> Get the name of this descriptor in a format that is suitable for legacy reporting infrastructure — for example, for reporting systems built on the Ant-based XML reporting format for JUnit 4.
>
> The default implementation delegates to `getDisplayName()`

If there only was a way for
https://github.com/cucumber/cucumber-jvm/blob/84e13b5a6fd451b588573ee56cf92fe2a05433bd/cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/NodeDescriptor.java#L31
or https://github.com/cucumber/cucumber-jvm/blob/84e13b5a6fd451b588573ee56cf92fe2a05433bd/cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/NodeDescriptor.java#L90
to provide legacy reporting name...


This of course would not help for surefire report with any other, non-cucumber, test in default package.

Thanks for your time.

**Comment by mpkorstanje** [comment]
If only the requirements for for `getLegacyReportingName` which uses `getDisplayName` by default were not contradictory. And if only Cucumber had anything that resembled a legacy name. It seems though our feature files are a bit short on class names.  :laughing:
