### ISSUE TITLE
Make TestNGCucumberRunner More Customizable in Respect to PluginFactory and ObjectFactory

### ISSUE THREAD

**Issue by teichholz** [cucumber/cucumber-jvm#2921]
### 🤔 What's the problem you've observed?

I make heavy use of Spring Boot and for proper injection & lifecycle management of beans I need to be able to instantiate objects myself or have access have to the objects after instantiation.
This worked well enough via SPI for the ObjectFactory, albeit it would be simpler, if you could just set it (like for example TestNG does it with ITestObjectFactory). 
For PluginFactory, there is no mechanism to have access to the created plugin objects. Is there a reason to gate the plugin objects? This forces me to use static for certain things.

### ✨ Do you have a proposal for making it better?

Open up TestNGCucumberRunner a bit. Maybe add a simple Builder which allows setting CucumberPropertiesProvider, ObjectFactory and PluginFactory

**Comment by mpkorstanje** [comment]
> I make heavy use of Spring Boot and for proper injection & lifecycle management of beans I need to be able to instantiate objects myself or have access have to the objects after instantiation.

Cucumber uses Springs `TestContextManager` framework and provides the class annotated with `@CucumberContextConfiguration` as the test class to the test context manager. It works mostly like a JUnit/TestNG test class. So I would expect that the usual methods to instantiate and modify beans with Spring Test are available to you.

Something like  this (not tested):

```java
package com.example.setup.a;

@CucumberContextConfiguration
public class MyCucumberContextConfiguration {
   @Configuration
   public static class MyConfiguration {
     
      @Bean
      public MyBean customBean(){
         return ....;
      }
   }
}
```

Then in combination with a runner in the same package, looking for extra step definitions in another package:

```java
package com.example.setup.a;

@CucumberOptions(extraGlue="com.example.stepdefinitions")
public class MyRunner {
   ...
}
```

And I realize that using two classes isolated in their own package is a bit verbose, but given that this has to work with the CLI, TestNG, JUnit4, JUnit5, ect, ect we don't have too many options right now.


> For PluginFactory, there is no mechanism to have access to the created plugin objects. Is there a reason to gate the plugin objects? This forces me to use static for certain things.

The `Plugin` system is designed for reporting (and badly named). It shouldn't interact with your tests. Could you elaborate a bit more concretely on what you're trying to do with it? Perhaps we can create some proper hooks.

**Comment by teichholz** [comment]
The current issue we are facing is properly aggregating all the information we need for Reports. We mostly use appropriate Spring Scopes (we copied Cucumber Spring, but simplified it, since we didn't want to rely on Spring Test and the `TestContextManager`) to store information and later pull that information up into a spring singleton. And we end up with a bunch of spring singletons. So being able to inject them into Plugins would make life a little bit easier.

But in the end, things work the way they are currently. As said we overwrote the ObjectFactory via SPI and use the actual singleton pattern to store some Spring singletons and have access to them from plugins.

**Comment by mpkorstanje** [comment]
Ah I see.

Would something similar to the `Runtime.Builder` API be what you are looking for?

https://github.com/cucumber/cucumber-jvm/blob/84e13b5a6fd451b588573ee56cf92fe2a05433bd/cucumber-core/src/main/java/io/cucumber/core/runtime/Runtime.java#L114

**Comment by teichholz** [comment]
Yes, I was thinking about something like that for the TestNGCucumberRunner. Optimally with ways to set CucumberPropertiesProvider, ObjectFactory, PluginFactory and maybe also the FeatureSupplier.

If it does not fit the current API design, then that is ok for me. Otherwise I would offer to make a PR and come up with a concept.

**Comment by mpkorstanje** [comment]
Ideally I would like to keep the `TestNGCucumberRunner` as is. It is a simple adapter and relatively hard to misuse. But I would also like to support your use case.

And there you're looking at an unsolved problem. Your use case could be supported by the `Runtime.Builder`. But you also want to run your scenarios individually, driven by TestNG. This is currently possible but requires a large amount of setup and involves the use of APIs that were not designed to be public (effectivley copying the `TestNGCucumberRunner`).

Then there is also a good amount of duplication between the `TestNGCucumberRunner` class for TestNG, the `Cucumber` class for JUnit 4 and the `CucumberEngineExecutionContext` for JUnit 5 and the `Runtime.Builder` for the CLI. 

Ideally each as well as your own use case use the same API to setup Cucumber, then discover and run scenarios. This would be comparable to the design of [JUnit Platform Launcher API](https://junit.org/junit5/docs/current/user-guide/#launcher-api-execution) of Junit 5. And ideally supporting TestNG, JUnit 4, JUnit 5, the CLI and your use case is all done with the same API.

But this is a much bigger ask then adding a few methods.

**Comment by teichholz** [comment]
I might at some point, if I have some spare time, play around with `Runtime` and try to implement what I'm looking for. Maybe also take some inspiration from the JUnit API. At this point I would like to tackle the problem and see if I can contribute something to this project.

Until then this issue can probably be closed, thanks for all the guidance :)
