### ISSUE TITLE
rerunFailingTestsCount dosent work for the tests using ObjectFactory

### ISSUE THREAD

**Issue by cb4gith** [cucumber/cucumber-jvm#2938]
### 👓 What did you see?

**Using rerunFailingTestsCount on this test :**
@ConfigurationParameter(key = Constants.OBJECT_FACTORY_PROPERTY_NAME, value = "com.mycompany.TesObjecttFactory")
@ConfigurationParameter(key = Constants.FEATURES_PROPERTY_NAME, value = "src/test/features/some.feature")
@Suite
public class SomeTest

**causes the surefire plugin fail even though the test passes at the 4rd run:**
[WARNING] Flakes: 
[WARNING] Some Test- Examples - Example #1
[ERROR]   Run 1: error
[ERROR]   Run 2: error
[ERROR]   Run 3: error
[INFO]   Run 4: PASS
[INFO]   Run 5: PASS
[INFO]   Run 6: PASS

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.916 s - in com.mycompany.SomeTest
[INFO] 
[INFO] Results:
[INFO]
[ERROR] Errors: 
[ERROR] SomeTest.Cucumber
[ERROR]   Run 1: More than one Cucumber ObjectFactory was found on the classpath

Found: com.mycompany.OtherTestFactory, com.mycompany.ObjectTestFactory

You may have included, for instance, cucumber-spring AND cucumber-guice as part
of your dependencies. When this happens, Cucumber can't decide which to use.
In order to enjoy dependency injection features, either remove the unnecessary
dependencies from your classpath or use the `cucumber.object-factory` property
or `@CucumberOptions(objectFactory=...)` to select one.

[ERROR]   Run 2: More than one Cucumber ObjectFactory was found on the classpath

Found: com.mycompany.OtherTestFactory, com.mycompany.ObjectTestFactory

You may have included, for instance, cucumber-spring AND cucumber-guice as part
of your dependencies. When this happens, Cucumber can't decide which to use.
In order to enjoy dependency injection features, either remove the unnecessary
dependencies from your classpath or use the `cucumber.object-factory` property
or `@CucumberOptions(objectFactory=...)` to select one.

[INFO]
[ERROR] com.mycompany.SomeTest.null
[ERROR]   Run 1: SomeTest » NoTestsDiscovered Suite [com.mycompany....

### ✅ What did you expect to see?

I expect the build to pass even though there are flaky cucumber test

### 📦 Which tool/library version are you using?

cucumber-core 7.10.1
cucumber-java 7.10.1
cucumber-junit-platform-engine 7.10.1
gherkin 25.0.2
junit-jupiter 5.6.1
junit-platform-engine 1.10.2
junit-platform-suite 1.10.2
junit-platform-suite-api 1.10.2

### 🔬 How could we reproduce it?

1. create a flaky test passing at the second run
2. run with maven using surefire plugin property rerunFailingTestsCount

**Comment by mpkorstanje** [comment]
Looks like this would have already been fixed by https://github.com/junit-team/junit5/pull/3694. Make sure you have the latest versions of both Cucumber and JUnit.
