### ISSUE TITLE
RunCukesTest prevents the execution of other tests

### ISSUE THREAD

**Issue by vitormcruz** [cucumber/cucumber-jvm#304]
Tried on IntelliJ. When I have a project with both features and common unit tests, the features get executed, but the other tests don't. If I comment @RunWith(Cucumber.class) from the RunCukes, other tests run as usual.

**Comment by veenamohandas** [comment]
+1

**Comment by veenamohandas** [comment]
@RunWith(Cucumber.class)
@CucumberOptions(
features = "src/test/feature/", tags = Config.tags, plugin = { "pretty",
		"html:target/cucumber" })

  @notnow
  Scenario: To verify the Get request response time.                  [90m# RestTest.feature:24[0m
    [32mGiven [0m[32mI am calling GetUser request.[0m                               [90m# Stepdefenition.i_am_calling_GetUser_request()[0m
    [32mWhen [0m[32mI am calling request with url parameter "[0m[32m[1m1[0m[32m"[0m                  [90m# Stepdefenition.i_am_calling_GetUser_request_with_parameter(String)[0m
    [32mThen [0m[32mI fire the get request.[0m                                      [90m# Stepdefenition.i_fire_the_request()[0m
    [32mThen [0m[32mI should be able to get the response in "[0m[32m[1m3612[0m[32m" milliSeconds.[0m [90m# Stepdefenition.i_should_be_able_to_get_the_response_in_milliSeconds(String)[0m

**Comment by mathan91** [comment]
I get the following error when I run through CLI runner, 

`Main.main(new String[]{"-g", "com.sanity.step.definition","-t", "@" +getRequest[1], "C:/Users/IBM_ADMIN/Documents/Automation/Performance Testing/PerformanceTesting/MyFeature.feature"});`

I get the following ouput, 
`[32m.[0m[32m.[0m[31mF[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m[36m-[0m`
 
Also it just stops and doesn't execute the steps after that. I'm using Cucumber Core 1.1.2
