### ISSUE TITLE
Allow specification of default converters to be used in StepDefs

### ISSUE THREAD

**Issue by tknerr** [cucumber/cucumber-jvm#308]
As per cucumber-jvm 1.0.4 you can specify XStreamConverters for both arguments in data tables and regular arguments.

For data table arguments:

``` java
@Given("^I have some stuff in a data table:$")
public void I_have_some_stuff_in_a_data_table(List<Stuff> stuffs) {
     //...
}

public static class Stuff {
    @XStreamConverter(FooConverter.class)
    public Foo foo;
}
```

For regular arguments:

``` java
@Given("^I have some foo named \"([^\"]*)\"$")
public void I_have_some_foo_named(Foo foo) {
    //...
}

@XStreamConverter(FooConverter.class)
public static class Foo{
    //...
}
```

It would be great if we could specify what the default XStreamConverters for specific types are, which would have the additional benefits of:
- don't need to repeat yourself that Foo should be converter using FooConverter across multiple places
- would allow to specify converters for runtime classes which you could not annotate otherwise because they are not locally defined in your StepDefs

I could imagine something like this (outlined here: https://gist.github.com/2497953):

``` java
@StepDefOptions(
        defaultConverters = {
                @Mapping(type = Foo.class, converter = FooConverter.class),
                @Mapping(type = Bag.class, converter = BarConverter.class),
                @Mapping(type = Baz.class, converter = BazConverter.class),
        })
public class FooStepDefs {
    //...
}
```

or this (outlined here: https://gist.github.com/2488376):

``` java
@StepDefOptions(defaultConverters = MyConverters.class)
public class FooStepDefs {

    static class MyConverters extends MapBasedConverterRegistry {
        public MyConverters(Map<Class<?>, Class<? extends ConverterMatcher>> converterRegistryMap) {
            super(new ConverterMapBuilder()
                    .convert(Foo.class).with(FooConverter.class)
                    .convert(Bar.class).with(BarConverter.class)
                    .convert(Baz.class).with(BazConverter.class)
                    .build());
        }
    }

    //...
```

Not sure whether default converters should be defineable on StepDef level, Test level (e.g. in @Cucumber.Options) or even more globally. 

What do you think?

**Comment by Darkvater** [comment]
I would like to second this as well. The current approach is undesirable as everywhere the custom converted type is used will have to be annotated. You want to set this globally.

 

Take for example org.joda.DateTime. This can be marshalled currently through the DynamicClassWithStringAssignableConverter, however new DateTime("string") will lose the timezone information so you want to use DateTime.parse(). Currently there is no official way of adding converters to cucumber.

 

I have hacked deep into cucumber-jvm and made it work as follows, which is okay for now:

GroovyBackend.getInstance().glue.localizedXStreams.get(Locale.ENGLISH).registerConverter(converter)

 

Now obviously this is not ideal and I wish there was an official way of doing this. The ConverterRegistry is a good start but it needs to be exposed.

**Comment by mpkorstanje** [comment]
We are currently working towards cucumber-expressions which will satisfy this use case. Closing this issue as cucumber-expressions  will replace xstream.
