### ISSUE TITLE
1.0.9 multiple backend stuff doesn't work so well

### ISSUE THREAD

**Issue by dkowis** [cucumber/cucumber-jvm#327]
EDIT: still a problem with 1.0.9

Glue paths being passed to the cucumber-jvm CLI executable: `--glue src/test/features --glue step_definitions`

Obviously, src/test/features is a path for our ruby step definition files, and then step_definitions is a package name for our java classes that are step definitions.

```
     [java] Exception in thread "main" java.lang.IllegalArgumentException: Not a file or directory: /home/dkowis/gitwork/itsm/incident-service/step_definitions
     [java]     at cucumber.io.FileResourceIterator$FileIterator.<init>(FileResourceIterator.java:54)
     [java]     at cucumber.io.FileResourceIterator.<init>(FileResourceIterator.java:20)
     [java]     at cucumber.io.FileResourceIterable.iterator(FileResourceIterable.java:19)
     [java]     at cucumber.runtime.jruby.JRubyBackend.loadGlue(JRubyBackend.java:64)
     [java]     at cucumber.runtime.Runtime.<init>(Runtime.java:63)
     [java]     at cucumber.runtime.Runtime.<init>(Runtime.java:50)
     [java]     at cucumber.cli.Main.run(Main.java:18)
     [java]     at cucumber.cli.Main.main(Main.java:12)
```

We have a jruby backend and a spring backend.  I haven't had an opportunity to look into the code, but probably something that should be fixed in the jRuby Backend.

**Comment by lunivore** [comment]
Hi @dkowis, I'm curating old tickets. Is this still an issue for you with the latest version? If so, please point us to some working code or let us know that you're working on it still. Otherwise if I don't hear back from you, I'll close this in a week.
