### ISSUE TITLE
Improve Javadoc for @CucumberOptions

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#338]
The JavaDoc for `@CucumberOptions` should list the same info as the CLI's `--help` option.

The `--help` options are printed from [USAGE.txt](https://github.com/cucumber/cucumber-jvm/blob/v4.2.0/core/src/main/resources/cucumber/api/cli/USAGE.txt).

**Comment by mlvandijk** [comment]
When should the help options be listed when running from a runner with CucumberOptions?
It makes sense to type '--help' in the command line, where would you set/request it for CucumberOptions?

**Comment by mpkorstanje** [comment]
@mlvandijk the options should be described in the Javadoc for `@CucumberOptions` rather then the CLI. The current Javadoc is rather sparse.

https://github.com/cucumber/cucumber-jvm/blob/v4.2.0/core/src/main/java/cucumber/api/CucumberOptions.java
