### ISSUE TITLE
Slightly odd behavior in IDEA when using JUnit

### ISSUE THREAD

**Issue by dkowis** [cucumber/cucumber-jvm#341]
On this project: https://github.com/dkowis/Cucumber-JVM-Ruby-Example when one runs the junit test in IDEA, it will not register "Done" but "Terminated".

If I take off the pretty formatter from the options in the test, the problem goes away. Of course this is currently on 1.0.6, because beyond that, the jruby backend freaks out about files and directories.

It might not be an issue, but I thought I'd log it here to be sure.

It doesn't cause build failures, it is just ... strange.

**Comment by mpkorstanje** [comment]
Ran a quick test of the repository above with IDEA 2016.2. I'm not seeing anything out of the ordinary. Since this issue is about 5 years old now I assume it has been fixed so I'm closing this.
