### ISSUE TITLE
Support for delimited lists in step parameters

### ISSUE THREAD

**Issue by marquiswang** [cucumber/cucumber-jvm#364]
I have use cases for steps where I list a set of enums to pass into a step. For a simple example:

```
Given there are walls to the EAST, WEST, NORTH
And I look for directions to move
Then I can move to the SOUTH
```

I would like to be able to use a step like:

``` java
@Given("^there are walls to the ([A-Z]+(?:, [A-Z]+)*)$")
public void wallsToThe(@Delimiter(", ") Collection<Direction> dirs)
```

What I've done for now is to create a Directions class that extends ForwardingCollection and a DirectionsConverter, but it would be nice if there was native support for a Collection converter.

Basically, I'm asking if there is a better way to do something like this, and if not if such a feature would be acceptable if I submitted a pull request.

**Comment by daratha** [comment]
Hi,
Is this feature implemented now in cucumber.

**Comment by mpkorstanje** [comment]
Yes. https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/api/Delimiter.java
