### ISSUE TITLE
gherkin:JSONFormatter assigns results to wrong step in coordiation with StepContainer

### ISSUE THREAD

**Issue by matthewpietal** [cucumber/cucumber-jvm#381]
StepContainer loops over all steps and calls step on the formatter prior to any step executing:

``` java
    void format(Formatter formatter) {
        statement.replay(formatter);
        for (Step step : getSteps()) {
            formatter.step(step);
        }
    }
```

When the JSONFormatter is set, the local currentStepOrHook variable gets set to the very last step:

``` java
    public void step(Step step) {
        currentStepOrHook = step.toMap();
        getSteps().add(currentStepOrHook);
    }
```

When each step finally runs, the result method is eventually invoked on the JSONFormatter:

``` java
    public void result(Result result) {
        currentStepOrHook.put("result", result.toMap());
    }
```

The means that the results for all steps gets put on the last currentStepOrHook rather than on the step the result belonged to.

Tested with cucumber-jvm 1.0.14

**Comment by brasmusson** [comment]
The previous comment indicate that this is fixed in v1.1.5. Besides now the JSON Formatter used the new event based formatter API, so any issue related to `StepContainer` is gone for sure. Closing.
