### ISSUE TITLE
Duplicate step definitions

### ISSUE THREAD

**Issue by carlparziale** [cucumber/cucumber-jvm#397]
When two Features have the same WHEN or THEN annotations, Cucumber JVM is finding collisions in the mappings.  Assume it has to do with how Cucumber/Regex resolves to the correct methods to execute.    

Since the Features were seperate files, and the Glue code where seperate Classes, was assuming this wouldn't conflict.

Any way to solve this, besides changing the feature files.

Error that is thrown:

Duplicate step definitions in cucumber.examples.java.helloworld.DummyName.I_ask_it_to_say_hi() in file:/C:/Users/nbk3wqf/workspaceJuno/java-helloworld/target/test-classes/ and cucumber.examples.java.helloworld.HelloCarlTestSteps.I_ask_it_to_say_hi() in file:/C:/Users/nbk3wqf/workspaceJuno/java-helloworld/target/test-classes/

Two separate Feature files:

Feature: Hello Carl
  Scenario: Say hello Carl
    Given I have a hello carlApp 
    When I ask it to say hi
    Then it should answer with "Howdy World"

Feature: Hello World
  Scenario: Say hello
    Given I have a hello app with "Howdy"
    When I ask it to say hi
    Then it should answer with "Howdy World"

**Comment by chrisdostert** [comment]
Very old thread, but did anything ever come of this? This is a fantastic enhancement. I prefer single purpose built FeatureStepDefs class for each feature that knows no more and no less than is needed to test the specific feature under test. If I need access to shared helpers I can simply use DI. The only way i've found to do this with current cucumber-jvm implementation is to use a package per feature and then explicitly supply that via ```@CucumberOptions(features = {"my.feature"},glue = {"mypackage"})```

**Comment by dkowis** [comment]
Take discussion up on the mailing list please.
