### ISSUE TITLE
stepdefs.json missing source

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#417]
Someone got this:

``` json
{
  "source": "I add to the table \"(.*)\" the values",
  "flags": "",
  "steps": []
}
```

The `file_colon_line` value seems to be missing. It could be that some backends don't fill in the value properly. In any case it should always be there and have a default "unknown" value if it can't be determined.

**Comment by mpkorstanje** [comment]
We have since upgraded to the latest Gherkin and changed several things about the way the uri is created and handled. I doubt it will be possible to recreate this issue.
