### ISSUE TITLE
Test count zero when building with Gradle

### ISSUE THREAD

**Issue by spacejens** [cucumber/cucumber-jvm#421]
When running tests with Gradle using the default output formatting, the number of tests is incorrectly reported as zero in the generated report, and no tests are listed.

I have reproduced this problem in /examples/java-helloworld by performing the following steps:
- Comment out the Cucumber.Options annotation in RunCukesTest
- Creating a minimal build.gradle file (attached) with the required dependencies
- Running "gradle test"

The generated build/reports/tests/index.html contains the error.

```
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    testCompile ( group: 'info.cukes', name: 'cucumber-picocontainer', version: '1.1.1') {
        transitive = false
    }
    testCompile ( group: 'info.cukes', name: 'cucumber-junit', version: '1.1.1') {
        transitive = false
    }
    testCompile ( group: 'com.rubiconproject.oss', name: 'jchronic', version: '0.2.6') {
        transitive = false
    }
    testCompile ( group: 'junit', name: 'junit', version: '4.10') {
        transitive = false
    }
}
```

**Comment by lunivore** [comment]
Closing this ticket as I am also running Cucumber-JVM tests through Gradle, so can confirm it still works 4 years later.
