### ISSUE TITLE
nested properties in datatables

### ISSUE THREAD

**Issue by floriankammermann** [cucumber/cucumber-jvm#442]
It would be nice when it would be possible to declare nested properties as field in data tables.

e.g. we have a datatable like this

type: customer

``` gherkin
| name | age | address.street | address.houseno |
| john | 40  | pinestreet     | 12              |
```

**Comment by nikolaikopernik** [comment]
@mgurov but in the end, I'd like to reuse my domain classes and do not introduce another mapping layer. 
less code, less mapping, fewer errors
