### ISSUE TITLE
Scala tests should be able to be run without mutable state

### ISSUE THREAD

**Issue by noelmarkham** [cucumber/cucumber-jvm#451]
Following on from my [question](http://stackoverflow.com/questions/14405345/is-it-possible-to-avoid-mutable-state-using-cucumber-jvm-scala) on StackOverflow, I don't believe it's possible to run Cucumber-jvm for Scala without using mutable state.

I'd like to propose an enhancement to allow this:
- Have the `Given` methods return a context containing any state to be stored.
- This context is then passed as a parameter to any `When` methods.
- These `When` methods return a new copy of any context.
- The `Then` methods are passed the context in order to do any assertions.

So it could look something like this:
For a feature:

```
Given the digit 2
When it is multiplied by 3
Then the result is 6
```

And the resulting steps could look something like:

``` Scala
class CucumberRunner extends ScalaDsl with EN with ShouldMatchers {

  Given("""^the digit (\d)$""") { digit: Int =>
    TestContext("digitUnderTest" -> digit)
  }

  When("""^it is multiplied by 3$""") { testContext: TestContext =>
    val multiplied = testContext("digitUnderTest") * 3
    TestContext("multipliedDigit" -> multiplied)
  }

  Then("""^the result is (\d)$""") { (result: Int, testContext: TestContext) =>
    val calculatedResult = testContext("multipliedDigit")
    calculatedResult should equal (result)
  }
}
```

In my mind, this leads to clearer tests and fewer issues arising from multiple tests accessing the same mutable variables.

Any thoughts?

**Comment by mpkorstanje** [comment]
I'm closing this issue as the discussion is about 4 years old now. There is however a more recent discussion.

https://github.com/cucumber/cucumber/issues/214
