### ISSUE TITLE
cucumber-scala does not support DI libraries.

### ISSUE THREAD

**Issue by tobyclemson** [cucumber/cucumber-jvm#469]
The ScalaBackend from cucumber-scala currently instantiates all step classes directly rather than using the ObjectFactory approach that the JavaBackend uses. 

Is there any possibility of introducing such support into the ScalaBackend? Alternatively, could the logic in the JavaBackend be extracted into some common library and reused?

Thanks,
Toby

**Comment by dkowis** [comment]
To revive dead threads, in the project I work on, we're using spring annotations to inject dependencies into scala classes. It does indeed just work.

**Comment by dkowis** [comment]
Also, I have no idea how I "unassigned" someone .... all I did was comment :|

**Comment by austek-mdsol** [comment]
DI seems to be the only way to share state between steps, so cucumber-scala should support DI frameworks
