### ISSUE TITLE
Example how to use date transformation from Groovy

### ISSUE THREAD

**Issue by pranasblk** [cucumber/cucumber-jvm#470]
The syntax for Java transformation is described:
http://cukes.info/step-definitions.html#transform-java

How it would look on Groovy script? Extension of examples and/or wiki would be valuable.

Thank you
Peter

**Comment by aslakhellesoy** [comment]
FWIW - the example code shows how to do this: 
https://github.com/cucumber/cucumber-jvm/blob/master/groovy/src/test/groovy/cucumber/runtime/groovy/date_stepdefs.groovy
