### ISSUE TITLE
Error or warn on more than one JUnit runner

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#472]
See [message](https://groups.google.com/forum/#!searchin/cukes/Senthil/cukes/uWlVKi6EGGs/PABJSKq837oJ) from Senthil on the list today

**Comment by mlvandijk** [comment]
*Steps to reproduce:*
1. Have multiple Runners
2. Specify the _exact same_ target filename for the report in both runners
3. End result will be only one file with the specified name
Note: Having multiple runners with different filenames for the reports will not reproduce this issue.

*Possible solution:*
Title of the issue proposes to give a warning when running multiple runners. However, there may be various reasons to run multiple runners (for instance with https://github.com/temyers/cucumber-jvm-parallel-plugin). As long as they specify different filenames, this is fine.
