### ISSUE TITLE
cannot run tests by path of .feature-file

### ISSUE THREAD

**Issue by ghost** [cucumber/cucumber-jvm#473]
When I try to start some test by using .feature path like this:
mvn test -Dcucumber.options="src/test/resources/package/Some.feature"
cucumber-jvm starts all tests i have (all .feature-files). could it be a bug?
i'm using version 1.1.2
thx

**Comment by brasmusson** [comment]
This works in both v1.2.5 and v2.0.0-SNAPSHOT (with of without line filters on the feature path).
