### ISSUE TITLE
No documentation for World hook

### ISSUE THREAD

**Issue by quantoid** [cucumber/cucumber-jvm#481]
I cannot find anywhere that explains how the World hook in Groovy should be used. The calculator example in Groovy uses it in a strange way that looks like dummy code, and there are no explanatory comments. The API documentation has no extra information.

It's really hard to find a decent tutorial for using Groovy with Cucumber-JVM so the documentation here on github is pretty much all I've got to go on.

**Comment by lunivore** [comment]
Hi @quantoid , sorry nobody got back to you on this! [We now have World documentation here.](https://github.com/cucumber/cucumber/wiki/A-Whole-New-World) I hope that you're enjoying your work with Cucumber, and wish you luck with your projects.

**Comment by lunivore** [comment]
@quantoid Sorry, that was a little quick off the mark - that documentation is for Cucumber-JVM rather than Cucumber, so AFAIK we still need this. Please let us know if it's still important to you though as we'll be able to prioritise it better.
