### ISSUE TITLE
Gherking Substeps  support feature

### ISSUE THREAD

**Issue by pranasblk** [cucumber/cucumber-jvm#483]
I and my colegues were reading http://www.technophobia.com/blog/read/experiences-with-bdd-and-cucumber-part-ii-substeps-439

Could you please consider adding support for Cucumber-JVM Groovy?

**Comment by Virgomax** [comment]
In case you are using Javascript, I've created a package named [reuse-cucumber-scenarios](https://www.npmjs.com/package/reuse-cucumber-scenarios) for calling a scenario by doing:

```gherkin
Given the scenario "scenario_tag"
```
```gherkin
Given the scenario "scenario_tag" with parameters
"""
{
  "1": ["step1_param1", "step1_param2"],
  "2": ["step2_param1", "step2_param2", "step2_param3"],
  "3": ["step3_param1", "step3_param2", "step3_param3"],
}
"""
```

```gherkin
Given the variable "$variable_name" is equal to
"""
#JSON object
"""
```
```gherkin
Given the scenario "@$scenario_function_tag" where variable "$variable_name" is "value_to_replace"
```

and more...
