### ISSUE TITLE
Allow Scenario reuse

### ISSUE THREAD

**Issue by zambrovski** [cucumber/cucumber-jvm#502]
I would like to reuse step definitions grouped to a scenario. This is particularly useful, if TDD strategy is used for incremental tests development along a happy path. In doing so, the scenarios follow the pattern below:

```
Feature HappyPath
Scenario X
  Given A
  When B
  Then C

Scenaro X+1
  Given A
    And B
  When C
  Then D

Scenaro X+2
  Given A
    And B
    And C
  When D
  Then E
```

and so on. I would like to reuse the information already stated in the previous scenario. In order to do so, we can rewrite the previous feature HappyPath in the following way:

```
Feature HappyPath
Scenario X
  Given A
  When B
  Then C

Scenario X+1
  Given "Scenario X"
  When "Scenario X" 
    And C
  Then D

Scenario X+2
  Given "Scenario X+1"
  When "Scenario X+1"
    And D 
  Then E
```

The meaning of _Given "Scenario X"_ is to execute all steps from Scenario X annotated with _Given_, _When "Scenario X"_ will execute all _When_ steps from the Scenario X and _Then "Scenario X"_ is responsible for running all _Then_ steps from the scenario. 

This addition will allow getting a much higher reuse of Gherkin definitions and steps from the glue classes. In particular, fosters the reuse of parameters used in steps and reduces duplication.

**Comment by Virgomax** [comment]
In case you are using Javascript, I've created a package named [reuse-cucumber-scenarios](https://www.npmjs.com/package/reuse-cucumber-scenarios) for calling a scenario by doing:

`Given the scenario "scenario_tag"`

and:
```gherkin
    Given the scenario "scenario_tag" with parameters
    """
    {
      "1": ["step1_param1", "step1_param2"],
      "2": ["step2_param1", "step2_param2", "step2_param3"],
      "3": ["step3_param1", "step3_param2", "step3_param3"],
    }
    """
```
