### ISSUE TITLE
Dependency on testNG causes Surefire to ignore JUnit wrapper class

### ISSUE THREAD

**Issue by quantoid** [cucumber/cucumber-jvm#513]
My POM has a dependency on a project that depends on testNG. When I run the test phase the Surefire plugin detects testNG and uses that instead of JUnit, and then fails to recognise and execute the JUnit wrapper that runs the Cucumber tests:

``` groovy
@RunWith(Cucumber.class)
@Cucumber.Options(features={"src/test/features"},
                  glue={"src/test/groovy/com/example/mytesting/glue"},
                  format={"html:target/cucumber",
                          "json:target/cucumber.json"})
public class TestFeatures
{
}
```

```
> mvn -Dtest=TestFeatures test
[INFO] Scanning for projects...
:::

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.example.mytesting.TestFeatures
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@4c397cea
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.52 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

I added this to the dependency that depends on testNG:

``` xml
<exclusions>
    <exclusion>
        <!-- exclude testNG otherwise Maven doesn't run TestFeatures -->
        <groupId>org.testng</groupId>
        <artifactId>testng</artifactId>
    </exclusion>
</exclusions>
```

Now it uses JUnit 4 and executes TestFeatures normally.

**Comment by rpsathish3** [comment]
This worked for me ---

<plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-surefire-plugin</artifactId>
       <version>2.19.1</version>
       <dependencies>
      <dependency>
        <groupId>org.apache.maven.surefire</groupId>
        <artifactId>surefire-junit47</artifactId>
        <version>2.19.1</version>
      </dependency>
    </dependencies>
  </plugin>
