### ISSUE TITLE
Screenshots in android example

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#548]
This is an extension of #547.

We should have an after hook that calls `scenario.embed` to embed a screenshot. The current android formatter just ignores them, but it should be improved so that the screenshots can be accessed on the local filesystem after the run.

Alternatively they could use HTTP to post them somewhere.

**Comment by SierraGolf** [comment]
@aslakhellesoy is this just a request to extend the examples or is this about adding functionality to capture screenshots from within cucumber android?

**Comment by aslakhellesoy** [comment]
It's both :-). Would be nice to run the android example and see a report with a screenshot of the UI.

**Comment by SierraGolf** [comment]
I just discovered the "scenario parameter in hooks"-feature and the ```Scenario.embed(byte[], Sring)``` interface. So now I get what you mean by embedding a screenshot. :D

I am unsure if it makes sense to embed such a functionality into cucumber-android, but I will at least provide an example.
