### ISSUE TITLE
maven surefire test results are wrong (cucumber-java)

### ISSUE THREAD

**Issue by BertRobbenSony** [cucumber/cucumber-jvm#577]
When running cukes using surefire, an xml file is generated with the results of the run. This xml file is wrong because:
- Each step is considered a testcase. A scenario corresponds to a test class. This is confusing, certainly in situations with many features.
- When using scenario outlines, the example line itself is also considered to be a testcase.
- When using scenario outlines, the example is used as classname. This results in unusable output.

You can easily see this by running "mvn clean install" on the cucumber-jvm/examples/java-helloworld sample, and then looking at target/surefire-reports/TEST-cucumber.examples.java.helloword.RunCukesTest.xml.

To also see the output for scenario outlines, change the first scenario in helloworld.feature into

Scenario Outline: Say hello
    Given I have a hello app with "<msg>"
    When I ask it to say hi
    Then it should answer with "<msg> World"

```
Examples:
| msg |
| one |
| two |
| three |
```

Then the xml output would be

``` xml
 <testcase name="Given I have a hello app with &quot;one&quot;" classname="| one |" time="0.001"/>
  <testcase name="When I ask it to say hi" classname="| one |" time="0"/>
  <testcase name="Then it should answer with &quot;one World&quot;" classname="| one |" time="0"/>
  <testcase name="| one |" classname="| one |" time="0.001"/>
  <testcase name="Given I have a hello app with &quot;two&quot;" classname="| two |" time="0"/>
  <testcase name="When I ask it to say hi" classname="| two |" time="0"/>
  <testcase name="Then it should answer with &quot;two World&quot;" classname="| two |" time="0"/>
  <testcase name="| two |" classname="| two |" time="0.002"/>
  <testcase name="Given I have a hello app with &quot;three&quot;" classname="| three |" time="0"/>
  <testcase name="When I ask it to say hi" classname="| three |" time="0"/>
  <testcase name="Then it should answer with &quot;three World&quot;" classname="| three |" time="0"/>
  <testcase name="| three |" classname="| three |" time="0"/>
  <testcase name="Given a shopping list:" classname="Scenario: Print my shopping list" time="0"/>
  <testcase name="When I print that list" classname="Scenario: Print my shopping list" time="0.006"/>
  <testcase name="Then it should look like:" classname="Scenario: Print my shopping list" time="0.001"/>
  <testcase name="Scenario: Print my shopping list" classname="Scenario: Print my shopping list" time="0.002"/>
  <testcase name="Given today is &quot;Dec 6, 2012&quot;" classname="Scenario: Transformation" time="0"/>
  <testcase name="And I did laundry 2 days ago" classname="Scenario: Transformation" time="0"/>
  <testcase name="Then my laundry day must have been &quot;Dec 4, 2012&quot;" classname="Scenario: Transformation" time="0"/>
  <testcase name="Scenario: Transformation" classname="Scenario: Transformation" time="0.001"/>
```

For me, this makes cucumber-jvm almost unusable.

What is strange, is that the junit output generated by using the junit output format as in @Cucumber.Options(format = {"html:target/cucumber-html-report", "json:target/cucumber-json-report.json", "junit:target/surefire-reports/cucumber-junit.xml"}), is ok.

Bert

**Comment by ArthurBilyk** [comment]
Hi all,
Is the problem solved in some way?
Maven surefire shows test runs number as sum of steps and scenarios in cucumber.

**Comment by mpkorstanje** [comment]
With #1135 it will look like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite ...
           name="com.github.mpkorstanje.cucumber.SomeIT" time="1.028" tests="4" errors="0"
           skipped="0" failures="1">
    <properties>
        ....
    </properties>
    <testcase name="Fail when running" classname="Fail when running" time="0.479">
        <failure message="failure" type="java.lang.AssertionError">java.lang.AssertionError: failure</failure>
    </testcase>
    <testcase name="Say hello" classname="Say hello" time="0.007"/>
    <testcase name="Say hello" classname="Say hello" time="0.007"/>
    <testcase name="Say hello" classname="Say hello" time="0.007"/>
</testsuite>
```

It doesn't distinguish between different examples but it is a lot more readable. I think this is the limit of integration between cucumber and surefire .If anybody else has more suggestions for improvement I think a new ticket would be the way to go.
