### ISSUE TITLE
IllegalStateException: No Scope registered for scope 'cucumber-glue'  

### ISSUE THREAD

**Issue by cpkelley** [cucumber/cucumber-jvm#600]
After Cucumber JVM v1.1.4, when using @Scope('cucumber-glue') or in the cucumber.xml context file <bean .... scope="cucumber-glue" /> , spring throws the following exception:

Caused by: java.lang.IllegalStateException: No Scope registered for scope 'cucumber-glue'

See failing example here: https://github.com/cpkelley/cuke-demo-spring/ 

This works fine when reverting back to v1.1.2. It's possible that I'm just not using the new cucumber spring properly. I tried following the steps specified in the Cucumber Recipes book.

**Comment by whittle** [comment]
I am encountering this error with v1.2.4. I have a class co.masslab.shiba.CucumberTests annotated with: 

```java
@RunWith(Cucumber.class)
@CucumberOptions(features="src/test/resources",
                 glue={"co.masslab.shiba", "cucumber.api.spring"})
@Configuration
```

A step definition class in the same package annotated with: 

```java
@ContextConfiguration(classes={ShibaApplication.class, TestDoubleConfig.class, DataSourceConfig.class},
                      loader=SpringApplicationContextLoader.class)
@IntegrationTest
@WebAppConfiguration
```

And a DataSourceConfig class, also in the same package, that looks like this: 

```java
@Configuration
public class DataSourceConfig {

    @Scope("cucumber-glue")
    @Bean
    public DataSource datasource() {
        return new EmbeddedDatabaseBuilder()
            .setType(EmbeddedDatabaseType.H2)
            .build();
    }
```

The innermost error in the stack trace is `java.lang.IllegalStateException: No Scope registered for scope name 'cucumber-glue'`. 

In light of this, I am asking that this ticket be reopened.

**Comment by whittle** [comment]
Sorry, just now saw #965 which I assume covers this issue.
