### ISSUE TITLE
Support step hooks

### ISSUE THREAD

**Issue by ShijunK** [cucumber/cucumber-jvm#604]
Feature: https://github.com/cucumber/cucumber/wiki/Hooks

I am surprised that cucumber-jvm does not support step hooks. For example, when I use cucumber-jvm to build web application acceptance tests, I'd like to take screenshot after each step. Without step hooks, I have to invoke the method in every single step. painful. 

Any reason don't include this feature?

**Comment by Evg3n** [comment]
Hello,

I need steps hooks too. So, I forked the repo and will work on java implementation. I doesn't look too hard to add but will see. I just started digging in the code but let me know if you have any cons.

Best regards,
Eugene.

**Comment by aslakhellesoy** [comment]
Go ahead!

**Comment by Evg3n** [comment]
Pull request #838.

Best regards,
Eugene.

**Comment by Evg3n** [comment]
Hey @aslakhellesoy could you please provide timeline when pull request #838  will be merged and released? I really need in my project.

Best regards,
Eugene.

**Comment by aslakhellesoy** [comment]
Hi @Evg3n I don't commit to timelines. I try to work on Open Source on Fridays - that's all I can say.

**Comment by IntelloScooby** [comment]
I am working on a mobile automation framework and use external reporting API. With this API, I would like to log a PASS, FAIL or INFO status after each step along with the step/step definition name. Right now, I have to add this line of code at the end of each step definition for logging in the external report. This is not a good practice and once our framework and team starts growing, it will be difficult to maintain. I am waiting eagerly for an afterstep hook in cucumber-jvm and a method similar to Scenario.getName (something like Step.getName) to handle this issue.

**Comment by IntelloScooby** [comment]
Is there any plan for adding step hooks any time soon? I see this conversation was started in 2013 and there also seems to be code already written for this change.

**Comment by brasmusson** [comment]
@IntelloScooby Speaking for me personally, I'm focusing the time I have available to work on upgrading Cucumber-JVM to use Gherkin v4.0.0. From that perspective I would not want to add step hooks before there is an Cucumber-JVM v2.0.0-SNAPSHOT available that uses Gherkin v4.0.0.

**Comment by npsullia** [comment]
I would like to add reasons supporting need for step level screenshots. For Pharmaceutical industry the evidence needs to be captured for every single step if it is part of validation checkpoint. This is part of CFR-11 requirement. We are trying to save manual testing effort for auditory and compliance  requirements by using automation reports.

**Comment by Saieph** [comment]
What @npsullia said is absolutely correct an is EXACTLY what I'm trying to do right now, which lead me to this post.

**Comment by SanjeevKumarmn** [comment]
do we have after step or still under consideration ?

**Comment by mpkorstanje** [comment]
There currently is no after-step hook but I don't believe the the concept it self has any opposition. There is however no usable pull request. An attempt was made with #938 but this was done against an older version of Gherkin and is not usable.

Keep in mind that Cucumber is mostly developed by its community.  If you want something the best way to do so is to implement this functionality and send a PR. If you are unable to do this you'll have to find someone to do this for you.

**Comment by eskignax** [comment]
After-step hook will be really useful with allure-report.

**Comment by Lupeipei** [comment]
@ShijunK I am sure you must have solved the problem of getting screenshot after each step. I would like to get screenshot after each step and use each step's description to generate a hash string, the problem I have now is I have no idea  how to get a step's description. I have googled but haven't got any effective answers, do you have any suggestion? I am using ruby2.4, Thanks in advance.

**Comment by bouillonpi** [comment]
Step hooks are not implemented in cucumber 5.0.2 (latest version at this time).
I need it to take screenshots after each failed step.
So far the only solution I found to achieve this is to include the screenshot function in each step which is painful.
Any news about step hooks or workaround? Thanks!
