### ISSUE TITLE
Android: Cucumber doesn't load step definitions when runing tests by gradle 

### ISSUE THREAD

**Issue by polok** [cucumber/cucumber-jvm#615]
First of all, good work ! 
About the problem: I am struggling few days to run cucumber tests from Android Studio using gradle. I am quite far with this (I hope so) but seems that my step definitions are ignored. The class annotated with CucumberOptions is loaded but something wrong is with my step definition/configuration. Below you can see that my features file is loaded correctly, the class which contains step definitions also, but unfortunately gradle says that I don't have step definitions. 

Debug output:
10-22 08:43:36.009  10529-10529/? D/cucumber-android﹕ Found CucumberOptions in class com.exmaple.test.MainActivitySteps
    Calculate the sum of two numbers which consist of one or more digits
10-22 08:43:36.141  10529-10542/? D/cucumber-android﹕ Scenario Outline: Enter one digit per number and press =
10-22 08:43:36.141  10529-10542/? D/cucumber-android﹕ Given I have a CalculatorActivity
10-22 08:43:36.141  10529-10542/? D/cucumber-android﹕ When I press <num1>
10-22 08:43:36.141  10529-10542/? D/cucumber-android﹕ And I press +
10-22 08:43:36.141  10529-10542/? D/cucumber-android﹕ And I press <num2>
10-22 08:43:36.141  10529-10542/? D/cucumber-android﹕ And I press =
10-22 08:43:36.141  10529-10542/? D/cucumber-android﹕ Then I should see <sum> on the display
10-22 08:43:36.141  10529-10542/? D/cucumber-android﹕ Examples:
10-22 08:43:36.145  10529-10542/? D/cucumber-android﹕ Scenario Outline: Enter one digit per number and press =
10-22 08:43:36.145  10529-10542/? D/cucumber-android﹕ Given I have a CalculatorActivity
10-22 08:43:36.145  10529-10542/? D/cucumber-android﹕ When I press 0
10-22 08:43:36.145  10529-10542/? D/cucumber-android﹕ And I press +
10-22 08:43:36.145  10529-10542/? D/cucumber-android﹕ And I press 0
10-22 08:43:36.145  10529-10542/? D/cucumber-android﹕ And I press =
10-22 08:43:36.145  10529-10542/? D/cucumber-android﹕ Then I should see 0.0 on the display
10-22 08:43:36.145  10529-10542/? D/cucumber-android﹕ Scenario Outline: Enter one digit per number and press =
10-22 08:43:36.145  10529-10542/? D/cucumber-android﹕ Given I have a CalculatorActivity

10-22 08:43:36.169  10529-10542/? W/cucumber-android﹕ @Given("^I have a CalculatorActivity$")
    public void I_have_a_CalculatorActivity() throws Throwable {
    // Express the Regexp above with the code you wish you had
    throw new PendingException();
    }
10-22 08:43:36.169  10529-10542/? W/cucumber-android﹕ @When("^I press (\d+)$")
    public void I_press(int arg1) throws Throwable {
    // Express the Regexp above with the code you wish you had
    throw new PendingException();
    }
10-22 08:43:36.169  10529-10542/? W/cucumber-android﹕ @When("^I press +$")
    public void I_press_() throws Throwable {
    // Express the Regexp above with the code you wish you had
    throw new PendingException();
    }
10-22 08:43:36.169  10529-10542/? W/cucumber-android﹕ @When("^I press =$")
    public void I_press_() throws Throwable {
    // Express the Regexp above with the code you wish you had
    throw new PendingException();
    }
10-22 08:43:36.169  10529-10542/? W/cucumber-android﹕ @Then("^I should see (\d+).(\d+) on the display$")
    public void I_should_see_on_the_display(int arg1, int arg2) throws Throwable {
    // Express the Regexp above with the code you wish you had
    throw new PendingException();
    }

My build.gradle is as follow:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.6.+'
    }
}
apply plugin: 'android'
apply plugin: 'idea'

repositories {
    mavenCentral()
}

android {
    compileSdkVersion 18
    buildToolsVersion "18.1.0"

    defaultConfig {
        minSdkVersion 8
        targetSdkVersion 18
        testPackageName "com.exmaple.test"
        testInstrumentationRunner "cucumber.api.android.CucumberInstrumentation"
    }
}

dependencies {
    compile 'com.android.support:appcompat-v7:+'
    compile 'info.cukes:cucumber-java:1.1.5'
    compile project(':project_libs:cucumber-android')
}
```

Cucumber-android's project contains sources from cucumber-jvm so they are up-to date.

Please, if any one one can help me with this. I can put somewhere the whole projects if this help.

**Comment by ari-fikri** [comment]
in my case, I need to put the step definition files in the same package as the java application package, then it will be read, otherwise anything didn't work, even using --glue didn't have any effect.
Still finding way to do it, properly.

Did you solve this problem @polok

**Comment by polok** [comment]
@ari-fikri Hey, no I didn't ;/. Btw. thanks for sharing your solution

**Comment by lunivore** [comment]
Hi @polok, really sorry that nobody was able to help you solve this. I'm just curating old tickets at the moment, since the codebase has moved on significantly. Is this still a problem for you? If so, please let us know. Otherwise, if I don't hear back from you in a week, I will close this ticket.

**Comment by christopherperry** [comment]
I am currently having this issue.

**Comment by aslakhellesoy** [comment]
@christopherperry please open a new ticket in https://github.com/cucumber/cucumber-android/
