### ISSUE TITLE
JSON output file - missing IDs - ok or not?

### ISSUE THREAD

**Issue by TrueDub** [cucumber/cucumber-jvm#646]
Hi,

I maintain a Jenkins plugin for providing performance data on cucumber test runs (https://github.com/TrueDub/cucumber-performance)

An issue has been raised where the plugin fails, because the JSON file generated has no scenario IDs for some scenarios.

I'm not sure about how to solve this: can I simply state that all features, scenarios and steps must have IDs, or should my code cope with the fact that they may not?

If they must have IDs, is there a specific format the feature file needs to be in to ensure generation of an ID in the JSON output?

I asked this over on the Cukes Google group but got no response.

Thanks in advance for any help

TrueDub

**Comment by mpkorstanje** [comment]
Looking quickly at the code it should not be possible. This may be a bug.

I am closing this issue due to age. If this remains a problem feel free to open it.
