### ISSUE TITLE
Android apklib & gradle incompatability

### ISSUE THREAD

**Issue by MariusVolkhart** [cucumber/cucumber-jvm#647]
cucumber-android current publishes a jar and an `apklib` using the android-maven-plugin.

The new android build system relies on gradle and a specific library format known as `aar`. The apklib format is incompatible with this system and breaks the builds.

A gradle build target needs to be included in order to produce the aar.

**Comment by SierraGolf** [comment]
@benoitdion we just removed the generation of the "apklib" since neither that nor the "aar" packaging is required. in future versions (1.2.1+) you don't have to use the ```@jar``` anymore because we will not deploy any other artifact to maven central.
