### ISSUE TITLE
Parallel Tests using the CLI

### ISSUE THREAD

**Issue by klausbayrhammer** [cucumber/cucumber-jvm#664]
In order to execute our tests in parallel using the CLI we have created a new ```ParallelMain``` which supports
 * Running multiple .feature-files in parallel
 * A mechanism to configure formatters as before (e.g. ```-f pretty:out -f fully.qual.name:out```) - each executer caches the calls to formatter/reporter and replays them after a feature is executed. So although multiple features are execute in parallel, only one formatter/reporter per type is written.
 * configurable number of executing-threads
 * configurable timout

We could provide a PR if you are interested.

**Comment by danielwegener** [comment]
This however puts expensive operations like classpath scanning and gluecode matching up to every scenario execution. I think these issues could better be solved in the cucumber core abstractions (see #630).

**Comment by klausbayrhammer** [comment]
Parallel exeuction of scenarios  will be tracked in #630
