### ISSUE TITLE
[Cucumber-jvm / Android] Eclipse Junit report is not displayed.

### ISSUE THREAD

**Issue by franck-serot** [cucumber/cucumber-jvm#675]
Hi,
Firstly, thank for your work.

I tested the example cukelator-test.

I configured the class CalculatorActivitySteps in order to generate several reports.

@CucumberOptions(features = "features", format = {"pretty", "junit:/storage/emulated/0/cucumber.example.android.cukeulator.test/junit.xml", "html:/storage/emulated/0/cucumber.example.android.cukeulator.test/cucumber-html", "json:/storage/emulated/0/cucumber.example.android.cukeulator.test/cucumber-report.json"})
public class CalculatorActivitySteps extends ActivityInstrumentationTestCase2<CalculatorActivity> { 
...
}

I pushed the reports from my device to my projet.

> adb pull /sdcard/cucumber.example.android.cukeulator.test

I opened manually the HTML report and the JUnit report.

But, could you please explain me why the JUnit report is not automatically displayed in the JUnit panel of Eclipse by comparaison with a standard Android test ?

Could you also update the roadmap of release and give the next release date ?

Thank you in advance for your response.
Best regards.
Franck

**Comment by SierraGolf** [comment]
There are people which are still using eclipse to do android development? :D 

Can you specify more details about your problem, like:

1. How did you run the test?
2. What versions are you using (e.g. eclipse, adt, cucumber, eclipse cucumber plugin)?

Generally I can say that cucumber for android outputs test results through the ```Instrumentation.sendStatus``` interface in the android junit format. That said it should display as any other android test result in your IDE, assuming you run it like any other android test. I can verify that it works when running cucumber tests from idea and from android studio through the "android test" run configuration with the appropriate cucumber settings (e.g. setting the correct Instrumentation).
