### ISSUE TITLE
Build fails on Java 8

### ISSUE THREAD

**Issue by nhajratw** [cucumber/cucumber-jvm#697]
Trying to do a `mvn clean install` using Oracle JDK 1.8.0-b132 (the released version) results in a few test failures:

    JSONPrettyFormatterTest.featureWithOutlineTest:35 (long stack trace)

and 

    cucumber.runtime.table.FromDataTableTest transforms_to_map_of_double_to_double(cucumber.runtime.table.FromDataTableTest)  Time elapsed: 0.003 sec  <<< FAILURE!
    org.junit.ComparisonFailure: expected:<{[1000.0=999.0, 0.5=-0.5, 100.5=99.5]}> but was:<{[0.5=-0.5, 100.5=99.5, 1000.0=999.0]}>

**Comment by paoloambrosio** [comment]
Closing as it compiles with Java 8
