### ISSUE TITLE
Don't require @Transform annotation if the Transformer can be found automatically

### ISSUE THREAD

**Issue by klikh** [cucumber/cucumber-jvm#703]
If I have a custom `class P`, and a `StringToPTransformer extends Transformer<P>`, cucumber engine could find the transformer automatically by looking to all implementations of Transformer.

In those rare cases when there are several `Transformer<P>` implementations, cucumber should throw an exception requiring the developer to use annotation to explicitly specify the transformer to use for the particular parameter.

**Comment by mpkorstanje** [comment]
We're currently working towards cucumber-expressions which will have a different way to indicate which transformation should be used for each parameter. As such I'm closing this issue.
