### ISSUE TITLE
cucumber-spring no documentation

### ISSUE THREAD

**Issue by jakub-bochenski** [cucumber/cucumber-jvm#724]
I don't require some book sized story, but seriously, at least some basic info?
What versions of spring are supported?
What does it even do? "Share instances across step definitons" - cool, but how exactly? Is context created per feature or per scenario? I see there are also so txn hooks, anything more?
How to go about enabling it at all?
How to enable annotation-based config?

The best thing I could find is https://zsoltfabok.com/blog/2012/01/cucumber-jvm-di/ but it's not very clear, plus involves quite a few DIY workarounds.

**Comment by jakub-bochenski** [comment]
Sorry no docs yet, but the code is on GitHub.

**Comment by jakub-bochenski** [comment]
Let's keep it open until it's 4yo!

**Comment by mlvandijk** [comment]
Blogged: https://medium.com/@mlvandijk/managing-state-in-cucumber-jvm-using-spring-a795e9a1dd18 and am working on a README off this.

**Comment by jakub-bochenski** [comment]
@mlvandijk nice, what I'm missing is a scope reference. E.g. I recall for git you had to use `@ScenarioScoped` to have a bean live for the duration of the scenario, by default it would create a new instance per each step (which can also be useful). An explicit text about how prototype and singletons scopes are going to behave would be useful.

**Comment by jakub-bochenski** [comment]
> Since my team already uses Spring in our projects, we’ve opted to use Spring with Cucumber.

@mlvandijk FYI I've been using different DI frameworks for Cucumber glue with good result. You could even argue it's a nice exercise in separation (e.g. HK2 for application and Guice for Cuccumber)

**Comment by mlvandijk** [comment]
@jakub-bochenski The `@Scope("cucumber-glue")` is in there (unless I'm not understanding your comment correctly?). What's still missing is some more info on using `@ContextConfiguration("classpath:cucumber.xml")` to mark the StepDefs, or @SpringBootTest(classes = TestConfig.class) if you're using SpriongBoot (like we are at our latest project.

**Comment by jakub-bochenski** [comment]
@mlvandijk I just mean you never mention one can also use the standard scopes with cucumber, e.g.:
 - prototype should create a new instance each time preventing any kind of state sharing (which can also be useful);
 - singleton should only create once instance, regardless of scenario boundaries (useful for expensive objects).
I'm making the above up from memory as I haven't used cucumber-spring for a while.

**Comment by mlvandijk** [comment]
@jakub-bochenski Thnx. I'll have to create some example projects to figure those out and document accordingly :)
