### ISSUE TITLE
JUnit runner fires wrong events

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#73]
Try running the example in the picocontainer module in IDEA: `cucumber.runtime.java.picocontainer.cukes_Test`

It prints out: 

```
Test '.Scenario: Many cukes.And a big basket with cukes' ignored
Wrong test finished. Last started: [] stopped: And a big basket with cukes; class org.junit.runner.Description
```

There is something wrong with how we're issuing JUnit events. Perhaps we need to use `runLeaf` - need to study the JUnit API more closely. This is not simple!

The main goal is to run with JUnit while still having the ability to forward events to a Cucumber/Gherkin formatter (such as HTML) at the same time as we forward events to JUnit. And everything must happen in the right order...

**Comment by jaff20** [comment]
Hi, I am running seleniumjava cucumber based test, I am facing this issue too... could u please tell me how to fix this one... all other test runs fine.. one particular test its giving me this issue... test ignored....

Thanks

regards
jaff
