### ISSUE TITLE
Java 8 support?

### ISSUE THREAD

**Issue by rmannibucau** [cucumber/cucumber-jvm#738]
Hi

any plan to add a java 8 module using new language features (an API like scala module surely)?

**Comment by ShijunK** [comment]
Just find out that `cucumber.runtime.ParameterInfo#fromTypes` always using null for format and transformer.

Where is documentation of Java 8 support? If there is one, could it be updated to include a warning?

```
The following two annotations are not supported with Java 8 lambda step definitions 
cucumber.api.Format
cucumber.api.Transform
```

And if the following bug is the reason behind, now it is reported being fixed and backported to 8u112, any plan to adopt it? 

http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8147585

Or should I just switch back to method based implementation if need @Format and @Transform?

**Comment by zyablic** [comment]
Is it feasible to implement the following feature:

When("I click (.*)", Element::click);

Using method reference we can make the steps defining process more convenient.
