### ISSUE TITLE
--tags @sometag:<count> not supported?

### ISSUE THREAD

**Issue by pblack** [cucumber/cucumber-jvm#762]
Perhaps I'm doing something wrong, or missing something, but in cucumber-ruby, I can do:

```
ruby -S cucumber @leave_window_open:0
```

And cucumber will fail if there are any scenarios tagged as @leave_window_open. I had wanted to use this in our CI server to fail if someone accidentally committed a feature with this tag, as it will hang the run. In my case, if a test fails, this will cause cucumber to wait for user input before closing the browser window (useful for building/debugging scripts). But I don't want our CI server to hang. I can filter out these scenarios with ~@leave_window_open, but then I would be quietly hiding that some of these integration tests are not getting run....

**Comment by lunivore** [comment]
Hi @pblack , you've managed to submit this issue in the cucumber-jvm repository, where the cucumber-ruby team won't see it. If this is still important to you, please could you submit it there? Apologies that nobody spotted it and redirected you at the time. I'm closing this ticket here as it's not related to Cucumber-JVM.
