### ISSUE TITLE
add a formatter before glue code creation

### ISSUE THREAD

**Issue by gboucherie** [cucumber/cucumber-jvm#769]
Hi,

Could it be possible to add a new method in Formatter class that will be called before glue code creation ?
We need this to retreive the Scenario name in our Selenium + Cucumber test and pass it to the WebDriver.
At this time we can't because our driver is created with spring (or picocontainer) at glue code creation and we can't change the Selenium driver capabilities after its creation.

I can provide more information or code if necessary.

Thanks

**Comment by lunivore** [comment]
Hi @gboucherie , is this problem still important to you? If so, please do provide us with some code which we can use to investigate, or let us know you're working on that.

Otherwise, if I don't hear from you, I will close this ticket in 1 week.
