### ISSUE TITLE
Intermittent "Arity mismatch error" 

### ISSUE THREAD

**Issue by maciejjaskowski** [cucumber/cucumber-jvm#773]
We are experiencing an `cucumber.runtime.CucumberException` every now and then
It says e.g.
`Arity mismatch: Step Definition 'StepDefinitions.scala:30' with pattern [^My pattern$] is declared with 0 parameters. However, the gherkin step has 2 arguments`

Which is obviously false.

I have digged into this issue and found out, that the root cause of this issue is a bug in `StepBody.functionParams` method.

The method

```
private def functionParams(f: Any) =
      f.getClass.getDeclaredMethods.filterNot(_.isBridge).head.getGenericParameterTypes
```

clearly assumes that `f.getClass.getDeclaredMethods` will always return at most 2 methods, and exactly one not bridged.

However, it turns out, this does not need to be true which sometimes (sic!) causes the aforementioned error. Sometimes because the `getDeclaredMethods` error returns methods in indeterministic order: http://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getDeclaredMethods%28%29

Please, find below the minimal counterexample.

The thing is that the same might happen when you define a StepDefinition class.

It's enough to extend it with a trait and then access any of it's methods or values in the declaring StepDefinition.

```
import cucumber.api.DataTable
import org.scalatest.{Matchers, FlatSpec}
import scala.language.reflectiveCalls

class StepBodyTest extends FlatSpec with Matchers {

  it must "abc" in {
    val s = new Outer {
      val arr = { (x: DataTable) =>
        List(1).foreach { y =>
          println(m)
        }
      }.getClass.getDeclaredMethods
    }

    s.arr.toList.length should be (2)
  }

  trait Outer {
    val m = "FancyMethod"
  }

}
```

**Comment by lunivore** [comment]
Hi @maciejjaskowski , are you still looking at the Scala reflection side of this issue? If so, please let us know.

Otherwise we'd prefer to reraise it if it rears its head again, as the codebase has moved on significantly and it may not be relevant any more. If I don't hear back from you I will close this ticket in a week.
