### ISSUE TITLE
Severe lack of documentation for Cucumber-Clojure

### ISSUE THREAD

**Issue by stormcoder** [cucumber/cucumber-jvm#780]
There is basically no documentation for Cucumber-Closure which makes the framework next to useless.

**Comment by grahamlyons** [comment]
Could we close this, please? It makes me sad.

**Comment by mattwynne** [comment]
Me too @grahamlyons! @stormcoder I'd love you to help us fix the docs. Feedback from new users is really important to us.

Are you willing to make a list of concrete actions we could take to improve the situation for you?

**Comment by aslakhellesoy** [comment]
@grahamlyons Are you sad about the bickering in this ticket, or the poor state of the docs? I'd like to keep this ticket open until we actually have some decent docs for cucumber-clojure.

**Comment by grahamlyons** [comment]
@aslakhellesoy it's the tone of the ticket - I'd love to see more extensive documentation but perhaps we could start afresh, in a more positive light?

**Comment by aslakhellesoy** [comment]
The tone is water under the bridge for me at least. What would be great is to simply document how cucumber-clojure works in the cucumber-clojure README.md. I don't have time to spend on this (and I'm not a Clojure expert), but I'm happy to merge PRs.

When [the new website](https://github.com/cucumber/website) starts to take shape we can move it there.

**Comment by khaledkebbe** [comment]
I have a question with regards to cucumber test automation in bamboo. Does anyone have any recommended approaches where cucumber tests can be automated for projects in bamboo using a config file? (yaml file maybe?)

**Comment by brasmusson** [comment]
@khaledkebbe Your questing should be asked on the [The Cukes Google Group](https://groups.google.com/forum/#!forum/cukes), this is an issue tracker and not a support or discussion forum.

**Comment by gphilipp** [comment]
I wrote a BDD getting started guide for Clojure here : https://github.com/gphilipp/bdd-guide-clojure

**Comment by kkebb** [comment]
The BDD guide will definitely prove to be useful, thank you!

FYI the latest version of lein cucumber is 1.0.4: https://clojars.org/org.clojars.punkisdead/lein-cucumber

**Comment by lunivore** [comment]
Verified that there's now some documentation for this; closing the issue.
