### ISSUE TITLE
Duplicate step definitions but different arguments

### ISSUE THREAD

**Issue by Gary-Xin** [cucumber/cucumber-jvm#782]
I have 2 step definition method. They have different argument number (1 has 1 String argument while the 2nd method has 7 String arguments). When I tried to run the following step, it got the following error. My understanding is that Cucumber should treat them as 2 different step definitions and it should look for the 2nd method in my case. Am I wrong? thanks.

cucumber.runtime.AmbiguousStepDefinitionsException: ✽.Given There is a user in KANA as "s930001", "Test", "middle", "Meme", "Happy", "Mr", "Male"(spml/spml.feature:25) matches more than one step definition:
  ^There is a user in KANA as "(._?)"$ in FeatureDefination_SPML.there_is_a_user_in_KANA_as(String)
  ^There is a user in KANA as "(._?)", "(._?)", "(._?)", "(._?)", "(._?)", "(._?)", "(._?)"$ in FeatureDefination_SPML.there_is_a_user_in_KANA_as(String,String,String,String,String,String,String)

The following are the 2 methods:

```
@Given("^There is a user in KANA as \"(.*?)\"$")
public void there_is_a_user_in_KANA_as(String username) throws Throwable {
    //some code
}

@Given("^There is a user in KANA as \"(.*?)\", \"(.*?)\", \"(.*?)\", \"(.*?)\", \"(.*?)\", \"(.*?)\", \"(.*?)\"$")
public void there_is_a_user_in_KANA_as(String arg1, String arg2, String arg3, String arg4, String arg5, String arg6, String arg7) throws Throwable {
    //some code
}
```

**Comment by clicman** [comment]
The rigght complete regex should be like:
``` java
    @Когда("^он \"([^\"]*)\"[^\"]*$")
    public void он_скобки(String a) throws Throwable {
        
    @Когда("^он \"([^\"]*)\" и \"([^\"]*)\"[^\"]*$")
    public void он_скобки(String a,String b) throws Throwable {
```

Will it be good for master? I can make appopriate PR.

**Comment by clicman** [comment]
@brasmusson what do you think about regex in upper comment? It will be good if it will possible to pass more than one string argument as parameters.

**Comment by brasmusson** [comment]
@clicman The capture groups was changed from ([^"]*) to (.*?) a while back, https://github.com/cucumber/cucumber-jvm/commit/9a21bbff1a0584665b3c99aad88e433667fcc37b, https://github.com/cucumber/cucumber-jvm/issues/737#issuecomment-47240448. Afterwards there have been some discussion if it was a good change, #737, [mailing list post](https://groups.google.com/forum/#!searchin/cukes/snippet|sort:date/cukes/icrXP6PX_c4/7xSNod4tpB0J), but there is no decision to change again (which preferably should be done in all Cucucmber versions).

**Comment by LArchaon** [comment]
Hi,
Currently having hard time with the same issue as well.
Cucumber has a [guess mode](https://github.com/cucumber/cucumber/wiki/Step-Definitions#guess-mode) that should handle this problem, but AFAIU cucumber-jvm does not support this

A preposition would be to add a guess mode code check in [Runtime Glue](https://github.com/cucumber/cucumber-jvm/blob/5a6400c8757d18e3b0f2fef2d9d49dfbc2186c58/core/src/main/java/cucumber/runtime/RuntimeGlue.java) line 68

I can try to do a Pull request for this feature, will it be ok?

**Comment by mattwynne** [comment]
@brasmusson we changed the default regexp back in Ruby: https://github.com/cucumber/cucumber/pull/663

@LArchaon I think guess mode is a bit of an anti-pattern myself. If you need it I'd say your step defs are getting over-complex. I'd urge you to just tighten up your regexes.

**Comment by sebrose** [comment]
> On 9 Apr 2015, at 21:57, Matt Wynne <notifications@github.com> wrote:
> 
> @brasmusson we changed the default regexp back in Ruby: cucumber/cucumber#663
> 
> @LArchaon I think guess mode is a bit of an anti-pattern myself. If you need it I'd say your step defs are getting over-complex. I'd urge you to just tighten up your regexes.
> 

+1

Guess mode? The clue is in the name. If you have to guess you're probably not defining business critical behaviour.

**Comment by LArchaon** [comment]
@mattwynne @sebrose Here is a good example when guess mode could simplify step definition

Guess mode:
```
@Given("^proxy settings is (.+)$")
public void proxy(String host) {
    facade.proxy(host);
}

@Given("^proxy settings is (.+):(\\d+)$")
public void proxy(String host, int port) {
    facade.proxy(host, port);
}
```

No Guess mode
```
@Given("^proxy settings is ((?:http|https):[^:]+)$")
public void proxy(String host) {
    facade.proxy(host);
}

@Given("^proxy settings is (.+):(\\d+)$")
public void proxy(String host, int port) {
    facade.proxy(host, port);
}
```

In this specific case I was able to create a workaround with a non trivial regex, but sometimes it is really nasty.

**Comment by lunivore** [comment]
Hi @Gary-Xin, we haven't heard back from you so I presume the suggestions provided have worked for you. If we don't hear back from you to tell us otherwise, we'll close this ticket in a week. Thanks!
