### ISSUE TITLE
Add support for spring-boot @IntegrationTest in spring module

### ISSUE THREAD

**Issue by yukatan** [cucumber/cucumber-jvm#783]
Sometimes you need to run test agains the server running and not to use mockMcv or something similar. At the moment there is not support for this annotation and run the spring boot application is really a headache. Where are at the moment running the spring boot application with a hook, but it would be easier to support this annotation to test spring boot applications with cucumber.

**Comment by c10gdn** [comment]
Hi, I tried using this solution referred to on stackoverflow but I couldn't get it to work, is there any update on the progress?  Thanks.

**Comment by aantono** [comment]
Actually all that is needed is to add support for `@BootstrapWith` annotation in the `SpringFactory`, that will automatically support the newly added Spring Boot `@SpringBootTest` annotation and all the sliced tests like `@WebMvcTest`, etc.

**Comment by mpkorstanje** [comment]
Superceded by #1061.
