### ISSUE TITLE
IntelliJ reporting error parsing POM using maven-android-plugin version  3.9.0-rc.1 

### ISSUE THREAD

**Issue by kikyoungkwon** [cucumber/cucumber-jvm#788]
For cucumber-android module, the issue is reported here (https://code.google.com/p/maven-android-plugin/issues/detail?id=449). Need to update to latest maven-android-plugin, version 4.0.0-rc.1.

When updating, also need to consider android project structure, because 4.0.0-rc.1 changed default project structure to Gradle structure (since it is much more like a real Maven project anyway, https://groups.google.com/forum/#!msg/maven-android-developers/eeMXog58mzA/fgDAXd7K_HcJ).

**Comment by SierraGolf** [comment]
we have migrated the cucumber android examples to 4.0.0. the cucumber-android project it self does not have a dependency to the maven android plugin anymore.

see: https://github.com/cucumber/cucumber-jvm/pull/819
