### ISSUE TITLE
unable to run cucumber options from teamcity using maven command lines

### ISSUE THREAD

**Issue by Narsimharao** [cucumber/cucumber-jvm#797]
when i am trying to run cucumber-jvm feature files from teamcity using command line as mvn test -Dcucumber.options="--tags @teamcity"..I am seeing the error as below 
"Invalid task '@teamcity': you must specify a valid lifecycle phase, or a goal in the format plugin:goal or pluginGroupId:pluginArtifactId:pluginVersion:goal"

**Comment by frankforward** [comment]
@Narsimharao how did you fix this?

**Comment by pgnanasekaran** [comment]
@Narsimharao Did you find a solution for ur problem?

**Comment by michalkaftanski-airhelp** [comment]
Any workaround found?

**Comment by Narsimharao** [comment]
Hi @michalkaftanski-airhelp , we have found some workaround for this as we created runner file and gave all the cucumber options and hooks showing as in example below..

@RunWith(Cucumber.class)
@CucumberOptions(format = { "pretty", "html:target/cucumber-html-report_test”,”json:target/basicreport_test.json" }, 
		glue = { "com.test.steps" },
		//dryRun=true,
		features = { "classpath:com/test/bdd/test.feature”}
		,tags ={"~@ignore", “@teamcity”}

        ,monochrome=true
)
public class TestRunner{
	//This is just a runner
	
}

Then we give this runner file name in teamcity. I hope this helps you

**Comment by michalkaftanski-airhelp** [comment]
Hi @Narsimharao, thanks I will check it out.

For the moment I've used ugly workaround with running maven from the command line step in TC instead of maven step. And it helps.
