### ISSUE TITLE
TestNG reports entire Cucumber test suite as a single <testcase>

### ISSUE THREAD

**Issue by rankinc** [cucumber/cucumber-jvm#804]
When running cucumber-jvm 1.2.0 with JUnit, Jenkins reports each Cucumber step as an individual testcase. However, switching to use TestNG with RunCukes implemented as:

    @CucumberOptions(plugin = "json:target/cucumber-report.json")
    public class RunCukesTest extends AbstractTestNGCucumberTests {
    }

Jenkins then reports the entire RunCukesTest as a *single* testcase called "run_cukes".

Cucumber's own report of (e.g.)

    5 Scenarios (4 failed, 1 passed)
    72 Steps (4 failed, 44 skipped, 24 passed)

is the same with both JUnit and TestNG, so I think the problem must be with the TestNG reporting.

**Comment by brasmusson** [comment]
I brought the two pending TestNG PR:s (#653 and #621) up to date with the current tip of the master; #817 and #818. I would be great if you evaluated them as a TestNG user @rankinc, neither I am using TestNG myself.

**Comment by Supreme85** [comment]
Is my issue related to this one? What actual status of it? (as I can see PRs 653 and 621 closed but issue still open)
My problem:
If I run tests using TestNG runner I have no steps in my IntelliJIdea view (and can't get them in report)
But if I use JUnit runner I can see all steps
JUnit runner
@RunWith(Cucumber.class)
@CucumberOptions(<same options as in TestNG runner>)
public class JUnitRunner { }
Results: http://pix.my/zSSImRsE

TestNG runner
@CucumberOptions(<same options as in JUnit runner>)
public class PharmCucumberTestSuite extends AbstractTestNGCucumberTests { }
Results: http://pix.my/kr8B9XNO

**Comment by brasmusson** [comment]
In Cucumber-JVM v1.2.3 and later, each feature should be executed as a separate TestNG test when extending `AbstractTestNGCucumberTests`.

**Comment by mikejramsey56** [comment]
I am running cucumber-java, cucumber-testng v1.2.4 with testng v6.9.10. I am using the TestNG runner. Tagging in the feature files works fine (only the selected features/scenarios execute).  But the reports are abysmal. I personally don't have a problem with the JUnit test runner but my client is set on cucumber and TestNG.  Cucumber is doing its part by running tagged tests. I'll try to dig around in the TestNG code to see what can be done.
