### ISSUE TITLE
release new version with juint 4.12 compatibility fixes

### ISSUE THREAD

**Issue by devopsd** [cucumber/cucumber-jvm#822]
merged in 002df29ff345d46a0fabd9940a8a3f4edbec435a (#794)

**Comment by aslakhellesoy** [comment]
Not sure what this ticket is about. Closing it.

**Comment by brasmusson** [comment]
@devopsd Using the snapshot release version 1.2.1-SNAPSHOT (see [install Cucumber-JVM](http://cukes.info/install-cucumber-jvm.html)), you can use Cucumber-JVM with junit 4.12 right now.
