### ISSUE TITLE
Define a "standard" java 8 API to define steps

### ISSUE THREAD

**Issue by rmannibucau** [cucumber/cucumber-jvm#830]
Hi

ATM java 8 uses constructor to define steps. it is broken in several situation - all which needs some init on the glue, ie when you use any kind of "container" lib.

We hit this issue in cukespace and I defined:

``` java
public interface Lambda {
    void define();
}
```

to workaround it

Is it possible to add it in LambdaGlueBase?

Only change is to call this method when creating instances for cucumber.

wdyt?

PS: also note the fact it uses JavaBackend so hardly makes hard to integrate with other framework - cukespace has its own backend and we now need to inherit from java one just for it, maybe introducing a LambdaBackend defining the needed methods could help here as well

FYI here is a test with Lambda: https://github.com/cukespace/cukespace/blob/a4f8e33cec2d34ac43ce004a9fa676082595b780/examples/src/test/java/cucumber/runtime/arquillian/java8/J8Test.java and here is the full diff https://github.com/cukespace/cukespace/commit/a4f8e33cec2d34ac43ce004a9fa676082595b780

**Comment by aslakhellesoy** [comment]
Can you send a PR please?

**Comment by mpkorstanje** [comment]
As discussed in https://github.com/cucumber/cucumber-jvm/issues/1117 a LambdaGlueRegistry has been extracted in ab51ea29a18d83de0a3b031bbeaa17b62cbba506. This should make it easier for other backends to use lambda glue outside of the constructor.

How other backends do this is left up to those backends.
