### ISSUE TITLE
Add @Documented annotation to all step annotations

### ISSUE THREAD

**Issue by peterox** [cucumber/cucumber-jvm#833]
Can you please add the @Documented annotation to the I18n.java.txt template file so that the Javadoc for all step definitions documents the pattern used by the definition?

See http://docs.oracle.com/javase/7/docs/api/java/lang/annotation/Documented.html

Thanks

**Comment by aslakhellesoy** [comment]
I'd be happy to apply a patch if you fork the repo and send us a pull request.

**Comment by peterox** [comment]
Pull request created
