### ISSUE TITLE
JSON report missing scenario description when provided for Scenario outline

### ISSUE THREAD

**Issue by kevinschwarz** [cucumber/cucumber-jvm#837]
When I configure the JSON reports the scenario description comes as null in the outputted JSON. It would be useful to populate this with the description from the Scenario outline

@CucumberOptions(plugin = {"json:target/cucumber/cukes.json" })

 Scenario Outline: Scenario outline name
    Scenario outline description
    
Given I have a feature
    When I test "<result type>"
    Then I get "<result type>" results

    Examples: 
      |result type |
      | positive   |
      | negative   |
      | ambiguous  |

Now see outputted JSON, description is null

   "description": "",
        "name": "Scenario outline name",
        "keyword": "Scenario Outline",
        "line": 44,
        "steps": [
          {
            "result": {
              "duration": 37500,
              "status": "passed"
            },
            "name": "I have a feature",
            "keyword": "Given ",
            "line": 38,
            "match": {
              "location": "ReporterSteps.i_have_a_feature()"
            }
          },
          {
            "result": {
              "duration": 44210,
              "status": "passed"
            },
            "name": "I test \"positive\"",
            "keyword": "When ",
            "line": 39,
            "match": {
              "arguments": [
                {
                  "val": "positive",
                  "offset": 8
                }
              ],
              "location": "ReporterSteps.i_test(String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "duration": 24473,
              "status": "passed"
            },
            "name": "I get \"positive\" results",
            "keyword": "Then ",
            "line": 40,
            "match": {
              "arguments": [
                {
                  "val": "positive",
                  "offset": 7
                }
              ],
              "location": "ReporterSteps.i_get_results(String)"
            },
            "matchedColumns": [
              0
            ]
          }
        ],
        "type": "scenario"

**Comment by AkaiTsuki** [comment]
In CucumberScenarioOutline.java under core model, the method createExampleScenario is hard code the description with "" when create a new instance of Scenario from example table(on line 59), which I guess it  should be getGherkinModel().getDescription().
