### ISSUE TITLE
Rerun functionality executes scenarios unnecessarily even the scenarios are passed 

### ISSUE THREAD

**Issue by Prabat** [cucumber/cucumber-jvm#840]
If any scenarios are failed in execution then rerun functionality working fine & executed only failed scenarios But in passed condition -> rerun.txt is blank/empty & it is initiating all the scenarios unnecessarily.

**TriggerTest.java**
```java
@RunWith(Cucumber.class)
@CucumberOptions(
		features = { "classpath:script"},
		plugin = { "pretty","rerun:target/rerun.txt","html:target/report/html-basic",
                                "json:target/report/cucumber.json" }, 
                glue = { "script" }
		,tags = { "@Sprint1"}
		)
public class TriggerTest {

}
```

**RerunTest.java**
```java
@RunWith(Cucumber.class)
@CucumberOptions(
		features = { "@target/rerun.txt" },
		plugin = { "pretty","html:target/report/rerun/html-basic",         
                                "json:target/report/rerun/cucumber.json" }, 
                glue = { "script" }
		)
public class RerunTest {

}
```

Above are two Test files used in project 
* **TriggerTest.java** file is the main test execution -> save the failed scenarios in the file "target/rerun.txt"
* **RerunTest.java** file is the second test execution for failed scenarios by taking input from "target/rerun.txt"

Please look into this issue for scenario's passed condition & Provide the solution if it can be done in a different way.

**Comment by aslakhellesoy** [comment]
@Prabat Please don't request that others fix bugs for you. This is an open source project, which means we rely on bugs to be fixed by the community.

Wold you be willing to spend time fixing this yourself and send us a pull request? You'd start by writing a failing test to reproduce the incorrect behaviour, then make it pass.
