### ISSUE TITLE
Dynamic Glues

### ISSUE THREAD

**Issue by bsz0206** [cucumber/cucumber-jvm#846]
Hi,

Sometimes you need to change your glues based dynamically based on the steps. Assume you have an step like this: "I login"

When I am testing site A
And I login as user "a", "b"

When I am testing site B
And I login as user "a", "b"

So there are two similar step definitions and glue should change as per the previous step.

Is there any way this can be done?

**Comment by aslakhellesoy** [comment]
Short answer: Yes. Please ask questions on the cukes google group. This is a bug tracker.
