### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by kwoz** [cucumber/cucumber-jvm#848]
I am looking into using it in a project for a client, but for formal reasons a license is required. Can you add a suitable license?

**Comment by aslakhellesoy** [comment]
Where do you want this added? The repo has had one since the start:

https://github.com/cucumber/cucumber-jvm

**Comment by aslakhellesoy** [comment]
Is the UK spelling of `LICENCE` the problem?

**Comment by kwoz** [comment]
Sorry, this issue was created in error.
