### ISSUE TITLE
Transformers are not eligible for dependency injection

### ISSUE THREAD

**Issue by ghost** [cucumber/cucumber-jvm#851]
Looking at the Guice module, I can see that dependency injection doesn't seem to take place on the `Transformer` interface.

In order to support this, the core/src/main/java/cucumber/runtime/ParameterInfo.java would need the `private static Transformer<?> getTransformer(Annotation annotation)` methods to be updated to call the object factory. From here, Guice would be able to inject the dependencies.

**Comment by mpkorstanje** [comment]
As we're building towards cucumber expressions this might be best solved by making it possible to add configurations to the configuration as part of the glue code. A lambda example of this might look like this:

```java

final class MaConfigurationFrançaise extends Configuration {
   
   MaConfigurationFrançaise(TrafficLightDatabase database){

       ExpressionDeConcombre("vert", "fue (rouge|jaune|vert)",
           groupValues -> database.createTrafficLight(groupValues);

   }
}
```
