### ISSUE TITLE
Arity mismatch Java8 Step Definition error

### ISSUE THREAD

**Issue by davidcoelho** [cucumber/cucumber-jvm#852]
When I define my step by using cucumber Java8 feature, I get this exception:

```
cucumber.runtime.CucumberException: Arity mismatch: Step Definition 'MyStepsDef.java:16' with pattern [^I have a list of numbers:$] is declared with 0 parameters. However, the gherkin step has 1 arguments [Table:[[11], [3], [7]]]. 
```

But If I use the **Given** annotation in a class method, with the same step definition works fine.

##### MyStepsDef.java
```java
public MyStepsDef() {
        Given("^I have a list of numbers:$", (DataTable t) -> {
            List<Integer> numbers = t.asList(Integer.class);
            // do something here
        });
}
```

##### myfeature.feature
```
Given I have a list of numbers:
      | 11 |
      | 3  |
      | 7  |
```

##### Dependencies
```
cucumber-java:1.2.2
cucumber-java8:1.2.2
```

**Comment by nablik** [comment]
I have the same problem too.

**Comment by brasmusson** [comment]
@davidcoelho Is this issue fixed by PR #847 that you opened a week ago?

**Comment by davidcoelho** [comment]
@brasmusson yes. After I coded, I tried to find an issue about this problem, but I didn't find it.. So I thought was better to create this issue...

**Comment by dayatang** [comment]
I have the same problem too.
