### ISSUE TITLE
Make method Formatter#uri provide fullpath to feature file.

### ISSUE THREAD

**Issue by avokin** [cucumber/cucumber-jvm#854]
In IntellJ IDEA we use Formatter implementation to process output of cucumber and build tree of tests.  

But we faced with problem that Formatter#uri provides only related path to executed feature file

Let’s consider running all features in folder.

For example we have following folder structure:
features
  |-  test1.feature
  |-  subdir
      |- test2.feature

When we run features in folder “feature”
Formatter#uri will provide
test1.feature
subdir/test2.feature

But it would be nice to have full path to executed feature file.

**Comment by os97673** [comment]
> But it would be nice to have full path to executed feature file.

or have another way to construct the full path (e.g. have full path to features directory)
