### ISSUE TITLE
TableTransformer<T>

### ISSUE THREAD

**Issue by sponte** [cucumber/cucumber-jvm#862]
Currently DataTables can only be converted to DataTable, Map or List.

In order to keep steps definitions, it would be good to add support for TableTransformer<T>:

``` java
public interface TableTransformer<T> {
    T transform(DataTable table);
}
```

``` java
@Given("I have a product")
public void Given_I_have_a_product(MyProduct product) {
    // code
}
```

``` cucumber
Scenario: Product
Given I have a product
| Name  | My product |
| Price | 220        |
```

**Comment by aslakhellesoy** [comment]
Does the `MyProduct` class have `name` and `myProduct` fields (instance variables) in this case?

I don't think it's a feature many people want, but I'd be happy to add support for it if you send a pull request.

**Comment by sponte** [comment]
Hi Aslak

Thanks for quick response.

Yes MyProduct would like as follows:

```java
@XStreamConverter(MyProductTableConverter.class)
public class MyProduct {
  public String name;

  // default
  public double price = 10;
}
```

I haven't looked into cucumber code yet, any pointers if I decide to implement it myself?

**Comment by aslakhellesoy** [comment]
So the `My product` column should be called `price` then?

See `TableConverter` and `TableConverterTest`

**Comment by sponte** [comment]
Sorry, forgot to add ```@Transpose``` to step definition. The idea is that you have a model class with lots of fields, and use table to "overlay" what's in the table over your model (overriding defaults). That way I can have MyProduct class with 20 fields, and only override price field because I only care about it in a test.

I'll have a look at the ```tests```, thanks.

**Comment by mpkorstanje** [comment]
It appears that this is currently possible.
