### ISSUE TITLE
formatter is not generating the json steps report

### ISSUE THREAD

**Issue by GiannisPapadakis** [cucumber/cucumber-jvm#869]
Using cucumber-testng artifact and running with CucumberOption --> format = {"json","json:target/cucumber-report-composite.json"} json is not generated under target directory.
this.runtimeOptions.formatter(this.classLoader) returns null

**Comment by brasmusson** [comment]
I cannot reproduce this issue. I have no problem to modify the [examples/java-calculator-testng](https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-calculator-testng) to generate json formatter output at the same time both to stdout and to a file in the target directory. I tested both v1.2.2 and v1.2.3-SNAPSHOT and all runner classes in the example.

**Comment by dkowis** [comment]
Please provide us a working proof that it doesn't work, and feel free to reopen the issue with that.

**Comment by GiannisPapadakis** [comment]
I am attaching the png showing that java-calculator-testng demo (RunCukesByFeatureAndCompositionTest.java) run using formatter json:target/cucumber-report-feature-composite.json but under target i am not seeing the generated json file for the step definitions. Is it something wrong with my run configuration. I am running using maven and individual file.
![run java calculator](https://cloud.githubusercontent.com/assets/3785668/7877683/e7ba033c-05e6-11e5-93b5-b8f9c7a842ee.png)

**Comment by brasmusson** [comment]
@GiannisPapadakis Try and run maven from command line instead from IntelliJ, it look suspiciously like you have run into #803 (which is fixed in v1.2.3-SNAPSHOT).

**Comment by GiannisPapadakis** [comment]
Now it is running the demo and generates report but in my project it does
not ....(very strange behaviour). I am using also
@CucumberOptions(

      glue = {"com.iri.qa.automation"},
      format = {"json:target/cucumber-report-composite.json"},
      features= {"ptamobilesuite/target/test-classes/com/"},
      strict = true)


Is there any reason why i cannot generate in my project the json using
1.2.3-SNAPSHOT?


Thanks


2015-05-29 10:29 GMT+03:00 Björn Rasmusson <notifications@github.com>:

**Comment by brasmusson** [comment]
@GiannisPapadakis If you add the sonatype snapshot repo to your pom.xml ([described here](https://cucumber.io/docs/reference/jvm)), and change the version of Cucumber-JVM in your pom.xml, you should be able to use v1.2.3-SNAPSHOT version from your IDE.

**Comment by GiannisPapadakis** [comment]
I solved the issue with your proposal. Thanks so much for the information!

2015-05-29 11:47 GMT+03:00 Björn Rasmusson <notifications@github.com>:
