### ISSUE TITLE
Eclipse Junit plugin broken by multiline examples

### ISSUE THREAD

**Issue by temyers** [cucumber/cucumber-jvm#872]
If I have a feature file containing a multiline argument in an example table, running it using the Cucumber JUnit runner through Eclipse, progress is not reported and the test never completes in the JUnit view and the process is still running under the debug view (although the process finishes as expected in the console)

Sample Cucumber runner:
```
package test.samples.acceptancetests;

import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

@RunWith(Cucumber.class)
@CucumberOptions(glue = { "test" }, features = "src/test/resources/features", format = {
        "pretty", "json:target/cucumber-reports/cucumber.json" }, tags = { "@complete,@accepted,@dev,@wip" })
public class DryRunTests {
}
```

Sample feature file:
```
Feature: Junit Eclipse

	In order to be productive
	As a tester
	I want to run Cucumber scenarios through Eclipse
	
	@dev
	Scenario Outline: test multiline output
		Given I have the text:
		"""
		one
		two
		"""
		When I look for text
		Then I should see <output>
		
		Examples:
		| output   |
		| one\ntwo |
```

**Comment by temyers** [comment]
tested using cucumber 1.2.0

**Comment by sebrose** [comment]
@temyers : you're not using table delimiters in your Given step, so this isn't valid Gherkin. An error should be produced.

However, even if you do use table delimiters '|' this behaviour still isn't supported.

**Comment by temyers** [comment]
@sebrose 

The Given step is using a DocString - https://cucumber.io/docs/reference#step-arguments

That step is not intended to be a table, and isn't the source of the problem.

The issue is that the example table of the scenario outline contains a newline character: `one\ntwo`

This is valid Gherkin, and works through the command line, but breaks the Eclipse Junit plugin, presumably because the scenario name.

If you can point me in the right direction I could look at contributing, but I'm not sure where to start.

**Comment by brasmusson** [comment]
@temyers You should try and use the option `--junit,--filename-compatible-names` (in v1.2.5-SNAPSHOT, see #1002), it changes the names used in notifications to JUnit listeners to not include anything other that [a-zA-Z0-9_],. so it should fix the problem with the Eclipse JUnit plugin.

**Comment by temyers** [comment]
@brasmusson Cheers, I'll check it out.
