### ISSUE TITLE
scenario.write() method not writing text in json report

### ISSUE THREAD

**Issue by tauheedkhan** [cucumber/cucumber-jvm#876]
I am using scenario.write() method to print session id in the report, but it is not printng the text in the json format of the report and working fine in html report.

My cuke file is:

import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

@RunWith(Cucumber.class)
@CucumberOptions(tags = { "@GuestMultiSkuAndNormalCheckout" }, monochrome = true, strict = true, glue = { "com.bbb" }, format = {
	"pretty", "html:target/cucumber-reports",
	"json:target/cucumber-reports/cucumber.json" }, features = "src/test/resources/features/sanity")
public class RunCuke {
}

**Comment by dkowis** [comment]
Can you provide a small example project that demonstrates the failure? Or better yet, a runnable test that can prove it's not working?

**Comment by tauheedkhan** [comment]
Issue is with masthought report plugin............closing the issue

**Comment by shankar4a1** [comment]
@tauheedkhan i am facing an issue with the scenario.write where as it is entering value in Json report but not in html report.could you please help me to resolve the issue .am using master thought cucumber report with 3.15 .
