### ISSUE TITLE
Null String arguments

### ISSUE THREAD

**Issue by M21B8** [cucumber/cucumber-jvm#877]
Not an issue as such, more of a feature request.

This is what i'm trying to do.

Scenario: English News
    Given with the locale is set to 'en-gb'
    When they access the login page
    Then they see the news
      | title   | image | link | linkText | preText                         | postText |
      | Welcome | null  | null | null     | FIT_SYS. You shouldn't be here. | null     |

In this feature, i have an object which i want to compare against what was returned by the system, the java object returned by the backend has null values. When i run this feature through, the 'null' values get passed in as the string "null", if i leave them blank, I get an empty string "".

I can get round it on this specific scenario by adding a converter to my data object like this:

@XStreamConverter(CustomStringConverter.class)
public class NewsItemData {
...
}

However, I have loads of these things to write, hundreds maybe even a thousands, and I don't want to have to do it for every single one of them. What I'd like to do is be able to somehow register this transformer against the whole test suite, in one go.

Alternatively, if there's a better way to handle null/blank/empty string arguments, please let me know.

**Comment by dkowis** [comment]
Honestly, I think you might be using cucumber wrong. You'll have a lot less pain if you try to use something that's designed to work with programming languages directly to accomplish this kind of testing.

Perhaps you can describe your data in a different way? Describe what the business value is in the page, not the exact content of the page. Doing so should help you have more robust and flexible feature files.

Also, I don't think that kind of feature is taking cucumber in the right direction. I'm going to recommend you ask on one of the cucumber support options: https://cucumber.io/support
