### ISSUE TITLE
classLoader-Parameter in cucumber.api.cli.main not used consequently (version 1.2.2)

### ISSUE THREAD

**Issue by shell88** [cucumber/cucumber-jvm#880]
I had to use my own ClassLoader and i mentioned, that the parameter classLoader from the run-method is not used consequently. Whereas the parameter is passed to every class (ResourceLoader, Runtime, ClassFinder) the PluginFactory won´t use it but calls Thread.currentThread().getContextClassLoader(). Seemed to me that this behaviour isn´t really senseful.

Thanks and kind regards from bavaria

**Comment by aslakhellesoy** [comment]
Hi @shell88, would you be interested in sending us a PR to improve this?

**Comment by shell88** [comment]
ok, may take a while...

**Comment by mpkorstanje** [comment]
Closed due to inactivity.
