### ISSUE TITLE
Set Guice inject source from command line

### ISSUE THREAD

**Issue by lcintrat** [cucumber/cucumber-jvm#881]
Hi,

Setting `guice.injector-source`property from the command line would be very handy instead of specifying it in file `cucumber-guice.properties`

Scenario:
I have a test set for several configurations involving different injector sources. For now, on the CI builder I have to overwrite the guice properties for each configuration. And the issue also exists for developers: they have to modify this property file (in Eclipse for example, with command line support, a developer might create a different run configuration per test configuration without modifying any file)

Best regards,
Ludovic

**Comment by lcintrat** [comment]
Thank you very much !
I will check this as soon as possible.

**Comment by aslakhellesoy** [comment]
You're welcome. It's already available as a snapshot: https://cucumber.io/docs/reference/jvm#snapshot-releases

**Comment by kodstark** [comment]
Here I posted how to define InjectorSource per individual testcase - http://stackoverflow.com/questions/35315963/cucumber-with-guice-multiple-guice-injector/40429150#40429150
