### ISSUE TITLE
How to use Spring DI with Lambda expressions.

### ISSUE THREAD

**Issue by sheltonn** [cucumber/cucumber-jvm#883]
If I rely on the normal Spring injection, then I will get a NPE.  I tried to inject the constructor, but Cucumber complained and said that I needed the PICO container on the classpath.  When I added the PICO container on the classpath, it started complaining about missing things.  

In my stepdefs class, I looked for the bean manually.  Does anyone have an example of Lambda expressions and Spring DI together?

My feature is as follows:

    Feature: Login
    
      @2015r16i1 @US5124
      Scenario Outline: A registered player should be able submit username and password. After submission player will be authenticated.
    
        Given my username is "<UserName>"
        And my password is "<Password>"
        When login
        Then I should receive the following authentication status "<login result>"
        Examples:
          | UserName | Password   | login result |
          | player1  | Password#1 | true         |

Here is my stepdefs file:

    package com.cdi.igp.gsi.core.cucumber;
    
    import com.cdi.igp.dao.person.Person;
    import com.cdi.igp.gsi.core.security.GsiSecurityService;
    import com.cdi.igp.gsi.models.security.GsiAuthenticatePlayerResponseModel;
    import com.cdi.igs.token.models.TokenModel;
    import cucumber.api.Scenario;
    import cucumber.api.java8.En;
    import org.springframework.context.ApplicationContext;
    import org.springframework.context.support.ClassPathXmlApplicationContext;
    
    import static org.junit.Assert.assertEquals;
    import static org.junit.Assert.assertNotSame;
    import static org.junit.Assert.fail;
    
    /**
     * Cucumber step definitions with Java8 Lamba expressions.
     * @author norris.shelton
     */
    @SuppressWarnings("unused")
    //@ContextConfiguration("classpath:/com/cdi/igp/gsi/core/cucumber/TestCucumber-context.xml")
    public class LambdaStepdefs implements En {
    
        private static LambdaStepdefs lastInstance;
    
        private String username;
        private String password;
        private GsiAuthenticatePlayerResponseModel gsiAuthenticatePlayerResponseModel;
    
        //@Autowired
        private GsiSecurityService gsiSecurityService;
    
        public LambdaStepdefs() {
            Before((Scenario scenario) -> {
                assertNotSame(this, lastInstance);
                lastInstance = this;
            });
    
            ApplicationContext context =
                new ClassPathXmlApplicationContext("/com/cdi/igp/gsi/core/cucumber/TestCucumber-context.xml");
            gsiSecurityService = context.getBean("gsiSecurityService", GsiSecurityService.class);
    
            Given("my username is \"(.*)\"", (String username) -> {
                this.username = username;
            });
    
    
            Given("my password is \"(.*)\"", (String password) -> {
                this.password = password;
            });
    
            When("login", () -> {
                try {
                    System.out.println("LOGIN");
                    gsiAuthenticatePlayerResponseModel = gsiSecurityService.authenticate(false,
                                                                                         new Person(),
                                                                                         "1",
                                                                                         new TokenModel());
                } catch (Exception e) {
                    fail(e.toString());
                }
            });
    
            //Then("I should receive the following authentication status \"(.*)\"",
            Then("^I should receive the following authentication status \"([^\"]*)\"$",
                 (Boolean authenticated) -> assertEquals(authenticated,
                                                         gsiAuthenticatePlayerResponseModel.getPlayer() != null));
        }
    }

**Comment by aslakhellesoy** [comment]
This is a bug tracker, not a help forum. Please see https://cucumber.io/support
