### ISSUE TITLE
Using cucumber-java8 list of numbers are deserialized with a String runtime type

### ISSUE THREAD

**Issue by kohanyirobert** [cucumber/cucumber-jvm#885]
Using cucumber-java8 if I have the following .feature

    Feature: List of numbers are mapped to List<Integer> when using the Java 8 Cucumber API

        Scenario: Passing some numbers to our test method
            Given the list of the following numbers: 1, 2, 3
            Then if we test the runtime type of the arguments it should be java.lang.Integer

and the following code to test it

    Given("^the list of the following numbers: (.*)$", (@Transform(IntegerListTransformer.class) List<Integer> values) -> {
        this.values = values;
    });
    Then("^if we test the runtime type of the arguments it should be java.lang.Number$", () -> {
        for (Object value : values) {
            assertThat(value, instanceOf(Number.class));
        }
    });

the test will fail with following message

    java.lang.AssertionError:
    Expected: an instance of java.lang.Number
         but: "1" is a java.lang.String

The expected is that if I have a List<Integer> then every element of the list is a Number.

Using the annotation API this worked as it should be.

Also, when I've tried to register a Transformer using the `@Transformer` annotation it didn't work, it never got called (I'm not a 100% sure, but as I remember the same stuff worked using the annotation API).

I've uploaded a runnable [Maven project][1] for easier testing.

[1]: https://gist.github.com/kohanyirobert/bd7e4bf644d7de59a994/raw/9953712d746714edd5f0805e98532bb330739066/cucumber-java8-test.zip

**Comment by bassmake** [comment]
Hello,
it looks like Transformers are not working with cucumber java8. Am I right, or is there some workaround for this?

**Comment by aslakhellesoy** [comment]
Java's reflection doesn't seem to provide the information necessary to support this. It seems impossible to get the generic type of a lambda argument.

**Comment by bassmake** [comment]
thanks for answer. Is there plan to support Java8 date-time classes in cucumber-java8?

**Comment by aslakhellesoy** [comment]
@bassmake I suggest you create a new issue for date-time support with clear code examples illustrating how you would like it to work.
