### ISSUE TITLE
DataTable.asList(clazz) doesn't call clazz' constructor

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#888]
It doesn’t seem to call the constructor, or even instanciate final fields, which is a bit of a pain.
This is probably because XStream (which we currently use for instantiation) uses some tricks like [this](http://stackoverflow.com/questions/19771375/is-it-possible-to-instantiate-a-class-without-calling-any-constructor).

If it's possible to configure XStream to always call constructors, we should do that. Otherwise, we might have to roll our own replacement for XStream (and get rid of the XStream dependency), but that could be a lot of work.

**Comment by mpkorstanje** [comment]
We're not going to fix this. We'll address this when a new data table standard library is extracted.
