### ISSUE TITLE
Support Espresso 2.2 

### ISSUE THREAD

**Issue by atali** [cucumber/cucumber-jvm#892]
Hello Guys, 

I am trying to use Cucumber with Espresso 2.2, I have seen the documentation about the previous version of Espresso and Cucumber.
https://github.com/cucumber/cucumber-jvm/tree/master/android

But I didn't manage to run cucumber with the new release of Espresso:
now they use android.support.test.runner.AndroidJUnitRunner and annotation @RunWith(AndroidJUnit4.class)

You can check 
https://code.google.com/p/android-test-kit/wiki/EspressoSetupInstructions

Any advice ?

**Comment by aslakhellesoy** [comment]
Hi @atali. Please use one of the [support channels](https://cucumber.io/support) for questions. This is a bug tracker.

**Comment by atali** [comment]
Hi @aslakhellesoy ok sorry , I'll do this ;-)
