### ISSUE TITLE
Defining several steps for the same function

### ISSUE THREAD

**Issue by javierseixas** [cucumber/cucumber-jvm#895]
Is there any way to have more than one step definition (of the same type) for the same function? Something like:

```java
@Then("^it's do something$")
@Then("^it's do another thing$")
public void this_is_my_function() throws Throwable {
    // Do something
}
```

I now that in Behat (PHP) and Specflow (C#) it is possible.

I'm getting the following error:

```
Error:(86, 5) java: cucumber.api.java.en.Then is not a repeatable annotation type
```

I found a [post](http://softwarecave.org/2014/05/20/repeating-annotations-in-java-8/) talking about a workaround for Java 7, and a solution for Java 8 using `@Repeatable`.

I tried the Java 7 approach but it doesn't work either:

```java
@Thens({
    @Then("^it's do something$")
    @Then("^it's do another thing$")
})
```

I guess I should define `@Thens` as a new annotation type, but I would like to depend only in what the library has.

Is it possible to include the `@Repetable' annotation in the code?

**Comment by aslakhellesoy** [comment]
Wouldn't multiple patterns for the same stepdef make your domain language less precise?

Can you give me a real world example of when this would be useful?

**Comment by javierseixas** [comment]
My real world example where I realised that was this:

```
@When("^it's ([a-z]+) is decreased to (\\d+)$")
@When("^it's ([a-z]+) is increased to (\\d+)$")
public void it_s_feeling_is_increased_to(String feeling, int value) throws Throwable {
    try {
        Method method = tamagotchi.getClass().getMethod(feeling);
        try {
            assertThat(method.invoke(tamagotchi), is(value));
        } catch (Exception e) {
            // ...
        }
    } catch (Exception e) {
        // ...
    }
}
```

It's a Tamagotchi game. The first parameter is a feeling (hungriness, fullness...) and the second one is a value. By introspection I call the corresponding method to get the value for this feeling. The behaviour is the same in both cases, just calling an accessor and compare to a value.

In my case I don't think it makes domain language less precise, I think is just reusability of the step functions.

**Comment by mike-rogers** [comment]
@javierseixas for this particular case you can simplify your `@When`s into:

```java
@When("^its ([a-z]+) is (?:de|in)creased to (\\d+)$")
```

That should match both (I removed the apostrophe due to general pedantry :wink:). If you're unfamiliar with the `(?:stuff)` notation it's called a 'passive' or 'non-collecting' group, and the pipe character (`|`) is an 'or', so you could read that as "match a string that starts with 'in' or 'de' and ends with 'creases', but don't collect it into an argument".

**Comment by javierseixas** [comment]
@mike-rogers thanks for your idea. I think is a good way of doing what I need.
In other hand, right now I don't have any other idea that could require to define more than one steps, so I close this issue for now.
Thanks!

**Comment by aslakhellesoy** [comment]
Good job guys. Classic [XY problem](http://xyproblem.info/) :-)
