### ISSUE TITLE
Be able to pre transform or overlay the String value of DataTable before it is converted

### ISSUE THREAD

**Issue by manat** [cucumber/cucumber-jvm#898]
Originally, I'm looking to support the needs of being able to resolve a set of values like null. For example,

``` gherkin
Given I have a list of Person, configured as follows:
  | firstName | lastName |
  | Sid       | L        |
  | Kate      | [null]   |
```

This can be translated to `List<Person>` nicely, if Person class has firstName and lastName field. However, preferred result of Kate's last name is actually expected to be `null`, not literally [null].

For a single value, this could be done with `@Transform` to convert null string ([null], null, Null, etc.) into `null`. But up to this point, `@Transform` doesn't work with `DataTable`. I'm guessing the reason `@Transform` is not applicable to DataTable because `asList`, and `asMap` already does the job through `TableConverter`. 

However, I can't seems to find a nice solution to actually solve the above scenario. So I'm thinking that it might be good to make `@Transform` applicable to DataTable, but only to do some pre-conversion, more like `List<String>` --> `List<Person>`, so that users can still benefit from the TableConverter without doing extra works, but still be able to redefine some meaning in the gherkin table. 
##### Proposed Solution

According to the current codebase, I understand that there's a code in DataTable that converts `List<DataTableRow>` into `List<List<String>>`, upon its construction. 

Would it be a good idea to apply `Transformer` class upon this process to resolve the mentioned scenario? I can submit a PR that could help illustrate this.
##### Alternative Ideas
1. Using `@Transform` may be confusing in what it actually does. Maybe something like `@Transform(pre = Transformer.class)`
2. Or may be come up with `@PreTransform`.

**Comment by lc-nyovchev** [comment]
It's weird but I also arrived at the same conclusion. It'd be really nice if @Transform works with a datatable so we can indeed pass null values, especially for places where we have multi-line datatables where one of the properties is sometimes filled in, and sometimes not. I had the problem that xStream could do UUID nicely but if I wanted to pass a null UUID in a datatable, it complained.

**Comment by manat** [comment]
Any support, or comment?

**Comment by sebrose** [comment]
Hi @manat - sorry for the long delay.

This sounds like a nice feature, but we're unlikely to get to it any time soon. If, however, you send us a PR we'd be happy to look at it.

Thanks!

**Comment by manat** [comment]
Actually I submitted PR #899 since about that time. 

Let me know what you think, thanks.

**Comment by brasmusson** [comment]
@manat I tip for you would be to reference the issue (with "`#XXX`") in the PR description instead of in the PR title, then Github picks up the reference and make it visible in the issue in question. Even better is to use [a keyword to closing issues](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) (for instance "`closes #XXX`") in the PR description, the Github will close the issue when the PR is merged.
