### ISSUE TITLE
Support for OSGi bundle resources

### ISSUE THREAD

**Issue by mdelapenya** [cucumber/cucumber-jvm#900]
At this moment, there is only support for FileResource and ZipResource, because it's expected to load those resources from a WebArchive.

If you need to use a JavaArchive (type of OSGi bundles) you want to retrieve them via bundleresource protocol.

**Comment by sebrose** [comment]
Can you create a Pull Request based on your fork?

**Comment by mdelapenya** [comment]
Hi @sebrose I'm trying to fix the error on openjdk7, as shown in TravisCI.

Any ideas why the bundle is not successfully discovering the dependencies?

And why are there less tests in jdk8 than in jdk7?

**Comment by brasmusson** [comment]
@mdelapenya The examples are examples and not tests, so they are built only on the openjdk7 build on Travis and not on the builds that release snapshots (that is the oraclejdk7 and oraclejdk8 builds on Travis).

**Comment by mdelapenya** [comment]
So if the pull is accepted then that openjdk7 with example built will be broken, that's why I'm trying to find the solution

**Comment by mdelapenya** [comment]
It passes now on OpenJDK 7, and sometimes fails on Oracle JDK 8 (https://travis-ci.org/cucumber/cucumber-jvm/builds/164570040). Others, it passes (https://travis-ci.org/cucumber/cucumber-jvm/builds/164566380)
