### ISSUE TITLE
Fail scenarios from After hook (or some equivalent)

### ISSUE THREAD

**Issue by timjwright** [cucumber/cucumber-jvm#901]
I would like to be able to fail tests from an After hook or some such thing.

An example use case would be to verify for an invarient after completion of testing. (For example I would like to check that the no exceptions have been thrown to top level exception handlers.

Another use case would be to fail a test on exceptions in shutdown of a component.

I appeciate this may feel like it goes against the grain a little in the sence that it's an implict condition which is not documented in the test case. Hoever there are a few cases when I feel this is a reasonable compromise.

**Comment by brasmusson** [comment]
@timjwright Throw an exception in the after hook, the the hook and thereby the scenario will be reported as failed.

**Comment by aslakhellesoy** [comment]
@timjwright plese use https://cucumber.io/support for questions. This is a bug tracker.

**Comment by timjwright** [comment]
Thanks actually I realised this was an ide issue. The integration with IntelliJ does not fail the tests for exceptions in after hook. Will raise a bug there instead!

Thx
