### ISSUE TITLE
Check for missing step definitions before scenario execution

### ISSUE THREAD

**Issue by Shumakriss** [cucumber/cucumber-jvm#907]
When running a feature file using the junit runner, scenarios with missing step definitions will run as far as possible which could amount to significant time with long-running tests.

**Comment by ndefeijter** [comment]
'Dry run' your test cases before you 'execute' them. Example:

/**
 * This test 'driver' does not execute the actual test cases, but does a strict
 * dry run instead. 
 * <p>
 * A dry run tests the Gherkin syntax for validity. Doing this strictly also
 * checks for all Cucumber glue code (step definitions) being available.
 */
@RunWith(Cucumber.class)
@CucumberOptions(
        plugin = { "pretty" },
        tags = { "~@ignore" }, 
        strict = true, 
        dryRun = true
)
public class RunGherkinSyntaxCheck {
}

**Comment by Shumakriss** [comment]
Ah, I should have thought of that! Are there any examples or recommendations for how to incorporate a dry-run with Maven? If not, would that be a valuable contribution?

**Comment by dkowis** [comment]
Please use the support forum on google groups: https://cucumber.io/support

I'm confident you'll be able to find an answer to your question there, this is for bugs with the software only. Thanks!

**Comment by Shumakriss** [comment]
Sure no problem, thanks!

On Mon, Nov 16, 2015 at 12:11 PM, David Kowis <notifications@github.com>
wrote:

> Please use the support forum on google groups: https://cucumber.io/support
>
> I'm confident you'll be able to find an answer to your question there,
> this is for bugs with the software only. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cucumber/cucumber-jvm/issues/907#issuecomment-157102852>
> .
>



-- 
*Chris Shumaker*
(804) 615-6669
chris.shumaker@gmail.com

**Comment by 4hiltoniattc** [comment]
I have a Cucumber project which runs fine in Netbeans but when I try to run from commandline it doesnt run.

**Comment by Rashidkhan786** [comment]
I have Cucumber script, when I have run it from cmd by Junit than it shows that *You can implement missing steps with the snippets below: *.But I have set class-path for step file.
Anybody help me.

Here is command : java -cp "D:\cucumberscript\cucumber-jars\*;D:\cucumberscript" org.junit.runner.JUnitCore cucumber1.RunTest

**Comment by mlvandijk** [comment]
@Rashidkhan786 - Please try one of the support options to get help with your question: https://cucumber.io/support
