### ISSUE TITLE
Guice package.html documentation incorrectly specifies 'cucumber-guice.properties'

### ISSUE THREAD

**Issue by jrgarlick** [cucumber/cucumber-jvm#913]
The cucumber guice package.html example describes how to incorporate your own injector and module into your Cucumber-JVM tests. At the bottom, it says, "You should create a properties file called cucumber-guice.properties' and place it in the root of the classpath." This is incorrect. The startup process never opens that file, which never activates your injector, which never binds the objects we're looking for. 

We found that the Guice startup factory tries to open a ResourceBundle called, 'cucumber,' which would map to a 'cucumber.properties' file. When we used 'cucumber.properties' as the filename, then things worked as they are supposed to.

**Comment by brasmusson** [comment]
Thanks for reporting this. The name of the properties file was changed in v1.2.4 (see [History.md](https://github.com/cucumber/cucumber-jvm/blob/master/History.md)), unfortunately the package.html was not updated.

**Comment by jakub-bochenski** [comment]
The javadoc https://cucumber.github.io/api/cucumber/jvm/javadoc/cucumber/api/guice/package-summary.html still lists the old filename
