### ISSUE TITLE
cucumber-weld cannot inject classes from src/main/java

### ISSUE THREAD

**Issue by albers** [cucumber/cucumber-jvm#915]
I want to place my application code in `src/main/java` and write specifications in `src/main/test` of the same Maven module. The domain classes should get injected into the glue code by `cucumber-weld`.

Injection only works for classes located in `src/main/test`.

Steps to reproduce:
In `cucumber-weld` sources, move `Belly.java` to `src/main/java`. The tests now fail with:

```shell
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type Belly with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private cucumber.runtime.java.weld.BellyStepdefs.belly
  at cucumber.runtime.java.weld.BellyStepdefs.belly(BellyStepdefs.java:0)

        at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:359)
        at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
        at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
        at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:155)
        at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:60)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:53)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

EDIT: you also have to move `META-INF/beans.xml` from `src/test/resources` to `src/main/resources`. Thanks @sventorben for pointing this out.

**Comment by aslakhellesoy** [comment]
I'd be happy to apply a patch for this, but the Cucumber team won't prioritise fixing this on our own.

**Comment by sventorben** [comment]
Looks like your _src/main/java_ folder is not a bean archive. Enable bean discovery by adding an empty file called _beans.xml_ to _src/main/resources/META-INF_

Weld will then scan classes in src/main/java and injection should work as expected.

**Comment by aslakhellesoy** [comment]
Would love a PR for this, demonstrating how it's done!

**Comment by sventorben** [comment]
No PR needed. I do not think this is a bug in cucumber-weld. Looks like a configuration issue with @albers application code.

For more detailed information take a look at section "What is beans.xml and why do I need it?" in [CDI FAQ](http://www.cdi-spec.org/faq/#accordion3).

**Comment by albers** [comment]
@sventorben Yo are right: following my how to reprouce instructions given above, you get a state where `beans.xml` is located in `src/test/java` whereas `Belly` is located in `src/main/java`. This is indeed a configuration issue.
The point is that injection still does not work if you also move `beans.xml` to `src/test/java`. In my understanding of CDI, a bean declared in `src/main/java` should be availale for injection in `src/test/java` of the same project if `beans.xml` is located in `src/main/java`.
I will create a PR as suggested by Aslak.

**Comment by albers** [comment]
@aslakhellesoy I created #920 to illustrate the problem.

**Comment by aslakhellesoy** [comment]
@albers what's needed to close this ticket and #920?

**Comment by albers** [comment]
cucumber-weld should be modified so that it works in the outlined setting: domain objects from `src/main/java` can be injected into glue code in `src/test/java` of the same project.

The acceptance criteria for that would be that the changes from #920 no longer break the build.

In its current state, CDI can only be used to inject objects that are defined in test scope into the glue, which is of limited use.

**Comment by aslakhellesoy** [comment]
@albers does this mean you disagree with what @sventorben said above?

**Comment by albers** [comment]
Yes, I disagree with @sventorben. This is not an issue of a missing or misplaced `beans.xml`.

**Comment by albers** [comment]
As @brasmusson pointed out in https://github.com/cucumber/cucumber-jvm/pull/920#issuecomment-148449568, this is not a defect in cucumber-weld but indeed a configuration issue as @sventorben already suggested.

Sorry for bothering you with this.

As Maven combines `src/main/java` and `src/test/java` to one classpath during the test phase, I assumed that this was also valid for Weld and that one `beans.xml` was sufficient. In fact I never encountered a project with two beans descriptors before. But with the reasoning for the existence of `beans.xml` given in the CDI FAQ, it makes sense that CDI treats both paths as distinct bean archieves.

I will post a follow-up PR that just adds a little bit of documentation about this.

Thank you for your work on cucumber-jvm.
