### ISSUE TITLE
Automatically integrate with Java

### ISSUE THREAD

**Issue by mcandre** [cucumber/cucumber-jvm#917]
Please don't require manual special configuration to integrate with Java projects. Instead, have cucumber-jvm detect which language is used, and automatically configure itself accordingly.

**Comment by aslakhellesoy** [comment]
Can you be more specific what you mean? What special configuration are you referring to?

**Comment by mcandre** [comment]
Each of these:

https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-gradle#caveats

**Comment by aslakhellesoy** [comment]
You seem to be referring to some example gradle script here, which isn't really part of the Cucumber-JVM codebase.

What exactly are you suggesting instead?

**Comment by mcandre** [comment]
That Cucumber simply supports normal, expected Java project behavior out of the box, with no manual configuration required.

**Comment by aslakhellesoy** [comment]
Can you give me a concrete example of what "normal, expected Java project behaviour" means to you?

**Comment by aslakhellesoy** [comment]
It's still not clear to me what "manual configuration" you are referring to. You've posted a link to a document that has both examples of Gradle configuration and Cucumber configuration. The only Cucumber-specific configuration I can see is the command line options, which are passed from Gradle to Cucumber:

```
args = ['-f', 'pretty', '--glue', 'gradle.cucumber', 'src/test/resources']
```

Are you suggesting that some of this should be removed? If so, what exactly?

**Comment by dkowis** [comment]
Dude, you can just use a JUnit runner. See: https://github.com/cucumber/cucumber-jvm/blob/master/examples/java-calculator/src/test/java/cucumber/examples/java/calculator/RunCukesTest.java

No additional "manual" configuration required, at least at the project level.

**Comment by mcandre** [comment]
Ah, I just had to find a more basic example!

https://github.com/mcandre/hello-kafka
