### ISSUE TITLE
java8: Use Consumer instead of HookBody and StepdefBody

### ISSUE THREAD

**Issue by mhfrantz** [cucumber/cucumber-jvm#918]
In order to compose with API's such as Durian's `Errors`, the proprietary `HookBody` and `StepdefBody` should be replaced with `java.util.function.Consumer`.  This would allow use of Durian to work around step bodies that contain checked exceptions.
```
Given("^a step with a string argument \"(.*)\"$",
        Errors.rethrow().wrap(
                (final String arg) -> { ... throw new Exception("this might happen"); ... }));
```

**Comment by aslakhellesoy** [comment]
Sounds like a good idea. Send a PR?

**Comment by mhfrantz** [comment]
Attempt to fix failed.  Reopen if there are better ideas.
