### ISSUE TITLE
Cucumber JSON reports embeddings new parameter "name"

### ISSUE THREAD

**Issue by MatWisz** [cucumber/cucumber-jvm#926]
I'd like to be able the obtain in the JSON report file inside embedding object additional object which storing name of attached embedding.

I see this as another parameter of method `embed()` in `Scenario` interface:

``` Java
void embed(String name, byte[] data, String mimeType);
```

And adding a new parameter `"name"` inside `"embedding"` object in JSON report

``` JSON
{
"name": "test image", 
"mime_type": "image/png",
"data": "test data"
}
```

**Comment by lcintrat** [comment]
+1

**Comment by tommywo** [comment]
+1

**Comment by mlvandijk** [comment]
It's not quite as simple as described above, as changing the method in the interface Scenario also alters the contract provided by the interface. The parameter has to be added in multiple places.
As this will be a breaking change, it would have to be part of a next major release.

**Comment by karltiirik** [comment]
This issue seems to be still unsolved (checked version 3.0.2)

**Comment by mpkorstanje** [comment]
> ### How soon will my ticket be fixed? ###
> 
> The best way to have a bug fixed or feature request implemented is to fork the cucumber-jvm repo and send a pull request. If the pull request has good tests and follows the coding conventions (see below) it has a good chance of making it into the next release.

You're welcome to help out.
