### ISSUE TITLE
Cucumber+JVM+eclipse+maven :  zh-CN ( chinese language feature ) not working

### ISSUE THREAD

**Issue by apydmarri** [cucumber/cucumber-jvm#927]
Hello all,

we are trying to write cucumber using Chinese language.

below is the code which we are trying in 

# language: zh-CN
#功能: 测试 

	场景: 注册负方案
	 鉴于    一世      开放 "https://accounts.coursera.org/signup" 网址 在 该 浏览器

we have step-implemetations also but we are facing issues in cucumber script itself as it is not able to identify Chinese language. below are the screen shots

![screenshot2](https://cloud.githubusercontent.com/assets/15264685/10693923/02bbdf5c-79b9-11e5-8d86-1882ed179181.png)
![screenshots1](https://cloud.githubusercontent.com/assets/15264685/10693924/02c0a2bc-79b9-11e5-857a-f45a0d8d5270.png)

can some one help us in setting up cucumber+JVM in eclipse which supports Chinese language

**Comment by aslakhellesoy** [comment]
Not a bug. See https://github.com/cucumber/cucumber-java-skeleton/commit/5783b99f8509868f70eedd80afedc8f74132471b
