### ISSUE TITLE
When using DataTables use the parameter name to map on the table also as java param name

### ISSUE THREAD

**Issue by tomdw** [cucumber/cucumber-jvm#930]
Using datatables has, e.g.

Given a patient that is registered with a length <length> cm and weight <weight> gr
When I ask for the details of the patient
Then the bmi <bmi> is given rounded to two digits

|length |weight |bmi    |
|160     |64000 |25.39 |

Then why is the syntax of the generated method still using arg1, arg2 instead of more readable 'length' and 'weight'?

**Comment by etlapa** [comment]
You need to change the RegExp and the method signature of your method manually. By default is created as you describe (two int params). Try something like:

@Then("^the bmi (\\d*.\\d*) is given rounded to two digits$")
public void the_bmi_is_given_rounded_to_two_digits(String bmi) throws Throwable {
//your code
}

If not works, try the regExp in sites like:
https://regex101.com/

To get the best regExp for your case.

**Comment by tomdw** [comment]
This change request is to automatically generate the correct name of the
java parameter based on the name given between < and > in the feature
description in my example given . Would make cucumber better. All info is
in place to do this.

Op woensdag 4 november 2015 heeft etlapa <notifications@github.com> het
volgende geschreven:
