### ISSUE TITLE
[Q] Is it possible to parse DataDable to nested object?

### ISSUE THREAD

**Issue by bademux** [cucumber/cucumber-jvm#931]
subj: Is it possible to declare properties in "dot notation"?
eg.:

``` gerkin
      | testProp | testPropNested.quota|
      |  qwerty  |         1234        |
```

**Comment by mpkorstanje** [comment]
No this is not possible. And while this question is ages old. Future questions are best directed to the [Mailing List, Slack or Gitter](https://cucumber.io/support).
