### ISSUE TITLE
Is it possible to generate json report with different file names?

### ISSUE THREAD

**Issue by saikrishna321** [cucumber/cucumber-jvm#932]
Hi Guys,

I'm looking for a way to generate json reports with different file names, as i'm my tests in parallel.

Runner code looks like below, i need the cucumber.json file name to be the feature file name. I use Cucumber-JVM with Maven

```
@RunWith(Cucumber.class)
@CucumberOptions(strict = false, features = "features", format = { "pretty",
		"html:target/site/cucumber-pretty",
		"json:target/cucumber.json" }, tags = { "~@ignore" })
public class RunBDD {

}

```

**Comment by saikrishna321** [comment]
@aslakhellesoy can you please help me on this ?

**Comment by dkowis** [comment]
This isn't a support forum. This is only used for bugs in the software.

Please use the cucumber Google group or one of the other options listed here: https://cucumber.io/support
