### ISSUE TITLE
A single failure is duplicated in the failsafe output

### ISSUE THREAD

**Issue by jlorenzen** [cucumber/cucumber-jvm#935]
It appears when using the maven-failsafe-plugin along with cucumber-jvm that a single failed Scenario is reported twice in the maven output. Is that expected? I've intentionally setup one test to fail, and when running `mvn clean verify`, the failure is reported twice and it appears I have two failures instead of one. I've attached all the output below.

<img width="564" alt="screen shot 2015-11-25 at 9 34 44 am" src="https://cloud.githubusercontent.com/assets/107843/11401358/d24e30c8-9357-11e5-815d-2ab5ad77cb04.png">

maven v3.2.1
maven-failsafe-plugin v2.18
cucumber-jvm v1.2.2
using cucumber-java, cucumber-spring, and cucumber-junit

[maven-failsafe-cucumber.txt](https://github.com/cucumber/cucumber-jvm/files/44028/maven-failsafe-cucumber.txt)

**Comment by mcrmfc** [comment]
I am guessing this is related to #263

**Comment by mpkorstanje** [comment]
This will be fixed with #1135. Provided you pass `--no-step-notifications`
