### ISSUE TITLE
Unique Description identifier

### ISSUE THREAD

**Issue by clicman** [cucumber/cucumber-jvm#959]
Hello! I`m allure-cucumver-jvm-adaptor developer. And I have various problems with scenarios and steps locating in my listener (for example https://github.com/allure-framework/allure-cucumber-jvm-adaptor/issues/25). So my suggestion is transparently add annotation to each description with some UUID. It wil help uniquely locate description placement in junit objects hierarchy.

@aslakhellesoy It will acceptable? If it so, I will create pull request

.

**Comment by brasmusson** [comment]
As the `org.junit.runner.Description`:s created for the examples scenarios from an scenario outline are unique even though they might have the same display name (by the use of the [`createSuiteDescription`](https://github.com/cucumber/cucumber-jvm/blob/master/junit/src/main/java/cucumber/runtime/junit/ExecutionUnitRunner.java#L51) added [specifically for Cucumber-JVM](https://github.com/junit-team/junit/pull/405/files)), I'm not convinced another UUID is necessary to uniquely locate their placement in the junit object hierarchy.

**Comment by clicman** [comment]
I`ve updated junit to 4.12 and i see, now fUniqueId is not null. But it still not equal for my comparsion.
I compare fUniqueId from Description which comes as parameter to testStarted in my listener and fUniqueId from Description which comes as parameter to testRunStarted (found it in object hierarchy).
As I see in debugger both objects looks same, but .equals method leadt to FALS for these fUniqueId`s.

**Comment by brasmusson** [comment]
I cannot find a problem here. I can ([on a branch](https://github.com/cucumber/cucumber-jvm/compare/check-unique-junit-descriptions)) show that the [Descriptions of example scenarios may have the same display name, but are not equal](https://github.com/cucumber/cucumber-jvm/blob/check-unique-junit-descriptions/junit/src/test/java/cucumber/runtime/junit/ExamplesRunnerTest.java#L35-L36), and that [each Description received in testStarted can be found in the hierarchy of Descritions received in testRunStarted](https://github.com/cucumber/cucumber-jvm/blob/check-unique-junit-descriptions/junit/src/main/java/cucumber/runtime/junit/SanityChecker2.java#L61-L111) (the most comprehensive checking of the notification from Cucumber-JVM JUnit runner have for some reason been made in the test of the picocontainer module, so I reused the tests there - [see the logs on Travis](https://travis-ci.org/cucumber/cucumber-jvm/jobs/107638108#L4734))

**Comment by clicman** [comment]
Thank you for example. Now I found the problem. It happens when listener SanityChecker2 connects via po pom.xml as surefire-plugin parameter. (I`ve moved listener to picoconatiner project for easy debug)
```
           <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <properties>
                        <property>
                            <name>listener</name>
                            <value>cucumber.api.picocontainer.SanityChecker2</value>
                        </property>
                    </properties>
                </configuration>
            </plugin>
```

Now if you run RunCukesTest.java you`ll see what step description fUniqueId ill not equals it`s mirror in suiteDescription

So loks like it`s surefire plugin issue. I`ve trined surefire 2.19.1 plugin version and here good and bad news: now fUniqueId equals but it comes with broken root Description (wit ho childs) on testRunStarted

**Comment by aslakhellesoy** [comment]
From what I can tell this is not a Cucumber bug then
