### ISSUE TITLE
Test output logs incorrect when running Cucumber feature files in parallel

### ISSUE THREAD

**Issue by mpalki-cabcat** [cucumber/cucumber-jvm#966]
When the following surefire plugin config is used
```
<threadCount>2</threadCount>
<parallel>classes</parallel>
<redirectTestOutputToFile>true</redirectTestOutputToFile>
```
then the output from the tests is partially directed to the 'xxxtest-output.txt file and partially to stdout.  At first I thought this was a surefire plugin bug and filed this ticket (https://issues.apache.org/jira/browse/SUREFIRE-1230). The ticket has steps to reproduce the issue. 

However, I debugged the issue a bit and found that when I run cukes, the JUnit4RunListener.testStarted method in Surefire is called after each step definition (i.e test) is executed.  When I run plain junit based unittests, that method is called before test is executed. This is the correct behaviour, i.e the 'testStarted' method should be called prior to the test. 
Surefire sets the logger inside the 'testStarted' method. Since Cucumber calls this after running the tests, the logs are redirected partially to stdout and partially to the file.

**Comment by mpalki-cabcat** [comment]
Versions used
1. cucumber-java - 1.2.4
2. maven surefire - 2.19.1

**Comment by brasmusson** [comment]
With #1002 the requested behaviour can be achieved with the option `--junit,--allow-started-ignored`. The reason for not always firing the `testStarted` before the execution of a step definitions, is that in case of pending and undefined steps (which in non-strict mode are mapped to the JUnit status skipped), then the listener would receive a `testStarted` followed by a `testIgnored`, which (some?, many?) JUnit listeners misbehave for. Standard JUnit test either fire a `testStarted` followed by a `testFinished` (with an optional failure in between), or only a `testIgnored`. #1002 made this behaviour configurable, but did not change the default behaviour.
