### ISSUE TITLE
Support for Android Instrumentation

### ISSUE THREAD

**Issue by SowmiaS** [cucumber/cucumber-jvm#968]
Any answer to this question:
http://stackoverflow.com/questions/35607500/android-unit-testing-cucumber-jvm-android-instrumentation

**Comment by SowmiaS** [comment]
Support for Android Junit Rules!!!!! Can anyone give idea how I can solve this problm

**Comment by SierraGolf** [comment]
since junit `@Rule`s are basically just a modularisation of `@Before` and `@After` logic, I think this issue duplicates #894.

sadly the original creator of that issue did not answer my last question. if you can give some more inside why such a rule would be necessary and how you would use it please do that on the other issue and close this one.

**Comment by audriusKV** [comment]
This is important issue for Android. Before was 'more' options to avoid `@Rule` annotations (e.g. `ActivityInstrumentationTestCase2`). But it is officially deprecated.
Android testing framework moving towards `Rules` approach. All new functionalities are based on this. [ProviderTestRule](https://developer.android.com/reference/android/support/test/rule/provider/ProviderTestRule.html), [GrantPermissionRule](https://developer.android.com/reference/android/support/test/rule/GrantPermissionRule.html), all Room testing tools.
It is harder and harder to have Cucumber tests run on Android.

**Comment by mpkorstanje** [comment]
The `cucumber-junit` runner supports `@ClassRule` which will be invoked around the execution of the suite of features. If you need to use it around scenario's you could perhaps create a PR to add this functionality to `cucumber-junit`.

**Comment by idulkin** [comment]
This is now more relevant with the release of the Android test support library 1.0. TestOrchestrator is a very useful tool that needs AndroidJUnitRunner as its instrumentation.

**Comment by audriusKV** [comment]
Bot, be more understanding please. This is very important issue for cucumber on android platform.

**Comment by ajsviado** [comment]
I was able to manually apply the GrantPermissionRule by adding the following snippet on the @Before method of my class.

PermissionRequester requester = new PermissionRequester();
requester.addPermissions(Manifest.permission.GET_ACCOUNTS);
requester.requestPermissions();

i hope this helps.

**Comment by Hsilgos** [comment]
> PermissionRequester requester = new PermissionRequester();
> requester.addPermissions(Manifest.permission.GET_ACCOUNTS);
> requester.requestPermissions();

In general it works, but not for all cases. 
For example it works in this case:

ActivityTestRule<MyActivity> activityTestRule = new ActivityTestRule<>(MyActivity.class);
activityTestRule.launchActivity(null);

But not in this case:

ActivityTestRule<MyActivity> activityTestRule = new ActivityTestRule<>(new SingleActivityFactory<MyActivity>(MyActivity.class) {
            @Override
            protected EmptyMapActivity create(Intent intent) {
                return new MyActivity();
            }
        }, true, false);
activityTestRule.launchActivity(null);

The reason: ActivityTestRule (as any other rule) has overriden method 'public Statement apply(final Statement base, Description description)' which is triggered automatically before tests
