### ISSUE TITLE
 Could not generate test report because of outline examples

### ISSUE THREAD

**Issue by L3K0V** [cucumber/cucumber-jvm#972]
I have following scenario outline with examples:

```
Scenario Outline: Example sale with adjustment
      Given fiscal device in normal state
      When open fiscal receipt with operator 1 and password "0000"
      And user try to sell <text> for $0.99 single price in Tax group "A" with quantity of 2 with adjustment <type> of <value>
      Examples:
        | text                 | type                      | value |
        | "discount by perc"   | "DISCOUNT_BY_PERCENTAGE"  | 10.0  |
        | "discount by value"  | "DISCOUNT_BY_SUM"         | 0.10  |
        | "surcharge by perc"  | "SURCHARGE_BY_PERCENTAGE" | 10.0  |
        | "surcharge by value" | "SURCHARGE_BY_SUM"        | 0.10  |
```

and defined test class as follow:

```
@RunWith(Cucumber.class)
@CucumberOptions(
        plugin = {"pretty", "html:target/cucumber-html-report"},
        features = "src/test/resources/"
)
public class SalesTest {

}
```

Then my build failed because of:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':devices:test'.
> Could not generate test report to 'D:\Intellij\DatecsFiscalFramework\devices\build\reports\tests'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.053 secs
D:\Intellij\DatecsFiscalFramework\devices\build\reports\tests\packages\| "discount by perc" | "DISCOUNT_BY_PERCENTAGE" | 10.html (The filename, directory name, or volume label syntax is incorrect)
16:08:25: External task execution finished 'build'.

```

I saw there was and --expand option but my project is configured with 1.2.4. How can make my build not failing and optionally to have successfully generated report.

```
dependencies {
    ...
    testCompile 'info.cukes:cucumber-java:1.2.4'
    testCompile 'info.cukes:cucumber-junit:1.2.4'
    testCompile 'junit:junit:4.12'
}
```

I'm on windows.
Thanks.

**Comment by OanaPasnicu** [comment]
Could you give more information and sample how you have defined the ':devices:test' task?

**Comment by mrduguo** [comment]
It happens to me as well on Windows due to the generated step name contain illegal windows characters with root cause:
`Caused by: java.io.FileNotFoundException: ...\github\mrduguo\gradle-sample-cucumber\build\reports\tests\packages\| 127.0.0.html (The filename, directory name, o
r volume label syntax is incorrect)
        at org.gradle.internal.IoActions$TextFileWriterIoAction.execute(IoActions.java:108)
        ... 77 more
`

**Comment by mrduguo** [comment]
Found related discussion: only fail if the outline value contain DOT
http://stackoverflow.com/questions/25174141/could-not-generate-test-report-in-gradle-due-to-cucumber-step-syntax

**Comment by mrduguo** [comment]
Created sample project [gradle-cucumber-jvm-issue-972](https://github.com/mrduguo/gradle-cucumber-jvm-issue-972) to reproduce:
```
git clone https://github.com/mrduguo/gradle-cucumber-jvm-issue-972.git

./gradlew
```

**Comment by RohitVerma0123** [comment]
I am not able to generate cucumber reports , I have added plugin ={"html:target/cucumber-html-report"} to my test runner file but when I run this using TestRunner file , It gives me only Reports.js file under target folder , Index.HTML file was missing from the folder , Only reprts.js file was there

Please help !!

![image](https://user-images.githubusercontent.com/33117203/33420059-25f27c4c-d5d3-11e7-8e4b-a77085fb4598.png)

**Comment by brasmusson** [comment]
@RohitVerma0123 This is an issue tracker, please ask for help in a [support forum](https://cucumber.io/support).

**Comment by mlvandijk** [comment]
@AnilKumar345 This is an issue tracker. Please ask for help in a [support forum](https://cucumber.io/support). Also, please provide additional information (i.e. which version of Cucumber do you use, what is the code of your runner?)

**Comment by AnilKumar345** [comment]
Thanks for your reply

I am using the following dependencies, Can you please suggest me which version is supports all the cucumber functionalities?

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.1.5</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-jvm</artifactId>
			<version>1.2.5</version>
			<type>pom</type>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.1.5</version>
			<scope>test</scope>
		</dependency>
	
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-jvm-deps</artifactId>
			<version>1.0.5</version>
		</dependency>
		
		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>1.0.0</version>
		</dependency>
		
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>gherkin</artifactId>
			<version>2.12.2</version>
		</dependency>

**Comment by mlvandijk** [comment]
@AnilKumar345 Please find installation info in the [docs](https://docs.cucumber.io/installation/java/)
