### ISSUE TITLE
How to transfer testng parameters from "BeforeClass" method to "Before" method?

### ISSUE THREAD

**Issue by tcwmj** [cucumber/cucumber-jvm#977]
I have my XXXTestNGRunner extends AbstractTestNGCucumberTests, and it has a methods annotated with "BeforeClass" which will get parameters from TestNG XML configuration file, 
like this:
@BeforeClass
    @Parameters({"os", "os_version", "browser", "browser_version", "resolution"})
    protected void beforeClass(ITestContext testContext, @Optional String os, @Optional String os_version, @Optional String browser, @Optional String browser_version, @Optional String resolution) 

I use PicoContainer as DI in my project, and with a ContextStep class to do setup and tear down with @Before and @After, other StepDefinitons classes shares the ContextStep objects state, such as webdriver, scenario in it.

At present, I hope transfer those parameters' value from @BeforeClass to @Before method so as to create kinds of Webdriver instance for different TestNGRunner, is that possible?

**Comment by dkowis** [comment]
This isn't a support forum, but instead for bugs oft the software. 

I recommend asking on the cucumber google groups, or one of the other methods listed here: https://cucumber.io/support
