### ISSUE TITLE
@Before and @After hook order comparison susceptible to underflow

### ISSUE THREAD

**Issue by auno** [cucumber/cucumber-jvm#985]
If two @Before hooks are created with a great enough difference (i.e. greater than 2^31), they may be executed in the incorrect order due to an arithmetic underflow in HookComparator.

**Comment by aslakhellesoy** [comment]
Why is this a problem? How many hooks do you have? Feel free to submit a fix if this is a problem for you.

**Comment by aslakhellesoy** [comment]
Just spotted the PR - thanks!

**Comment by auno** [comment]
You don't need that many. My scenario is that I have one @Before hook that I want to always run first, so to guard against future bugs I give it `order = Integer.MIN_VALUE`. This combined with another @Before hook with the default order of 10000 triggers this.
