### ISSUE TITLE
Support to define execution order of feature files in cucumberconfig file 

### ISSUE THREAD

**Issue by mannejkumar** [cucumber/cucumber-jvm#988]
It will be very useful if we have options to define the execution order of feature files.

**Comment by aslakhellesoy** [comment]
We'll never add this I'm afraid. It's an old debate and our firm stance is that scenarios should be independent.

**Comment by yvolk** [comment]
@aslakhellesoy It appears that Cucumber core acts differently: it imposes voluntary chosen order of features, explicitly listed e.g in CucumberOptions annotation.
In cucmber.runtime.model.CucumberFeature#load it sorts the provided lists of features using CucumberFeatureUriComparator
This hardcoded sorting effectively makes tested features dependent on this order, making it hard even to test, if features are actually independent. Please remove this sorting or at least add an option to skip sorting.

?!
