### ISSUE TITLE
Lazy loading feature file and running (JUnit or TestNG Runner)

### ISSUE THREAD

**Issue by stanislav-antufeev** [cucumber/cucumber-jvm#989]
I am facing the problem with running huge number of feature files, around 10,000. Some of them contains multiple scenarios (more than 5)and i am getting OutOfMemory error on ~1200 executed feature files. As I understand how JUnit and TestNG runner classes have been implemented, they are both loading all given feature file into memory and parsing using Gerkhin library. Current implementation of JUnit and TestNG feature runners has such limitation.
I found that TestNG framework has a special type of DataProvider which returns Iterator<Resource>.
I prepared some implementation of additional TestNG Runner class with lazy loading and running feature one by one.

**Comment by stanislav-antufeev** [comment]
Could you please verify my commit. I can understand that it is not common case but an issue is exist and should be fixed or as I created a separate solution to run huge amount of feature files.

**Comment by aslakhellesoy** [comment]
Please create a pull request. Our CI will then verify it automatically.

**Comment by stanislav-antufeev** [comment]
I am already created and closed. I was confused by GIT Hub process of pull request a bit. @aslakhellesoy Are you seeing my pull request ?

**Comment by aslakhellesoy** [comment]
Yes, I can see #991 thanks

**Comment by stanislav-antufeev** [comment]
Closing issue because feature is implemented not completely.
