### ISSUE TITLE
Cucumber TestNG reporting

### ISSUE THREAD

**Issue by mikejramsey56** [cucumber/cucumber-jvm#996]
I know that this issue has been discussed but I cannot get a satisfactory resolution.  I don't want to create a test runner for each feature file and I want a scenario to map to a TestNG '@Test.'.  The root of the problem is that TestNG wants to know the Scenario name in @BeforeClass but cucumber doesn't make the scenario name available until its @Before which runs as part of @Test.

TestNG wants to know all the test names in advance while cucumber feeds them to us as the test is executed.  Strikes me that this problem could be cracked if cucumber provided an API which returned a list of all the scenarios to be run in execution order. Failing that, an API that can be invoked in the TestNG @BeforeClass (via a Listener) that returns the next scenario to be executed.

**Comment by FrankS77** [comment]
I ran into the same problem.

**Comment by brasmusson** [comment]
Duplicate of #1113.

**Comment by mikejramsey56** [comment]
Closing as duplicate.
