### ISSUE TITLE
HTML report cannot be displayed when incomplete

### ISSUE THREAD

**Issue by RichardBradley** [cucumber/cucumber-jvm#997]
The HTML report is written to "report.js" as the test run progresses, but the javascript preamble contains a function opening brace:

```
$(document).ready(function() {var formatter = new CucumberHTML.DOMFormatter($('.cucumber-report'));
```

(see [the relevant code](https://github.com/cucumber/cucumber-jvm/blob/0aecc4d3e4c15fc34b63f848043deba2c230e35f/core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java#L58)).

This means that if the test run is aborted (for example, manually after a failure has been noticed by an impatient developer), or if the test run is still in progress then the HTML report cannot be displayed at all in a browser, giving the following error:

```
report.js:5905 Uncaught SyntaxError: Unexpected end of input
```

It would be nice if this restriction were lifted so that partial reports could still be displayed in a browser.

Given the order of the javascript `<script>` tags in `index.html`, I think that the `$(document).ready` call is unnecssary, and simply removing that might suffice. 

It might be nice to give some UI indication that the report is incomplete (either due to being aborted or due to being still in progress; the javascript is unlikely to be able to distinguish the two), but perhaps not necessary.

**Comment by mpkorstanje** [comment]
We are not going to fix this. However you may want to look at this project https://github.com/damianszczepanik/cucumber-reporting. You can either use the maven or jenkins plugin .
