### ISSUE TITLE
classpath:features also runs features from dependencies

### ISSUE THREAD

**Issue by JWGmeligMeyling** [cucumber/cucumber-jvm#999]
`classpath:features` also runs the features in the resources of (test) dependencies. This is inconsistent with for example JUnit, that does not run the testcases from classes in the classpath from transitive dependencies.

**Comment by RichardBradley** [comment]
(By convention, Java JARs should not include test resources, so this is arguably a bug or misbehaviour by the dependencies that have published their feature files. This does sound like a sensible fix though.)

**Comment by JWGmeligMeyling** [comment]
In a common scenario, you do not include the test-jar, agreed. But sometimes you do, for example when you want to share test modules or custom mock classes. And in this cases JUnit does not run the testcases from that dependency, even though the classes are on the classpath. But Cucumber runs the features from the dependencies. This is inconsistent with JUnit, and in my opinion the behaviour of JUnit is preferred here.

**Comment by RichardBradley** [comment]
(When you want to share test modules or custom mock classes, the correct approach would be to publish a "`myproject-test`" jar which has the classes needed in its `src/main` dir, rather than publishing your `src/test` dir. As you say, JUnit's approach is more forgiving though.)

**Comment by JWGmeligMeyling** [comment]
Closing this as I feel both options have their own quirks, and sharing the features may also be useful in some ways as well.
